### ISSUE TITLE
Failed to push image (i can login and create project named newtest in webUI)

### ISSUE THREAD

**Issue by ghoul008** [vmware/harbor#100]
I can login by docker client (all in same machine),but can not push image.

[root@registry]# docker push newtest/shaozp-hello-world:latest
The push refers to a repository [docker.io/newtest/shaozp-hello-world]
Repository does not exist: newtest/shaozp-hello-world

[root@registry]# docker push localhost:newtest/shaozp-hello-world:latest
Error parsing reference: "localhost:newtest/shaozp-hello-world:latest" is not a valid repository/tag

what's wrong?

**Comment by ghoul008** [comment]
/data/database
/data/registry
By the way , what's mean the two directory
[root@ registry]# ll /data/registry/
total 0
is it normal?

**Comment by wknet123** [comment]
It may caused by you've not created a project as which should named 'newtest' in UI before pushing images with docker client.

**Comment by wknet123** [comment]
The volumes mounted on host by the parameter '-v'

**Comment by wknet123** [comment]
BTW, your tag name written in push command seems not right. The first one, you were missing the URL that will push onto the Docker Hub by default, and the second one, 'localhost' is not a recommended, you should assign an IP address as 'eth0' of your host.

**Comment by ghoul008** [comment]
【1】I already created a project named "newtest" before pushing images with docker client.(my docker client and docker server on same machine)
【2】"The volumes mounted on host by the parameter '-v'"  what's this mean?
【3】the right way for push some image to my registry format like what? i see in some where you say that is like this     docker push [project_name]/[repository_name]:[tag]  
【4】 “Repository does not exist: newtest/shaozp-hello-world” what‘s this error mean , where can i find it。

**Comment by ghoul008** [comment]
i try to do it like this ,but get another error 
[root@harbor]# docker push reg.mydomain.com:newtest/shaozp-hello-world
Error parsing reference: "reg.mydomain.com:newtest/shaozp-hello-world" is not a valid repository/tag
[root@ harbor]# docker push reg.mydomain.com:newtest/shaozp-hello-world:latest
Error parsing reference: "reg.mydomain.com:newtest/shaozp-hello-world:latest" is not a valid repository/tag


ip reg.mydomain.com already add in /etc/hosts ,i can login like this 
[root@harbor]# docker login reg.mydomain.com
Username (admin):

**Comment by wknet123** [comment]
'reg.mydomain.com' is just a placeholder for you to replace with your practical IP address of your host.

**Comment by wknet123** [comment]
You should write the push command URL like this, 'reg.mydomain.com/newtest/shaozp-hello-world:latest'

**Comment by ghoul008** [comment]
[root@ ~]# docker push reg.mydomain.com/newtest/shaozp-hello-world:latest
The push refers to a repository [reg.mydomain.com/newtest/shaozp-hello-world]
Repository does not exist: reg.mydomain.com/newtest/shaozp-hello-world

same error,when is the "Repository" be created?

**Comment by wknet123** [comment]
Please confirm the image tagged `reg.mydomain.com/newtest/shaozp-hello-world:latest` existing on your host.

**Comment by ghoul008** [comment]
[root@~]# docker images 
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
harbor_mysql         latest              9b7ccec63b77        26 hours ago        324.1 MB
harbor_ui            latest              ee6d533b4d36        27 hours ago        231.6 MB
harbor_log           latest              cf02c7bab9e4        27 hours ago        187.9 MB
ubuntu               14.04               b549a9959a66        6 days ago          187.9 MB
nginx                1.9                 eb4a127a1188        7 days ago          182.6 MB
mysql                latest              e78ddcc15639        8 days ago          361.1 MB
mysql                5.6                 9a26fdc248f4        8 days ago          324.1 MB
registry             2.3.0               5eaced67751b        5 weeks ago         165.7 MB
bydga/portus         latest              095f5913026d        7 weeks ago         1.14 GB
hello-world          latest              690ed74de00f        6 months ago        960 B
shaozp-hello-world   latest              690ed74de00f        6 months ago        960 B

**Comment by wknet123** [comment]
You should first tag `shaozp-hello-world:latest` as `newtest/shaozp-hello-world:lastest`, then execute  `docker push reg.mydomain.com/newtest/shaozp-hello-world:latest`.

**Comment by ghoul008** [comment]
[root@ ~]# docker tag 690ed74de00f newtest/shaozp-hello-world
[root@ ~]# docker images
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
harbor_mysql                 latest              9b7ccec63b77        27 hours ago        324.1 MB
harbor_ui                    latest              ee6d533b4d36        27 hours ago        231.6 MB
harbor_log                   latest              cf02c7bab9e4        27 hours ago        187.9 MB
ubuntu                       14.04               b549a9959a66        6 days ago          187.9 MB
nginx                        1.9                 eb4a127a1188        7 days ago          182.6 MB
mysql                        latest              e78ddcc15639        8 days ago          361.1 MB
mysql                        5.6                 9a26fdc248f4        8 days ago          324.1 MB
registry                     2.3.0               5eaced67751b        5 weeks ago         165.7 MB
bydga/portus                 latest              095f5913026d        7 weeks ago         1.14 GB
hello-world                  latest              690ed74de00f        6 months ago        960 B
newtest/shaozp-hello-world   latest              690ed74de00f        6 months ago        960 B
shaozp-hello-world           latest              690ed74de00f        6 months ago        960 B
[root@ ~]# docker push reg.mydomain.com/newtest/shaozp-hello-world:latest
The push refers to a repository [reg.mydomain.com/newtest/shaozp-hello-world]
Repository does not exist: reg.mydomain.com/newtest/shaozp-hello-world

**Comment by wknet123** [comment]
Tagged as `reg.mydomain.com/newtest/shaozp-hello-world:latest`

**Comment by ghoul008** [comment]
OMG thank U !!!!!!!!!
good job!!
i shoud learn more docker knowledge!
