### ISSUE TITLE
Provide more explicit description of the attributes on both .ova and doc.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#1001]
There are quite a few confusing attributes on .ova.

Some are only effective when first bootstrap.   (root password)
Some can not be changed after setup.(auth mode)
Some has dependencies( email, self_registration ... depend on auth mode)

If we can not figure out how to reflect that on .ova we need to add description in .ova and document the limitations, to less confuse the .ova users.

**Comment by ywk253100** [comment]
Fixed by #1123 .
