### ISSUE TITLE
Enhancement: Option to turn-off "My Projects"

### ISSUE THREAD

**Issue by gondor** [vmware/harbor#1004]
In our organization we don't want users to be able to create Projects.   Ideally this should be role based but at the minimum it would nice to turn off this feature altogether.

Have there been any thoughts to offer a flag for this screen?  Right now I have been modifying the `project.htm` and `repositories.htm` to exclude it by commenting that span/a out.

**Comment by reasonerjt** [comment]
We have plan to add a flag and when it's set only admin can add project, but no ETA yet.

**Comment by reasonerjt** [comment]
The fix will be merged to master soon, it's controlled by attribute: "project_creation_restriction" see harbor.cfg for details, doc will be updated accordingly this week.
