### ISSUE TITLE
Remove user management from harbor if the auth mode is `ldap_auth`

### ISSUE THREAD

**Issue by int32bit** [vmware/harbor#101]
We verify a user's credentials against our LDAP server. We find it can't be synchronized with our LDAP server(In fact, permission deny) when we delete an user  through the WebUI of harbor. What's worse, we can't recover the deleted user unless re-deploy entire project as well as clean all data in database.

In my opinion, user management can be removed from harbor if the auth mode is `ladp_auth`, which can be exactly taken over by LDAP server.

**Comment by wknet123** [comment]
Thanks. I accept your opinion, and we'll refine the current user management workflow in the future release.

**Comment by hainingzhang** [comment]
completed.
