### ISSUE TITLE
Harbor and Notary

### ISSUE THREAD

**Issue by rikatz** [vmware/harbor#1012]
I've been testing some of Docker Notary, with Vmware Harbor.

As those are separate and different components that can work independently, when I try to integrate the Notary Authentication with Registry I get an unauthorized error.

The following is my 'Notary' config. Note that I've copied the root.crt certificate from the 'registry' to the Notary Server config directory, naming it as token.crt:

```
{
        "server": {
                "http_addr": ":4443",
                "tls_key_file": "./192.168.1.34.key",
                "tls_cert_file": "./192.168.1.34.crt"
        },
        "trust_service": {
          "type": "remote",
          "hostname": "notarysigner",
          "port": "7899",
          "tls_ca_file": "./ca.crt",
          "key_algorithm": "ecdsa",
          "tls_client_cert": "./192.168.1.34.crt",
          "tls_client_key": "./192.168.1.34.key"
        },
        "auth": {
          "type": "token",
          "options": {
               "realm": "https://192.168.1.34/service/token",
               "service": "token-service",
               "issuer": "registry-token-issuer",
               "rootcertbundle": "/etc/docker/notary-server/token.crt"
          }
        },
        "logging": {
                "level": "debug"
        },
        "storage": {
                "backend": "mysql",
                "db_url": "server@tcp(mysql:3306)/notaryserver?parseTime=True"
        }
}

```

As this is not a Notary bug, I'm sending you the notary config so you can try to reproduce this with Harbor.

I think notary sends a token request/validation to Harbor, and Harbor does not understand the request :)

I'm logged on Harbor (docker login my_registry) succesfully, but when I try to push a signed image to Harbor with this integrated I get an error.

If I disable the Notary Authentication, I'm able to sign and push an image. The thing is, I need to verify if a user is authorized to sign an image on that project :)

Thanks!

**Comment by rikatz** [comment]
An update:

Checking for the differences between signed and unsigned images:

**With Token Login enabled:**
```
192.168.1.35 - - [04/Nov/2016:01:59:21 +0000] "GET /v2/ HTTP/1.1" 401 87 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/3.10.0-327.36.3.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.3 \x5C(linux\x5C))"
192.168.1.35 - admin [04/Nov/2016:01:59:22 +0000] "GET /service/token?account=admin&scope=repository%3Alibrary%2Falpine%3Apush%2Cpull&service=token-service HTTP/1.1" 200 1197 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/3.10.0-327.36.3.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.3 \x5C(linux\x5C))"
192.168.1.35 - - [04/Nov/2016:01:59:22 +0000] "HEAD /v2/library/alpine/blobs/sha256:3690ec4760f95690944da86dc4496148a63d85c9e3100669a318110092f6862f HTTP/1.1" 200 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/3.10.0-327.36.3.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.3 \x5C(linux\x5C))"
192.168.1.35 - - [04/Nov/2016:01:59:22 +0000] "HEAD /v2/library/alpine/blobs/sha256:baa5d63471ead618ff91ddfacf1e2c81bf0612bfeb1daf00eb0843a41fbfade3 HTTP/1.1" 200 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/3.10.0-327.36.3.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.3 \x5C(linux\x5C))"
192.168.1.35 - - [04/Nov/2016:01:59:22 +0000] "PUT /v2/library/alpine/manifests/sign HTTP/1.1" 201 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/3.10.0-327.36.3.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.3 \x5C(linux\x5C))"
**192.168.1.35 - admin [04/Nov/2016:01:59:22 +0000] "GET /service/token?account=admin&scope=repository%3A192.168.1.34%2Flibrary%2Falpine%3Apush%2Cpull&service=notary-service HTTP/1.1" 200 1193 "-" "Docker-Client/1.12.3 (linux)"**
```

**Without token login enabled**

```
192.168.1.35 - - [04/Nov/2016:02:01:47 +0000] "GET /v2/ HTTP/1.1" 401 87 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/3.10.0-327.36.3.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.3 \x5C(linux\x5C))"
192.168.1.35 - admin [04/Nov/2016:02:01:47 +0000] "GET /service/token?account=admin&scope=repository%3Alibrary%2Falpine%3Apush%2Cpull&service=token-service HTTP/1.1" 200 1197 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/3.10.0-327.36.3.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.3 \x5C(linux\x5C))"
192.168.1.35 - - [04/Nov/2016:02:01:47 +0000] "HEAD /v2/library/alpine/blobs/sha256:3690ec4760f95690944da86dc4496148a63d85c9e3100669a318110092f6862f HTTP/1.1" 200 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/3.10.0-327.36.3.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.3 \x5C(linux\x5C))"
192.168.1.35 - - [04/Nov/2016:02:01:47 +0000] "HEAD /v2/library/alpine/blobs/sha256:baa5d63471ead618ff91ddfacf1e2c81bf0612bfeb1daf00eb0843a41fbfade3 HTTP/1.1" 200 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/3.10.0-327.36.3.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.3 \x5C(linux\x5C))"
192.168.1.35 - - [04/Nov/2016:02:01:47 +0000] "PUT /v2/library/alpine/manifests/sign HTTP/1.1" 201 0 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/3.10.0-327.36.3.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.3 \x5C(linux\x5C))"
```

There is a final request, to check if that token has some kind of permission. I'm not able to check which permission is this now, but I think it's waiting for some special role.

**Comment by rikatz** [comment]
OK guys, one last update.

Debugging the returned JWT from both actions (the GET /service/token before pushing, and the GET /service/token before the siging attempt) you can check that the returned JWT (when I try to get the token for signing - GET /service/token?account=admin&scope=repository%3A192.168.1.34%2Flibrary%2Falpine%3Apush%2Cpull&service=token-service) cames with the 'actions' field missing:

```
{
  "iss": "registry-token-issuer",
  "sub": "",
  "aud": "token-service",
  "exp": 1478227342,
  "nbf": 1478225542,
  "iat": 1478225542,
  "jti": "wVxBSeKWJ2sCw9tN",
  "access": [
    {
      "type": "repository",
      "name": "192.168.1.34/library/alpine",
      "actions": []
    }
  ]
}
```

The valid request (GET /service/token?account=admin&scope=repository%3Alibrary%2Falpine%3Apush%2Cpull&service=token-service) returns the actions array populated, as the following:
 ```
{
  "iss": "registry-token-issuer",
  "sub": "",
  "aud": "token-service",
  "exp": 1478227707,
  "nbf": 1478225907,
  "iat": 1478225907,
  "jti": "TBTQCMH14d7Ygvn0",
  "access": [
    {
      "type": "repository",
      "name": "library/alpine",
      "actions": [
        "pull"
      ]
    }
  ]
}
```

**Comment by reasonerjt** [comment]
@rikatz Thanks for raising this issue.  
Based on the logs, in section "With Token Login enabled:" the second request to token service is asking for a different repo "192.168.1.34/library/alpine" and the token service on Harbor failed to understand it is the same as "library/alpine" and provide a token with insufficient access permission.

Whether Notary's approach is correct is debatable, the hostname "192.168.1.34" may probably be put in some other parm and keep the scope same as the previous request for token.

I'm currently busy with other tasks, let me leave this issue open and when I have time I'll check the doc of Notary to understand the flow.  Integration with Notary is on our plan.

**Comment by rikatz** [comment]
@reasonerjt Thanks for the answer!

I'm rebuilding my environment here, and will try to workaround this with some rewrite on NGINX for now.

Let me know if I can help you with something else.

Thanks!

**Comment by reasonerjt** [comment]
Since you've been testing with Notary, letting us know what works and what does not would be very helpful!

**Comment by rikatz** [comment]
Guys, an update here:

The code that checks the ProjectName is here:

https://github.com/vmware/harbor/blob/master/src/ui/service/token/authutils.go#L109

And here is the DEBUG log of this happening:

- Right request: 
```
2016-11-05T02:00:48Z [INFO] current access, type: repository, name:library/alpine, actions:[push * pull]
```

- Wrong request: 
```
project 192.168.1.34/library does not exist, set empty permission for admin
2016-11-05T02:00:55Z [INFO] current access, type: repository, name:192.168.1.34/library/alpine, actions:[]
```

Probably it should check what's the length of the array generated by a split on the string "a.Name", and if it's bigger than 2 (like 3, meaning that it contains the host/project/image), use the 'second' item of this array generated by the split function. Otherwise, use the first.

I'm not going to try fixing this right now (as I'm even not a Golang skilled developer), but probably on the weekend will make a PR for this fix.

Also, I don't know what's the logic of using the LastIndex function, and if this is due to previewing something like subprojects (or even something related to the Replication feature).

Anyway, will try to fix this and see what happens next :)

**Comment by rikatz** [comment]
@reasonerjt I did a little correction based on my last comment. Don't know if this is enough for you to accept the PR, but I've tested here the integration between Notary and Harbor and it worked fine, as you can see here:

** User without permission on the following repo **

```
 $ notary -s "https://192.168.1.34:4443" -d ~/.docker/trust publish  192.168.1.34/library/alpine sign
Pushing changes to 192.168.1.34/library/alpine
Enter username: rkatz
Enter password:
Enter passphrase for targets key with ID 0676a40:

* fatal: you are not authorized to perform this operation: server returned 401.
```

** User with granted permission on the following repo **

```
 $ notary -s "https://192.168.1.34:4443" -d ~/.docker/trust publish 192.168.1.34/library/alpine sign
Pushing changes to 192.168.1.34/library/alpine
Enter username: rkatz1
Enter password:
Enter passphrase for targets key with ID 0676a40:
Successfully published changes for repository 192.168.1.34/library/alpine
```

I consider this a reasonable result, as I'm able to use Notary authenticating against Harbor tokens :) Just need to document how to do this now, but this PR solves my issue.

**Comment by rikatz** [comment]
@reasonerjt What do you think if I, instead of spliting and replacing the string, verifies if is there the Harbor Hostname (as in harbor.cfg) configured on the 'scope' name, and than parses that as desired?

**Comment by reasonerjt** [comment]
@rikatz  sorry for bugging you,  I'm trying to integrate notary with Harbor, and when I update server-config.json with Harobr's token service I hit an "nil pointer" error.
You can see details in https://github.com/docker/notary/issues/1097, have you met this issue in your test?

**Comment by rikatz** [comment]
@reasonerjt Nope. In my tests all worked fine :(

Maybe this is something added from that time to now, I haven't tested notary anymore because some other priorities have rised here.

This 'context' issues happened for me when I was migrating some things from Go 1.6 to Go 1.7, maybe is this the case?

**Comment by reasonerjt** [comment]
Closing the issue as Harbor 1.1.0 has Notary support.
