### ISSUE TITLE
incorrect error message

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#1014]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose
2)Config files of harbor, you can get them by packaging "Deploy/config" directory
3)Log files, you can get them by package the /var/log/harbor/ 

harbor version 0.4.5 
when delete an empty project  has a replication policy, it will show a message that the project contains repositories，where it should be the project contains replication policies
![11111](https://cloud.githubusercontent.com/assets/23101283/19997817/fca9777c-a2a3-11e6-9762-0aea847b5919.PNG)

**Comment by wknet123** [comment]
Fixed by #1031
