### ISSUE TITLE
can't send the reset password email when configured as the user guide/default form

### ISSUE THREAD

**Issue by fulllove890** [vmware/harbor#1016]
Hello, 
When I set 
`email_from = admin robot@mydomain.com` or `email_from = admin <robot@oneapm.com>`
, I got a `[ERROR] [password.go:87]: Send email failed: 501 mail from address must be same as authorization user ` from /var/log/harbor/2016-11-04/ui.log 
After trying and trying, I found the form of `email_from = robot@mydomain.com` is reachable, so is it the guide/default configuration not correct?

Docker version 1.12.1 & docker-compose version 1.8.0

**Comment by hainingzhang** [comment]
The error means the "from email" should be the same as the "email_username".

**Comment by fulllove890** [comment]
What I mean is, the harbor's user guide and the default configuration in harbor.cfg tell us an unavailable example.

**Comment by reasonerjt** [comment]
Closing as this is clearly due to a misconfiguration.
