### ISSUE TITLE
Missing nginx.https.conf in the source file

### ISSUE THREAD

**Issue by terpsho** [vmware/harbor#1018]
This file is introduced when configuring harbor as secure mode. However, this file cannot be found in the source code. This file was in the last version. 
I tried to do a harbor pull request but don't have the permission.

**Comment by reasonerjt** [comment]
Sorry, it's moved to https://github.com/vmware/harbor/blob/master/make/common/templates/nginx/nginx.https.conf

We made update to the process so that https configuration can be done automaticly, we'll update the docs in next couple of days.

**Comment by reasonerjt** [comment]
The doc has been updated on master branch, closing the issue.
