### ISSUE TITLE
Harbor instance not accessible when logged in with LDAP user (refused to connect)

### ISSUE THREAD

**Issue by mobla** [vmware/harbor#1020]
Harbor OVA 0.4.5
Will provide the live setup in slack channel

1. Deploy Harbor OVA with CA certs & key (https config) and LDAP auth
2. when I login with LDAP auth (user2), it does not connect. docker service in Harbor OVA does not respond
This site can’t be reached

xxxx refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

a. nginx logs does not show /var/log/harbor/2016-11-05/docker_proxy.log any issues
b. ui logs shows 
Nov  5 20:05:25 172.18.0.1 docker/ui[2916]: 2016-11-05T20:05:25Z [DEBUG] [ldap.go:72]: Bind search dn errorLDAP::Bind() error (-1) : Can't contact LDAP server
Nov  5 20:05:25 172.18.0.1 docker/ui[2916]: 2016-11-05T20:05:25Z [ERROR] [base.go:162]: Error occurred in UserLogin: LDAP::Bind() error (-1) : Can't contact LDAP server
Nov  5 20:06:10 172.18.0.1 docker/ui[2916]: 2016-11-05T20:06:10Z [DEBUG] [ldap.go:72]: Bind search dn errorLDAP::Bind() error (-1) : Can't contact LDAP server
Nov  5 20:06:10 172.18.0.1 docker/ui[2916]: 2016-11-05T20:06:10Z [ERROR] [base.go:162]: Error occurred in UserLogin: LDAP::Bind() error (-1) : Can't contact LDAP server

[config.tar.gz](https://github.com/vmware/harbor/files/573484/config.tar.gz)
[logs.tar.gz](https://github.com/vmware/harbor/files/573485/logs.tar.gz)

**Comment by reasonerjt** [comment]
Seems the ui instance failed to access the ldap server?

@ywk253100 could you investigate?

**Comment by ywk253100** [comment]
I checked the environment and found the "solutionhost1.eng.vmware.com" can not be resolved in your host. Could you use the IP to configure the LDAP server?

**Comment by ywk253100** [comment]
Closing this issue as it's caused by environment, not Harbor. Feel free to reopen it.
