### ISSUE TITLE
vmware/harbor-log:0.4.5 Restarting (1) 23 seconds ago

### ISSUE THREAD

**Issue by ghost** [vmware/harbor#1021]
1,[root@reg harbor]# docker -v
Docker version 1.12.3, build 6b644ec
[root@reg harbor]# docker-compose -v
docker-compose version 1.9.0-rc3, build fcd38d3
[root@reg harbor]# 
![error](https://cloud.githubusercontent.com/assets/16472446/20037174/ed4b05c6-a455-11e6-9f4d-7a85a315c6c3.png)

**Comment by lwh** [comment]
get a similar thing on docker 1.12 docker-compose 1.9.0-rc2 
docker logs show:

harbor-log    | rsyslogd: pidfile '/var/run/rsyslogd.pid' and pid 7 already exist.
harbor-log    | If you want to run multiple instances of rsyslog, you need to specify
harbor-log    | different pid files for them (-i option).
harbor-log    | rsyslogd: run failed with error -3000 (see rsyslog.h or try http://www.rsyslog.com/e/3000 to learn what that number means)

**Comment by reasonerjt** [comment]
Closing as it's fixed.
