### ISSUE TITLE
when i reset harbor.cfg,how make it tkae effect.

### ISSUE THREAD

**Issue by ghoul008** [vmware/harbor#103]
did i must del images and "docker-compose up -d" again?

**Comment by ghoul008** [comment]
i used 0.1.1 for step.

**Comment by wknet123** [comment]
You need to execute `docker-compose build`, and remove the old volume `/data` because of the updated DB schema of this version, then run `docker-compose up -d`

**Comment by ghoul008** [comment]
then after that,am i created user and project will be OK？

**Comment by wknet123** [comment]
Old data will be lost, you need to create user and project again.

**Comment by ghoul008** [comment]
thanks ~~

**Comment by ghoul008** [comment]
btw before execute docker-compose build,am i must "docker-compose stop"?

**Comment by wknet123** [comment]
Of course.

**Comment by ghoul008** [comment]
Thank you for your answer patiently.
