### ISSUE TITLE
how to get the project tags list from harbor api?

### ISSUE THREAD

**Issue by 272909106** [vmware/harbor#1038]
harbor:0.4.5
i want to get the project tags list ,like "curl 10.96.141.222:5000/v2/rancher/server/tags/list"
where can i find the harbor api?

**Comment by yhua123** [comment]
you can follow the swagger.yaml
or
projects list:
curl -X GET --header 'Accept: application/json' 'http://10.96.141.222/api/projects'
repositories list:
curl -X GET --header 'Accept: application/json' 'http://10.96.141.222/api/repositories?project_id=XXXX'
tags list:
curl -X GET --header 'Accept: application/json' 'http://10.96.141.222/api/repositories/tags?repo_name=XXXX'

**Comment by 272909106** [comment]
when i setup the swagger ui ,i got the api,like your last answer.
but i got the tags list,not need username,password,awalys like this ?

**Comment by yhua123** [comment]
if one project setting as 'public', you can get the list without username and password.

**Comment by 272909106** [comment]
Exactly!,thanks again.

**Comment by gagayuan** [comment]
1, Open chrome devtools,then refresh your public hub webpage.
2, In network tab, **find the XHR file(maybe startswith 'artifacts')** which includes the tab info.
3, The Request URL is what your want. You can get it by request.urlopen of python.
