### ISSUE TITLE
setup swagger ui 

### ISSUE THREAD

**Issue by 272909106** [vmware/harbor#1040]
harbor:0.4.5
i follow the word (https://github.com/vmware/harbor/blob/master/docs/configure_swagger.md) to setup swagger ui ,
root:~/harbor/harbor-master/make# docker-compose build
log uses an image, skipping
ui uses an image, skipping
mysql uses an image, skipping
jobservice uses an image, skipping
registry uses an image, skipping
proxy uses an image, skipping
,then docker-compose up -d 
harbor is up ,i can login ,but i can't open   http://<HARBOR_SERVER>/static/vendors/swagger/index.html,the page show "Not Found"

**Comment by yhua123** [comment]
please use the docker-compose file under make/dev for swagger setup
or follow the document (https://github.com/vmware/harbor/blob/dev/docs/configure_swagger.md)
the document on master missing on directory

**Comment by 272909106** [comment]
@yhua123 
i passed ,thank you .
