### ISSUE TITLE
Deploying harbor with ovftool gives memory error

### ISSUE THREAD

**Issue by sflxn** [vmware/harbor#1051]
When I use ovftool to deploy the respin2 version of the harbor ovf, I get the following error:

```
 - Virtual machine has 4,096 megabytes of memory, which is outside the range of 4 to 3,600 megabytes supported on the host. This may be a general limitation of the host software, or specific to the guest OS selected for the virtual machine.
Completed with errors
```

When I look at harbor installed with a Windows vsphere client (thick client), the VM indicates it's using hardware version 4 (esx 3.5).  When I look in the harbor ovf file, there is no specification for hardware version.  I wonder if this is causing the problem.

I used ovftool 4.1.0, build 2459827 for Linux.

Follow the instructions here, https://github.com/vmware/vic-product/blob/master/docs/setup/beta/install-configure-harbor.md.

**Comment by hainingzhang** [comment]
The OStype of OVA respin2 has been set to Photon OS TP2, which is not supported by ESX and it is converted into 32bit guest OStype. This may cause the memory limitation. We have adjusted the OS type for this to enforce 64bit OS. 

@ywk253100 @mreferre

**Comment by mreferre** [comment]
I am sure I have seen this problem before. As I was trying to fix it by editing max amount of memory in various XML files (as suggested on some blogs / forums) I eventually got rid of it and I have never seen it again since. 

Unfortunately I don't remember what it was. 

Off the top of my head it could have been a couple of things: 

1) I saw the error when I was trying to deploy the OVA directly using ovftool (Vs unpacking the OVA first using `ovftool file.ova file.ovf` and THEN importing the OVF using ovftool) or 
2) I saw the error when trying to deploy the OVA/OVF on a hosted platform (e.g. Fusion, etc). 

I know that right now in my lab I use the following script and it works all the time (deploying Harbor against a vCenter): 
```
export VCENTERSERVER="192.168.8.211"
export VCENTERDATACENTER="DTC1"
export VCENTERCLUSTER="Cluster1"
export ESXSERVER="192.168.8.200"
export VSPHEREUSER="user1@vsphere.local"
export VSPHEREPASSWORD="Vmware123!"  
export VSPHEREDATASTORE="sharedstorage"
export EXTERNALNETWORK="VM Network"
export VCHINTERNALNETWORK="PG1"
export VCHTLS=0 # 0=no tls, 1=tls enabled
export VCHNAME="VCH1"
export HARBORVMIP="192.168.8.221"
export HARBORVMNAME="Harbor1"
export HARBORVMDOMAIN="vsphere.local"
export HARBORVMSEARCHPATH="vsphere.local"
export HARBORVMDNS="8.8.8.8"
export HARBORVMMASK="255.255.255.0"
export HARBORVMGATEWAY="192.168.8.253"
export HARBORROOTPASSWORD="Vmware123!" #this is the value to be set when deploying Harbor
export HARBORADMINPASSWORD="Vmware123!" #this is the value to be set when deploying Harbor
export HARBORDBPASSWORD="Vmware123!" #this is the value to be set when deploying Harbor
export HARBORURL="https://github.com/vmware/harbor/releases/download/0.4.5/"
export HARBORFILE="harbor_0.4.5_beta_respin2"  

curl -O -L "${HARBORURL}${HARBORFILE}.ova"

ovftool "${HARBORFILE}.ova" "${HARBORFILE}.ovf"

ovftool --datastore=${VSPHEREDATASTORE} \
               --noSSLVerify \
               --name=${HARBORVMNAME} \
               --net:"Network 1"="${EXTERNALNETWORK}" \
               --diskMode=thin \
               --powerOn \
               --X:waitForIp \
               --X:injectOvfEnv \
               --X:enableHiddenProperties \
               --prop:root_pwd="${HARBORROOTPASSWORD}" \
               --prop:harbor_admin_password="${HARBORADMINPASSWORD}" \
               --prop:db_password="${HARBORDBPASSWORD}" \
               --prop:vami.domain.Harbor="${HARBORVMDOMAIN}" \
               --prop:vami.searchpath.Harbor="${HARBORVMSEARCHPATH}" \
               --prop:vami.DNS.Harbor="${HARBORVMDNS}" \
               --prop:vami.ip0.Harbor="${HARBORVMIP}" \
               --prop:vami.netmask0.Harbor="${HARBORVMMASK}" \
               --prop:vami.gateway.Harbor="${HARBORVMGATEWAY}" \
               --prop:vm.vmname=Harbor \
               "${HARBORFILE}.ovf" \
vi://"${VSPHEREUSER}":"${VSPHEREPASSWORD}"@${VCENTERSERVER}/${VCENTERDATACENTER}/host/${VCENTERCLUSTER}/${ESXSERVER}

```

**Comment by sflxn** [comment]
I don't know if you guys created this ovf file or the ovftool did, but when I use ovftool to unpack the ova file, it produced an ovf file that had this,

```
    <VirtualHardwareSection ovf:required="false" ovf:transport="com.vmware.guestInfo">
      <Info>Virtual Hardware Requirements</Info>
      <System>
        <vssd:ElementName>Virtual Hardware Family</vssd:ElementName>
        <vssd:InstanceID>0</vssd:InstanceID>
        <vssd:VirtualSystemType>vmx-04</vssd:VirtualSystemType>
      </System>
```
When I changed type to vmx-10, it worked fine.  This is the bug.

**Comment by mobla** [comment]
Note: This happens only when we use ovftool CLI (hit the same issue in my env as well). So far it has not happened when harbor ova is deployed using C# (thick) client on vCenter 6.0/ESX6.0 or from vSphere Web client vCenter 6.5.

Thanks,
Murali

**Comment by sflxn** [comment]
@mobla I'm interested in the ovftool route for integration into our CI.  When installing manually, it's not an issue.

**Comment by mobla** [comment]
@sflxn : Yes, it is a blocker for CI integration..

**Comment by sflxn** [comment]
I found a big clue.  Following the direction on the vic-product page, I used ovftool to unpack the ova first, as I didn't know this tool very well.  After looking at some existing scripts, I tried using ovftool on just the ova directly instead of unpacking the ova.  It did not complain about hardware level or memory.  However, the deployed Harbor didn't come up with a static IP that I set in the properties.

**Comment by mreferre** [comment]
@sflxn are you saying that unpacking the OVA and using ovftool against the OVF didn't work whereas using ovftool against the OVA directly did work? That's kind of interesting cause (if I remember well) I had to unpack it to work properly. 

Also, all of the tests I have done (and that works) do not involve a secured (https) Harbor configuration. If you are importing Harbor and configure it with plain http then the script I pasted above should work (note you had to unpack the OVA first as it will look for the OVF). 

I had 5 people yesterday test that method/script above in live environments and it worked for everyone.  

If you are trying to import it and configure it for https than I have little to say as this is something I have never attempted doing.

**Comment by hainingzhang** [comment]
I tested @mreferre 's  script and it worked. It can be used to obtain both static or DHCP-ed IP address. We will fixed the vmx version issue in the next release so that it won't complain about the memory size. 

The ovftool I used was v5.0 .

**Comment by sflxn** [comment]
@mreferre Yes, if I use the OVA directly, there is no issue.  If I unpack the OVA, it fails.  It might be the version of ovftool I used?  It's the latest version from our public download site.  I have not tried ovftool 5.0.  Maybe we should specify that version as a requirement?  Is build web the only place to get 5.0?  It wasn't on the VMware download site.

Also, I am using the linux version of ovftool.  Not sure what OS you guys are running on.

**Comment by mreferre** [comment]
I am not sure if it's the ovftool version. I am using version 4.1.0. 

Could you (just out of curiosity) use the script below? You need to tweak some of the parameters to match your environment but for me this script never failed. I am really curious to see what's breaking here. 

```
export VCENTERSERVER="192.168.8.211"
export VCENTERDATACENTER="DTC1"
export VCENTERCLUSTER="Cluster1"
export ESXSERVER="192.168.8.200"
export VSPHEREUSER="user1@vsphere.local"
export VSPHEREPASSWORD="Vmware123!"  
export VSPHEREDATASTORE="sharedstorage"
export EXTERNALNETWORK="VM Network"
export HARBORVMIP="192.168.8.221"
export HARBORVMNAME="Harbor1"
export HARBORVMDOMAIN="vsphere.local"
export HARBORVMSEARCHPATH="vsphere.local"
export HARBORVMDNS="8.8.8.8"
export HARBORVMMASK="255.255.255.0"
export HARBORVMGATEWAY="192.168.8.253"
export HARBORROOTPASSWORD="Vmware123!" #this is the value to be set when deploying Harbor
export HARBORADMINPASSWORD="Vmware123!" #this is the value to be set when deploying Harbor
export HARBORDBPASSWORD="Vmware123!" #this is the value to be set when deploying Harbor
export HARBORURL="https://github.com/vmware/harbor/releases/download/0.4.5/"
export HARBORFILE="harbor_0.4.5_beta_respin2"


curl -O -L "${HARBORURL}${HARBORFILE}.ova"

ovftool "${HARBORFILE}.ova" "${HARBORFILE}.ovf"

ovftool --datastore=${VSPHEREDATASTORE} \
               --noSSLVerify \
               --name=${HARBORVMNAME} \
               --net:"Network 1"="${EXTERNALNETWORK}" \
               --diskMode=thin \
               --powerOn \
               --X:waitForIp \
               --X:injectOvfEnv \
               --X:enableHiddenProperties \
               --prop:root_pwd="${HARBORROOTPASSWORD}" \
               --prop:harbor_admin_password="${HARBORADMINPASSWORD}" \
               --prop:db_password="${HARBORDBPASSWORD}" \
               --prop:vami.domain.Harbor="${HARBORVMDOMAIN}" \
               --prop:vami.searchpath.Harbor="${HARBORVMSEARCHPATH}" \
               --prop:vami.DNS.Harbor="${HARBORVMDNS}" \
               --prop:vami.ip0.Harbor="${HARBORVMIP}" \
               --prop:vami.netmask0.Harbor="${HARBORVMMASK}" \
               --prop:vami.gateway.Harbor="${HARBORVMGATEWAY}" \
               --prop:vm.vmname=Harbor \
               "${HARBORFILE}.ovf" \
vi://"${VSPHEREUSER}":"${VSPHEREPASSWORD}"@${VCENTERSERVER}/${VCENTERDATACENTER}/host/${VCENTERCLUSTER}/${ESXSERVER}
```

**Comment by ywk253100** [comment]
I have tried both unpacking OVA and using OVA directly and there was no issue. 
ovftool: 5.0 linux version
ESX: 5.5

**Comment by hainingzhang** [comment]
Ovftool 5.0 comes with the VMstudio. Not sure if it is publicly available. 

Harbor has added EULA in OVA, so you may need to add a param in the command line to silently accept the EULA:  
--acceptAllEulas

@mreferre  @sflxn

**Comment by mreferre** [comment]
Thanks @hainingzhang. Is there a public link for Harbor 5.0RC1. I'd like to test the setup of that OVA (with the --acceptAllEulas option, thanks for the hint). 

@mobla can you please try the script I pasted above. It always works in my environment (Linux Ubuntu / Photon with ovftool 4.1 / 4.2).

**Comment by hainingzhang** [comment]
Download here: 
https://github.com/vmware/harbor/releases/tag/0.5.0-rc1  @mreferre

**Comment by ywk253100** [comment]
Closing this issue, feel free to reopen it if you have any questions.
