### ISSUE TITLE
Get the manifests of image very slow

### ISSUE THREAD

**Issue by huzhengchuan** [vmware/harbor#1055]
I use harbor tag 0.4 to use private repository in my project. and When the number of uploaded images is large in harbor， but less than 100, and get the manifest of a image  very slow. it costs 7-10 seconds. I get the manifest of image throw python-client generated by swagger.

**Comment by reasonerjt** [comment]
could you try use API to reproduce the issue?
It'd be even better if you can provide the logs.

**Comment by huzhengchuan** [comment]
thanks, I resolve it.  
Throw add the log in harbor, I found harbor invoke the docker registry api  is slowly. and found error message in 'systemctl status docker '. 
docker-current[4987]: time="2016-11-14T17:03:57.318585696+08:00" level=error msg="external resolution failed, read udp 10.137.73.74:36153->8.8.8.8:53: i/o timeout" .
I know this is docker question https://github.com/gliderlabs/docker-alpine/issues/153. 

so i will close this issue.
