### ISSUE TITLE
Send email failed: x509: certificate is valid for Root, not our mail server.

### ISSUE THREAD

**Issue by 272909106** [vmware/harbor#1059]
harbor 0.4.5
i tried forgot_password function,but error is:
Send email failed: x509: certificate is valid for Root, not smtp.mail.xxxx.com.cn

**Comment by reasonerjt** [comment]
is your mail server using a cert?

**Comment by 272909106** [comment]
@reasonerjt 
yes ,it is our mail server. 
if i use the qq mail server or 163 mail server ,also need the cert??

**Comment by reasonerjt** [comment]
Please have a look at issue #28

**Comment by 272909106** [comment]
@reasonerjt 
my harbor.cfg of certificate 
#Information of your organization for certificate
crt_country = CN
crt_state = State
crt_location = CN
crt_organization = organization
crt_organizationalunit = organizational unit
crt_commonname = open.com.cn
crt_email = jinxj@mail.open.com.cn
**************************************************
#Email account settings for sending out password resetting emails.
email_server = smtp.open.com.cn
email_server_port = 25
email_username = jinxj@mail.open.com.cn
email_password = ******
email_from = admin <sample_admin@mydomain.com>
email_ssl = false
********************************************************************
i run the command "dig smtp.mail.open.com.cn"

; <<>> DiG 9.10.3-P4-Ubuntu <<>> smtp.mail.open.com.cn
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13972
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1280
;; QUESTION SECTION:
;smtp.mail.open.com.cn.		IN	A

;; ANSWER SECTION:
smtp.mail.open.com.cn.	3600	IN	A	10.100.14.81

;; Query time: 0 msec
;; SERVER: 10.100.132.13#53(10.100.132.13)
;; WHEN: Mon Nov 14 14:23:59 CST 2016
;; MSG SIZE  rcvd: 66
*************************************************************
i have the cname record in my local area network.
but i run forget password,the results is " Send email failed: x509: certificate is valid for Root, not smtp.open.com.cn"
how to modify the cert ?not in harbor.cfg ?

**Comment by 272909106** [comment]
Using other providers to solve the mail server problems.
