### ISSUE TITLE
cant add project or users on 0.4.5 (after migration from 0.3.5-rc)

### ISSUE THREAD

**Issue by tronicum** [vmware/harbor#1062]
Hi, i migrated from 0.3.5-rc to 0.4.5 (and run the database migration as documented).
I just noticed i can not add new projects (button "hangs" after click on save) nor can I add users (option not even visible in UI) to existing projects.

docker version: 1.12.3 1.8.0 (installed with 0.4.5 installer+docker-compose up -d)
![screen shot 2016-11-10 at 15 57 59](https://cloud.githubusercontent.com/assets/534773/20181591/0de8e01c-a75f-11e6-96f8-77c866018c63.png)
![screen shot 2016-11-10 at 15 57 36](https://cloud.githubusercontent.com/assets/534773/20181592/0e25b028-a75f-11e6-88d0-bf9ad8ba2296.png)

```
xxx        nginx:1.9                        "nginx -g 'daemon off"   23 hours ago        Up 23 hours         0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   nginx
xxx        vmware/harbor-jobservice:0.4.5   "/harbor/harbor_jobse"   23 hours ago        Up 23 hours                                                    harbor-jobservice
xxx        library/registry:2.5.0           "/entrypoint.sh serve"   23 hours ago        Up 23 hours         5000/tcp                                   registry
xxx        vmware/harbor-ui:0.4.5           "/harbor/harbor_ui"      23 hours ago        Up 23 hours                                                    harbor-ui
xxx        vmware/harbor-db:0.4.5           "docker-entrypoint.sh"   23 hours ago        Up 23 hours         3306/tcp                                   harbor-db
xxx        vmware/harbor-log:0.4.5          "/bin/sh -c 'crond &&"   23 hours ago        Up 23 hours         0.0.0.0:1514->514/tcp                      harbor-log
```

**Comment by hainingzhang** [comment]
Have you tried clearing the cache of your browser and refresh? This happens sometimes after an upgrade.

**Comment by ywk253100** [comment]
Closing due to no further details provided.
