### ISSUE TITLE
It is better to prevent user to select a date of To section earlier than the date of From section in Projects-> Logs-> Advanced Search page

### ISSUE THREAD

**Issue by frankli0614** [vmware/harbor#1064]
Docker version: 1.12.3
Harbor: 0.4.5

Steps:
1. Log in Harbor
2. Select a project
3. Click Logs-> Advanced Search
4. Set From as "11/09/2016" 
5.  Set To as "11/08/2016"

Actual Result: The date of To section earlier than the date of From section.

Expected Result: It is better to prevent user to select a date of To section earlier than the date of From section.
   
![projects_logs_advancedsearch](https://cloud.githubusercontent.com/assets/23302563/20206511/e277552c-a81b-11e6-9838-39be7b9c3595.png)

**Comment by wknet123** [comment]
I'll add validation about this date range check, thanks.

**Comment by wknet123** [comment]
Fixed with PR #1107

**Comment by frankli0614** [comment]
Get an error "Begin date should not be later than end date" to remind user to use correct date range to search logs. 

Close the issue now.

![1064](https://cloud.githubusercontent.com/assets/23302563/20420414/a24424c6-ad98-11e6-96a8-1c59612b2f31.png)

**Comment by frankli0614** [comment]
Verified and passed on 0.5.0 rc2 build.
