### ISSUE TITLE
bug in UI

### ISSUE THREAD

**Issue by niyanchun** [vmware/harbor#1066]
I push image to harbor, and then cancel it before completely. Sometimes the UI will appear an empty repository:

![_-_harbor](https://cloud.githubusercontent.com/assets/5145759/20208400/e58fbf62-a828-11e6-933a-03e46490d647.png)

This results I cannot delete the empty repository and the project.

![_-_harbor](https://cloud.githubusercontent.com/assets/5145759/20208436/1fcf1290-a829-11e6-9f0b-5b8045276bd8.png)

**Comment by ywk253100** [comment]
What version is your Harbor? Could you provide the logs under directory /var/log/harbor?

**Comment by allan1991** [comment]
Harbor version is 0.4.5, our environment has been deleted, I will provide logs if that happens again.
