### ISSUE TITLE
Failed to send mail when used forget passwd

### ISSUE THREAD

**Issue by ghoul008** [vmware/harbor#107]
check /docker_ui.log
Apr 14 15:09:42 host-10-1-241-130 docker/ui[4480]: 2016/04/14 07:09:42 #033[1;34m[router.go:828][D] | POST       | /userExists                              | 1.285775ms       | match      | /userExists                              | #033[0m
Apr 14 15:09:42 host-10-1-241-130 docker/ui[4480]: 2016-04-14T07:09:42Z [ERROR] [password.go:170]: Send email failed: 501 Mail path must not include special characters.

check /docker_proxy.log
Apr 14 15:09:42 host-10-1-241-130 docker/proxy[4480]: 10.1.39.55 - - [14/Apr/2016:07:09:42 +0000] "POST /userExists HTTP/1.1" 200 4 "http://10.1.241.130/forgotPassword" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
Apr 14 15:09:42 host-10-1-241-130 docker/proxy[4480]: 10.1.39.55 - - [14/Apr/2016:07:09:42 +0000] "GET /sendEmail?email=412012135%40qq.com HTTP/1.1" 500 17 "http://10.1.241.130/forgotPassword" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"

**Comment by wknet123** [comment]
This may caused by mis-configured of mail section in harbor.cfg file, or the smtp server is unavailable.

**Comment by ghoul008** [comment]
i'm rebuild harbor "docker-compose build" and run again

check /docker_ui.log
Apr 14 15:48:04 host-10-1-241-132 docker/ui[21809]: 2016/04/14 07:48:04 #033[1;34m[router.go:828][D] | POST       | /userExists                              | 1.484162ms       | match      | /userExists                              | #033[0m
Apr 14 15:48:08 host-10-1-241-132 docker/ui[21809]: 2016-04-14T07:48:08Z [ERROR] [password.go:170]: Send email failed: 535 Incorrect authentication data

check /docker_proxy.log
Apr 14 15:48:04 host-10-1-241-132 docker/proxy[21809]: 10.1.39.55 - - [14/Apr/2016:07:48:04 +0000] "POST /userExists HTTP/1.1" 200 4 "http://reg.mydomain.com/forgotPassword" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
Apr 14 15:48:08 host-10-1-241-132 docker/proxy[21809]: 10.1.39.55 - - [14/Apr/2016:07:48:08 +0000] "GET /sendEmail?email=412012135%40qq.com HTTP/1.1" 500 17 "http://reg.mydomain.com/forgotPassword" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"

**Comment by wknet123** [comment]
What is your SMTP/port?

**Comment by ghoul008** [comment]
imap is 143
smtp is 25

**Comment by wknet123** [comment]
It seems that we don't support IMAP currently.

**Comment by ghoul008** [comment]
i see that in /harbor.cfg 
oh is that mailserver needed support  encryption,example smtp open port 465.

**Comment by wknet123** [comment]
I wrote a sample of sending mail as our current implementation at [https://play.golang.org/p/IbE1-O8g2L](url), you may paste it to your local and test it by changing parameters with your configurations.

**Comment by ghoul008** [comment]
OK ,i will try it later.

**Comment by ghoul008** [comment]
404 page

**Comment by wknet123** [comment]
You shouldn't click the url directly in the comment or you can't visit google in China.

**Comment by ghoul008** [comment]
e.........

**Comment by wknet123** [comment]
Are you familiar with Go? Have you tried this [https://play.golang.org/p/IbE1-O8g2L](https://play.golang.org/p/IbE1-O8g2L)?
