### ISSUE TITLE
Password test is broken

### ISSUE THREAD

**Issue by tronicum** [vmware/harbor#1070]
I just setup a new instance and used pwgen -y 23 to generate a password.
Odly enough
it gives an error for the string
ahj!ahtieThoh3ieh5bohwa 
but if you cut the first 3 charaters
!ahtieThoh3ieh5bohwa
it is considered right again.
using 0.4.5 of harbor.

**Comment by wknet123** [comment]
Password has a length restriction between 7 and 20 characters.

**Comment by tronicum** [comment]
Well the UI does not tell ("At least 8 characters with 1 lowercase letter, 1 capital letter and 1 numeric character.") nor does it limit 
`<input type="password" class="form-control" id="password" ng-model="user.password" ng-change="vm.reset()" name="uPassword" required password>`

**Comment by wknet123** [comment]
We've updated message about this status, it will release at 0.5.0. 
Dup #1010
