### ISSUE TITLE
First time logged LDAP user (say mobla) can create a project, add other LDAP user to the new project that is created. Later that user loses admin rights to the project

### ISSUE THREAD

**Issue by mobla** [vmware/harbor#1072]
Production harbor instance: (reg-xxxx)
Harbor Version: 0.4.6-test

Steps:
0. Ensure other users (say user1, user2 were logged in and user-profiles were created in Harbor)
1. Login as LDAP user (vmware ldap - mobla)
2. Create a project say mobla-project
3. At this point Harbor Admin UI lets mobla user to add other LDAP users to the mobla-project
4. Now, logout and re-login as mobla user
5. mobla user lost admin rights to the mobla-project and not able to add new user or modify user role to the existing users

Live setup is accessible to Harbor team (reg-xxxx)..

Thanks,
Murali

**Comment by hainingzhang** [comment]
I can still see you are project admin. Can you provide a screenshoot?

**Comment by hainingzhang** [comment]
After refresh the browser, it worked fine. Please check.

**Comment by mobla** [comment]
Refresh does not help in my case. Works fine on Incognito window or a new session. Browser cache issue with different users logged in with different roles?

**Comment by reasonerjt** [comment]
please clean the browser history and refresh, yes it's cache issue, some part of the code is not latest on the browser and failed to work with the latest response data.

**Comment by reasonerjt** [comment]
@mobla based on our chat I believe this is due to browser cache, can I close this issue?

**Comment by mobla** [comment]
Should we document this?

**Comment by hainingzhang** [comment]
We have created a fix for this to clear the cache after upgrading to a newer version.

**Comment by reasonerjt** [comment]
#1073 tracked the issue about having to clear browser cache after upgrade. 
closing this issue.
