### ISSUE TITLE
Should not ask user to clean cache each time the code upgrades.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#1073]
shoud set some attributes 

such as 
<meta http-equiv="pragma" content="no-cache" />
to avoid it.

**Comment by wknet123** [comment]
I think we could trigger browser to reload upgrades by changing JS file `harbor.app.min.js` name with random content which included in header of HTML at the UI image building stage, and also need to update the tag `script` attribute `src` against to the changed name.

**Comment by wknet123** [comment]
Fixed with PR #1081
