### ISSUE TITLE
'prepare' script error info ' SyntaxError: invalid token'

### ISSUE THREAD

**Issue by Jamlee** [vmware/harbor#1074]
Environment:
harbor-offline-installer-0.4.5.tgz
python 2.7 && python 3.5

Error Info:

> ➜  harbor sudo ./prepare
>   File "./prepare", line 46
>     os.makedirs(path, mode= 0600)
>                                ^
> SyntaxError: invalid token
> 

Solution:
change to 
```
 os.makedirs(path, mode= 0O0600)
```

**Comment by Azuka** [comment]
I'm still seeing this issue with the latest installer

**Comment by Jamlee** [comment]
@Azuka  maybe you can try clean all file and re-extract all file from harbor.tgz.

**Comment by Azuka** [comment]
@Jamlee, thanks, looks like it was a Python 3 issue. I was able to get it working with Python 2.7.
