### ISSUE TITLE
Can input 20 non-ASCII characters in Comments textbox on Account Settings page, but get error when save the comments

### ISSUE THREAD

**Issue by frankli0614** [vmware/harbor#1075]
Docker version: 1.12.3
Harbor: 0.4.5

1. Login to Harbor
2. Click Admin->Account Settings
3. Try to input 20 Non-ASCII characters (for example, "系统管理员系统管理员系统管理员系统管理员")
4. Click Save button

Actual Result: Got error "Failed to update user. Change user profile error: Comment with illegal length"

Expected Result: It should not allow user to input 20 non-ASCII characters in Comments textbox or give user a clear error message to let user know the maximum number of characters allowed.

NOTE:
1. The maximum number of ASCII characters allowed input in the Comments textbox  is 20.

![editaccountserror](https://cloud.githubusercontent.com/assets/23302563/20251737/a70d8910-aa56-11e6-8967-6c7c7f586967.png)

**Comment by wknet123** [comment]
Fixed with PR #1139
