### ISSUE TITLE
Page redirect issue when search projects

### ISSUE THREAD

**Issue by frankli0614** [vmware/harbor#1078]
Docker version: 1.12.3
Harbor: 0.4.5

1. Login to Harbor and navigate to Projects.
2. Create 16 or more projects (for example, create 18 projects in my scenarios: test001~test018) so that the pagination control has multiple pages.
3. Navigate to Page 2.
4. Input string '018' in project search textbox.
5. Click Search button.

Actual result: The text "No projects available now" displays. And user should click Page 1 number to view the search result: test018.

Expected Result: The search result should redirect to page 1 directly to show user's search result.

![searcprojectwithmultiplepages](https://cloud.githubusercontent.com/assets/23302563/20255955/7712ff18-aa7b-11e6-83e4-abeaebab4f18.png)

**Comment by wknet123** [comment]
Can't reproduce in current Dev branch code.

**Comment by frankli0614** [comment]
Verified and passed.

**Comment by frankli0614** [comment]
Verified and passed on 0.5.0 rc2 build.
