### ISSUE TITLE
All projects in current page can be shown if search project by symbol "%" .

### ISSUE THREAD

**Issue by frankli0614** [vmware/harbor#1079]
Docker version: 1.12.3
Harbor: 0.4.5

1. Login to Harbor and navigate to Projects.
2. Create 16 or more projects (for example, create 18 projects in my scenarios: test001~test018) so that the pagination control has multiple pages.
3. Navigate to Page 1 (page 1 includes project test001 ~ test015).
4. Input symbol '%' in project search textbox.
5. Click Search button.

Actual result: All projects (test001 ~ test015) in page 1 can be shown.

Expected Result: No projects shown. 

![searchbysymbolpercent](https://cloud.githubusercontent.com/assets/23302563/20256819/c3cf4e24-aa80-11e6-8047-e4fc9cb742d1.png)

**Comment by reasonerjt** [comment]
What？ looks like a sql-injection?

**Comment by ywk253100** [comment]
It is not a sql-injection, just a wildcard.

**Comment by ywk253100** [comment]
Fixed by #1100 .

**Comment by frankli0614** [comment]
Verified and passed on 0.5.0 rc1 build.

**Comment by frankli0614** [comment]
Verified and passed on 0.5.0 rc2 build.
