### ISSUE TITLE
Suggest to change "中文" to "简体中文" in language selection option.

### ISSUE THREAD

**Issue by frankli0614** [vmware/harbor#1082]
Docker version: 1.12.3
Harbor: 0.4.5

1. Open Harbor login page.
2. Click language selection icon.

Suggest to change "中文" to "简体中文" in language selection. Because Chinese includes "Simplified Chinese" and "Traditional Chinese".

![harborlanguagechinese](https://cloud.githubusercontent.com/assets/23302563/20290615/1d78cb30-ab1c-11e6-8692-29dd0a8e34c4.png)

**Comment by wknet123** [comment]
Fixed with PR #1096. Thanks.

**Comment by frankli0614** [comment]
Verified and passed.

![1082](https://cloud.githubusercontent.com/assets/23302563/20387787/c893608e-acfc-11e6-800e-3101a60e8c8f.png)

**Comment by frankli0614** [comment]
Verified and passed on 0.5.0 rc2 build.
