### ISSUE TITLE
The Cancel button on new user added successfully dialog can be removed.

### ISSUE THREAD

**Issue by frankli0614** [vmware/harbor#1083]
Docker version: 1.12.3
Harbor: 0.4.5

1. Login to Harbor with Admin.
2. Click Admin->Add User
3. Input valid information for Username, Email, Full name, Password and Confirm Password.
4. Click Add button

Actual result: New user added successfully dialog includes OK, Cancel button and x button (Close button) pops up.

Expected Result: The Cancel button is not needed for new user added successfully dialog. It can be removed.

![newuseraddedsuccessfullydialog](https://cloud.githubusercontent.com/assets/23302563/20291278/096af2b8-ab20-11e6-8940-f118b5bee039.png)

**Comment by reasonerjt** [comment]
I would agree, but if time is not enough we delay this issue to after 0.5.0

**Comment by wknet123** [comment]
Fixed with PR #1093

**Comment by frankli0614** [comment]
Verified and passed.

![1083](https://cloud.githubusercontent.com/assets/23302563/20388204/c4611784-acfe-11e6-8030-cee9ad7567d9.png)

**Comment by frankli0614** [comment]
Verified and passed on 0.5.0 rc2 build.
