### ISSUE TITLE
how to modify  cert for my domain

### ISSUE THREAD

**Issue by 272909106** [vmware/harbor#1084]
given setup 
docker 1.11   、docker-compose 1.8.1   ，harbor 0.4.5
********************************************************
#Email account settings for sending out password resetting emails.
email_server = smtp.mail.open.com.cn
email_server_port = 25
email_username = jinxj@mail.open.com.cn
email_password = xxxx
email_from = jinxj@mail.open.com.cn
email_ssl = false
************************************************
#Information of your organization for certificate
crt_country = CN
crt_state = State
crt_location = CN
crt_organization = organization
crt_organizationalunit = organizational unit
crt_commonname = open.com.cn
crt_email = jinxj@mail.open.com.cn
************************************************
i config harbor.cfg ,while  i trying forgot password,the docker_ui.log show "Send email failed: x509: certificate is valid for Root, not smtp.mail.open.com.cn",so i config cert like above,but not success.
how to modify the cert for mail.open.com.cn ??

**Comment by reasonerjt** [comment]
The issue is in the cert of your mail server, which Harbor can do nothing with.

**Comment by 272909106** [comment]
@reasonerjt 
if i have the cert ,where the path of  the replace cert.

**Comment by hainingzhang** [comment]
The problem is in the cert of  mail.open.com.cn. Are you the owner of mail.open.com.cn? It has nothing to do with Harbor.

**Comment by 272909106** [comment]
Using other providers to solve the mail server problems.
Very grateful to everyone who answered, the following is my test results:

**provider**| **ssl**|**reset_password**
---------|---------|------------
open.com.cn|               yes|            no
open.com.cn   |             no      |        no
qq.com            |            yes    |         yes
qq.com             |           no    |          no
163.com            |          no   |           yes
163.com             |         yes |            no
