### ISSUE TITLE
[Feature Request]: Adding function to automatic detect user's browser locale and to display corresponding language in UI

### ISSUE THREAD

**Issue by frankli0614** [vmware/harbor#1086]
Now we can switch UI language by selecting "English" and "中文" in UI. 

It is better to add another function to automatic detect user's browser locale and to display corresponding language in UI.

**Comment by reasonerjt** [comment]
I think the code already covered this right? @wknet123

**Comment by wknet123** [comment]
Yes.
 The sequence is: Cookie, User selected (send request, then response cookie to record), Browser locale settings (when cookie not found, then response cookie to record)

**Comment by frankli0614** [comment]
Yes .I think i can close the issue now.
