### ISSUE TITLE
The color of information text should be RED when input invalid information in New Destination dialog.

### ISSUE THREAD

**Issue by frankli0614** [vmware/harbor#1087]
Docker version: 1.12.3
Harbor: 0.4.5

1. Login to Harbor with Admin.
2. Click Admin Options-> System Management
3. Click New Destination button
4. Leave all textbox as blank
5. Click OK button

Expected Result: The color of information text "Name is required" and "Destination URL is required" should be Red.

NOTE:
1. Same issue happens on Add New Policy dialog

![newdestinationdialog](https://cloud.githubusercontent.com/assets/23302563/20303725/c6d50806-ab67-11e6-8c84-4dc67e9819a3.png)

![addnewpolicyinvalidname url_information](https://cloud.githubusercontent.com/assets/23302563/20303730/ca8b6b84-ab67-11e6-9286-77060378dd95.png)

**Comment by reasonerjt** [comment]
is there any inconsistencies between different dialogs?

**Comment by frankli0614** [comment]
Most of this type of information is red in Harbor UI. Just capture a screenshot of Change Password page for your reference.

![changpasswordpage](https://cloud.githubusercontent.com/assets/23302563/20333126/7247e3f6-abeb-11e6-8b79-5d7f77973ee7.png)

**Comment by wknet123** [comment]
Fixed with PR #1091

**Comment by frankli0614** [comment]
Verified and passed.

![1087-1](https://cloud.githubusercontent.com/assets/23302563/20387993/c7cff044-acfd-11e6-9d23-bb4db99502f0.png)

![1087-2](https://cloud.githubusercontent.com/assets/23302563/20388050/0d48ed74-acfe-11e6-84fd-2eb0fa152905.png)

**Comment by frankli0614** [comment]
Verified and passed on 0.5.0 rc2 build.
