### ISSUE TITLE
Suggest to add Dockerfile in Harbor

### ISSUE THREAD

**Issue by iclouding** [vmware/harbor#1088]
1. Suggest to add Dockerfile view in harbor UI. I put a image to Harbor, but others may not understand its usage only by image's name. 
2. Suggest to add images build from Dockerfile in UI.

**Comment by reasonerjt** [comment]
that sounds like there has to be an cluster for building, for short term I don't think it's in the scope of this project.

**Comment by hainingzhang** [comment]
Thanks for your suggestion. 

It looks like adding a description to the image is more appropriate for this use case. What do you think? 
@clouderding

**Comment by clouderding** [comment]
**@hainingzhang**  嗯，就是这个意思。这样其他人可以更全面了解到该镜像的内容、用途。

**Comment by hainingzhang** [comment]
Sure. We can consider to add this in future release. Thanks for your suggestion. @clouderding

**Comment by reasonerjt** [comment]
Closing as we've supported description.
