### ISSUE TITLE
Harbor service fails to come up when DB password is changed after the firstboot of harbor

### ISSUE THREAD

**Issue by mobla** [vmware/harbor#1103]
Harbor OVA 0.4.5 respin

Steps:
1. Deploy Harbor OVA with root, admin & db password as say 'pASSWORD12345'
2. Later shutdown and change the OVF property to change them to 'password12345'
3. Looks like DB password is hard-wired/encrypted  and changing it breaks the application 
We must document this..
4. Changing the DB password back to original  'pASSWORD12345' and boot the Harbor works fine..

1)Version of docker engine and docker-compose
root@wdc-xxxx-dhcp-xxxx [ ~ ]# docker-compose version
docker-compose version 1.7.1, build 0a9ab35
docker-py version: 1.8.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013

2)Config files of harbor, you can get them by packaging "Deploy/config" directory
attached

3)Log files, you can get them by package the /var/log/harbor/ 
attached

![image](https://cloud.githubusercontent.com/assets/3538999/20371980/08b0d13c-ac1d-11e6-92b4-5e9e86d74c3a.png)

snippet from ui.log
-----------------------
> Nov 16 20:53:38 172.18.0.1 ui[846]: 2016-11-16T20:53:38Z [INFO] Config path: /etc/ui/app.conf
Nov 16 20:53:38 172.18.0.1 ui[846]: 2016-11-16T20:53:38Z [INFO] initializing database: type-MySQL host-mysql port-3306 user-root database-registry
Nov 16 20:53:38 172.18.0.1 ui[846]: 2016-11-16T20:53:38Z [INFO] User id: 1 already has its encrypted password.
Nov 16 20:53:39 172.18.0.1 ui[846]: 2016-11-16T20:53:39Z [DEBUG] [utils.go:246]: Start syncing repositories from registry to DB...
Nov 16 20:53:39 172.18.0.1 ui[846]: 2016-11-16T20:53:39Z [ERROR] [utils.go:445]: failed to connect to registry client, retry after 2 seconds :dial tcp 172.18.0.7:5000: getsockopt: connection refused
Nov 16 20:54:00 172.18.0.1 ui[846]: 2016-11-16T20:54:00Z [INFO] token expiration: 30 minutes
Nov 16 20:54:00 172.18.0.1 ui[846]: 2016-11-16T20:54:00Z [INFO] Config path: /etc/ui/app.conf
Nov 16 20:54:00 172.18.0.1 ui[846]: 2016-11-16T20:54:00Z [INFO] initializing database: type-MySQL host-mysql port-3306 user-root database-registry
Nov 16 20:54:01 172.18.0.1 ui[846]: 2016-11-16T20:54:01Z [ERROR] [mysql.go:79]: failed to connect to db, retry after 2 seconds :dial tcp 172.18.0.4:3306: getsockopt: connection refused
Nov 16 20:54:03 172.18.0.1 ui[846]: 2016-11-16T20:54:03Z [INFO] User id: 1 already has its encrypted password.
Nov 16 20:54:03 172.18.0.1 ui[846]: 2016-11-16T20:54:03Z [DEBUG] [utils.go:246]: Start syncing repositories from registry to DB...
Nov 16 20:54:03 172.18.0.1 ui[846]: 2016-11-16T20:54:03Z [DEBUG] [authutils.go:67]: scopes: [registry:catalog:*]
Nov 16 20:54:03 172.18.0.1 ui[846]: 2016-11-16T20:54:03Z [INFO] current access, type: registry, name:catalog, actions:[*]
Nov 16 20:54:03 172.18.0.1 ui[846]: 2016-11-16T20:54:03Z [DEBUG] [transport.go:51]: 200 | GET http://registry:5000/v2/_catalog?n=1000
Nov 16 20:54:03 172.18.0.1 ui[846]: 2016-11-16T20:54:03Z [DEBUG] [authutils.go:67]: scopes: [repository:project1/powerclicore:]
Nov 16 20:54:03 172.18.0.1 ui[846]: 2016-11-16T20:54:03Z [INFO] current access, type: repository, name:project1/powerclicore, actions:[push * pull]
Nov 16 20:54:03 172.18.0.1 ui[846]: 2016-11-16T20:54:03Z [DEBUG] [transport.go:51]: 200 | GET http://registry:5000/v2/project1/powerclicore/tags/list
Nov 16 20:54:03 172.18.0.1 ui[846]: 2016-11-16T20:54:03Z [DEBUG] [utils.go:308]: Sync repositories from registry to DB is done.
Nov 16 20:54:04 172.18.0.1 ui[846]: 2016/12/16 20:54:04 #033[1;34m[asm_amd64.s:1998][I] http server Running on :80#033[0m
Nov 16 21:08:01 172.18.0.1 ui[5021]: 2016-11-16T21:08:01Z [INFO] current access, type: repository, name:project1/powerclicore, actions:[push * pull]

snippet from proxy.log
-----------------------
> Nov 16 21:21:45 172.18.0.1 proxy[852]: 10.20.85.137 - - [16/Nov/2016:21:21:45 +0000] "GET /api/logs HTTP/1.1" 200 2667 "https://wdc-qead-dhcp-10-139-23-234.eng.vmware.com/dashboard" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"
Nov 16 22:48:21 172.18.0.1 proxy[857]: 2016/11/16 22:48:21 [error] 8#8: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 10.20.85.137, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.3:80/", host: "wdc-qead-dhcp-10-139-23-234.eng.vmware.com"
Nov 16 22:48:21 172.18.0.1 proxy[857]: 10.20.85.137 - - [16/Nov/2016:22:48:21 +0000] "GET / HTTP/1.1" 502 575 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"
Nov 16 22:49:22 172.18.0.1 proxy[857]: 2016/11/16 22:49:22 [error] 8#8: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 10.20.85.137, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.3:80/", host: "wdc-qead-dhcp-10-139-23-234.eng.vmware.com"
Nov 16 22:49:22 172.18.0.1 proxy[857]: 10.20.85.137 - - [16/Nov/2016:22:49:22 +0000] "GET / HTTP/1.1" 502 575 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"
Nov 16 22:55:18 172.18.0.1 proxy[857]: 2016/11/16 22:55:18 [error] 8#8: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 10.20.80.227, server: , request: "GET /repository HTTP/1.1", upstream: "http://172.18.0.3:80/repository", host: "10.139.23.234", referrer: "https://10.139.23.234/project"
Nov 16 22:55:18 172.18.0.1 proxy[857]: 10.20.80.227 - - [16/Nov/2016:22:55:18 +0000] "GET /repository HTTP/1.1" 502 575 "https://10.139.23.234/project" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"
Nov 16 22:55:19 172.18.0.1 proxy[857]: 2016/11/16 22:55:19 [error] 8#8: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 10.20.80.227, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.3:80/favicon.ico", host: "10.139.23.234", referrer: "https://10.139.23.234/repository"
Nov 16 22:55:19 172.18.0.1 proxy[857]: 10.20.80.227 - - [16/Nov/2016:22:55:19 +0000] "GET /favicon.ico HTTP/1.1" 502 575 "https://10.139.23.234/repository" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"

**Comment by reasonerjt** [comment]
As the DB won't be recreated, the DB password should be ignored if it's configured once?

**Comment by ywk253100** [comment]
@reasonerjt We can ignore the password in subsequent boot of Harbor.

**Comment by ywk253100** [comment]
Fixed by #1118 .
