### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by jiangshouzhuang** [vmware/harbor#1105]
> Harbor Envornment Information as following:

Docker: 1.12.3
Harbor: 0.4.5

> harbor.cfg file:

#The IP address or hostname to access admin UI and registry service.
#DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
hostname = xx.xxx.xx.77

#The protocol for accessing the UI and token/notification service, by default it is http.
#It can be set to https if ssl is enabled on nginx.
ui_url_protocol = https

#Email account settings for sending out password resetting emails.
email_server = smtp.mydomain.com
email_server_port = 25
email_username = sample_admin@mydomain.com
email_password = abc
email_from = admin <sample_admin@mydomain.com>
email_ssl = false

#It has no effect after the first launch of Harbor.
#Change the admin password from UI after launching Harbor.
harbor_admin_password = xxxxxxxx

#Set it to ldap_auth if you want to verify a user's credentials against an LDAP server.
auth_mode = db_auth

#The url for an ldap endpoint.
ldap_url = ldaps://ldap.mydomain.com

#A user's DN who has the permission to search the LDAP/AD server. 
#If your LDAP/AD server does not support anonymous search, you should configure this DN and ldap_search_pwd.
#ldap_searchdn = uid=searchuser,ou=people,dc=mydomain,dc=com

#the password of the ldap_searchdn
#ldap_search_pwd = password

#The base DN from which to look up a user in LDAP/AD
ldap_basedn = ou=people,dc=mydomain,dc=com

#Search filter for LDAP/AD, make sure the syntax of the filter is correct.
#ldap_filter = (objectClass=person)

ldap_uid = uid 

#the scope to search for users, 1-LDAP_SCOPE_BASE, 2-LDAP_SCOPE_ONELEVEL, 3-LDAP_SCOPE_SUBTREE
ldap_scope = 3 

#The password for the root user of mysql db, change this before any production use.
db_password = Wanda2016

#Turn on or off the self-registration feature
self_registration = on

#Determine whether the UI should use compressed js files. 
#For production, set it to on. For development, set it to off.
use_compressed_js = on

#Maximum number of job workers in job service  
max_job_workers = 3 

#The expiration time (in minute) of token created by token service, default is 30 minutes
token_expiration = 30

#Determine whether the job service should verify the ssl cert when it connects to a remote registry.
#Set this flag to off when the remote registry uses a self-signed or untrusted certificate.
verify_remote_cert = on

#Determine whether or not to generate certificate for the registry's token.
#If the value is on, the prepare script creates new root cert and private key 
#for generating token to access the registry. If the value is off, a key/certificate must 
#be supplied for token generation.
customize_crt = on

#Information of your organization for certificate
crt_country = CN
crt_state = State
crt_location = CN
crt_organization = organization
crt_organizationalunit = organizational unit
crt_commonname = example.com
crt_email = example@example.com

#The path of cert and key files for nginx, they are applied only the protocol is set to https
ssl_cert = /root/software/docker/harbor/xx.xxx.xx.77.crt
ssl_cert_key = /root/software/docker/harbor/xx.xxx.xx.77.key

> When I edit policy, click "test connections", some issues come:

**Connetion test failed, please check your settings.:Get https://xx.xxx.xx.85/v2/: x509: certificate signed by unknown authority**

But I login in Linux, I can pull images from xx.xxx.xx.85:
[root@cvl-ansi-a01 ~]# docker login xx.xxx.xx.77
Username: admin
Password: 
Login Succeeded
[root@cvl-ansi-a01 ~]# docker pull xx.xxx.xx.77/vmware/harbor-db:0.4.5
0.4.5: Pulling from vmware/harbor-db
Digest: sha256:598ebc05af2fb66c160a64254d96de6a472bc9d3ae20903d10cb014a66d59ea3
Status: Image is up to date for xx.xxx.xx.77/vmware/harbor-db:0.4.5

**Comment by reasonerjt** [comment]
update the harbor.cfg on x.x.x.77:

verify_remote_cert = off

and prepare, and docker-compose down and up, then retry.

**Comment by reasonerjt** [comment]
@jiangshouzhuang any update?

**Comment by jiangshouzhuang** [comment]
@reasonerjt That's OK. Thanks!
We should set verify_remote_cert to off.

**Comment by sundeepk1** [comment]
Can someone please guide what should be done for the same scenario, when we are integrating PKS with harbor registry .. I am unable to login to the harbor registry .
