### ISSUE TITLE
Unable to power on Harbor VM in vSphere 6.5 env

### ISSUE THREAD

**Issue by frankli0614** [vmware/harbor#1114]
Docker version: 1.12.3
Harbor: 0.4.5

OVA: harbor_0.4.5_beta_OVF10.ova

Got an error "The guest operating system 'other3xLinux64Guest' is not support." when powering on Harbor VM in vSphere 6.5 env. 

NOTE:
1.  Deploy harbor_0.4.1_beta.ova and the VM can power on in vSphere 6.5 env.

![error_poweronharborvm_vc6 5](https://cloud.githubusercontent.com/assets/23302563/20386172/6376740e-acf5-11e6-9128-a1c749d467a4.png)

**Comment by wknet123** [comment]
Add download link to UI with PR #1120

**Comment by ywk253100** [comment]
Fixed by changing the OS type.

**Comment by frankli0614** [comment]
Verified and passed on 0.5.0 rc2 build.
