### ISSUE TITLE
Replication failed on OVA deployment while turned OFF the 'verify remote cert' option

### ISSUE THREAD

**Issue by wknet123** [vmware/harbor#1117]
FYI
`2016-11-17T11:14:09Z [INFO] initializing: repository: myproject/ubuntu, tags: [], source URL: http://registry:5000, destination URL: https://pek2-office-05-dhcp255.eng.vmware.com, insecure: false, destination user: admin`
`2016-11-17T11:14:09Z [ERROR] [transfer.go:151]: an error occurred while creating destination repository client: Get https://pek2-office-05-dhcp255.eng.vmware.com/v2/: x509: certificate signed by unknown authority`

**Comment by reasonerjt** [comment]
@wknet123 this is invalid.

**Comment by wknet123** [comment]
When ping target is failed.

**Comment by reasonerjt** [comment]
Yep this is a bug, thanks @wknet123 .

**Comment by reasonerjt** [comment]
To be fixed by #1128, waiting for review @ywk253100

**Comment by reasonerjt** [comment]
Fixed in #1128
