### ISSUE TITLE
[Issue ?] No Publisher Certificate Shown when OVA Import 

### ISSUE THREAD

**Issue by yhua123** [vmware/harbor#1129]
Don't know this is an issue or not?

![untitled](https://cloud.githubusercontent.com/assets/19166125/20470207/3d58a398-afe1-11e6-8fe3-b396f57ace5e.png)

**Comment by hainingzhang** [comment]
This is an known issue

**Comment by yhua123** [comment]
fixed by ova official building process
![pub](https://cloud.githubusercontent.com/assets/19166125/22048325/2789f5c2-dd67-11e6-9a1a-cfdd33d97773.PNG)
