### ISSUE TITLE
Update Harbor version to "0.5.0" in About Harbor dialog.

### ISSUE THREAD

**Issue by frankli0614** [vmware/harbor#1130]
Please update the Harbor version to "0.5.0" in About Harbor dialog.

![harborversion](https://cloud.githubusercontent.com/assets/23302563/20472653/51b9ed1e-aff6-11e6-96bd-9dc93816b5a8.png)

**Comment by yhua123** [comment]
this tag generate by Github status
if github tag 0.5.0 rc or some else, image make process will generate new version label for harbor.

**Comment by frankli0614** [comment]
Verified and passed on 0.5.0 rc1 build .

![about](https://cloud.githubusercontent.com/assets/23302563/20513397/8c215c88-b0c0-11e6-8d87-5fb3562b9049.png)

**Comment by frankli0614** [comment]
Verified and passed on 0.5.0 rc2 build.
