### ISSUE TITLE
[Enhancement] Add Local Language Tips for Foreign Language Switch

### ISSUE THREAD

**Issue by yhua123** [vmware/harbor#1132]
for better user experience
![untitled](https://cloud.githubusercontent.com/assets/19166125/20474752/23497c58-b003-11e6-9cd8-cd2878a6e1f5.png)

like ios:

![untitled](https://cloud.githubusercontent.com/assets/19166125/20474918/ef3665ce-b003-11e6-89f1-37a8f19f988c.png)

**Comment by hainingzhang** [comment]
thanks. but this is probably not necessary for now.
