### ISSUE TITLE
Unable to configure LDAP on harbor_0.5.0_rc1

### ISSUE THREAD

**Issue by vlakshmivenkat** [vmware/harbor#1137]
vic version: vic_0.8.0-rc1
Harbor version: harbor_0.5.0_rc1

1. OVA deploy of Harbor on VC/ESX 6.5 via vSphere Webclient
2. Change to http, DHCP,
3. Configure LDAP with the following values.(Note: This config of LDAP used to work on previous versions of Harbor)

```
LDAP URL: ldap://10.118.97.15
LDAP Search DN: cn=ldapuser1,ou=people,dc=ssotest,dc=com
LDAP Search Password: admin
LDAP Base DN: ou=people,dc=ssotest,dc=com
LDAP UID: cn
```

harbor ui.log snippet : 
```
Nov 21 20:29:55 172.18.0.1 ui[879]: 2016-11-21T20:29:55Z [DEBUG] [authenticator.go:57]: Current AUTH_MODE is ldap_auth
Nov 21 20:29:55 172.18.0.1 ui[879]: 2016-11-21T20:29:55Z [DEBUG] [ldap.go:53]: ldapURL:ldap://10.118.97.15
Nov 21 20:29:55 172.18.0.1 ui[879]: 2016-11-21T20:29:55Z [DEBUG] [ldap.go:64]: baseDn:ou=people,dc=ssotest,dc=com
Nov 21 20:29:55 172.18.0.1 ui[879]: 2016-11-21T20:29:55Z [DEBUG] [ldap.go:68]: Search DN: cn=ldapuser1,ou=people,dc=ssotest,dc=com
Nov 21 20:29:55 172.18.0.1 ui[879]: 2016-11-21T20:29:55Z [DEBUG] [ldap.go:72]: Bind search dn errorLDAP::Bind() error (49) : Invalid credentials
Nov 21 20:29:55 172.18.0.1 ui[879]: 2016-11-21T20:29:55Z [ERROR] [base.go:186]: Error occurred in UserLogin: LDAP::Bind() error (49) : Invalid credentials
```

Attaching logs
[config.tar.gz](https://github.com/vmware/harbor/files/604782/config.tar.gz)
[logs.tar.gz](https://github.com/vmware/harbor/files/604783/logs.tar.gz)

**Comment by vlakshmivenkat** [comment]
Tried two times and was hitting the error. But it worked the second time for my colleague @mobla .

**Comment by sigsbee** [comment]
@vlakshmivenkat  
I have tried connect to the ldap server by apache directory studio, got the same invalid credentials error,maybe there is something wrong with the ldap?
![con2](https://cloud.githubusercontent.com/assets/23101283/20514967/080e75d4-b0ca-11e6-8719-3c6e635f40ef.PNG)

**Comment by vlakshmivenkat** [comment]
My bad. The `LDAP Search Password: admin`  was supplied wrong.  Closing this issue was user error
