### ISSUE TITLE
delete others checkbox in project logs

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#1142]
Harbor0.5.0rc
Will there be other actions besides create, delete, pull and push? the others option seems not necessary

![projlog](https://cloud.githubusercontent.com/assets/23101283/20519715/f6eda800-b0de-11e6-9e68-eb0857ae99c4.PNG)

**Comment by steven-zou** [comment]
As we'll release 1.2 soon, this issue seems out of date, let's close it. If customer think it's a issue, then we can try to fix it.
