### ISSUE TITLE
Extra space on Properties page when Deploy ova via vSphere C# client

### ISSUE THREAD

**Issue by frankli0614** [vmware/harbor#1150]
Docker ova: 0.5.0 rc1

1. Deploy ova via vSphere C# client
2. Go to Properties page without input any information 
3. Observer System section

Actual Result: Extra space between Database Password and Permit Root Login.

NOTE:
1. The space will be disappeared if you type something in root password.

![deployovf_properties_extraspace](https://cloud.githubusercontent.com/assets/23302563/20584608/46f0e654-b22f-11e6-9c7e-452c81046d38.png)

**Comment by hainingzhang** [comment]
C# client is deprecated. We don't need to fix anything.
