### ISSUE TITLE
HTML code shows when test connection on New Destination dialog

### ISSUE THREAD

**Issue by frankli0614** [vmware/harbor#1156]
Docker ova: 0.5.0 rc1

1. Login to Harbor
2. Navigate to Admin Options -> System Management page
3. Click New Destination
4. Input an invalid harbor instance (make sure the protocol for accessing Harbor is http) address (like 10.192.117.215/v5) in Destination URL textbox
5. Click Test connection button with username and password as blank

Actual Result: HTML code shows in New Destination dialog

![newdestination](https://cloud.githubusercontent.com/assets/23302563/20590043/9777db4c-b25b-11e6-8b3b-e2186930063c.png)

**Comment by reasonerjt** [comment]
404?

**Comment by wknet123** [comment]
Fixed with PR #1160

**Comment by frankli0614** [comment]
Verified and passed on 0.5.0 rc2 build.
