### ISSUE TITLE
Got "301 Moved Permanently" error during replication

### ISSUE THREAD

**Issue by frankli0614** [vmware/harbor#1159]
Docker ova: 0.5.0 rc1

**Repro Steps:**
1. Deploy 2 Harbor and make sure the protocol for accessing Harbor is https
Harbor A: **10.160.244.179**
Harbor B: **10.192.104.99**

2. Login to Harbor A (https://10.160.244.179) with Admin user.
3. Navigate to Admin Options -> System Management.
4. Click New Destination.
5. Input 10.192.104.99 (the prefix http:// will be added automatically)in Destination textbox.
6. Input valid information for Name, Username and Password.
7. Click Test connection button => Connection tested successfully.
8. Click OK button.
9. Select a project named **test_l10n**.
10. Switch to Replication page.
11. Click Add New Policy button.
12. Input valid information for Name and Description and make Enabled is checked.
13. Use new created destination in step 8 => Destination URL is http://10.192.104.99 ("http://" is added automatically).
14. Click OK button.

**Actual Result:** 
Got error "Found errors in the current replication jobs, please check" in Harbor UI.From error log, Got "301 Moved Permanently".

Here is the link of the error log
link: https://10.160.244.179/api/jobs/replication/8/log

**Log:**
2016-11-24T09:13:45Z [INFO] initializing: repository: test_l10n/ubuntu, tags: [], source URL: http://registry:5000, destination URL: http://10.192.104.99, insecure: true, destination user: admin
2016-11-24T09:13:45Z [INFO] initialization completed: project: test_l10n, repository: test_l10n/ubuntu, tags: [v1], source URL: http://registry:5000, destination URL: http://10.192.104.99, insecure: true, destination user: admin
2016-11-24T09:13:45Z [ERROR] [transfer.go:209]: an error occurred while creating project test_l10n on http://10.192.104.99 with user admin : failed to create project test_l10n on http://10.192.104.99 with user admin: 301 <html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.11.5</center>
</body>
</html>

**Screenshot:**

![replicationerror](https://cloud.githubusercontent.com/assets/23302563/20593018/94ea1506-b26b-11e6-9860-eabbd8bcfc3e.png)

**Comment by reasonerjt** [comment]
This is because you are using http to access destination B, it should work if you set it to https.
@ywk253100 is it possible to handle it more gracefully?

**Comment by frankli0614** [comment]
Yes, just report it to discuss whether it is an issue or not.

**Comment by ywk253100** [comment]
Golang HTTP client redirects POST request automatically if the response code is 302 and 303. Our nginx responses 301 instead.

**Comment by ywk253100** [comment]
As discussed, this is not an issue.
