### ISSUE TITLE
Failed to docker-compose up

### ISSUE THREAD

**Issue by vcent** [vmware/harbor#116]
when i run "docker-compose up -d"
==
[root@bj-dockercloud-1 Deploy]#  docker-compose up -d
Creating network "deploy_default" with the default driver
ERROR: 404 page not found

how can i fix it, thanks

My env:
CentOS Linux release 7.2.1511 (Core)
docker-compose version 1.7.0, build 0d7bf73
Docker version 1.8.2-el7.centos, build a01dc02/1.8.2

**Comment by reasonerjt** [comment]
you need docker +1.10

**Comment by reasonerjt** [comment]
@vcent please upgrade your docker binary.

**Comment by vcent** [comment]
@reasonerjt  Thanks a lot
