### ISSUE TITLE
Splash screen "Welcome to Harbor" displays when switch from Admin Options page to Dashboard page by clicking Harbor icon at top left corner

### ISSUE THREAD

**Issue by frankli0614** [vmware/harbor#1161]
Docker ova: 0.5.0 rc1

**Repro Steps:**
1. Login to Harbor.
2. Navigate to Admin Options page.
3. Switch to Dashboard page by clicking Harbor icon at top left corner.

**Actual Result:** 
Splash screen "Welcome to Harbor" displays 

**Screenshot:**
![welcometoharbor](https://cloud.githubusercontent.com/assets/23302563/20596203/3b5362d8-b278-11e6-8a72-93d2ab112bed.png)

**Comment by wknet123** [comment]
This is by design to distinguish index page when user has signed into Harbor.
