### ISSUE TITLE
The first letter of some words should be uppercase

### ISSUE THREAD

**Issue by frankli0614** [vmware/harbor#1166]
Harbor ova: 0.5.0 rc1

The first letter of some words should be uppercase. Please see screenshots.

![addnewpolicy_noname](https://cloud.githubusercontent.com/assets/23302563/20617157/36551c54-b322-11e6-8e60-911e403eb3f7.png)

![delete destination](https://cloud.githubusercontent.com/assets/23302563/20617162/38e7af5e-b322-11e6-82f5-dfc7827dba70.png)

![edit account](https://cloud.githubusercontent.com/assets/23302563/20617163/3be021d2-b322-11e6-9ef1-003befb2f7e5.png)

**Comment by hainingzhang** [comment]
please check spelling, "can not" => "cannot" . use format like: "faile to do something: reason".

**Comment by wknet123** [comment]
I think we should normalize error messages from backend by using error code mapping.

**Comment by wknet123** [comment]
Fixed with PR #1254
