### ISSUE TITLE
上传一个名称很长的镜像，界面显示不出来，但是上传和下载都是成功

### ISSUE THREAD

**Issue by guayeguaye** [vmware/harbor#1169]
上传一个名称很长的镜像，界面显示不出来，但是上传和下载都是成功，harbor会有名称长度的限制么

this is my image name  10.30.11.11/test/com.test.service.comm.message:latest

**Comment by wknet123** [comment]
I can't reproduce this issue with your description, please upload some screenshot for this issue.

**Comment by guayeguaye** [comment]
![1](https://cloud.githubusercontent.com/assets/19300958/20654454/7332dcae-b554-11e6-9993-8e9deb563553.png)
push success

![image](https://cloud.githubusercontent.com/assets/19300958/20654465/9fc57092-b554-11e6-9911-e06ad00c96b5.png)

![image](https://cloud.githubusercontent.com/assets/19300958/20654498/03d0499a-b555-11e6-876d-7f3cad3101a3.png)


![2](https://cloud.githubusercontent.com/assets/19300958/20654475/be91e46a-b554-11e6-8dd4-4f227b7f28dd.png)
pull success

**Comment by wknet123** [comment]
It seems you are using an old version of Harbor, please check out the latest release and try again.
