### ISSUE TITLE
Harbor maybe not support images like pattern /a/b/c

### ISSUE THREAD

**Issue by jiangshouzhuang** [vmware/harbor#1179]
1. Docker Environment
Version of docker engine: 1.12.3
Version of docker-compose: 1.8.1

2. Problem Description
when pushing image with path pattern /a/b/c (3 level of depth, with extra b in between), then it will fail;
However, when pushing image with path /a/b (2 level of depth), it is ok.

A sample input is like below:
[root@cvl-dock-a01 bin]# docker push 10.214.96.77/gcr.io/google_containers/kube-apiserver:1.4.6
The push refers to a repository [10.214.96.77/gcr.io/google_containers/kube-apiserver]

5b698d72b887: Preparing 
5f70bf18a086: Preparing 
unauthorized: authentication required

[root@cvl-dock-a01 bin]# docker push 10.214.96.77/gcr.io/kube-apiserver:1.4.6
The push refers to a repository [10.214.96.77/gcr.io/kube-apiserver]
5b698d72b887: Pushed 
5f70bf18a086: Pushed 
e88b3f82283b: Pushed 
1.4.6: digest: sha256:75452acb6fb987fb0ed40a10a50daccf0ce85452b6ffa02a55c41dcf567af309 size: 945

**Comment by hainingzhang** [comment]
we do not support multi-level image name for now. This is working as design.

**Comment by jiangshouzhuang** [comment]
OK. Thanks!

**Comment by nuaays** [comment]
@jiangshouzhuang  pushing 3 level of depth images is allow for me, but this image will not be showed on Harbor UI while acutally it is in registry, and pulling this image from harbor is also ok.
it's just not showed on harbor UI.



### push 3 level of depth image

[root@iZbp1h9mcsfqonyx1mrd4zZ v2]# docker tag registry:2.5.0 10.253.20.65/test/env/registry:2.5.0
[root@iZbp1h9mcsfqonyx1mrd4zZ v2]# docker push 10.253.20.65/test/env/registry:2.5.0
The push refers to a repository [10.253.20.65/test/env/registry]
3bb5bc5ad373: Pushed 
35039a507f7a: Pushed 
d00444e19d65: Pushed 
aa3a31ee27f3: Pushed 
4fe15f8d0ae6: Pushed 
2.5.0: digest: sha256:51d8869caea35f58dd6a2309423ec5382f19c4e649b5d2c0e3898493f42289d6 size: 1363


### pull 3 level of depth image

[root@iZbp1hzc874gjzeex1wexyZ ~]# docker pull 10.253.20.65/test/env/registry:2.5.0
2.5.0: Pulling from test/env/registry
7c563a369b34: Pull complete 
e70be49f2d01: Pull complete 
39b74051b997: Pull complete 
fc188a5e4a4a: Pull complete 
4039be1e17f0: Pull complete 
52fc633e7f0e: Pull complete 
41d63f27d221: Pull complete 
fba3b13a59dc: Pull complete 
e26bb2bff6c0: Pull complete 
Digest: sha256:7ed413bfb20921704479e899cbbff5327a87fc0ccb4d4e8c244e28b9c67ef873
Status: Downloaded newer image for 10.253.20.65/test/env/registry:2.5.0

**Comment by jiangshouzhuang** [comment]
@nuaays Thanks for your answer.
But I want to know what's the project name in you Harbor UI?

**Comment by reasonerjt** [comment]
Closing as this has been fixed.
