### ISSUE TITLE
Comments cannot be saved if press Enter key to add new user when the focus is in Comments text box

### ISSUE THREAD

**Issue by frankli0614** [vmware/harbor#1185]
Docker ova: 0.5.0 rc1

**Repro Steps:**
1. Login to Harbor with Admin user.
2. Click admin -> Add user.
3. Input valid information for Username (like "test"), Email, Full Name, Password, Confirm Password.=> 
4. Click Comments text box and input a comment (like "test")
5. Make sure the focus is in the Comments text box and press Enter button => Add User dialog will pop up to indicate the new user added successfully. 
6. Log out Admin user 
7. Log in Harbor use the new created user.
8. Click test->Account Settings and observe the comments of the user

**Actual Result:** 
The Comments text box is blank. The comment is not saved in step 5.

Screenshots:
![adduser_1](https://cloud.githubusercontent.com/assets/23302563/20701653/35b9d8f4-b64f-11e6-81ab-19f8b8cc451f.png)

![adduser_2](https://cloud.githubusercontent.com/assets/23302563/20701657/3908a792-b64f-11e6-9ffe-1c5298a9c076.png)

![adduser_3](https://cloud.githubusercontent.com/assets/23302563/20701658/3b79f6ca-b64f-11e6-879e-73e20b124947.png)

**Comment by wknet123** [comment]
Fixed with PR #1186
