### ISSUE TITLE
call create project api failed

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#1188]
when I ran the create project command from swagger "curl -X POST --header 'Content-Type: text/plain' --header 'Accept: application/json' -d 'projectname' 'http://localhost/api/projects'  " ,
I received an invalid json request error

**Comment by yhua123** [comment]
please check your json string.

curl -X POST --header 'Content-Type: text/plain' --header 'Accept: text/plain' -d '{
  "project_name": "myproject_0001",
  "public": 0
}' 'http://youripaddress/api/projects'

**Comment by sigsbee** [comment]
it's my mistake that I didn't input data in the correct  format,the value of the project parameter should be a json not a string
