### ISSUE TITLE
不能拆开使用？已经构建了registry的怎么接入ui部分？为什么不把ui放dockerhub上呢？

### ISSUE THREAD

**Issue by Dreampie** [vmware/harbor#119]
不能拆开使用？已经构建了registry的怎么接入ui部分？为什么不把ui放dockerhub上呢？

**Comment by hainingzhang** [comment]
因为Harbor认证部分需要在Registry里面做配置，所以目前不提供单独的接入方式。docker hub对大多数用户比较慢，我们正在国内增加下载镜像。

**Comment by Dreampie** [comment]
毕竟是官方仓库 希望尽快存在一份  源码安装的方式不太好升级维护

**Comment by hainingzhang** [comment]
还有就是涉及license问题，我们暂时不方便把第三方的软件置入镜像中，请谅解。我们会考虑其他一些替代的变通办法。

**Comment by wenxin1234114** [comment]
ldap认证部分一直没有成功，harbor/Deploy/harbor.cfg ，设置 ldap_basedn一直失败，绑定ldap也没有地方设置用户名密码，求指点

**Comment by reasonerjt** [comment]
@wenxin1234114 新问题请开新的issue

**Comment by KeithTt** [comment]
没看太明白，所以楼主拆了吗？
