### ISSUE TITLE
Redundant word "null" shows on New Destination dialog when set Destination URL to Harbor itself.

### ISSUE THREAD

**Issue by frankli0614** [vmware/harbor#1190]
Docker ova: 0.5.0 rc2

**Steps:**
1. Login to Harbor A.
2. Navigate to Admin Options -> System Management page
3. Click New Destination
4. Set Destination URL as Harbor A's IP address.
5. Click Test connection button 

**Actual Result:** 
Redundant word "null" shows on New Destination dialog

**Screenshot:**
![newdestination](https://cloud.githubusercontent.com/assets/23302563/20743617/5f21198c-b712-11e6-8a4a-eb222c152a00.png)

**Comment by wknet123** [comment]
Fixed with PR #1254
