### ISSUE TITLE
All projects or repositories can be shown if searched by semicolon ";".

### ISSUE THREAD

**Issue by frankli0614** [vmware/harbor#1194]
Harbor ova: 0.5.0rc2

**Steps:**
1. Login to Harbor and navigate to Projects.
2. Create some projects 
3. Input symbol ';' in project search textbox.
4. Click Search button.

**Actual result:** All projects can be shown.

**Expected Result:** No projects shown.

**Note:**
1. If search by semicolon in Search projects or repositories textbox, all projects and repositories can be shown.

**Screenshots:** 
![searchbysemicolon](https://cloud.githubusercontent.com/assets/23302563/20782184/60f051ee-b7c4-11e6-80de-65e236c145bc.png)

![searchbysemicolon_projectandrepositories](https://cloud.githubusercontent.com/assets/23302563/20782218/c185875e-b7c4-11e6-898c-bff33064b390.png)

**Comment by ywk253100** [comment]
The root cause is that the semicolon in query string is not encoded and is regard as a delimiter of attrs.

**Comment by wknet123** [comment]
separated by semicolons ";" This is matrix URL notation 
Matrix URL notation is an idea first floated in a 1996 proposal by the founder of the web, Tim Berners-Lee.
Although matrix notation never made it into the HTML standard, it is legal and it became popular among browser routing systems as a way to isolate parameters belonging to parent and child routes.

**Comment by hainingzhang** [comment]
please see if there is a quick fix for this.

**Comment by wknet123** [comment]
Fixed with PR #1198

**Comment by reasonerjt** [comment]
@steven-zou Please double check if this issue still exists.

**Comment by steven-zou** [comment]
Existing a long time, as it was fixed, close it.
