### ISSUE TITLE
Access Harbor Api occur Unauthorized

### ISSUE THREAD

**Issue by JoshuaAndrew** [vmware/harbor#1199]
Harbor Version v0.4.5

`Unexpected code Response{protocol=http/1.1, code=401, message=Unauthorized, url=http://192.168.2.129/api/users}`

Is there any login api?

**Comment by yhua123** [comment]
what's your request? in code or using swagger?
you can setting basic auth for your request.
or login on UI and then using the curl visit API.

**Comment by JoshuaAndrew** [comment]
@yhua123 

I request Harbor Api in code!

How can I set basic auth for my request in code?

**Comment by JoshuaAndrew** [comment]
@yhua123  Thanks a lot  ^_^

I figured out !

```
	OkHttpClient client = new OkHttpClient();
	String credential = Credentials.basic("admin", "Harbor12345");
	Request request = new Request.Builder()
			.url("http://192.168.2.129/api/users")
			.header("Authorization", credential)
			.build();
	Response response = client.newCall(request).execute();
```

**Comment by yhua123** [comment]
our API UT also did that;
src/ui/api/harborapi_test.go

**Comment by reasonerjt** [comment]
Thanks guys
