### ISSUE TITLE
Harbor doesn't support  pull cache as a mirror registry

### ISSUE THREAD

**Issue by int32bit** [vmware/harbor#120]
We use harbor as our private registry, but it seems that harbor has not supported pull cache yet. If I pull an image which doesn't exist in the harbor, the image can't be cached 
automatically. To configure a registry to run as a pull through cache, the addition of a proxy section is required to the config file(`config.yml`),see https://github.com/docker/distribution/blob/master/docs/mirror.md

**Comment by hainingzhang** [comment]
When enabling the mirror pulling features, the registry's original push/pull does not work any more. So that's why Harbor does not support mirror for now. We may consider a feature to support mirror in the future.

**Comment by int32bit** [comment]
The registry's original push/pull does not work any more, we have not test it yet. If it's true,I think it can be configured as option. @hainingzhang

**Comment by hainingzhang** [comment]
yes, it could be a feature that the registry serves as a mirror only, not a "normal" registry. We will consider to put this in our roadmap.

**Comment by int32bit** [comment]
We don't understand why the registry's original push/pull does not work any more if enabling the mirror pulling features. In fact, I modify the  `harbor/Deploy/config/registry/config.yml` manually and append `proxy` to enable pull cache according to [official documents](https://github.com/docker/distribution/blob/master/docs/mirror.md), it works fine！

**Comment by vergilchiu** [comment]
yes,if modifying the `harbor/Deploy/config/registry/config.yml` manually and append `proxy`,it can pull cache from docker-hub,but i can't push my image to pivate registry

**Comment by tyhoho** [comment]
same scenario with @vergilchiu, it can sucessfully pulling images and caching, but fails with pushing images to private registry
Anybody is looking into this issue?

**Comment by reasonerjt** [comment]
I believe this is a limitation in docker registry, see #220

**Comment by tyhoho** [comment]
@reasonerjt Thanks! This helps a lot! I've been searching this issue a while.
