### ISSUE TITLE
Failed to disable replication policy

### ISSUE THREAD

**Issue by onecool2** [vmware/harbor#1206]
1) **Docker version and Docker-compose version:**
 #docker version
 Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64
 Experimental: true

 Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64
 Experimental: true

#docker-compose version
docker-compose version 1.9.0, build 2585387
docker-py version: 1.10.6
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

2) **Config files: I didn't modify anything in the configure file excepte the hostname**
3) **Log files, I put UI.log here**
Dec  4 03:20:32 172.18.0.1 ui[26532]: 2016/13/04 08:20:32 #033[1;34m[router.go:829][D] | GET        | /api/projects                            | 5.89476ms        | match      | /api/projects/                           | #033[0m
Dec  4 03:20:32 172.18.0.1 ui[26532]: 2016/13/04 08:20:32 #033[1;34m[router.go:829][D] | GET        | /api/policies/replication/               | 4.916276ms       | match      | /api/policies/replication                | #033[0m
Dec  4 03:20:32 172.18.0.1 ui[26532]: 2016/13/04 08:20:32 #033[1;34m[router.go:829][D] | GET        | /api/projects/2/members/current          | 5.64084ms        | match      | /api/projects/:pid([0-9]+)/members/?:mid | #033[0m
Dec  4 03:20:33 172.18.0.1 ui[26532]: 2016/13/04 08:20:33 #033[1;34m[router.go:829][D] | GET        | /api/jobs/replication/                   | 5.001953ms       | match      | /api/jobs/replication/                   | #033[0m
Dec  4 03:20:36 172.18.0.1 ui[26532]: 2016/13/04 08:20:36 #033[1;34m[router.go:829][D] | GET        | /api/jobs/replication/                   | 5.436136ms       | match      | /api/jobs/replication/                   | #033[0m
Dec  4 03:20:56 172.18.0.1 ui[26532]: 2016/13/04 08:20:56 #033[1;34m[router.go:829][D] | GET        | /api/projects/2/members/current          | 6.228499ms       | match      | /api/projects/:pid([0-9]+)/members/?:mid | #033[0m
Dec  4 03:20:56 172.18.0.1 ui[26532]: 2016/13/04 08:20:56 #033[1;34m[router.go:829][D] | GET        | /api/projects/2/members                  | 5.800606ms       | match      | /api/projects/:pid([0-9]+)/members/?:mid | #033[0m
Dec  4 03:21:01 172.18.0.1 ui[26532]: 2016/13/04 08:21:01 #033[1;34m[router.go:829][D] | GET        | /api/policies/replication/               | 5.557593ms       | match      | /api/policies/replication                | #033[0m
Dec  4 03:21:01 172.18.0.1 ui[26532]: 2016/13/04 08:21:01 #033[1;34m[router.go:829][D] | GET        | /api/projects/2/members/current          | 6.835906ms       | match      | /api/projects/:pid([0-9]+)/members/?:mid | #033[0m
Dec  4 03:21:01 172.18.0.1 ui[26532]: 2016/13/04 08:21:01 #033[1;34m[router.go:829][D] | GET        | /api/jobs/replication/                   | 4.911523ms       | match      | /api/jobs/replication/                   | #033[0m
Dec  4 03:21:04 172.18.0.1 ui[26532]: 2016/13/04 08:21:04 #033[1;34m[router.go:829][D] | GET        | /api/projects/2/members/current          | 6.289643ms       | match      | /api/projects/:pid([0-9]+)/members/?:mid | #033[0m
Dec  4 03:21:05 172.18.0.1 ui[26532]: 2016/13/04 08:21:05 #033[1;34m[router.go:829][D] | GET        | /api/repositories                        | 3.068584ms       | match      | /api/repositories                        | #033[0m
Dec  4 03:21:06 172.18.0.1 ui[26532]: 2016-12-04T08:21:06Z [DEBUG] [authutils.go:49]: scopes: [repository:replication1/oracle_systemd:pull,push,*]
Dec  4 03:21:06 172.18.0.1 ui[26532]: 2016-12-04T08:21:06Z [INFO] current access, type: repository, name:replication1/oracle_systemd, actions:[push * pull]
Dec  4 03:21:06 172.18.0.1 ui[26532]: 2016-12-04T08:21:06Z [DEBUG] [transport.go:51]: 200 | GET http://registry:5000/v2/replication1/oracle_systemd/tags/list
Dec  4 03:21:06 172.18.0.1 ui[26532]: 2016/13/04 08:21:06 #033[1;34m[router.go:829][D] | GET        | /api/repositories/tags                   | 85.229667ms      | match      | /api/repositories/tags                   | #033[0m
Dec  4 03:21:12 172.18.0.1 ui[26532]: 2016/13/04 08:21:12 #033[1;34m[router.go:829][D] | GET        | /api/policies/replication/               | 5.763943ms       | match      | /api/policies/replication                | #033[0m
Dec  4 03:21:12 172.18.0.1 ui[26532]: 2016/13/04 08:21:12 #033[1;34m[router.go:829][D] | GET        | /api/projects/2/members/current          | 6.407073ms       | match      | /api/projects/:pid([0-9]+)/members/?:mid | #033[0m
Dec  4 03:21:12 172.18.0.1 ui[26532]: 2016/13/04 08:21:12 #033[1;34m[router.go:829][D] | GET        | /api/jobs/replication/                   | 5.573123ms       | match      | /api/jobs/replication/                   | #033[0m
Dec  4 03:21:14 172.18.0.1 ui[26532]: 2016/13/04 08:21:14 #033[1;34m[router.go:829][D] | GET        | /api/jobs/replication/                   | 5.981703ms       | match      | /api/jobs/replication/                   | #033[0m
Dec  4 03:21:20 172.18.0.1 ui[26532]: 2016/13/04 08:21:20 #033[1;34m[router.go:829][D] | GET        | /api/jobs/replication/                   | 5.743506ms       | match      | /api/jobs/replication/                   | #033[0m
                                
BTW: I copied a picture from my browser when I click the "disable"
![screenshot](https://cloud.githubusercontent.com/assets/24353734/20865003/eb713350-ba40-11e6-959c-bb2601ca918e.png)
 button

**Comment by onecool2** [comment]
Complete the environment: my setup is under the company LAN, so my browser has proxy setting , after I disable the proxy, this issuse disappear.

**Comment by reasonerjt** [comment]
Closing this issue since it's env issue, the 403 is probably returned by proxy.
