### ISSUE TITLE
ldap_auth failed

### ISSUE THREAD

**Issue by wenxin1234114** [vmware/harbor#121]
I tried ldap_auth config many times ,all failed .
do you have sample ?

**Comment by int32bit** [comment]
Please refer [my post](http://int32bit.github.io/2016/04/18/docker%E9%95%9C%E5%83%8F%E4%BB%93%E5%BA%93harbor%E5%BF%AB%E9%80%9F%E9%83%A8%E7%BD%B2%E5%92%8C%E4%BD%BF%E7%94%A8/).

**Comment by wenxin1234114** [comment]
AD用公司的统一的，按照模板配置不行，不知道哪里出了问题

**Comment by wenxin1234114** [comment]
[ERROR] [token.go:77]: Error occurred in UserLogin: LDAP::Bind() error (49) : Invalid credentials

**Comment by wknet123** [comment]
是否写对了ldap_url的ldaps和 ldap协议部分

**Comment by wenxin1234114** [comment]
一个是加密一个是不加密 吧

**Comment by wknet123** [comment]
是的，要看服务端支持哪一个。

**Comment by wenxin1234114** [comment]
不加密 我们是支持的

**Comment by wknet123** [comment]
可以发一段当前harbor.cfg文件里的 ldap_url 和 ldap_basedn配置吗？

**Comment by wenxin1234114** [comment]
auth_mode = ldap_auth
ldap_url = ldap://ldap.test.org
ldap_basedn = uid=%s,dc=test-inc,dc=com

**Comment by reasonerjt** [comment]
have you tried to use ldapsearch to bind user?   Could you show us the command?

**Comment by wenxin1234114** [comment]
ldapsearch -h ldap.test.org -x -W -b 'dc=test-inc,dc=com' -D 'CN=test1,OU=测试账号(启用),OU=测试服务账户,DC=test-inc,DC=com' '(sAMAccountName=test1)'

**Comment by reasonerjt** [comment]
Did you try this?
ldap_basedn = cn=%s,dc=test-inc,dc=com

**Comment by wenxin1234114** [comment]
still doesn't work
[ERROR] [login.go:54]: Error occurred in UserLogin: LDAP::Bind() error (49) : Invalid credentials

**Comment by hainingzhang** [comment]
From your ldapsearch command, it seems the basedn should be: 

CN=%s,OU=测试账号(启用),OU=测试服务账户,DC=test-inc,DC=com

But we have not tested whether Chinese characters work in the template, maybe you can try UTF-8 encoding of Chinese characters.

**Comment by wenxin1234114** [comment]
用中文帐号才能登录 ，拼音不行，我看看代码去。。

**Comment by wenxin1234114** [comment]
注释了ldap.go中77行-101行代码 ,修改了如Username和Email，Realname部分：
`	u.Username = m.Principal
	u.Email = m.Principal + "@test.com"
	u.Realname = m.Principal`

**Comment by reasonerjt** [comment]
@wenxin1234114 多谢更新
所以您后来没有再遇到ldap bind失败的问题？那么在harbor.cfg中 basedn是如何设置的？

**Comment by ghoul008** [comment]
同样遇到这个问题，ldap未加密，在别的系统是可以用的。
May  3 17:23:12 localhost docker/ui[8959]: 2016-05-03T09:23:12Z [DEBUG] [authenticator.go:52]: Current AUTH_MODE is ldap_auth
May  3 17:23:12 localhost docker/ui[8959]: 2016-05-03T09:23:12Z [DEBUG] [ldap.go:47]: ldapURL:ldap://10.1.130.13
May  3 17:23:12 localhost docker/ui[8959]: 2016-05-03T09:23:12Z [DEBUG] [ldap.go:69]: baseDn:uid=shaozp,ou=people,dc=asiainfo,dc=com
May  3 17:23:12 localhost docker/ui[8959]: 2016-05-03T09:23:12Z [ERROR] [login.go:57]: Error occurred in UserLogin: LDAP::Bind() error (49) : Invalid credentials

**Comment by nagarjung** [comment]
+1

**Comment by reasonerjt** [comment]
@ghoul008  could you let me know your ldapsearch command to bind the user??

**Comment by nagarjung** [comment]
@reasonerjt 
ldapsearch -h ldap.xxxx.com  -b "uid=bmtrac,ou=Employees,dc=xxxx,dc=com" -x

This works for me

Thank you

**Comment by ghoul008** [comment]
@reasonerjt 我发现个问题，是不是在harbor.cfg里面需要指定389端口啊(未加密)。
@nagarjung 你的这配的ldap，然后日志看的是ldaps?

**Comment by ghoul008** [comment]
集成成功了，我真醉了。
大家指定ldap时加上端口
大家指定basecn时候记得用cn不要用uid.......

**Comment by reasonerjt** [comment]
@ghoul008  
1)the basedn setting depends on the configuration of your ldap server.
2)Are you saying without setting the port it will return Invalid Credential error in log???
How did you update harbor.cfg?
did you set it to:  **ldap_url = ldap://ldap.mydomain.com:389** ?
3)I don't think @nagarjung understands what you are saying, he doesn't seem to speak Chinese...

**Comment by nagarjung** [comment]
@reasonerjt @ghoul008 

Yes i dont understand chinese... Also proper translation was not happening, thats the reason i was unable to understand @ghoul008  . But re-configuring harbor on a new machine without giving the port worked for me. Earlier i tried with various combinations for ldap url and basedn which dint work for me. In this case i used to run ./prepare binary everytime i make changes to my harbor.cfg and restart containers using docker-compose. Seems like configuration was not affecting the change.

But when I tried with new machine without port worked me. 

Thank you

**Comment by ghoul008** [comment]
@reasonerjt yes,set "ldap_url = ldap://ldap.mydomain.com:389" like this is work.used add port.
@nagarjung sry guy first,why you can get "ldapURL:ldaps://ldap.xxxx.com:389" in your log when you set "ldap_url = ldap://ldap.xxxx.com"  in "harbor.cfg". it's encrypted or not.
I suggest you set like this and try again.

configuration:

ldap_url = ldap://ldap.xxxx.com:389
ldap_basedn = cn=%s,ou=Employees,dc=xxxx,dc=com

if you wanted your new configuration worked,I think you shoud rm your  container and images(rm /data/* yet),rebuild again,it's worked for me.

Praise the Chinese,Ha, ha...

**Comment by maksonlee** [comment]
is it possible to use uid as username? maybe find out cn by uid, then authenticate to ldap with cn?

**Comment by g0194776** [comment]
@ghoul008 

It still not works for me even I've set the harbor.cfg: CN=%s.
When login with LDAP in my company, we always use the email as username.
which like that at blow:
>NAME@xxx.com

Can u have more suggestions about that?
The harbor returned "Invalid Credentials" every time when I try to logon the system.
