### ISSUE TITLE
使用RESTful API提示Couldn't find env file

### ISSUE THREAD

**Issue by zhaogj1987** [vmware/harbor#1219]
参照这地方进行安装https://github.com/vmware/harbor/blob/master/docs/configure_swagger.md
在进行docker-compose build时有报Couldn't find env file错

**Comment by yhua123** [comment]
I guess not run `./prepare` first.
By default configure swagger after successful install harbor.
Reference: https://github.com/vmware/harbor/blob/master/docs/compile_guide.md#iii-manual-build-process-compatible-with-previous-versions

**Comment by yhua123** [comment]
@zhaogj1987 
It's ok?

**Comment by zhaogj1987** [comment]
yes,Thank you very much for your help
