### ISSUE TITLE
Harbor 0.1.0 Beta how to enable https

### ISSUE THREAD

**Issue by wenxin1234114** [vmware/harbor#1220]
1.edit harbor.cfg :ui_url_protocol = https
2.edit nginx.https.conf,add domain cert 

but in docker nginx ,can not start 443 port 

how to fix ?

**Comment by hainingzhang** [comment]
can you upgrade to newer version of harbor? 0.1.0 is not supported any more. you can trace the document in the early history. 
https://github.com/vmware/harbor/blob/master/docs/configure_https.md
