### ISSUE TITLE
replication failure

### ISSUE THREAD

**Issue by biolounge** [vmware/harbor#1227]
Hi,

I am trying to setup a replication from Harbor 0.3.5 instance to 0.5.0 instance.

The replication job service is failing with following error:

job.service.log (source)
_Dec  8 16:59:14 172.18.0.1 jobservice[17893]: 2016-12-08T15:59:14Z [WARNING] Job id: 6, the statemachin will enter error state due to error: failed to create project fact-containers on http://destination.com with user tester: 400 Invalid json request
Dec  8 16:59:14 172.18.0.1 jobservice[17893]: 2016-12-08T15:59:14Z [DEBUG] [statemachine.go:62]: Job id: 6, transiting from State: initialize, to State: error
Dec  8 16:59:14 172.18.0.1 jobservice[17893]: 2016-12-08T15:59:14Z [DEBUG] [statemachine.go:89]: Job id: 5, transition succeeded, current state: error
Dec  8 16:59:14 172.18.0.1 jobservice[17893]: 2016-12-08T15:59:14Z [DEBUG] [statemachine.go:89]: Job id: 6, transition succeeded, current state: error_

registry.log (destination)

_Dec  8 16:59:01 172.18.0.1 registry[1180]: time="2016-12-08T15:59:01.193945675Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.6.3 http.request.host=DestinationIP http.request.id=b1a03c48-3691-440e-aa1f-67ac7ae009d7 http.request.method=GET http.request.remoteaddr=SourceIP http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=4301db03-67b1-46de-be3f-b227b312ceb8 service=registry version=v2.5.0_

The replication LDAP user is available on both source and destination sites. This user also can successfully create project from web UI.
  
Is there a way to fix this replication issue?

************************************************************
Docker version: 
_Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec_

Docker compose: 
_docker-compose version 1.9.0, build 2585387_

**Comment by reasonerjt** [comment]
I think this is a known issue due to API incompatibility?

**Comment by ywk253100** [comment]
@reasonerjt Yes. It's the incompatibility of API. 
@biolounge Please refer to the user guide https://github.com/vmware/harbor/blob/master/docs/user_guide.md#replicating-images.
