### ISSUE TITLE
LDAP Library used is deprecated

### ISSUE THREAD

**Issue by rikatz** [vmware/harbor#1228]
According to the OpenLDAP library used on Harbor project (https://github.com/mqu/openldap), it's deprecated and the maintainer is not going to continue it's development.

This brings some other non desirable behaviour, as not supporting StartTLS, non configurable dial timeout (this brings a lot of problems when you try to pull an image from an anonymous repository) and limits a future work to support LDAP Group (and a lot of other problems).

Fortunatelly, there is another library (that is much more updated) here: https://github.com/go-ldap/ldap

So, this issue is to register an attempt to migrate from the old library to a new one. I'm going to open a PR submitting changes to this, and then some other commits to solve the "TODO" marked on the code.

Any suggestion? :smile:

**Comment by yhua123** [comment]
@rikatz 
Thank you for your recommend~ 
We already start working on this. Will update LDAP library soon.
#1136

**Comment by rikatz** [comment]
Solved in the PR, closing the issue.
