### ISSUE TITLE
Install scripts for 0.5.0

### ISSUE THREAD

**Issue by bergtwvd** [vmware/harbor#1230]
I have placed all of my data (registry, database, logs) under:
/var/lib/harbor/data
/var/log/harbor

My certs are under /home/bergtwvd/certs

The install scripts assume however directory "/data" for all.

With the prepare script I can set an alternate location with --data-volume, but this applies just to the certs.

The install script always assumes /data, as it calls prepare without arguments. So I need to patch the scripts to make them work.

So, my request is:
- make the scripts more flexible so that I can specify the location of my certs, logs, and data
- allow for certs, logs and data to be stored in different directories

**Comment by onecool2** [comment]
Hi bergtwvd
Did you check the yml file which used by docker-compose?

**Comment by yhua123** [comment]
@bergtwvd 
The install.sh only support standard install. I think maybe need one item in harbor.cfg for specific data restore.

**Comment by yhua123** [comment]
#1237

**Comment by bergtwvd** [comment]
I had to adapt the docker compose file too, to point to the right directories.
I thing the scripts should assume that information is stored in different places:
- certs
- registry data
- logs

**Comment by yhua123** [comment]
Thanks for your recommends.
Till now we don't have any script render docker compose file, so registry/log/database data storage needs to modify docker compose file manually. 
Your request will mark as a new requirement in later release.

**Comment by reasonerjt** [comment]
I don't think we'll provide that flexibility to `docker-compose` based installation.
