### ISSUE TITLE
kubernetes can't pull image from Harbor

### ISSUE THREAD

**Issue by hongtao12310** [vmware/harbor#1238]
i can pull the docker image from harbor use the docker client. the steps are
1) docker login HarborIP
2) docker pull HarborIP/library/nginx:1.9

but we can't pull the image from harbor by use kubectl create -f nginx-app.yaml

the part of content of the yaml as below:
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # the node selector can assign the pod to the specific nodes
      nodeSelector:
        nginx: "true"
      containers:
      - name: nginxhttps
        image: 10.214.96.77/library/nginx:1.9
        imagePullPolicy: IfNotPresent #IfNotPresent, Always
        ports:
        - containerPort: 443
        - containerPort: 80

1. docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

2. Harbor log /var/log/Harbor
Dec 12 14:50:31 172.18.0.1 registry[25937]: time="2016-12-12T06:50:31.971344966Z" level=debug msg="authorizing request" go.version=go1.6.3 http.request.host=10.214.96.77 http.request.id=9ca77180-ff39-4df7-80af-13a363a9a44f http.request.method=GET http.request.remoteaddr=10.213.58.203 http.request.uri="/v2/" http.request.useragent="docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" instance.id=b4fa65a0-30af-495c-ac18-a5a1def78cbd service=registry version=v2.5.0
Dec 12 14:50:31 172.18.0.1 registry[25937]: time="2016-12-12T06:50:31.971540196Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.6.3 http.request.host=10.214.96.77 http.request.id=9ca77180-ff39-4df7-80af-13a363a9a44f http.request.method=GET http.request.remoteaddr=10.213.58.203 http.request.uri="/v2/" http.request.useragent="docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" instance.id=b4fa65a0-30af-495c-ac18-a5a1def78cbd service=registry version=v2.5.0
Dec 12 14:50:31 172.18.0.1 registry[25937]: 172.18.0.7 - - [12/Dec/2016:06:50:31 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)"
Dec 12 14:51:00 172.18.0.1 registry[25937]: time="2016-12-12T06:51:00.923819759Z" level=debug msg="authorizing request" go.version=go1.6.3 http.request.host=10.214.96.77 http.request.id=3d68eec4-9ba8-45cf-aa04-46d4ba69fdb5 http.request.method=GET http.request.remoteaddr=10.213.58.203 http.request.uri="/v2/" http.request.useragent="docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" instance.id=b4fa65a0-30af-495c-ac18-a5a1def78cbd service=registry version=v2.5.0
Dec 12 14:51:00 172.18.0.1 registry[25937]: time="2016-12-12T06:51:00.924016713Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.6.3 http.request.host=10.214.96.77 http.request.id=3d68eec4-9ba8-45cf-aa04-46d4ba69fdb5 http.request.method=GET http.request.remoteaddr=10.213.58.203 http.request.uri="/v2/" http.request.useragent="docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" instance.id=b4fa65a0-30af-495c-ac18-a5a1def78cbd service=registry version=v2.5.0
Dec 12 14:51:00 172.18.0.1 registry[25937]: 172.18.0.7 - - [12/Dec/2016:06:51:00 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)"

**Comment by reasonerjt** [comment]
The issue is how to login to Harbor (or other image registry) in k8s.
See: http://kubernetes.io/docs/user-guide/images/
