### ISSUE TITLE
Failed to get catalog of hundreds of repositories with timeout error. (storage: oss)

### ISSUE THREAD

**Issue by ScorpioCPH** [vmware/harbor#1239]
I think we should remove timeout option of http client from `src/common/utils/registry/registry.go`.

I have tested it, I will open a PR later.

**Comment by reasonerjt** [comment]
Thanks, please proceed.

**Comment by reasonerjt** [comment]
This can be closed? @ScorpioCPH

**Comment by ScorpioCPH** [comment]
Yes.
