### ISSUE TITLE
Cannot install VMware Harbor 0.3.5 anymore

### ISSUE THREAD

**Issue by biolounge** [vmware/harbor#1241]
I am trying to install a new instance of VMware 0.3.5 to test the upgrade procedure before I do the real production upgrade. After I installed VMware 0.3.5 from source, I noticed that the site design is completely broken and even login text box is not showing. Its always downloading 0.5.0 docker images.  See the attached screenshot of the web UI.

Any idea, how can I fix it or it's not possible to install VMware 0.3.5 anymore?

Docker version: 1.12.3
Docker compose: 1.9.0
![capture3](https://cloud.githubusercontent.com/assets/11211830/21136204/f962aa3a-c124-11e6-9180-7dfbe8fd1aa5.PNG)

**Comment by reasonerjt** [comment]
looks like a issue of cached page? @wknet123 
@biolounge could you please try to clean the history of your browser and refresh?

**Comment by hainingzhang** [comment]
what did you mean by downloading images of 0.5.0? Did you build 0.3.5 from source?

**Comment by biolounge** [comment]
@reasonerjt: Indeed. It was a caching issue.
