### ISSUE TITLE
Harbor 0.5 upgrade and database migration guide

### ISSUE THREAD

**Issue by gunboe** [vmware/harbor#1242]
Hello all,
I have tried upgrade Harbor 0.4.5 to 0.5, but I've found some issues. Has there been any schema or structure changed on new release?
I think the migration guide (https://github.com/vmware/harbor/blob/master/docs/migration_guide.md) is Out of date, isn't?
Thank you.

**Comment by reasonerjt** [comment]
There's no change in schema from 0.4.5 to 0.5.0, why you think the guide is out of date?

**Comment by gunboe** [comment]
Cause, I've tried migrate, but fail and unexpected behaviours was returned. I'll try again and report that errors. thank.

**Comment by gunboe** [comment]
Upgrade 0.4.5 to 0.5.0 is ok, but you must clean up the Cache and Cookies from Browser.
