### ISSUE TITLE
401 returned from /api/targets/ping with basic auth

### ISSUE THREAD

**Issue by Fly-Luck** [vmware/harbor#1246]
docker engine version: 1.10.3
docker-compose version: 1.8.0
harbor version: 0.4.1

I have 2 harbor instances running in 2 VMs(harbor A & harbor B), both using basic auth with Apache htpasswd. I need to use basic auth instead of token service provided by harbor.

1. Create the htpasswd file
```
htpasswd -c htpasswd admin
[enter password]
```

2. Configurate the registry's config yaml
./config/registry/config.yml
...auth part:
```
auth:
  htpasswd:
    realm: Registry Realm
    path: /etc/registry/conf/htpasswd
```
and other configs like volumes in docker-compose.yml, hostname(ip in my case) and password in harbor.cfg, etc.

3. When both instances are running, I used curl to call their apis, e.g.
```
curl -i -u admin -H "Content-type: application/json" -XPOST -d '{"endpoint":"[harbor B ip:port]","name":"to-B","password":"[password]","username":"admin"}' http://[harbor A ip:port]/api/targets
[enter password]
```
201 was returned and I can see the target from UI of harbor A.
Other apis such as creating/deleting a project also worked fine.

4. However when I tried to ping this target with the same credential it returns 401 unauthorized error.
```
curl -i -u admin -XPOST -d '' [harbor A ip:port]/api/targets/ping?id=1
[enter password]
```
and from the logs in /var/log/harbor, I can see something like the following:
```
"GET /v2/ HTTP/1.1" 401 87 "-" "Go-http-client/1.1"
```

Ping target failure means replication policy cannot work. Any idea what the cause is?

Any help would be appreciated!

**Comment by ywk253100** [comment]
Harbor supports token authentication for registry only.

**Comment by Fly-Luck** [comment]
> Harbor supports token authentication for registry only.

Thanks for your reply, so there is no way to use basic auth to access registry api with harbor I assume?

Because of some network restrict in our deploy environment, we are unable to use the token service of harbor. I'll open another issue if possible.

btw can I use external token service instead?

**Comment by zeyangli** [comment]
I found a problem, which is very similar to this one.  please help me

harbor 1.7.5
```
[root@gitlab-server harbor]# curl -i -u admin:Harbor12345 -XPOST -d '{"id": 1}' http://192.168.10.130:808/api/targets/ping -H "Content-t
ype: application/json"HTTP/1.1 400 Bad Request
Server: nginx
Date: Wed, 17 Apr 2019 05:45:05 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 22
Connection: keep-alive
Set-Cookie: sid=4aa6cdcd4f1c96f3feb6fe186f379634; Path=/; HttpOnly
X-Content-Type-Options: nosniff

failed to ping target

```


```
Apr 17 01:44:55 172.18.0.1 proxy[7634]: 172.18.0.1 - "GET /v2/ HTTP/1.1" 401 87 "-" "Go-http-client/1.1" 0.007 0.007 .
Apr 17 01:44:57 172.18.0.1 proxy[7634]: 127.0.0.1 - "GET / HTTP/1.1" 200 693 "-" "curl/7.59.0" 0.001 0.001 .
Apr 17 01:45:05 172.18.0.1 proxy[7634]: 192.168.10.130 - "POST /api/targets/ping HTTP/1.1" 400 22 "-" "curl/7.29.0" 10.021 10.021 .
```

**Comment by zeyangli** [comment]
```
auth:
  token:
    issuer: harbor-token-issuer
    realm: http://hrbor.example.com/service/token
    rootcertbundle: /etc/registry/root.crt
    service: harbor-registry

```

**Comment by zeyangli** [comment]
![image](https://user-images.githubusercontent.com/21000263/56263935-6c434200-6117-11e9-8ff7-cda0fd7cbc8b.png)

**Comment by Wang-Kai** [comment]
> I found a problem, which is very similar to this one. please help me
> 
> harbor 1.7.5
> 
> ```
> [root@gitlab-server harbor]# curl -i -u admin:Harbor12345 -XPOST -d '{"id": 1}' http://192.168.10.130:808/api/targets/ping -H "Content-t
> ype: application/json"HTTP/1.1 400 Bad Request
> Server: nginx
> Date: Wed, 17 Apr 2019 05:45:05 GMT
> Content-Type: text/plain; charset=utf-8
> Content-Length: 22
> Connection: keep-alive
> Set-Cookie: sid=4aa6cdcd4f1c96f3feb6fe186f379634; Path=/; HttpOnly
> X-Content-Type-Options: nosniff
> 
> failed to ping target
> ```
> 
> ```
> Apr 17 01:44:55 172.18.0.1 proxy[7634]: 172.18.0.1 - "GET /v2/ HTTP/1.1" 401 87 "-" "Go-http-client/1.1" 0.007 0.007 .
> Apr 17 01:44:57 172.18.0.1 proxy[7634]: 127.0.0.1 - "GET / HTTP/1.1" 200 693 "-" "curl/7.59.0" 0.001 0.001 .
> Apr 17 01:45:05 172.18.0.1 proxy[7634]: 192.168.10.130 - "POST /api/targets/ping HTTP/1.1" 400 22 "-" "curl/7.29.0" 10.021 10.021 .
> ```

Are you solve your problem?
