### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by srknkrbb** [vmware/harbor#1247]
harbor give error message when backend haproxy (haproxy work with ssl and 443 port, harbor not ssl and 80 port),
how can i do this configuration
haproxy and harbor use same ssl ignore this error
i dont think the right way
error message is
Failed to get secret cookie, error: http: named cookie not present
token.go:53]: uid for logging:
authenticator.go:57]: Current AUTH_MODE is db_auth
authenticator.go:69]: Login failed, locking , and sleep for 1.5s
login request with invalid credentials in token service, uid:

**Comment by ywk253100** [comment]
Harbor does not support the scenario that deploying Harbor behind another proxy for now.
