### ISSUE TITLE
邮件发送失败

### ISSUE THREAD

**Issue by xingxing9688** [vmware/harbor#1248]
邮箱配置
email_server = smtp.qq.com
email_server_port = 465
email_username = 
email_password = 
email_from = admin <>
email_ssl = true
日志如下
 [ERROR] [password.go:83]: Send email failed: 535 Error: Ȩ¼http://service.mail.qq.com/cgi-bin/h
elp?subtype=1&&id=28&&no=1001256
我使用ssl false 模式发送也是失败， harbor 版本0.45

**Comment by reasonerjt** [comment]
if you open the url, it says you need "授权码" to use smtp.

**Comment by xingxing9688** [comment]
按照这个也没有解决

**Comment by xingxing9688** [comment]
开启之后，输入授权码，依然发送失败

**Comment by reasonerjt** [comment]
same error?

**Comment by reasonerjt** [comment]
Please verify it with other smtp client and make sure it can send an Email and then use the configuration to setup harbor?  
Also did you rerun prepare after updating harbor.cfg?

**Comment by xingxing9688** [comment]
Send email failed: 501 mail from address must be same as authorization user
email_server = smtp.qq.com
email_server_port = 465
email_username = 1218761836@qq.com
email_password = gwynpcxgdwyjhdfi
email_from = admin <1218761836@qq.com>
email_ssl = true

**Comment by xingxing9688** [comment]
![image](https://cloud.githubusercontent.com/assets/23273577/21219842/5c1d9a86-c2f1-11e6-8c96-e6beb63c2294.png)

**Comment by xingxing9688** [comment]
验证，这里的验证用什么好的验证方法，我是修改harbor.cfg 之后直接更新然后在启动，在界面直接测试

**Comment by xingxing9688** [comment]
授权码是统一的，并且是和配置是一致的。应该还是哪里配置问题或者其他问题了

**Comment by xingxing9688** [comment]
测试阿里云企业邮箱和qq邮箱都不能发送邮件

**Comment by xingxing9688** [comment]
阿里云企业邮箱配置后报错如下
[ERROR] [password.go:83]: Send email failed: 500 Error: bad syntax

**Comment by xingxing9688** [comment]
我在企业客户端使用授权码发送邮件是可以的，使用的是一个授权码，但是在harbor 测试发送邮件是失败的
报错如下
[ERROR] [password.go:83]: Send email failed: 501 mail from address must be same as authorization user
但是授权码对比是一样的，更新配置，然后重启，不知道你们在测试qq邮箱是否正常发送

**Comment by ywk253100** [comment]
According to the error message, the email_from in harbor.cfg should be same with email_username.

**Comment by xingxing9688** [comment]
非常感谢，qq邮件可以发送了
之前的配置
email_from = admin  <1218761836@qq.com> 
修改为
email_from = 1218761836@qq.com

这样的配置就可以发送了

**Comment by ywk253100** [comment]
OK, I will close this issue.
