### ISSUE TITLE
涉及到版本升级、harbor.cfg配置修改时候,如何备份数据。

### ISSUE THREAD

**Issue by ghoul008** [vmware/harbor#125]
当升级时，重新build后如何保证之前的用户、与私有镜像库安全完成备份与升级。

**Comment by tinytub** [comment]
我在使用的时候把数据库单独拆出来了.
registry 容器因为默认挂载的 vol.重新 build 不会丢的吧.
不过你需要做的是改配置改配置和改配置.
感觉默认配置只是能让服务跑起来.还是需要自己定制一下.

**Comment by ghoul008** [comment]
啊，这个有个例子吗，因为我能看到的配置貌似就是harbor.cfg

**Comment by hainingzhang** [comment]
如果Harbor代码没有升级，只需要把/data目录备份并重新拷贝回去即可。

如果代码已经升级，需要看当前版本和新版本之间是否有数据库的变动才能确定方案。升级脚本正在编制。镜像所在的目录/data/registry可以备份并拷贝回去，但project可能需要重建。

**Comment by ghoul008** [comment]
好的，回头我再考虑这个。
