### ISSUE TITLE
harbor 配置第三方存储阿里云OSS 删除的问题

### ISSUE THREAD

**Issue by xingxing9688** [vmware/harbor#1252]
1. harbor 版本0.45 
2. 配置的是阿里云的OSS，在harbor 上删除镜像，然后重启释放，客户在阿里云OSS 中的镜像 依然存在，没有删除掉。

**Comment by xingxing9688** [comment]
这个问题是由于阿里云的延迟导致的，执行垃圾回收之后，阿里云延迟将近3个小时以后才能清除空间。

**Comment by hainingzhang** [comment]
Thanks for the update. Closing this issue for now. Please reopen if needed.
