### ISSUE TITLE
镜像复制策略只能使用80端口

### ISSUE THREAD

**Issue by keith4743** [vmware/harbor#1253]
proxy:
    image: nginx:1.11.5
    container_name: nginx
    restart: always
    volumes:
      - ./common/config/nginx:/etc/nginx
    ports:
      - 80:80
      - 443:443

修改成其他端口启动后，从其他节点添加复制策略时提示连接失败，改回80再启动就能连接成功。

以下是日志：
==> 2016-12-16/docker-current_registry.log <==
Dec 16 13:44:50 repo-server docker-current/registry[3746]: time="2016-12-16T05:44:50.20920166Z" level=debug msg="authorizing request" go.version=go1.6.3 http.request.host="10.9.0.102:81" http.request.id=fd7041aa-7688-4ac9-bd1d-653c65367c63 http.request.method=GET http.request.remoteaddr=172.16.100.242 http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=ad325648-73e7-475b-8f5b-905c603976a9 service=registry version=v2.5.0 
Dec 16 13:44:50 repo-server docker-current/registry[3746]: time="2016-12-16T05:44:50.209393726Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.6.3 http.request.host="10.9.0.102:81" http.request.id=fd7041aa-7688-4ac9-bd1d-653c65367c63 http.request.method=GET http.request.remoteaddr=172.16.100.242 http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=ad325648-73e7-475b-8f5b-905c603976a9 service=registry version=v2.5.0 
Dec 16 13:44:50 repo-server docker-current/registry[3746]: 172.18.0.6 - - [16/Dec/2016:05:44:50 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "Go-http-client/1.1"

==> 2016-12-16/docker-current_proxy.log <==
Dec 16 13:44:50 repo-server docker-current/proxy[3746]: 172.16.100.242 - - [16/Dec/2016:05:44:50 +0000] "GET /v2/ HTTP/1.1" 401 87 "-" "Go-http-client/1.1"

anyone encountered the same problem?

**Comment by ywk253100** [comment]
How did you customize the port Harbor listened on? Did you follow the [guide](https://github.com/vmware/harbor/blob/master/docs/installation_guide.md#configuring-harbor-listening-on-a-customized-port)?

Please provide the logs of UI.

**Comment by keith4743** [comment]
Resolved, thanks a lot! @ywk253100
