### ISSUE TITLE
SSL Certs with intermediate bundles

### ISSUE THREAD

**Issue by rb3896** [vmware/harbor#1259]
using harbor_0.5.0-9e4c90e.ova

My SSL certs include an intermediary CA.  Just installing the server cert isn't enough, as docker clients (unless they know about this intermediary) throw an x509 error when attempting to connect to harbor. 

As written, when I attempt to paste in an SSL cert + intermediate + ca bundle in on OVF deployment it gets mangled when written to /data/certs/server.crt by /harbor/script/config.sh.  

I've been able to work around it by manually putting the correct certs in place and commenting out a few lines in in config.sh so it doesn't get trampled on every reboot, but that's a hack.  I don't know what the long term answer is -  perhaps only doing SSL cert generation on 1st boot (which makes sense anyway), or maybe an "I'll manage my own certs" option rather than taking what is given or generating self signed on every boot, or maybe something else.

**Comment by ywk253100** [comment]
Thank you for reporting this issue, we'll fix it.

**Comment by ywk253100** [comment]
Fixed.
