### ISSUE TITLE
Docker images referenced in kubernetes .yaml files are well out of date

### ISSUE THREAD

**Issue by colemanserious** [vmware/harbor#1262]
The docker images referenced in make/kubernetes/ui-rc.yaml are not at all up-to-date on Docker Hub.  Docker Hub shows the last push as 8 months ago, and there have been significant changes to the UI code base since that time.

Optimally, the image would also be tagged with a release version, such that latest would be available and coupled with the most recent release, but downstream users would be able to compare their version to issues and code listed in GitHub.

**Comment by ywk253100** [comment]
There is an ongoing PR #1270 to fix it.

**Comment by ywk253100** [comment]
Fixed.
