### ISSUE TITLE
Some of the containers are not started after system reboot

### ISSUE THREAD

**Issue by guiguan** [vmware/harbor#1265]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose
Docker version 1.12.5, build 7392c3b
docker-compose version 1.9.0, build 2585387
2)Config files of harbor, you can get them by packaging "Deploy/config" directory
Used `restart: always` for every container defined in that `docker-compose.yml`
3)Log files, you can get them by package the /var/log/harbor/ 
Will provide if needed

I suspect this is a container dependency problem. Somehow, "always" is not respected by the docker when dependency order is broken when starting a compose. I am using docker for mac.

**Comment by ywk253100** [comment]
I think the key to this issue is the reason why the containers are failed to start. Provide the logs please so that we can check what happened.

**Comment by ywk253100** [comment]
Closing due to no further information provided.
