### ISSUE TITLE
How to develop harbor?

### ISSUE THREAD

**Issue by laz2** [vmware/harbor#1267]
I am novice in this project and want fix some important for me issues. I have 2 questions about developing process:
- How to restart harbor in development? Now i use next command (but it is very slow):
```
make compile_golangimage build down start -e GOBUILDIMAGE=harborgo:1.6.2 COMPILETAG=compile_golangimage
```
- How to run tests? I don't known command :(

**Comment by ywk253100** [comment]
1. The command you used is the easiest way to restart Harbor. Or you can run the binaries of UI and job service directly, but in this way the other components(database, registry, nginx) need to be started by yourself and some configurations need to be set, such as environment variables, certificate. The details please refer to make/docker-compose.tpl and make/common/templates/.
2. Some dependencies need to be set up before you run the tests, refer to the .travis.yml.

**Comment by laz2** [comment]
Should i create pull request for `master` branch or for `dev`?

**Comment by ywk253100** [comment]
Branch dev.

**Comment by reasonerjt** [comment]
Shall we close this issue?

**Comment by laz2** [comment]
> Shall we close this issue?

Thanks. Yes.
