### ISSUE TITLE
docker-compose stop后再start， logs容器出错

### ISSUE THREAD

**Issue by sysit** [vmware/harbor#1268]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose
```
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.14.x86_64
 Go version:      go1.6.3
 Git commit:      cb079f6-unsupported
 Built:           Fri Sep 16 13:24:25 2016
 OS/Arch:         linux/amd64
```
docker-compose version 1.8.0, build f3628c7
docker-py version: 1.9.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
2)Config files of harbor, you can get them by packaging "Deploy/config" directory
   harbor  0.5.0-rc 官方版，没改过
3)Log files, you can get them by package the /var/log/harbor/ 

docker-compose stop后，再start， log容器状态
`15b983fe4863        vmware/harbor-log:0.5.0-rc2          "/bin/sh -c 'crond &&"   About an hour ago   Restarting (1) About a minute ago   0.0.0.0:1514->514/tcp                      harbor-log`

docker 查看日志：
```
rsyslogd: run failed with error -3000 (see rsyslog.h or try http://www.rsyslog.com/e/3000 to learn what that number means)
rsyslogd: pidfile '/var/run/rsyslogd.pid' and pid 10 already exist.
If you want to run multiple instances of rsyslog, you need to specify
different pid files for them (-i option).
rsyslogd: run failed with error -3000 (see rsyslog.h or try http://www.rsyslog.com/e/3000 to learn what that number means)

```

**Comment by ywk253100** [comment]
The issue has been fixed in 0.5.0 release.
