### ISSUE TITLE
2habor cannot auto Synchronize

### ISSUE THREAD

**Issue by wuming333666** [vmware/harbor#1269]
i hava 2 harbor,one have 33 Images(call a harbor) ,other one is empty(call b harbor).when i set replication on a harbor ,it can only Synchronize 10 images,the rest images cannot sen to B harbor.i try stop and restart replication ,but it don't work any more,there is no error in log.

**Comment by ywk253100** [comment]
1. Are all images in one project on Harbor A? The replication policy is project-based. 
2. How many jobs can you see on UI? There should be 33 jobs if it worked well. 
3. Provide the logs please.

**Comment by hainingzhang** [comment]
which version of Harbor did you use? There used to be a similar issue of older version. @wuming333666

**Comment by wuming333666** [comment]
My version is harbor 0.4.1,and my operation system is centos 7.3.1611.

**Comment by wuming333666** [comment]
@ywk253100 
1.All images are in library.
2.I only have one job to do the replication.
3.Dec 30 14:56:53 B2B-Registry01dev docker-current/jobservice[19612]: 2016-12-30T06:56:53Z [DEBUG] [replication.go:93]: repo list: [library/dx library/nginx library/redis library/mongo library/mysql library/tomcat library/busybox library/hello-world library/httpd library/influxdb]。There is the images to replicate ,but it don's contain all images

**Comment by ywk253100** [comment]
It's a known issue #856 which has been fixed. Please upgrade your Harbor instance to the latest release.

**Comment by ywk253100** [comment]
I'm going to close this issue, feel free to reopen it if you have any other problems.
