### ISSUE TITLE
邮箱配置后发送邮件日志输出：Send email failed: 535 Error: authentication failed, system busy

### ISSUE THREAD

**Issue by hanmenghui** [vmware/harbor#1271]
使用腾讯企业邮箱，配置如下
email_identity = name

email_server =smtp.exmail.qq.com
email_server_port =465
email_username =myemail@domain
email_password =password
email_from =myemail@domain
email_ssl = true

然找回密码提示邮件发送失败，日志输出为：
Send email failed: 535 Error: authentication failed, system busy

同样配置在其他客户端可以通过。

**Comment by hanmenghui** [comment]
需重新执行./install

**Comment by motelover** [comment]
解决了吗

**Comment by samzhou** [comment]
腾讯企业邮箱 重新`开启安全登录`后，在`邮箱绑定`里设置`客户端专用密码`

see also https://blog.csdn.net/MyMBS/article/details/89017493

**Comment by gotoworld** [comment]
163邮箱配置中EMAIL_HOST_PASSWORD不能填写自己的QQ账号密码，而是应该填写授权码。如果填写QQ账号密码则会报535错误即smtplib.SMTPAuthenticationError: (535, b'Error: authentication failed')。授权码在QQ邮箱的设置中获得

**Comment by nexcvon** [comment]
> email_server=smtp.exmail.qq.com

这里很容易忽视, 要注意一下, 企业邮箱是 `smtp.exmail.qq.com`, 个人邮箱是 `smtp.qq.com`

**Comment by TARATRAOVO** [comment]
> > email_server=smtp.exmail.qq.com
> 
> 这里很容易忽视, 要注意一下, 企业邮箱是 `smtp.exmail.qq.com`, 个人邮箱是 `smtp.qq.com`

thankyousomuch

**Comment by huyarufitor** [comment]
配置都写对了，还是报错，会是什么原因呢

**Comment by yang0009** [comment]
一般都是服务未开启或者授权码不对，需要设置一下

第一：设置--收发信设置
开启IMAP/SMTP服务
开启POP/SMTP服务

第二:设置--邮箱绑定
开启安全登陆,在客户端专用密码，点击生成密码，复制授权码出来

第一步是必须的，如果没有开启对应服务，同样会535报错
