### ISSUE TITLE
MariaDB or Postgres support?

### ISSUE THREAD

**Issue by sokoow** [vmware/harbor#1272]
Are you planning to support mariadb or postgres?

If you are reporting a problem, please make sure the following information are provided:

1)Version of docker engine and docker-compose
Doesn't matter - running standalone.

2)Config files of harbor, you can get them by packaging "Deploy/config" directory
I only use this:
ENV:

MYSQL_HOST=localhost
MYSQL_PORT=3306
MYSQL_USR=registry
MYSQL_PWD=XXXXXX
UI_SECRET=XXXXXXXXXXXXXXXXXX
SECRET_KEY=XXXXXXXXXXXXXXXXX
CONFIG_PATH=/harbor/configs/app.conf
REGISTRY_URL=http://registry:5000
VERIFY_REMOTE_CERT=on
MAX_JOB_WORKERS=3
LOG_LEVEL=debug
LOG_DIR=/harbor/log/jobs
GODEBUG=netdns=cgo
EXT_ENDPOINT=http://reg.mydomain.com
TOKEN_ENDPOINT=http://ui

APP:

appname = jobservice
runmode = dev

[dev]
httpport = 80

3)Log files, you can get them by package the /var/log/harbor/ 

MariaDB [(none)]> select version();
+----------------------------------+
| version()                        |
+----------------------------------+
| 10.0.28-MariaDB-0ubuntu0.16.04.1 |
+----------------------------------+
1 row in set (0.00 sec)

2016-12-28T17:29:20Z [INFO] Config path: /harbor/configs/app.conf
2016-12-28T17:29:20Z [DEBUG] [config.go:95]: config: maxJobWorkers: 3
2016-12-28T17:29:20Z [DEBUG] [config.go:96]: config: localUIURL: http://ui
2016-12-28T17:29:20Z [DEBUG] [config.go:97]: config: localRegURL: http://registry:5000
2016-12-28T17:29:20Z [DEBUG] [config.go:98]: config: verifyRemoteCert: on
2016-12-28T17:29:20Z [DEBUG] [config.go:99]: config: logDir: /harbor/log/jobs
2016-12-28T17:29:20Z [DEBUG] [config.go:100]: config: uiSecret: ******
2016-12-28T17:29:20Z [INFO] token expiration: 30 minutes
2016-12-28T17:29:20Z [INFO] initializing database: type-MySQL host-localhost port-3306 user-root database-registry
[ORM]register db Ping `default`, Error 1251: Client does not support authentication protocol requested by server; consider upgrading MariaDB client
panic: register db Ping `default`, Error 1251: Client does not support authentication protocol requested by server; consider upgrading MariaDB client

**Comment by ywk253100** [comment]
Why do you need MariaDB or Postgres? Can you describe your use case? Are you trying to configure Harbor to connect to the external database?

**Comment by sokoow** [comment]
No, reason is a bit more pragmatic than that. I had a huge problem for a while with using mysql for arm64 platform, so automatically fallen back to mariadb, which didn't work due to logon compatilibity issues. That's it, and now it's resolved, I got it running on arm64 and are very happy about it.

Postgres question is down to the fact that this is far superior and more stable DB than mysql, do you plan any support for it ? I guess with generic ORM, it shouldn't be that hard right ? Greetings and thanks for answering.

**Comment by ywk253100** [comment]
Got it. But we have no plan to support these two databases for now.

**Comment by ywk253100** [comment]
I'm going to close this issue, feel free to reopen it if there is any other question.

**Comment by odg0318** [comment]
@ywk253100 Hi. No plain still now?
