### ISSUE TITLE
How to upgrade from harbor-0.3.5 to harbor-0.5.0?

### ISSUE THREAD

**Issue by wangfeiping** [vmware/harbor#1275]
I updated harbor, but harbor web page warn me an error with message "Error   Failed to get top repositories."
I found a error log in /var/log/harbor/ui.log
[ERROR] [repository.go:421]: failed to get top repos: Error 1146: Table 'registry.repository' doesn't exist

I restart harbor-0.3.5 and everything is ok.

I don't know how to do.

1)Version of docker engine and docker-compose
Docker version 1.12.1, build 23cf638
docker-compose version 1.8.0, build f3628c7

2)Config files of harbor, you can get them by packaging "Deploy/config" directory
[harbor-0.3.5.zip](https://github.com/vmware/harbor/files/676744/harbor-0.3.5.zip)
[harbor-0.5.0.zip](https://github.com/vmware/harbor/files/676745/harbor-0.5.0.zip)

3)Log files, you can get them by package the /var/log/harbor/ 
[harbor-0.5.0-logs.zip](https://github.com/vmware/harbor/files/676747/harbor-0.5.0-logs.zip)

**Comment by wknet123** [comment]
@wangfeiping, you need to perform a DB migration, please refer the doc [migration_guide](https://github.com/vmware/harbor/blob/master/docs/migration_guide.md).

**Comment by wangfeiping** [comment]
@wknet123 
Ok, I see.
Thanks alot!
