### ISSUE TITLE
Project name is too short

### ISSUE THREAD

**Issue by mustafayildirim** [vmware/harbor#1276]
When creating project;

Project name is too short, it should be greater than 4 characters.
My project name: **b2b**

Can you fix to 3 or 2?
Thanks

**Comment by yhua123** [comment]
@mustafayildirim 
Thank you.
I think maybe this is an issue. 
For reference:
https://github.com/docker/distribution/blob/master/docs/spec/api.md#overview
...
The rules for a repository name are as follows:

1.     A repository name is broken up into path components. A component of a repository name must be at least one lowercase, alpha-numeric characters, optionally separated by periods, dashes or underscores. More strictly, it must match the regular expression [a-z0-9]+(?:[._-][a-z0-9]+)*.
2.     If a repository name has two or more path components, they must be separated by a forward slash ("/").
3.     The total length of a repository name, including slashes, must be less than 256 characters.
...

**Comment by yhua123** [comment]
fixed #1302

**Comment by elmariofredo** [comment]
@yhua123 Shouldn't #1302 cover front end part as well? Please see suggestion from @gumby8813 here https://github.com/vmware/harbor/issues/1320#issuecomment-275384904
