### ISSUE TITLE
Consider projects visibility for top repository list

### ISSUE THREAD

**Issue by hellivan** [vmware/harbor#1281]
So far, the project visibility (public/private) is not considered when generating the list of the top repositories for the index.html. The API '/api/repositories/top' lists all repositories regardless of whether a user is logged in or not, or if he has sufficient privileges to see the repository's project. 

In my opinion the expected behavior would be:
* Unauthenticated users should only see repositories from public projects
* Authenticated users should only see repositories from projects to which they have access too

**Comment by ywk253100** [comment]
Fixed by #1301 .
