### ISSUE TITLE
Purge/registry cleanup

### ISSUE THREAD

**Issue by yeta-io** [vmware/harbor#1283]
Hello

Is it possible to run registry purge/old images cleanup from harbor?
I don't see any option in UI to do it.

Thanks

**Comment by ywk253100** [comment]
Refer to [user guide](https://github.com/vmware/harbor/blob/master/docs/user_guide.md#deleting-repositories) .

**Comment by bitencourts** [comment]
Hello yeta-io-ceo,
I've some problems with my registry server. In my case, I can't clean up old images. I tried a lot of things but I didn't have success. One time I managed to clean up a little space using this command:

docker run -it --name gc --rm --volumes-from registry vmware/registry:2.6.2-photon garbage-collect --dry-run /etc/registry/config.yml

But for me, it's worked just one time.

**Comment by shinebayar-g** [comment]
Hello @ywk253100 

https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#online-gc

Link doesn't work can you help?
