### ISSUE TITLE
questions about tokens

### ISSUE THREAD

**Issue by allan1991** [vmware/harbor#1289]
Hi, I deploy two harbors, and an nginx as lb, harbors are both in private network(A: 10.x.x.x, B: 10.x.x.x), and lb is in public network(registry.xxx.com).  Then I configure registry's `realm` as `realm: https://registry.xxx.com/service/token`. 

Then sometimes Harbor A's token request may be handled by Harbor B's token service. Both A and B share the sames key files(ui and registry), but I found A regard token produced by B as invalid:

```
Jan  5 08:45:25 172.18.0.1 registry[4570]: time="2017-01-05T08:45:25.536210681Z" level=error msg="token signed by untrusted key with ID: \"EXAT:SAHX:TTR2:G2DY:VEDN:RSM4:RZVJ:HNEW:2XIE:QOQO:57PZ:2H3V\""
``` 

I'm not familiar with JWT token, I wonder can harbor A's registry use tokens produced by harbor B's? Thank you.

**Comment by ywk253100** [comment]
If A and B share the same crt and key, this should work. Does the ID in the log msg match the key of instance A?

**Comment by allan1991** [comment]
I have found the problem: after execute `./prepare`, the generated key file is different from the src key file. I looked into the prepare script, it use `shutil.copyfile`, I don't know why it change the file content.

**Comment by ywk253100** [comment]
The certificate and private key files are generated every time you run prepare.
