### ISSUE TITLE
ERROR: Failed to initialize logging driver: dial tcp 127.0.0.1:1514: getsockopt: connection refused

### ISSUE THREAD

**Issue by ghoul008** [vmware/harbor#129]
使用docker-compose restart | stop | start 对容器进行管理时候，重启有时失败，报错如标题。
docker-compose up -d 报错相同。

**Comment by ywk253100** [comment]
There is a log container in Harbor and it is responsible for collecting logs of other containers by configuring log driver. So before other container start, the log container must start first. The "connection refused"  error occurred when other container is starting while rsyslog service in log container is not ready. You can re-run the command when you get this error.

**Comment by ghoul008** [comment]
[root@host-10-1-241-132 harbor]# docker-compose restart
Restarting harbor_proxy_1 ... done
Restarting harbor_registry_1 ... done
Restarting harbor_mysql_1 ... done
Restarting harbor_ui_1 ... error
Restarting harbor_log_1 ... done

ERROR: for harbor_ui_1  Cannot restart container 0132ac82f684b0052139185b381ec7642c056193afbc4364ce9fa075a0f91929: initlogger: Failed to initialize logging driver: dial tcp 127.0.0.1:1514: getsockopt: connection refused 
[root@host-10-1-241-132 harbor]# docker-compose restart
Restarting harbor_proxy_1 ... error
Restarting harbor_registry_1 ... done
Restarting harbor_mysql_1 ... error
Restarting harbor_ui_1 ... done
Restarting harbor_log_1 ... done

ERROR: for harbor_proxy_1  Cannot restart container 0a21cd52fe22976e21e739cb22cc454aecb25a490e3a5648116f1a3cd006203c: initlogger: Failed to initialize logging driver: dial tcp 127.0.0.1:1514: getsockopt: connection refused 
ERROR: for harbor_mysql_1  Cannot restart container 5f3c437bdc628f42b10da7fd9883101ffcb3088448543e6f92390e630b6dca0b: initlogger: Failed to initialize logging driver: dial tcp 127.0.0.1:1514: getsockopt: connection refused 
[root@host-10-1-241-132 harbor]# docker-compose restart
Restarting harbor_proxy_1 ... done
Restarting harbor_registry_1 ... error
Restarting harbor_mysql_1 ... done
Restarting harbor_ui_1 ... done
Restarting harbor_log_1 ... done

ERROR: for harbor_registry_1  Cannot restart container 08dfd2a2214a4a6464d73739ec9f590cabf0fcf4d23b406ee81c067452bcbe0d: initlogger: Failed to initialize logging driver: dial tcp 127.0.0.1:1514: getsockopt: connection refused

**Comment by ghoul008** [comment]
每次错误都不一样这什么鬼。我单独去启动   docker start log的容器又起不来，求解救。

**Comment by ghoul008** [comment]
尝试了多次 ,算是启动起来了，然后log又没起来竟然，你们遇到过吗？

**Comment by ywk253100** [comment]
Every time you run command "restart", all containers will be shutdown first, and then start them. So the sequence problem occurs every time. 

Run "docker-compose stop" and then run "docker-compose start" until all containers running is a workaround for your problem. 

If docker daemon could gracefully handle the situation that container connects to the unavailable service which is configured in log driver rather than fail with an error, this will not a problem. And someone has raised an issue about this to docker and I will watch it.

**Comment by ghoul008** [comment]
i see new ci fix it already

**Comment by freemankevin** [comment]
v2.6.1 ,   same issue

**Comment by freemankevin** [comment]
Suspected overlay2 storage driver,  solve.
```shell
$ cat /etc/docker/daemon.json 
{
  "registry-mirrors": ["https://ustc-edu-cn.mirror.aliyuncs.com"],
  "data-root": "/data/docker",
  "insecure-registries": ["0.0.0.0/0"]
}
$ systemctl daemon-reload 
$ systemctl restart docker 
```
