### ISSUE TITLE
[New Request] Customize the Log level

### ISSUE THREAD

**Issue by gunboe** [vmware/harbor#1290]
Would be good customize the Log Level in `harbor.cfg` for all services (mainly registry, ui, jobservice). Like this:
`log_level = [ fatal | error | warn | info | debug | trace ]  # Default: debug`

**Comment by gunboe** [comment]
Created a PR #1291

**Comment by ywk253100** [comment]
Thank you for your contribution. We are doing some modifications to provide a more friendly user experience to customize some configurations of Harbor, the log level is included. So your PR may not be merged. Thanks anyway.

**Comment by ywk253100** [comment]
Duplicate with #2354 .
