### ISSUE TITLE
Host & Intermediate CA certificate in OVF properties

### ISSUE THREAD

**Issue by csciarri** [vmware/harbor#1292]
I am experiencing an issue when attempting to put the contents of a ssl certificate into the SSL Cert field of the OVF properties in the 0.5.0 appliance. I am attempting to put in both the host certificate and the required intermediate certificate. The nginx container fails to start properly and upon inspection of the /data/cert/server.crt file it does not look proper. If I paste the contents of both certificates into this file directly nginx starts successfully.

**Comment by ywk253100** [comment]
It's a known issue #1259 and has been fixed in branch dev.
