### ISSUE TITLE
how to set hostname in harbor.cfg using LB

### ISSUE THREAD

**Issue by huzhengchuan** [vmware/harbor#1293]
Here is my way of deployment：
Make a cluster registry service with three harbor. The harbors deploy in three vm. each vm have a private ip, such as 192.168.1.x. And using a load-balancing to distribute the harbor requests to a vm, bind a public ip to the load-balancing. so a request the public ip will be proxy to the harbor in vm.

Here is my test-case
1. setting the hostname in harbor.cfg with public ip,  can docker login and pull/push a image from harbor.
but setting the replication strategy on project not work. I think it causes by the hostname.
 
2. setting the hostname with the private ip, the replication work well, but cannot docker login.

I don't know how to set the harbor.cfg in this deployment.

**Comment by ywk253100** [comment]
Are you trying to deploy multiple Harbor instance behind a LB and use replication among the instances to make sure the image synchronization?
In your test case 1, make sure (1)the private key used by Ui (2)certificate used by registry (3)date are same among all Harbor instances should resolve your problems. But the scenario is not tested.

**Comment by huzhengchuan** [comment]
Yes, using a public ip bind to the LB. Need to visit harbor service through the public ip.
In test case 1,  can execute 'docker login public_ip'/docker push/pull success. But the replication failed. 
When setting the hostip in harbor.cfg with a public ip, it will cause the hostip is same in all VM. 
what is the meaning of 'certificate used by registry'? others check ok, but not work well.

**Comment by ywk253100** [comment]
There is a root.crt under directory harbor/common/config/registry/, make sure all instances use the same crt. If it does not work, provide logs please.
