### ISSUE TITLE
WARNING: no logs are available with the 'syslog' log driver

### ISSUE THREAD

**Issue by bimedu** [vmware/harbor#1297]
Docker version 1.12.5, build 7392c3b
docker-compose version 1.9.0, build 2585387
harbor.0.5.0

[root@bimedu harbor]# docker-compose up
Starting harbor-log
Recreating harbor-ui
Recreating registry
Recreating harbor-db
Recreating nginx
Recreating harbor-jobservice
Attaching to harbor-log, registry, harbor-db, harbor-ui, harbor-jobservice, nginx
registry      | WARNING: no logs are available with the 'syslog' log driver
harbor-db     | WARNING: no logs are available with the 'syslog' log driver
harbor-ui     | WARNING: no logs are available with the 'syslog' log driver
harbor-jobservice | WARNING: no logs are available with the 'syslog' log driver
nginx         | WARNING: no logs are available with the 'syslog' log driver

**Comment by ywk253100** [comment]
You can get logs under directory /var/log/harbor/.

**Comment by dm17** [comment]
Why does this happen using syslog but not journald driver? The syslog driver puts logs in a path I don't like and also does this nasty behavior so 'docker logs' becomes useless.
