### ISSUE TITLE
用户登录认证失败（docker login）

### ISSUE THREAD

**Issue by ltz3317** [vmware/harbor#130]
Error response from daemon: Get https://XXX/v1/users/: dial tcp XXX:443: getsockopt: connection refused

/etc/default/docker 中配置了DOCKER_OPTS="--insecure-registry XXX" 没有效果。问题依旧存在。

容器详情：
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                      NAMES
cbf674e48cf0        library/nginx:1.9        "nginx -g 'daemon off"   26 seconds ago      Up 24 seconds       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   deploy_proxy_1
f2560881027e        deploy_ui                "/go/bin/harbor_ui"      27 seconds ago      Up 25 seconds       80/tcp                                     deploy_ui_1
cd23e302b2f0        deploy_mysql             "docker-entrypoint.sh"   27 seconds ago      Up 25 seconds       3306/tcp                                   deploy_mysql_1
d5f2e1911882        library/registry:2.3.0   "/bin/registry /etc/r"   27 seconds ago      Up 25 seconds       5000/tcp, 0.0.0.0:5001->5001/tcp           deploy_registry_1
dd19c8d67748        deploy_log               "/bin/sh -c 'cron && "   28 seconds ago      Up 26 seconds       0.0.0.0:1514->514/tcp                      deploy_log_1

**Comment by int32bit** [comment]
The option `--insecure-registry` should be same with `hostname` in harbor.cfg, I guess.

**Comment by ltz3317** [comment]
I set up the network testing machine，Don't use the hostname, instead of using the IP。

**Comment by int32bit** [comment]
What's your docker client version ?  You can refer [my post](http://int32bit.github.io/2016/04/18/docker镜像仓库harbor快速部署和使用/)。It seems that the version <= 1.7 can not work well.

**Comment by reasonerjt** [comment]
@ltz3317 have you restarted docker after making update to /etc/default/docker?

**Comment by BrickXu** [comment]
the same issue, docker login failed after docker-compose up, all settings the same as offical docs. It does not work as well.

**Comment by yunzhonghe71** [comment]
me to. I can acess the ui,but can't login. I just do all as the  offical docs .

**Comment by ZhangZhenhua** [comment]
Run into same issue here too.  

I just installed the 0.1.1 release following official document. I can access the web UI and create project and user correctly. The only difference I made is letting the web UI listening on 8001 instead of 80 by changing compose file.

Then I tried to login from CLI with the newly created user, however, it fails.

```
zhangzh@base[~]$sudo docker login 192.168.30.231:8001
Username: admin
Password:
Error response from daemon: Get http://192.168.30.231:8001/v2/: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.4.6 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"
```

From the server side, I saw log that needs token to auth this request.
```
Jul 12 18:40:32 172.17.0.1 docker/registry[858]: time="2016-07-12T10:40:32.951028712Z" level=debug msg="authorizing request" go.version=go1.5.3 http.request.host=192.168.30.231 http.request.id=da32b003-b827-4b3b-9144-eccd8c4826e7 http.request.method=GET http.request.remoteaddr=192.168.220.111 http.request.uri="/v2/" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.13.0-91-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))" instance.id=678e7aa6-6e93-457e-8fd0-6c109945c521 service=registry version=v2.3.0
Jul 12 18:40:32 172.17.0.1 docker/registry[858]: time="2016-07-12T10:40:32.952069804Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.5.3 http.request.host=192.168.30.231 http.request.id=da32b003-b827-4b3b-9144-eccd8c4826e7 http.request.method=GET http.request.remoteaddr=192.168.220.111 http.request.uri="/v2/" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.13.0-91-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))" instance.id=678e7aa6-6e93-457e-8fd0-6c109945c521 service=registry version=v2.3.0
Jul 12 18:40:32 172.17.0.1 docker/registry[858]: 172.17.0.6 - - [12/Jul/2016:10:40:32 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.13.0-91-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))"
```

Well, I doesn't try to build harbor against source. Is it fixed in master? Or will the next release be soon?

Thanks.

**Comment by reasonerjt** [comment]
in this case you need to let the nginx "proxy" listen on 8001 port, not the UI.

**Comment by jmccann** [comment]
I'm having a very similar issue to @ltz3317.

```
$ docker -D login x.x.x.x
Username: admin
Password: 
Error response from daemon: Get https://x.x.x.x/v1/users/: dial tcp x.x.x.x:443: getsockopt: connection refused
```

I am not sure how to troubleshoot this.  I've added `DOCKER_OPTS="--insecure-registry=x.x.x.x"` to my harbor server's `/etc/default/docker` (matching `hostname` from `harbor.cfg`) and restarted docker and that did not help.

My harbor.cfg is:

```
root@harbor:~/harbor/Deploy# grep -v '#' harbor.cfg 
hostname = x.x.x.x
ui_url_protocol = http
email_server = smtp.mydomain.com
email_server_port = 25
email_username = sample_admin@mydomain.com
email_password = abc
email_from = admin <sample_admin@mydomain.com>
email_ssl = false
harbor_admin_password = Harbor12345
auth_mode = db_auth
ldap_url = ldaps://ldap.mydomain.com
ldap_basedn = uid=%s,ou=people,dc=mydomain,dc=com
db_password = root123
self_registration = on
production = on
max_job_workers = 3 
verify_remote_cert = off
customize_crt = on
crt_country = US
crt_state = Minnesota
crt_location = US
crt_organization = organization
crt_organizationalunit = organizational unit
crt_commonname = example.com
crt_email = example@example.com
```

Is this working for others?  Any known setup I need to do or guide I need to read?  If you need more info let me know!

**Comment by reasonerjt** [comment]
@jmccann, normally adding "--insecure-registry=x.x.x.x" fix such issues.

could you run "ps -ef|grep docker" to double check this setting actual takes effect?

please also package the directory Deploy/config and attach to the issue, if convenient.

**Comment by jmccann** [comment]
So I think the issue may have something to do that I'm trying to run this in an Openstack instance that is fronted by a floating IP.  When on the instance that is running harbor I can do:

```
root@harbor:~# docker -D login 127.0.0.1
Username (admin): admin
Password: 
Login Succeeded
```

But still when trying to access it remotely/externally through the FIP (floating IP) I still get:

```
$ docker -D login x.x.x.x
Username: admin
Password: 
Error response from daemon: Get https://x.x.x.x/v1/users/: dial tcp x.x.x.x:443: getsockopt: connection refused
```

Not sure about attaching all the configs yet ... have to look through them to see what was generated ...

**Comment by jmccann** [comment]
OK, I finally figured out my issue.  Hopefully this will help someone else in the future.

1) Add `--insecure-registry=x.x.x.x:80` on the client (with default harbor config).
 * I was setting it on my server which does nothing.

2) Test with `docker -D login x.x.x.x:80` from client
 * I was testing with `docker -D login x.x.x.x` from client ... and so I was hitting the wrong port.

After those 2 things it seems to work!

```
$ docker -D login x.x.x.x:80
Username (admin): admin    
Password: 
Login Succeeded
```

**Comment by bobbyjunzhang** [comment]
@jmccann Great stuff! Thanks. 
@reasonerjt Let's enhance our documentation to include it. This might be confusing, especially for new Docker users.

**Comment by reasonerjt** [comment]
@jmccann, this is weird because this:
--insecure-registry=x.x.x.x
it tells docker to access x.x.x.x on port 80 with http

**Comment by jmccann** [comment]
@reasonerjt YOU ARE RIGHT!  Shows my lack of docker experience with private registries. :(

So in the end the main issue was setting that on the server instead of on the client.

Thanks for all the help and responses @reasonerjt even though this was probably a simple issue.

**Comment by reasonerjt** [comment]
no problem

**Comment by kingtiger2** [comment]
这里不得不说,harbor里面有个大坑.端口好一定不能省略.恰恰是你用xxx代替的地址,我遇到过,解决了这个问题

**Comment by Just2017** [comment]
harbor 的配置中 hostname = xxx.xxx.xxx.xxx 不加端口的话，默认是走的80 端口。

**Comment by kevindwei** [comment]
@Just2017  不需要在harbor.cfg里面配置为hostname:port    登录时候docker login 192.168.:80  具体看我博客https://www.cnblogs.com/kevincaptain/p/10346506.html

**Comment by elrondwong** [comment]
```conf
# The external URL for Harbor core service. It is used to
# 1) populate the docker/helm commands showed on portal
# 2) populate the token service URL returned to docker/notary client
#
# Format: protocol://domain[:port]. Usually:
# 1) if "expose.type" is "ingress", the "domain" should be
# the value of "expose.ingress.hosts.core"
# 2) if "expose.type" is "clusterIP", the "domain" should be
# the value of "expose.clusterIP.name"
# 3) if "expose.type" is "nodePort", the "domain" should be
# the IP address of k8s node
#
# If Harbor is deployed behind the proxy, set it as the URL of proxy
externalURL: https://172.16.10.10:30003
```

Edit the `values.yaml` file, and  configure the `externalURL` option to use the NodePort IP:PORT or other values in comments。
