### ISSUE TITLE
harbor sometimes push unsucessfully with 500 internal server error

### ISSUE THREAD

**Issue by joeyjy** [vmware/harbor#1309]
Hi Harbor team,

recently pushing image to my harbor instance, sometimes got error with some layers, it happens randomly, then the client will retry to push those failed layers, finally pushed completely, when I looking into the docker_registry.log, I found two kinds of error with SWIFT response:

1. swift: Object Corrupted
2. swift: HTTP Error: 401: 401 Unauthorized

Jan 17 19:28:03 172.18.0.1 docker/registry[64535]: time="2017-01-17T11:28:03.242245005Z" level=error msg="response completed with error" auth.user.name= err.code="manifest unknown" err.detail="swift: HTTP Error: 401: 401 Unauthorized" err.message="manifest unknown" go.version=go1.6.3 http.request.host=hub.cloud.ctripcorp.com http.request.id=4f568aec-beff-4c79-80cf-aa5dc4cc506d http.request.method=GET http.request.remoteaddr=10.3.204.146 http.request.uri="/v2/container/uat_100003949_46356/manifests/201613333209134807" http.request.useragent="docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.10.3 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.167502715s http.response.status=404 http.response.written=175 instance.id=ac1f277c-b3cb-41ca-8c9d-cd12f8dfc31b service=registry vars.name="container/uat_100003949_46356" vars.reference=201613333209134807 version=v2.5.0
Jan 17 19:36:51 172.18.0.1 docker/registry[64535]: time="2017-01-17T11:36:51.585265166Z" level=error msg="response completed with error" auth.user.name=app-pebble err.code=unknown err.detail="swift: Object Corrupted" err.message="unknown error" go.version=go1.6.3 http.request.host=hub.cloud.ctripcorp.com http.request.id=6fefe38c-db8c-4925-9e94-c4cbafed6e00 http.request.method=POST http.request.remoteaddr=192.168.83.150 http.request.uri="/v2/container/fat_100006901_245651/blobs/uploads/" http.request.useragent="docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" http.response.contenttype="application/json; charset=utf-8" http.response.duration=257.914728ms http.response.status=500 http.response.written=146 instance.id=ac1f277c-b3cb-41ca-8c9d-cd12f8dfc31b service=registry vars.name="container/fat_100006901_245651" version=v2.5.0
Jan 17 19:51:04 172.18.0.1 docker/registry[64535]: time="2017-01-17T11:51:04.325817901Z" level=error msg="response completed with error" auth.user.name= err.code="manifest unknown" err.detail="swift: HTTP Error: 401: 401 Unauthorized" err.message="manifest unknown" go.version=go1.6.3 http.request.host=hub.cloud.ctripcorp.com http.request.id=578f173a-9b0e-4f11-ba05-7b12cc7c3a25 http.request.method=GET http.request.remoteaddr=10.3.204.146 http.request.uri="/v2/container/uat_100003949_46356/manifests/201613333209134807" http.request.useragent="docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.10.3 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.402410262s http.response.status=404 http.response.written=175 instance.id=ac1f277c-b3cb-41ca-8c9d-cd12f8dfc31b service=registry vars.name="container/uat_100003949_46356" vars.reference=201613333209134807 version=v2.5.0
Jan 17 20:29:03 172.18.0.1 docker/registry[64535]: time="2017-01-17T12:29:03.249738228Z" level=error msg="response completed with error" auth.user.name= err.code="manifest unknown" err.detail="swift: HTTP Error: 401: 401 Unauthorized" err.message="manifest unknown" go.version=go1.6.3 http.request.host=hub.cloud.ctripcorp.com http.request.id=e85dc5f5-7e63-4fde-a9d2-7a44eb338fdd http.request.method=GET http.request.remoteaddr=10.3.204.146 http.request.uri="/v2/container/uat_100003949_46356/manifests/201613333209134807" http.request.useragent="docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.10.3 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.137192038s http.response.status=404 http.response.written=175 instance.id=ac1f277c-b3cb-41ca-8c9d-cd12f8dfc31b service=registry vars.name="container/uat_100003949_46356" vars.reference=201613333209134807 version=v2.5.0
Jan 17 21:07:29 172.18.0.1 docker/registry[64535]: time="2017-01-17T13:07:29.753710366Z" level=error msg="response completed with error" auth.user.name=app-pebble err.code=unknown err.detail="swift: Object Corrupted" err.message="unknown error" go.version=go1.6.3 http.request.host=hub.cloud.ctripcorp.com http.request.id=09a559c5-0f64-46c6-998f-8e5b93b78b5d http.request.method=POST http.request.remoteaddr=192.168.83.151 http.request.uri="/v2/container/prod_100002312_127183/blobs/uploads/" http.request.useragent="docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" http.response.contenttype="application/json; charset=utf-8" http.response.duration=254.140875ms http.response.status=500 http.response.written=146 instance.id=ac1f277c-b3cb-41ca-8c9d-cd12f8dfc31b service=registry vars.name="container/prod_100002312_127183" version=v2.5.0
Jan 17 21:07:29 172.18.0.1 docker/registry[64535]: time="2017-01-17T13:07:29.947657671Z" level=error msg="response completed with error" auth.user.name=app-pebble err.code=unknown err.detail="swift: Object Corrupted" err.message="unknown error" go.version=go1.6.3 http.request.host=hub.cloud.ctripcorp.com http.request.id=8c73439c-701a-4561-a236-5f059fdfee4e http.request.method=POST http.request.remoteaddr=192.168.83.151 http.request.uri="/v2/container/prod_100002312_127183/blobs/uploads/" http.request.useragent="docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(docker-py/1.10.6)" http.response.contenttype="application/json; charset=utf-8" http.response.duration=447.824865ms http.response.status=500 http.response.written=146 instance.id=ac1f277c-b3cb-41ca-8c9d-cd12f8dfc31b service=registry vars.name="container/prod_100002312_127183" version=v2.5.0
Jan 18 00:16:04 172.18.0.1 docker/registry[64535]: time="2017-01-17T16:16:04.077772749Z" level=error msg="response completed with error" auth.user.name= err.code="manifest unknown" err.detail="swift: HTTP Error: 401: 401 Unauthorized" err.message="manifest unknown" go.version=go1.6.3 http.request.host=hub.cloud.ctripcorp.com http.request.id=fd20bf15-7b4e-433a-97e3-23e537eb12d5 http.request.method=GET http.request.remoteaddr=10.3.204.146 http.request.uri="/v2/container/uat_100003949_46356/manifests/201613333209134807" http.request.useragent="docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.10.3 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.275514848s http.response.status=404 http.response.written=175 instance.id=ac1f277c-b3cb-41ca-8c9d-cd12f8dfc31b service=registry vars.name="container/uat_100003949_46356" vars.reference=201613333209134807 version=v2.5.0
Jan 18 01:35:05 172.18.0.1 docker/registry[64535]: time="2017-01-17T17:35:05.152686832Z" level=error msg="response completed with error" auth.user.name= err.code="manifest unknown" err.detail="swift: HTTP Error: 401: 401 Unauthorized" err.message="manifest unknown" go.version=go1.6.3 http.request.host=hub.cloud.ctripcorp.com http.request.id=ae95c522-8779-493c-9a92-3123c3a43a92 http.request.method=GET http.request.remoteaddr=10.3.204.145 http.request.uri="/v2/container/uat_100003949_46356/manifests/201613333209134807" http.request.useragent="docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.10.3 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.106278098s http.response.status=404 http.response.written=175 instance.id=ac1f277c-b3cb-41ca-8c9d-cd12f8dfc31b service=registry vars.name="container/uat_100003949_46356" vars.reference=201613333209134807 version=v2.5.0

I'm sure that my storage backend configuration is correct and my ceph works well, no changes recently, can you help me to troubleshoot?

docker-compose version 1.7.1, build 0a9ab35
Docker version 1.11.1, build 5604cbe

version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
    swift:
        username: swift
        password: password
        authurl: http://cloud.ops.sh.com:5000/v2.0
        tenant: admin
        domain: 10.9.90.17
        region: regionOne
        container: cloudharbor
    cache:
        layerinfo: inmemory
    maintenance:
        uploadpurging:
            enabled: false
    delete:
        enabled: true
http:
    addr: :5000
    secret: placeholder
    debug:
        addr: localhost:5001
auth:
  token:
    issuer: registry-token-issuer
    realm: http://hub.cloud.corp.com/service/token
    rootcertbundle: /etc/registry/root.crt
    service: token-service

notifications:
  endpoints:
      - name: harbor
        disabled: false
        url: http://ui/service/notifications
        timeout: 3000ms
        threshold: 5
        backoff: 1s

**Comment by reasonerjt** [comment]
So does this happen only when you are using swift as the storage backend?

**Comment by joeyjy** [comment]
@reasonerjt yes, if use local storage, works well

**Comment by joeyjy** [comment]
Sorry, there's some problem with our keystone service, close the issue.
