### ISSUE TITLE
Can harbor create project automatically？

### ISSUE THREAD

**Issue by int32bit** [vmware/harbor#131]
I have login my harbor server, When I push an image like `my_server/foobar/ubuntu`, if the project `foobar` doesn't exist, I get the error :
```
unauthorized: authentication required
```
I prefer it will create the project automatically. Why? Because I use harbor as our internal mirror registry, we strongly hope that it can not only synchronize the official image， but user-defined image!
For example:
```
docker pull krystism/ffmpeg # Pull from dockerhub because our registry not existes.
docker rmi krystism/ffmpeg # Romove the image from local.
docker pull krystism/ffmpeg # Pull from dockerhub again because the image can't be cached.
```
but if I pull officical image like `ubuntu`, it will work!

```
docker pull ubuntu # Pull from dockerhub.
docker rmi ubuntu # Remove from local.
docker pull ubuntu # Yes, pull from our harbor now, good! 
```
@hainingzhang

**Comment by hainingzhang** [comment]
it seems Docker only allows mirror for Docker Hub. So mirroring any private registry does not work.

**Comment by int32bit** [comment]
@hainingzhang Sorry I make you confused，I intent to show that non-officical images like `foobar/ubuntu`,`foobar/mysql`,etc. couldn't be cached if the corresponding project wasn't built before,not private registry. I guess the private registry may also be mirrored if we tell the username & password to the proxy as follows:
```
proxy:
  remoteurl: http://harbor_addr:harbor_port
  username: int32bit
  password: 1q2w3e4r
```
But we have not test yet.

**Comment by hainingzhang** [comment]
For RBAC mangement, this works as design. closing it.
