### ISSUE TITLE
Bump up the registry version to 2.6.0

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#1316]
1) update the docker image
2) update the source in vendor/ folder.
3) verify everything works.

**Comment by yhua123** [comment]
meet some issues, ref:
https://github.com/yhua123/harbor/tree/update-registry-2.6.0
https://travis-ci.org/yhua123/harbor/builds/203319455

**Comment by ywk253100** [comment]
Finished by #1626 .
