### ISSUE TITLE
Prevent public respositories

### ISSUE THREAD

**Issue by csciarri** [vmware/harbor#1319]
Using Harbor version appliance 0.5.0.

Is it possible to prevent a user from making a repository public? Ideally we could disable the public function from users except the admin. We want to make sure that a user cannot accidentally make something publicly available that should not be.

**Comment by laz2** [comment]
Is problem user project admin?

**Comment by csciarri** [comment]
Yes, is there a way to ensure that project admins are prevented from making repositories public?

**Comment by laz2** [comment]
Why u need this? Project admin can make with project what he want. I am not maintainer but i think answer is no :)

**Comment by laz2** [comment]
You can set role Developer or Guest for problem user.

**Comment by csciarri** [comment]
I understand that I could set the roles to something other than Project Admin. However, if I have hundreds or thousands of users in harbor that becomes difficult to manage. It also doesn't prevent the user from creating a new project in the registry and making it public.

If the registry is connected to the internet, there is a risk of users accidentally making a project public and possibly leaking containers that should not be accessible to people anonymously.

**Comment by reasonerjt** [comment]
You can restrict that only sys admin can create new project, will that help?

**Comment by csciarri** [comment]
Yes that could work. How would we do that?

**Comment by reasonerjt** [comment]
@csciarri 
You can try setting the attribute "project_creation_restriction" in harbor.cfg to "adminonly" before deploying harbor.

**Comment by csciarri** [comment]
That attribute worked thanks.
