### ISSUE TITLE
Project name is too short, it should be greater than 4 characters?

### ISSUE THREAD

**Issue by jm66** [vmware/harbor#1320]
Is there a way to avoid this restriction? We have a three-char repo name for organizational units.

**Comment by reasonerjt** [comment]
You'll need to update the code to work around...

**Comment by jm66** [comment]
Thanks Is there any particular reason why the name should be greater than 4 chars?

**Comment by gumby8813** [comment]
For quick reference, the code that needs to be changed to modify the project name requirement can be found here.
src/ui/api/project.go: const projectNameMinLen = 4
src/ui/static/resources/js/components/project/add-project.directive.js: if (status === 400 && vm0.projectName != '' && vm0.projectName.length < 4)

You will need to rebuild the ui which can be done by running "make compile_ui" from the parent directory. Copy the output of that compilation (make/dev/ui/harbor_ui) into /harbor of the running UI container and restart the container.

**Comment by yhua123** [comment]
@wknet123 
 Backend already done.
Please update UI code. thanks~

**Comment by jm66** [comment]
Thanks
