### ISSUE TITLE
Changing LDAP attribute used by "Author" in "Image Details" repository

### ISSUE THREAD

**Issue by gunboe** [vmware/harbor#1324]
Hi all,
I'd like to change LDAP attribute used to describe "Author" in "Image Details" repository showed by Harbor Web UI, how can I do that? Tks.

**Comment by yhua123** [comment]
Hi Gunboe,
For Harbor now, the "Author" shown on "Image Details" get from docker registry service API.
That's mean if you want to add the "Author" attribute to one image, you should use `docker commit`. 

`docker commit --help`
`Usage:	docker commit [OPTIONS] CONTAINER [REPOSITORY[:TAG]]` 
`Create a new image from a container's changes `
`  -a, --author        Author (e.g., "John Hannibal Smith <hannibal@a-team.com>") `
`...`

This process doesn't under Harbor control now.
