### ISSUE TITLE
Merge dev to master, and make a new release

### ISSUE THREAD

**Issue by rikatz** [vmware/harbor#1326]
@yhua123 Harbor received a lot of improvements since the last release.

Is there a ROADMAP / Plan to make a new release, merging dev into master and releasing a new version?

Thanks

**Comment by yhua123** [comment]
Hi Rikatz,
Henry and Daniel will help to answer this question.

**Comment by reasonerjt** [comment]
@rikatz 
We're still working out the release plan.
currently the target date for next official release is 15th April, code will be merged by the end of March.

The dev branch has the new features and master branch will be updated between releases to contain urgent bug fixes.

**Comment by rikatz** [comment]
OK, thanks :D will use the DEV branch there, until we get an official release.
