### ISSUE TITLE
Encrypt the password stored by configuration service.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#1329]

**Comment by tronicum** [comment]
https://github.com/vmware/harbor/pull/1060/files also implements a decent Hash algo, if you are want to upgrade from SHA1 to SHA3. if implemented with {SHA3} prefix, it should be a seamless upgrade. no migration needed.

**Comment by ywk253100** [comment]
@tronicum  We encrypt the passwords using AES.

**Comment by ywk253100** [comment]
Finished by #1422 .
