### ISSUE TITLE
在centos直接安装的docker1.12.5安装harbor出现问题

### ISSUE THREAD

**Issue by liaolinrong** [vmware/harbor#1332]
docker-compose version 1.8.0-rc1, build 9bf6bc6
Docker version 1.12.5, build 047e51b/1.12.5
在CentOS Linux release 7.2.1511 (Core)上直接`yum install docker` 安装的docker1.12.5，没有修改yum源。

下载了harbor-offline-installer-0.5.0.tgz 离线安装包，修改了harbor.cfg的hostname为自己主机IP，然后 ./install.sh，安装会到 docker.io 下载 library/registry:2.5.0，如果主机网络不通会导致安装失败。

测试把 docker-compose.yml 中 registry 的镜像由 library/registry:2.5.0 改为 registry:2.5.0 即可解决该问题。

原因：因为docker load的时候的镜像名是 registry:2.5.0，而docker-compose.yml 中又是library/registry:2.5.0，在通用版的docker下安装harbor测过没问题，在centos版的docker下安装会有问题。

**Comment by hainingzhang** [comment]
Thanks for your feedback.  @yhua123 please take a look.

**Comment by yhua123** [comment]
By default, docker pull will add library tag for the official image. For some unknown reason, this has different behavior on different systems, maybe docker issue. Whatever for our code, some part is inconsistent. Will fix them later.
