### ISSUE TITLE
LDAP support enhancement

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#1340]
This epic involves effort to make Harbor better support LDAP.

Such as using a better ldap library, improve the process to onboard a user.

There're some advanced requirements, such as supporting DB and LDAP authentication at the same time .etc.  These are not covered in this epic.

**Comment by reasonerjt** [comment]
@yhua123  please add issues to this epic per our discussion.

**Comment by yhua123** [comment]
#1355
