### ISSUE TITLE
cannot docker login via LDAP user

### ISSUE THREAD

**Issue by xionglun** [vmware/harbor#1341]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
docker                     **1.13.1**
docker-compose    **1.10.0, build 4bd6f1a**
harbor                      **0.5.0**
2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
My LDAP settings:
```
auth_mode = ldap_auth
ldap_url = ldaps://ldap.example.com
ldap_searchdn = cn=ldapuser,dc=example,dc=com
ldap_search_pwd = thepassword
ldap_basedn = dc=example,dc=com
ldap_filter = (objectClass=person)
ldap_uid = cn
ldap_scope = 3
self_registration = off
```

3)Log files, you can get them by package the /var/log/harbor/ .
```
Feb  9 12:26:35 172.18.0.1 ui[8904]: 2017-02-09T04:26:35Z [DEBUG] [authutils.go:49]: scopes: []
Feb  9 12:26:35 172.18.0.1 ui[8904]: 2017-02-09T04:26:35Z [INFO] request url: /service/token?account=hello&client_id=docker&offline_token=true&service=token-service
Feb  9 12:26:35 172.18.0.1 ui[8904]: 2017-02-09T04:26:35Z [WARNING] Failed to get secret cookie, error: http: named cookie not present
Feb  9 12:26:35 172.18.0.1 ui[8904]: 2017-02-09T04:26:35Z [DEBUG] [token.go:53]: uid for logging:
Feb  9 12:26:35 172.18.0.1 ui[8904]: 2017-02-09T04:26:35Z [DEBUG] [authenticator.go:57]: Current AUTH_MODE is ldap_auth
Feb  9 12:26:35 172.18.0.1 ui[8904]: 2017-02-09T04:26:35Z [DEBUG] [ldap.go:53]: ldapURL:ldaps://ldap.example.com
Feb  9 12:26:35 172.18.0.1 ui[8904]: 2017-02-09T04:26:35Z [DEBUG] [ldap.go:64]: baseDn:dc=example,dc=com
Feb  9 12:26:35 172.18.0.1 ui[8904]: 2017-02-09T04:26:35Z [DEBUG] [ldap.go:68]: Search DN: cn=ldapuser,dc=example,dc=com
Feb  9 12:26:35 172.18.0.1 ui[8904]: 2017-02-09T04:26:35Z [DEBUG] [ldap.go:84]: one or more filter(&(objectClass=person)(cn=))
Feb  9 12:26:35 172.18.0.1 ui[8904]: LDAP::Search() error : 32 (No such object)
Feb  9 12:26:35 172.18.0.1 ui[8904]: 2017-02-09T04:26:35Z [ERROR] [token.go:94]: Error occurred in UserLogin: LDAP::Search() error : 32 (No such object)
Feb  9 12:26:35 172.18.0.1 ui[8904]: 2017-02-09T04:26:35Z [WARNING] login request with invalid credentials in token service, uid:
```

------

The issue is:  
**I can't login via ldap user from docker, but i can login via same ldap user from UI**

I tracked the issue and found something maybe useful:
1. docker login url is
  /service/token?account=hello&client_id=docker&offline_token=true&service=token-service
2. harbor tryp to use [basic auth](https://github.com/vmware/harbor/blob/master/src/ui/service/token/token.go#L52) to extract username and password
  so,  __uid for logging:__'s uid is empty.
3. Then the ldap filter is also empty
  filter: (&(objectClass=person)(cn=))

I'm not familiar with docker's APIs and docker's client login. So i don't know whether the login url changed or not.

**Comment by yhua123** [comment]
please post your docker login command and harbor.cfg
Thanks~

**Comment by xionglun** [comment]
@yhua123 I have update some of my harbor.cfg.
And i **cannot** post the real configuration file here, because it is not a test deployment!

**Comment by xionglun** [comment]
I've try to login via db_auth, but also cannot get uid.
Maybe it's not a LDAP related issue, it's a docker login issue.
I will close this issue and open a new issue.

**Comment by yhua123** [comment]
`[DEBUG] [ldap.go:84]: one or more filter(&(objectClass=person)(cn=))`
looks this line have some problem. the filter shoud like this:
`one or more filter(&(objectClass=person)(cn=hello))`
I don't know why missing uid "hello".

the docker login command:
`docker login -u hello [your harbor address]`

**Comment by xionglun** [comment]
I have fixed this issue.
I install my harbor project behind a nginx, and nginx use https but harbor not.
So i did some tiny modification, then everything works.

**Comment by yhua123** [comment]
:)

**Comment by reasonerjt** [comment]
@xionglun Could you let us know what modification did you make to fix it? 
Just in case other users meet the same issue.

**Comment by xionglun** [comment]
Sure, I am glad to share my issue and solution here.

I have a proxy server (nginx, **A**) before all harbor components. This server will manage things like SSL certificates and others, but mostly it's just a proxy. And also have another nginx server (one installed by one-step script, **B**). 

Nginx A configuration
```
upstream harborNginxB {
    server  192.168.10.3:80;
}

server {
    listen   443 ssl;
    server_name  hub.example.com;
    location / {
        proxy_pass http://harborNginxB;
    }
}
```

So `harbor.cfg` looks like:
```
hostname = hub.example.com
ui_url_protocol = http
```

Now, for harbor nginx, it's **http** not **https**, but actually it is **https**.
In `common/templates/registry/config.yml`, the auth field is:
```
auth:
  token:
    issuer: registry-token-issuer
    realm: $ui_url/service/token
    #realm: https://hub.example.com/service/token
    rootcertbundle: /etc/registry/root.crt
    service: token-service
```

I guess `$ui_url` is `http://hub.example.com`, then replace it with `https://hub.example.com`.
It maybe not a perfect solution, but works.
