### ISSUE TITLE
Popular Repositories should not display private project repositories

### ISSUE THREAD

**Issue by xionglun** [vmware/harbor#1342]
Harbor version: **0.5.0**

Current login page without logged:
![image](https://cloud.githubusercontent.com/assets/1031768/22775489/e949c242-eee6-11e6-8cac-e2c20ac6eb12.png)

BUT the project **i1dev** is private!  
![image](https://cloud.githubusercontent.com/assets/1031768/22775481/ddb28252-eee6-11e6-8337-d921d1f9f477.png)

Popular Repositories should not display private project's repositories..

**Comment by laz2** [comment]
Version of harbor?

**Comment by laz2** [comment]
I think this is fixed in dev branch.

**Comment by xionglun** [comment]
@laz2 I didn't try dev branch.
It's ok to close if next version has fixed this issue.
