### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by timchenxiaoyu** [vmware/harbor#1347]
docker login reg.skycloud.com
Username: tim
Password: 
Error response from daemon: Get https://reg.skycloud.com/v1/users/: x509: certificate is valid for *.internettraffic.click, internettraffic.click, not reg.skycloud.com

I compile harbor use galang image，after bringing up,login error

**Comment by reasonerjt** [comment]
your cert is not valid.

**Comment by timchenxiaoyu** [comment]
I use http

**Comment by timchenxiaoyu** [comment]
I know if I use http,I must set --insecure-registry

**Comment by timchenxiaoyu** [comment]
when I docker push reg.skycloud.com/test/busybox:v1 ,it has other error!!!
Error: Status 405 trying to push repository test/busybox: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>405 Method Not Allowed</title>\n</head><body>\n<h1>Method Not Allowed</h1>\n<p>The requested method PUT is not allowed for the URL /v1/repositories/test/busybox/.</p>\n<hr>\n<address>Apache/2.2.22 (Ubuntu) Server at reg.skycloud.com Port 443</address>\n</body></html>\n"

**Comment by reasonerjt** [comment]
"Apache/2.2.22 (Ubuntu) Server at reg.skycloud.com Port 443"

I think this piece in your error means you are still using http?

**Comment by timchenxiaoyu** [comment]
do I must  use https?

**Comment by timchenxiaoyu** [comment]
docker version is 1.13.0-rc3

**Comment by qingchn** [comment]
I see the same error ?
Centos 7.3
Docker version 1.13.1-rc1
Habor 0.5.0
USE the wiki https://github.com/vmware/harbor/blob/master/docs/configure_https.md configure.
Error response from daemon: Get https://reg.abc.com/v1/users/: x509: certificate is valid for , not reg.abc.com

**Comment by supereagle** [comment]
Please set `--insecure-registry`, as Docker will try both `http` and `https`.

**Comment by timchenxiaoyu** [comment]
afte  set --insecure-registry  I can login,but cann't push image

**Comment by supereagle** [comment]
According to your log, Docker uses `v1` when you push image, but the Registry does not support `v1`. Set `--disable-legacy-registry` in Docker options to disable `v1`.

**Comment by timchenxiaoyu** [comment]
I change https ，login error，-bash-4.2# docker login reg.skycloud.com
Username (admin): admin
Password: 
Error response from daemon: Get https://reg.skycloud.com/v1/users/: x509: certificate is valid for *.internettraffic.click, internettraffic.click, not reg.skycloud.com

**Comment by timchenxiaoyu** [comment]
x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate

**Comment by timchenxiaoyu** [comment]
I hava cp ca.crt  ,server.crt,server.key to right dir,but still error

**Comment by timchenxiaoyu** [comment]
openssl x509 -in ./xxx.com.crt  -noout -text
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number: 10647997531226427841 (0x93c54956d1fcd1c1)
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: C=XX, L=Default City, O=xxx, OU=dev, CN=reg.xxx.com
        Validity
            Not Before: May 15 06:16:54 2017 GMT
            Not After : May 15 06:16:54 2018 GMT
        Subject: C=XX, L=Default City, O=xxx, OU=dev, CN=reg.xxx.com

**Comment by timchenxiaoyu** [comment]
I found problem ,fix in https://github.com/vmware/harbor/pull/2318
