### ISSUE TITLE
Who is the sysadmin user when you use LDAP auth?

### ISSUE THREAD

**Issue by chrisfelix82** [vmware/harbor#1352]
Who is the sysadmin user when you use LDAP auth?  I am using LDAP auth and I can log in successfully, but how do I configure harbor to use my ldap username as the sysadmin user?

Thanks!

**Comment by hainingzhang** [comment]
Harbor always has the local user "admin" as the sysadmin. You can log in as "admin" and grant sysadmin to your ldap account.

**Comment by chrisfelix82** [comment]
Great!  Thanks
