### ISSUE TITLE
Error sending email - connection refused

### ISSUE THREAD

**Issue by weaktyper** [vmware/harbor#1356]
Hi, I am getting an error when sending an email from the `ui.log`

```
Feb 13 13:20:14 172.18.0.1 ui[1100]: 2017-02-13T12:20:14Z [ERROR] [password.go:83]: Send email failed: dial tcp 172.18.0.25:587: getsockopt: connection refused
```

I have tried multiple settings:
```
EMAIL_SERVER=smtp.mailgun.org
EMAIL_SERVER_PORT=587
EMAIL_USERNAME=<hide>
EMAIL_PASSWORD=<hide>
EMAIL_FROM=<hide>
EMAIL_SSL=false
```

and 
```
EMAIL_SERVER=smtp.mailgun.org
EMAIL_SERVER_PORT=465
EMAIL_USERNAME=<hide>
EMAIL_PASSWORD=<hide>
EMAIL_FROM=<hide>
EMAIL_SSL=true
```

But this error `Send email failed: dial tcp 172.18.0.25:587: getsockopt: connection refused` means that the email wont even send. 

Why is it trying to send on port 587?

Any ideas?

**Comment by reasonerjt** [comment]
Did you run prepare and deploy again to make the configuration effective?

**Comment by stephenmoloney** [comment]
@reasonerjt 

Well spotted, it turns out I hadn't changed my docker `.env` variables properly which I use to populated the harbor config. 

This error is gone now but I have a new error `Send email failed: 501 Syntax error`
which already has an open  pull request `https://github.com/vmware/harbor/pull/1261`

**Comment by weaktyper** [comment]
@reasonerjt

Well spotted, it turns out I hadn't changed my docker .env variables properly which I use to populated the harbor config.

This error is gone now but I have a new error Send email failed: 501 Syntax error
which already has an open pull request `https://github.com/vmware/harbor/pull/1261`

#1261
