### ISSUE TITLE
启动UI偶尔失败，不知原因。显示无法连接DB。

### ISSUE THREAD

**Issue by ghoul008** [vmware/harbor#138]
mysql_1    | 2016-04-20 09:57:31 1 [Note] Execution of init_file '/tmp/mysql-first-time.sql' ended.
mysql_1    | 2016-04-20 09:57:31 1 [Note] mysqld: ready for connections.
mysql_1    | Version: '5.6.29'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
ui_1       | 2016-04-20T09:57:36Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1       | 2016-04-20T09:58:01Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1       | panic: Failed to connect to DB after 60 seconds
ui_1       | 
ui_1       | goroutine 1 [running]:
ui_1       | github.com/vmware/harbor/dao.InitDB()
ui_1       |    /go/src/github.com/vmware/harbor/dao/base.go:93 +0x66d

**Comment by ghoul008** [comment]
UI常常启动起来后，过一会自己就挂掉了。

**Comment by ywk253100** [comment]
Please pull the latest code and rebuild Harbor. If the same error occurs, please provide complete logs.
