### ISSUE TITLE
Is it possible to create repositories without project?

### ISSUE THREAD

**Issue by hiscal2015** [vmware/harbor#1385]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose. 1.12.6
2)Harbor version: 0.5.0

I'd like to use Harbor as my default docker registry instead of Docker hub, that is, when I run docker pull nginx:latest, it will pull image myreg.demo.com/nginx:latest, but seems repositories in Harbor should be created under projects, like myreg.demo.com/nginx/nginx:latest, so may I know is it possible to create image like myreg.demo.com/nginx:latest?

**Comment by reasonerjt** [comment]
No, currently not, very image has be under a namespace which is the equivalent of project.

**Comment by hiscal2015** [comment]
@reasonerjt Will this be supported in future releases?

**Comment by rmrf** [comment]
@reasonerjt I'm trying to add a Nginx proxy before Harbor, the proxy working for make docker client does not aware of the namespace exist, but I can't make it work ... any suggestion?

**Comment by jessehu** [comment]
@hiscal2015 Currently you can create a project (e.g. dockerhub) to host all images pulled from dockerhub. We will discuss whether to support this feature in future release.

**Comment by franzudev** [comment]
Any news on this? I have to migrate a docker registry from Distribution to Harbor on kubernetes, but at the moment I have <url>/<image>:<tag>, there's a way to maintain the same format in Harbor or I need to rewrite all of my images endpoints?
