### ISSUE TITLE
重启容器常常遇到502

### ISSUE THREAD

**Issue by ghoul008** [vmware/harbor#139]
日志如下
Apr 21 11:47:32 host-10-1-241-132 docker/proxy[29011]: 10.1.39.55 - - [21/Apr/2016:03:47:32 +0000] "GET / HTTP/1.1" 502 575 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
Apr 21 11:47:32 host-10-1-241-132 docker/proxy[29011]: 2016/04/21 03:47:32 [error] 7#7: *4 connect() failed (113: No route to host) while connecting to upstream, client: 10.1.39.55, server: , request: "GET / HTTP/1.1", upstream: "http://172.19.0.3:80/", host: "10.1.241.132"
Apr 21 11:47:35 host-10-1-241-132 docker/proxy[29011]: 2016/04/21 03:47:35 [error] 7#7: *4 connect() failed (113: No route to host) while connecting to upstream, client: 10.1.39.55, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.19.0.3:80/favicon.ico", host: "10.1.241.132", referrer: "http://10.1.241.132/"
Apr 21 11:47:35 host-10-1-241-132 docker/proxy[29011]: 10.1.39.55 - - [21/Apr/2016:03:47:35 +0000] "GET /favicon.ico HTTP/1.1" 502 575 "http://10.1.241.132/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"

**Comment by ghoul008** [comment]
尝试过删除容器重新构建，也清干净了/data/
遇到的还是蛮频繁的。

**Comment by wknet123** [comment]
@ghoul008 please check out the latest code and rebuild the images by using `docker-compose up --build`

**Comment by ghoul008** [comment]
这是我的清理步骤不知道是否正确
1：docker-compose stop
2:docker-compose rm -f
3:docker rmi 三个对应的镜像log mysql ui
4:rm -rf /data/database/*
5:rm -rf /data/registry/*
6:docker-compose build
7:docker-compose up -d

**Comment by wknet123** [comment]
No need to execute `docker rmi` each time, others seem OK.

**Comment by ghoul008** [comment]
然而，我这样清理了，常常是UI起不来，完全看脸，起来了常常502，看日志就会常常看到类似这种
ui_1 | 2016-04-20T09:57:36Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1 | 2016-04-20T09:58:01Z [INFO] failed to connect to db, retry after 2 seconds...
ui_1 | panic: Failed to connect to DB after 60 seconds

**Comment by hainingzhang** [comment]
这个问题和 #138 都是数据库没有启动成功，请你贴一下数据库容器的日志。以便分析。@ghoul008

**Comment by dingmingk** [comment]
我也是ui一直挂掉，harbor_ui总是去连106.75.141.74:3306不知道为什么。
`
2016-04-27T12:36:47Z [DEBUG] [base.go:73]: db url: mysql:3306, db user: root
2016-04-27T12:37:07Z [ERROR] [base.go:85]: failed to connect to db, retry after 2 seconds :dial tcp 106.75.141.74:3306: i/o timeout
PING mysql (172.18.0.4): 56 data bytes
64 bytes from 172.18.0.4: icmp_seq=0 ttl=64 time=0.086 ms
`

**Comment by ywk253100** [comment]
@dingmingk #117

**Comment by ghoul008** [comment]
@ywk253100 thanks a lot
