### ISSUE TITLE
Integration with Clair

### ISSUE THREAD

**Issue by roldancer** [vmware/harbor#1411]
When would be available the integration with CoreOS Clair?, any idea ?

Thanks.

**Comment by reasonerjt** [comment]
Probably not in Q1.

**Comment by chbiel** [comment]
There is already another isue #914 and an open PR #1260 but without an integrated ui. Maybe this would be a good starting point?

We also looking forward to this integration :)

**Comment by supereagle** [comment]
If the plan is out, I will continue the integration.

**Comment by roldancer** [comment]
Any news ? When would be available the integration with Clair ? any idea +/- ?

**Comment by reasonerjt** [comment]
There's WIP to integrate Clair for vulnerability scan, the work is tracked by #2042
