### ISSUE TITLE
[Issue] Inconsistent LDAP SCOPE in "harbor.cfg" and Go-ldap Lib

### ISSUE THREAD

**Issue by yhua123** [vmware/harbor#1424]
In `harbor.cfg`, https://github.com/vmware/harbor/blob/master/make/harbor.cfg, line 52:53
`...`
`#the scope to search for users, 1-LDAP_SCOPE_BASE, 2-LDAP_SCOPE_ONELEVEL, 3-LDAP_SCOPE_SUBTREE`
`ldap_scope = 3`
`...`
In Go-ldap lib, https://github.com/go-ldap/ldap/blob/master/search.go, line 71:76
`...`
`// scope choices`
`const (`
`	ScopeBaseObject   = 0`
`	ScopeSingleLevel  = 1`
`	ScopeWholeSubtree = 2`
`)`
`...`

impact file:
https://github.com/vmware/harbor/blob/master/src/ui/auth/ldap/ldap.go, line 84:96

**Comment by stonezdj** [comment]
Duplicate with #3763
