### ISSUE TITLE
web 界面无法及时显示上传的镜像

### ISSUE THREAD

**Issue by vcent** [vmware/harbor#143]
当我push一个镜像到harbor服务端，push成功后，在web界面看不到这个镜像
大概过10分钟之后，刷新才可以看到。
这是什么原因呢

---
[root@wx-snp-01 ]# docker push hub.docker.master.com/library/centos:7
The push refers to a repository [hub.docker.master.com/library/centos] (len: 1)
88f9454e60dd: Image already exists
5b12ef8fd570: Image successfully pushed
511136ea3c5a: Image successfully pushed
Digest: sha256:275be3397c40be9a5bbc987afb689d8fe180f1df35413f3a9c6eccef38f1bfd

**Comment by reasonerjt** [comment]
Hi, please do the following:
1)package the log files in** /var/log/harbor**
2)provide your configuration file, you can get them by packaging** Deploy/config**

And attach them to this issue

**Comment by reasonerjt** [comment]
@vcent  could you please provide the information for debuging?

**Comment by vcent** [comment]
this log is important, i can not provide
is there other way to debug this

**Comment by vcent** [comment]
in docker_ui.log  find this
Apr 21 17:21:27 172.18.0.1 docker/ui[2320]: 2016-04-21T09:21:27Z [INFO] Query AccessLog: begin: 1970-01-01 00:00:00 +0000 UTC, end: 1970-01-01 00:00:00 +0000 UTC, keywords:

**Comment by reasonerjt** [comment]
So could you please provide config files?

**Comment by vcent** [comment]
this is webhook??
--
notifications:
  endpoints:
      - name: harbor
        disabled: false
        url: http://ui/service/notifications
        timeout: 500
        threshold: 5
        backoff: 1000

**Comment by reasonerjt** [comment]
yes, it is.  could you check ui log to see if the webhook is actually called or not

**Comment by vcent** [comment]
The docker_ui.log ::

Apr 25 18:04:08 172.18.0.1 docker/ui[2320]: 2016-04-25T10:04:08Z [INFO] Query AccessLog: begin: 1970-01-01 00:00:00 +0000 UTC, end: 1970-01-01 00:00:00 +0000 UTC, keywords:
Apr 25 18:04:08 172.18.0.1 docker/ui[2320]: 2016/04/25 10:04:08 #033[1;34m[router.go:828][D] | POST       | /api/projects/1/logs/filter              | 3.065983ms       | match      | /api/projects/:id/logs/filter            | #033[0m
^C
前后的时间不一致
# Apr 25 18:04:08 172.18.0.1 docker/ui[2320]: 2016/04/25 10:04:08

一个是18点 一个是10点

**Comment by vcent** [comment]
Apr 25 18:09:58 172.18.0.1 docker/ui[2320]: 2016-04-25T10:09:58Z [DEBUG] [registryutils.go:50]: Registry API url: http://registry:5000/v2/_catalog
Apr 25 18:09:58 172.18.0.1 docker/ui[2320]: 2016/04/25 10:09:58 #033[1;34m[router.go:828][D] | GET        | /api/projects/1/members/current          | 5.493456ms       | match      | /api/projects/:pid/members/?:mid         | #033[0m
Apr 25 18:09:58 172.18.0.1 docker/ui[2320]: 2016-04-25T10:09:58Z [DEBUG] [registryutils.go:64]: authenticate header: Bearer realm="http://hub.docker.master.com/service/token",service="token-service",scope="registry:catalog:*"
Apr 25 18:09:58 172.18.0.1 docker/ui[2320]: 2016/04/25 10:09:58 #033[1;34m[router.go:828][D] | GET        | /api/repositories                        | 15.848849ms      | match      | /api/repositories                        | #033[0m

**Comment by reasonerjt** [comment]
时间不一致是logger配置的问题，这个我们会看下，那么您在push之后ui log里是否有/notifications被调到的信息？
类似：
match | /service/notifications

**Comment by vcent** [comment]
@reasonerjt  push成功后，在web界面还是要过几分钟刷新后才可以看到

Apr 26 11:35:40 172.18.0.1 docker/ui[2320]: 2016-04-26T03:35:40Z [DEBUG] [authenticator.go:52]: Current AUTH_MODE is db_auth
Apr 26 11:35:40 172.18.0.1 docker/ui[2320]: 2016-04-26T03:35:40Z [DEBUG] [token.go:46]: scopes: [repository:library/kibana111:pull,push]
Apr 26 11:35:40 172.18.0.1 docker/ui[2320]: 2016-04-26T03:35:40Z [INFO] current access, type: repository, name:library/kibana111, actions:[push pull]
Apr 26 11:35:40 172.18.0.1 docker/ui[2320]: 2016/04/26 03:35:40 #033[1;34m[router.go:828][D] | GET        | /service/token                           | 22.419474ms      | match      | /service/token                           | #033[0m
Apr 26 11:35:43 172.18.0.1 docker/ui[2320]: 2016/04/26 03:35:43 #033[1;34m[router.go:828][D] | POST       | /service/notifications                   | 641.159µs        | match      | /service/notifications                   | #033[0m
Apr 26 11:35:43 172.18.0.1 docker/ui[2320]: 2016/04/26 03:35:43 #033[1;34m[router.go:828][D] | POST       | /service/notifications                   | 387.013µs        | match      | /service/notifications                   | #033[0m
Apr 26 11:35:43 172.18.0.1 docker/ui[2320]: 2016/04/26 03:35:43 #033[1;34m[router.go:828][D] | POST       | /service/notifications                   | 271.926µs        | match      | /service/notifications                   | #033[0m

**Comment by xiaods** [comment]
/notifications is not filter function, so this is pain

**Comment by reasonerjt** [comment]
Agree, but I don't think it will crash or be unable to handle the amount requests for regular use, either there's a bug in code or there's configuration issue.

**Comment by hainingzhang** [comment]
should have been fixed. please reopen if problem persists.

**Comment by KeithTt** [comment]
Similar problem here.

Version: v1.10.2-d0189bed

I have an image named `harbor.xxx.com/yyy/tensorflow-serving:2.10.0-hadoop-2.10.2-14` which has been pushed to harbor yesterday, I can pull it but I can not find it on the web page until now.
