### ISSUE TITLE
notary return 401 when run notary list GUN

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#1484]
dev branch

use content trust 
export content trust and content trust server
run notary list ip/repo/image:tag 
will get an error"* fatal:  you are not authorized to perform this operation: server returned 401"

**Comment by reasonerjt** [comment]
root cause is in notary client:
https://github.com/docker/notary/issues/1107

I have a quick fix and will push to upstream, if not we have revisit it later to find other workaournd

**Comment by reasonerjt** [comment]
My PR to fix the issue has been merged, will close this issue if notary has a new release that contains my fix

**Comment by reasonerjt** [comment]
The notary is bound to port 4443 now, no more such issue as long as the "-s" is properly set.
