### ISSUE TITLE
New Harbor UI requested for your comments

### ISSUE THREAD

**Issue by wknet123** [vmware/harbor#149]
Below are overall UI designs, please feel free to your comment.

- User Login

![u-home](https://cloud.githubusercontent.com/assets/5027302/14773231/291426ac-0ada-11e6-9c0f-547155524d34.jpg)

- Dashboard View
![u-dashboard](https://cloud.githubusercontent.com/assets/5027302/14773265/944d05a6-0ada-11e6-84a1-20a2a26323b1.jpg)

- Admin Dashboard View
![a-dashboard](https://cloud.githubusercontent.com/assets/5027302/14773508/80139408-0add-11e6-84d3-6935453146dd.jpg)

- My Projects List
![u-myprojects](https://cloud.githubusercontent.com/assets/5027302/14773278/bdd289f0-0ada-11e6-9782-4a950688847b.jpg)

- Add New Project
![u-myprojects-addproject](https://cloud.githubusercontent.com/assets/5027302/14773285/ce1c535e-0ada-11e6-963e-0fd298889b72.jpg)

- Public Project List
![u-publicprojects](https://cloud.githubusercontent.com/assets/5027302/14773313/2d4196d2-0adb-11e6-8132-f1dfdf905959.jpg)

- Repositories List
![u-projects-repositories](https://cloud.githubusercontent.com/assets/5027302/14773319/3f462c3a-0adb-11e6-8a05-bf03af0f6610.jpg)

- Change Repository List View
![projects-repositories-improve](https://cloud.githubusercontent.com/assets/5027302/14773656/6b35e28c-0adf-11e6-90cd-1e9b6eedbfa8.jpg)

- Confirmation of Deleting Repository or Tag
![deletewarning](https://cloud.githubusercontent.com/assets/5027302/14773747/9784e080-0ae0-11e6-94dc-3051bd1b6d90.jpg)

- Show Image Details
![u-projects-repositories-tooltips](https://cloud.githubusercontent.com/assets/5027302/14773341/8e7bb838-0adb-11e6-9184-0afb178f2ecb.jpg)

- Select a Repository 
![u-projects-repositories-dropdown](https://cloud.githubusercontent.com/assets/5027302/14773352/b457ac9c-0adb-11e6-8c0b-108e091d0519.jpg)

- Project Members
![u-projects-users](https://cloud.githubusercontent.com/assets/5027302/14773374/e021e1e4-0adb-11e6-83ee-285daa4a4c4b.jpg)

- Add a Project Member
![u-projects-users-add](https://cloud.githubusercontent.com/assets/5027302/14773379/f76b0290-0adb-11e6-82c3-6df0cc396b3e.jpg)

- Project Member Management
![u-projects-users-edit](https://cloud.githubusercontent.com/assets/5027302/14773395/22ad9a26-0adc-11e6-8587-7b494496048e.jpg)

- Audit Logs
![u-projects-logs](https://cloud.githubusercontent.com/assets/5027302/14773403/365b7412-0adc-11e6-8891-d409d785793e.jpg)

- Advanced Search for Audit Logs
![u-projects-logs_-_adsearch](https://cloud.githubusercontent.com/assets/5027302/14773409/47bf1416-0adc-11e6-808f-000181aa948a.jpg)

- Sign Up
![sign-up](https://cloud.githubusercontent.com/assets/5027302/14773440/a946655e-0adc-11e6-8069-d25e5cb18091.jpg)

- After Login, Select Account Settings
![account-settings](https://cloud.githubusercontent.com/assets/5027302/14773450/c7d565b0-0adc-11e6-87b3-7e23e030914a.jpg)

- Show Account Info
![accountinfo](https://cloud.githubusercontent.com/assets/5027302/14773464/e6c78804-0adc-11e6-8aee-b5effe1dd9e7.jpg)

- Change Password
![changepassword](https://cloud.githubusercontent.com/assets/5027302/14773470/0ab969da-0add-11e6-9c34-5d2bcb7b7221.jpg)

- Change Languages
![language](https://cloud.githubusercontent.com/assets/5027302/14773488/48fa5808-0add-11e6-9ae3-3b2ee110bf11.jpg)

- Admin Options, Add User
![adduserharbor](https://cloud.githubusercontent.com/assets/5027302/14773621/baf5fcc2-0ade-11e6-8ca1-9f95f9ed1f62.jpg)

- Admin Options, Add User Successfully
![adduser_ok](https://cloud.githubusercontent.com/assets/5027302/14773635/0dc0e6a6-0adf-11e6-88e3-02f64455b09b.jpg)

- Admin Options, Something Wrong When Adding User
![adduser_failed](https://cloud.githubusercontent.com/assets/5027302/14773642/32a231e6-0adf-11e6-8502-e3df5067dea3.jpg)

- Admin Options, Make User As Admin
![a-users-add](https://cloud.githubusercontent.com/assets/5027302/14773544/cea81b66-0add-11e6-8f29-81f3bcd0e605.jpg)

- Admin Options, Make User As Normal.
![a-users-remove](https://cloud.githubusercontent.com/assets/5027302/14773566/07448900-0ade-11e6-9a93-3896e87a159d.jpg)

- Admin Options, System Configuration and Management
![a-systemmanagement](https://cloud.githubusercontent.com/assets/5027302/14773584/2ab837c4-0ade-11e6-92f1-cb1a6af68512.jpg)

**Comment by bobbyjunzhang** [comment]
We are redesigning the UI of Harbor, and would like to request for your comments. Please let us know how you like / don't like the new UI. Thanks!

**Comment by hmwenchen** [comment]
The detail pages look good, but not the dashboard view page.
It seems to me that the dashboard view has too much details on it. Is it possible to simplify log info on dashboard? There is already a detailed page for audit log.

**Comment by senk** [comment]
despite the design, the html and javascript should be strictly seperated using angular.js

**Comment by bobbyjunzhang** [comment]
@senk Thank you for the suggestion. We are using angular.js in the new design.

**Comment by bobbyjunzhang** [comment]
@hmwenchen Great suggestion! How do you think we can simplify the log info in the dashboard view page? Or shall we simply remove it, if you think it is irrelevant.

**Comment by hmwenchen** [comment]
It can be removed. Or, it may be integrated into summary section.

**Comment by yurinnick** [comment]
It might be a good idea to put user's dropdown menu to the top right corner and also make it a bit bigger + add profile picture.

**Comment by reasonerjt** [comment]
Please open new issue as the new UI has released in 0.3.0
