### ISSUE TITLE
Registry does not support SWIFT?!?!?

### ISSUE THREAD

**Issue by c6opuc** [vmware/harbor#1509]
Hello I am using harbor 0.5.0 as OVA. 
We also have EMC Isilon Storage that supports SWIFT and I am trying to integrate both together, but unfortunately I get errors like this whenever I configure swift instead of the default storage. The line 9 is actually is a beginning of the swift section. :

```
Mar  3 15:21:46 172.18.0.1 registry[861]: configuration error: error parsing /etc/registry/config.yml: yaml: line 9: found character that cannot start any token
Mar  3 15:21:46 172.18.0.1 registry[861]: 
Mar  3 15:21:46 172.18.0.1 registry[861]: Usage: 
Mar  3 15:21:46 172.18.0.1 registry[861]:   registry serve <config> [flags]
Mar  3 15:21:46 172.18.0.1 registry[861]: Flags:
Mar  3 15:21:46 172.18.0.1 registry[861]:   -h, --help=false: help for serve
Mar  3 15:21:46 172.18.0.1 registry[861]: 
Mar  3 15:21:46 172.18.0.1 registry[861]: 
Mar  3 15:21:46 172.18.0.1 registry[861]: Additional help topics:
Mar  3 15:21:46 172.18.0.1 registry[861]: 
```

It seems that swift is not recognized as a valid storage backend by registry although documantation says it should.

Here is what I changed:

Update common/templates/registry/config.yml and replace storage section that looks like this:
```javascript
    storage:
        cache:
            layerinfo: inmemory
        filesystem:
            rootdirectory: /storage
        maintenance:
            uploadpurging:
                enabled: false
        delete:
            enabled: true
```
to: 
```javascript
    storage:
        cache:
            layerinfo: inmemory
        swift:
            username: user:user
            password: PASSW0RD
            authurl: http://swift.storage.isilon:28080/auth/v1.0
            container: harbor
        maintenance:
            uploadpurging:
                enabled: false
        delete:
            enabled: true
```
Am I doing something wrong?

**Comment by niyanchun** [comment]
seems right. I ever config ceph with swift interface, my config is below:

```
    swift:
        authurl: http://xxxx:880/auth/v1
        username: xxx:swift
        password: ******
        container: registry
```

And it works fine. 

BTW: I use harbor 0.5.

**Comment by c6opuc** [comment]
Thanks niyanchun,

would you please post the entire common/templates/registry/config.yml? May be I have an error somewhere else. And one more question: do you use OVA or just a normal tar.gz as installation source?

**Comment by niyanchun** [comment]
my complete config is as below：

```
root@compute20:~/allan/registry/harbor/make# cat common/templates/registry/config.yml
version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
    cache:
        layerinfo: inmemory
    swift:
        authurl: http://*****:880/auth/v1
        username: ****:swift
        password: *****
        container: registry
    maintenance:
        uploadpurging:
            enabled: false
    delete:
        enabled: true
http:
    addr: :5000
    secret: placeholder
    debug:
        addr: localhost:5001
auth:
  token:
    issuer: registry-token-issuer
    realm: https://xxxx/service/token
    rootcertbundle: /etc/registry/root.crt
    service: token-service

notifications:
  endpoints:
      - name: harbor
        disabled: false
        url: http://ui/service/notifications
        timeout: 3000ms
        threshold: 5
        backoff: 1s
```

And I installed from souce code.

**Comment by c6opuc** [comment]
Thanks niyanchun.

My config looks identically to yours. I suspect that the issue is with the binaries or OVA. How do I push it further? Do I need to file a case at VMWARE to get this looked at and fixed?

**Comment by niyanchun** [comment]
I don't think something wrong with the binaries or OVA. From your error message: 

```
Mar  3 15:21:46 172.18.0.1 registry[861]: configuration error: error parsing /etc/registry/config.yml: yaml: line 9: found character that cannot start any token
```

I seems something wrong with the config, and the error is report by the registry image, not others. I have two suggestions:

- check your config again, such as there should not have any tabs in yaml(use spaces)
- if you could, you can git clone the registy source code, and start it from your own computer with your config. And that is not too difficult. IDEA may be a good choice for such huge project.  Of course, you can send me your config file, I could do it for you when I'm free.

Hope to help you.

**Comment by c6opuc** [comment]
niyanchun,

yes you were right, the tabs were the reason for the error. I moved one step forward but got stuck again :-(
Now I cannot  push the images. The SWIFT container is getting created upon push but then error HTTP/500 is reported. I guess it is on the storage side now. Thanks a lot for your help wit the tabs/spaces. I did not know yaml is so sensitive to tabs :-)

**Comment by niyanchun** [comment]
Yeah, tabs is illegal in yaml~

**Comment by reasonerjt** [comment]
Thanks @niyanchun !
@c6opuc so your issue has been fixed right?

**Comment by c6opuc** [comment]
Yes. the issue is fixed. I am still fighting with the storage though,
but it has nothing to do with the initial problem :-)

**Comment by reasonerjt** [comment]
Let me close this issue and happy fighting :)
