### ISSUE TITLE
Legal clearance.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#1516]
get legal approvals for all open source packages and update the LICENSE.

**Comment by reasonerjt** [comment]
@steven-zou please provide the list of .js library you used for UI work.

**Comment by reasonerjt** [comment]
@ywk253100 Please provide the package/version/license you added for this release by adding comment.

**Comment by steven-zou** [comment]
Angular2 | License: The MIT License | github: https://github.com/angular/angular | version: 2.4.7

**Comment by steven-zou** [comment]
ngx-translate | License: https://github.com/ngx-translate/core/blob/master/LICENSE | github：https://github.com/ngx-translate/core | version: v6.0.0

**Comment by steven-zou** [comment]
@ngx-translate/http-loader | License: https://github.com/ngx-translate/http-loader/blob/master/LICENSE | github: https://github.com/ngx-translate/http-loader | version: 0.0.3

**Comment by steven-zou** [comment]
angular2-cookie | License: MIT | github: https://github.com/salemdar/angular2-cookie | version: 1.2.6

**Comment by steven-zou** [comment]
clarity | License: MIT | github: https://github.com/vmware/clarity | version: 0.8.6

**Comment by steven-zou** [comment]
rxjs | License: Apache 2.0 | github: https://github.com/ReactiveX/RxJS | version: 5.1.1

**Comment by steven-zou** [comment]
zone.js | License: MIT | github: https://github.com/angular/zone.js/ | version: 0.7.6

**Comment by steven-zou** [comment]
web-animations-js | License:  | github: https://github.com/web-animations | version: 2.2.2

**Comment by steven-zou** [comment]
core-js | License: MIT | github: https://github.com/zloirock/core-js | version: 2.4.1

**Comment by steven-zou** [comment]
mutationobserver-shim | License: http://www.wtfpl.net/ | github: https://github.com/megawac/MutationObserver.js | version: 0.3.2

**Comment by steven-zou** [comment]
ts-helpers | License: MIT | github: https://github.com/ngParty/ts-helpers | version: 1.1.2
