### ISSUE TITLE
how about remove beego?

### ISSUE THREAD

**Issue by xiaods** [vmware/harbor#152]
beego is heavily usage on the design. how about Gin ?

**Comment by reasonerjt** [comment]
How does its heaviness impact?

**Comment by xiaods** [comment]
there many more components, orm, session

**Comment by bobbyjunzhang** [comment]
@xiaods What would we benefit if we switched from Beego to Gin?

**Comment by xiaods** [comment]
fast performance, low overhead

http://www.slant.co/topics/1412/compare/~revel_vs_beego_vs_gin-gonic

**Comment by hainingzhang** [comment]
thanks for the suggestion. Will consider it. closing it for now.
