### ISSUE TITLE
Remove properties in harbor.cfg which are not necessary

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#1542]
As some configurations can be modified on UI, some of them in harbor.cfg can be removed.

**Comment by reasonerjt** [comment]
@ywk253100 let's hold this for this sprint.

**Comment by ywk253100** [comment]
Move this to backlog considering the upgrade progress.

**Comment by reasonerjt** [comment]
Removing these attributes will require some signifiant update in the "prepare" script, IMO this can be deferred.

**Comment by reasonerjt** [comment]
Close as fixed.
