### ISSUE TITLE
software licence issue

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#1555]
harbor clarity UI
there is an EULA in harbor clarity UI, since harbor is an open source software,  an EULA seems unreasonable.
![eula](https://cloud.githubusercontent.com/assets/23101283/23740398/5a144724-04de-11e7-81fc-c670823d3b45.PNG)

**Comment by steven-zou** [comment]
@lweitzman @reasonerjt 

What's your opinion for this issue?

**Comment by reasonerjt** [comment]
In previous release I recall the EULA and licensing is on the vic-product.

**Comment by lweitzman** [comment]
i think this is a question for the legal team. but i assume we will need something.
