### ISSUE TITLE
advanced search not localized

### ISSUE THREAD

**Issue by senk** [vmware/harbor#157]
advanced search is not localized (see screenshot)
![screenshot 2016-04-26 08 10 48](https://cloud.githubusercontent.com/assets/710568/14808559/7b85c7fe-0b86-11e6-8f9f-cbc894eeff3c.png)

**Comment by senk** [comment]
maybe this was intentional

**Comment by wknet123** [comment]
I think these verbs should be consistent with Docker native definitions.
