### ISSUE TITLE
the administrator without having to provide the user's original password can reset the user password exist a bug

### ISSUE THREAD

**Issue by bianhua2015** [vmware/harbor#1573]
When modifying user.go in  /harbor/src/ui/api to realize the function that the administrator without having to provide the user's original password can reset the user password . After debugging found there is a bug in harbor/src/common/dao user. go , we need to change the func ChangeUserPassword
![image](https://cloud.githubusercontent.com/assets/12478883/23847261/92ab9854-080c-11e7-9fbe-c9610ade5c52.png)

**Comment by ywk253100** [comment]
Duplicate with #840
