### ISSUE TITLE
在未登录的情况下可以查看，下载仓库镜像

### ISSUE THREAD

**Issue by vcent** [vmware/harbor#158]
在浏览器打开： http://*/registry/detail?project_id=1
在未登陆的状态下，也可以查看镜像信息
如果我启动了harbor服务，那就是任何人都可以看到我的镜像， 都可以pull下来

**Comment by wknet123** [comment]
该项目默认就是公开的

**Comment by int32bit** [comment]
Make it private can solve your problem .

**Comment by vcent** [comment]
@int32bit  how can i make it private?

**Comment by vcent** [comment]
@wknet123  Harbor is designed to be deployed in a private environment of an organization. A private registry is important for organizations who care much about security.

**Comment by int32bit** [comment]
@vcent You can see a button in your project list(http://your_addr/registry/project).

**Comment by vcent** [comment]
@int32bit  thanks a lot
