### ISSUE TITLE
Front Page and logo should be customizable

### ISSUE THREAD

**Issue by senk** [vmware/harbor#159]
I think it would be nice if the text on the Front Page and the logo can be customized

**Comment by reasonerjt** [comment]
I don't think it's very necessary to make it configurable, as user can always fork our code and make update to UI.

**Comment by bobbyjunzhang** [comment]
Well, I guess _developers_ can always fork our code and make update to UI. This might not hold for _users_ - many of our _users _can be IT admin folks.
