### ISSUE TITLE
Confusing text in new project dialog

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#1590]
The label **"Public/Private"** not clear to me that the new project is **"public"** or not, when the check box is checked

<img width="647" alt="screen shot 2017-03-14 at 5 03 27 pm" src="https://cloud.githubusercontent.com/assets/2390463/23893112/3c8adbac-08d8-11e7-996a-030f2a3c21cb.png">

**Comment by lweitzman** [comment]
current mock is this...
<img width="584" alt="screen shot 2017-03-14 at 10 01 51 am" src="https://cloud.githubusercontent.com/assets/626032/23904212/67b96ebe-089d-11e7-8263-01e0b77ac224.png">
