### ISSUE TITLE
branch dev build error

### ISSUE THREAD

**Issue by roldancer** [vmware/harbor#1596]
Hi All, I'm trying to build the DEV branch, but I get the follwing error, any idea ? the clarity image is trying to use a proxy called proxy.vmware.com ....

make install -e GOBUILDIMAGE=golang:1.7.3 COMPILETAG=compile_golangimage -e CLARITYIMAGE=danieljt/harbor-clarity-base:0.8.3

➜ Better to upgrade golang package to 1.6.0+ or use golang docker image build binary.

Note: docker version: 1.10.3

Note: docker-compose version: 1.8.0
compiling binary for clarity ui...
npm info it worked if it ends with ok
npm info using npm@4.1.2
npm info using node@v7.5.0
npm info attempt registry request try #1 at 10:28:36 PM
npm http request GET https://registry.npmjs.org/fs
npm info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.vmware.com proxy.vmware.com:3128
npm info attempt registry request try #2 at 10:28:46 PM
npm http request GET https://registry.npmjs.org/fs
npm info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.vmware.com proxy.vmware.com:3128
npm info attempt registry request try #3 at 10:29:47 PM
npm http request GET https://registry.npmjs.org/fs
npm ERR! Linux 3.13.0-54-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.vmware.com proxy.vmware.com:3128
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /clarity-seed/npm-debug.log
make: *** [compile_clarity] Error 1

Thanks.

**Comment by wy65701436** [comment]
roldancer, thanks for pointing this. The 0.8.3 is now an internal used image for Harbor development, we will provide an clean image soon without npm proxy.

**Comment by wy65701436** [comment]
@roldancer the clarity image has been upgraded to 0.8.4 which doesn't contain the proxy info. We have closed this issue, if you still encounter any error, feel free to reopen it.
