### ISSUE TITLE
Refine the related components of Harbor new UI based on some suggestions

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#1598]
Ø  Add role to project detail;
Ø  Move ‘replication’ of project to right most tab; 
Ø  Use solid flat buttons for + actions;

**Comment by steven-zou** [comment]
@wknet123 

  Is this issue done?

**Comment by steven-zou** [comment]
Add role to project detail;

**Comment by wknet123** [comment]
Fixed with PR #1791

**Comment by lweitzman** [comment]
i disagree with all these "new" requirements. having a role on project details is ok, but it needs to be designed. i think logs should be the last tab. and buttons should not be solid.

**Comment by steven-zou** [comment]
@proposed by @akshayl 

  We'd better make a stable and consistent decisions otherwise we'll take efforts to change it ‘back and forth’.

**Comment by steven-zou** [comment]
Related with #1685

**Comment by steven-zou** [comment]
@lweitzman @akshayl 

  So what's the final decision? Which tab should be the right most one?
