### ISSUE TITLE
Add Make process in travis.

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#1599]
1, Enable Https.
2, Automatically generate crt and key.
3, Add make install .
4, Add an parameter to index proxy.

**Comment by reasonerjt** [comment]
Please also consider use simple command to verify things work after enabling docker content trust, you may need "expect" for that, maybe open a new issue.

**Comment by wy65701436** [comment]
I will open an new issue to track this. This will only enable Make in travis.

**Comment by wy65701436** [comment]
Close it as done.
