### ISSUE TITLE
Failed to run unit tests of notary

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#1600]
--- FAIL: TestGetTargets (0.03s)
	Error Trace:	helper_test.go:29
	Error:      	Expected nil, but got: signed.ErrExpired{Role:"timestamp", Expired:"Tue Mar 14 12:58:40 UTC 2017"}
	Messages:   	Unexpected error: timestamp expired at Tue Mar 14 12:58:40 UTC 2017
	Error Trace:	helper_test.go:30
	Error:      	Not equal: 
	            	expected: 1
	            	received: 0

**Comment by reasonerjt** [comment]
Hmm, had to update the code of notary to generate a timestamp.json with longer expiry time...
