### ISSUE TITLE
UI: email settings

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#1603]
Harbor clarity ui
while test email server,click other tag in configuration, the spin will also show and the hint of connect error show too short

![email2](https://cloud.githubusercontent.com/assets/23101283/23935750/b15428ac-0988-11e7-991b-6ae742b3121b.PNG)
![emai1](https://cloud.githubusercontent.com/assets/23101283/23935734/932d3562-0988-11e7-91aa-34efa362c9b1.PNG)

**Comment by reasonerjt** [comment]
Verified.

**Comment by sigsbee** [comment]
fixed
