### ISSUE TITLE
Header - search should be icon on the right side

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1613]
the search icon should be next to the language selection with a divider
see mockup: https://vmware.invisionapp.com/share/BFA95DAMR#/219012300_Harbor_-_Projects
clarity header search standard: https://github.com/vmware/clarity/issues/186

**Comment by steven-zou** [comment]
@lweitzman 

  The search box on header is current clarity search implementation. The search on the right side with drop down input box is still undergoing. If we insist this design, we may need to implement it by ourselves. 
  See https://vmware.github.io/clarity/documentation.

**Comment by lweitzman** [comment]
we can make this a P1 priority

**Comment by steven-zou** [comment]
Sure.

**Comment by lweitzman** [comment]
don't think this is an important issue. going to close it.
