### ISSUE TITLE
Right hand side Projects window spacing

### ISSUE THREAD

**Issue by tonycgil** [vmware/harbor#1616]
Spacing specs for this can be seen here
<img width="367" alt="screen shot 2017-03-15 at 1 34 45 pm" src="https://cloud.githubusercontent.com/assets/25991813/23969587/38856890-0984-11e7-9111-96d4c7986b65.png">

**Comment by steven-zou** [comment]
Will merge with #1687

**Comment by steven-zou** [comment]
add margin-left 12px plus the 24px padding-right of content area,leave 36px. Look like a little wider.
