### ISSUE TITLE
New project dialog confusion about public private setting

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1619]
the setting for public / private is confusing in the new project dialog. 
here is the mockup that makes it more clear what is happening. the information icon will be the "i" within a circle. 

![screen shot 2017-03-15 at 4 43 45 pm](https://cloud.githubusercontent.com/assets/626032/23970130/3618624a-099f-11e7-86ab-b81c8d47ae52.png)

**Comment by wknet123** [comment]
We don't provide description in creation project.

**Comment by lweitzman** [comment]
Why is the signpost help shown all the time? I thought we were going to put that into a signpost popup.

**Comment by steven-zou** [comment]
@wknet123 

Any comments?

**Comment by lweitzman** [comment]
we should move the help text into the signpost help icon.

**Comment by steven-zou** [comment]
@wknet123 

  Let's use icon tooltip.

**Comment by steven-zou** [comment]
Fixed in #2315
