### ISSUE TITLE
Modal specific error pattern

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1620]
When creating a new project and providing an invalid name, that is a specific error and should be handled like:

![screen shot 2017-03-15 at 4 50 51 pm](https://cloud.githubusercontent.com/assets/626032/23970277/ab7340be-099f-11e7-9dc4-b7c54e52c835.png)

**Comment by steven-zou** [comment]
Will use instant existing check method to handle this requirement

**Comment by steven-zou** [comment]
@wknet123  please have a look at the project creation

**Comment by wknet123** [comment]
Already made a workaround.
