### ISSUE TITLE
Selecting an action from the datagrid actions dropdown does not remove menu

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1621]
After selecting an actions in the datagrid menu, the menu does not disappear.
Here i switched between public and private on the project and the menu stays visible.
![screen shot 2017-03-15 at 4 53 30 pm](https://cloud.githubusercontent.com/assets/626032/23970455/374b2a8e-09a0-11e7-9b6e-488e679e0770.png)

**Comment by steven-zou** [comment]
A known issue

**Comment by steven-zou** [comment]
Same root cause with #1614. Fixed after we adopted the Clarity action flow component in their latest released version. (>0.8.6)
