### ISSUE TITLE
When session times out, 2 warning messages appear.

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1637]
After letting the session time out, clicking on the login button produces a second warning message with another login button. Neither button actually takes you back to the login page.

![double error message when session time out](https://cloud.githubusercontent.com/assets/626032/24014457/67639538-0a5b-11e7-8fb0-a9e2e2412e84.png)

**Comment by steven-zou** [comment]
Cause by statistics component on dashboard.

**Comment by lweitzman** [comment]
now when it times out i only see one warning but the login link does not work.
![screen shot 2017-03-21 at 1 37 38 pm](https://cloud.githubusercontent.com/assets/626032/24161756/aee26810-0e3b-11e7-9745-c6bf781973d5.png)

**Comment by steven-zou** [comment]
We already fixed this issue but did not enabled in the demo. Fix will contained in next env update.
