### ISSUE TITLE
Links in About dialog don't go to the right place

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1638]
the end user license agreement and open source links don't navigate to the right place.

**Comment by steven-zou** [comment]
Who can provide the link urls? @lweitzman @reasonerjt

**Comment by lweitzman** [comment]
@akshayl should be able to provide content or links to the right place

**Comment by steven-zou** [comment]
@lweitzman @akshayl 

  Can we confirm the links?

**Comment by steven-zou** [comment]
@lweitzman @akshayl 

Looking forward to the answer.

**Comment by steven-zou** [comment]
@lweitzman @akshayl

Looking forward to the answer.

**Comment by steven-zou** [comment]
@lweitzman @akshayl 

Point the link to "https://raw.githubusercontent.com/vmware/harbor/master/LICENSE"
