### ISSUE TITLE
"Replication rules" should be used consistently throughout the UI

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1639]
there are many places where the replications rules are called policies. we should use the term "replication rule" instead.
in project actions menu:
![project actions](https://cloud.githubusercontent.com/assets/626032/24015243/4b8b3458-0a5e-11e7-8489-27bbab2d9053.png)

**Comment by lweitzman** [comment]
filters still say "filter policies" in both the project / replication tab and the left nav replication / replication rule tab

**Comment by steven-zou** [comment]
@wknet123 

  Please check all the related parts to make sure all keep consistent

**Comment by lweitzman** [comment]
Filter on jobs in the replication page should say "Filter Jobs"
<img width="1032" alt="screen shot 2017-03-29 at 10 00 04 am" src="https://cloud.githubusercontent.com/assets/626032/24458315/8dfe5628-1466-11e7-80d8-38d621062cc0.png">
