### ISSUE TITLE
Action button for creating new objects should not say "NEW"

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1640]
An action button above a datagrid has a + icon plus the name of the thing being created. Don't use the word NEW.

in the New Endpoint
![new endpoint](https://cloud.githubusercontent.com/assets/626032/24015390/bbb01122-0a5e-11e7-8957-182240cbfc92.png)

in the New Replication Rule
![project tab](https://cloud.githubusercontent.com/assets/626032/24015424/d0e0d5cc-0a5e-11e7-88d6-a3234aaffb84.png)

**Comment by steven-zou** [comment]
Already fixed in code but not updated to the demo env.
