### ISSUE TITLE
When navigating away from the configuration pages and the page content has changed, notify the user to save or cancel.

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1641]
Changes will be lost if the user navigates away from the configuration pages without saving. Provide a dialog to either save the content and continue or cancel and return to the configuration page.
![screen shot 2017-03-16 at 3 42 19 pm](https://cloud.githubusercontent.com/assets/626032/24015792/df189368-0a5f-11e7-84e6-83c6714d21a6.png)

**Comment by steven-zou** [comment]
Confirmation added before leaving if there are changes unsaved.

**Comment by lweitzman** [comment]
You also need to pop up the dialog when the user navigates to a new configuration tab. otherwise they will not know which tab needs to be saved.

**Comment by steven-zou** [comment]
Support proposing confirmation when switching tab if changes existing in last tab

**Comment by steven-zou** [comment]
Comment:

  Use clarity static tab instead of clr-tab

**Comment by lweitzman** [comment]
added new issue regarding the text in the confirmation dialog
