### ISSUE TITLE
Add User modal has label, input fields alignment issues and scrollbar 

### ISSUE THREAD

**Issue by tonycgil** [vmware/harbor#1644]
UI components need alignment. 
![administration-add-user](https://cloud.githubusercontent.com/assets/25991813/24016576/f32c7bf0-0a49-11e7-8b94-5b63ae918aa9.png)

**Comment by steven-zou** [comment]
Default clarity form style, will try to override the styles. 

Will check and fix all other related forms.

**Comment by steven-zou** [comment]
Adjust the layout
