### ISSUE TITLE
Left nav - reduce line height

### ISSUE THREAD

**Issue by tonycgil** [vmware/harbor#1645]
Reduce the left navigation line height for even spacing. 
![screen shot 2017-03-16 at 3 11 22 pm](https://cloud.githubusercontent.com/assets/25991813/24020826/1955c83e-0a5b-11e7-97c7-9d6083e6ac24.png)

**Comment by steven-zou** [comment]
This is the default clarity style. If needed, we'll try to override the default style.

**Comment by steven-zou** [comment]
Clarity does not use line-height, they use margin to control the space.

Changed margin-top: "margin-top: 4px;"
