### ISSUE TITLE
too many records 

### ISSUE THREAD

**Issue by wemeya** [vmware/harbor#165]
I pulled the latest code and run harbor, find below problem: 

![image](https://cloud.githubusercontent.com/assets/12540577/14813662/56311d7e-0bd5-11e6-8ce0-1812b9bb3335.png)

**Comment by reasonerjt** [comment]
I see lot of retries in the log of registry, seems there's perf issue in docker 1.11 in embeded dns, I tried to increase the timeout from nansec level to mili sec level and the problem is gone. 
I'll update the config.yml and follow up to investigate how the dns is implemented.
