### ISSUE TITLE
[UI]it takes too long to load harbor clarity home page.

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#1661]

**Comment by steven-zou** [comment]
Let's put it as P1. Will introduce packing and compressing in build process later.

**Comment by steven-zou** [comment]
@wknet123 

wk will take a look at this.
enable js/css compressing option when build.

**Comment by wknet123** [comment]
@wy65701436 , please re-check this issue by using our current AoT building result.

**Comment by steven-zou** [comment]
As AoT build is enabled, let's close this issue.
