### ISSUE TITLE
[UI] the Waring message isn't clear for me when to sign up an new account. 

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#1662]
![warning](https://cloud.githubusercontent.com/assets/2841473/24087494/bff1c90c-0d5a-11e7-8bf9-20115e3c08d9.png)

**Comment by wy65701436** [comment]
what do you mean by "Form value changed, confirm to cancel?"

**Comment by reasonerjt** [comment]
I believe this is a known issue that has been fixed?

**Comment by steven-zou** [comment]
"CONFIRM_SUMMARY": "Some changes are not saved yet, do you really want to leave?",

**Comment by steven-zou** [comment]
"Some changes are not saved yet, do you really want to cancel?",

**Comment by lweitzman** [comment]
This warning should be for in page editing confirmation dialog. I don't think we need it on a cancel on a modal dialog. also, it should probably say "Some changes have not been saved. Do you want to cancel?" 
Actually wonder if this will be ambiguous. it might be better to say "Some changes have not been saved. Click Continue to cancel your changes?" (assuming the user clicked on some navigation outside of the in page editing.)

**Comment by steven-zou** [comment]
@wy65701436 

  Please help to verify the fix of this issue. Thanks

**Comment by wy65701436** [comment]
close it as fixed.
