### ISSUE TITLE
[UI] Why password cannot have special characters？

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#1663]
I tried to sign up an new user with password contains special characters, but it blocked by UI.

**Comment by wy65701436** [comment]
If I specify the password with special character password, UI doesn't give me any error or warning. I know Harbor don't allow user to set password with special character. But, the UI show point that.

**Comment by steven-zou** [comment]
Now, will clear indicating the password pattern under the password input box. See design https://vmware.invisionapp.com/share/BFA95DAMR#/screens/221420552.

Mark this as done as we will not change regexp pattern at this moment.

**Comment by wy65701436** [comment]
still can be reproduce at build f62b890. Please help to check.

**Comment by wy65701436** [comment]
passed on build harbor-offline-installer-0.5.0-454-g2092387.tgz.
