### ISSUE TITLE
member.component.html has problem caused by merge action

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#1681]
member.component.html has problem caused by merge action

**Comment by wy65701436** [comment]
08:24:59.423 Error: Template parse errors:
Unexpected closing tag "div" ("
     </clr-datagrid>
  </div>
[ERROR ->]</div>"): MemberComponent@56:01 vendor.bundle.js:95902:20

**Comment by wy65701436** [comment]
@wknet123 see the errors. I tried to build UI with latest merged code, but get this error on launching home page.

**Comment by wknet123** [comment]
This was caused by incorrect code merging, already fixed.

**Comment by steven-zou** [comment]
close it.
