### ISSUE TITLE
Buttons in tool bar should be flat/tertiary buttons

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1685]
the buttons are to dominant and should be tertiary buttons 

![screen shot 2017-03-20 at 1 23 50 pm](https://cloud.githubusercontent.com/assets/626032/24112633/8f8230c0-0d70-11e7-8352-6f1ba57c4e95.png)

**Comment by steven-zou** [comment]
@lweitzman 

  This is suggested by @akshayl , you can confirm with him what style should be used for these buttons.

**Comment by lweitzman** [comment]
i will let @tonycgil provide the final say here. but i think the primary button (all blue) is way to strong and should just be the colored icon and colored text as in the mockups.

**Comment by tonycgil** [comment]
This is a datagrid action so it should follow the tool bar which uses [icon] Flat button component

**Comment by steven-zou** [comment]
@lweitzman @tonycgil 

  Do we need @akshayl to confirm the design change?

**Comment by lweitzman** [comment]
No but he should be aware of it.

**Comment by steven-zou** [comment]
Sure.

**Comment by steven-zou** [comment]
Related with #1598

**Comment by steven-zou** [comment]
Change back to flat button

**Comment by steven-zou** [comment]
@lweitzman @tonycgil 

Chang back to 'Tertiary Button'.
