### ISSUE TITLE
Search result panel is closed when clearing the search terms in search box but should NOT

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1686]
when only one result in search there is an extra row in the datagrid

![search results has extra row in datagrid](https://cloud.githubusercontent.com/assets/626032/24113806/530ed9be-0d74-11e7-80ec-b157bb37e003.png)

BTW, when do we clear the search field. seems like when you click the "back" link, it should clear the field. maybe there is a dropdown of recent searches so the user can easily get that search back. (dropdown is a P1 or P2 probably)

**Comment by steven-zou** [comment]
@lweitzman 

  Right, if you clear the search filed and the search results panel existing, it will close the result overlay panel. Is it expected or you just want to clear field and keep the panel it was?

**Comment by lweitzman** [comment]
i think we should leave the result page as is until the user explicitly clicks "Back" or initiates a new search

**Comment by steven-zou** [comment]
Got you

**Comment by steven-zou** [comment]
@lweitzman 

  The extra row is designed style of Clarity datagrid. Then we'll not override its default style. I'll use this issue to track the issue **'Search result panel is closed when clear the search terms in search box but should NOT'**.

**Comment by steven-zou** [comment]
Just leave the search result page as it is when clearing the search term in box
