### ISSUE TITLE
Metrics should show up on projects page

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1687]
the metrics should show up on the project page. now there is a gauge for storage as well.
developers on the photon platform have implemented the gauge and maybe you can reuse that component.

https://vmware.invisionapp.com/share/BFA95DAMR#/219626325_Harbor_-_VIC_Header

Specs: 
![harbor-storage-metric-final](https://cloud.githubusercontent.com/assets/25991813/24118148/0a21c680-0d6a-11e7-844e-f9b5db3edb0c.png)

**Comment by steven-zou** [comment]
Show project metrics on the project page now.

@lweitzman 
As you raised a new issue #1709 to track the storage metrics, I'll make this one as done.

**Comment by lweitzman** [comment]
[Moved from 1709 to this issue]
font is incorrect on the numbered metrics for projects and repos
if no storage info, don't display it.
also, these metrics should be moved up the page.

![538bd992-107f-11e7-95df-af1e0ecec959](https://cloud.githubusercontent.com/assets/626032/24307430/7f02cafc-109a-11e7-9767-86850bfaf073.png)

**Comment by steven-zou** [comment]
Is 'font-family' incorrect? @lweitzman Could you please help to clarify the font-family with standard formal name?

**Comment by steven-zou** [comment]
As moved issue to #1709, to avoid duplicated items, mark this as 'Close'. @lweitzman

**Comment by lweitzman** [comment]
the font is still wrong. and the whole metrics should follow the spec tony added in the first comment of this issue.

**Comment by steven-zou** [comment]
Change 'font-family' to clarity style: 'Metropolis,"Avenir Next","Helvetica Neue",Arial,sans-serif'. Avoid missing fonts in the os.

Metrics of layout changed as well.

**Comment by lweitzman** [comment]
font is still wrong
![screen shot 2017-04-03 at 8 34 48 am](https://cloud.githubusercontent.com/assets/626032/24609337/77192c7c-1848-11e7-8720-c8035d6b4044.png)

**Comment by steven-zou** [comment]
Here is the snapshot on my system:
<img width="1376" alt="2017-04-05 12 19 18" src="https://cloud.githubusercontent.com/assets/5753287/24689593/270fa220-19fa-11e7-899d-c8600e5de9cd.png">


Missing fonts on OS?

**Comment by steven-zou** [comment]
@lweitzman 

Fonts fixed now.

**Comment by lweitzman** [comment]
its not on https://10.117.4.151/harbor/projects yet.

**Comment by tonycgil** [comment]
Things are looking good. Can we make a few more adjustments?
1) Mach "2" gage number with others in size
2) Shrink gage size to about 50%
3) Align "15 GB Limit" horizontally with other metrics to the left of it

![storage-gage-2](https://cloud.githubusercontent.com/assets/25991813/24715331/d5723906-19df-11e7-9910-c3da01c4e370.png)

**Comment by steven-zou** [comment]
@lweitzman @tonycgil 

  Updated storage metrics.

**Comment by tonycgil** [comment]
Looks good!

**Comment by lweitzman** [comment]
awesome!
