### ISSUE TITLE
Use of "Endpoint" consistently (instead of destination)

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1688]
in the replication link in the left nav, the endpoints tab has a datagrid that labels the name as "Destination name". that should just say "Name" 
the filter should say "Filter endpoints"

**Comment by steven-zou** [comment]
@wknet123 

  Please take a loot at this issue.

**Comment by wknet123** [comment]
We need to make these changes consistent by more detailed disscussion.

**Comment by steven-zou** [comment]
@wknet123 

  Need discussion with who? @lweitzman , @reasonerjt or @tonycgil ?

**Comment by lweitzman** [comment]
the filter says "Filter Targets"  should say Filter Endpoints
<img width="1024" alt="screen shot 2017-03-29 at 9 57 28 am" src="https://cloud.githubusercontent.com/assets/626032/24458192/373b1006-1466-11e7-8c6d-106d2a190adc.png">
