### ISSUE TITLE
a datgrid with 6 rows is spread across 2 pages

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1689]
looking at projects, i see that the datagrid has 6 items but they are spread across 2 pages.
there should be no reason to paginate 6 items.
<img width="849" alt="screen shot 2017-03-20 at 2 45 32 pm" src="https://cloud.githubusercontent.com/assets/626032/24116136/12da24cc-0d7c-11e7-821a-8af00290886a.png">

**Comment by steven-zou** [comment]
@wknet123 

  Please take a look at this issue and the related ones if existing.

**Comment by wknet123** [comment]
Just in test status, we'll adjust it to a fit size.
