### ISSUE TITLE
don't have help text just repeat the label for the field

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1690]
When the hint text just repeats the label of the field with "Enter" in front, don't use any hint text.
In the Add User dialog all hint text can be removed.

<img width="570" alt="screen shot 2017-03-20 at 3 02 06 pm" src="https://cloud.githubusercontent.com/assets/626032/24116859/699a9b50-0d7e-11e7-80b0-15f3ea2f05af.png">

**Comment by steven-zou** [comment]
Removed!
