### ISSUE TITLE
Use the term "User" instead of "Member"

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1691]
In projects users, the add action is to add a member. Also, the filter shows "Filter members". Members should be replaced with "User"

<img width="853" alt="screen shot 2017-03-20 at 3 06 11 pm" src="https://cloud.githubusercontent.com/assets/626032/24117061/17da4dbe-0d7f-11e7-9f01-29ab0ac3783e.png">

**Comment by wknet123** [comment]
We need to make them in consistent with discussion.

**Comment by akshayl** [comment]
Let's go with Members. This way we clearly distinguish between management of users (Administration -> Users) and managing project membership and roles (Projects -> [Project] -> Membership)
