### ISSUE TITLE
An unauthenticated user should not be able to delete an image.

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1692]
If the user is not logged in and viewing a popular image, there should be no action menu to delete the image. 

<img width="1205" alt="screen shot 2017-03-20 at 3 14 59 pm" src="https://cloud.githubusercontent.com/assets/626032/24117311/233b6e08-0d80-11e7-9186-292d69f1c2a6.png">

Also, the "back" button should not say Repositories but should say "Popular Images"

**Comment by steven-zou** [comment]
This might be a general problem because of the upgrading of Clarity. We'll fix it.

@wknet123 

  Please take a loot at this issue.

**Comment by steven-zou** [comment]
@wknet123 

Add same permission control like other components such as 'projects','repositories' etc.

(listMode)

**Comment by wknet123** [comment]
Fixed

**Comment by lweitzman** [comment]
Does copy ID and copy parent ID make sense for the unauthenticated user @akshayl @steven-zou

**Comment by steven-zou** [comment]
@lweitzman 
The two ID are just read-only information. Checked with @wknet123, in the old version, these two IDs are exposed to unauthenticated users.
