### ISSUE TITLE
Bug: when unauthenticated user does a search then the user can get into a state where they can't do anything.

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1693]
as an unauthenticated user i did the following:
search - go back to login - search term still in header - and popular repos are showing up - login ok - logout - now no popular repos are shown - search term still in header - now when i log in i get the projects page with no left nav and no user ID in header and i can't do anything.

the search field should be cleared when returning to the login page.

**Comment by lweitzman** [comment]
this is a dupe of #1697 but has a better description of how to replicate the error condition

**Comment by steven-zou** [comment]
this issue might caused by a Clarity bug of datagrid.

**Comment by steven-zou** [comment]
Fixed from harbor side but still blocked by Clarity bug.

**Comment by steven-zou** [comment]
Blocked by Clarity issue https://github.com/vmware/clarity/issues/625 and they're trying to figure out the cause and fix.

**Comment by steven-zou** [comment]
Find root cause(*ngIf problem): Create separate project/repo list datagrid to avoid this problem.

**Comment by steven-zou** [comment]
Fixed
