### ISSUE TITLE
[UI] Where to view the popular projects after sign in?

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#1695]
I can see the popular projects as a anonymous. But, after I logged in, where to view it?

**Comment by steven-zou** [comment]
It works as design.

@lweitzman 

  Can you help to confirm this issue?

**Comment by lweitzman** [comment]
@akshayl decided that we don't have a dashboard and don't show the popular repos in this release. popular repos were on the dashboard and in a future release the dashboard (and popular repos) might return

**Comment by steven-zou** [comment]
As it is 'work as design', I'll close this issue.
