### ISSUE TITLE
project menu layout issue

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#1696]
text is out of text box
![capture1](https://cloud.githubusercontent.com/assets/23101283/24129927/baad94d2-0e20-11e7-9562-139f1e7dc6b5.PNG)

Firefox esr 45.8.0

**Comment by steven-zou** [comment]
@wknet123 

  Please take a look at this issue and confirm whether or not is caused by Clarity itself.

**Comment by sigsbee** [comment]
no such issue in latest firefox(52).
