### ISSUE TITLE
startuptest.go can be replaced by curl or python.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#1701]
Based on log of travis-ci:
https://travis-ci.org/vmware/harbor#L1314
It took 1 minute to finish it, if we use curl is should be less than 1 second.

Same to userlogintest.go

**Comment by wy65701436** [comment]
it's not because of the go script, there is an 60 seconds sleep in the startuptest. Not sure the exactly reason.

**Comment by reasonerjt** [comment]
yep, sorry.
