### ISSUE TITLE
when session expires, ui should go to login screen with message explaining why

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1707]
when the session times out you get this cryptic message:
"JSON parse error..." instead the system should know a session is invalid/timed out and return to the login page with a message saying that "Your session has timed out. Please login again to continue.

<img width="1385" alt="should logout instead of getting this alert" src="https://cloud.githubusercontent.com/assets/626032/24156469/fb9bf770-0e2c-11e7-88c2-a1d1748d0f83.png">
"

**Comment by steven-zou** [comment]
@lweitzman 

  Actually we have special handlers for the 401 and 403 errors. If the error is 401/403, the handling process will be totally same as what you described. 

  The error shown in this issue might be a general error (not 401/403) and then display general message.
  As an enhancement, added a general message as prefix of the error message returned from backend api call to avoid confusion.

**Comment by steven-zou** [comment]
"GENERAL_ERROR": "Errors have occurred when performing service call: {{param}}"

**Comment by lweitzman** [comment]
instead of saying "... performing service call: ..." could you say "... performing action: ..."

**Comment by lweitzman** [comment]
there are still some issues with this. i got this message below the header. but i was still able to click around the ui. the first click put up a second error message lower on the page.

![screen shot 2017-03-24 at 11 51 06 am](https://cloud.githubusercontent.com/assets/626032/24302214/4647e272-1088-11e7-81d5-d4d0ad2ba00f.png)

**Comment by lweitzman** [comment]
clicking on the Login button in the warning. i got this.
![screen shot 2017-03-24 at 11 53 57 am](https://cloud.githubusercontent.com/assets/626032/24302335/a6b1c042-1088-11e7-937c-a9aa43edc84c.png)

**Comment by lweitzman** [comment]
after all the above, i was no longer able to log into the system.

**Comment by steven-zou** [comment]
Please refer #1694 for enhancing error handling functions.

**Comment by lweitzman** [comment]
when i get bumped off of vpn, i can click around but don't get any data and don't get any errors

**Comment by steven-zou** [comment]
@lweitzman 

  Actually it will show errors if there are network errors occurred. The reason why you did not see the errors is that not reach the timeout of xhr calling and no response returned yet.

  I have tested that, error handler works well. See the following snapshot:
 
<img width="1440" alt="2017-04-01 10 33 44" src="https://cloud.githubusercontent.com/assets/5753287/24579627/7cf6bb28-172b-11e7-8847-55387f1f0f45.png">

**Comment by steven-zou** [comment]
@lweitzman 

  So change status to 'done' and labeled with 'waiting-for-verify'.
