### ISSUE TITLE
Show log component change

### ISSUE THREAD

**Issue by tonycgil** [vmware/harbor#1708]
Show log should be on right side with divider. Use Clarity Select Boxes component for drop down.

Original screenshot:
<img width="250" alt="screen shot 2017-03-21 at 8 59 32 am" src="https://cloud.githubusercontent.com/assets/25991813/24157041/84387a9e-0e15-11e7-9d62-0061593102d7.png">

Fix:
![harbor-show-logs-final](https://cloud.githubusercontent.com/assets/25991813/24157069/9280a16c-0e15-11e7-8813-75c934945a9a.png)

**Comment by steven-zou** [comment]
@tonycgil 

Refactor the log action panel as what you mentioned. Will deploy new code in next env update turn.

**Comment by lweitzman** [comment]
Dont think we need to say "recent" in the drop down. It makes the dropdown too verbose.

**Comment by steven-zou** [comment]
Sure. Removed "recent".
