### ISSUE TITLE
Adding storage metic 

### ISSUE THREAD

**Issue by tonycgil** [vmware/harbor#1709]
Adding storage metric for projects

Design:
![harbor-storage-metric-final-nospec](https://cloud.githubusercontent.com/assets/25991813/24170856/7a993da0-0e3f-11e7-8771-25b12cae8a17.png)

Spec:
![harbor-storage-metric-final](https://cloud.githubusercontent.com/assets/25991813/24170871/8901961c-0e3f-11e7-8a83-86c533ed20b2.png)

**Comment by reasonerjt** [comment]
I think we need to consider when the API doesn't return the usage data or it returns an error, should UI just hide this widget?

**Comment by lweitzman** [comment]
yes, if no data is available, remove the storage metric and shift the other metrics to be right justified against the margin

**Comment by lweitzman** [comment]
i know this is in progress but a couple notes:
font is incorrect on the numbered metrics for projects and repos
if no storage info, don't display it.
![screen shot 2017-03-24 at 10 42 58 am](https://cloud.githubusercontent.com/assets/626032/24299347/538bd992-107f-11e7-95df-af1e0ecec959.png)

**Comment by steven-zou** [comment]
@lweitzman 

Right, the 'Storage' text is just a placeholder. It is still undergoing and depending on the photon team.

**Comment by steven-zou** [comment]
Is 'font-family' incorrect? @lweitzman Could you please help to clarify the font-family with standard formal name?

**Comment by lweitzman** [comment]
see the mockup @tonycgil provided. that has the font spec i.e., my, public, total and storage are all the same uppercase font. font family is metropolis the standard clarity font.

**Comment by steven-zou** [comment]
Supported now!

**Comment by tonycgil** [comment]
Looking at the latest build, correct font is not coming though. Also, can we align text and shrink the gage a bit in size?

![storage-gage](https://cloud.githubusercontent.com/assets/25991813/24616667/a2d94114-1846-11e7-8f4f-d20311f0957c.png)
