### ISSUE TITLE
some words inconsistent

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#1715]
some words inconsistent. some time it's policy and some time rule
![endpointtext](https://cloud.githubusercontent.com/assets/23101283/24192345/903c4b08-0f29-11e7-97d5-cd006b8fdf2c.PNG)

**Comment by lweitzman** [comment]
this is a dupe of #1688

**Comment by reasonerjt** [comment]
Thanks @lweitzman , closing.
