### ISSUE TITLE
pull image without login

### ISSUE THREAD

**Issue by frank798** [vmware/harbor#172]
Should I must be login before pull image? When I try  pull image without login,I get the message:"Error: image xxx not found". But after login,pull image is ok.
my env is 
       harbor:
            docker verson 1.11.0 
            compose version is 1.6.2 
       client:
            docker version 1.9.1
Is anyone find the same the problem?

**Comment by ywk253100** [comment]
@frank798 Only the public projects can be pulled without login.

**Comment by frank798** [comment]
@ywk253100 Yes this is it! thanks for your replay
