### ISSUE TITLE
About box text fixes

### ISSUE THREAD

**Issue by tonycgil** [vmware/harbor#1724]
Current About box carries wrong font
![aboutbox-spec-fix](https://cloud.githubusercontent.com/assets/25991813/24218849/1059c0fe-0f02-11e7-8f56-cf856d881377.png)

**Comment by steven-zou** [comment]
@tonycgil 

  The font style adopted in about dialog strictly follow the design provided by @lweitzman 

  Please refer https://vmware.invisionapp.com/share/BFA95DAMR#/screens/219216366

**Comment by lweitzman** [comment]
@tonycgil has the final say about styling.

**Comment by tonycgil** [comment]
@steven-zou I did not see this. Thanks. Yes, follow @lweitzman design. I like the side graphic. My main concern on the existing was the font, but @lweitzman has captured that.

**Comment by steven-zou** [comment]
@tonycgil 

  If needed, I can change the font.

  About the side graphic, as we use the Clarity modal, there are limitations to let us add background graph to the side. So, in the release, we'll leave it as it is now.

**Comment by steven-zou** [comment]
Changed to h2 and .p5.

Keep the font size and weight for the version and build labels.

**Comment by tonycgil** [comment]
Thanks!
