### ISSUE TITLE
Harbor (docker-compose) fails installation on VIC

### ISSUE THREAD

**Issue by lcastellano** [vmware/harbor#1725]
When selecting a VIC/VCH target the docker-compose installation of Harbor fails because VIC does not yet implement Load Image. If possible Harbor install should avoid using Load Image.

**Comment by wy65701436** [comment]
@lcastellano could you show me the error? And please also help to tell how do you run the offline installer.

Harbor packages all the fundamental docker images into one tgz file, then load it at the installation phase.

**Comment by reasonerjt** [comment]
@lcastellano this is a known limitation, could you try to online install package?
