### ISSUE TITLE
Double current user checking in unauthenticated pages.

### ISSUE THREAD

**Issue by wknet123** [vmware/harbor#1735]
Should perform one request to check current user status.
![image](https://cloud.githubusercontent.com/assets/5027302/24239252/3528126e-0fe8-11e7-92dc-27feeaf56e4b.png)

**Comment by steven-zou** [comment]
We setup more than one activates which are based on current user checking and we have no way to control the executing order, so sometimes may perform two requests. 

I don't think this is a issue.

Only one time, not calling two requests each time.
