### ISSUE TITLE
Failed to send email for resetting password.

### ISSUE THREAD

**Issue by wknet123** [vmware/harbor#1736]
Due to missing `reset-password-mail.tpl` file under `views` path.
![image](https://cloud.githubusercontent.com/assets/5027302/24239464/09a7f388-0fe9-11e7-9f6b-eb118b983f82.png)

**Comment by wy65701436** [comment]
This file is copied into Harbor UI image at the building images phase, @wknet123 please check.

**Comment by reasonerjt** [comment]
dupped with #1834
