### ISSUE TITLE
[UI] please hide the title of UI component.

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#1737]
![image](https://cloud.githubusercontent.com/assets/2841473/24239598/85729446-0fe9-11e7-8fd1-442be888bf80.png)

**Comment by steven-zou** [comment]
@wknet123 

  Please investigate and fix.

**Comment by lweitzman** [comment]
here is another example
![screen shot 2017-03-24 at 10 41 23 am](https://cloud.githubusercontent.com/assets/626032/24299418/87440480-107f-11e7-95a7-6a5e1afffd40.png)

**Comment by wknet123** [comment]
This only can be seen under Firefox.

**Comment by lweitzman** [comment]
this also shows up in safari

**Comment by steven-zou** [comment]
Raise issue to Clarity team.

https://github.com/vmware/clarity/issues/734

**Comment by steven-zou** [comment]
Clarity has fixed the issue. Checked, no tooltip appear again. Close this issue.

**Comment by lweitzman** [comment]
i still see it in safari @10.112.122.230
![screen shot 2017-05-16 at 11 35 37 am](https://cloud.githubusercontent.com/assets/626032/26114687/f1cb2ca4-3a2b-11e7-88da-2d8a7278ad70.png)

**Comment by steven-zou** [comment]
It was fixed and close it.
