### ISSUE TITLE
install sometimes will meet notary error

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#1738]
install with notary, sometimes will meet notary db cannot start
![installnotary](https://cloud.githubusercontent.com/assets/23101283/24239803/4b5eebd2-0fea-11e7-9130-38059685c279.PNG)

**Comment by reasonerjt** [comment]
Will add dependency of notary-db on log service.

**Comment by frapposelli** [comment]
This impacts the OVA work as well, related issue vmware/vic#4354

**Comment by reasonerjt** [comment]
A fix is included in #1775
