### ISSUE TITLE
The search box should be cleared after user sign-in and sign-out

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#1739]
It should be cleared when user's switched to another pane, at least when log out.

<img width="1196" alt="screen shot 2017-03-23 at 5 02 50 pm" src="https://cloud.githubusercontent.com/assets/2390463/24239975/eaca73b2-0fea-11e7-95ce-2071ad75db63.png">

**Comment by steven-zou** [comment]
Will only support clear after logout. in other situations, the shell is not changed, all the pane switching is internal action. Shell is not changed.

**Comment by steven-zou** [comment]
Will clear the search term when the search result page closing

**Comment by steven-zou** [comment]
fixed.

**Comment by reasonerjt** [comment]
verified, thanks.
