### ISSUE TITLE
The search box should be cleared after create project.

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#1740]
User may want to see the newly created project, but the filter is not clear.
![image](https://cloud.githubusercontent.com/assets/2841473/24240166/9f8af09c-0feb-11e7-9e72-618a5ae51aa5.png)

**Comment by lweitzman** [comment]
agree that the filter should be cleared when adding a project or any new object

**Comment by wy65701436** [comment]
close it as fixed.
