### ISSUE TITLE
Clicking the link "Repositories" will be redirected to sign in page if user's not signed in

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#1742]
1, Before signing in, click a link in popular repo table.
2, Click the link Repositories, it takes me back to the sign in page, not repositories.
<img width="1122" alt="screen shot 2017-03-23 at 5 11 11 pm" src="https://cloud.githubusercontent.com/assets/2390463/24240693/8628d3ec-0fed-11e7-86ca-9036c3d72734.png">

**Comment by lweitzman** [comment]
the link should just say "<  Back" when unauthenticated to go back to the login page with popular repos.

**Comment by wknet123** [comment]
Fixed with #1791

**Comment by reasonerjt** [comment]
Verified.
