### ISSUE TITLE
[UI] Is it possible to remove the project description in UI?

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#1743]
Nowhere to edit the description but it still show in the UI.

**Comment by lweitzman** [comment]
i don't believe that editing a project is in this release. @akshayl would know. if it is, we need an edit action on a project row and a new dialog. what properties of a project can be changed?

**Comment by reasonerjt** [comment]
I think the point of OP is even when creating the project there's no way to set the description.  I think we should remove this column for this release.

**Comment by lweitzman** [comment]
agree

**Comment by steven-zou** [comment]
@wknet123 

  Please take a look at this issue.

**Comment by wknet123** [comment]
Already removed.

**Comment by wy65701436** [comment]
close it as fixed.
