### ISSUE TITLE
The "Remember me" doesn't seem to work.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#1744]
Seems there's no effect whether or not I check the "Remember me" when logging in.
<img width="485" alt="screen shot 2017-03-23 at 5 28 07 pm" src="https://cloud.githubusercontent.com/assets/2390463/24241051/8e33378e-0fee-11e7-84cf-bf464d3d0b7a.png">

**Comment by steven-zou** [comment]
To securely support this function , might need a backend api support.

**Comment by steven-zou** [comment]
@lweitzman 

  About the 'remember me', just remember the username or remember the sigin session?

**Comment by steven-zou** [comment]
@lweitzman 

  Can you give me the answer?

**Comment by lweitzman** [comment]
just remember the username

**Comment by steven-zou** [comment]
Support now.

**Comment by reasonerjt** [comment]
Verified it remembers the username.
