### ISSUE TITLE
FYI: Atomic Registry

### ISSUE THREAD

**Issue by xiaods** [vmware/harbor#175]
Atomic Registry
An enterprise container registry solution run on-premise or in the cloud

http://www.projectatomic.io/registry/

please review and enhance

**Comment by senk** [comment]
Atomic Registry is tightly coupled to Atomic Host
Also take a look at https://github.com/SUSE/Portus

**Comment by bobbyjunzhang** [comment]
Thank you for the information. We are doing a comparative study on related projects/products (including those commercial ones) and see how we can learn from them to further enhance Harbor. Harbor is currently positioned as a flexible and independent project that can be easily integrated in different scenarios.

**Comment by hainingzhang** [comment]
thanks for the info. close this for now.
