### ISSUE TITLE
Clicking public project from UI has no response.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#1751]
On developer tool it shows the UI tries to list the members of the project and get 403.

In 0.5.0 user can see the repositories of a public project.

**Comment by reasonerjt** [comment]
<img width="1130" alt="screen shot 2017-03-23 at 6 05 36 pm" src="https://cloud.githubusercontent.com/assets/2390463/24242702/87e34644-0ff3-11e7-8144-744e7880e866.png">

**Comment by lweitzman** [comment]
not sure why i'm on this bug?

**Comment by reasonerjt** [comment]
I believe this is related to workflow? @lweitzman  what should a user see if he clicks the link of a public project?

**Comment by reasonerjt** [comment]
Verified, thanks.
