### ISSUE TITLE
Performance issue on loading projects

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#1753]
it takes about 480ms to load 15 projects.

**Comment by ywk253100** [comment]
The listing projects API lists n(defined by page size param in the query string) projects first, and then it iterates every project and populates user role and repository count. We don't want to dependent the underlying database very much so we don't use a join SQL to implement it. 
And I tested the API in a Harbor instance where contained 1000+ projects, the time was always about 400ms, so I think it's OK.
What's your opinion @reasonerjt ?

**Comment by reasonerjt** [comment]
Let's keep it as is.
