### ISSUE TITLE
hit of delete notary tag should more accurate

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#1754]
when delete a signed image, the hint of delete notary tag should more accurate
![notarytag](https://cloud.githubusercontent.com/assets/23101283/24242522/eeb02082-0ff2-11e7-8506-10c58a50f8db.PNG)

**Comment by reasonerjt** [comment]
@wknet123 
The command should be put in a newline and the content should be:

'notary -s https://' + this.registryUrl + ':4443 -d ~/.docker/trust remove -p ' + this.registryUrl + '/' + this.repoName + ' ' + tag.tag

**Comment by sigsbee** [comment]
verified
