### ISSUE TITLE
Deleting a non-empty project doesn't show meaningful Error.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#1758]
1)When I remove a project that has a repository, API returns 412, UI should not show this 412 on message bar, instead, it should show meaningful message, please reference 0.5.0

2)After I dismiss the message and try to delete again, the deletion will fail but no error message.

for 2) Seems the component "inline error" has some issue

**Comment by steven-zou** [comment]
@wknet123 

  please take a look.
 
@reasonerjt 
  For the meaningful error message, why backend api only return response code and no meaningful error message returned? In many cases， UI does not know what the error real is?  This is a general situation now which already cause many issue.

**Comment by reasonerjt** [comment]
@wknet123 why not render a more meaningful error as we did in 0.5.0?  To specify the criteria for project deletion.

**Comment by reasonerjt** [comment]
Verified, thanks.
