### ISSUE TITLE
when delete trust data of a repo, signed image still remain signed

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#1759]
1. push a image with content trust, it will show in UI signed
2. use notary delete command to delete trust data
![notarydelte1](https://cloud.githubusercontent.com/assets/23101283/24243458/2cb70230-0ff6-11e7-9a39-58009fc01375.PNG)

3. the signed image still remain signed
![notarydelete2](https://cloud.githubusercontent.com/assets/23101283/24243469/3616757c-0ff6-11e7-981d-426fad1c26cb.PNG)

**Comment by reasonerjt** [comment]
Thanks for the finding @sigsbee,

see this log:
Mar 25 10:28:12 172.18.0.1 ui[17018]: 2017-03-25T02:28:12Z [DEBUG] [transport.go:51]: 404 | GET http://notary-server:4443/v2/10.117.4.167/abcde/abc/_trust/tuf/timestamp.json
Mar 25 10:28:12 172.18.0.1 ui[17018]: time="2017-03-25T02:28:12Z" level=warning msg="Error while downloading remote metadata, using cached timestamp - this might not be the latest version available remotely"

Notary by default use the cached metadata it fails to download the new one, which happens in this case as it is completely removed and returns 404.
I'll check the code to see if it's possible to workaround.

**Comment by reasonerjt** [comment]
Fixed in #1793 

Delete root.json after getting all the metadata, such that it won't return the old data if hit a 404 error.
