### ISSUE TITLE
Need reload systeminfo when login

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#1760]
System admin changes the project creation property to "adminonly" in one browser while a normal user has signed in in another browser. When the normal user logouts and logins again, he can still create projects.

**Comment by steven-zou** [comment]
As we change the signin design, we'll load the system info when sign-in being opened instead of @app bootstrap.

**Comment by steven-zou** [comment]
Reload configurations when initialize sign-in page as well.

**Comment by ywk253100** [comment]
Verified.
