### ISSUE TITLE
[UI] Get "Invalid json request" when to ping email server with invalid input.

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#1761]
Can you give readable error message?

![image](https://cloud.githubusercontent.com/assets/2841473/24243651/cc4fd70e-0ff6-11e7-811e-19e8d054212a.png)

**Comment by lweitzman** [comment]
would "Verification of email server failed" work? Not sure of the full context.

**Comment by steven-zou** [comment]
General error message handling problem. Will refactor the error handling mechanism.

**Comment by steven-zou** [comment]
Please refer #1694

**Comment by wy65701436** [comment]
close it per https://github.com/vmware/harbor/issues/1694.
