### ISSUE TITLE
[UI] User get unclear message when to delete himself, "LON IN" should be removed.

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#1766]
The message is not clear, and the login button in the error message could be removed.

![image](https://cloud.githubusercontent.com/assets/2841473/24244198/e12b3694-0ff8-11e7-975d-204890be538e.png)

**Comment by steven-zou** [comment]
For the unclear message, it is a general message for 403 case. Currently as api return none meaningful error message, we can not handle accurate error message at front end.

Will downgrade 403 to use normal error alert.

**Comment by reasonerjt** [comment]
"Log in" should never fix a 403

**Comment by steven-zou** [comment]
Please refer #1694

**Comment by steven-zou** [comment]
Use this issue to track the bug of deleting current user itself. Should NOT!
For message things, as mentioned before, please refer #1694.

**Comment by wy65701436** [comment]
close it as fixed.
