### ISSUE TITLE
Filter does not work as expected

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#1767]
The filter in recent logs and Administrator-Users does not work as expected. The following steps can reproduce the issue:
1. Fill in the keyword in filter, press enter, it works.
2. Click the refresh button behind the filter.
3. Press enter again to filter items, it does not work.

**Comment by steven-zou** [comment]
Actually is was as designed. We distinguish the same term to avoid duplicated querying.
It is easy to cause confusion, we'll remove the 'distinguish' function.

**Comment by steven-zou** [comment]
@wknet123 

  Please pay attention to other same situations, remove the "distinguish" function if existing to avoid confusion.

**Comment by steven-zou** [comment]
Remove 'distinctUntilChanged' to let filer duplicated term.

**Comment by ywk253100** [comment]
Verified.
