### ISSUE TITLE
when add an endpoint,remote return 404

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#1768]
when add an endpoint,remote return 404
![reppingremote](https://cloud.githubusercontent.com/assets/23101283/24244563/7016392a-0ffa-11e7-9f92-3e9a6acd994e.PNG)

**Comment by lweitzman** [comment]
that is not the standard error display in a modal dialog.

**Comment by reasonerjt** [comment]
@lweitzman thanks for pointing out.

@wknet123  could you open another issue to track the error display problem?

**Comment by sigsbee** [comment]
it's because the endpoint has some problem, change an endpoint will be OK
