### ISSUE TITLE
automate the process to build notary images.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#1774]
It should involve clone the code from github, build binary, grab latest migration sql, build the image to copy these files into photon image.

Note if the structure of Notary's code is changed the process needs to be tweaked to match the change.

**Comment by reasonerjt** [comment]
This is a prereq of #3173 so priority is high, and it may be move to earlier target, such as "vic-1.2.1"

**Comment by wy65701436** [comment]
Close it as done.
