### ISSUE TITLE
Sometimes meet error when starting Harbor with Notary

### ISSUE THREAD

**Issue by wknet123** [vmware/harbor#1777]
`ERROR: for notary-db  Cannot start service notary-db: Failed to initialize logging driver: dial tcp 127.0.0.1:1514: getsockopt: connection refused
ERROR: Encountered errors while bringing up the project.`
By using command `docker-compose -f docker-compose.yml -f docker-compose.notary.yml up -d`, meet error sometimes, but it would be fine after retrying times.

**Comment by reasonerjt** [comment]
should be a dup to #1738
