### ISSUE TITLE
Can't download CA cert from Web UI when using self-signed cert

### ISSUE THREAD

**Issue by frapposelli** [vmware/harbor#1794]
Using the web ui on the latest build I can't access the ca.crt download from the about page:

<img width="603" alt="screenshot 2017-03-24 13 26 57" src="https://cloud.githubusercontent.com/assets/541832/24294143/8a475e28-1095-11e7-9c22-33aadc4bdeca.png">

**Comment by wy65701436** [comment]
It's a known issue.

**Comment by steven-zou** [comment]
right,not added yet. Will provide it later.

@lweitzman 

  Just confirm with you, for the cert downloading, we provide a separate menu named 'Download cert' under the account icon, right?

**Comment by lweitzman** [comment]
Yes, add it to the menu under the account icon.

**Comment by steven-zou** [comment]
Support.
