### ISSUE TITLE
Tag with role next to project name

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1796]
The UI is now showing the role of the user when looking at a project. Is this a new requirement because a person might have different roles on different projects? and why is it purple :-)

![screen shot 2017-03-24 at 11 04 16 am](https://cloud.githubusercontent.com/assets/626032/24300196/06963b3e-1082-11e7-8bc9-bf75d90fc54a.png)

**Comment by wknet123** [comment]
Per this issue #1598 mentioned about.

**Comment by wknet123** [comment]
A project can be assigned to an ordinary user with one specific role. System admin is a special role to all projects in Harbor.

**Comment by lweitzman** [comment]
Where did this requirement come from?

**Comment by steven-zou** [comment]
by @akshayl. akshay, can you confirm this requirement? Is it still valid?

**Comment by lweitzman** [comment]
according to akshay's email this is valid but needs some redesign. @tonycgil and i will work on this.

**Comment by lweitzman** [comment]
tony will provide a visual for this

**Comment by tonycgil** [comment]
Here's the spec
![user-title-italic-spec](https://cloud.githubusercontent.com/assets/25991813/24459184/c87fbad8-144f-11e7-9f74-03af8394dd93.png)
