### ISSUE TITLE
Message to "Confirm to cancel" needs updating

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1797]
The text: 
"Some changes are not saved yet, do you really want to discard?"
should read:
"Some changes have not been saved. Do you want to discard them?"

![screen shot 2017-03-24 at 11 43 55 am](https://cloud.githubusercontent.com/assets/626032/24301910/2f858888-1087-11e7-9121-4a8584c098b5.png)

**Comment by steven-zou** [comment]
Fixed:
 "CONFIRM_SUMMARY": "Some changes have not been saved. Do you want to discard them?"

  "CANCEL" => "NEGATIVE"

**Comment by lweitzman** [comment]
I'm not seeing that message. it should be 2 sentences.  "Some changes have not been saved. Do you want to discard them?" also, when navigating away from configuration edits, cancel button shouldn't be "Negative" Should use "Continue" or something like that. 
<img width="591" alt="screen shot 2017-03-29 at 9 30 18 am" src="https://cloud.githubusercontent.com/assets/626032/24457200/86522c0e-1463-11e7-806c-d49a3acb5ab1.png">

**Comment by steven-zou** [comment]
@lweitzman 

 This confirmation dialog is a general dialog for confirming to deletion or confirming to leave, so 'continue' is not suitable for deletion case.

  I suggest to change these two buttons to the simple general one, "NO","YES".

**Comment by lweitzman** [comment]
thanks that works well.

**Comment by lweitzman** [comment]
The text should be 2 sentences with a period and sentence capitalization. (not a comma)
