### ISSUE TITLE
Logs has a lozenge with the number of logs by the title

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1798]
Please remove the number by the title.

![screen shot 2017-03-24 at 1 55 19 pm](https://cloud.githubusercontent.com/assets/626032/24307219/a72d186c-1099-11e7-80d9-1010de9627ab.png)

**Comment by steven-zou** [comment]
@lweitzman 

Sure.

**Comment by steven-zou** [comment]
Removed!

**Comment by lweitzman** [comment]
looks like repos now have a number by them. this number is in the datagrid so it doesnt need to be by the title
<img width="594" alt="screen shot 2017-03-29 at 9 26 53 am" src="https://cloud.githubusercontent.com/assets/626032/24456749/0338a060-1462-11e7-8251-d5e7310bb522.png">

**Comment by steven-zou** [comment]
@wknet123 

Please remove the number label.
