### ISSUE TITLE
Minor issues of project and replication

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#1801]
- Font of Enable checkbox when creating a new replication rule is smaller than the others
- Projects: the dropdown should say "All Projects" and "Public Projects" instead of "My Projects" and "Public Projects"
|- When making a project public, we should have a confirmation dialog|

**Comment by lweitzman** [comment]
i don't think we need a confirmation dialog. if the user doesn't want to make it public, its easy to revert by making it private. what is needed is a way to make the modification more visible in the UI. not sure how we do that though. and for this release, it may not be important. @akshayl @tonycgil
