### ISSUE TITLE
Margins of content area are inconsistent among different pages

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#1802]
- Users and Configuration page are are about 20 pixels to the right of the other pages by @akshayl 

@lweitzman @tonycgil 

Please help too confirm all the three margins what we need. Please be aware that the clarity has set default 24px paddings for all four directions.
<img width="1225" alt="2017-03-25 11 21 42" src="https://cloud.githubusercontent.com/assets/5753287/24323567/909277b8-11b2-11e7-97f8-0c9a8eb31596.png">

**Comment by tonycgil** [comment]
Hi @steven-zou Here's the spacing for gutters.
![gutter-spacing](https://cloud.githubusercontent.com/assets/25991813/24376751/dcfdcd2e-12f1-11e7-813f-5cca2e8fd065.png)

**Comment by steven-zou** [comment]
@wknet123 

Use a separate div with padding 12px
