### ISSUE TITLE
Data too long for colums RealName

### ISSUE THREAD

**Issue by 252221110802** [vmware/harbor#1805]
Using the latest release available (0.5.0) I am setting up my ldap_auth to use userPrincipalName as this is the binding argument we would like to use (similar to the email one)

I can log with most of my users, but with mine since its a long name (the email is like guillaume.trottier@xxxx.com. When I try to authenticate I have the following message in ui.log:

Mar 26 22:04:51 172.18.0.1 ui[811]: 2017-03-26T22:04:51Z [ERROR] [base.go:186]: Error occurred in UserLogin: Error 1406: Data too long for column 'realname' at row 1

If I use the sAMAccountName since it's shorther it does work. Is this something that I can change in mysql to allow for longer name?

THanks!

**Comment by chrisfelix82** [comment]
Same here.  Hoping for a fix or workaround.  Thanks.

**Comment by reasonerjt** [comment]
@252221110802 thanks for raising the issue, yes there is an easy workaround, see the link by @chrisfelix82, you can update the sql to extend the length of the column in DB.

**Comment by chrisfelix82** [comment]
Yes this worked:

```
docker exec -it harbor-db bash
mysql --host=localhost --user=root --password=root123 registry
ALTER TABLE user MODIFY realname VARCHAR(250);
```

**Comment by 252221110802** [comment]
Wonderfull this works great! Do you know if this is something that will be updated in another release?

Thanks a lot @chrisfelix82 I still have a lot to learn with docker! 👍 I was trying to connect to mysql directly from the vm instead of docker-db!!

**Comment by nehaljwani** [comment]
For those who forgot the mysql root user password (like me), can do:
```bash
sudo docker inspect harbor-db | \
   jq '.[].Config.Env | map(split("=") | { (.[0]) : .[1] }) | add | .MYSQL_ROOT_PASSWORD'
```

**Comment by reasonerjt** [comment]
Closing as the column has been increased to 255.
