### ISSUE TITLE
The confirmation dialog should support new line

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#1809]
For #1754, I'd like to display the notary command in a new line, current the dialog does not support rendering newline nor rendiring HTML .

**Comment by steven-zou** [comment]
Support at least '\n' for newline now.

**Comment by reasonerjt** [comment]
Will verify this after Kun updates the error message for removing a signed image.

**Comment by steven-zou** [comment]
@reasonerjt 

Verify now?
