### ISSUE TITLE
Clear these intermediate files generated in make process

### ISSUE THREAD

**Issue by wknet123** [vmware/harbor#1822]
`make/.srl`
`make/cert_tmp/`
These files below should package into Harbor UI image.
`src/ui/static/i18n/lang/en-lang.json`
`src/ui/static/i18n/lang/zh-lang.json`

**Comment by reasonerjt** [comment]
I'll clear the generated files by prepare script.

**Comment by reasonerjt** [comment]
#1851 covered my part.

**Comment by wy65701436** [comment]
close it as PR https://github.com/vmware/harbor/pull/2017
