### ISSUE TITLE
Compatible issue under Safari browser with new UI

### ISSUE THREAD

**Issue by wknet123** [vmware/harbor#1823]
With Safari browser [Version 10.0.3 (12602.4.8)], there cause an endless loop requesting at sign-in page.

**Comment by wknet123** [comment]
Only occur at IP with a port number pattern.

**Comment by steven-zou** [comment]
@wknet123 

The root cause might be the invalid server certs.

Check with the deployed env, everything works well. So it is local env problem, not code function.
