### ISSUE TITLE
Can not display properly in Safari

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#1832]
![picture1](https://cloud.githubusercontent.com/assets/5835782/24397977/6dd5ca70-13da-11e7-9026-039e94eaff9e.png)

**Comment by steven-zou** [comment]
There is an error in Safari:
<img width="835" alt="2017-03-29 12 12 24" src="https://cloud.githubusercontent.com/assets/5753287/24415574/77d641a0-1414-11e7-8982-8626c85aa84b.png">

@wknet123 

Please take a look!

**Comment by steven-zou** [comment]
Seems related with date formate function.

**Comment by wknet123** [comment]
Fixed with latest updates.

**Comment by ywk253100** [comment]
Errors still exist in v9.0.2.

**Comment by steven-zou** [comment]
Bug fixed. Merge code in #2339
