### ISSUE TITLE
Confused error message when deleting a signed tag

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#1836]
Users should not be allowed to delete a signed tag on UI. 
Besides, the error message "We are unable to perform your action because your submission has conflicts" for response code 412 is not correct.

**Comment by ywk253100** [comment]
<img width="577" alt="63be6735-f1e2-4d9c-9b24-bef989334c07" src="https://cloud.githubusercontent.com/assets/5835782/24498127/3459e654-1570-11e7-8f29-20f864571838.png">

There should be an information dialog. Or we can use a warning message to show the information.

**Comment by reasonerjt** [comment]
<img width="751" alt="screen shot 2017-04-05 at 5 49 05 pm" src="https://cloud.githubusercontent.com/assets/2390463/24700063/9dcdbc3e-1a28-11e7-875a-ebceef920cfe.png">

**Comment by reasonerjt** [comment]
There are two issues:
1) the only button should be "OK" instead of yes
2) the notary command should be like: notary -s **https://10.117.5.104:4443** -d ~/.docker/trust remove -p 10.117.5.104/mytest/golang 1.7.3

**Comment by ywk253100** [comment]
Please verify @reasonerjt .
