### ISSUE TITLE
log filter does not filter tags

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#1840]
log filter does not filter tags
![log1](https://cloud.githubusercontent.com/assets/23101283/24399804/8fca7f58-13e0-11e7-84f8-acb0e74bde0c.PNG)
![log2](https://cloud.githubusercontent.com/assets/23101283/24399807/90af06fa-13e0-11e7-977c-3e9b0aab18c7.PNG)

**Comment by steven-zou** [comment]
Support filter by repo tags
