### ISSUE TITLE
Adding a new user should be titled "New User"

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1862]
"New" is used for creating new objects. "Add" is for adding a relationship between 2 existing objects.
<img width="588" alt="screen shot 2017-03-29 at 9 51 26 am" src="https://cloud.githubusercontent.com/assets/626032/24457897/79b46320-1465-11e7-98cd-9a5f216288ad.png">

**Comment by steven-zou** [comment]
Changed to 'New User'
