### ISSUE TITLE
Change "i" to default grey

### ISSUE THREAD

**Issue by tonycgil** [vmware/harbor#1863]
The default color of the "i" should be grey. Blue is only for clickable items. Here's the mockup
![i-information](https://cloud.githubusercontent.com/assets/25991813/24471085/dd2feb8a-1475-11e7-9cc6-cc5f589b4726.png)

**Comment by steven-zou** [comment]
Changed to grey @tonycgil

**Comment by tonycgil** [comment]
Thanks!
