### ISSUE TITLE
Language switcher should be hide when Harbor is in integration mode

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#1865]
One more thing, the title in login page should be changed to 'VIC'

**Comment by steven-zou** [comment]
Change app title in sign-in page to 'VIC' when integration mode is enabled
Hide language switcher when integration mode is enabled

**Comment by steven-zou** [comment]
@lweitzman 

 Please help to verify.

**Comment by lweitzman** [comment]
i'm looking at https://10.160.251.93:8443/harbor/sign-in this one is probably old and has "Harbor" as title and the language picker.
is there another environment to see the integrated mode?
