### ISSUE TITLE
Support customized host/port in pull command

### ISSUE THREAD

**Issue by hainingzhang** [vmware/harbor#1866]
In Harbor's UI, user can view the pull command of an image. Currently, displaying of hostname/port is not configurable. It will be helpful to configure this in some scenario. 

Please consider adding a param in the config or admin console.

**Comment by reasonerjt** [comment]
add the port in hostname in harbor.cfg should fix this, i.e.:

hostname=192.168.0.5:8443

**Comment by hainingzhang** [comment]
ok. maybe we can update the document for this.

**Comment by reasonerjt** [comment]
Updated installation guide.
