### ISSUE TITLE
Password should not be passed to front end in GET target API

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#1873]

**Comment by reasonerjt** [comment]
I think it's the "GET" target API that should not pass the password to browser and at the same time in ping API UI should remove the "password" key in request?

**Comment by ywk253100** [comment]
Yes, it's GET target API. But "password" is needed sometimes in ping target API, such as user creates a new target or ping an existing target but modifies its attributions.

**Comment by ywk253100** [comment]
Fixed by #1944 .
