### ISSUE TITLE
all container can not start 

### ISSUE THREAD

**Issue by scheng1** [vmware/harbor#1877]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
docker version 1.10.3  docker-compose version 1.11.2  harbor 0.5.0
2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
[root@hna-fedora harbor]# cat harbor.cfg |egrep -v ^#

hostname = bjmirror.hcpaas.com

ui_url_protocol = http

email_identity = 

email_server = smtp.mydomain.com
email_server_port = 25
email_username = sample_admin@mydomain.com
email_password = abc
email_from = admin <sample_admin@mydomain.com>
email_ssl = false

harbor_admin_password = Harbor12345

auth_mode = db_auth

ldap_url = ldaps://10.70.77.41:389
ldap_searchdn = cn=%s,ou=users,dc=hcpaas,dc=com

ldap_search_pwd = toor

ldap_basedn = ou=users,dc=mydomain,dc=com

ldap_uid = cn

ldap_scope = 3 

db_password = root123

self_registration = off

use_compressed_js = on

max_job_workers = 3 

token_expiration = 30

verify_remote_cert = off

customize_crt = off

crt_country = CN
crt_state = State
crt_location = CN
crt_organization = organization
crt_organizationalunit = organizational unit
crt_commonname = example.com
crt_email = example@example.com

project_creation_restriction = everyone

ssl_cert = /data/cert/server.crt
ssl_cert_key = /data/cert/server.key

3)Log files, you can get them by package the /var/log/harbor/ .
nothing

[root@hna-fedora harbor]# docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                          PORTS                                      NAMES
6fb821ac1d64        nginx:1.11.5                     "nginx -g 'daemon off"   29 seconds ago      Restarting (1) 4 seconds ago    0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   nginx
dce9b9487436        vmware/harbor-jobservice:0.5.0   "/harbor/harbor_jobse"   31 seconds ago      Restarting (2) 4 seconds ago                                               harbor-jobservice
b37c1c1d309f        vmware/harbor-db:0.5.0           "docker-entrypoint.sh"   37 seconds ago      Restarting (1) 11 seconds ago   3306/tcp                                   harbor-db
855e54b6febf        vmware/harbor-ui:0.5.0           "/harbor/harbor_ui"      37 seconds ago      Restarting (2) 1 seconds ago                                               harbor-ui
65786de1eeee        library/registry:2.5.0           "/entrypoint.sh serve"   37 seconds ago      Restarting (1) 12 seconds ago   5000/tcp                                   registry
e693c35e5a3d        vmware/harbor-log:0.5.0          "/bin/sh -c 'crond &&"   40 seconds ago      Up 36 seconds                   0.0.0.0:1514->514/tcp                      harbor-log

**Comment by scheng1** [comment]
laji

**Comment by reasonerjt** [comment]
It's likely an issue with permission of directories on your docker host.

**Comment by reasonerjt** [comment]
closing due to in activity.
