### ISSUE TITLE
word make user confuse

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#1878]
the all projects should be all my projects, or it seems to mean all user's projects(include public and private) on this registry.
![confuse](https://cloud.githubusercontent.com/assets/23101283/24496236/3af8dffc-156a-11e7-8ce7-641623712022.PNG)

**Comment by lweitzman** [comment]
I think this is working as @akshayl (please verify) asked ie 
'- Projects: the dropdown should say "All Projects" and "Public Projects" instead of "My Projects" and "Public Projects" ' from his email dated March 24th

**Comment by lweitzman** [comment]
can we close this @steven-zou
