### ISSUE TITLE
Button currently looks a little small, especially in Chinese.

### ISSUE THREAD

**Issue by wknet123** [vmware/harbor#1879]
![image](https://cloud.githubusercontent.com/assets/5027302/24497057/c1be3e36-156c-11e7-8233-a3e759c27005.png)

![image](https://cloud.githubusercontent.com/assets/5027302/24496885/3246dc18-156c-11e7-8737-8b314e356f99.png)

**Comment by lweitzman** [comment]
This is the proper size for english. Not sure if there should be a conversion of font sizes when using chinese.

**Comment by tonycgil** [comment]
@lweitzman No I haven't seen this. We should increase it by 2px if possible

**Comment by lweitzman** [comment]
just a clarification @tonycgil  thats a 2px increase for chinese only, right?

**Comment by steven-zou** [comment]
Raise issue to Clarity team. Let's wait for their response and solution.

**Comment by tonycgil** [comment]
@lweitzman yes. I got that number by doing simple photoshop resize of the font. We can wait to see what Clarity says per @steven-zou reply.

**Comment by steven-zou** [comment]
Outdated, close our issue now.
