### ISSUE TITLE
Missing APIs for UI development.

### ISSUE THREAD

**Issue by wknet123** [vmware/harbor#188]
## Missing API about counting repositories and getting roles when retrieve the public or private projects.
Based on the existing project api, missing two fields about counting repositories and corresponding role info.
`
{
  'project_name' : 'myrepo',
  'repo_count': '2',
  'role_id': '2'
  ...
}
`
## Missing API about listing top 10 public repositories with corresponding image size and creator.

This API should retrieve records without logging in. It seems like the existing search API in repositories 
section.

`
{
  'repo_name': 'myrepo/mysql'
  'size':  '598mb'
  'author': 'kunw'
}
`
## Missing API about listing recent push/pull/create operation logs not considering project 
`
[
  {
    'user_name': 'kunw'
    'repo_name': 'myrepo/ubuntu'
    'operation': 'create'
    'creation_time': '2016-05-07 13:25:30'
  },
   {
    'user_name': 'haox'
    'repo_name': 'myrepo/mysql'
    'operation': 'push'
    'creation_time': '2016-05-07 14:35:30'
  },
   {
    'user_name': 'haox'
    'repo_name': 'myrepo/mysql'
    'operation': 'pull'
    'creation_time': '2016-05-07 14:45:21'
  }
]
`
## Missing API about updating user's profile.
method='PUT'
`
{
  'username': 'test',
  'email': 'test@mydomain.com',
  'full_name': 'tester',
  'comment': 'My Comments'
}
`

**Comment by wemeya** [comment]
have completed the first API and now working on the 3rd and 4th

**Comment by wknet123** [comment]
### Please add a field  "owner_id" into API "/api/projects/2/members" (GET) for getting project owner id.

**Comment by reasonerjt** [comment]
Owner_id is an attribute of a project so it should be returned by " GET /api/projects/{id}"
