### ISSUE TITLE
delete an endpiont which is used by replication rule should give meaningful error

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#1881]
delete an endpiont which is used by replication rule should give meaningful error
![delendpoint](https://cloud.githubusercontent.com/assets/23101283/24498243/82c4f14e-1570-11e7-8c8e-353111d610cf.PNG)

**Comment by reasonerjt** [comment]
1)API should return 412
2)When getting a 412 UI should be specific about the restriction.

**Comment by ywk253100** [comment]
The API returns 412 now.
