### ISSUE TITLE
Cannot enable a disabled policy when edit the policy

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#1882]
<img width="577" alt="2" src="https://cloud.githubusercontent.com/assets/5835782/24499894/d68f0f44-1575-11e7-9f26-031f8ae399bd.png">

**Comment by wknet123** [comment]
Fixed with PR #1891

**Comment by steven-zou** [comment]
@ywk253100 

Please verify now?

**Comment by ywk253100** [comment]
Verified.
