### ISSUE TITLE
Need more information about first issue in troubleshooting section in installation guide.

### ISSUE THREAD

**Issue by chuqiming** [vmware/harbor#189]
In the troubleshooting section of installation guide, I have no idea which file should be updated to remove lines 
proxy_set_header X-Forwarded-Proto $scheme;

**Comment by xiahaoshawn** [comment]
@chuqiming  ./Deploy/config/nginx/nginx.conf  include the lines which need to be removed.

**Comment by chuqiming** [comment]
Please add this configuration into the installation guide. Thanks.

**Comment by xiahaoshawn** [comment]
update this configuration with pull request https://github.com/vmware/harbor/pull/206

**Comment by reasonerjt** [comment]
@chuqiming could you check the PR and see if that's clear to you?  If it is I'll merge it

**Comment by reasonerjt** [comment]
fixed in #206

**Comment by chuqiming** [comment]
The installation guide has been updated with this fix. Agree to close this issue.
