### ISSUE TITLE
when password does not match, should give user hint

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#1897]
sign up a new user, if password does not match, the sign up button is grey, but no error hint
![password](https://cloud.githubusercontent.com/assets/23101283/24542644/fbfcb4a2-162e-11e7-94e4-eedecd0f2cb7.PNG)

**Comment by sigsbee** [comment]
close because of old firefox version

**Comment by lweitzman** [comment]
there is still an issue. if i fill out the password field, put a password into the confirm field that doesnt match, i get the warning. but then if i go back and fix the original password to match, the system doesn't do the check until i go back to the confirmation field and exit that field. if the confirmation field has content in it, the check should be done when exiting the main password field as well.

**Comment by steven-zou** [comment]
@lweitzman @sigsbee 

Support now!

**Comment by steven-zou** [comment]
Will use event 'blur' to instead the 'focusout'.

**Comment by steven-zou** [comment]
changed.

**Comment by sigsbee** [comment]
verified
