### ISSUE TITLE
Members action menu is clipped on last row in datagrid

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1899]
the members action menu for a project is clipped and a scroll bar shows up when clicking on the 3 dots.
<img width="1054" alt="screen shot 2017-03-31 at 9 31 09 am" src="https://cloud.githubusercontent.com/assets/626032/24553183/4b56da42-15f7-11e7-871b-da1d0441fe59.png">

**Comment by stuclem** [comment]
I also saw something similar in the Projects view with vic-v1.1.0-rc2-81820686.ova:

![rendering](https://cloud.githubusercontent.com/assets/16718369/24755228/a587942a-1ad9-11e7-80d0-89633aa61256.png)
