### ISSUE TITLE
"i" next to checkbox

### ISSUE THREAD

**Issue by tonycgil** [vmware/harbor#1902]
Small nit here but I can't help to notice the checkmark and "i" are not vertically centered in many places. Hopefully if fixed, it will cascade.

![i-checkmark](https://cloud.githubusercontent.com/assets/25991813/24618794/0754a538-184d-11e7-84de-e560527c80fd.png)

**Comment by steven-zou** [comment]
Applied minor changes.

<img width="1376" alt="2017-04-05 12 19 18" src="https://cloud.githubusercontent.com/assets/5753287/24690823/fdb4d442-1a01-11e7-98a1-4e1122af9bc9.png">

**Comment by tonycgil** [comment]
Awesome!
