### ISSUE TITLE
Use Clarity Select Boxes for "All Project" drop down

### ISSUE THREAD

**Issue by tonycgil** [vmware/harbor#1904]
Use Clarity Select Boxes for "All Project" drop down

<img width="253" alt="screen shot 2017-04-03 at 7 43 52 am" src="https://cloud.githubusercontent.com/assets/25991813/24670300/59a19b2c-1922-11e7-9614-df71625af7e6.png">

**Comment by steven-zou** [comment]
Pending for many days, will close it.

@tonycgil 

If you have any problems, you can reopen it. Thanks.

**Comment by tonycgil** [comment]
@steven-zou thank you
