### ISSUE TITLE
It is not a good idea to check the tag when getting the catalog

### ISSUE THREAD

**Issue by 10liuguang01** [vmware/harbor#191]
code: harbor/service/utils/cache.go  func RefreshCatalogCache()
When there many repositories in one project, too many http request will be established.

**Comment by ywk253100** [comment]
When calling the catalog API, repositories which are removed are also listed. This is a bug of registry.
https://github.com/docker/distribution/issues/1615
So we made a workaround as you mentioned to fix it. The cache refreshing is an asynchronous operation, and it has a small impact on user experience.

**Comment by reasonerjt** [comment]
I've commented the code and further work will be tracked by #435
