### ISSUE TITLE
[UI] tooltip should not fix after click.

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#1921]
![image](https://cloud.githubusercontent.com/assets/2841473/24699396/66697988-1a26-11e7-98e9-c12faaf82beb.png)

**Comment by steven-zou** [comment]
Raise issue to Clarity team, pls refer https://github.com/vmware/clarity/issues/681

**Comment by steven-zou** [comment]
Verified, issue will be gone if upgrading Clarity to version >0.8.14

**Comment by steven-zou** [comment]
We have upgrade to 0.9.X. Let's close this issue.
