### ISSUE TITLE
[UI] the warning message should not pop up after leave the page.

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#1923]
![image](https://cloud.githubusercontent.com/assets/2841473/24700010/7d6a450c-1a28-11e7-832e-a41f84c2e564.png)

**Comment by steven-zou** [comment]
Wrong snapshot.

**Comment by steven-zou** [comment]
The message alert is more like a notification. Although you have left the page, the triggered backend job is still running and we should notify the user the result when response returned.

Currently, the later is becoming fixed as notification. No matter what pages you're staying. Focusing on job response notifications.

**Comment by steven-zou** [comment]
Upgrade the message alert as global box on top of all components.
Fixed in master.

**Comment by steven-zou** [comment]
Use a top fixed alert as notification.
