### ISSUE TITLE
Sensitive files in /data/harbor directory are readable by everyone

### ISSUE THREAD

**Issue by hmahmood** [vmware/harbor#1932]
Files in `/data/harbor`, `/etc/vmware/harbor`, and subdirectories seem to be all readable by everyone on the system. Examples:
```
/data/harbor/cert/*
/data/harbor/config/key
/data/harbor/secretkey
/data/fileserver/cert/server.key
/etc/vmware/harbor/common/config/nginx/cert/server.key
/etc/vmware/harbor/common/config/ui/private_key.pem
/etc/vmware/harbor/common/templates/ui/private_key.pem
/etc/vmware/harbor/common/config/notary/notary-signer.key
/etc/vmware/harbor/common/templates/notary/notary-signer.key
```

**Comment by reasonerjt** [comment]
@hmahmood thanks for raising such issues, but IMO #1932 and #1933 are issue in deployment, hence it should be fixed in OVA?

Your thoughts?

**Comment by hmahmood** [comment]
However you guys want to fix it. If the files are not created by your code, then yes, they are a deployment issue.

**Comment by frapposelli** [comment]
Quick update (we're tracking this issue deployment side with vmware/vic#4638).

Certificates are generated by our deployment scripts, so everything under
```
/data/harbor/cert/*
/etc/vmware/harbor/common/templates/ui/private_key.pem
/etc/vmware/harbor/common/templates/notary/notary-signer.key
```
is going to be fixed on the OVA side, while

```
/data/harbor/config/key
/data/harbor/secretkey
/etc/vmware/harbor/common/config/nginx/cert/server.key
/etc/vmware/harbor/common/config/ui/private_key.pem
/etc/vmware/harbor/common/config/notary/notary-signer.key
```

Are generated by the harbor `prepare` script that we consume, so I would suggest setting a `umask 077` in the script when generating secrets.


`/data/fileserver/cert/server.key` is not a Harbor file.

**Comment by wy65701436** [comment]
change to 600, and tested in RC2 build.
