### ISSUE TITLE
 How do I delete images ?

### ISSUE THREAD

**Issue by xiaoqge** [vmware/harbor#194]
root@a01:/opt# docker login 10.254.1.24
Username: user
Password: 
Login Succeeded

root@a01:/opt# curl -X DELETE 10.254.1.24/v2/test/consul-server/manifests/v2
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Name":"test/consul-server","Action":"*"}]}]}

 How do I delete images ?

**Comment by ywk253100** [comment]
You can delete repositories and tags using Harobr's API. Please check docs/configure_swagger.md and docs/swagger.yaml about the details.

**Comment by xiaoqge** [comment]
thank you
