### ISSUE TITLE
API does NOT return right data

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#1956]
API: /api/projects/1/members
Data returned:
`[
  {
    "user_id": 1,
    "username": "admin",
    "email": "",
    "password": "",
    "realname": "",
    "comment": "",
    "deleted": 0,
    "role_name": "projectAdmin",
    "role_id": 1,
    "has_admin_role": 0,
    "reset_uuid": "",
    "creation_time": "2017-02-08T08:03:25Z",
    "update_time": "2017-02-08T08:03:25Z"
  }
]`

admin is an administrator, the "has_admin_role" should be 1, but now is 0.

**Comment by ywk253100** [comment]
"has_admin_role" is a useless field in the member API. We can remove it.

**Comment by reasonerjt** [comment]
this is a technical debt that we should not reuse same model for different APIs.  @ywk253100 if we cannot remove the field in struct by adding annotation, let's fix it in next release.

**Comment by ywk253100** [comment]
Done #2607 .
