### ISSUE TITLE
what is the meaning of project, repository and user? 

### ISSUE THREAD

**Issue by fastzhong** [vmware/harbor#196]
Hi, Docker image format: 
Usage:  docker tag [OPTIONS] IMAGE[:TAG] [REGISTRYHOST/][USERNAME/]NAME[:TAG]

It seems Harbor introduces project and repository? How to use them with Docker? I think it is missing from the document.

**Comment by bobbyjunzhang** [comment]
@fastzhong Thanks for the comment and great to know that you are exploring our project! Yes, we will enhance the documentation on this. Before that is done, any quick words on this, @hainingzhang @reasonerjt ? @fastzhong is a friend.

**Comment by bobbyjunzhang** [comment]
@fastzhong, have you checked out the user guide at:
https://github.com/vmware/harbor/blob/master/docs/user_guide.md

**Comment by fastzhong** [comment]
Hi, from the user guide: 

$ docker tag ubuntu:14.04 10.117.169.182/demo/ubuntu:14.04  

demo is a harbor project name, so the format looks different from docker.

**Comment by reasonerjt** [comment]
username or projectname are all "namespace" for docker image.
On docker hub, docker use the username as the namespace
On Harbor, we use the project name as the namespace.

The term "project" is designed as both namespace of docker images and a group of users, such that when a user is added to a project, assigned with a role, he has permission to write/read the images under this namespace, according to the role he has.

**Comment by reasonerjt** [comment]
@fastzhong is there any further question?

**Comment by cmingxu** [comment]
The project/namespace gave me some confusion initially too, do we have any plan to change project to namespace?

**Comment by reasonerjt** [comment]
@cmingxu  thanks for raising this, we don't have the plan yet
But we'll discuss it maybe add some inline help to help user better understand the terminology.
