### ISSUE TITLE
in standalone mode, the header should say "Harbor" not "vSphere Integrated Containers"

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1969]
in standalone mode the header should say Harbor.

![screen shot 2017-04-07 at 9 05 31 am](https://cloud.githubusercontent.com/assets/626032/24801291/9a5b42ac-1b71-11e7-913f-ccf0223b33c1.png)

**Comment by steven-zou** [comment]
A weird issue, will check why happened.

**Comment by steven-zou** [comment]
@lweitzman 

Which env did you find it? https://10.117.4.151/harbor?

I cannot reproduce it in 151 env. Have you tried clear browser cache and reload the page?

<img width="1412" alt="2017-04-10 10 47 50" src="https://cloud.githubusercontent.com/assets/5753287/24844165/47890f98-1ddb-11e7-9ec1-38a455cab84c.png">

**Comment by lweitzman** [comment]
i will close this. i think it was a caching issue.
