### ISSUE TITLE
Accounts should lock out for a configurable period after N invalid password attempts

### ISSUE THREAD

**Issue by jakedsouza** [vmware/harbor#1971]
According the security testing criteria, accounts should lock out for at least 15 minutes after 5 invalid password attempts. This should preferable be configurable as a lockout policy

I was able to login after multiple incorrect login attempts

**Comment by maplain** [comment]
https://github.com/vmware/harbor/issues/1935

**Comment by jakedsouza** [comment]
Marking as a dup and closing.
