### ISSUE TITLE
UX: inconsistency in error messages on sign up page

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/harbor#1972]
Harbor version 1.1.0-rc1

Sign up with a username that's taken:

<img width="549" alt="username" src="https://cloud.githubusercontent.com/assets/4361620/24819607/edf08416-1baa-11e7-8525-768bdb96ae59.png">

Sign up with an email that already has an account:

<img width="558" alt="email" src="https://cloud.githubusercontent.com/assets/4361620/24819608/f2402576-1baa-11e7-930e-63fd26ef15ef.png">

The error messages should have consistent phrasing. For the second instance, "Email address is already used" or "Email address already exists" would be good.

This is a minor detail but it's nice to have consistent phrasing. Looks like the change belongs in https://github.com/vmware/harbor/blob/master/src/ui/static/i18n/lang/en-lang.json.

**Comment by steven-zou** [comment]
We have changed the messages, please check the latest code (master branch).

"EMAIL_EXISTING": "Email address already exists.",
"USER_EXISTING": "Username is already in use."
