### ISSUE TITLE
Question about 1.1.0-rc1

### ISSUE THREAD

**Issue by roldancer** [vmware/harbor#1974]
Hi All, I was testing this new tag (1.1.0-rc1) the look&feel is pretty nice, but I would like to know: 

What are the most important features that introduce this tag? 

Clair integration is ready?

Would be easy to migrate from 0.5 to 1.1.X ?

When +/- would be the stable version, any idea?

Thanks.

**Comment by cavemandaveman** [comment]
I would also add that an installer tarball, like in previous releases, would be very useful

**Comment by It4lik** [comment]
Yep, I was forced to use `make` with the target `all` to setup the solution : 
`$ make all GOBUILDIMAGE=golang:1.7.3 COMPILETAG=compile_golangimage CLARITYIMAGE=vmware/harbor-clarity-ui-builder:0.8.4 NOTARYFLAG=true HTTPPROXY=`

Yeah Clair integration would be great.

**Comment by cavemandaveman** [comment]
Yeah, I was hoping for a harbor-online-installer and harbor-offline-installer tarball like in previous releases, to avoid compiling

**Comment by reasonerjt** [comment]
we are not providing installer for RC, but soon there will be installer when it's released.
In the make command, if you remove "NOTARYFLAG=true", notary should not be installed.

For 1.1 we only introduced notary integration, for Clair, it's high priority but not very top...

**Comment by wy65701436** [comment]
guys, we won't provide the offline installer for RC, it's the internal used version so far. The new release will be announced soon.

**Comment by reasonerjt** [comment]
closing the issue due to inactivity.
