### ISSUE TITLE
In VIC mode, all references to "Harbor" should be replaced by "Registry"

### ISSUE THREAD

**Issue by akshayl** [vmware/harbor#1999]
![pasted_image_4_11_17__9_38_am](https://cloud.githubusercontent.com/assets/3515060/24920086/c3661b8c-1e9a-11e7-9318-0e6fa4bdb6ac.png)

- Search box should say Registry
- The page title should be Registry
- About box should say "vSphere Integrated Containers Registry (Powered by Harbor)"

**Comment by luguang** [comment]
Yes, it looks a reasonable change.

**Comment by steven-zou** [comment]
Changed in rc3.
