### ISSUE TITLE
Insecure registry push image fail

### ISSUE THREAD

**Issue by logicigam** [vmware/harbor#200]
I just setup a harbor following the offical instruction, docker deamon start with argument "--insecure-registry" , but I fail to push a image to the registry after I login to the registry,error log as follow:
`unauthorized: authentication required`

also the log of registry:
`
registry_1  | time="2016-05-09T15:18:26.284651273Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.6.1 http.request.host=reg.docker.meizu.com http.request.id=da453ca5-a821-4548-95ad-81649ff50a74 http.request.method=POST http.request.remoteaddr=172.17.32.16 http.request.uri="/v2/library/rancher/server/blobs/uploads/" http.request.useragent="docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/3.10.0-229.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \\(linux\\))" instance.id=0bb55562-08c6-4d1a-8c21-f27013490751 service=registry vars.name="library/rancher/server" version=v2.4.0 `

any idea?

**Comment by logicigam** [comment]
`error authorizing context: insufficient scope`
this maybe the cause,anyone know why?

**Comment by ywk253100** [comment]
@logicigam Harbor does not support multi-level namespace in repository name. You can use library/rancher_server instead.

**Comment by logicigam** [comment]
but this image is require by a third party dependency,the image name must keep exactly what they should be .otherwise I must manually tag all of the images(which is a huge number of)by myself... is there any road map to support multi-level namespace?

**Comment by reasonerjt** [comment]
@logicigam I don't quite understand, do you mean the image name has to be** library/rancher/server**?

I assume it has to be **rancher/server**?  If this is the case why not just create a project called "rancher"?

**Comment by searover** [comment]
@reasonerjt I dont't think so, **rancher** maybe a company's name, a framework's name, or just a person's name, we really don't want to create a project for it, and also, we don't want to rename **rancher/server** to **rancher_server**, because the "_" symbol often used to combine two tools in one image, like **library/java_maven**, and if this image created by jerry, it better be  **library/jerry/java_maven**.
Please consider this situation, thanks.

**Comment by hainingzhang** [comment]
We are not supporting multi-level namespace unless there is a strong requirement on this. Closing it for now. please reopen if needed.
