### ISSUE TITLE
"ALL STATUS" dropdown should be Select Boxes Clarity component 

### ISSUE THREAD

**Issue by tonycgil** [vmware/harbor#2005]
The "ALL STATUS" dropdown in the Projects>Replication page should be a Clarity Select Boxes component: https://vmware.github.io/clarity/documentation/select-boxes

<img width="315" alt="screen shot 2017-04-12 at 7 42 40 am" src="https://cloud.githubusercontent.com/assets/25991813/24963758/5e54107c-1f54-11e7-9ba4-701d1788927b.png">

**Comment by steven-zou** [comment]
None function blocking issue, defer to next release.

**Comment by steven-zou** [comment]
As it was fixed. Close it.
