### ISSUE TITLE
Known issues in Harbor portal of V1.1

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#2007]
The date format component block the datagrid view to display data on Safari of version < 10.

**Comment by stuclem** [comment]
Proposed release note entry:

-----

- <b>The date format component blocks the datagrid view to display data on Safari 10 and later. [#2007](https://github.com/vmware/harbor/issues/2007)</b>

-----

@steven-zou is this OK? Thanks!

**Comment by steven-zou** [comment]
Invalid now, close!
