### ISSUE TITLE
Limitation about current vmware/harbor-clarity-ui-builder image

### ISSUE THREAD

**Issue by wknet123** [vmware/harbor#2014]
Should fit UI building task with dependency module changes dynamically.

**Comment by wy65701436** [comment]
@wknet123 , can you give more details?

**Comment by wknet123** [comment]
Should detect changes on `package.json` file then update the node_modules, means should rebuild and update this builder image simultaneously.

**Comment by wy65701436** [comment]
Discussed with Wk, here needs to add two parameters in the build process.
1, Flag to index whether to build the Clarity image and push it into VMware namespace.
2, Clarity builder version.

**Comment by wknet123** [comment]
Close as it fixed.
