### ISSUE TITLE
API /repositories/tags method: GET caught an json error

### ISSUE THREAD

**Issue by tinytub** [vmware/harbor#202]
I have pull harber master latest code.

I try to get repositories tags use this uri
`/repositories/tags?repo_name=public/registry`
then i got an 500 error

and this is the error log from harbor_ui
```
==> /var/log/harbor/2016-05-09/docker_ui.log <==
May  9 19:38:30 172.19.0.1 docker/ui[15985]: 2016-05-09T11:38:30Z [ERROR] [repository.go:192]: Get http://registry:5000/v2/public/registry/tags/list: json: cannot unmarshal number into Go value of type string
```

and please check my new comment in https://github.com/vmware/harbor/pull/171
@ywk253100 @reasonerjt 
I'm sorry for my first comment in that PR. The code I have tested is not the latest.

**Comment by ywk253100** [comment]
Resolved. Please pull the latest code.
