### ISSUE TITLE
hint text and validation for date input when in advanced mode for filtering logs

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#2022]
when filtering logs its hard to know what format to put the date in. it would be nice if clicking on the calendar icon opens a widget to select a date. if not we should provide hint text in the field to show the format of the date. also, typing invalid input should provide validation.

![validation for log filter](https://cloud.githubusercontent.com/assets/626032/25044831/cb8161f6-20f6-11e7-9f1c-b88be090af25.png)

**Comment by steven-zou** [comment]
A long time and it was fixed. Close this issue.
