### ISSUE TITLE
Repo API should be enhanced to support get all data of tags in one call

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#2027]
Currently, sending request for each tag
Notary info is retrieved in another call
In v1.2, vulnerability is involved in

**Comment by steven-zou** [comment]
@lweitzman @akshayl 

Use this issue to track the API upgrading

**Comment by reasonerjt** [comment]
We should fix #2236 along with this issue.

**Comment by ywk253100** [comment]
Completed by #2355 .
