### ISSUE TITLE
change label on the metrics from "My" to "Private"

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#2036]
in the metrics in the upper right, change the label from "My" to "Personal"

<img width="504" alt="screen shot 2017-04-17 at 5 51 18 pm" src="https://cloud.githubusercontent.com/assets/626032/25106251/84f75202-2396-11e7-931a-2f75ac2b8586.png">

**Comment by steven-zou** [comment]
@lweitzman 

to 'private' not 'personal', finalized?

**Comment by lweitzman** [comment]
but you can have public "personal" projects ... so private is not appropriate (afaik)

**Comment by steven-zou** [comment]
Related with https://github.com/vmware/harbor/issues/2040

**Comment by lweitzman** [comment]
@akshayl should comment on this

**Comment by steven-zou** [comment]
Will change 'MY' to 'PRIVATE' and make sure PRIVATE+PUBLIC=ALL. These three metrics will based on 'access level' property.

**Comment by steven-zou** [comment]
Changes of UI end is in PR #2516.
Api of showing metrics still has issues, tracked by #2468. Close this issue.
