### ISSUE TITLE
MySQL container fails to start with innodb error

### ISSUE THREAD

**Issue by seanlutner** [vmware/harbor#204]
I'm trying to setup the harbor service and I'm running into an issue where I cannot start the project because of an error in starting the mysql container. I have removed all previous containers, images, volumes, but the error persists. I do not have any data in /var/log/harbor or even a /var/log/harbor directory on my system (mac), but I've attached the output from the cli. I am using the Docker for Mac beta, not sure if that matters or not.

$ docker version
Client:
Version:      1.11.1
API version:  1.23
Go version:   go1.5.4
Git commit:   5604cbe
Built:        Wed Apr 27 00:34:20 2016
OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   8b63c77
 Built:        Fri Apr 29 14:13:26 2016
 OS/Arch:      linux/amd64

$ docker-compose version
    docker-compose version 1.7.0, build 0d7bf73
    docker-py version: 1.8.0
    CPython version: 2.7.9
    OpenSSL version: OpenSSL 1.0.1j 15 Oct 2014

[harbor-error-cli-log.txt](https://github.com/vmware/harbor/files/255268/harbor-error-cli-log.txt)
[harbor-config.tar.gz](https://github.com/vmware/harbor/files/255270/harbor-config.tar.gz)

**Comment by saga92** [comment]
Hi @seanlutner Maybe there's another mysqld process using the same InnoDB data or log files. You can use `service mysql stop ` to stop mysqld daemon in your virtualbox host machine or `docker ps` and `docker stop xxx && docker rm xxx` to remove other mysqld daemon in docker container which still occupy your ibdata resource.

**Comment by seanlutner** [comment]
Hi @saga92 I don't have any other containers running mysql. I have deleted all the containers, images, and volumes associated with the Harbor project a number of times, and this happens every time. I've even deleted my clone of the repo and started over from that level as well. Even when starting from that point, I am still seeing this error. I'm going to switch back to Docker Toolbox to see if that helps. If that works, then there is some issue with the Docker for Mac Beta when working with the Harbor project.

**Comment by seanlutner** [comment]
After switching back to the Docker toolbox, I saw some old images and containers that did not get moved over to the Docker for Mac beta upon installation. One of these was a previous copy of the harbor mysql server and was causing the problem. Removing those and flipping back to the beta has done the trick and I'm up and running again. Sorry for the confusion and thanks for the help.
