### ISSUE TITLE
Integrate with Clair for vulnerability scan.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#2042]
1. Deploy Harbor with Clair.
2. Use backend job to call Clair for scanning image on Harbor
3. Show state of scanning.
4. Overview/Details of vulnerabilities of image.

**Comment by marcellodesales** [comment]
@reasonerjt any ETA for this?

**Comment by UlaganathanNamachivayam** [comment]
Any update on this ? Will be really helpful!

**Comment by jryberg** [comment]
This is very useful and important from a audit/security perspective.

I just cross my fingers and hope it will be released anytime soon.

For now, I'm using https://github.com/optiopay/klar for CI integration but I would really want to have this feature implemented in Harbor as well.

**Comment by reasonerjt** [comment]
resolving this issue as the key features are in master branch, further tweak will be tracked by new issues.

**Comment by marcellodesales** [comment]
@reasonerjt Is the key features documented anywhere?
