### ISSUE TITLE
alignment of first tab in the tab bar should start at the beginning of the line

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#2063]
the first item in the tab bar should start at the beginning of the tab bar line. this is correct on the configuration page but its not on a project page and the replication page. see https://vmware.github.io/clarity/documentation/tabs 

![screen shot 2017-04-18 at 8 36 52 am](https://cloud.githubusercontent.com/assets/626032/25131214/e981828e-2412-11e7-9205-110781fc844d.png)

![screen shot 2017-04-18 at 8 33 10 am](https://cloud.githubusercontent.com/assets/626032/25131220/eefb55c8-2412-11e7-8a1f-7be39bcd7ba1.png)

**Comment by steven-zou** [comment]
@wknet123 

  Please help to fix this bug.

**Comment by steven-zou** [comment]
A long time and it was fixed. I'll close it.
