### ISSUE TITLE
Projects table footer sticks out beyond the width of the table

### ISSUE THREAD

**Issue by akshayl** [vmware/harbor#2064]
![image](https://cloud.githubusercontent.com/assets/3515060/25149250/9b611798-2432-11e7-9394-4d05950b0344.png)

**Comment by steven-zou** [comment]
Bug only appear on Chrome browser.
It might be a bug from Clarity Datagrid component, will do investigation and fixed it in v1.2.

**Comment by steven-zou** [comment]
Checked, caused by Clarity datagrid issue.
It can be fixed after upgrading Clarity version to >0.9.0.

**Comment by wknet123** [comment]
Duplicate with #2140
