### ISSUE TITLE
Unable to delete an image

### ISSUE THREAD

**Issue by manginkr** [vmware/harbor#208]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose
2)Config files of harbor, you can get them by packaging "Deploy/config" directory
3)Log files, you can get them by package the /var/log/harbor/

**Comment by reasonerjt** [comment]
There's nothing we can do with such information

**Comment by manginkr** [comment]
thanks for the reply. then how can we delete the old images pushed in to the projects

**Comment by manginkr** [comment]
docker engine - 1.11.1
docker compose - 1.7
Harbor - 0.1.1 package

**Comment by ywk253100** [comment]
@manginkr The deletion of repositories and tags is supported in the latest code. You can use the API of Harbor to delete them for now. About the details of Harbor API, please see docs/swagger.yaml. And the issue #112 explains the implements.

**Comment by xiaods** [comment]
The deletion of projects is not supported for now.

**Comment by manginkr** [comment]
How about deletion of repositories

**Comment by xiaods** [comment]
https://github.com/vmware/harbor/blob/master/api/repository.go#L113
it works
