### ISSUE TITLE
Expand disk on harbor virtual appliance 1.1

### ISSUE THREAD

**Issue by fduranti** [vmware/harbor#2085]
On harbor 0.5 the /data was in a LVM volume and there was a clear procedure to extend the /data partitoin.
On harbor 1.1 I've not found the procedure to expand the volume and the /data seems to be mounted directly from /dev/sdb1.

There's a procedure to expand the disk?

**Comment by reasonerjt** [comment]
We are not shipping virtual appliance for 1.1 and probably future releases.
You can mount the /data directory to a volume managed by LVM, but it's not in the installer.

**Comment by fduranti** [comment]
The virtual appliance is the one of the vic installation so I should probably check/ask on vic project. 
Thanks for the answer.
