### ISSUE TITLE
buttons on delete project should be "Cancel" and "Delete"

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#2099]
the current confirmation dialog for deleting a project is
![screen shot 2017-04-20 at 5 41 07 pm](https://cloud.githubusercontent.com/assets/626032/25253834/95d472e2-25f0-11e7-95ba-6332d616ab85.png)

and the buttons should say "Cancel" and "Delete" (according to clarity) 
the title should say "Delete project"
![screen shot 2017-04-20 at 5 39 30 pm](https://cloud.githubusercontent.com/assets/626032/25253820/8123de28-25f0-11e7-9702-e7a8492bab44.png)

**Comment by steven-zou** [comment]
Will fix this in next version.

**Comment by steven-zou** [comment]
As it was fixed, let's close it.
<img width="597" alt="2017-05-16 10 31 46" src="https://cloud.githubusercontent.com/assets/5753287/26119683/ee9f4c1c-3a22-11e7-9c07-34e5b07be82c.png">
