### ISSUE TITLE
Cannot set admin password in WebUI on 1.1.0

### ISSUE THREAD

**Issue by asmartin** [vmware/harbor#2100]
There does not appear to be a way to set the `admin` user's password on a fresh install of 1.1.0 when using `ldap_auth`. Is there a way to set this credential from the command line, or what is the new method for changing this password?

Thanks!

**Comment by steven-zou** [comment]
It's a bug and will fix it soon.

**Comment by asmartin** [comment]
I upgraded to 1.1.1-rc1 but still cannot see how to change the admin user's password when LDAP is enabled - how can I do this?

**Comment by sigsbee** [comment]
please make sure that you are running 1.1.1-rc1, and click admin's user name, change password option is above about
![change](https://cloud.githubusercontent.com/assets/23101283/25515488/9138a140-2c17-11e7-8c50-89e749f65710.PNG)

**Comment by asmartin** [comment]
It appears to be working now - I'm not sure if had some caching going on in my browser or what the problem was yesterday, but I can see the "Change Password" link on the admin account now. Thanks!
