### ISSUE TITLE
In the header, the vertical separator is on the wrong side of search

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#2137]
the search input is on the left of the vertical separator and should be to the right of it in standalone mode. also, the input field for search can be much longer if its on the right side.
this is on https://10.112.122.230/harbor/projects

![screen shot 2017-04-25 at 8 56 55 am](https://cloud.githubusercontent.com/assets/626032/25386423/49a6202a-2995-11e7-9bf2-da964e6fcf1c.png)

**Comment by steven-zou** [comment]
o? So weird. Will check and fix later.

**Comment by steven-zou** [comment]
@lweitzman 
 
  I checked, only found the issue in Safari. What's your browser and version?

**Comment by steven-zou** [comment]
@lweitzman 

About the search box, we use the Clarity style.

**Comment by lweitzman** [comment]
yes i was viewing it in safari

**Comment by lweitzman** [comment]
fixed in safari
