### ISSUE TITLE
我使用 Harbor 作为企业内部的registry，同时企业内部有自己私有的registry，现在想让我们自己私有registry作为Harbor的mirror，配置好后不起作用

### ISSUE THREAD

**Issue by kinglion811** [vmware/harbor#214]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose
2)Config files of harbor, you can get them by packaging "Deploy/config" directory
3)Log files, you can get them by package the /var/log/harbor/

**Comment by kinglion811** [comment]
我实验环境为serverA(10.10.219.231)、serverB(10.10.227.12)，serverA部署Harbor，serverB部署我私有的registry，现在想让severB作为serverA的mirror,配置好后，我再serverC(10.10.235.166)pull 镜像，severB 没有起到mirror作用。
serverA 能正常登陆，正常pull、cache即Harbor是正常的
serverB中我修改registry的配置
proxy:
  remoteurl: http://10.10.219.231
即其proxy指定为Harbor服务器
serverC中docker的配置文件为
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// -D  --registry-mirror=http://10.10.227.12 --insecure-registry 10.10.219.231
我push到我Harbor账号（testPr）的镜像能在serverC中正常pull，但是此镜像没有缓存到serverB中。

**Comment by reasonerjt** [comment]
目前registry应该只支持对docker hub的mirror吧？

**Comment by kinglion811** [comment]
让私有的registry 作为Harbor的mirror不可以？

**Comment by reasonerjt** [comment]
这和harbor没任何关系，据我所知，registry 本身只能mirror docker hub

**Comment by Thinkwp** [comment]
请问你的问题解决了吗？我也遇到了类似的问题。 @kinglion811

**Comment by kinglion811** [comment]
已经解决，这个是registry的问题，貌似2.5后的registry没有这个问题了






在 2016-12-13 16:10:31，"Thinkwp" <notifications@github.com> 写道：


请问你的问题解决了吗？我也遇到了类似的问题。 @kinglion811

**Comment by sysucjl** [comment]
你好！我也遇到了相似的问题，我把registry升级到2.5后，问题还是没有解决。请问还有什么办法吗？
