### ISSUE TITLE
Replace official docker images. - maria DB and mySQL

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#2142]
There are concerns for the nginx, mysql and notary db(based on maria db official image).

Need to replace them.

**Comment by reasonerjt** [comment]
This is not a must-have for 1.2 based on current information.

**Comment by wy65701436** [comment]
assing to @yixingjia

**Comment by reasonerjt** [comment]
Currently replaced official images:
nginx, postgresql.

TODO in future:
mysql, mariadb ...

**Comment by reasonerjt** [comment]
Harbor uses mysql but Notary uses MariaDB:
1) Build MariaDB on photon.
2) Try to move Harbor DB from mysql to Maria DB.  Risk: migration.

If 2) is not possible : 
2-a) Redesign migration process to export all data from Harbor db and import to new db instance.
2-b) build mysql on photon.

**Comment by yixingjia** [comment]
estimation  for 3171 1w

**Comment by yixingjia** [comment]
according to discussion with Daniel the 3173 issue is the the pks1.0 scope,not this one

**Comment by mdubya66** [comment]
should this have the 1.3 label added?

**Comment by reasonerjt** [comment]
It should.

**Comment by reasonerjt** [comment]
There maybe risk for #3323 , so plan B is to create a mysql image on top of photon.

**Comment by reasonerjt** [comment]
Fixed. closing the Epic.
