### ISSUE TITLE
REST API : "GET /repositories/manifest" can not work correctly

### ISSUE THREAD

**Issue by qq511700505** [vmware/harbor#215]
I am trying to get manifest of a repositories. I have push the docker image named **library/nginx:latest**, but when I use the  Harbor API to get its manifest. I got a respond from **Beego** like this:

   `     <html lang="en">`
   `	     <head>`
   `		     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">`
   `     <title>Not Found</title>`
   `	     	     <style type="text/css">`
   `			     * {`
   `				     margin:0;`
   `				     padding:0;`
   `			      }`
   `     ...`

However, I could use the API :**/repositories/tags** get the tag of **library/nginx** : 

` [         `
`  "latest" `
` ] `

**Comment by ywk253100** [comment]
It should be "/repositories/manifests", note the s in the end.

**Comment by qq511700505** [comment]
Indeed, the Swagger UI provides the URL is : 
`curl -X GET --header 'Accept: text/html' 'http://x.xxx.xxx.xx/api/repositories/manifest?repo_name=library%2Fnginx&tag=latest' `

This will get a respond of **NOT FOUND**.

But when I change **manifest** to **manifests** , I get a different respond :  **interral error**  .

What should I do to solve this error , thanks

**Comment by ywk253100** [comment]
The docs of API has been updated.
And for the internal error, please provide logs, you can find them in /var/log/harbor.

**Comment by qq511700505** [comment]
My problem has been solved. thanks for your help.
I think we could close the issue soon.

**Comment by qq511700505** [comment]
My problem has been solved. thanks for your help.
I think we could close the issue soon.
