### ISSUE TITLE
Should display the status when image signature cannot be determined.

### ISSUE THREAD

**Issue by hainingzhang** [vmware/harbor#2163]
When Notary is enabled but fails(crashes) for whatever reasons, the UI should show an unknown status of the signature instead of a tick or a cross sign. 

Suggest we display a question mark (?) or the like for this purpose. This avoids the confusion to the users. The user can refresh the UI to get the updated status when the Notary service is back to normal.

@akshayl @lweitzman

**Comment by akshayl** [comment]
Proposed behavior sounds good to me.

**Comment by lweitzman** [comment]
So the only place this notary itself exists in the UI currently is on the configration/image replication page. we should put up an alert when it is down with a link to that page. that status can be shown there using these icons to indicate that it is up and connected or needs attention.
![screen shot 2017-04-27 at 11 26 45 am](https://cloud.githubusercontent.com/assets/626032/25490963/7e47c6f0-2b3c-11e7-8cca-538269e6f8b6.png)

**Comment by lweitzman** [comment]
do we have the information about what is wrong with the notary? or that we just can't connect. 
it would be helpful to have a short message on the status icon about the state, whether connected or can't connect or something worse.

**Comment by steven-zou** [comment]
In summary, there should be three signature status:

  Notary is NOT enabled, hide the signature column or show a special icon;
  Notary is enabled and signatures are successfully returned, show green check icon;
  Notary is enabled but failed to return signature status, show cross error icon.

@hainingzhang @akshayl @lweitzman 
Anything else?

**Comment by lweitzman** [comment]
i thought this was when the notary itself was unreachable or down for some reason. changing the status for individual images is not appropriate in my opinion. thats why i created a status on the configuration/image replication page. @akshayl is this what is being asked for here? i think steven has the correct conditions for the "signed" column in the image datagrid. (only the icon for failed signature is an "!" in a circle (red).

![screen shot 2017-05-02 at 8 23 49 am](https://cloud.githubusercontent.com/assets/626032/25617525/b67c8498-2f10-11e7-8baa-f6dea1a194db.png)
