### ISSUE TITLE
Error logging in to Harbor from Photon OS

### ISSUE THREAD

**Issue by pdaigle** [vmware/harbor#2168]
I am unable to log in to Harbor using Photon OS Docker client (also tested with CoreOS, with same result). Log in works if I log in using VIC:

root@photon-b82rE9sWY [ ~ ]# docker login 192.168.100.102
Username (admin):
Password:
Error response from daemon: readdirent: not a directory
root@photon-b82rE9sWY [ ~ ]# docker -H 192.168.100.103:2376 --tls login 192.168.100.102
Username (admin):
Password:
Login Succeeded

Harbor was installed using OVA vic-v1.1.0-bf760ea2.

I can reproduce in my lab.

If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.

root@photon-b82rE9sWY [ ~ ]# uname -a
Linux photon-b82rE9sWY 4.4.60-1.ph1-esx #1-photon SMP Thu Apr 13 00:56:50 UTC 2017 x86_64 GNU/Linux
root@photon-b82rE9sWY [ ~ ]# docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.4
 Git commit:   092cba3
 Built:        Mon Apr 17 00:08:35 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   092cba3
 Built:        Mon Apr 17 00:08:35 2017
 OS/Arch:      linux/amd64
 Experimental: false

2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
3)Log files, you can get them by package the /var/log/harbor/ .

**Comment by reasonerjt** [comment]
Could you provide the log?  This looks like an error of your docker daemon.
In terms of "docker login" I don't think Harbor differentiates VCH and vanilla docker.

**Comment by pdaigle** [comment]
I fixed the login issue: it turns out I had an error in my certificate path.

Closing the issue.
