### ISSUE TITLE
can`t delete user in harbor v1.1.1

### ISSUE THREAD

**Issue by sinycn** [vmware/harbor#2169]
hi:
    I just upgrade harbor to v1.1.1 I can not del user in Administration---Users ,even I login with admin users
it shows   You do not have the proper privileges to perform the action.

**Comment by cbarzu** [comment]
I had the same problem trying to delete another user with admin permissions. The workaround in my case was to revoke administrador permissions and delete after.

Reagards,
Claudiu

**Comment by hainingzhang** [comment]
do you use LDAP/AD authentication or local database to store user info? @sinycn @cbarzu

**Comment by sinycn** [comment]
i use ad authentication to store user info ,once the account lothar is ok to login but the username is not shown well in v1.1.0, so i want to delete it,the user lothar does not have administrator permission,another problem is if i can not del user lothar ,it login failure now

**Comment by cbarzu** [comment]
Hmm I don't remeber when I did that if the ldap was configured.

Now, with LDAP configured, I can't delete any user.

**Comment by hainingzhang** [comment]
@cbarzu when LDAP is configured, deleting user should be at the LDAP server, not in Harbor. Once a user is deleted/disabled in LDAP, he/she no longer can log into Harbor.

**Comment by cbarzu** [comment]
Ok @hainingzhang, thank you :+1:

**Comment by steven-zou** [comment]
As it works as design. Close this issue.
