### ISSUE TITLE
Broken links on https://vmware.github.io/harbor/

### ISSUE THREAD

**Issue by stuclem** [vmware/harbor#2180]
As pointed out by @pdaigle, the links to the appliance user docs on https://vmware.github.io/harbor/ are broken. In fact, they should probably be removed, since the appliance is no longer being created for standalone Harbor. 

Also, should we link to https://vmware.github.io/vic-product from this page?

I am happy to do this, if you want me to.

**Comment by wknet123** [comment]
I'll update this page, thanks again.
