### ISSUE TITLE
project name should not have upper case character

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#2181]
1.1.1 rc2
when project name has upper case character, there should be a hint about the rule of project name
![name](https://cloud.githubusercontent.com/assets/23101283/25524584/b808ec50-2c3d-11e7-8b84-511911bacb33.PNG)

**Comment by steven-zou** [comment]
@wknet123 

  Confirm?

**Comment by steven-zou** [comment]
Fixed in #2315
