### ISSUE TITLE
Fails to login if the password contains ';'

### ISSUE THREAD

**Issue by TheJohnCollier** [vmware/harbor#2185]
I have installed the 1.1.1rc.  

I have SSL certs working and harbor works fine to log in via a CN without a space in the name.  If the DN has a space in it (i.e. CN=John Collier, OU=...), it fails to log in.  This similar config works in Harbor 0.5

Docker - 17.03.1-ce build c6d412e
Docker-compose - 1.12.0 build b31ff33

Config (excerpts): 
auth_mode = ldap_auth
ldap_url = ldaps://<DC Hostname>:3269
ldap_searchdn = CN=Harbor-r0,OU=ServiceAccount,OU=example,DC=domain,DC=com
ldap_search_pwd = <password>
ldap_basedn = DC=domain,DC=com
ldap_filter = (objectClass=person)
ldap_uid = sAMAccountName
ldap_scope = 3 
ldap_timeout = 5

self_registration = off
token_expiration = 30
project_creation_restriction = adminonly

This CN fails. (John Collier)
May  1 11:58:42 172.18.0.1 ui[2890]: 2017-05-01T15:58:42Z [DEBUG] [authenticator.go:59]: Current AUTH_MODE is ldap_auth
May  1 11:58:42 172.18.0.1 ui[2890]: 2017-05-01T15:58:42Z [DEBUG] [ldap.go:143]: one or more ldapFilter: (sAMAccountName=collierj.adm@dcgs.mil)
May  1 11:58:42 172.18.0.1 ui[2890]: 2017-05-01T15:58:42Z [WARNING] Not found an entry.
May  1 11:58:42 172.18.0.1 ui[2890]: 2017-05-01T15:58:42Z [DEBUG] [authenticator.go:71]: Login failed, locking collierj.adm@domain.com, and sleep for 1.5s
May  1 11:58:53 172.18.0.1 ui[2890]: 2017-05-01T15:58:53Z [DEBUG] [authenticator.go:59]: Current AUTH_MODE is ldap_auth
May  1 11:58:53 172.18.0.1 ui[2890]: 2017-05-01T15:58:53Z [DEBUG] [ldap.go:143]: one or more ldapFilter: (sAMAccountName=collierj.adm)
May  1 11:58:53 172.18.0.1 ui[2890]: 2017-05-01T15:58:53Z [DEBUG] [ldap.go:206]: Current ldap entry attr name: cn
May  1 11:58:53 172.18.0.1 ui[2890]: 2017-05-01T15:58:53Z [DEBUG] [ldap.go:206]: Current ldap entry attr name: sAMAccountName
May  1 11:58:53 172.18.0.1 ui[2890]: 2017-05-01T15:58:53Z [DEBUG] [ldap.go:80]: username: collierj.adm, dn: CN=John Collier,OU=<>,OU=<>=IT,DC=domain,DC=com
May  1 11:58:53 172.18.0.1 ui[2890]: 2017-05-01T15:58:53Z [WARNING] Failed to bind user, username: collierj.adm, dn: CN=John Collier, OU=Remote_users,OU=<>,OU=IT,DC=domain,DC=com, error: LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C0903D9, comment: AcceptSecurityContext error, data 52e, v2580
May  1 11:58:53 172.18.0.1 ui[2890]: 2017-05-01T15:58:53Z [DEBUG] [authenticator.go:71]: Login failed, locking collierj.adm, and sleep for 1.5s

This CN works. (test)
May  1 12:22:25 172.18.0.1 ui[2890]: 2017-05-01T16:22:25Z [DEBUG] [authenticator.go:59]: Current AUTH_MODE is ldap_auth
May  1 12:22:25 172.18.0.1 ui[2890]: 2017-05-01T16:22:25Z [DEBUG] [ldap.go:143]: one or more ldapFilter: (sAMAccountName=test)
May  1 12:22:25 172.18.0.1 ui[2890]: 2017-05-01T16:22:25Z [DEBUG] [ldap.go:206]: Current ldap entry attr name: cn
May  1 12:22:25 172.18.0.1 ui[2890]: 2017-05-01T16:22:25Z [DEBUG] [ldap.go:206]: Current ldap entry attr name: sAMAccountName
May  1 12:22:25 172.18.0.1 ui[2890]: 2017-05-01T16:22:25Z [DEBUG] [ldap.go:80]: username: test, dn: CN=test,OU=Remote_users,OU=<>,OU=IT,DC=domain,DC=com
May  1 12:22:25 172.18.0.1 ui[2890]: 2017-05-01T16:22:25Z [DEBUG] [ldap.go:280]: username:test,email:

**Comment by TheJohnCollier** [comment]
update - typo:
ldap_url = ldaps://dc1.domain.com:3269

**Comment by reasonerjt** [comment]
Hi, thanks for reporting the issue.  But I can't reproduce the issue, user can login when the CN has a space in my env:

May  2 10:57:08 172.18.0.1 ui[762]: 2017-05-02T02:57:08Z [DEBUG] [authenticator.go:59]: Current AUTH_MODE is ldap_auth
May  2 10:57:08 172.18.0.1 ui[762]: 2017-05-02T02:57:08Z [DEBUG] [ldap.go:143]: one or more ldapFilter: (samaccountName=jim.green)
May  2 10:57:08 172.18.0.1 ui[762]: 2017-05-02T02:57:08Z [DEBUG] [ldap.go:206]: Current ldap entry attr name: cn
May  2 10:57:08 172.18.0.1 ui[762]: 2017-05-02T02:57:08Z [DEBUG] [ldap.go:206]: Current ldap entry attr name: sAMAccountName
May  2 10:57:08 172.18.0.1 ui[762]: 2017-05-02T02:57:08Z [DEBUG] [ldap.go:80]: username: jim.green, dn: CN=jim green,OU=ATC,DC=harbor,DC=com
May  2 10:57:08 172.18.0.1 ui[762]: 2017/05/02 02:57:08 #033[1;34m[router.go:829][D] | POST       | /login                                   | 37.450174ms      | match      | /login                                   | #033[0m
May  2 10:57:09 172.18.0.1 ui[762]: 2017/05/02 02:57:09 #033[1;34m[router.go:829][D] | GET        | /api/users/current                       | 4.327252ms       | match      | /api/users/?:id                          | #033[0m
.....


The 52e error code means "invalid credentials" if you are very sure you are using the correct password, then if you can clarify the meaning of the error code "DSID-0C0903D9"

**Comment by TheJohnCollier** [comment]
I think I stumbled across the real issue.  I did some wireshark traces and discovered that some users can log in fine and my account could not.  The wireshark traces shows:
   LDAPMessage bindRequest(2) "CN=John Collier,OU=<>,OU=<>=IT,DC=domain,DC=com" simple
   messageID: 2
   protocolOp: bindRequest (0)
      bindRequest
         version: 3
             name: CN=John Collier,OU=<>,OU=<>=IT,DC=domain,DC=com
             authentication: simple (0)
                 simple: 0p

then a bind failure with invalid credentials.  The password is 16 characters long but only shows 2 characters in wireshark.  Logging in with another user, I see the full password.

The third character is a semi-colon (;).  I redid the password to have the ; in another location in the password and the pattern followed.  The password truncates at the ;

My test account didn't have this password which led me to believe it was a space issue.

**Comment by reasonerjt** [comment]
@TheJohnCollier 
Thanks for the update.
so I think you are saying the root cause is the ";" in your password?  If you remove it can you login without problems?

**Comment by reasonerjt** [comment]
I can reproduce the issue, the root cause is UI, he should encode the value in the form.

**Comment by TheJohnCollier** [comment]
Thanks very much.  I appreciate the work.
John

John Collier
Ball Aerospace and Techologies Corp
937-320-6941 (office)
