### ISSUE TITLE
API to query whether an image exists?

### ISSUE THREAD

**Issue by colachg** [vmware/harbor#2195]
As the title, I want to know if there are some apis to query existence of an image before I push it to repo. And other apis to operate images and repos.

**Comment by ywk253100** [comment]
Harbor has APIs described in https://github.com/vmware/harbor/blob/master/docs/swagger.yaml. 
And you can call registry APIs directly if Harbor's APIs can not meet your requirement.
Note: The APIs of Harbor are not stable now, there may be some modifications in the future.
