### ISSUE TITLE
Need commands to perform Harbor operations through CLI

### ISSUE THREAD

**Issue by lgayatri** [vmware/harbor#2199]
I have an integrated OVA and was trying to automate the harbor operations. Tried https://github.com/tobegit3hub/harbor-py for the same but hit https://github.com/tobegit3hub/harbor-py/issues/4.

 It will be helpful to have equivalent cli commands for harbor to help automation. Any guidance here is appreciated.

Pasting the reported error that I sae using harbor-py:
root@Ubuntu-VIc:/home/vmlib/VIC/VIC/admiral-cli-0.9.1/bin/linux-i386# python test.py
Traceback (most recent call last):
File "test.py", line 7, in 
client = harborclient.HarborClient(host, user, password)
File "/usr/local/lib/python2.7/dist-packages/harborclient/harborclient.py", line 17, in init
self.session_id = self.login()
File "/usr/local/lib/python2.7/dist-packages/harborclient/harborclient.py", line 26, in login
'password': self.password})
File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 110, in post
return request('post', url, data=data, json=json, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.133.154.169', port=80): Max retries exceeded with url: /login (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fb90be1e110>: Failed to establish a new connection: [Errno 110] Connection timed out',))
Exception AttributeError: "'HarborClient' object has no attribute 'session_id'" in <bound method HarborClient.del of <harborclient.harborclient.HarborClient object at 0x7fb90bdfaf50>> ignored
root@Ubuntu-VIc:/home/vmlib/VIC/VIC/admiral-cli-0.9.1/bin/linux-i386# cat test.py
from harborclient import harborclient

host = "10.133.154.169"
user = "admin"
password = "Admin!23"

client = harborclient.HarborClient(host, user, password)

client.get_projects()
client.get_users()
client.get_statistics()
client.get_top_accessed_repositories()
client.search("library")

**Comment by wy65701436** [comment]
the latest code is as master branch.

Usage:
client = harborclient.HarborClient(host, user, password)
client .login()
client.get_projects()
client.logout()

**Comment by lgayatri** [comment]
Issue has been verified with the latest code from master and it works as expected. For https,  protocol should be passed as http is default

client = harborclient.HarborClient(host, user, password,protocol="https")
Testcode:
cat HarborSmallScale.py
from harborclient import harborclient
host = "10.133.151.101"
user = "admin"
password = "Admin!23"
client = harborclient.HarborClient(host, user, password,protocol="https")
client.login()
print client.get_top_accessed_repositories()

python HarborSmallScale.py
[{u'count': 2, u'name': u'library/busybox'}, {u'count': 2, u'name': u'library/nginx'}, {u'count': 2, u'name': u'library/redis'}, {u'count': 0, u'name': u'library/alpine'}, {u'count': 0, u'name': u'library/elasticsearch'}, {u'count': 0, u'name': u'library/logstash'}, {u'count': 0, u'name': u'library/mongo'}, {u'count': 0, u'name': u'library/mysql'}, {u'count': 0, u'name': u'library/registry'}, {u'count': 0, u'name': u'library/ubuntu'}]
