### ISSUE TITLE
I use Harbor as docker hub mirror，when I log in harbor and push mirror into harbor it not work

### ISSUE THREAD

**Issue by kinglion811** [vmware/harbor#220]
I have config the harbor registry config.yml ,I add proxy like this:
proxy:
  remoteurl: https://registry-1.docker.io
 
at the same time,I change my docker config 
ExecStart=/usr/bin/docker daemon -H fd:// -D  --registry-mirror=http://10.10.219.231 --insecure-registry 10.10.219.231
the ip 10.10.219.231 is the harbor servr ip
when I login harbor and push image to harbor it not work:
[root@10-10-235-166 docker.service.d]# docker push 10.10.219.231/lxhtest/nginx
The push refers to a repository [10.10.219.231/lxhtest/nginx]
5f70bf18a086: Retrying in 5 seconds 
e7a7429c13b8: Retrying in 5 seconds 
cc066b45d597: Retrying in 5 seconds 
6eb35183d3b8: Retrying in 5 seconds

**Comment by reasonerjt** [comment]
@kinglion811 do you see the same issue if you remove the mirror and proxy settings?

**Comment by kinglion811** [comment]
If I remove the proxy,this issue will not appear

**Comment by reasonerjt** [comment]
We haven't tried to configure Harbor as a mirror, so the functionality was only verified by some guys in community, you can see there are a few issues opened in this area
We will try it later and figure out what works and what doesn't.

This issue is expected to remain open until we clarify it.

**Comment by kinglion811** [comment]
ok

**Comment by kinglion811** [comment]
I think this issuse  [](https://github.com/docker/distribution/issues/1218) may explain

**Comment by kinglion811** [comment]
I think this issuse may explain this question
[](https://github.com/docker/distribution/issues/1218)

**Comment by reasonerjt** [comment]
Yes I'll keep it open and add comments to it.

**Comment by kinglion811** [comment]
I think this issuse may explain this question

https://github.com/docker/distribution/issues/1218

**Comment by xiaods** [comment]
A proxy registry cannot currently accept pushes until image provenance is fully worked out.

**Comment by reasonerjt** [comment]
yep I see in the doc of docker that currently push to a mirror registry is not supported:
https://docs.docker.com/registry/configuration/
> Proxy enables a registry to be configured as a pull through cache to the official Docker Hub. See mirror for more information. Pushing to a registry configured as a pull through cache is currently unsupported

.
