### ISSUE TITLE
Internal server error in LDAP mode

### ISSUE THREAD

**Issue by hainingzhang** [vmware/harbor#2203]
1.1.1-rc2, 

when in LDAP auth_mode, the user is not logged in, use docker pull to pull a public image gets 500 internal Server Error.

Error response from daemon: Get https://ipaddress/v2/harborrelease/harborgo/manifests/1.6.2: received unexpected HTTP status: 500 Internal Server Error

**Comment by reasonerjt** [comment]
This is due to ldap returns an Error when searching.

**Comment by sstine** [comment]
Unfortunately I'm seeing this as well. Why is the issue closed? Is it not a goal to support anonymous pulls when using LDAP authentication?
