### ISSUE TITLE
Users page should be paginated

### ISSUE THREAD

**Issue by cbarzu** [vmware/harbor#2206]
Hi everybody,

I cannot access https://example.com/harbor/users because we have a lot of users ( ~ 4000) and my laptop freeze everytime I access it. 

That list should be paginated. It's not a big problem but it would be a great improvement.

This happens to me under version 1.1.1-rc1.

Regards,
Claudiu

**Comment by steven-zou** [comment]
@cbarzu 

  We'll take a look. Thanks for raising the issue.

**Comment by steven-zou** [comment]
@ywk253100 

  Please prepare and enhance the api to support server driven pagination now.

**Comment by steven-zou** [comment]
Currently, no pagination cause serious performance problem which relevant with Clarity issue vmware/clarity#913.

**Comment by ywk253100** [comment]
@steven-zou OK. Got it.

**Comment by steven-zou** [comment]
Code merged, close this issue.

**Comment by cbarzu** [comment]
Thank you @steven-zou :)
