### ISSUE TITLE
harbor_adminserver always restarting,can't open web

### ISSUE THREAD

**Issue by Hackeruncle** [vmware/harbor#2208]
adminserver[14789]: 2017-05-04T03:09:55Z [INFO] initializing system configurations...
adminserver[14789]: 2017-05-04T03:09:55Z [INFO] the path of json configuration storage: /etc/adminserver/config/config.json
adminserver[14789]: 2017-05-04T03:09:55Z [DEBUG] [driver_json.go:46]: path of configuration file: /etc/adminserver/config/config.json
adminserver[14789]: 2017-05-04T03:09:55Z [INFO] the path of key used by key provider: /etc/adminserver/key
adminserver[14789]: 2017-05-04T03:09:55Z [INFO] configurations read from storage driver are null, will load them from environment variables
adminserver[14789]: 2017-05-04T03:09:55Z [FATAL] [main.go:46]: failed to initialize the system: read /etc/adminserver/key: is a directory

**Comment by Hackeruncle** [comment]
/etc/adminserver/config/config.json
/etc/adminserver/key
can't init.
I manaual mkdir the dir /etc/adminserver/ and /etc/adminserver/config, 
use these command:
docker-compose down;
./prepare;
docker-compose up -d;

always thses exception.

**Comment by ywk253100** [comment]
Run commands:
docker-compose down
rm -r /data/secretkey
./prepare
docker-compose up -d

**Comment by Hackeruncle** [comment]
@ywk253100  ,I run these commands, still harbor_adminserver restarting, i check the log:
[INFO] initializing system configurations...
[INFO] the path of json configuration storage: /etc/adminserver/config/config.json
[DEBUG] [driver_json.go:46]: path of configuration file: /etc/adminserver/config/config.json
[INFO] the path of key used by key provider: /etc/adminserver/key
[INFO] configurations read from storage driver are null, will load them from environment variables
[FATAL] [main.go:46]: failed to initialize the system: read /etc/adminserver/key: is a directory

**Comment by Hackeruncle** [comment]
@ywk253100   the /etc/adminserver/config/config.json and /etc/adminserver/key , what command is created?

**Comment by ywk253100** [comment]
The file /data/secretkey is generated by prepare script and is mounted into adminserver container as /etc/adminserver/key. So you should make sure the /data/secretkey is generated successfully after running prepare script.

**Comment by Hackeruncle** [comment]
@ywk253100 Thanks,it's ok.

I modify the path of secretkey storage in harbor.cfg,as follow:
**secretkey_path = /usr/local/harbor/data** , so cause this above error.
Now i recover the parameter of **secretkey_path = /data**, so harbor_adminserver is up.

And I think that the harbor code should have an error ,can't auto read the  the parameter of **secretkey_path** in initing of using “./prepare”.

**Comment by ywk253100** [comment]
Yes, there is already an issue #2134 to track this.

**Comment by jmarceli** [comment]
To summarize: as for now **secretkey_path** in **harbor.cfg** should never be changed or if you have to change it you should remember to adjust paths in **docker-compose.yml** manually because they are hardcoded.
