### ISSUE TITLE
It take too much time in getting notary signature status

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#2217]
1.1.1 rc3

It will take too much time to get notary status (windows firefox and linux platform firefox chromium)
![nnnnn](https://cloud.githubusercontent.com/assets/23101283/25694005/e897a924-30de-11e7-93b9-96676ff6f5c3.PNG)

**Comment by steven-zou** [comment]
API will take charge of calling signature backend services and reorganize the tag data. Close this one.
