### ISSUE TITLE
When click [test connection] button in Replication tab,the error is "failed to ping endpoint."

### ISSUE THREAD

**Issue by Hackeruncle** [vmware/harbor#2221]
Docker Compose: 1.13.0
Harbor: v1.1.1-rc2

1.A machine 192.168.1.101  : docker+harbor
2.B machine 192.168.1.102  : docker+harbor
3.Login A machine, click Replication tab, and click "+ENDPOINT", fill in a form:
**Endpoint Name:**  _Bwarehouse_replication_ 
**Endpoint Name:**  _https://192.168.1.102_
**Username:** _admin_
**Password:** _Harbor12345_

and click [test connection] button in Replication tab,**the error is "failed to ping endpoint."**

**Comment by Hackeruncle** [comment]
[root@192.168.1.101 2017-05-04]# ll
total 100
-rw-r----- 1 docker 16  5964 May  4 16:11 adminserver.log
-rw-r----- 1 docker 16   389 May  4 16:01 anacron.log
-rw-r----- 1 docker 16   220 May  4 16:01 CROND.log
-rw-r----- 1 docker 16  2048 May  4 15:07 jobservice.log
-rw-r----- 1 docker 16 13168 May  4 15:07 mysql.log
-rw-r----- 1 docker 16 23423 May  4 16:12 proxy.log
-rw-r----- 1 docker 16 10634 May  4 15:59 registry.log
-rw-r----- 1 docker 16   166 May  4 16:01 run-parts.log
-rw-r----- 1 docker 16 21009 May  4 16:11 ui.log

which log should i see?

**Comment by Hackeruncle** [comment]
I check ui.log, as follow:
May  4 16:52:20 172.18.0.1 ui[25985]: 2017/05/04 08:52:20 #033[1;34m[router.go:829][D] | GET        | /api/targets/1/policies                  | 3.051479ms       | match      | /api/targets/:id([0-9]+)/policies/       | #033[0m
May  4 16:52:20 172.18.0.1 ui[25985]: 2017/05/04 08:52:20 #033[1;34m[router.go:829][D] | GET        | /api/targets/1                           | 2.131332ms       | match      | /api/targets/:id([0-9]+)                 | #033[0m

**Comment by ywk253100** [comment]
Do you use self-sign certificate? If yes, you should uncheck "Verify Remote Cert" on configuration web page.
If the problem can not be resolved, please provide all logs in ui.log.

**Comment by Hackeruncle** [comment]
I uncheck "Verify Remote Cert" on configuration  two machine web page.
I try to do it ,also this above error.
the log:
[ui.txt](https://github.com/vmware/harbor/files/975673/ui.txt)

**Comment by ywk253100** [comment]
It seems that the request is not sent to the backend server. Can you open the console of browser to check if there is an error?

**Comment by Hackeruncle** [comment]
@ywk253100 Thanks,It'ok.

**Cause:**  the two herbor-ui containers, can't ping the hostname or ip each other.

**Solution:**  **_the two herbor-ui containers are do these steps:_**
**1.login herbor-ui container**
$ docker exec -it herbor-ui /bin/bash

**2.add the "nameserver 192.168.0.9" from the  /etc/resolv.conf of the machine** 
sh-4.3# vi /etc/resolv.conf 
#add the nameserver  from the  /etc/resolv.conf of the machine 
nameserver 192.168.0.9

**3.add the "ip hostname" from the /etc/hosts of the machine** 
sh-4.3# vi /etc/hosts
192.168.1.101 hadoop1.com
192.168.1.102 hadoop2.com

**4.use curl command to ping the hostname or ip**
sh-4.3# curl hadoop1.com
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.11.5</center>
</body>
 </html>

sh-4.3# curl 192.168.1.101
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.11.5</center>
</body>
</html>

**5.Login A machine, click Replication tab, and click "+ENDPOINT", fill in a form:**
Endpoint Name: Bwarehouse_replication
Endpoint Name: https://192.168.1.102
Username: admin
Password: Harbor12345

and click [test connection] button in Replication tab,
**## the message is "Connection tested successfully."**

**Comment by Hackeruncle** [comment]
close this issue.

**Comment by reasonerjt** [comment]
So the issue is connectivity of your env?
@ywk253100 I think we should log the timeout issue for better debugability...

**Comment by ywk253100** [comment]
@reasonerjt Open #2234 to track this.
