### ISSUE TITLE
services persisting a reboot of VM

### ISSUE THREAD

**Issue by steveschofield** [vmware/harbor#2227]
I'm running 1.1.1.rc3 installation went fine, rebooted VM now the web interface not coming up.  Is the OVA appliance been deprecated in favor of just running docker containers?  In regular VM's, there are services to start, how to persist a reboot in the new brave world of docker images?

**Comment by reasonerjt** [comment]
You can write a start script, and hook it to your init system.
the .ova is not maintained as Harbor will be shipped with other components, and we decided to only provide all-in-one ova.

**Comment by reasonerjt** [comment]
Closing.
