### ISSUE TITLE
configure replication,but delete a image on web, not sync to the other harbor node

### ISSUE THREAD

**Issue by Hackeruncle** [vmware/harbor#2238]
I have been configured  the two harbor replication, test push image, 
the image can be replicated each other.
But I delete a image on hadoop1.com web, not sync to the hadoop2.com.

## **The delete job log:**
2017-05-05T09:09:24Z [INFO] initialization completed: repository: testproject/hello-world, tags: [latest], destination URL: https://hadoop1.com, insecure: true, destination user: admin
_2017-05-05T09:09:24Z [WARNING] repository testproject/hello-world does not exist on https://hadoop1.com_

**Comment by Hackeruncle** [comment]
[root@hadoop2 harbor]# docker pull hadoop36.jiuye/testproject/hello-world
Using default tag: latest
latest: Pulling from testproject/hello-world
983bfa07a342: Pull complete 
Digest: sha256:2075ac87b043415d35bb6351b4a59df19b8ad154e578f7048335feeb02d0f759
Status: Downloaded newer image for hadoop36.jiuye/testproject/hello-world:latest
[root@hadoop2 harbor]# docker images
REPOSITORY                               TAG                 IMAGE ID            CREATED             SIZE
vmware/harbor-jobservice                 v1.1.1-rc2          ff9f04244dfb        6 days ago          163 MB
vmware/harbor-ui                         v1.1.1-rc2          3966a39f9cc6        6 days ago          183 MB
vmware/harbor-adminserver                v1.1.1-rc2          fabdeab472a3        6 days ago          142 MB
vmware/harbor-db                         v1.1.1-rc2          ca166fa6033c        6 days ago          329 MB
vmware/harbor-notary-db                  mariadb-10.1.10     64ed814665c6        4 weeks ago         324 MB
vmware/nginx                             1.11.5-patched      8ddadb143133        4 weeks ago         199 MB
vmware/notary-photon                     signer-0.5.0        b1eda7d10640        5 weeks ago         156 MB
vmware/registry                          photon-2.6.0        6cb4438d7197        6 weeks ago         146 MB
vmware/notary-photon                     server-0.5.0        6e2646682e3c        6 weeks ago         157 MB
vmware/harbor-log                        v1.1.1-rc2          9c46a7b5e517        2 months ago        192 MB
hadoop2.com/testproject/hello-world   latest              48b5124b2768        3 months ago        1.84 kB
photon                                   1.0                 e6e4e4a2ba1b        10 months ago       128 MB
[root@hadoop2 harbor]# 


on hadoop2.com machine, I use docker pull from hadoop2.com/testproject/hello-world , is successful.
So hadoop2.com have exist the testproject/hello-world image.

**Comment by reasonerjt** [comment]
Thanks for reporting, will provide a fix.

**Comment by ywk253100** [comment]
Fixed by #2240 .
