### ISSUE TITLE
Proposal: ldapFilter don't check "ldapUID="

### ISSUE THREAD

**Issue by fjpqzm** [vmware/harbor#2247]
docker-engine: Docker version 17.04.0-ce, build 4845c56
harbor: v1.1.1-rc4

1、harbor.cfg
ldap_url = ldap://ldap.example.com
ldap_searchdn = cn=ldap-reader,ou=users,dc=example,dc=com
ldap_search_pwd = ldap-reader
ldap_basedn = ou=users,dc=dc=example,dc=com
ldap_filter = (&(objectclass=inetorgperson)(memberof=cn=harbor-users,ou=groups,dc=example,dc=com))
ldap_uid = cn
ldap_scope = 3
ldap_timeout = 5

openldap config:
    /dc=example,dc=com
       /ou=groups,dc=example,dc=com
            /cn=harbor-users,ou=groups,dc=example,dc=com  (objectClass=groupOfNames)
       /ou=users,dc=example,dc=com
            /cn=user1,ou=users,dc=example,dc=com (objectClass=inetOrgPerson)

2、UI error log
May  7 00:36:05 172.30.2.1 ui[843]: 2017-05-06T16:36:05Z [DEBUG] [authenticator.go:59]: Current AUTH_MODE is ldap_auth
May  7 00:36:05 172.30.2.1 ui[843]: 2017-05-06T16:36:05Z [DEBUG] [ldap.go:143]: one or more ldapFilter: (&(objectclass=inetOrgPerson)(memberof=cn=harbor-users,ou=groups,dc=example,dc=com))
May  7 00:36:05 172.30.2.1 ui[843]: 2017-05-06T16:36:05Z [DEBUG] [ldap.go:206]: Current ldap entry attr name: cn
May  7 00:36:05 172.30.2.1 ui[843]: 2017-05-06T16:36:05Z [DEBUG] [ldap.go:206]: Current ldap entry attr name: mail
May  7 00:36:05 172.30.2.1 ui[843]: 2017-05-06T16:36:05Z [DEBUG] [ldap.go:206]: Current ldap entry attr name: cn
May  7 00:36:05 172.30.2.1 ui[843]: 2017-05-06T16:36:05Z [DEBUG] [ldap.go:206]: Current ldap entry attr name: mail
May  7 00:36:05 172.30.2.1 ui[843]: 2017-05-06T16:36:05Z [DEBUG] [ldap.go:206]: Current ldap entry attr name: cn
May  7 00:36:05 172.30.2.1 ui[843]: 2017-05-06T16:36:05Z [DEBUG] [ldap.go:206]: Current ldap entry attr name: mail
May  7 00:36:05 172.30.2.1 ui[843]: 2017-05-06T16:36:05Z [WARNING] Found more than one entry.

3、find ldap
 common/utils/ldap/ldap.go 133:141
` if ldapFilter == "" {
		ldapFilter = "(" + ldapUID + "=" + filterTag + ")"
	} else {
		if !strings.Contains(ldapFilter, ldapUID+"=") {
			ldapFilter = "(&" + ldapFilter + "(" + ldapUID + "=" + filterTag + "))"
		} else {
			ldapFilter = strings.Replace(ldapFilter, ldapUID+"=*", ldapUID+"="+filterTag, -1)
		}
	}
`
=> 
`if ldapFilter == "" {
		ldapFilter = "(" + ldapUID + "=" + filterTag + ")"
	} else {
		ldapFilter = "(&" + ldapFilter + "(" + ldapUID + "=" + filterTag + "))"
	}
`
Don't check ldapUID!!!

**Comment by stonezdj** [comment]
Fixed in PR https://github.com/vmware/harbor/pull/3683
