### ISSUE TITLE
Password validator is broken, long passwords are not allowed

### ISSUE THREAD

**Issue by jryberg** [vmware/harbor#2251]
This is a pure GUI/API issue, running Harbor 1.1.1 rc-3, not docker related, ignoring that part of requested info.

If you create a new user and put a valid password, upper, lower, number but it's little longer than "normal" then it will not allow you to save the user. 

I tried to use a 24 character password and the validator told me I don't follow minimal requirements. 

I removed a couple of characters and I was able to create the new user. 

If there are a limit of the password length then it would be nice to be notified =)

**Comment by steven-zou** [comment]
@jryberg 

  Thanks for raising issue to us.

  If I understand correctly, you mean the validation tooltips for the limitation of password length is not explicit, right?
  
  If right, about the tooltip, we'll use more explicit messages in future releases.

**Comment by jryberg** [comment]
Hi @steven-zou,

Yes, the tooltip/input control will mark the password as invalid if the string is to long.

**Comment by steven-zou** [comment]
Code merged #2315
