### ISSUE TITLE
[harbor] [issue] failed to install harbor on kubernetes

### ISSUE THREAD

**Issue by wang990099** [vmware/harbor#2261]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.  
Q: N/A

2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
Q:  just modify hostname

3)Log files, you can get them by package the /var/log/harbor/ .
Q: attached k8s log

2017-05-09T03:46:32.392745498Z 2017-05-09T03:46:32Z [ERROR] [utils.go:94]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp: lookup adminserver: Temporary failure in name resolution

I have followed setup harbor with "Integration with Kubernetes", meanwhile I didn't find run "adminserver" container in the guideline. Could you give some comments? thank you in advance.

**Comment by reasonerjt** [comment]
Hi,
The K8S installation guide is maintained by community and it does not work with the latest code.

**Comment by wang990099** [comment]
thanks a lot, I have also got reply from kira. you're right, that part code didn't update for long time, meanwhile it isn't suitable to the latest code. that code just work on 0.4-0.5 harbor versions.
