### ISSUE TITLE
Support multiple  storage backends 

### ISSUE THREAD

**Issue by int32bit** [vmware/harbor#227]
Until now, Our image can only be stored in local file system with default setting. In fact, the `Docker Registry` can support multiple storage backends, like `Swift`, `S3`, `Ceph`,etc. See [docker-distribution](https://github.com/docker/distribution/blob/master/docs/storagedrivers.md). I'd like to introduce it to `harbor`, and we can easily initial our configuration in `harbor.cfg`. It may be useful for those who has deployed `Openstack` platform and need to integrate with `Swift`. Thanks!

**Comment by int32bit** [comment]
I can try to implement it if my idea can be accepted! 😄

**Comment by reasonerjt** [comment]
@int32bit so you are suggesting introducing a template for config.yml and render it in "prepare" ?

**Comment by int32bit** [comment]
@reasonerjt  Yes, but I think the template is a little inflexible, and it's difficult to append new config item. That may make it hard to extend in the future. I'd like to move `config.yaml` to the root of `Deploy`, instead rendering by machine, user can modify it manually.  @hainingzhang

**Comment by reasonerjt** [comment]
@int32bit Thanks for updating the doc.  So is there any work remained for this issue?

**Comment by reasonerjt** [comment]
@int32bit I'm closing the issue, feel free to re-open if you think something's missing.
