### ISSUE TITLE
Loading /harbor/users page takes about 80+ seconds time to load with just 350 users 

### ISSUE THREAD

**Issue by lgayatri** [vmware/harbor#2281]
I have 350 users on harbor and the web page takes about 80+ seconds to load 350 users. This is a long time and needs to be improved.

**Comment by reasonerjt** [comment]
@steven-zou please investigate why it took so long on UI?

**Comment by lgayatri** [comment]
Logs attached:
[harborLogs.zip](https://github.com/vmware/harbor/files/989307/harborLogs.zip)

**Comment by steven-zou** [comment]
Will do investigation.

Please note that, we'll enable pagination for user list in next version.

**Comment by steven-zou** [comment]
The root cause might be from the drop down action of each item (ellipsis). Raise issue to Clarity team. https://github.com/vmware/clarity/issues/913.

We'll also enable pagination for all the datagrid.

**Comment by steven-zou** [comment]
Request pagination feature for next release.

**Comment by steven-zou** [comment]
Please use #2206 to track the pagination for user list and related performance issue caused by no pagination.

For this one, to avoid duplicated problems, I'll close this one.
