### ISSUE TITLE
docker login  404

### ISSUE THREAD

**Issue by post707** [vmware/harbor#2285]
Note: golang version: 1.8.1
Note: docker version: 1.12.3
Note: docker-compose version: 1.13.0
---------------------------------------------------
## Configuration file of Harbor

#The IP address or hostname to access admin UI and registry service.
#DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
hostname = reg.delery.online

#The protocol for accessing the UI and token/notification service, by default it is http.
#It can be set to https if ssl is enabled on nginx.
ui_url_protocol = https

#The password for the root user of mysql db, change this before any production use.
db_password = root123

#Maximum number of job workers in job service  
max_job_workers = 3 

#Determine whether or not to generate certificate for the registry's token.
#If the value is on, the prepare script creates new root cert and private key 
#for generating token to access the registry. If the value is off the default key/cert will be used.
#This flag also controls the creation of the notary signer's cert.
customize_crt = on

#The path of cert and key files for nginx, they are applied only the protocol is set to https
ssl_cert = /certs/server.crt
ssl_cert_key = /certs/server.key

#The path of secretkey storage
secretkey_path = /data

#Admiral's url, comment this attribute, or set its value to NA when Harbor is standalone
admiral_url = NA

#NOTES: The properties between BEGIN INITIAL PROPERTIES and END INITIAL PROPERTIES
#only take effect in the first boot, the subsequent changes of these properties 
#should be performed on web ui

#************************BEGIN INITIAL PROPERTIES************************

#Email account settings for sending out password resetting emails.

#Email server uses the given username and password to authenticate on TLS connections to host and act as identity.
#Identity left blank to act as username.
email_identity = 

email_server = smtp.mydomain.com
email_server_port = 25
email_username = sample_admin@mydomain.com
email_password = abc
email_from = admin <sample_admin@mydomain.com>
email_ssl = false

##The initial password of Harbor admin, only works for the first time when Harbor starts. 
#It has no effect after the first launch of Harbor.
#Change the admin password from UI after launching Harbor.
harbor_admin_password = Harbor12345

##By default the auth mode is db_auth, i.e. the credentials are stored in a local database.
#Set it to ldap_auth if you want to verify a user's credentials against an LDAP server.
auth_mode = db_auth

#The url for an ldap endpoint.
ldap_url = ldaps://ldap.mydomain.com

#A user's DN who has the permission to search the LDAP/AD server. 
#If your LDAP/AD server does not support anonymous search, you should configure this DN and ldap_search_pwd.
#ldap_searchdn = uid=searchuser,ou=people,dc=mydomain,dc=com

#the password of the ldap_searchdn
#ldap_search_pwd = password

#The base DN from which to look up a user in LDAP/AD
ldap_basedn = ou=people,dc=mydomain,dc=com

#Search filter for LDAP/AD, make sure the syntax of the filter is correct.
#ldap_filter = (objectClass=person)

# The attribute used in a search to match a user, it could be uid, cn, email, sAMAccountName or other attributes depending on your LDAP/AD  
ldap_uid = uid 

#the scope to search for users, 1-LDAP_SCOPE_BASE, 2-LDAP_SCOPE_ONELEVEL, 3-LDAP_SCOPE_SUBTREE
ldap_scope = 3 

#Timeout (in seconds)  when connecting to an LDAP Server. The default value (and most reasonable) is 5 seconds.
ldap_timeout = 5

#Turn on or off the self-registration feature
self_registration = on

#The expiration time (in minute) of token created by token service, default is 30 minutes
token_expiration = 30

#The flag to control what users have permission to create projects
#The default value "everyone" allows everyone to creates a project. 
#Set to "adminonly" so that only admin user can create project.
project_creation_restriction = everyone

#Determine whether the job service should verify the ssl cert when it connects to a remote registry.
#Set this flag to off when the remote registry uses a self-signed or untrusted certificate.
verify_remote_cert = on

-------------------------------------------------------------------
docker login www.delery.online
Username: test1
Password: 
Error response from daemon: Login: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.11.5</center>
</body>
</html>
 (Code: 404; Headers: map[Server:[nginx/1.11.5] Date:[Thu, 11 May 2017 02:12:43 GMT] Content-Type:[text/html] Content-Length:[169]])
------------------------------------------------------------------
==> ui.log <==
May 11 10:07:29 192.168.16.1 ui[4913]: 2017/05/11 02:07:29 #033[1;34m[router.go:829][D] | GET        | /registryproxy/v2/                       | 645.154µs        | notmatch   | #033[0m
May 11 10:12:42 192.168.16.1 ui[4913]: 2017/05/11 02:12:42 #033[1;34m[router.go:829][D] | GET        | /registryproxy/v2/                       | 801.253µs        | notmatch   | #033[0m
May 11 10:12:43 192.168.16.1 ui[4913]: 2017/05/11 02:12:43 #033[1;34m[router.go:829][D] | GET        | /registryproxy/v2/                       | 1.147312ms       | notmatch   | #033[0m

==> proxy.log <==
May 11 10:12:42 192.168.16.1 proxy[4913]: 106.14.44.62 - "GET /v2/ HTTP/1.1" 404 513 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/3.10.0-514.10.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.3 \x5C(linux\x5C))" 0.002 0.002 .
May 11 10:12:43 192.168.16.1 proxy[4913]: 106.14.44.62 - "GET /v2/ HTTP/1.1" 404 513 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/3.10.0-514.10.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.3 \x5C(linux\x5C))" 0.002 0.002 .
May 11 10:12:43 192.168.16.1 proxy[4913]: 106.14.44.62 - "GET /v1/users/ HTTP/1.1" 404 169 "-" "docker/1.12.3 go/go1.6.3 git-commit/6b644ec kernel/3.10.0-514.10.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.3 \x5C(linux\x5C))" 0.000 - .

**Comment by post707** [comment]
I have to solve~~

**Comment by 472732787** [comment]
why?
