### ISSUE TITLE
Harbor 0.5.0 LDAP high CPU usage

### ISSUE THREAD

**Issue by roldancer** [vmware/harbor#2293]
Hi All, Our AD LDAP are consuming lof of CPU, the LDAP's team suspect that Harbor is generating that high CPU usage, at the Harbor side I don't see any problem, Did someone has this kind of problem using Harbor with AD ?

Many thanks.

**Comment by reasonerjt** [comment]
@roldancer thanks for reporting,
 we didn't see such issue, but there is known connection leak issue in 0.5.0 #1480 

We verified it's fixed in 1.1.1, could you kindly try 1.1.1-rc4 to see if it fixed the CPU issue?

**Comment by cbarzu** [comment]
@reasonerjt do you know if that was solved on 1.1.1-rc1 ?

**Comment by reasonerjt** [comment]
The leak issue? I think it is fixed in 1.1.1-rc1, but rc4 has more fixes.

**Comment by hainingzhang** [comment]
@roldancer did you use any filter? how many users or items are in the AD? I suspect some atttibute of AD is not indexed so that it may take up a long time to search if the size of AD is large.

**Comment by roldancer** [comment]
@hainingzhang  Many thanks for your help

**Comment by reasonerjt** [comment]
@roldancer is this issue fixed?

**Comment by reasonerjt** [comment]
closing, please reopen if you hit the problem again.
