### ISSUE TITLE
release1.1.0——jobservice——nonharbor——registry——delete，code params has a bug

### ISSUE THREAD

**Issue by stoneagle** [vmware/harbor#2297]
ldelete.go
ine130

dstClient, err := newRepositoryClient(d.dstURL, d.insecure, dstCred,
	d.repository, "repository", d.repository, "pull", "push", "*")

func newRepositoryClient(endpoint string, insecure bool, credential auth.Credential,
	tokenServiceEndpoint, repository, scopeType, scopeName string,
	scopeActions ...string) (*registry.Repository, error)

missing tokenServiceEndpoint

**Comment by ywk253100** [comment]
Thanks for this, but the codes are commented and if they are used an error will be found.
