### ISSUE TITLE
internal server error null

### ISSUE THREAD

**Issue by chuqiming** [vmware/harbor#23]
When create an empty project, and enter into this project on the web page, wait for 5 seconds, then an error message pop up, says,
Operation Failed
internal server error null

1. Create a new project test.
2. Click the test project.
3. Wait for 5 seconds, you can see this error message.

Expected behaviour: no error message.

**Comment by wknet123** [comment]
This problem might be caused by misconfiguring in _harbor.cfg_ file.
Make sure you have input correct IP address [**eth0**] as your deployed server in _harbor.cfg_, then execute _prepare.sh_ again, rebuild it by using _docker-compose_ command.

**Comment by chuqiming** [comment]
Thank you. The problem is fixed after setting DNS in /etc/default/docker. I
think harbor.cfg is an alternative solution.

Regards,
DC
