### ISSUE TITLE
Provide an option to delete unwanted projects from Harbor from registry's UI

### ISSUE THREAD

**Issue by lgayatri** [vmware/harbor#2304]
We can create projects in the registry and also need an option to delete unwanted projects from UI.
Please consider this request.

**Comment by reasonerjt** [comment]
As long as the project is "empty" (no images/ no members) it can be removed from UI.

**Comment by ywk253100** [comment]
@lgayatri The feature has been implemented for a long time.

**Comment by lgayatri** [comment]
@ywk253100 and @reasonerjt , I have an integrated OVA environment on which there are empty projects. I dont see an option to delete them.
Setup: https://10.197.37.132/harbor/projects - admin/Admin!23

**Comment by reasonerjt** [comment]
<img width="1147" alt="screen shot 2017-05-14 at 10 51 29 pm" src="https://cloud.githubusercontent.com/assets/2390463/26044234/f4918b20-38f7-11e7-99e8-4b9abf19a891.png">

@lgayatri you need to click the dots at the left of each row to show the list.

We're using Clarity data grid, @steven-zou is it there alternative way to show the "action" list?

**Comment by lgayatri** [comment]
I could not interpret this from the UI. That too it was left click for showing these options and usually  right click is used for options display. This is not user intuitive. Please consider enhancing UI.

**Comment by reasonerjt** [comment]
@steven-zou will drive the discussion with designer and Clairty team, but it may likely remain unchanged in 1.2

**Comment by steven-zou** [comment]
Yeah, we have raise the problem to Clarity team. They will start to consider the improvement. But as @reasonerjt said, might need time to become a reality.

As the deletion action of project does work well, I'll close this issue.

**Comment by lgayatri** [comment]
@steven-zou , can you please let me know the clarity issue# that was raised ?

**Comment by steven-zou** [comment]
@lgayatri 

Here is the issue link https://github.com/vmware/clarity/issues/927
