### ISSUE TITLE
Can't compile harbor_ui in accordance with compile_guide.md.

### ISSUE THREAD

**Issue by m-masataka** [vmware/harbor#2306]
I failed compiling harbor_ui in accordance with docs/compile_guide.md. 
The cause of the failure is following command
```
make install GOBUILDIMAGE=golang:1.7.3 COMPILETAG=compile_golangimage CLARITYIMAGE=vmware/harbor-clarity-ui-builder:0.8.4 NOTARYFLAG=true
```
Current Makefile doesn't support vmware/harbor-clarity-ui-builder version 0.8.4. 
It should be changed 0.8.4 to 1.1.1.

**Comment by wy65701436** [comment]
close it as https://github.com/vmware/harbor/pull/2307
