### ISSUE TITLE
New UI has no vertical scrollbar

### ISSUE THREAD

**Issue by chuqiming** [vmware/harbor#231]
Need add this feature to find all UI elements in a low resolution.

**Comment by xiaods** [comment]
how about get a screen to get know your situation?

**Comment by wknet123** [comment]
I've created a branch named 'new-version-of-ui', you may checkout them, and currently, to visit the new version of UI, the URL is [http://[your_ip_address]/ng](http://[your_ip_address]/ng)

**Comment by chuqiming** [comment]
[image: Inline image 1]

No vertical scrollbar, which leads some words cannot be seen.

**Comment by wknet123** [comment]
New updates has repaired this issue, please checkout the latest codes from branch 'new-version-of-ui'.

**Comment by chuqiming** [comment]
Thank you. I will try soon.

**Comment by reasonerjt** [comment]
Verfied
