### ISSUE TITLE
The pattern of updating project API

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#2313]
Maybe we can change PUT /api/projects/:id([0-9]+)/publicity to PUT /api/projects/:id([0-9]+)?

**Comment by srm912** [comment]
Does this mean that the publicity be toggled? So basically, public -> private and vice versa, right?

**Comment by reasonerjt** [comment]
@srm912 thanks, please go ahead, and this issue will likely be deferred to post-1.2

**Comment by ywk253100** [comment]
Closing due to moving public property into metadata and will provide API to update metadata.
