### ISSUE TITLE
The pattern of getting logs of project API

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#2314]
Currently:
GET /api/projects/:id([0-9]+)/logs/filter?page=1&page_size=3
and username, operation, begin time, end time are all sent in body.

Ideally:
GET /api/projects/:id([0-9]+)/logs
and all query conditions are sent in query string.

**Comment by reasonerjt** [comment]
The query string from UI has to be encoded, if you wanna change that, make sure Steven reviews the change on UI.

**Comment by ywk253100** [comment]
Done.
