### ISSUE TITLE
Need to install docker-compose(1.7.1+) by yourself first and run this script again.

### ISSUE THREAD

**Issue by fffffreedom** [vmware/harbor#2317]
I run the centos 7.2 os in virtualbox.  I  only changed the hostname in harbor.cfg, and run sudo ./install, then error happens:
[Step 0]: checking installation environment ...

Note: docker version: 17.05.0
✖ Need to install docker-compose(1.7.1+) by yourself first and run this script again.
 
[jrq@freedom ~]$ docker --version
Docker version 17.05.0-ce, build 89658be
[jrq@freedom ~]$ docker-compose --version
docker-compose version 1.13.0, build 1719ceb
[jrq@freedom ~]$ uname -a
Linux freedom 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by wy65701436** [comment]
@fffffreedom can you tell the build that you are using? v1.1.1?

**Comment by wy65701436** [comment]
can you help to check the install location of docker-compose, is it in the sudo path? 

If it is installed at /usr/local/bin, please install Harbor with sudo -E env "PATH=$PATH" or you can add local user to docker group, and then install Harbor with the added user.

I will close it, if you still encounter it. Feel free to reopen.

**Comment by fffffreedom** [comment]
@wy65701436 i am using v1.1.1
"sudo -E env "PATH=$PATH" ./install"  works well, 
but when try the second as you said, i add myself to the docker group ( docker:x:388:jrq ) and run ./install, it fails (prearing fail)..

**Comment by sigsbee** [comment]
@fffffreedom 
I think you should make a directory /data and change the ownner of /data to yourself too, by default, harbor stores data in /data, if you want to change it, you need to modify several files.

**Comment by pminnebach** [comment]
[This](https://stackoverflow.com/questions/38775954/sudo-docker-compose-command-not-found) answer on Stackoverflow provided the much needed solution for me:

`sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose`
