### ISSUE TITLE
Add a filter to disable APIs in integration mode

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#2319]

**Comment by reasonerjt** [comment]
What will be returned?  I was thinking we could skip registering the routers.  What's the benefit to filer/block the request in contrast to not registering it?

**Comment by ywk253100** [comment]
@reasonerjt I am not thinking the detail yet, just open this issue to record the task. Maybe we can discuss when I start to do this.

**Comment by ywk253100** [comment]
POST /projects should be supported in integration mode as the jobservice needs it to create project.

**Comment by reasonerjt** [comment]
Oops...

**Comment by ywk253100** [comment]
Done
