### ISSUE TITLE
Registry UI crashes to load 3/5 times with 1000 users 

### ISSUE THREAD

**Issue by lgayatri** [vmware/harbor#2320]
![registry-ui-crash](https://cloud.githubusercontent.com/assets/25006749/26102513/ec8ce8b4-3a52-11e7-8d85-d72863c19d4b.PNG)
Please see the attached screenshot. There are about 1000 users on this registry but the UI fails to load 3/5 times. I will recheck the issue after pagination gets enabled on the harbor/Users.

Browser used : Chrome.
OS used : Windows 2008

**Comment by reasonerjt** [comment]
@steven-zou  I think we can dup this one.

**Comment by steven-zou** [comment]
Duplicated with #2206 and related with vmware/clarity#913.

**Comment by steven-zou** [comment]
We'll support pagination in 1.2. 

As this is a duplicated one, I'll close it.
