### ISSUE TITLE
docker login 404

### ISSUE THREAD

**Issue by zhangchunzhen** [vmware/harbor#2321]
hello：
docker version

Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64
 Experimental: false

vi docker-compose.yml 
`version: '2'
services:
  log:
    image: vmware/harbor-log:v1.1.0
    container_name: harbor-log
    restart: always
    volumes:
      - /var/log/harbor/:/var/log/docker/:z
    ports:
      - 127.0.0.1:1514:514
    networks:
      - harbor
  registry:
    image: vmware/registry:photon-2.6.0
    container_name: registry
    restart: always
    volumes:
      - /data/registry:/storage:z
      - ./common/config/registry/:/etc/registry/:z
    networks:
      - harbor
    environment:
      - GODEBUG=netdns=cgo
    command:
      ["serve", "/etc/registry/config.yml"]
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "registry"
  mysql:
    image: vmware/harbor-db:v1.1.0
    container_name: harbor-db
    restart: always
    volumes:
      - /data/database:/var/lib/mysql:z
    networks:
      - harbor
    env_file:
      - ./common/config/db/env
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "mysql"
  adminserver:
    image: vmware/harbor-adminserver:v1.1.0
    container_name: harbor-adminserver
    env_file:
      - ./common/config/adminserver/env
    restart: always
    volumes:
      - /data/config/:/etc/adminserver/config/:z
      - /data/secretkey:/etc/adminserver/key:z
      - /data/:/data/:z
    networks:
      - harbor
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "adminserver"
  ui:
    image: vmware/harbor-ui:v1.1.0
    container_name: harbor-ui
    env_file:
      - ./common/config/ui/env
    restart: always
    volumes:
      - ./common/config/ui/app.conf:/etc/ui/app.conf:z
      - ./common/config/ui/private_key.pem:/etc/ui/private_key.pem:z
      - /data/secretkey:/etc/ui/key:z
      - /data/ca_download/:/etc/ui/ca/:z
    networks:
      - harbor
    depends_on:
      - log
      - adminserver
      - registry
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "ui"
  jobservice:
    image: vmware/harbor-jobservice:v1.1.0
    container_name: harbor-jobservice
    env_file:
      - ./common/config/jobservice/env
    restart: always
    volumes:
      - /data/job_logs:/var/log/jobs:z
      - ./common/config/jobservice/app.conf:/etc/jobservice/app.conf:z
      - /data/secretkey:/etc/jobservice/key:z
    networks:
      - harbor
    depends_on:
      - ui
      - adminserver
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "jobservice"
  proxy:
    image: vmware/nginx:1.11.5-patched
    container_name: nginx
    restart: always
    volumes:
      - ./common/config/nginx:/etc/nginx:z
    networks:
      - harbor
    ports:
      - 80:80
      - 443:443
      - 4443:4443
    depends_on:
      - mysql
      - registry
      - ui
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "proxy"
networks:
  harbor:
    external: false`

docker-compose ps
   
harbor-adminserver   /harbor/harbor_adminserver       Up                                                                       
harbor-db            docker-entrypoint.sh mysqld      Up      3306/tcp                                                         
harbor-jobservice    /harbor/harbor_jobservice        Up                                                                       
harbor-log           /bin/sh -c crond && rm -f  ...   Up      127.0.0.1:1514->514/tcp                                          
harbor-ui            /harbor/harbor_ui                Up                                                                       
nginx                nginx -g daemon off;             Up      0.0.0.0:443->443/tcp, 0.0.0.0:4443->4443/tcp, 0.0.0.0:80->80/tcp 
registry             /entrypoint.sh serve /etc/ ...   Up      5000/tcp   

docker login 192.168.0.50
Username: admin
Password: 
Error response from daemon: Login: <html>
<head><title>404 Not Found</title></head>
``<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.11.5</center>
</body>
</html>
 (Code: 404; Headers: map[Server:[nginx/1.11.5] Date:[Tue, 16 May 2017 11:07:35 GMT] Content-Type:[text/html] Content-Length:[169]])

**Comment by ywk253100** [comment]
Provide the logs under directory /var/log/harbor/

**Comment by roldancer** [comment]
We had the same problem after migrating from 0.5.0 to 1.1.1, We opened the following ticket  #2302

**Comment by reasonerjt** [comment]
I believe it's not the same issue, we'll track these two separately.

**Comment by zhangchunzhen** [comment]
@ywk253100   

This is my ‘docker login’ log
proxy.log
May 17 09:11:38 172.18.0.1 proxy[13746]: 192.168.0.50 - "GET /v2/ HTTP/1.1" 404 513 "-" "docker/17.05.0-ce go/go1.7.5 git-commit/89658be kernel/3.19.0-25-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.05.0-ce \x5C(linux\x5C))" 0.004 0.004 .
May 17 09:11:38 172.18.0.1 proxy[13746]: 192.168.0.50 - "GET /v2/ HTTP/1.1" 404 513 "-" "docker/17.05.0-ce go/go1.7.5 git-commit/89658be kernel/3.19.0-25-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.05.0-ce \x5C(linux\x5C))" 0.003 0.003 .
May 17 09:11:38 172.18.0.1 proxy[13746]: 192.168.0.50 - "GET /v1/users/ HTTP/1.1" 404 169 "-" "docker/17.05.0-ce go/go1.7.5 git-commit/89658be kernel/3.19.0-25-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.05.0-ce \x5C(linux\x5C))" 0.000 - .

ui.log
May 17 09:11:38 172.18.0.1 ui[13746]: 2017/05/17 01:11:38 #033[1;34m[router.go:829][D] | GET        | /registryproxy/v2/                       | 2.576123ms       | notmatch   | #033[0m
May 17 09:11:38 172.18.0.1 ui[13746]: 2017/05/17 01:11:38 #033[1;34m[router.go:829][D] | GET        | /registryproxy/v2/                       | 1.256586ms       | notmatch   | #033[0m

**Comment by reasonerjt** [comment]
@zhangchunzhen so you are using the master code?

**Comment by zhangchunzhen** [comment]
@reasonerjt   harbor download address  : https://github.com/vmware/harbor/archive/master.zip        
Do you have another download  address ?

**Comment by reasonerjt** [comment]
try using the code/package in release tab.

**Comment by zhangchunzhen** [comment]
@reasonerjt    Thank you very much.

**Comment by BirkhoffLee** [comment]
Did it solve the problem?

**Comment by reasonerjt** [comment]
@BirkhoffLee open another issue and attach log the "/registryproxy" is not in 1.1.1 so you shouldn't see that in the log.
