### ISSUE TITLE
respin the registry image

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#2328]
upgrade to registry 2.6.1 and rebuild the docker image on top of photon 1.0.

This should fix #2302 (which is reported by community user but we can't reproduce)

Another issue is to track the automation work, it should be done sooner: #1729

**Comment by nlowe** [comment]
I just want to chime in that I wasn't able to push windows container images without manually changing the `docker-compose.yml` to use `vmware/registry:2.6.1-photon`. The registry would return an unknown blob error. I tried applying the workaround mentioned in docker/distribution#2232 but that did not seem to have any effect.

**Comment by reasonerjt** [comment]
Fixed in 1.1.0 branch.

**Comment by reasonerjt** [comment]
@nlowe So were you able to do it with 0.5.0?

**Comment by nlowe** [comment]
@reasonerjt We have not tested with `0.5.0` as we started looking into this project only a few days ago. I can try it if you'd like though.

**Comment by reasonerjt** [comment]
@nlowe , that would be nice, please open an other issue to let us know.
