### ISSUE TITLE
Error JS error with latest code when to execute UI tests.

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#2336]
I am using phantomjs to run UI tests, but get the following error with the latest code.

1:25:15.489 INFO - Executing: [get: http://localhost])
[ERROR - 2017-05-18T08:25:15.718Z] Session [84e41e60-3ba3-11e7-a2fa-6331d7cea211] - page.onError - msg: ReferenceError: Can't find variable: Map

  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-05-18T08:25:15.719Z] Session [84e41e60-3ba3-11e7-a2fa-6331d7cea211] - page.onError - stack:
  c (http://localhost/static/custom-elements.min.js:10)
  (anonymous function) (http://localhost/static/custom-elements.min.js:22)

  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-05-18T08:25:15.729Z] Session [84e41e60-3ba3-11e7-a2fa-6331d7cea211] - page.onError - msg: TypeError: undefined is not a function (evaluating 'template.startsWith("<svg")')

  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-05-18T08:25:15.729Z] Session [84e41e60-3ba3-11e7-a2fa-6331d7cea211] - page.onError - stack:
  validateTemplate (http://localhost/static/clarity-icons.min.js:1)
  setIconTemplate (http://localhost/static/clarity-icons.min.js:1)
  add (http://localhost/static/clarity-icons.min.js:1)
  (anonymous function) (http://localhost/static/clarity-icons.min.js:2)
  l (http://localhost/static/clarity-icons.min.js:1)
  i (http://localhost/static/clarity-icons.min.js:1)
  (anonymous function) (http://localhost/static/clarity-icons.min.js:1)
  (anonymous function) (http://localhost/static/clarity-icons.min.js:13)
  l (http://localhost/static/clarity-icons.min.js:1)
  a (http://localhost/static/clarity-icons.min.js:1)
  p (http://localhost/static/clarity-icons.min.js:1)
  (anonymous function) (http://localhost/static/clarity-icons.min.js:1)
  (anonymous function) (http://localhost/static/clarity-icons.min.js:13)
  (anonymous function) (http://localhost/static/clarity-icons.min.js:1)

  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-05-18T08:25:16.126Z] Session [84e41e60-3ba3-11e7-a2fa-6331d7cea211] - page.onError - msg: TypeError: undefined is not an object (evaluating 'c.a')

  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-05-18T08:25:16.127Z] Session [84e41e60-3ba3-11e7-a2fa-6331d7cea211] - page.onError - stack:
  l (http://localhost/static/custom-elements.min.js:11)
  createElement (http://localhost/static/custom-elements.min.js:20)
  i (http://localhost/static/build.min.js:47)
  setDocument (http://localhost/static/build.min.js:47)
  (anonymous function) (http://localhost/static/build.min.js:48)
  (anonymous function) (http://localhost/static/build.min.js:48)
  (anonymous function) (http://localhost/static/build.min.js:47)
  (anonymous function) (http://localhost/static/build.min.js:47)
  e (http://localhost/static/build.min.js:1)
  (anonymous function) (http://localhost/static/build.min.js:47)

  phantomjs://platform/console++.js:263 in error
01:25:16.305 INFO - Done: [get: http://localhost]
01:25:16.309 INFO - Executing: [set window size])
01:25:16.357 INFO - Done: [set window size]
01:25:16.361 INFO - Executing: [delete all cookies])
01:25:16.412 INFO - Done: [delete all cookies]
01:25:18.418 INFO - Executing: [refresh])
[ERROR - 2017-05-18T08:25:18.861Z] Session [84e41e60-3ba3-11e7-a2fa-6331d7cea211] - page.onError - msg: ReferenceError: Can't find variable: Map

  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-05-18T08:25:18.862Z] Session [84e41e60-3ba3-11e7-a2fa-6331d7cea211] - page.onError - stack:
  c (http://localhost/static/custom-elements.min.js:10)
  (anonymous function) (http://localhost/static/custom-elements.min.js:22)

  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-05-18T08:25:18.884Z] Session [84e41e60-3ba3-11e7-a2fa-6331d7cea211] - page.onError - msg: TypeError: undefined is not a function (evaluating 'template.startsWith("<svg")')

  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-05-18T08:25:18.884Z] Session [84e41e60-3ba3-11e7-a2fa-6331d7cea211] - page.onError - stack:
  validateTemplate (http://localhost/static/clarity-icons.min.js:1)
  setIconTemplate (http://localhost/static/clarity-icons.min.js:1)
  add (http://localhost/static/clarity-icons.min.js:1)
  (anonymous function) (http://localhost/static/clarity-icons.min.js:2)
  l (http://localhost/static/clarity-icons.min.js:1)
  i (http://localhost/static/clarity-icons.min.js:1)
  (anonymous function) (http://localhost/static/clarity-icons.min.js:1)
  (anonymous function) (http://localhost/static/clarity-icons.min.js:13)
  l (http://localhost/static/clarity-icons.min.js:1)
  a (http://localhost/static/clarity-icons.min.js:1)
  p (http://localhost/static/clarity-icons.min.js:1)
  (anonymous function) (http://localhost/static/clarity-icons.min.js:1)
  (anonymous function) (http://localhost/static/clarity-icons.min.js:13)
  (anonymous function) (http://localhost/static/clarity-icons.min.js:1)

  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-05-18T08:25:18.938Z] Session [84e41e60-3ba3-11e7-a2fa-6331d7cea211] - page.onError - msg: TypeError: undefined is not an object (evaluating 'c.a')

  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-05-18T08:25:18.939Z] Session [84e41e60-3ba3-11e7-a2fa-6331d7cea211] - page.onError - stack:
  l (http://localhost/static/custom-elements.min.js:11)
  createElement (http://localhost/static/custom-elements.min.js:20)
  i (http://localhost/static/build.min.js:47)
  setDocument (http://localhost/static/build.min.js:47)
  (anonymous function) (http://localhost/static/build.min.js:48)
  (anonymous function) (http://localhost/static/build.min.js:48)
  (anonymous function) (http://localhost/static/build.min.js:47)
  (anonymous function) (http://localhost/static/build.min.js:47)
  e (http://localhost/static/build.min.js:1)
  (anonymous function) (http://localhost/static/build.min.js:47)

  phantomjs://platform/console++.js:263 in error

**Comment by wy65701436** [comment]
The same tests can be executed in the v1.1.1. Now, it blocks my automation.

**Comment by steven-zou** [comment]
No clue found from the log and seems hard to reproduce in local env. Maybe need to analyze which code delivered these days might influence it.

Possibly might cause by the ts specification or version changes if we have.

**Comment by steven-zou** [comment]
We should limit the scope of test cases and then might get some useful info from the case itself.

**Comment by wy65701436** [comment]
will try the Chrome headless mode.

**Comment by wy65701436** [comment]
works with Chrome headless.
