### ISSUE TITLE
Cannot pull image from within a docker runner for gitlab-multi-runner

### ISSUE THREAD

**Issue by weaktyper** [vmware/harbor#2351]
I am using a gitlab-ci-multi-runner and I can pull the image from the this container.

When gitlab-ci starts a new job, it runs it in a runner (which is another docker container). 

docker login is successful.

docker pull in the runner throws an error with the following message
```
received unexpected HTTP status: 500 Internal Server Error
```

```
$ docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD} ${REGISTRY_URL}
Login Succeeded
```

This is the response from the GITLAB CI pipeline which is the runner:
```
}$ docker pull $REMOTE_BUILDER_IMAGE_NAME
Error response from daemon: Get https://<<server>>/v2/test_gitlab_ci_builder/manifests/erl-19.3-ex-1.4.4-node-v7.10.0: received unexpected HTTP status: 500 Internal Server Error
```
^^^ Running this same command in other docker containers or in the host directly, leads to successful pulling of the image. 

LOGS issue:
```
May 21 20:14:16 172.20.0.1 ui[1003]: 2017-05-21T20:14:16Z [WARNING] Failed to get secret cookie, error: http: named cookie not present
May 21 20:14:16 172.20.0.1 ui[1003]: 2017-05-21T20:14:16Z [DEBUG] [authenticator.go:59]: Current AUTH_MODE is db_auth

......
May 21 20:14:16 172.20.0.1 ui[1003]: 2017-05-21T20:14:16Z [ERROR] [token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: test_gitlab_ci_builder
```

```
$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by weaktyper** [comment]
Also worth noting is that `docker push` is successful on the gitlab runner.

**Comment by stephenmoloney** [comment]
Also worth noting is that docker push is successful on the gitlab runner.

**Comment by weaktyper** [comment]
okay, it must have something to do with the tag

`docker pull ${REG_URL}/library/image:erl-19.3-ex-1.4.4-node-v7.10.0` fails in the runner

but 

`docker pull ${REG_URL}/library/image:test` pulls successfully in the runner

**Comment by ywk253100** [comment]
Provide the logs when you pulling images which failed.

**Comment by weaktyper** [comment]
Ok, on further inspection it seems that I had a typo in the image tag name....
because I no longer have this issue and that was why it didn't work in the multi runner...
Didn't see it until this morning.....
Closing issue, thanks for responding.
