### ISSUE TITLE
Remove "Copy ID" and "Copy Parent ID" 

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#2370]
![picture1](https://cloud.githubusercontent.com/assets/5835782/26391798/bf1d60e4-4096-11e7-8634-4bdb81093300.png)
As the ID and parent ID are not supported in v2 manifest any more and seems that this two attributes in v1 manifest are just for compatibility, they have no meaningful effect, so we should remove them.

Maybe we can add another column called ID to show the digest.

**Comment by ywk253100** [comment]
@reasonerjt @steven-zou Any comments?

**Comment by reasonerjt** [comment]
@steven-zou I think we need to check with Louie, why these buttons are introduced.

I personally don't think we need it, maybe add a button "Copy digest"

**Comment by lweitzman** [comment]
i don't remember exactly why these were introduced but i think it was requested by @akshayl 
we should not add a new column, but i would support the additional action item if that makes sense. what does the "Copy digest" provide?

**Comment by akshayl** [comment]
Let's remove the Copy ID and Copy Parent ID.

**Comment by steven-zou** [comment]
@wknet123 

  Let's remove the two menu items.

**Comment by steven-zou** [comment]
Move menu items in Harbor UI library, but not enabled in harbor portal itself. Move to SP11

**Comment by steven-zou** [comment]
Move to SP12

**Comment by steven-zou** [comment]
Done in PR #2601
