### ISSUE TITLE
harbor ui shows duplicated string "days" in popup-details.directive.js

### ISSUE THREAD

**Issue by nuaays** [vmware/harbor#2371]
I use docker-compose to launch harbor, "vmware/harbor-ui:latest" pulled from hub.docker.com

I see duplicated string "days" when i click to see the detail of one image with tag in pop window, as follows
<img width="713" alt="2017-05-24 4 24 38" src="https://cloud.githubusercontent.com/assets/1469585/26393797/8c1d99fa-409d-11e7-8a5c-db432ca23e96.png">

I check the js file "static/resources/js/components/repository/popup-details.directive.js" and see
<img width="1586" alt="2017-05-24 4 27 23" src="https://cloud.githubusercontent.com/assets/1469585/26394001/29fe54de-409e-11e7-852b-f849ee413e2f.png">

so I think here is the root cause, and we can remve string "days" in popup-details.directive.js.

But it seems I cannot find popup-details.directive.js in repo "https://github.com/vmware/harbor" ...

**Comment by nuaays** [comment]
@hainingzhang @wknet123

**Comment by wy65701436** [comment]
Hi @nuaays, are you using the 0.5.0? 

You can finde the js file is because that we have refinded UI, and this issue doesn't exist in the 1.1.1. 
Just try with the latest release.

**Comment by reasonerjt** [comment]
Close due to inactivity.
Please use the latest release.
