### ISSUE TITLE
The retrying jobs can not be canceled although the policy is disabled already

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#2382]

**Comment by reasonerjt** [comment]
You don't see it to be "canceled" right away, instead, once it's scheduled it should be canceled.
Could you confirm with tester?

**Comment by ywk253100** [comment]
I have confirm with @sigsbee , the job is rescheduled again and again.

**Comment by reasonerjt** [comment]
ok, I'll check when I'm back :), keep bashing jobservice and open more issues :)
