### ISSUE TITLE
nginx fails to start leaving OVA unusable post docker-compose restart

### ISSUE THREAD

**Issue by lgayatri** [vmware/harbor#2394]
On an integrated OVA environment, I restarted services using:

root@vic-st-h2-132 [ /etc/vmware/harbor ]# docker-compose ps
       Name                     Command               State                          Ports
------------------------------------------------------------------------------------------------------------------
harbor-adminserver   /harbor/harbor_adminserver       Up
harbor-db            docker-entrypoint.sh mysqld      Up      3306/tcp
harbor-jobservice    /harbor/harbor_jobservice        Up
harbor-log           /bin/sh -c crond && rm -f  ...   Up      127.0.0.1:1514->514/tcp
harbor-ui            /harbor/harbor_ui                Up
nginx                nginx -g daemon off;             Up      0.0.0.0:443->443/tcp, 0.0.0.0:4443->4443/tcp, 80/tcp
registry             /entrypoint.sh serve /etc/ ...   Up      5000/tcp

root@vic-st-h2-132 [ /etc/vmware/harbor ]# docker-compose restart
Restarting nginx ... done
Restarting harbor-jobservice ... done
Restarting harbor-ui ... done
Restarting harbor-adminserver ... done
Restarting harbor-db ... done
Restarting registry ... done
Restarting harbor-log ... done

root@vic-st-h2-132 [ /etc/vmware/harbor ]# docker-compose ps
       Name                     Command                 State               Ports
------------------------------------------------------------------------------------------
harbor-adminserver   /harbor/harbor_adminserver       Up
harbor-db            docker-entrypoint.sh mysqld      Up           3306/tcp
harbor-jobservice    /harbor/harbor_jobservice        Up
harbor-log           /bin/sh -c crond && rm -f  ...   Up           127.0.0.1:1514->514/tcp
harbor-ui            /harbor/harbor_ui                Up
nginx                nginx -g daemon off;             Restarting
registry             /entrypoint.sh serve /etc/ ...   Up           5000/tcp

nginx is not getting started since 1 hour now, leaving the system unusable, screen shot attached.

![nginx-failed-setup-unusable](https://cloud.githubusercontent.com/assets/25006749/26577368/d0ad341c-4549-11e7-8ab8-b5415560e121.PNG)
Logs attached:
[vm-2017-05-30.14860.tar.gz](https://github.com/vmware/harbor/files/1037902/vm-2017-05-30.14860.tar.gz)

**Comment by frapposelli** [comment]
@lgayatri in the integrated OVA you should follow the correct shutdown/startup procedures detailed in the docs https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/restart_services.html

**Comment by lgayatri** [comment]
@frapposelli 
I tried to restart again using systemctl and seeing TIMEOUT error now. 
root@vic-st-h2-132 [ /etc/vmware/harbor ]# systemctl restart harbor
root@vic-st-h2-132 [ /etc/vmware/harbor ]# systemctl restart admiral
root@vic-st-h2-132 [ /etc/vmware/harbor ]# docker-compose ps
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
root@vic-st-h2-132 [ /etc/vmware/harbor ]#

The setup continues to be in unusable state, is there any way to resurrect it? 
Why is nginx not getting started normally? Please help to clarify.

**Comment by lgayatri** [comment]
proxy.log says:

May 30 16:56:49 172.18.0.1 proxy[386]: nginx: [emerg] host not found in upstream "notary-server:4443" in /etc/nginx/conf.d/notary.upstream.conf:3
May 30 16:56:53 172.18.0.1 proxy[386]: 2017/05/30 16:56:53 [emerg] 1#1: host not found in upstream "notary-server:4443" in /etc/nginx/conf.d/notary.upstream.conf:3
May 30 16:56:53 172.18.0.1 proxy[386]: nginx: [emerg] host not found in upstream "notary-server:4443" in /etc/nginx/conf.d/notary.upstream.conf:3
May 30 16:57:00 172.18.0.1 proxy[386]: 2017/05/30 16:57:00 [emerg] 1#1: host not found in upstream "notary-server:4443" in /etc/nginx/conf.d/notary.upstream.conf:3
May 30 16:57:00 172.18.0.1 proxy[386]: nginx: [emerg] host not found in upstream "notary-server:4443" in /etc/nginx/conf.d/notary.upstream.conf:3

**Comment by ywk253100** [comment]
@lgayatri Please refer to this [guide](https://github.com/vmware/harbor/blob/master/docs/installation_guide.md#managing-lifecycle-of-harbor-when-its-installed-with-notary) .

**Comment by lgayatri** [comment]
Which one is correct way to restart harbor on integrated OVA 
systemctl restart harbor 
or 
https://github.com/vmware/harbor/blob/master/docs/installation_guide.md#managing-harbors-lifecycle ?

I dont see any way to bring back the OVA. As I provided all the required logs for investigation, will tear down the test bed.

**Comment by lgayatri** [comment]
I rebooted the OVA itself and hit: https://github.com/vmware/harbor/issues/2397

**Comment by reasonerjt** [comment]
Close as it's fixed in .ova. it's a dup to 2394 in vic-product.
