### ISSUE TITLE
Harbor continuously fails to start after OVA reboot 

### ISSUE THREAD

**Issue by lgayatri** [vmware/harbor#2397]
On an integrated OVA, I was hitting
root@vic-st-h2-132 [ /etc/vmware/harbor ]# docker-compose ps
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

For which I rebooted the OVA after which harbor service fails to start up
mysql.log says:

May 31 06:40:31 172.18.0.1 mysql[368]: 2017-05-31 06:40:31 1 [Note] InnoDB: Starting shutdown...
May 31 06:40:33 172.18.0.1 mysql[368]: 2017-05-31 06:40:33 1 [Note] InnoDB: Shutdown completed; log sequence number 2350137
...
May 31 06:40:33 172.18.0.1 mysql[368]: 2017-05-31 06:40:33 1 [Note] Shutting down plugin 'mysql_native_password'
May 31 06:40:33 172.18.0.1 mysql[368]: 2017-05-31 06:40:33 1 [Note] Shutting down plugin 'binlog'
May 31 06:40:33 172.18.0.1 mysql[368]: 2017-05-31 06:40:33 1 [Note] mysqld: Shutdown complete

Attached the harbor logs from the OVA.

[2017-05-31.zip](https://github.com/vmware/harbor/files/1040470/2017-05-31.zip)

The service attempts to starts and then exits.

root@vic-st-h2-132 [ /etc/vmware/harbor ]# docker-compose  ps
       Name                     Command               State            Ports
-------------------------------------------------------------------------------------
harbor-adminserver   /harbor/harbor_adminserver       Up
harbor-db            docker-entrypoint.sh mysqld      Up      3306/tcp
harbor-log           /bin/sh -c crond && rm -f  ...   Up      127.0.0.1:1514->514/tcp
registry             /entrypoint.sh serve /etc/ ...   Up      5000/tcp
root@vic-st-h2-132 [ /etc/vmware/harbor ]# docker-compose  ps
       Name                     Command                State              Ports
----------------------------------------------------------------------------------------
harbor-adminserver   /harbor/harbor_adminserver       Exit 2
harbor-db            docker-entrypoint.sh mysqld      Up         3306/tcp
harbor-jobservice    /harbor/harbor_jobservice        Exit 2
harbor-log           /bin/sh -c crond && rm -f  ...   Up         127.0.0.1:1514->514/tcp
harbor-ui            /harbor/harbor_ui                Exit 2
nginx                nginx -g daemon off;             Exit 128
registry             /entrypoint.sh serve /etc/ ...   Exit 2

**Comment by lgayatri** [comment]
[vm-2017-05-31.23497.tar.gz](https://github.com/vmware/harbor/files/1040479/vm-2017-05-31.23497.tar.gz)

**Comment by wy65701436** [comment]
@lgayatri, I cannot reproduce it, can you tell the exactly steps? If possible, can you share your env to have a debug?

**Comment by lgayatri** [comment]
@wy65701436 
1. First I hit https://github.com/vmware/harbor/issues/2394
2. After which I restarted the integrated OVA 
3. Upon its power on checked docker-compose ps which reported the given failure.
Scale : 2500 containers and 50 VCH

**Comment by wy65701436** [comment]
can you have your env to debug this issue?

**Comment by lgayatri** [comment]
@wy65701436 : I just  deleted all 50 VCHs and 2500 containers. Will provide the setup for you on next tear down window.

**Comment by lgayatri** [comment]
@wy65701436 , I could NOT reproduce this issue with build 11340. Will try on the next build as well and conclude.

**Comment by wy65701436** [comment]
Thanks @lgayatri for your infor, shall we just close this issue? And you can reopen it if any new clue.

**Comment by lgayatri** [comment]
Ok @wy65701436
