### ISSUE TITLE
add a parameter in harbor.conf to specify the path of storage

### ISSUE THREAD

**Issue by silenceshell** [vmware/harbor#2399]
Harbor use /data as its default storage path, so when get  `/api/systeminfo/capacity`, the adminserver uses `syscall.Statfs` to get /data size and return.
This is no problem.

But in my envrionment, the default root filesystem is too small, so I want to specify the bigger /home/registry directory for harbor to store repositories.
I edited the docker-compose.yml, change /data/registry to /home/registry:

```
  registry:
    image: vmware/registry:2.6.1-photon
    container_name: registry
    restart: always
    volumes:
      - /home/registry:/storage:z
      - ./common/config/registry/:/etc/registry/:z
```

Then I run install.sh, everything is well done, and the registry does store data in /home/registry.

BUT, when I checked the `STORAGE` in the front page, I find that it shows the root fs size(which is 98GB), not the /home/registry size(which is 1TB).

I know that I should change all /data to /home in docker-compose.yml, so the adminserver will get the right size, but it is not friendly.
Maybe we can add a parameter in harbor.conf, like `storage = /data`, so that users can change it to the path they want, in case.

---

If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-28.git1398f24.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      1398f24/1.12.6
 Built:           Fri May 26 17:28:18 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-28.git1398f24.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      1398f24/1.12.6
 Built:           Fri May 26 17:28:18 2017

docker-compose version 1.13.0, build 1719ceb
docker-py version: 2.3.0
CPython version: 2.7.5
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013

2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
no need.

3)Log files, you can get them by package the /var/log/harbor/ .
no log files.

**Comment by ywk253100** [comment]
@silenceshell Yes, I agree. We'll provide a parameter to configure the storage path.

**Comment by zevaks** [comment]
Hello @ywk253100 , any advices, why metrics for diskusage is missing in dashboard. 
![harbor](https://user-images.githubusercontent.com/37455849/67487459-48d0f500-f66e-11e9-88a6-7863ed12a2e0.PNG)

Version v1.9.0-d13cf448
Using filesystem type with custom /storage rootdirectory.
thanks
