### ISSUE TITLE
storage "meter" when using S3 backend?

### ISSUE THREAD

**Issue by jaychris** [vmware/harbor#2400]
I'm using an S3 backend for my Harbor installation.  I've uploaded a few images, verified they are saved to S3.  All is well.

The storage "meter" in the GUI though, shows 4G of 8G used.  I'm not exactly sure what it is reporting on, since I'm using S3 for my backend.  I just want to be certain I'm not about to run into an unforeseen storage issue.

Is it safe to ignore it, or so I need to Do Something about it?

**Comment by silenceshell** [comment]
It looks like the same problem as #2399 which I faced.
I guess you installed harbor on an os, who's root filesystem is 8G totally and 4G used, and the apiserver reported storage meter data based on this, not based on the actually s3 backend.

**Comment by ywk253100** [comment]
@jaychris The storage "meter" is only supported for file system backend now. Just ignore it, it does not matter for other operations.

**Comment by jaychris** [comment]
thanks!
