### ISSUE TITLE
Volume metrics should be disabled if backend storage of registry does not support, such as s3.

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#2425]
Volume metrics should be disabled if backend storage of registry does not support, such as s3.

**Comment by reasonerjt** [comment]
This may require some structural change, for example, admin server can read configurations of registry.

**Comment by ywk253100** [comment]
Backend works are finished by #4036. 
@ninjadq The `registry_storage_provider_name` is returned by `/api/systeminfo` now, UI should disable disk usage view if the value isn't `filesystem`.
