### ISSUE TITLE
scroll bars appear in datagrid when not needed

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#2428]
its hard to reproduce but the scrollbars appeared after clicking on the menu item on one row when content was selected with the mouse. refreshing the page removed the scrollbars.

![screen shot 2017-06-05 at 8 23 13 am](https://cloud.githubusercontent.com/assets/626032/26783898/a1c369b8-49c8-11e7-9d82-7ed94b7eea26.png)

**Comment by steven-zou** [comment]
Checked, did not reproduced in master code. So close this issue. If you reproduced again, you can reopen it. @lweitzman
