### ISSUE TITLE
managing Harbor logs

### ISSUE THREAD

**Issue by jaychris** [vmware/harbor#2429]
The logfiles in Harbor are managed through the harbor-log container.  The container rotates those files weekly, which means they fill up your filesystem pretty fast (we get about 1G or more per day).

I don't see any documentation for managing them so the fastest way I can see to fix it is to edit the container to rotate more often/aggressively, but that won't persist past a pave/re-launch.  Is there a better way to manage the log cleanup in Harbor?

**Comment by reasonerjt** [comment]
@jaychris  thanks for reporting, which log file is eating too much space? Is it ui.log?

**Comment by cbarzu** [comment]
Hi @reasonerjt , we disabled debug traces using this method #2354 
But there is still generating a lot of traces in info:
```
500M	./2017-06-04
358M	./2017-06-05

cd 2017-06-04

 /var/log/harbor/2017-06-04]$ ls -lh | cut -f5-11 -d' '

 872 jun  4 05:37 anacron.log
5,6K jun  5 01:01 CROND.log
2,3M jun  5 01:59 docker-current_adminserver.log
2,4M jun  5 02:01 docker-current_jobservice.log
 77M jun  5 01:59 docker-current_proxy.log
208M jun  5 01:59 docker-current_registry.log
212M jun  5 01:59 docker-current_ui.log
4,1K jun  5 01:01 run-parts.log
```

**Comment by jaychris** [comment]
It's actually primarily the registry.log, though ui.log is a close 2nd.  The listing below is from today so far...  it'll be over a gig by the end of the day.

```
root@ip-10-234-0-227:/var/log/harbor/2017-06-06# ls -lh
total 607M
-rw-r----- 1 ubuntu 16 869K Jun  6 16:37 adminserver.log
-rw-r----- 1 ubuntu 16  995 Jun  6 03:26 anacron.log
-rw-r----- 1 ubuntu 16 3.9K Jun  6 16:01 CROND.log
-rw-r----- 1 ubuntu 16  27M Jun  6 16:37 proxy.log
-rw-r----- 1 ubuntu 16 460M Jun  6 16:37 registry.log
-rw-r----- 1 ubuntu 16 3.1K Jun  6 16:01 run-parts.log
-rw-r----- 1 ubuntu 16 120M Jun  6 16:37 ui.log
```

**Comment by ywk253100** [comment]
@jaychris @cbarzu You can modify the log level by the following steps:
1) Change the LOG_LEVEL to error in common/config/ui/env
2) Change the level to error in common/config/registry/config.yml
3) Run docker-compose down
4) Run docker-compose up -d

If you want to rotate the logs more often/aggressively, you need to rebuild the log image.

**Comment by mdasgit** [comment]
![image](https://user-images.githubusercontent.com/46070532/55496464-ba0e7380-565c-11e9-9a51-14155e702920.png)
My logs are eating a lot of space . Can we delete them ?

**Comment by thyarles** [comment]
I now this thread was closed, but I found an easy way to minimize Clair logs today in Harbor:

Just add the line **command: "-log-level error"** on your docker-compose.yaml:

```
  [...]
  clair:
    command: "-log-level error"
    networks:
      - harbor-clair
  [...]
```

Then delete the Clair pod and recreate just this pod with the commands:

```
$ cd /harbor_src_dir/harbor
$ docker-compose stop clair && docker-compose rm
$ docker-compose up -d clair
```

Now your logs only write erros of Clair container.
