### ISSUE TITLE
Can not pull the vmware/harbor-adminserver

### ISSUE THREAD

**Issue by aaron0428** [vmware/harbor#2430]
HI:
  I can not pull the vmware/harbor-adminserver image.cloud you send the vmware/harbor-adminserver image file to me!!!  My email :740338368@qq.com
   thank you very much!!!

docker pull vmware/harbor-adminserver:__version__

Error response from daemon: manifest for vmware/harbor-adminserver:__version__ not found

**Comment by reasonerjt** [comment]
@aaron0428  could you try the offline installer?

**Comment by aaron0428** [comment]
@reasonerjt I am in china! The network ie not Stabilization!!!

**Comment by caicaicai** [comment]
I have a latest offline package, I can share it with BAIDU NET DISK with you.

**Comment by aaron0428** [comment]
@caicaicai 谢谢！！我已经下载好了，整整下载了4个小时！！！很是郁闷！！

**Comment by aaron0428** [comment]
@@caicaicai 顺便想问下，harbor你用的是http还是HTTPS？？

**Comment by caicaicai** [comment]
如果你有证书就建议用https啊，方便，不用配置insecure-registries。我们公司生产我配置的https，自己玩用的http。没差的。

**Comment by caicaicai** [comment]
用中文会不会被人家骂啊？

**Comment by aaron0428** [comment]
我现在用的就是HTTPS，但是奇怪的是，用购买的证书配置上去服务器不能登录，只能网页登录，用我自己制作的证书就没问题，只是自己制作的证书用起来比较麻烦，每台服务器都要配置认证
应该不会被骂吧！！反正也没其他人看！！！

**Comment by chenliping972385283** [comment]
@aaron0428 我用自己的证书弄得，登陆进去后push的时候报的是301，因为我服务器传回来的是http请求，能分享一下你是怎么用的https么？

**Comment by reasonerjt** [comment]
close due to inactivity.

**Comment by handsomebai** [comment]
请教一个问题，harbor-adminserver 这个镜像什么作用。官方文档只给出docker-compose中其他6个image的解释，但是把harbor-adminserver省略了。求教
