### ISSUE TITLE
The loading indicator is still existing even the ping response is returned .

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#2435]
The loading indicator is still existing even the ping response is returned .
<img width="605" alt="2017-06-06 2 26 27" src="https://cloud.githubusercontent.com/assets/5753287/26816466/4d30cc04-4ac4-11e7-9668-4da3100a9b6e.png">

**Comment by lweitzman** [comment]
Is there a reason there is a scroll bar that appears? can we make sure it doesn't appear?

**Comment by steven-zou** [comment]
@lweitzman 

  Seems it's not caused by our code, might come from the framework themselves, possibly Angular. The framework fails to refresh the view when the data status is changed. Sometimes, if you click the view, then everything become normal again. So, a weird issue. Keep eyes on it.

**Comment by steven-zou** [comment]
move to SP12

**Comment by reasonerjt** [comment]
defer to sprint 13.

**Comment by steven-zou** [comment]
As it's fixed, close this issue.
