### ISSUE TITLE
Harbor 1.1.1 console is not working with Microsoft IE 11

### ISSUE THREAD

**Issue by roldancer** [vmware/harbor#2441]
Hi All, We are using Harbor 1.1.1, some Harbor's pages are not working properly with Microsoft IE 11, for example the TAG page is alway empty with IE, with Chrome and Firefox works OK. The same issue happen if you click on the Logs links.

Any idea?

![image007](https://cloud.githubusercontent.com/assets/5012200/26823150/dae15ba8-4aac-11e7-8d84-9da174891fce.jpg)

**Comment by steven-zou** [comment]
@roldancer 

  Could you please provide more details of the issue? For example, what's the windows OS version and concrete version of IE 11?

  We can not reproduce this issue under IE 11 and Windows 7 now.

  Additionally could you please try to open developer tool of IE with F12 and paste the errors here if they're displayed in the console?

**Comment by steven-zou** [comment]
@roldancer 

  Any updates about this issue?

**Comment by betazep** [comment]
We also have this issue.  Decided to use Chrome/Firefox for now.  I noticed that the data is updated in the database correctly, but the webpage presents cached information even on subsequent logins.  (e.g. Users are still present even though they were deleted. Session tabs load with old data even though you are not logged in.)  Deleting "Cookies and Website data" allows the data to represent current information, but is then cached for subsequent visits.
