### ISSUE TITLE
Not support syslog

### ISSUE THREAD

**Issue by aaron0428** [vmware/harbor#2444]
when i start the habor service,there have  some error logs!!!

docker logs harbor-adminserver
Error response from daemon: configured logging driver does not support reading

how can i slove this problem！！？？

**Comment by reasonerjt** [comment]
The logs are redirected to a syslog container you can read the log files in /var/log/harbor/

**Comment by aaron0428** [comment]
@reasonerjt  谢谢，，已解决！！！

**Comment by threeq** [comment]
@aaron0428 这个问题怎么解决的啊 ？

**Comment by atzq1234** [comment]
privileged: true
