### ISSUE TITLE
I upload the image to harbor, But I can't check it from my admin ui.

### ISSUE THREAD

**Issue by caicaicai** [vmware/harbor#2453]
Docker version 1.10.3, build cb079f6-unsupported
docker-compose version 1.8.1, build 878cff1

I have download the harbor-offline-installer-v1.1.1.tgz.
untgz it, make some basic config with the harbor.cfg.

run "sh install.sh"

Everything looks normal..

The VM harbor UI startup,I can login with my password.

add my "--insecure-registry"

I can login with my harbor.
I can push and pull image from harbor.

BUT THE PROBLEM is that I can't seen any image from my harbor admin ui panel, it was empty while I was just push the image into it.

I google it, and try a lot of..
for example, I tag my image with library,like this "harbor.localhost:5000/library/busybox"

What did I miss?

Sorry about my bad English.

**Comment by roldancer** [comment]
Are you using microsoft IE ?

**Comment by caicaicai** [comment]
Chrome Version 58.0.3029.110 (64-bit) macOS

**Comment by caicaicai** [comment]
It works now ,after re-install.
