### ISSUE TITLE
what is the function of admiral_url in harbor.cfg ?

### ISSUE THREAD

**Issue by fffffreedom** [vmware/harbor#2462]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
3)Log files, you can get them by package the /var/log/harbor/ .

hi, 
i'm quit confused about the fucnction of admiral_url, what's the difference between hostname and admiral_url ?

thx

**Comment by fffffreedom** [comment]
@reasonerjt

**Comment by reasonerjt** [comment]
It's for integrate with another project:
https://github.com/vmware/admiral

For standalone Harbor it should be left unset.

**Comment by fffffreedom** [comment]
thanks
