### ISSUE TITLE
关于镜像仓库复制管理问题

### ISSUE THREAD

**Issue by aaron0428** [vmware/harbor#2465]
你好：
      我在配置镜像仓库复制的时候，目标URL已经添加好了，但是在复制管理页面，没有想过的按钮可以管理需要复制的项目，请问我要怎么添加我想要复制的项目？页面如下
![image](https://user-images.githubusercontent.com/15682845/26916813-4be9132e-4c5e-11e7-8a3f-8dea0eb798d9.png)

**Comment by sigsbee** [comment]
add rules from project manage page
![aaa](https://user-images.githubusercontent.com/23101283/26917268-31b2acf2-4c60-11e7-8db1-feecfd1735fe.PNG)

**Comment by aaron0428** [comment]
好的，非常感谢！
