### ISSUE TITLE
fail to start harbor due to “Temporary failure in name resolution”

### ISSUE THREAD

**Issue by fffffreedom** [vmware/harbor#2466]
$ docker -v
Docker version 17.05.0-ce, build 89658be
$ docker-compose -v
docker-compose version 1.13.0, build 1719ceb

i'm using vbox to deploy harbor, harbor fail to start as sysytem boot up. but when i start harbor manully, it works well. the containers started are shown as bellow: 
$ docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS                          PORTS                     NAMES
be4d6fc0aa3d        vmware/harbor-jobservice:v1.1.1   "/harbor/harbor_jo..."   27 minutes ago      Up 49 seconds                                             harbor-jobservice
6ffabea94088        vmware/nginx:1.11.5-patched       "nginx -g 'daemon ..."   27 minutes ago      Restarting (1) 21 seconds ago                             nginx
8b60f5db97ff        vmware/harbor-ui:v1.1.1           "/harbor/harbor_ui"      27 minutes ago      Up 49 seconds                                             harbor-ui
32f7d9aab24c        vmware/harbor-log:v1.1.1          "/bin/sh -c 'crond..."   27 minutes ago      Up 22 minutes                   127.0.0.1:1514->514/tcp   harbor-log

the ui.log' log 

Jun  8 03:51:43 172.18.0.1 ui[1434]: 2017-06-08T07:51:43Z [INFO] Config path: /etc/ui/app.conf
Jun  8 03:51:43 172.18.0.1 ui[1434]: 2017-06-08T07:51:43Z [INFO] initializing configurations...
Jun  8 03:51:43 172.18.0.1 ui[1434]: 2017-06-08T07:51:43Z [INFO] key path: /etc/ui/key
Jun  8 03:51:43 172.18.0.1 ui[1434]: 2017-06-08T07:51:43Z [INFO] initializing client for adminserver http://adminserver ...
**Jun  8 03:51:43 172.18.0.1 ui[1434]: 2017-06-08T07:51:43Z [ERROR] [utils.go:94]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp: lookup adminserver: Temporary failure in name resolution**

**Comment by ywk253100** [comment]
Provide all logs, seems nginx didn't start either?

**Comment by fffffreedom** [comment]
[jobservice.txt](https://github.com/vmware/harbor/files/1063577/jobservice.txt)
[proxy.txt](https://github.com/vmware/harbor/files/1063579/proxy.txt)
[ui.txt](https://github.com/vmware/harbor/files/1063580/ui.txt)
@ywk253100

**Comment by ywk253100** [comment]
Seems it's the issue of docker, the hostname can not be resolved.

**Comment by fffffreedom** [comment]
i modify the /etc/hosts and /etc/hostname, maybe this matters

**Comment by fffffreedom** [comment]
I think this may be related to dependencies between containers.
harbor's container s use domain name , such as adminserver/ui, to communicate with each other, and some containers depend on others, or somes containers will ping other containers.
for example, as show in log files, jobserver ui proxy containers fail to start because of **"failed to connect to tcp://adminserver:80,"**.
**but i also quit confused on why adminserver didn't come up as shown in docker ps?**
 @ywk253100 @reasonerjt 
i found another isser which is the same to mines #1265

**Comment by ywk253100** [comment]
Check the logs of adminserver to see why it didn't start up.

**Comment by fffffreedom** [comment]
just like
Jun 8 03:51:43 172.18.0.1 ui[1434]: 2017-06-08T07:51:43Z [ERROR] [utils.go:94]: f**ailed to connect to tcp://adminserver:80**, retry after 2 seconds :dial tcp: lookup adminserver: Temporary failure in name resolution

**Comment by ywk253100** [comment]
This is the log of UI, can you reproduce the issue and provide logs of adminserver?

**Comment by fffffreedom** [comment]
it happens almost everytime i reboot the host where the harbor is running.
i wonder whether you can try it or not?

**Comment by ywk253100** [comment]
We can not reproduce it.

**Comment by chanNet** [comment]
I have the same problem, it may be the issue of docker, i restart docker service and it works as expected

**Comment by reasonerjt** [comment]
What's your version of docker?

**Comment by yixingjia** [comment]
Cannot reproduce on latest build, Close as cannot reproduce.

Please feel free to reopen it if you still encounter the issue in latest build.

**Comment by bo-er** [comment]
I did `sudo service docker restart` and the problem is gone, I think it's more like a docker problem rather than a harbor one.
BTW this happened after I modified `/etc/docker/daemon.json` and restarted docker.
