### ISSUE TITLE
Add 'Image ID' column to repository page

### ISSUE THREAD

**Issue by xkrt** [vmware/harbor#2469]
It is very conveniently to see which tags alias which images.
Harbor v1.1.1

**Comment by lweitzman** [comment]
why are we adding the image id to the repository page? whats the use case for doing that? when there are more than one image in a repo, what does that look like?
@steven-zou @tonycgil @akshayl

**Comment by xkrt** [comment]
We use docker tags for versioning our images (we use format yymmdd-<git hash>).
Also, we use special tags `prod` and `stage`, which points to (alias) same images with "version tags". Sometimes `stage` and `prod` aliases same image, sometimes them alias different images.
I believe this scheme is not rare and quite common.

The problem with Harbor UI, which btw is a great project 👍, that we do not see what versions `prod`/`stage` tags alias because we do not see images ids. Compare screenshots of Harbor and output of `docker images`:
![harbor_screen](https://user-images.githubusercontent.com/428187/26963065-5fae13f6-4cf3-11e7-8416-308117b6e388.png)
![docker_images_screen](https://user-images.githubusercontent.com/428187/26963253-4f8d43e2-4cf4-11e7-8759-6187f9b85ae4.png)

As you can see, if I look at the output of `docker images` command - I can easily figure out that `prod` and `stage` tags both points to image with version tag `170607-6c037bb`.
But this impossible to figure out with current Harbor UI.

**Comment by lweitzman** [comment]
@xkrt you're saying that because an image can have multiple tags, which will be displayed on different rows, you can't tell that 2 rows in the datagrid refer to the same image. would a better solution be to group the tags of a given image together in the datagrid? is there any reason to actually copy and use the image ID on the command line? @akshayl @steven-zou @tonycgil  thanks.

**Comment by xkrt** [comment]
@lweitzman yes, looks like your proposal solves my problem. And I do not see any uses cases of copying image id actually.
Btw maybe you should consider some "columns to show settings" functionality. For example, I do not really need "Architecture" and "OS" columns at all, they just waste of space for me.

**Comment by ywk253100** [comment]
The `Image ID` is a concept of docker client side. You can use digest instead and you can get it from UI.

**Comment by loganmzz** [comment]
Hello there, but I can't find where is showed image digest ... I need to check image version stored in our Harbor and the one used to deploy on Kubernetes.

**Comment by testwill** [comment]
这个镜像id是不打算加入吗？如果这样的话，就只能下载到本地才能知道镜像ID吧
