### ISSUE TITLE
cleanup of repository image list page

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#2472]
on the image listing page of a repo, the pull command spans across columns. additional width should be given. resizing the columns after cleans it up. Also, i think that the red X for not being signed is a bit too much. @tonycgil is there another icon we can use to indicate that an image is not signed (e.g., a dash). then the green check indicates a signed image.

![screen shot 2017-06-08 at 8 25 37 am](https://user-images.githubusercontent.com/626032/26928806-71233234-4c25-11e7-8f3e-3f350984e48d.png)

**Comment by tonycgil** [comment]
“Signed” column should have a small max-width to fit an icon. “Pull command” should also have a max-width and include the “…” for uncertain long strings.

![github-repository-library-datagrid-fix](https://user-images.githubusercontent.com/25991813/26938973-b3572f8e-4c2a-11e7-9ab2-1ce6ebe73cbc.png)

**Comment by steven-zou** [comment]
@lweitzman @tonycgil 

  Will do some investigation to confirm how we can improve it.

**Comment by steven-zou** [comment]
Already reset the column widths. Close this issue.
