### ISSUE TITLE
Need a standard way to get token from repoclient/modifier.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#2486]
Job service need a way to get token of resource by calling token service. 
Currently the code scattered in modifier and authorizer.

Looks it maybe easy to refactor and let modifer has capability to return a token

**Comment by ywk253100** [comment]
The authorizer(modifier) authorizes a request by adding a token according to the resources that the request want to access, so refactor the authorizer to return a token doesn't make sense. As discussed, I'm going to close this issue.
