### ISSUE TITLE
Update DB migrator for 1.2.0

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#2490]
more details of DB change refer to issues labled “DB Change"
and 
https://github.com/vmware/harbor/blob/master/tools/migration/changelog.md

**Comment by reasonerjt** [comment]
Defer to sprint 13 due to late DB schema change.

**Comment by reasonerjt** [comment]
Shall we close this one @wy65701436

**Comment by wy65701436** [comment]
Sure, it's done and passed test.
