### ISSUE TITLE
inconsistency in the directories of Dockerfiles

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#2492]
For example, when using ./make/common/db/Dockerfile is requires to be used in local directory, but for docker files such as make/photon/*/Dockerfile they require to be used under vmware/harbor/

Better to make this consistent.

**Comment by wdhif** [comment]
This would help greatly for the issue https://github.com/vmware/harbor/issues/3061

**Comment by wy65701436** [comment]
Already move all the docker files to make/photon. Close it as fixed.
