### ISSUE TITLE
            Need to install docker-compose(1.7.1+) by yourself first and run this script again. 

### ISSUE THREAD

**Issue by kangweihu** [vmware/harbor#2514]
docker-compose version 1.11.2, 
  docker-compose version 1.13.0, 
  docker-compose version 1.9.0
  I changed my-docker-compose version like 1.11.2 ，1.13.0, 1.9.0 ,but the error always the same.How do I solve the problem?

**Comment by wy65701436** [comment]
please refer to https://github.com/vmware/harbor/issues/2317

**Comment by wy65701436** [comment]
@kangweihu, are you still experiencing this issue?

**Comment by wy65701436** [comment]
Please use the soluation above to resolve this issue. Reopen it any new issue.
