### ISSUE TITLE
admin user should not be shown in user manage page

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#2527]
v1.1.2-271-g46c4667
admin user should not be shown in user manage page. since it may be deleted by mistake

![admin](https://user-images.githubusercontent.com/23101283/27168612-07401b98-51d9-11e7-98e0-5455d7bd81e8.PNG)

**Comment by ywk253100** [comment]
GET /users should not return admin user.
DELETE /users/uid should block the operation to admin user either.

**Comment by lweitzman** [comment]
this view is for the admin only and i think we should show all admins that are in the system. you should be able to delete some administrators but just not the last one. or yourself if you are an administrator.

**Comment by steven-zou** [comment]
@lweitzman 

  Actually the 'admin' account is a preserved account and more like a super 'root' account in os . It's not created by the system and then should be treated as different "administrator" account comparing with other "admin" accounts. Although, currently it has no obviously diff with the other "admin" accounts, it may be assigned more other important priviledges in future. So disabling the eidting functions for admin or even hiding it may be more reasonabe, right?

**Comment by ywk253100** [comment]
Fixed by #2547 .
