### ISSUE TITLE
Project name create in UI should be checked whether they are in lowercase.

### ISSUE THREAD

**Issue by wknet123** [vmware/harbor#253]
Both front-end and back-end should do this check as to meet the Docker registry services.

**Comment by xiaods** [comment]
please follow [docker Image spec:](https://github.com/docker/docker/blob/master/image/spec/v1.md) 

**Repository**:  they SHOULD be limited to the set of alphanumeric characters [a-zA-z0-9], and punctuation characters [._-], however it MAY contain additional / and : characters for organizational purposes, with the last : character being interpreted dividing the repository component of the name from the tag suffix component.

**Tag**: they SHOULD be limited to the set of alphanumeric characters [a-zA-z0-9], punctuation characters [._-], and MUST NOT contain a : character.

**Comment by wemeya** [comment]
verified.
