### ISSUE TITLE
could not delete a user getting error "object does not exist"

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#2538]
as admin, i could not delete the user "louis" from the list of users getting the error "... the object does not exist"

![screen shot 2017-06-15 at 8 38 38 am](https://user-images.githubusercontent.com/626032/27182082-1d6e7044-51a8-11e7-801a-80aa4ecccc49.png)

**Comment by lweitzman** [comment]
i was using https://10.112.122.204/harbor/users

**Comment by steven-zou** [comment]
@ywk253100 

Api changed?

Error in console:  DELETE https://10.112.122.204/api/users/4 404 (Not Found)

**Comment by wy65701436** [comment]
encounter it when to update user comments.

**Comment by ywk253100** [comment]
Fixed by #2547 .
