### ISSUE TITLE
Fails to authenticate user with MS AD as LDAP server

### ISSUE THREAD

**Issue by tonardo2015** [vmware/harbor#254]
Hi Guys,

We tried to integrate Harbor with MS AD in our enviornment, however it seems Harbor could not properly authenticate the user from Active Directory.

Below is the requested info in our environment:
1)Version of docker engine and docker-compose
[root@starhost ~]# docker-compose -version
docker-compose version 1.7.0rc2, build ea2d526
[root@starhost ~]# docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

2)Config files of harbor, you can get them by packaging "Deploy/config" directory
/opt/harbor-0.1.1/Deploy/harbor.cfg

auth_mode = ldap_auth
ldap_url = ldap://10.32.167.175:389
ldap_basedn = cn=%s,dc=centera,dc=com

After change the configuration, we restart the service to ensuare the configuration takes effect.
Then we try to login the Harbor GUI with Active Directory user, e.g:  ee1@centera.com, however it failed with error Invalid credentials.

3)Log files, you can get them by package the /var/log/harbor/ 

Logs  when login via GUI or docker client,

==> /var/log/harbor/2016-05-19/docker_ui.log <==
May 19 05:02:10 starhost docker/ui[66486]: 2016/05/19 09:02:10 #033[1;34m[router.go:828][D] | GET        | /signIn                                  | 4.811597ms       | match      | /signIn                                  | #033[0m
May 19 05:02:11 starhost docker/ui[66486]: 2016-05-19T09:02:11Z [WARNING] No user id in session, canceling request
May 19 05:02:21 starhost docker/ui[66486]: 2016-05-19T09:02:21Z [DEBUG] [authenticator.go:52]: Current AUTH_MODE is ldap_auth
May 19 05:02:21 starhost docker/ui[66486]: 2016-05-19T09:02:21Z [DEBUG] [ldap.go:47]: ldapURL:ldap://10.32.167.175:389
May 19 05:02:21 starhost docker/ui[66486]: 2016-05-19T09:02:21Z [DEBUG] [ldap.go:69]: baseDn:cn=ee1,dc=centera,dc=com
May 19 05:02:21 starhost docker/ui[66486]: 2016-05-19T09:02:21Z [ERROR] [login.go:54]: Error occurred in UserLogin: LDAP::Bind() error (49) : Invalid credentials

We also tried with openldap, it works fine.

**Comment by tonardo2015** [comment]
Any progress for this issue?

**Comment by tonardo2015** [comment]
Sorry for late reply.
Yes, we do the test with ldapsearch, the account and the credential is
right, but the login  failed.

Do you have any progress for your AD Testing?
If it works in your environment, could you pls let us know how you do the
configuration?

Thanks a lot!

**Comment by wemeya** [comment]
@tonardo2015 
Yes, we reproduced your issue in our environment. I will confirm and solve the problem with my colleagues as soon as possible. See the articles listed below, maybe they help.
[https://www.ldap.com/the-ldap-bind-operation](url)
[http://clintboessen.blogspot.com/2011/06/error-49-ldapsimplebinds-failed-invalid.html](url)

**Comment by wemeya** [comment]
@tonardo2015 
Hi, we succeeded in our test environment. Our AD serve is like below, we use a ldap client named JXplorer:

![image](https://cloud.githubusercontent.com/assets/12540577/16108153/18b30ce2-33d4-11e6-966d-cd242ca508a4.png)

click search buttion:
![image](https://cloud.githubusercontent.com/assets/12540577/16108203/6ea15302-33d4-11e6-9f19-3f5a042b790c.png)

You can see the text in the Start Searching From textbox: CN=Jack Liu,OU=ljack,DC=crt,DC=fvt

Then you can configure your harbor.cfg like this:

![image](https://cloud.githubusercontent.com/assets/12540577/16108290/e0d7e68e-33d4-11e6-862e-d8a8e99ef028.png)

If your AD server uses TLS/SSL, you need change the ldap_url = ldaps://......

Then you run ./prepare, docker-compose build and docker compose up -d 
Open browser, input username and password, in ourcase it's Jack Liu and his password in AD.
clike sign in, you will see:
![image](https://cloud.githubusercontent.com/assets/12540577/16108395/72931846-33d5-11e6-895d-2b2f1540c365.png)

**Comment by tonardo2015** [comment]
Thanks Weme, I will try it.

**Comment by reasonerjt** [comment]
@tonardo2015 have you had a chance to try?

**Comment by tonardo2015** [comment]
Hi Daniel,

The issue is still there, we are still not able to login Harbor with
Microsoft AD as LDAP server.

**Comment by tonardo2015** [comment]
Our latest try with AD.

I tried the settings from VMware engineer and also many other options but still same error.

Following is what I have tried:

1.	With and without port 389 in the ldap_url
2.	Ldap and ldaps in Ldap_url
3.	Created a new OU and a new user account

Seems we stuck here. Can we ask the VMware engineer for further investigation?

auth_mode = ldap_auth
ldap_url = ldap://10.32.167.175:389
ldap_basedn = CN=%s,OU=test,DC=Centera,DC=com

==> /var/log/harbor/2016-05-19/docker_ui.log <==
Jul 18 23:53:55 starhost docker/ui[21215]: 2016-07-19T03:53:55Z [DEBUG] [authenticator.go:52]: Current AUTH_MODE is ldap_auth
Jul 18 23:53:55 starhost docker/ui[21215]: 2016-07-19T03:53:55Z [DEBUG] [ldap.go:47]: ldapURL:ldap://10.32.167.175:389
Jul 18 23:53:55 starhost docker/ui[21215]: 2016-07-19T03:53:55Z [DEBUG] [ldap.go:69]: baseDn:CN=manz@centera.com,OU=test,DC=Centera,DC=com
Jul 18 23:53:55 starhost docker/ui[21215]: 2016-07-19T03:53:55Z [ERROR] [login.go:54]: Error occurred in UserLogin: LDAP::Bind() error (49) : Invalid credentials  


Jul 18 02:10:02 starhost docker/ui[21215]: 2016-07-18T06:10:02Z [DEBUG] [authenticator.go:52]: Current AUTH_MODE is ldap_auth
Jul 18 02:10:02 starhost docker/ui[21215]: 2016-07-18T06:10:02Z [DEBUG] [ldap.go:47]: ldapURL:ldaps://10.32.167.175:389
Jul 18 02:10:02 starhost docker/ui[21215]: 2016-07-18T06:10:02Z [DEBUG] [ldap.go:69]: baseDn:CN=manz@centera.com,OU=users,DC=centera,DC=com
Jul 18 02:10:02 starhost docker/ui[21215]: 2016-07-18T06:10:02Z [ERROR] [login.go:54]: Error occurred in UserLogin: LDAP::Bind() error (-1) : Can't contact LDAP server

**Comment by wemeya** [comment]
@tonardo2015 
Can you connect your AD server with a LDAP client, and right click the relevant user, and check what his or her CN is. It seems that CN=manz@centera.com is not right, use the right CN to login.

**Comment by wemeya** [comment]
@tonardo2015 
Hi, our AD server is also windows 2003, the version 5.2.3790.3959.

**Comment by tonardo2015** [comment]
Hi Wemeya,

Thanks for continuously support, finally, we find some clue.
To successfully login, we need to assign UPN or email address for the user
or he/she can not successfully login.
But we are not sure if this is one valid limitation or not.

One another thing we notice is when the AD user successfully login harbor,
harbor will not create user profile for him/she.
It seems like one bug.

I will open one issue for it later.

Thanks a lot!

**Comment by wemeya** [comment]
@tonardo2015 
Actually, Harbor only needs the UPN(CN), if the user does not have an email, Harbor will automatically assign one to him/her. Like we have configured in the harbor.cfg: CN=%s, OU=...,DC=..., DC=..., CN is a must.
For the bug you mentioned, Harbor will create a user account for the LDAP user, which is definitely sure. 
You can feed us your issue back and I will see what's wrong.

**Comment by wemeya** [comment]
@tonardo2015 
If no question, we'll close the issue later. You're welcome and feel free to reopen it if you have further questions .

**Comment by tonardo2015** [comment]
Thanks@wemeya, the issue is solved, close this ticket.

**Comment by tonardo2015** [comment]
Thanks @wemeya, it is ok for us to close this ticket. Thanks for all the
kind help!
