### ISSUE TITLE
customized port error

### ISSUE THREAD

**Issue by lvsir625** [vmware/harbor#2540]
docker version :1.12.6
docker-compose version：1.13.0
some  config  of  harbor.cfg：
      hostname = 18.16.202.24:5000

error log：
      Jun 16 10:27:37 172.18.0.1 registry[13331]: time="2017-06-16T02:27:37.00656902Z" level=debug msg="authorizing request" go.version=go1.7.5 http.request.host="18.16.202.24:5000" http.request.id=573c208a-7c6e-41c8-befe-d797af814bc6 http.request.method=GET http.request.remoteaddr=18.16.202.24 http.request.uri="/v2/" http.request.useragent="docker/1.12.6 go/go1.7.4 kernel/3.10.0-327.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \\(linux\\))" instance.id=c4632b1a-6ebf-4c3c-998e-995b0e354a96 service=registry version=v2.6.1 
Jun 16 10:27:37 172.18.0.1 registry[13331]: time="2017-06-16T02:27:37.006740545Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.5 http.request.host="18.16.202.24:5000" http.request.id=573c208a-7c6e-41c8-befe-d797af814bc6 http.request.method=GET http.request.remoteaddr=18.16.202.24 http.request.uri="/v2/" http.request.useragent="docker/1.12.6 go/go1.7.4 kernel/3.10.0-327.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \\(linux\\))" instance.id=c4632b1a-6ebf-4c3c-998e-995b0e354a96 service=registry version=v2.6.1 
Jun 16 10:27:37 172.18.0.1 registry[13331]: 172.18.0.7 - - [16/Jun/2017:02:27:36 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/1.12.6 go/go1.7.4 kernel/3.10.0-327.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \\(linux\\))"
Jun 16 10:31:50 172.18.0.1 registry[13331]: time="2017-06-16T02:31:50.65710014Z" level=debug msg="authorizing request" go.version=go1.7.5 http.request.host="18.16.202.24:5000" http.request.id=85290c1c-d85e-436f-af74-98b3c0097437 http.request.method=GET http.request.remoteaddr=18.16.202.24 http.request.uri="/v2/" http.request.useragent="docker/1.12.6 go/go1.7.4 kernel/3.10.0-327.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \\(linux\\))" instance.id=c4632b1a-6ebf-4c3c-998e-995b0e354a96 service=registry version=v2.6.1 
Jun 16 10:31:50 172.18.0.1 registry[13331]: time="2017-06-16T02:31:50.657212224Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.5 http.request.host="18.16.202.24:5000" http.request.id=85290c1c-d85e-436f-af74-98b3c0097437 http.request.method=GET http.request.remoteaddr=18.16.202.24 http.request.uri="/v2/" http.request.useragent="docker/1.12.6 go/go1.7.4 kernel/3.10.0-327.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \\(linux\\))" instance.id=c4632b1a-6ebf-4c3c-998e-995b0e354a96 service=registry version=v2.6.1 
Jun 16 10:31:50 172.18.0.1 registry[13331]: 172.18.0.7 - - [16/Jun/2017:02:31:50 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/1.12.6 go/go1.7.4 kernel/3.10.0-327.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \\(linux\\))"

**Comment by lvsir625** [comment]
I want  to modify the default  insecure-registry  port  from 80 to  5000

**Comment by lvsir625** [comment]
and  the above logs is the error log when I push the image

**Comment by lvsir625** [comment]
the following is the content of proxy.log:
Jun 16 10:56:17 172.18.0.1 proxy[13331]: 18.16.202.24 - "GET /service/token?account=admin&scope=repository%3Aapphouse%3Apush%2Cpull&service=harbor-registry HTTP/1.1" 500 0 "-" "docker/1.12.6 go/go1.7.4 kernel/3.10.0-327.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \x5C(linux\x5C))" 0.007 0.007 .
Jun 16 10:56:17 172.18.0.1 proxy[13331]: 18.16.202.24 - "GET /service/token?account=admin&scope=repository%3Aapphouse%3Apush%2Cpull&service=harbor-registry HTTP/1.1" 500 0 "-" "docker/1.12.6 go/go1.7.4 kernel/3.10.0-327.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \x5C(linux\x5C))" 0.006 0.006 .
Jun 16 10:56:17 172.18.0.1 proxy[13331]: 18.16.202.24 - "GET /service/token?account=admin&scope=repository%3Aapphouse%3Apush%2Cpull&service=harbor-registry HTTP/1.1" 500 0 "-" "docker/1.12.6 go/go1.7.4 kernel/3.10.0-327.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \x5C(linux\x5C))" 0.006 0.006 .

**Comment by lvsir625** [comment]
the following is the content of 
Jun 16 10:56:55 172.18.0.1 ui[13331]: 2017-06-16T02:56:55Z [DEBUG] [creator.go:206]: scopes: [repository:apphouse:push,pull]
Jun 16 10:56:55 172.18.0.1 ui[13331]: 2017-06-16T02:56:55Z [WARNING] Failed to get secret cookie, error: http: named cookie not present
Jun 16 10:56:55 172.18.0.1 ui[13331]: 2017-06-16T02:56:55Z [DEBUG] [authenticator.go:59]: Current AUTH_MODE is db_auth
Jun 16 10:56:55 172.18.0.1 ui[13331]: 2017-06-16T02:56:55Z [DEBUG] [authutils.go:46]: scopes: [repository:apphouse:push,pull]
Jun 16 10:56:55 172.18.0.1 ui[13331]: 2017-06-16T02:56:55Z [DEBUG] [authutils.go:87]: user: admin, access: &{repository  apphouse [push pull]}
Jun 16 10:56:55 172.18.0.1 ui[13331]: 2017-06-16T02:56:55Z [ERROR] [token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: apphouse
Jun 16 10:56:56 172.18.0.1 ui[13331]: 2017-06-16T02:56:56Z [DEBUG] [token.go:35]: URL for token request: /service/token?account=admin&scope=repository%3Aapphouse%3Apush%2Cpull&service=harbor-registry
Jun 16 10:56:56 172.18.0.1 ui[13331]: 2017-06-16T02:56:56Z [DEBUG] [creator.go:206]: scopes: [repository:apphouse:push,pull]
Jun 16 10:56:56 172.18.0.1 ui[13331]: 2017-06-16T02:56:56Z [WARNING] Failed to get secret cookie, error: http: named cookie not present
Jun 16 10:56:56 172.18.0.1 ui[13331]: 2017-06-16T02:56:56Z [DEBUG] [authenticator.go:59]: Current AUTH_MODE is db_auth

**Comment by lvsir625** [comment]
下面是推送镜像时控制台报错
The push refers to a repository [18.16.202.24:5000/apphouse]
54b42228c0e4: Retrying in 1 second 
0a5360ef55cd: Retrying in 1 second 
77a4cbe3acdf: Retrying in 1 second 
62d4d6faa08e: Retrying in 1 second 
b6215f339e78: Retrying in 1 second 
8f01a53880b9: Waiting 
received unexpected HTTP status: 500 Internal Server Error

**Comment by lvsir625** [comment]
问题已经解决，我没有创建项目，创建了个test项目后是正常的
[root@lvsir24 harbor]# docker push 18.16.202.24:5000/test/apphouse
The push refers to a repository [18.16.202.24:5000/test/apphouse]
54b42228c0e4: Pushed 
0a5360ef55cd: Pushed 
77a4cbe3acdf: Pushed 
62d4d6faa08e: Pushed 
b6215f339e78: Pushed 
8f01a53880b9: Pushed 
latest: digest: sha256:9af83ed09bcbce72023dee9376094e4f3f19a37dbc0928d918b2d6e6ff2982bb size: 1577
但是我本地的已经仓库上传直接就是18.16.202.24:5000/apphouse样式的，如果现在要用harbor的话打镜像时候要每个配置都要在前面加上test，请问可否修改配置直接18.16.202.24:5000/apphouse

**Comment by reasonerjt** [comment]
No, it has to have a namespace, i.e. project..

**Comment by lvsir625** [comment]
ok。3ks
