### ISSUE TITLE
mirror 模式下镜像列表及 tag 列表显示极为缓慢或显示不出来

### ISSUE THREAD

**Issue by nanpuyue** [vmware/harbor#2545]
Docker version 1.12.6, build 78d1802
docker-compose version 1.8.0

[harbor_logs.tar.gz](https://github.com/vmware/harbor/files/1080081/harbor_logs.tar.gz)
[harbor_config.tar.gz](https://github.com/vmware/harbor/files/1080082/harbor_config.tar.gz)
![20170616155906](https://user-images.githubusercontent.com/1524609/27217521-c263d44a-52ac-11e7-8aad-61a585f9fc4d.png)

tag列表空白

**Comment by reasonerjt** [comment]
Closing as won't fix, because for now it's not supported to configure Harbor as a mirror.
