### ISSUE TITLE
new replication rule window button not properly grayed out

### ISSUE THREAD

**Issue by hainingzhang** [vmware/harbor#2552]
when creating a new replication rule, 
test connection button should be grayed out when there is no endpoint selected or input.

When testing connection, "test connection" and "cancel" button should be grayed out.

Or "Cancel" can be enabled, but should really delete the connection, not just hiding the dialog box. 

Same to the create endpoint dialog.

**Comment by steven-zou** [comment]
Fixed by @pengpengshui , code merged into master. Close issue.
