### ISSUE TITLE
A bad request "GET /api/projects?public=-1" is sent after changing the public of project

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#2556]
The "public" in query string should be 0, 1, false, true.

**Comment by reasonerjt** [comment]
Is this request form UI?

**Comment by steven-zou** [comment]
Found in latest master branch? I think I have fixed the issue. Please check latest code in master.

**Comment by steven-zou** [comment]
Problem is already fixed in master. Close this issue.
