### ISSUE TITLE
upgrade script skips some ldap settings in harbor.cfg

### ISSUE THREAD

**Issue by dejwsz** [vmware/harbor#2557]
I was trying to upgrade harbor.cfg from release version 0.5.0 to 1.1.2 by using upgrade script. Three ldap settings were skipped/ignored and I had to set them manually after the upgrade is finished: ldap_searchdn, ldap_search_pwd and ldap_filter.

**Comment by wy65701436** [comment]
how did you run the upgrade script? Can you provide the source cfg file?

**Comment by dejwsz** [comment]
Accordingly to the guide and yes I pointed to the source cfg file. Like this:
./upgrade --source-loc /opt/harbor-0.5.0/harbor.cfg --source-version 0.5.0 --target-loc /opt/harbor/harbor.cfg --target-version 1.1.x

**Comment by dejwsz** [comment]
I can't provide the cfg file as there are many fragile data inside which I cannot reveal - the registry is a private instance inside our organization. Simply not all ldap attributes are processed somehow - the rest is OK. One of it is a password - maybe some characters are not accepted which is in our complicated ldap access password or something?

**Comment by wy65701436** [comment]
Is there an '#' in the beginning of the line(ldap_searchdn, ldap_search_pwd and ldap_filter)? But with the correct values.

**Comment by dejwsz** [comment]
Yes there were '#' signs in the beginning of the lines but with some default values as I understand. The real values from source config weren't copied at all.
Such entries came up:

#A user's DN who has the permission to search the LDAP/AD server.
#If your LDAP/AD server does not support anonymous search, you should configure this DN and ldap_search_pwd.
#ldap_searchdn = uid=searchuser,ou=people,dc=mydomain,dc=com

#the password of the ldap_searchdn
#ldap_search_pwd = password

#Search filter for LDAP/AD, make sure the syntax of the filter is correct.
#ldap_filter = (objectClass=person)

**Comment by wy65701436** [comment]
Ok, thx. I will have a debug.

**Comment by wy65701436** [comment]
@dejwsz  as we do not provide tool to upgrade harbor.cfg in the latest release, please handle this manually. 
And, you can open an new feature request if need one tool/script in the upgrade process. I just close it.
