### ISSUE TITLE
Increase items displayed per page for a given search string in Registry

### ISSUE THREAD

**Issue by lgayatri** [vmware/harbor#2568]
From the screenshot we can see that when searched "busybox"  in Registry, the page displayed only 3 rows though 50 matches were found. 
Displaying only three matched entities is too less. 10 would be optimal. 
Same is the case with Projects(only 5 matched entities are displayed and 10 would be optimal).
Please consider this UI enhancement. 

![increase-items-displayed-per-page](https://user-images.githubusercontent.com/25006749/27279011-ce09b9ee-5500-11e7-8dba-908411fca17f.PNG)
![increase-items-displayed-per-project](https://user-images.githubusercontent.com/25006749/27279204-99464d52-5501-11e7-80a0-3fa3a4be3285.PNG)

**Comment by steven-zou** [comment]
@lgayatri 

  Thanks for raising issues, we'll carefully consider your comments and find proper time to put the fix in.

**Comment by steven-zou** [comment]
Fixed in PR #2601, increase page size to 15
