### ISSUE TITLE
Login Succeeded but return IdentityToken is ""

### ISSUE THREAD

**Issue by shaowin16** [vmware/harbor#2571]
I have deployed a registry in 121.40.83.23.
My docker  server is 123.56.208.223 and has publish the port of 2375.
Follow is my request:

```
POST http://123.56.208.223:2375/auth

{
"username": "admin",
"password": "admin123",
"email": "xxxx@qq.com",
"serveraddress": "121.40.83.23"
}
```
and the reponse:

```
{
	"IdentityToken": "",
	"Status": "Login Succeeded"
}
```
Can you tell me why IdentityToken is ""?

**Comment by reasonerjt** [comment]
The response is from Docker, I think you need to check the code of docker or ask in docker's repo...

**Comment by reasonerjt** [comment]
Close due to inactivity.
