### ISSUE TITLE
need to print raw sql of beego orm into docker_mysql.log for debug reason

### ISSUE THREAD

**Issue by wemeya** [vmware/harbor#258]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose
2)Config files of harbor, you can get them by packaging "Deploy/config" directory
3)Log files, you can get them by package the /var/log/harbor/ 

If we use orm, it is better to output orm logs into files to make it convenient to check orm errors. Hope to realize this feature.

**Comment by saga92** [comment]
I will handle this.

**Comment by reasonerjt** [comment]
If you use raw sql you need to log it manually, if you use orm's exposed method there's a flag in orm to print the sql commands.

Meanwhile need to consider protecting sensitive data from leaked in the log.

**Comment by saga92** [comment]
use the following code as a solution when debug
```
func main() {
    orm.Debug = true
...
```
don't apply it to the product which may cause performance problem.
Without any problem, you may close this issue. @wemeya
