### ISSUE TITLE
Integration with Admiral

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#2582]
1. Setup Admiral and PSC(vCenter) environment
2. Integrate with token service
3. Integrate with project management service using token
4. Integrate with project management service using service account

**Comment by andrewtchin** [comment]
@ywk253100 please ping me when this is complete

**Comment by ywk253100** [comment]
@andrewtchin OK. We'll start the integration if Admiral's APIs are ready.

**Comment by andrewtchin** [comment]
@ywk253100 Will you be providing a data migration script as part of this story? This migration script is required for https://github.com/vmware/vic/issues/4726

**Comment by ywk253100** [comment]
@andrewtchin  @wy65701436 is responsible for the data migration work.

**Comment by reasonerjt** [comment]
defer to sprint 13.

**Comment by ywk253100** [comment]
Done
