### ISSUE TITLE
x509 Cert Error on Email due to unknown authority

### ISSUE THREAD

**Issue by betazep** [vmware/harbor#2585]
This is from Vsphere Integrated Containers 1.1.1 appliance, so whatever is configure in that relative to docker.  For our test environment, we have an internal CA.  How do I add the root cert trust to Harbor?

Do I docker exec into one of the running containers and add it to the cert store there?  Any advice would be great as I would like to get this running in our test environment as soon as possible, and email would be great.

![x509](https://user-images.githubusercontent.com/22081672/27361055-b3a9650c-55d9-11e7-9f8f-748ceb35ac9b.jpg)

**Comment by betazep** [comment]
Well I guess this is known.  
Can there be a possible workaround for now?

https://github.com/vmware/harbor/issues/1154

**Comment by reasonerjt** [comment]
Hi,

I don't have an env to reproduce and test the solution currently.
But I think you need to import the CA crt into the "harbor-ui" container via `docker cp` and `docker exec`

harbor-ui is based on photonOS and this is how you import a CA to the truststore of the OS:
```cat ./my.crt >> /etc/pki/tls/certs/ca-bundle.crt```

Please have a try and let us know the result.

**Comment by betazep** [comment]
Not working.  I restarted harbor-ui container and CA cert is still appended.  Any other thoughts?

**Comment by betazep** [comment]
Apologies... that did work.  (cert guy gave me the wrong cert... it happens... hehe)

**Comment by reasonerjt** [comment]
OK, closing the issue.
