### ISSUE TITLE
Datagrid not correct after deleting a user

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#2610]
After deleting a user and only 1 user remains the user is deleted but that row is not removed from the datagrid. also, the number of items in the lower right is not updated. ideally if there is only 1 page of items, the footer should just say "1 User" or "3 Users" (no need for "1-2 of 2 ..."

![screen shot 2017-06-22 at 8 35 52 am](https://user-images.githubusercontent.com/626032/27434605-3a6e8182-5727-11e7-964d-60bdc32ad645.png)

**Comment by steven-zou** [comment]
Issue is already fixed, close this issue.
