### ISSUE TITLE
ac9487f63367        vmware/harbor-adminserver:v1.1.2   "/harbor/harbor_ad..."   18 seconds ago      Restarting (1) 3 seconds ago                                                                    

### ISSUE THREAD

**Issue by swq499809608** [vmware/harbor#2611]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
3)Log files, you can get them by package the /var/log/harbor/ .

问题:
ac9487f63367        vmware/harbor-adminserver:v1.1.2   "/harbor/harbor_ad..."   18 seconds ago      Restarting (1) 3 seconds ago

**Comment by reasonerjt** [comment]
please provide log files.

**Comment by reasonerjt** [comment]
Close due to inactivity.
