### ISSUE TITLE
标签数超过一定数量，无法列出镜像信息

### ISSUE THREAD

**Issue by zhaogj1987** [vmware/harbor#2613]
![image](https://user-images.githubusercontent.com/16099451/27464271-ffefd9e2-57fe-11e7-9e8c-c0c9af76df24.png)
![image](https://user-images.githubusercontent.com/16099451/27464284-163d06b6-57ff-11e7-9c97-cc8b96d77ab6.png)

**Comment by reasonerjt** [comment]
How many tags do you have? Do you have a approximate number?

**Comment by zhaogj1987** [comment]
About 19 tags

**Comment by sigsbee** [comment]
would you like to supply your harbor version?

**Comment by zhaogj1987** [comment]
v1.1.1

**Comment by sigsbee** [comment]
I can not reproduce your problem, if you can reproduce it in your environment, do you mind upload the logs under /var/log/harbor ?

**Comment by reasonerjt** [comment]
close due to inactivity.
