### ISSUE TITLE
Dockerfiles for Notary images

### ISSUE THREAD

**Issue by rammaram06** [vmware/harbor#2618]
Hi,

First of all, Thanks for awesome docker registry.
We are building harbor images on top of redhat base images and using them instead of photon images, we would like to use notary with our harbor registry. Would you be able to share the dockerfiles used to build notary on photon, so that we can use similar setup to build on redhat?

**Comment by reasonerjt** [comment]
I need to check, but I recall we just referenced the official image's dockerfile, you can find it on docker hub, what we did is simply compile the code in another image and copy the compiled binary to base image.

**Comment by rammaram06** [comment]
Oh ok Thank you..I have one more question..I see we can bring up harbor with Clair or notary..Can we run harbor with both of them?

**Comment by reasonerjt** [comment]
Yes,  but it's currently a WIP
