### ISSUE TITLE
创建项目显示的时区不一致

### ISSUE THREAD

**Issue by xingxing9688** [vmware/harbor#2619]
1.1.1 harbor 版本， 
harbor 的容器里面时区已经修改，数据库的时区也修改了，但是创建项目依然不是东八区的时间，.

**Comment by reasonerjt** [comment]
Did you try to query the data via DB and what is the timestamp?

Could you verify your browser's setting?

**Comment by reasonerjt** [comment]
There will be another one opened by community user based on my communication. 
Closing this one.
