### ISSUE TITLE
Ldap:unauthorized: authentication required

### ISSUE THREAD

**Issue by chenliping972385283** [vmware/harbor#2625]
1,Docker version 17.05.0-ce, build 89658be;docker-compose version 1.14.0, build c7bdf9e;
2,harbor.cfg:i set the variables only this
     hostname = 192.168.111.133
auth_mode = ldap_auth
dap_url = ldap://xxxx
ldap_basedn = ou=xxx,dc=xxx,dc=com
3,logs:
GET /service/token?account=chenlp&client_id=docker&offline_token=true&service=harbor-registry HTTP/1.1" 401 0 "-" "docker/17.05.0-ce go/go1.7.5 git-commit/89658be kernel/3.10.0-514.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/17.05.0-ce \x5C(linux\x5C))" 1.519 1.519 .
 

when i used admin login in harbor,i test the ldap server ,it can passed.but when i login in with docker command,it occured unauthorized: authentication required.when i first run ./install.sh,the harbor.cfg varliables is setted.what shoud i do?why i can  not login in when i use doker command?thanks.

**Comment by chenliping972385283** [comment]
i have resolved,it is my problem.

**Comment by reasonerjt** [comment]
great.

**Comment by KeithTt** [comment]
遇到相同的情况  楼主怎么解决的？？？

**Comment by xiaonizi-github** [comment]
@KeithTt  ,哈哈哈，一看就知道我就是中式英语啊。貌似很长时间了，我记得ldap数据库的设置可以在页面设置，也可以在配置文件中设置，但有一个前提是添加了一个用户之后就不能再去设置数据库了。这个问题貌似就是与数据库的设置有关，你把那个官方文档再仔细看一下，严格按照步骤来，是没有问题的。

**Comment by KeithTt** [comment]
@xiaonizi-github 哈哈，你的名字一看就是中文。不过我的情况跟你可能还是不太一样，我部署的最新版本1.2.0，在配置文件中添加ldap配置之后没有生效，还单独手动改了一个文件才把验证模式切换到ldap，而且，ldap搜索信息又没生效，后来发现只能在UI上设置。然后发现客户端docker login各种失败。问题真的多。。我这已经解决了，是token服务的问题，把token服务的url改成https就好了。谢谢妹妹啦。
