### ISSUE TITLE
How to compile jobservice image by myself?

### ISSUE THREAD

**Issue by fffffreedom** [vmware/harbor#2626]
hi, 
i add some code to jobservice, and i want to build jobservice by myself.  and  i try to do it in two ways:
- cd  make/dev/jobserice, and run docker build .
[root@www jobservice]# docker build .
Sending build context to Docker daemon  2.048kB
Step 1/7 : FROM golang:1.7.3
 ---> ef15416724f6
Step 2/7 : MAINTAINER jiangd@vmware.com
 ---> Using cache
 ---> 931ba7c7a344
Step 3/7 : COPY . /go/src/github.com/vmware/harbor
 ---> Using cache
 ---> efc8c69a7b87
Step 4/7 : WORKDIR /go/src/github.com/vmware/harbor/src/jobservice
 ---> Using cache
 ---> ba5b57564a08
Step 5/7 : RUN go build -v -a -o /go/bin/harbor_jobservice     && chmod u+x /go/bin/harbor_jobservice
 ---> Running in ccbe8445eb05
**can't load package: package github.com/vmware/harbor/src/jobservice: no buildable Go source files in /go/src/github.com/vmware/harbor/src/jobservice**
The command '/bin/sh -c go build -v -a -o /go/bin/harbor_jobservice     && chmod u+x /go/bin/harbor_jobservice' returned a non-zero code: 1

- https://github.com/vmware/harbor/blob/master/docs/compile_guide.md
do as way II 
[root@www harbor]# make all

Note: golang version: 1.8.3

Note: docker version: 17.05.0

Note: docker-compose version: 1.13.0
compiling binary for clarity ui...
/usr/bin/docker: invalid reference format.
See '/usr/bin/docker run --help'.
make: *** [compile_clarity] Error 125

my GO config
[root@www jobservice]# export | grep GO
declare -x GOPATH="/go/"
declare -x GOROOT="/usr/local/go"

thanks

**Comment by wy65701436** [comment]
Please refer to the Makefile target -- complile_golangimage(jobservice  part).

**Comment by wy65701436** [comment]
@fffffreedom I would like to close it if you don't have question further.
