### ISSUE TITLE
Issue trying to build a version

### ISSUE THREAD

**Issue by tomIharaRznde** [vmware/harbor#2633]
Hi everyone,

**Im trying to compile the Harbor to add a new language and im getting a issue following the guide:**
   https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_vmware_harbor_blob_master_docs_compile-5Fguide.md&d=DwIFAg&c=uilaK90D4TOVoH58JNXRgQ&r=s2CPn_EYVVss7Hme7yCei_jy8c4kV_By39gUs_C9Fx0&m=hZKFjKiugaLRoiIJEGWZourUPfFBKBoDn9HB2_SMXro&s=nwaz-dUNwuS_wYegfpwTzKj4vBIJDt5L93hjhZngT_E&e= 

   **I downloaded the source using:**

   $ git clone https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_vmware_harbor&d=DwIFAg&c=uilaK90D4TOVoH58JNXRgQ&r=s2CPn_EYVVss7Hme7yCei_jy8c4kV_By39gUs_C9Fx0&m=hZKFjKiugaLRoiIJEGWZourUPfFBKBoDn9HB2_SMXro&s=6FeW0gOmAwLiRCFsqRh1kQw9lyqLytd7nS0ETSXz5y0&e= 

   **I made the changes to add the language following the guide:**
   https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_vmware_harbor_blob_master_docs_developer-5Fguide-5Fi18n.md&d=DwIFAg&c=uilaK90D4TOVoH58JNXRgQ&r=s2CPn_EYVVss7Hme7yCei_jy8c4kV_By39gUs_C9Fx0&m=hZKFjKiugaLRoiIJEGWZourUPfFBKBoDn9HB2_SMXro&s=LYVxPt967XxGMZCe4X1CoKYN2q7XShl4D6nksockV74&e= 

   **Then I executed the following steps:**
      $ cd harbor
      $ vi make/harbor.cfg

*   Get offcial Golang image from docker hub:

      $ docker pull golang:1.7.3

*   Build, install and bring up Harbor without Notary:

      $ make install GOBUILDIMAGE=golang:1.7.3 COMPILETAG=compile_golangimage CLARITYIMAGE=vmware/harbor-clarity-ui-builder:1.1.2

-----
**I tried using my OS macosx (El Capitain 10.11.6), and others OS (CentOS7, Fedora23, Ubuntu16.04) using vagrant/VirtualBox and Im getting different issue by OS.**

   **In my MacOSX got the following:**
   sed: 1: "/private/tmp/harbor/mak ...": undefined label 'mp/harbor/make/docker-compose.yml'
   make: *** [modify_composefile] Error 1

   **Another example, in CentOS7 I got the following:**
   Error File '/harbor_ui/src/app/app.module.ts' not found.
   Error File '/harbor_ui/src/main-aot.ts' not found.
   make: *** [compile_clarity] Error 1

   **Any clue?

   Thank you in advance.**

**1)Version of docker engine and docker-compose.**
Note: golang version: 1.7.4
Note: docker version: 17.03.1
Note: docker-compose version: 1.11.2
**2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.**
Attached.
**3)Log files, you can get them by package the /var/log/harbor/ .**
Attached.
[Archive.zip](https://github.com/vmware/harbor/files/1102111/Archive.zip)

**Comment by wy65701436** [comment]
if you are building from the master code, please use the builder 1.2.6.

**Comment by tomIharaRznde** [comment]
Thanks for your answer,

I did the clone again from harbor and im using harbor-clarity-ui-builder:1.2.6, and I got another error now:
$ make install GOBUILDIMAGE=golang:1.7.3 COMPILETAG=compile_golangimage CLARITYIMAGE=vmware/harbor-clarity-ui-builder:1.2.6

Note: golang version: 1.7.4

Note: docker version: 17.03.1

Note: docker-compose version: 1.11.2
compiling binary for clarity ui...
mv: inter-device move failed: '/harbor_resources/node_modules' to './node_modules'; unable to remove target: Directory not empty
make: *** [compile_clarity] Error 1

**Comment by wy65701436** [comment]
Sorry about that, as we are working on builder updating, this one is out of date, now is 1.2.7. Let me know if it is still exist. 

BTW, master is not an stable branch, if you want to try Harbor, feel free to use the latest release.

**Comment by tomIharaRznde** [comment]
Hi Yan,

I changed the clone to branch **release-1.1.0** and executed the make against the **harbor-clarity-ui-builder:1.2.7**, getting another error:
$ make install GOBUILDIMAGE=golang:1.7.3 COMPILETAG=compile_golangimage CLARITYIMAGE=vmware/harbor-clarity-ui-builder:1.2.7

Note: golang version: 1.7.4

Note: docker version: 17.03.1

Note: docker-compose version: 1.11.2
compiling binary for clarity ui...
/entrypoint.sh: line 4: cd: /harbor_src/ui_ng: No such file or directory
make: *** [compile_clarity] Error 1

**Comment by wy65701436** [comment]
The builder is changing. You can get the usable version from the compile guide, we will update this doc if any change. 

For release 1.1.0, the builder version is 0.8.4. Why don't try the offline installer?

**Comment by wy65701436** [comment]
If you want to commit code, you'd better to use the master branch. 1.2.7 is now for master, again, it's changing, please see the doc as I mentioned.

Another way to get the compile method is to refer the Travis script, it contains the latest builder version.

**Comment by reasonerjt** [comment]
Close due to inactivity.
