### ISSUE TITLE
download Harbor-1.1.2 source code execute docker-compose up,visit harbor home page came up with the  error that cann't find js 

### ISSUE THREAD

**Issue by bianhua2015** [vmware/harbor#2640]
![image](https://user-images.githubusercontent.com/12478883/27575167-6ee75f74-5b4b-11e7-9b9b-0b5e09ed8abe.png)

**Comment by wy65701436** [comment]
did you use make to compile the source code? If you want to try Harbor, please use the offline installer.

**Comment by bianhua2015** [comment]
because I need to modify source code to add some function，,the offline installer is not not suitable for me，when I build the source code  without a eero,but visiting harbor home page ,the page can not load js

**Comment by wy65701436** [comment]
How did you build the source code?

**Comment by bianhua2015** [comment]
I download the  source code and modify the file  in the folder of /harbor-1.1.2/src/ui/auth,then I execute docker-compose build  to build the image.

**Comment by wemeya** [comment]
I got the similar error, I pulled the newest code, and make according to the use_make.md.  It returns:
![image](https://user-images.githubusercontent.com/12540577/27686998-b8552cb4-5d07-11e7-9c34-306a367391c0.png)

**Comment by bianhua2015** [comment]
@wy65701436  Is the way  I use to  build image ok??

I download the source code and modify the file in the folder of /harbor-1.1.2/src/ui/auth,then I execute docker-compose build to build the image.

**Comment by wemeya** [comment]
problem solved when changed to harbor-clarity-builder:1.2.7.

**Comment by bianhua2015** [comment]
@wemeya how to change harbor-clarity-builder:1.2.7.

**Comment by wemeya** [comment]
see docs/use_make.md make install.

**Comment by wy65701436** [comment]
You need to refer to the compile guide.

**Comment by bianhua2015** [comment]
@wemeya @wy65701436 thank you very much ,the problem has solved
