### ISSUE TITLE
I can't login my harbor while i use "docker login xxxx"

### ISSUE THREAD

**Issue by niuchp** [vmware/harbor#2641]
docker : 1.12
docker-compose : 1.12
harbor iamges: v1.1.2

i just change "http" to "https", change domain, and generate the server.key server.crt
then, execute ./install.sh

Now, i can login harbor by browser, but can't by "docker login xxx.com"

log:
[root@harbor make]# docker login 'mydomain'
Username: admin
Password:
Error response from daemon: Login: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.11.5</center>
</body>
</html>
 (Code: 404; Headers: map[Server:[nginx/1.11.5] Date:[Tue, 27 Jun 2017 07:57:56 GMT] Content-Type:[text/html] Content-Length:[169]])

can u help me? Thinks!

**Comment by niuchp** [comment]
This problem already has been sloved. There is an error is nginx.conf
1. docker-compose down
2. sed s%ui\/registryproxy%registry%g  harbor/make/common/config/nginx/nginx.conf
3. docker-compose up -d
it's work!

[root@harbor ~]# docker login ''my domain''
Username: admin
Password:
Login Succeeded
[root@harbor ~]#

**Comment by little-humor** [comment]
出于安全考虑，harbor服务器只能内网连接，我在上层配置了nginx作为入口，通过119.18.193.77:1952（上层nginx转发的是harbor服务器的内网地址10.6.52.5）可以正常访问harbor的ui界面，但是无法docker login 119.18.193.77:1952；该命令执行后的日志信息是：Error response from daemon: Get http://119.18.193.77:1952/v2/: Get http://10.6.52.5/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: net/http: request canceled (Client.Timeout exceeded while awaiting headers) (Client.Timeout exceeded while awaiting headers)harbor.cfg内容片段：_version = 1.5.0hostname = 10.6.52.5ui_url_protocol = httpno_proxy = 127.0.0.1,localhost,uiauth_mode = db_auth...
--


您好，您有遇到类似的问题吗？如果可以的话，稍微占用一点您的时间，帮助我解决一下。谢谢🙏

**Comment by jarvisqi** [comment]
@little-humor 
你好，遇到一样的问题，请问您是怎么解决的？？

**Comment by CoderLiuyang** [comment]
@little-humor 我也遇到了。。。。
