### ISSUE TITLE
Left nav loses highlighting when in Replication -> Replication Rule

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#2662]
when navigating to admin replication, the highlight is lost when selecting the second tab (Replication Rule) see images. (using https://10.112.122.204/harbor/replications/rules)

![screen shot 2017-06-28 at 10 45 44 am](https://user-images.githubusercontent.com/626032/27643528-595d2f18-5bef-11e7-91a1-135484b28539.png)

![screen shot 2017-06-28 at 10 45 53 am](https://user-images.githubusercontent.com/626032/27643538-5d530f8e-5bef-11e7-985b-7597e4feac59.png)

**Comment by steven-zou** [comment]
@pengpengshui 

  Please take a look at this issue!
