### ISSUE TITLE
[BUG] swagger 404 Page Not Found

### ISSUE THREAD

**Issue by fffffreedom** [vmware/harbor#2664]
hi
i'm using v1.1.2
i followed the guide:
https://github.com/vmware/harbor/blob/master/docs/configure_swagger.md
but http://192.168.56.107/static/vendors/swagger/index.html can't not be openned
it shows "404 Page Not Found"

is there any step missed by the guide?

log 
==> /var/log/harbor/2017-06-29/proxy.log <==
Jun 28 21:19:43 172.18.0.1 proxy[1162]: 192.168.56.1 - "GET /static/vendors/swagger/index.html HTTP/1.1" 404 513 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" 0.005 0.005 .

thanks

**Comment by fffffreedom** [comment]
i find the problem in guide: https://github.com/vmware/harbor/blob/master/docs/configure_swagger.md

we should use absolute path below:
    ## add two lines as below ##
    - ../src/ui/static/vendors/swagger-ui-2.1.4/dist:/harbor/static/vendors/swagger
    - ../src/ui/static/resources/yaml/swagger.yaml:/harbor/static/resources/yaml/swagger.yaml
for me that is: 
    - /root/harbor/src/ui/static/vendors/swagger-ui-2.1.4/dist:/harbor/static/vendors/swagger
    - /root/harbor/src/ui/static/resources/yaml/swagger.yaml:/harbor/static/resources/yaml/swagger.yaml

**Comment by reasonerjt** [comment]
The guide on master branch should work with master code.

**Comment by wemeya** [comment]
Pls make sure the path you add to the docker-compose.yml is right, cause we suppose you operate under harbor directory, then the script will make src directory outside harbor, the absolute path should be /root/src... (as you provided) if you don't move.  You can configure swagger totally according to the doc and try again.  @fffffreedom

**Comment by fffffreedom** [comment]
thanks all
