### ISSUE TITLE
project replicate failed

### ISSUE THREAD

**Issue by chenliping972385283** [vmware/harbor#2668]
1,Docker version 17.05.0-ce, build 89658be;docker-compose version 1.14.0, build c7bdf9e;
2  setting:i set the variables following this:
   harbor.cfg
         hostname = 192.168.111.133
        auth_mode = ldap_auth
       dap_url = ldap://xxxx
        ldap_basedn = ou=xxx,dc=xxx,dc=com
 config/registry/config.yml 
        proxy:
           remoteurl: https://registry-1.docker.io
          username: username
          password: passwoord
   /etc/docker/daemon.json
         "registry-mirrors":["my.registry.com"]

for example:
1,harbor A and harbor B,I replicate A's project to B,
2,project C(This project was pushed up from my local  docker command)，  project D（i pulled form registry.docker-cn.com）
when I replicate the project C,that is succeed,  but when i replicate the project D,it is failed,  i don't know why?can you help me?and i have seen the log,that is normal.

**Comment by chenliping972385283** [comment]
@reasonerjt

**Comment by reasonerjt** [comment]
@chenliping972385283 let me clarify.

When you say "it is failed" do you mean the job is in Error State?

**Comment by reasonerjt** [comment]
Close due to inactivity.
