### ISSUE TITLE
Too many configuration options returned by configuration API

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#2669]
`
{
  "admiral_url": {
    "value": "NA",
    "editable": true
  },
  "auth_mode": {
    "value": "ldap_auth",
    "editable": true
  },
  "cfg_expiration": {
    "value": 5,
    "editable": true
  },

  "email_host": {
    "value": "smtp.mydomain.com",
    "editable": true
  },
  "email_identity": {
    "value": "",
    "editable": true
  },
  "ext_endpoint": {
    "value": "http://reg.mydomain.com",
    "editable": true
  },
  "ldap_base_dn": {
    "value": "ou=atc,dc=harbor,dc=com",
    "editable": true
  },
  "ldap_filter": {
    "value": "",
    "editable": true
  },
  "ldap_scope": {
    "value": 3,
    "editable": true
  },
  "ldap_search_dn": {
    "value": "cn=administrator,cn=users,dc=harbor,dc=com",
    "editable": true
  },
  "ldap_timeout": {
    "value": 5,
    "editable": true
  },
  "max_job_workers": {
    "value": 3,
    "editable": true
  },
  "project_creation_restriction": {
    "value": "everyone",
    "editable": true
  },
  "registry_url": {
    "value": "http://registry:5000",
    "editable": true
  },
  "scan_all_policy": {
    "value": {
      "type": "daily",
      "parameter": {
        "daily_time": 0
      }
    },
    "editable": true
  },
  "self_registration": {
    "value": true,
    "editable": true
  },
  "sqlite_file": {
    "value": "",
    "editable": true
  },
  "token_expiration": {
    "value": 60,
    "editable": true
  },
  "use_compressed_js": {
    "value": false,
    "editable": true
  },
  "verify_remote_cert": {
    "value": false,
    "editable": true
  },
  "with_clair": {
    "value": true,
    "editable": true
  },
  "with_notary": {
    "value": false,
    "editable": true
  }
}
`

**Comment by ywk253100** [comment]
Done
