### ISSUE TITLE
We may need to set the clair update interval to 12 hours or more. 

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#2677]
See this bug in clair:
https://github.com/coreos/clair/issues/419

**Comment by reasonerjt** [comment]
Thanks! 
And btw it seems to me a bug for the RHEL updater

**Comment by reasonerjt** [comment]
Keep it short for now for testing, will update it to 12h before releasing.

**Comment by reasonerjt** [comment]
fixed in #3092
