### ISSUE TITLE
tool tip was cut on ui with clair in chrome 59

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#2679]
v1.1.2-376-gea827ff
tool tip was cut on ui with clair in chrome 59
![crome](https://user-images.githubusercontent.com/23101283/27724930-a5977d76-5da6-11e7-82af-babac9f63424.PNG)

**Comment by steven-zou** [comment]
@sigsbee 

Not use latest code.

**Comment by steven-zou** [comment]
Fixed. Code merged into master.
