### ISSUE TITLE
there should be a rescan button

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#2680]
v1.1.2-376-gea827ff
now scan now can be click only one time and after scan show the result.
there should be a rescan button, so user can scan their image by manual at anytime

**Comment by lweitzman** [comment]
can the rescan action be put on the menu for the row? given that the vulnerabilities column will already have information about the status of the scan or a button for the "scan now" action, there isn't room in the column.

**Comment by steven-zou** [comment]
We have scan call policy to "daily" or "Upon refresh" scan all the images, do we really need the rescan button/menu?

@lweitzman 
  You made the decision.

**Comment by steven-zou** [comment]
We have it now!
