### ISSUE TITLE
 Ceph swift delete image error

### ISSUE THREAD

**Issue by xingxing9688** [vmware/harbor#2684]
1. docker  1.12.6
2. docker-compose 1.13.0
3. harbor 1.1.1

delete images 

Jul  1 22:51:08 172.18.0.1 registry[671]: time="2017-07-01T22:51:08.35405249+08:00" level=debug msg="(*manifestStore).Delete" auth.user.name=wangxxg go.version=go1.7.3 http.request.host="registry:5000" http.request.id=d602a35a-146f-49dc-b8e6-7dd12b5975be http.request.method=DELETE http.request.remoteaddr="172.18.0.5:48572" http.request.uri="/v2/qinzhao-harbor/svntest/manifests/sha256:b94314c2f075f1302370881e9ef991b955bb415ac78326fbd36a00c5bea403ed" http.request.useragent="Go-http-client/1.1" instance.id=b2b64b15-f564-4016-b759-163cc131df33 service=registry vars.name="qinzhao-harbor/svntest" vars.reference="sha256:b94314c2f075f1302370881e9ef991b955bb415ac78326fbd36a00c5bea403ed" version="v2.4.1+unknown" 
Jul  1 22:51:08 172.18.0.1 registry[671]: time="2017-07-01T22:51:08.354147444+08:00" level=error msg="response completed with error" auth.user.name=wangxxg err.code=unsupported err.message="The operation is unsupported." go.version=go1.7.3 http.request.host="registry:5000" http.request.id=d602a35a-146f-49dc-b8e6-7dd12b5975be http.request.method=DELETE http.request.remoteaddr="172.18.0.5:48572" http.request.uri="/v2/qinzhao-harbor/svntest/manifests/sha256:b94314c2f075f1302370881e9ef991b955bb415ac78326fbd36a00c5bea403ed" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.476526ms http.response.status=405 http.response.written=78 instance.id=b2b64b15-f564-4016-b759-163cc131df33 service=registry vars.name="qinzhao-harbor/svntest" vars.reference="sha256:b94314c2f075f1302370881e9ef991b955bb415ac78326fbd36a00c5bea403ed" version="v2.4.1+unknown" 
Jul  1 22:51:08 172.18.0.1 registry[671]: 172.18.0.5 - - [01/Jul/2017:22:51:08 +0800] "DELETE /v2/qinzhao-harbor/svntest/manifests/sha256:b94314c2f075f1302370881e9ef991b955bb415ac78326fbd36a00c5bea403ed HTTP/1.1" 405 78 "" "Go-http-client/1.1"

**Comment by fenghui2013** [comment]
@xingxing9688  ceph verison? thanks
