### ISSUE TITLE
[Vul] UI shows red color without any high Vulnerabilities. 

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#2688]
![image](https://user-images.githubusercontent.com/2841473/27779806-377217fe-5f7a-11e7-94fc-c5e729e2141c.png)

**Comment by wy65701436** [comment]
it's an bug of tooltip.

**Comment by lweitzman** [comment]
Looking at the image, "None vulnerabilities" should say "No vulnerabilities"

**Comment by tonycgil** [comment]
All icons should be 16x16. They look different sizes on the screenshot

**Comment by steven-zou** [comment]
@tonycgil 

Actually, all the icons are set with same size. But seems the Clarity icons do not look the same size. Will use different size to try to make they looks like the same size.

**Comment by tonycgil** [comment]
@steven-zou hmm strange. I've added a 16x16 square and some of them are really close accept the "?" This would be good feedback if there's a way to find out the issue. Is it the general footprint size of the icon that's too big? Should I redesign to actual size?
![iconsize](https://user-images.githubusercontent.com/25991813/28123731-98490d0e-66d6-11e7-922e-f8bc39440064.png)

**Comment by steven-zou** [comment]
Fixed, close issue.
