### ISSUE TITLE
[Question] is it safe to delete tags when harbor is running?

### ISSUE THREAD

**Issue by fffffreedom** [vmware/harbor#2690]
Hi
i want to delete images tags using harbor API, for example:
curl -u admin:Harbor12345 -X DELETE http://registry.com/api/repositories/test/busybox/tags/v1

as said in https://github.com/vmware/harbor/blob/master/docs/user_guide.md
So before running GC, a preferred approach is to stop Harbor first.

if we don't use the tag, is it safe to delete tags when harbor is running?

thanks

**Comment by reasonerjt** [comment]
By "delete tag" do you mean run GC?

**Comment by fffffreedom** [comment]
no, i'm calling RESTFul API to delete tags of repo.

**Comment by reasonerjt** [comment]
If you call Harbor's API to delete tag then Harbor **has to be running**

**Comment by fffffreedom** [comment]
thanks
