### ISSUE TITLE
"fork/exec /usr/bin/gcc: cannot allocate memory" during docker build

### ISSUE THREAD

**Issue by starjason** [vmware/harbor#27]
fork/exec /usr/bin/gcc: cannot allocate memory

**Comment by starjason** [comment]
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory

ERROR: Service 'ui' failed to build: The command '/bin/sh -c go get -d github.com/docker/distribution     && go get -d github.com/docker/libtrust     && go get -d github.com/go-sql-driver/mysql     && go install -v -a' returned a n

**Comment by hainingzhang** [comment]
Could you provide your OS version, and CPU/memory on your machine?

**Comment by reasonerjt** [comment]
This seems the memory is insufficient when running docker build to build the ui container, @starjason could you try to kill a few processes (or reboot) and run docker-compose build again?

**Comment by starjason** [comment]
Ubuntu 14.04.2 LTS
# cat /proc/meminfo | grep MemTotal
MemTotal:        1016348 kB
#  cat /proc/cpuinfo | grep "cpu cores" | uniq
cpu cores       : 1
# cat /proc/cpuinfo | grep 'model name' |uniq
model name      : Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
# docker -v
Docker version 1.10.3, build 20f81dd
# docker-compose --version
docker-compose version 1.6.2, build 4d72027

**Comment by reasonerjt** [comment]
@starjason during my test, when building the docker image for harbor ui the process will use hundreds of megabytes of RAM, in your env there's only 1G in total, so it's very likely you are running out of memory during "docker build". Without knowing the status of memory usage of your env, my only suggestion is to increase the memory.

**Comment by xiaods** [comment]
1G RAM? too low footprint

**Comment by xiaods** [comment]
@starjason have a try a 2G ram box to testing again. it will conclude the result.

**Comment by reasonerjt** [comment]
@starjason  if there's no response I'll close this issue in 2 days.

**Comment by AlexZeitler** [comment]
Using a 2G ram box fixed this for me.

**Comment by phpjsnerd** [comment]
I got same issue also in vagrant ubuntu 14.04 virtualbox, i fixed by increasing the RAM size to 2048 MB (2GB) it worked.
