### ISSUE TITLE
can not delete image from docker registry

### ISSUE THREAD

**Issue by qq511700505** [vmware/harbor#270]
I am trying to delete a  repository with **Harbor Swagger-UI** ,but when I try to push this image again into registry, the respond is 'Image already exists',and I can find this image again on Habor UI.

so I think the 'DELETE REPOSITORIES' API don not delete the real  image in the registry , only to delete the record in the Harbor Database.

should we do the real delete when we are deleting a repository.

Thanks.

**Comment by ywk253100** [comment]
#112 explains the implements of API.
