### ISSUE TITLE
configuration can not be saved

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#2702]
In configuration page, change a configuration and click save, will meet a bad request error
![screencapture-10-112-122-200-harbor-configs-1499162998191](https://user-images.githubusercontent.com/23101283/27826066-50f2e724-60e4-11e7-97c9-a5dd37660d76.png)

**Comment by wy65701436** [comment]
Invalid value type, expected bool, key: self_registration, value: 0, type: string

**Comment by reasonerjt** [comment]
Let's fix it before this sprint exits. @steven-zou

**Comment by steven-zou** [comment]
Right, will check all the bool type

**Comment by steven-zou** [comment]
@sigsbee 
@wy65701436 

Is it the latest code? I tried the latest code, it works well.

<img width="683" alt="2017-07-07 8 35 50" src="https://user-images.githubusercontent.com/5753287/27958073-fb32bc02-6353-11e7-8803-218781242cb6.png">

**Comment by steven-zou** [comment]
Fixed, close this one!
