### ISSUE TITLE
Tag detail doesn't appear in Repository UI

### ISSUE THREAD

**Issue by m-masataka** [vmware/harbor#2703]
Tag's detail information doesn't appear in repository UI when I use S3 as registry's backend storage.
This is because the response of registry is little slow and tag detail UI doesn't wait the response(, the timeout setting 1 second ).  
In my environment, it takes less than 2 seconds to get response of registry.
I think we should set timeout more longer.

**Comment by steven-zou** [comment]
Code merged, let's close this issue.

**Comment by m-masataka** [comment]
thank you!
