### ISSUE TITLE
Collect UI package change in 1.2.0

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#2707]
For OSS legal clearance.

Please add comments to this issue to elaborate.

**Comment by steven-zou** [comment]
Angular related packages:(version change)
"@angular/animations": "~4.1.3",
        "@angular/common": "~4.1.3",
        "@angular/compiler": "~4.1.3",
        "@angular/compiler-cli": "~4.1.3",
        "@angular/core": "~4.1.3",
        "@angular/forms": "~4.1.3",
        "@angular/http": "~4.1.3",
        "@angular/platform-browser": "~4.1.3",
        "@angular/platform-browser-dynamic": "~4.1.3",
        "@angular/router": "~4.1.3",

**Comment by steven-zou** [comment]
Clarity related packages: (version upgrade)
        "clarity-angular": "^0.9.8",
        "clarity-icons": "^0.9.8",
        "clarity-ui": "^0.9.8",

github:https://github.com/vmware/clarity/
license: https://github.com/vmware/clarity/blob/master/LICENSE

**Comment by steven-zou** [comment]
ngx-clipboard:v8.0.3

github:https://github.com/maxisam/ngx-clipboard
license: (MIT)https://github.com/maxisam/ngx-clipboard/blob/master/LICENSE

**Comment by steven-zou** [comment]
intl 1.2.5

https://github.com/andyearnshaw/Intl.js.git

**Comment by steven-zou** [comment]
mutationobserver-shim 0.3.2
github.com/megawac/MutationObserver.js

https://registry.npmjs.org/mutationobserver-shim/-/mutationobserver-shim-0.3.2.tgz

**Comment by steven-zou** [comment]
zone.js 0.8.12

git://github.com/angular/zone.js.git

**Comment by steven-zou** [comment]
web-animations-js 2.2.5
https://registry.npmjs.org/web-animations-js/-/web-animations-js-2.2.5.tgz
Apache-2.0

https://github.com/web-animations/web-animations-js.git

**Comment by steven-zou** [comment]
ts-helpers 1.1.2

https://registry.npmjs.org/ts-helpers/-/ts-helpers-1.1.2.tgz

https://github.com/ngParty/ts-helpers.git

**Comment by reasonerjt** [comment]
Thanks, submitted the tickets.
