### ISSUE TITLE
[feature request]ldap search in adding user

### ISSUE THREAD

**Issue by sinycn** [vmware/harbor#2720]
when add members in harbor(AD users),the user must login once before add it ,is it possible to create search button  in new member tab .
   function maybe that when you enter username then search, harbor will search username (display name ) in ad,then add it to harbor automatically, you can select user and add to member .
hope for your reply

**Comment by reasonerjt** [comment]
How'bout add this feature to system config tab, so only sys admin can add a user?

**Comment by stonezdj** [comment]
Add this feature in #3596
