### ISSUE TITLE
Home page review

### ISSUE THREAD

**Issue by monicaw** [vmware/harbor#273]
Home page improve

**Comment by xiahaoshawn** [comment]
![7 pic_hd](https://cloud.githubusercontent.com/assets/10750864/15568539/03fd0210-235f-11e6-8cfe-0a0f29baa711.jpg)

**Comment by monicaw** [comment]
Mockup can be read from:
https://wiki.eng.vmware.com/wiki/images/4/4d/Miscellaneous.pdf
Page 3
