### ISSUE TITLE
Update the text on the vulnerabilities tooltip

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#2743]
the tooltip for vulnerabilities should be as shown in the attached image.

![screen shot 2017-07-11 at 2 49 06 pm](https://user-images.githubusercontent.com/626032/28084974-59ca3da2-6648-11e7-9488-d948c1294c68.png)

**Comment by lweitzman** [comment]
updated mockup at https://vmware.invisionapp.com/share/DGBDPFBJA#/229493327_Harbor_-_Repositories_-_V1-2

**Comment by steven-zou** [comment]
Updated, code merged into master.
