### ISSUE TITLE
It will take about 38 seconds to load 137 images in UI

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#2747]
1> create a project in harbor
2>upload about 137 images into harbor register
3> view those images in the ui
it will takes about 38seconds before I can see images list.

but the switch between different page is pretty fast.

**Comment by yixingjia** [comment]
Ideally no matter how many images in the register it should take no much difference, as each time we should only list one page.

**Comment by yixingjia** [comment]
[harbor.zip](https://github.com/vmware/harbor/files/1140918/harbor.zip)

**Comment by ywk253100** [comment]
Open #2754 and #2755 to track the fix of this issue.

**Comment by ywk253100** [comment]
Closing this due to #2755 has been fixed. Using #2754 to track API fix.
