### ISSUE TITLE
Issues found by Gas scan results

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#2753]
{
	"issues": [
		{
			"severity": "HIGH",
			"confidence": "LOW",
			"details": "Potential hardcoded credentials",
			"file": "/github.com/vmware/harbor/src/common/security/admiral/authcontext/authcontext.go",
			"code": "AuthTokenHeader  = \"x-xenon-auth-token\"",
			"line": 35
		},
		{
			"severity": "HIGH",
			"confidence": "HIGH",
			"details": "TLS InsecureSkipVerify set true.",
			"file": "/github.com/vmware/harbor/src/common/utils/ldap/ldap.go",
			"code": "InsecureSkipVerify: true",
			"line": 349
		},
		{
			"severity": "HIGH",
			"confidence": "HIGH",
			"details": "TLS InsecureSkipVerify set true.",
			"file": "/github.com/vmware/harbor/src/common/utils/registry/registry.go",
			"code": "InsecureSkipVerify: true",
			"line": 46
		},
		{
			"severity": "LOW",
			"confidence": "HIGH",
			"details": "Errors unhandled.",
			"file": "/github.com/vmware/harbor/src/common/utils/test/test.go",
			"code": "io.Copy(w, bytes.NewReader(resp.Body))",
			"line": 75
		},
		{
			"severity": "LOW",
			"confidence": "HIGH",
			"details": "Errors unhandled.",
			"file": "c/github.com/vmware/harbor/src/common/utils/utils.go",
			"code": "conn.Close()",
			"line": 105
		},
		{
			"severity": "HIGH",
			"confidence": "HIGH",
			"details": "TLS InsecureSkipVerify set true.",
			"file": "/github.com/vmware/harbor/src/jobservice/replication/delete.go",
			"code": "InsecureSkipVerify: insecure",
			"line": 175
		},
		{
			"severity": "HIGH",
			"confidence": "LOW",
			"details": "TLS InsecureSkipVerify may be true.",
			"file": "/github.com/vmware/harbor/src/jobservice/replication/transfer.go",
			"code": "InsecureSkipVerify: c.insecure",
			"line": 279
		},
		{
			"severity": "HIGH",
			"confidence": "LOW",
			"details": "Potential hardcoded credentials",
			"file": "/github.com/vmware/harbor/src/ui/config/config.go",
			"code": "defaultTokenFilePath string = \"/etc/ui/service_token\"",
			"line": 39
		},
		{
			"severity": "HIGH",
			"confidence": "HIGH",
			"details": "TLS InsecureSkipVerify set true.",
			"file": "/github.com/vmware/harbor/src/ui/config/config.go",
			"code": "InsecureSkipVerify: true",
			"line": 119
		}
	],
	"metrics": {
		"files": 184,
		"lines": 22409,
		"nosec": 0,
		"found": 9
	}
}

**Comment by reasonerjt** [comment]
Closing as clarified with SE they are false negative.
