### ISSUE TITLE
Request tags of repo in parallel when listing repositories

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#2754]

**Comment by nuzz** [comment]
I've been trying to trackdown slowness with getting tags from a repo. I'm running a harbor installation on a kubernetes cluster using s3 for registry storage. I have a few repos with a few tags (under 50). As an example it takes about 15 seconds to turn  a list of 32 tags. I have a few repos with hundreds of tags and the requests for tag info on the bigger repos wend up timing out after 1 minute.

example
curl -X GET https://myregistry/api/repositories/project/repo/tags
