### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by oronboni** [vmware/harbor#2768]
Harbor developer,

Clair project is a project that analyse the container after push for security vulnerabilities.
add to harbor CoreOS\Clair will upgrade harbor to a new level of container registry for on prem.

My email is oronboni@hotmail.com

**Comment by oronboni** [comment]
Wow i saw that you already did that COOL (-: now i need to learn how to install it.

**Comment by reasonerjt** [comment]
It's a WIP, targeting next release hopefully an RC will be around end of Jul

**Comment by reasonerjt** [comment]
Closing the issue as the original question is answered.
