### ISSUE TITLE
Dashboard page review

### ISSUE THREAD

**Issue by monicaw** [vmware/harbor#277]
![dashboardreview](https://cloud.githubusercontent.com/assets/19568623/15601369/892e50ca-2421-11e6-8267-2cf5e7781ff1.jpg)

**Comment by yugongpeng** [comment]
![harbor](https://cloud.githubusercontent.com/assets/10625207/15604600/cf9ba6f4-2433-11e6-8804-2b609b797a9f.png)
why not have dashboard in my web.My version is 0.1.1

**Comment by monicaw** [comment]
Mokcup can be read from: https://wiki.eng.vmware.com/Project_Harbor_SWG/UE_mockup/user
