### ISSUE TITLE
click scan now will cause 500 error

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#2773]
v1.1.2-458-gca6bd3b
![scan](https://user-images.githubusercontent.com/23101283/28155650-28cf14fc-67e2-11e7-94d4-f5d4a4066a78.PNG)

**Comment by reasonerjt** [comment]
looks like a false-negative?
probably due to out-dated schema?

**Comment by reasonerjt** [comment]
Should be fixed upstream by #2769
