### ISSUE TITLE
Can't get job log in integration mode

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#2776]
Got error:
{
  "message": "Service not found: http://127.0.0.1:8282/api/jobs/replication/10/log",
  "statusCode": 404,
  "documentKind": "com:vmware:xenon:common:ServiceErrorResponse",
  "errorCode": -2147483648
}

**Comment by reasonerjt** [comment]
this should be an issue in Admiral wrapper?

**Comment by steven-zou** [comment]
Add job viewer
