### ISSUE TITLE
Handler crashed after deleting the database and restarting

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#2787]
Jul 14 17:52:08 172.18.0.1 ui[869]: 2017/07/14 09:52:08 #033[1;35m[router.go:854][C] the request url is  /api/systeminfo #033[0m
Jul 14 17:52:08 172.18.0.1 ui[869]: 2017/07/14 09:52:08 #033[1;35m[router.go:855][C] Handler crashed with error runtime error: invalid memory address or nil pointer dereference #033[0m

**Comment by reasonerjt** [comment]
Fixed in #2789
