### ISSUE TITLE
Send email failed when certificate does not match with smtp server.

### ISSUE THREAD

**Issue by tuxknight** [vmware/harbor#28]
```
# cat harbor.cfg|grep email_server
email_server = smtp.xxxxxx.com
email_server_port = 25
```

``Mar 21 11:12:36 registry.idc docker/ui[15559]: 2016/03/21 03:12:36 [password.go:169][E] send email failed: x509: certificate is valid for *.icoremail.net, icoremail.net, not smtp.xxxxxx.com ``

It is a common situation that serve name does not match with the domain name in certificate when using an email vendor. So, it is better to make smtp TLS configurable.

**Comment by ywk253100** [comment]
Maybe the email vendor should fix the problem of mismatching the domain name in certificate and the server name, or how to guarantee the security of communications?

**Comment by hainingzhang** [comment]
@tuxknight, what is your suggestion for the TLS configuration under this scenario?

**Comment by tuxknight** [comment]
@ywk253100  Good point. It will be better to assign one certificate each domain name. 
But in this scenario, a smtp server such as  *smtp.xxxxxxx.com* has a cname like *smtp.icoremail.net* which is the real server of the vendor. And xxxxxxx.com could be  a customer's domain name.

```
dig smtp.xxxxxxx.com
;; ANSWER SECTION:
smtp.xxxxxxx.com. 600	IN	CNAME	smtp.icoremail.net.
smtp.icoremail.net.	600	IN	CNAME	mail1.icoremail.net.
mail1.icoremail.net.	600	IN	A	223.252.214.64
mail1.icoremail.net.	600	IN	A	223.252.214.65
```

@hainingzhang  Perhaps It's good to make smtp TLS configurable. Or you could just add another configuration item called "domain" which used to match the certificate. In my scenario, it would be "icoremail.net".

Thanks.

**Comment by reasonerjt** [comment]
@tuxknight , thanks for elaborating.
So given it's a cname, I suppose you can simply configure smtp.icoremail.net as email_server in harbor.cfg?

**Comment by ywk253100** [comment]
@tuxknight  Does setting cname work? If it works, I will close this issue.

**Comment by xiaods** [comment]
@ywk253100 please add label to category the issue's type. it's will fine.

**Comment by tuxknight** [comment]
It works while using smtp.icoremail.net.

Harbor is online and I will keep migrating projects to harbor :)

**Comment by hainingzhang** [comment]
@tuxknight Did you run Harbor in a private environment? We'd like to learn more about your use case if possible. Thanks.
