### ISSUE TITLE
inconsistent use of datagrid footer indicating number of items 

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#2800]
the item count in the lower right is inconsistent throughout the application. 
1) sometimes the label says "items" and sometimes it calls out the type of object "users" 
     its good to see the object type listed
2) when all items fit on 1 page sometimes it says "1-1 of 1 users" and sometimes "3 item(s)
     just indicating the total number is sufficient in this case
3) when there are no items it says "1-5 of 0 item(s)" 
     it should just say "0 replication rules"
including the screenshots:
![screen shot 2017-07-17 at 9 48 08 am](https://user-images.githubusercontent.com/626032/28271235-0070adda-6ad6-11e7-993e-e86045ca8029.png)
![screen shot 2017-07-17 at 8 50 28 am](https://user-images.githubusercontent.com/626032/28271246-057d2452-6ad6-11e7-9a25-bf6d1a9870db.png)
![screen shot 2017-07-17 at 9 48 34 am](https://user-images.githubusercontent.com/626032/28271252-08dad5ea-6ad6-11e7-8dcc-d776f3009f1c.png)
![screen shot 2017-07-17 at 9 49 25 am](https://user-images.githubusercontent.com/626032/28271254-0bac7ce2-6ad6-11e7-9127-f51f0613a10d.png)

**Comment by steven-zou** [comment]
@pengpengshui Please take a look at this issue.

**Comment by steven-zou** [comment]
Here are some comments:

  The full pattern of the pagination is '{{pagination.firstItem + 1}} - {{pagination.lastItem + 1}} {{'REPOSITORY.OF' | translate}}
        {{pagination.totalItems}} {{'REPOSITORY.ITEMS' | translate}}'; we should wrap '{{pagination.firstItem + 1}} - {{pagination.lastItem + 1}} {{'REPOSITORY.OF' | translate}}' as a separate part.

If  {{pagination.totalItems}} is 0, then hidden the '{{pagination.firstItem + 1}} - {{pagination.lastItem + 1}} {{'REPOSITORY.OF' | translate}}'

If {{pagination.totalItems}} > 0, then show the full pattern.

All the suffix use the same notes "Items"

**Comment by lweitzman** [comment]
this is still an issue on the users page and the project > members page
![screen shot 2017-07-20 at 11 15 46 am](https://user-images.githubusercontent.com/626032/28424975-04fca8d6-6d3d-11e7-9a30-97a699525c77.png)
![screen shot 2017-07-20 at 11 17 00 am](https://user-images.githubusercontent.com/626032/28424984-0920b858-6d3d-11e7-996f-7887bc4184a0.png)

**Comment by steven-zou** [comment]
Already fixed by @pengpengshui , close this issue.
