### ISSUE TITLE
#The path of secretkey storage secretkey_path = /data

### ISSUE THREAD

**Issue by linlynn** [vmware/harbor#2801]
can someone help explain this (secretly_path) ? how to create this ? share one example ?

thx

**Comment by ywk253100** [comment]
secret_path is the directory where the secretkey is. secretkey is a file contains 16 characters and is used to encrypt/decrypt passwords used inside Harbor. It is generated automatically if the user doesn't set it when Harbor starts.

If you want to create it by yourself, you should put a file named secretkey under the directory configured by "secret_path" in harbor.cfg. The secretkey file must contain 16 characters which look like this: lkJe1JVumcftP3ca .

**Comment by linlynn** [comment]
@ywk253100  thanks ,it works in ubuntu env but doesn't work in my mac system . so  it doesn't support setup harbor in mac ,right?

**Comment by ywk253100** [comment]
We haven't tested Harbor in mac environment.
