### ISSUE TITLE
harbor默认docker仓库镜像存储位置无效

### ISSUE THREAD

**Issue by dangzhiqiang** [vmware/harbor#2810]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
环境：centos 7
docker-compose-1.9.0-5.el7.noarch
docker-engine-1.13.1-1.el7.centos.x86_64
2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
默认配置，仅更改hostname为当前主机名
3)Log files, you can get them by package the /var/log/harbor/ .
无报错

**问题描述：**
下载harbor-offline-installer-v1.1.2.tgz，解压后，更改配置文件，通过./install.sh脚本安装。

后台上传镜像，镜像默认存储在/home/registry/目录，而不是在 /data/registry/目录，而且界面看不到上传的进行信息，但通过api可以正常访问。

**Comment by dangzhiqiang** [comment]
后面看了一下，原来配置文件用的是/etc/docker-distribution/registry/config.yml
进程是：
/usr/bin/registry serve /etc/docker-distribution/registry/config.yml
对应软件包是：
docker-distribution-2.6.0-1.el7.x86_64
所以还是有问题的，需要改这里的config文件。

**Comment by dangzhiqiang** [comment]
原来是/etc/docker-distribution/registry/config.yml配置文件无效导致的，使用默认的配置文件即可。
docker-distribution-2.6.1-1.el7.x86_64
之后镜像会存到默认位置，并且界面就可以看到镜像了！
还是环境不够纯净导致的。

**Comment by dangzhiqiang** [comment]
还是有问题，默认存储位置是按照/etc/docker-distribution/registry/config.yml中存放的，并不在/data/registry目录

**Comment by reasonerjt** [comment]
>默认存储位置是按照/etc/docker-distribution/registry/config.yml中存放的

What's the location?

**Comment by dangzhiqiang** [comment]
后面看了，原因是服务器上其他人已经部署了docker-distribution服务，导致上传镜像上传到了本地镜像仓库中，根本没有使用harbor中的registry。

**Comment by dangzhiqiang** [comment]
结论：本地应该禁用docker-distribution服务，防止冲突，harbor默认docker仓库镜像存储位置是正确的。
