### ISSUE TITLE
The message for cannot scan all in short time is not clear

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#2811]
When try to trigger "scan now" in short time, less than 30 minutes, the error message is "We are unable to perform your action because of a precondition failure."

**Comment by reasonerjt** [comment]
Will add "next_scan_all" in systeminfo api, so UI can easily disable the button and have sufficient information to render a meaningful message.

**Comment by steven-zou** [comment]
API might need to enhance. let's have further discussion. @reasonerjt

**Comment by steven-zou** [comment]
Close this issue as it's fixed.
