### ISSUE TITLE
time input error in Firefox52

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#2826]
v1.1.2-515-gaa681eb

![time](https://user-images.githubusercontent.com/23101283/28406126-c9b0c7e2-6d61-11e7-86c1-4f73a7f0d623.PNG)

**Comment by steven-zou** [comment]
Raise issue to Clarity team

**Comment by steven-zou** [comment]
@pengpengshui 

  Please do some investigation, if the issue is caused by the 'date' component itself, we can raise issue to the Clair team then

**Comment by steven-zou** [comment]
Firefox does not support <input type="time" >, please refer https://www.w3schools.com/html/html_form_input_types.asp .

As it's limitation of browser itself, close this issue.
