### ISSUE TITLE
vulnerability tooltip inaccurate

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#2832]
the vulnerability tooltip is a bit inaccurate. 
1) should the first line say "image" instead of "tag"?
2) the first line is ok but would it be better to say 
"This image includes 67 packages with vulnerabilities in 15 of those packages"
3) can we generate the first line without the parenthesis? ie, if only 1 package don't say "package(s)"
4) the icon colors don't match the colors in the bar. i think you need to replace the low vulnerability with the one @tonycgil created that is yellow. (medium vulnerability is orange)

existing tooltip:
![screen shot 2017-07-20 at 11 26 39 am](https://user-images.githubusercontent.com/626032/28425731-2ce077ea-6d3f-11e7-843f-d361fb8cd7da.png)

mockup provided by @tonycgil:
![screen shot 2017-07-20 at 11 28 34 am](https://user-images.githubusercontent.com/626032/28425749-3a0604c6-6d3f-11e7-8318-90697221ca8d.png)

**Comment by steven-zou** [comment]
Fixed, close issue

**Comment by lweitzman** [comment]
As per Paul's comment we should change the first line to read  “14 of 67 packages have known vulnerabilities”

**Comment by steven-zou** [comment]
@lweitzman 

Sure!

**Comment by steven-zou** [comment]
Changed, close
