### ISSUE TITLE
Jobservice and ui container always restart because they can't connect to tcp://adminserver:80.

### ISSUE THREAD

**Issue by whulyx** [vmware/harbor#2833]
Version of docker:
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:04 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:18:59 2017
 OS/Arch:      linux/amd64
 Experimental: false

Version of docker-compose:
docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

harbor.cfg:
secretkey_path = /data

/var/log/harbor-----ui.log
`Jul 21 11:24:42 172.18.0.1 ui[27809]: 2017-07-21T03:24:42Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp 172.18.0.3:80: getsockopt: connection timed out
Jul 21 11:24:59 172.18.0.1 ui[27809]: 2017-07-21T03:24:59Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp 172.18.0.3:80: getsockopt: connection timed out
Jul 21 11:25:16 172.18.0.1 ui[27809]: 2017-07-21T03:25:16Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp 172.18.0.3:80: getsockopt: connection timed out
Jul 21 11:25:33 172.18.0.1 ui[27809]: 2017-07-21T03:25:33Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp 172.18.0.3:80: getsockopt: connection timed out
Jul 21 11:25:35 172.18.0.1 ui[27809]: 2017-07-21T03:25:35Z [FATAL] [main.go:83]: failed to initialize configurations: failed to ping adminserver: failed to connect to tcp:adminserver:80 after 60 seconds`

/var/log/harbor----jobservice.log
`Jul 21 11:24:29 172.18.0.1 jobservice[27809]: 2017-07-21T03:24:29Z [INFO] initializing client for adminserver http://adminserver ...
Jul 21 11:24:44 172.18.0.1 jobservice[27809]: 2017-07-21T03:24:44Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp 172.18.0.3:80: getsockopt: connection timed out
Jul 21 11:25:01 172.18.0.1 jobservice[27809]: 2017-07-21T03:25:01Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp 172.18.0.3:80: getsockopt: connection timed out
Jul 21 11:25:18 172.18.0.1 jobservice[27809]: 2017-07-21T03:25:18Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp 172.18.0.3:80: getsockopt: connection timed out
Jul 21 11:25:35 172.18.0.1 jobservice[27809]: 2017-07-21T03:25:35Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp 172.18.0.3:80: getsockopt: connection timed out
Jul 21 11:25:37 172.18.0.1 jobservice[27809]: 2017-07-21T03:25:37Z [FATAL] [main.go:31]: failed to initialize configurations: failed to ping adminserver: failed to connect to tcp:adminserver:80 after 60 seconds
Jul 21 11:25:38 172.18.0.1 jobservice[27809]: 2017-07-21T03:25:38Z [INFO] Config path: /etc/jobservice/app.conf`

Jobservice and ui container restart every 60 seconds so I can't open the web ui of harbor. What should I do? Thanks for all reply.

**Comment by whulyx** [comment]
Oh I forgot to put the adminserver.log:
`Jul 21 11:20:57 172.18.0.1 adminserver[27809]: 2017-07-21T03:20:57Z [INFO] initializing system configurations...
Jul 21 11:20:57 172.18.0.1 adminserver[27809]: 2017-07-21T03:20:57Z [INFO] the path of json configuration storage: /etc/adminserver/config/config.json
Jul 21 11:20:57 172.18.0.1 adminserver[27809]: 2017-07-21T03:20:57Z [DEBUG] [driver_json.go:46]: path of configuration file: /etc/adminserver/config/config.json
Jul 21 11:20:57 172.18.0.1 adminserver[27809]: 2017-07-21T03:20:57Z [INFO] the configuration file /etc/adminserver/config/config.json does not exist, creating it...
Jul 21 11:20:57 172.18.0.1 adminserver[27809]: 2017-07-21T03:20:57Z [INFO] the path of key used by key provider: /etc/adminserver/key
Jul 21 11:20:57 172.18.0.1 adminserver[27809]: 2017-07-21T03:20:57Z [INFO] configurations read from storage driver are null, will load them from environment variables
Jul 21 11:20:57 172.18.0.1 adminserver[27809]: 2017-07-21T03:20:57Z [INFO] system initialization completed`

**Comment by reasonerjt** [comment]
Thanks for reporting.
But I see the time does not match between the ui.log and adminserver.log.

Did you restart the containers or do you see immediate failure after `docker-compose down` and `docker-compose up`

**Comment by whulyx** [comment]
@reasonerjt Thanks for your reply.
I clear the history log and run docker-compose command again. Here are the logs generated:

ui.log
`Jul 21 15:02:42 172.18.0.1 ui[27809]: 2017-07-21T07:02:42Z [INFO] Config path: /etc/ui/app.conf
Jul 21 15:02:42 172.18.0.1 ui[27809]: 2017-07-21T07:02:42Z [INFO] initializing configurations...
Jul 21 15:02:42 172.18.0.1 ui[27809]: 2017-07-21T07:02:42Z [INFO] key path: /etc/ui/key
Jul 21 15:02:42 172.18.0.1 ui[27809]: 2017-07-21T07:02:42Z [INFO] initializing client for adminserver http://adminserver ...
Jul 21 15:02:57 172.18.0.1 ui[27809]: 2017-07-21T07:02:57Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp 172.18.0.5:80: getsockopt: connection timed out
Jul 21 15:03:14 172.18.0.1 ui[27809]: 2017-07-21T07:03:14Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp 172.18.0.5:80: getsockopt: connection timed out
Jul 21 15:03:31 172.18.0.1 ui[27809]: 2017-07-21T07:03:31Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp 172.18.0.5:80: getsockopt: connection timed out
Jul 21 15:03:48 172.18.0.1 ui[27809]: 2017-07-21T07:03:48Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp 172.18.0.5:80: getsockopt: connection timed out
Jul 21 15:03:50 172.18.0.1 ui[27809]: 2017-07-21T07:03:50Z [FATAL] [main.go:83]: failed to initialize configurations: failed to ping adminserver: failed to connect to tcp:adminserver:80 after 60 seconds
Jul 21 15:03:52 172.18.0.1 ui[27809]: 2017-07-21T07:03:52Z [INFO] Config path: /etc/ui/app.conf
Jul 21 15:03:52 172.18.0.1 ui[27809]: 2017-07-21T07:03:52Z [INFO] initializing configurations...
Jul 21 15:03:52 172.18.0.1 ui[27809]: 2017-07-21T07:03:52Z [INFO] key path: /etc/ui/key
Jul 21 15:03:52 172.18.0.1 ui[27809]: 2017-07-21T07:03:52Z [INFO] initializing client for adminserver http://adminserver ...
Jul 21 15:04:07 172.18.0.1 ui[27809]: 2017-07-21T07:04:07Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp 172.18.0.5:80: getsockopt: connection timed out
Jul 21 15:04:24 172.18.0.1 ui[27809]: 2017-07-21T07:04:24Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp 172.18.0.5:80: getsockopt: connection timed out
Jul 21 15:04:41 172.18.0.1 ui[27809]: 2017-07-21T07:04:41Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp 172.18.0.5:80: getsockopt: connection timed out
Jul 21 15:04:58 172.18.0.1 ui[27809]: 2017-07-21T07:04:58Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp 172.18.0.5:80: getsockopt: connection timed out
Jul 21 15:05:00 172.18.0.1 ui[27809]: 2017-07-21T07:05:00Z [FATAL] [main.go:83]: failed to initialize configurations: failed to ping adminserver: failed to connect to tcp:adminserver:80 after 60 seconds`

adminserver.log:
`Jul 21 15:02:41 172.18.0.1 adminserver[27809]: 2017-07-21T07:02:41Z [INFO] initializing system configurations...
Jul 21 15:02:41 172.18.0.1 adminserver[27809]: 2017-07-21T07:02:41Z [INFO] the path of json configuration storage: /etc/adminserver/config/config.json
Jul 21 15:02:41 172.18.0.1 adminserver[27809]: 2017-07-21T07:02:41Z [DEBUG] [driver_json.go:46]: path of configuration file: /etc/adminserver/config/config.json
Jul 21 15:02:41 172.18.0.1 adminserver[27809]: 2017-07-21T07:02:41Z [INFO] the path of key used by key provider: /etc/adminserver/key
Jul 21 15:02:41 172.18.0.1 adminserver[27809]: 2017-07-21T07:02:41Z [INFO] system initialization completed`

I changed the nginx port mapping from 80:80 443:443 to 10204:80 10205:443 because the port 80 and 443 have been used by other program, is there any relation between this error and the change I did ?

**Comment by whulyx** [comment]
It seemed that jobservice and ui container failed to ping the adminserver container, but I entered the container and saw their IP are all in 172.18.0.x.  What would cause this connection problem?

**Comment by whulyx** [comment]
@reasonerjt Oh I have solved my problem. My workmate start the dockerd with "--iptables=false" so my containers can't connect with each other. Thanks for your help, I will close this issue.
