### ISSUE TITLE
没有显示任何tag，但是向默认的library推送的镜像有tag 显示，具体见一下截图

### ISSUE THREAD

**Issue by yuqipg** [vmware/harbor#284]
![no_tag](https://cloud.githubusercontent.com/assets/18362187/15644509/11cfe82e-2686-11e6-83af-db0f46444553.png)
![library_has_tag](https://cloud.githubusercontent.com/assets/18362187/15644545/34584256-2686-11e6-9772-76f373f4b6e2.png)

**Comment by ywk253100** [comment]
Provide the logs please, you can find them in /var/log/harbor/.

**Comment by yuqipg** [comment]
docker_registry.log
May 31 09:25:06 udokreg docker/registry[740]: time="2016-05-31T01:25:06.773130602Z" level=debug msg="authorizing request" go.version=go1.6.1 http.request.host="registry:5000" http.request.id=f012fb7e-5264-4247-9e8b-36d371bb517e http.request.method=GET http.request.remoteaddr="172.18.0.3:48051" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=473cf9bc-1a25-47d2-a38f-5776a3c688d3 service=registry version=v2.4.0 
May 31 09:25:06 udokreg docker/registry[740]: time="2016-05-31T01:25:06.774140128Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.6.1 http.request.host="registry:5000" http.request.id=f012fb7e-5264-4247-9e8b-36d371bb517e http.request.method=GET http.request.remoteaddr="172.18.0.3:48051" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=473cf9bc-1a25-47d2-a38f-5776a3c688d3 service=registry version=v2.4.0 
May 31 09:25:06 udokreg docker/registry[740]: 172.18.0.3 - - [31/May/2016:01:25:06 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "Go-http-client/1.1"
May 31 09:25:08 udokreg docker/registry[740]: time="2016-05-31T01:25:08.80102444Z" level=debug msg="authorizing request" go.version=go1.6.1 http.request.host="registry:5000" http.request.id=e5f08ba3-9ea5-463f-8e02-58f84774a7f0 http.request.method=GET http.request.remoteaddr="172.18.0.3:48053" http.request.uri="/v2/activemq/centos5_activemq-5.11.11/tags/list" http.request.useragent="Go-http-client/1.1" instance.id=473cf9bc-1a25-47d2-a38f-5776a3c688d3 service=registry vars.name="activemq/centos5_activemq-5.11.11" version=v2.4.0 
May 31 09:25:08 udokreg docker/registry[740]: time="2016-05-31T01:25:08.80224681Z" level=debug msg="filesystem.List(\"/docker/registry/v2/repositories/activemq/centos5_activemq-5.11.11/_manifests/tags\")" auth.user.name=admin go.version=go1.6.1 http.request.host="registry:5000" http.request.id=e5f08ba3-9ea5-463f-8e02-58f84774a7f0 http.request.method=GET http.request.remoteaddr="172.18.0.3:48053" http.request.uri="/v2/activemq/centos5_activemq-5.11.11/tags/list" http.request.useragent="Go-http-client/1.1" instance.id=473cf9bc-1a25-47d2-a38f-5776a3c688d3 service=registry trace.duration=128.402µs trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=820c12e8-103b-466d-a216-64028c4b41ef trace.line=150 vars.name="activemq/centos5_activemq-5.11.11" version=v2.4.0 
May 31 09:25:08 udokreg docker/registry[740]: time="2016-05-31T01:25:08.802477317Z" level=info msg="response completed" go.version=go1.6.1 http.request.host="registry:5000" http.request.id=e5f08ba3-9ea5-463f-8e02-58f84774a7f0 http.request.method=GET http.request.remoteaddr="172.18.0.3:48053" http.request.uri="/v2/activemq/centos5_activemq-5.11.11/tags/list" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=13.112833ms http.response.status=200 http.response.written=61 instance.id=473cf9bc-1a25-47d2-a38f-5776a3c688d3 service=registry version=v2.4.0 
May 31 09:25:08 udokreg docker/registry[740]: 172.18.0.3 - - [31/May/2016:01:25:08 +0000] "GET /v2/activemq/centos5_activemq-5.11.11/tags/list HTTP/1.1" 200 61 "" "Go-http-client/1.1"



docker_ui.log

May 31 09:25:06 udokreg docker/ui[740]: 2016-05-31T01:25:06Z [DEBUG] [challenge.go:29]: challenges: [{bearer map[realm:http://192.168.1.123/service/token service:token-service]}]
May 31 09:25:06 udokreg docker/ui[740]: 2016-05-31T01:25:06Z [DEBUG] [repository.go:109]: initialized a repository client with username: http://registry:5000 activemq/centos5_activemq-5.11.11 admin
May 31 09:25:06 udokreg docker/ui[740]: 2016-05-31T01:25:06Z [DEBUG] [authutils.go:42]: scopes: [repository:activemq/centos5_activemq-5.11.11:pull,push]
May 31 09:25:06 udokreg docker/ui[740]: 2016-05-31T01:25:06Z [INFO] current access, type: repository, name:activemq/centos5_activemq-5.11.11, actions:[push * pull]
May 31 09:25:06 udokreg docker/ui[740]: 2016-05-31T01:25:06Z [DEBUG] [tokenhandler.go:245]: get token by calling GenTokenForUI directly
May 31 09:25:06 udokreg docker/ui[740]: 2016-05-31T01:25:06Z [DEBUG] [tokenhandler.go:101]: add token to cache
May 31 09:25:06 udokreg docker/ui[740]: 2016-05-31T01:25:06Z [DEBUG] [tokenhandler.go:109]: add token to request: GET http://registry:5000/v2/activemq/centos5_activemq-5.11.11/tags/list
May 31 09:25:08 udokreg docker/ui[740]: 2016-05-31T01:25:08Z [DEBUG] [transport.go:56]: 200 | GET http://registry:5000/v2/activemq/centos5_activemq-5.11.11/tags/list
May 31 09:25:08 udokreg docker/ui[740]: 2016/05/31 01:25:08 #033[1;34m[router.go:828][D] | GET        | /api/repositories/tags                   | 2.033750576s     | match      | /api/repositories/tags                   | #033[0m

thank you very much

**Comment by ywk253100** [comment]
Thank you for your feedback. This is caused by the character "." in the namespace of repository "activemq/centos5_activemq-5.11.11". You can rename it by avoiding the character as a workaround for now. And we will fix it soon.

**Comment by yuqipg** [comment]
hi,have you fix the bug? Thank you

**Comment by wknet123** [comment]
We've made a refactor on API with data models' attribute renamed, and this branch will merge to master with this bug fixed as soon as possible, thanks.

**Comment by yuqipg** [comment]
![Uploading QQ截图20160606111035.png…]()

**Comment by yuqipg** [comment]
![qq 20160606111035](https://cloud.githubusercontent.com/assets/18362187/15811080/91ba4bfa-2bd7-11e6-8e41-03d9e4d08667.png)
Hi,I have merge the code "fixed bug of issue #284" but it still not work,can you help me found out  the issue or .something i do wrong

**Comment by ywk253100** [comment]
@yuqipg You should rebuild Harbor by running "docker-compose build" and then restart it by running "docker-compose up -d". Clear the browser cache if needed.

**Comment by yuqipg** [comment]
i have do the  following step
1.docker-compose stop
2.docker-compose rm
3.remove all the data which docker-compose file volume to the host machine
4. download the harbor repository
5.do the install guide step

it still not work 
![qq 1](https://cloud.githubusercontent.com/assets/18362187/15851025/a6c13486-2ccd-11e6-8db2-4756d0aaaa92.png)
![qq 2](https://cloud.githubusercontent.com/assets/18362187/15851027/aa281220-2ccd-11e6-9732-d1c724c4ea90.png)

**Comment by ywk253100** [comment]
I have tested the issue and it is fixed in the latest codes. The key to resolve it for you is image-rebuilding. Your steps "1.docker-compose stop", "2.docker-compose rm", "5.do the install guide step" are just operating containers, but the images which containers are created from are not changed. So you should:
1. pull the latest codes from master branch
2. modify harbor/Deploy/harbor.cfg
3. cd harbor/Deploy and run prepare
4. run "docker-compose build", this is the key step
5. run "docker-compose up -d" to start Harbor
6. clear cache of browser if needed

**Comment by yuqipg** [comment]
Thank you,but  i have did this step"4. run "docker-compose build", this is the key step",maybe i need rmi all the images which the docker compose file used

**Comment by ywk253100** [comment]
The issue is fixed by some modification of javascript codes. So you should make sure the javascript codes that your browser loads is the latest, you can prepare them with the changes of #308 in your browser.
