### ISSUE TITLE
404 on 443 port when deployed with .ova

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#2840]
The guys working on .ova suggest we should redirect or render a message, otherwise it will confuse the user upgraded from 1.1.x

@steven-zou I think you mentioned this right?  I couldn't find the issue, so opening this one to track this part of the work.

**Comment by steven-zou** [comment]
@reasonerjt 

  I did not get the background of this issue. Do you mean the one used to disable standalone api when deployed with .ova? If yes, current solution is directly disabled the related apis. As a result, 403 will be returned.

**Comment by steven-zou** [comment]
#2728

**Comment by reasonerjt** [comment]
@steven-zou I mean the home page of UI
When user uses browser to access Harbor after deploying via .ova

**Comment by steven-zou** [comment]
@reasonerjt 

  Yes, the page request is also disabled at the router table under integration mode.

**Comment by steven-zou** [comment]
If in integration mode, all the requests to the harbor portal pages will be redirected to Admiral endpoint. Code merged. Close it.
