### ISSUE TITLE
Error response from daemon: login: code: 404

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/harbor#2841]
I have a harbor instance installed using the latest OVA master branch and I have added the harbor instance as an insecure registry to my vanilla docker daemon:
dockerd -H fd:// -s overlay --dns 8.8.8.8 --dns 10.118.81.1 --insecure-registry=10.192.252.171:443

When I attempt login:
docker login 10.192.252.171:443
Username: admin
Password: 
Error response from daemon: Login:  (Code: 404; Headers: map[Date:[Fri, 21 Jul 2017 16:52:49 GMT] Content-Type:[text; charset=plain] X-Frame-Options:[DENY] Content-Length:[0]])

**Comment by mhagen-vmware** [comment]
No longer seeing this on the latest build:
https://storage.googleapis.com/vic-product-ova-builds/vic-b51b4adc-dev.ova

**Comment by wy65701436** [comment]
Thanks Mikkel
