### ISSUE TITLE
Value error when swift keystone password contains special charactor

### ISSUE THREAD

**Issue by joeyjy** [vmware/harbor#2848]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
Docker version 1.12.3, build 6b644ec
docker-compose version 1.8.1, build 878cff1

2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
only set hostname to IP

3)Log files, you can get them by package the /var/log/harbor/ .

Hi VMware team,

I met a ValueError when running ./prepare, I found that my password to connecting keystone contains special characters: pasS!@#$
I think these special characters cause the ValueError when generating config file, please take a look

Thanks

**Comment by reasonerjt** [comment]
@joeyjy thanks for reporting.

I didn't reproduce this issue, could you clarify which attribute was set to "pasS!@#$"?

I would be more helpful if you can provide the stacktrace of the python script.

**Comment by joeyjy** [comment]
@reasonerjt 

storage:
    swift:
        username: swift
        password: **pasS!@#$**                                                                                                                                          
        authurl: http://keystone:35357/v2.0
        tenant: admin
        container: harbor
    cache:
        layerinfo: inmemory
    maintenance:
        uploadpurging:
            enabled: false
    delete:
        enabled: true

**Comment by reasonerjt** [comment]
I see, so you updated the harbor/make/common/templates/registry/config.yml?
Because it's template the `$`should be replaced by `$$`

**Comment by joeyjy** [comment]
@reasonerjt Oh, Thanks! I didn't know this before, will close this issue
