### ISSUE TITLE
The same repository can not be pushed if its project is deleted and created again in integration mode with notary enabled

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#2857]
In integration mode, the project can be deleted even though it contains repositories and replication rules. When a project with the same name is created again, the same repository can not be pushed as the user has no signature key if the content trust is enabled.

**Comment by reasonerjt** [comment]
@ywk253100 I believe this is not valid anymore?  As there will be a pre-req check before deleting a project?

**Comment by ywk253100** [comment]
@reasonerjt Yes, closing this issue.
