### ISSUE TITLE
show error info if click the log of a pending status replication job

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#2870]
Click "log" of a pending status job will display
 "Your request cannot be completed because the object does not exist."

Ideally we should just display empty log content without any error message. 

<img width="702" alt="screen shot 2017-07-26 at 11 17 37 am" src="https://user-images.githubusercontent.com/1715683/28603030-3c3a1a34-71f4-11e7-8318-289e7b15975d.png">

**Comment by lweitzman** [comment]
ideally you can add the job to the list of replication jobs but don't put the log icon in the datagrid until the logs exist. also, the status could indicate that the job is "running" or "pending" that way no error will ever be produced.

**Comment by steven-zou** [comment]
Fixed in PR #2885, close issue.
