### ISSUE TITLE
only show 500 item in replication Jobs tab

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#2879]
If you have more than 500 images in one project and setup replication, you will only see 500 jobs in the "Replication Jobs" panel.

**Comment by steven-zou** [comment]
Please provide the api response, especially the header with total count

**Comment by yixingjia** [comment]
Connection:keep-alive
Content-Encoding:gzip
Content-Type:application/json; charset=utf-8
Date:Thu, 27 Jul 2017 05:46:33 GMT
Link:</api/jobs/replication?end_time=&page=2&policy_id=2&repository=&start_time=&status=>; rel="next"
Server:nginx/1.11.13
Transfer-Encoding:chunked
X-Total-Count:505

**Comment by steven-zou** [comment]
Let's support server-driven pagination

**Comment by steven-zou** [comment]
Fixed, close
