### ISSUE TITLE
The Daily scan all mechanism may need changed

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#2880]
Currently it seems Clair will scan all the images daily even they already have been scanned. 

For the environment with 505 images it will take 12.5 hours ( more or less) to finish each round. 

So this brings two possible issues in the future:
1> if customer has more images then the daily scan will not finished in 24 hours and day by day our system will eventually run out of resource, we should try to avoid this if the previous run don't finished, new jobs will not trigger.

2> according to Clair's design , only new images need to be scanned, olds images only need to query it's vulnerability status to update the overview status.
This will help save a lot of resources.

**Comment by reasonerjt** [comment]
Let's reproduce the 12h scenario first, as I retried via one single image, by comparing the log files, the scan on my env took only a few seconds while on the problematic env it took more than 10mins.

**Comment by reasonerjt** [comment]
root cause seems to be connection leak, should be fixed in #2960

**Comment by reasonerjt** [comment]
Fixed in #2972
