### ISSUE TITLE
Creation time of different tags

### ISSUE THREAD

**Issue by srm09** [vmware/harbor#2882]
While pushing images to Harbor, if the same image is tagged with different tags, the creation time of the UI is the same for all the tags.
Following steps can be used to reproduce:
```
docker pull hello-world
docker tag hello-world 192.1.2.3/abcd/hworld:1.0
docker push 192.1.2.3/abcd/hworld:1.0
docker tag hello-world 192.1.2.3/abcd/hworld:2.0
docker push 192.1.2.3/abcd/hworld:2.0
```
In this case, the creation time for both the tags would be the creation time when the second image is pushed.

**Comment by steven-zou** [comment]
@srm912 

  The creation time is from the docker registry. It should be same for the same image even it's tagged with different tags. The time is the 'docker build' time.

**Comment by srm912** [comment]
@steven-zou This makes sense from the registry POV. But as a Harbor end user, two tags/images having the same creation time might be slightly confusing. And from the perspective of the end user, how did I manage to update the time of an earlier tag when that particular tag wasn't even touched.

I get it that this is the correct functionality from the docker perspective, but on the Harbor UI it might cause the user to be confused.

**Comment by reasonerjt** [comment]
I don't think we plan to fix this.
Closing.
