### ISSUE TITLE
[UI] it takes about 6 seconds to load home page.

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#2887]
![image](https://user-images.githubusercontent.com/2841473/28661832-eb81d4e6-726c-11e7-9b70-7a0797206207.png)

**Comment by steven-zou** [comment]
<img width="1375" alt="2017-07-27 17 53 06" src="https://user-images.githubusercontent.com/5753287/28665004-c735b70a-72f4-11e7-8d28-2dc15ebeaba4.png">


Please remove the proxy settings, it will cause perf issue.

Checked as snapshot shown, no perf issue existing.
