### ISSUE TITLE
[UI] Please show reasonable time format for Scan Now

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#2890]
![image](https://user-images.githubusercontent.com/2841473/28662225-3a1fa960-726e-11e7-84e9-552bbd82e01c.png)

**Comment by steven-zou** [comment]
Will check later

**Comment by steven-zou** [comment]
Change datatime format from 'HH:mm' to 'yyyy/MM/dd HH:mm'. Code merged, close issue.
