### ISSUE TITLE
inline alert position are differ

### ISSUE THREAD

**Issue by pengpengshui** [vmware/harbor#2896]
![image](https://user-images.githubusercontent.com/29880301/28664682-d18fa28e-72f3-11e7-86b9-e454ea17912b.png)

![image](https://user-images.githubusercontent.com/29880301/28664380-df7c14d2-72f2-11e7-99e9-cd9ade178b4d.png)
![image](https://user-images.githubusercontent.com/29880301/28664501-4e266a90-72f3-11e7-9fe2-5f0c8cff60b9.png)

**Comment by steven-zou** [comment]
@pengpengshui 

  please help to fix this issue.
