### ISSUE TITLE
can never delete a endpoint if the job failed due to endpoint configuration error

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#2897]
1.> create endpoint ,input wrong ip( simulate user input error) and save
2> start a replication rule with this endpoint

3>the jobs will always in retrying status and never finished

4> try to delete the replication rule  will failed report error: cannot delete due to a job is running.

workaround ：

disable the rule and wait the next scheduler then the task will change to cancel status 
then  rule can be deleted .

We should ether document this or fix the issue (like add the cancel job transfer functionality)

**Comment by reasonerjt** [comment]
As far as I remember, we decided that disabling the rule is the "official" way to stop a job.  
If we have no problem with this approach, let's just document this.

But a potential enhancement here is to introduce a max-retry mechanism in the job service controller.

**Comment by ywk253100** [comment]
Will close it if PR #4004 is merged.
