### ISSUE TITLE
when click scan ,response data  scan_overview  missing

### ISSUE THREAD

**Issue by pengpengshui** [vmware/harbor#2898]
![image](https://user-images.githubusercontent.com/29880301/28666031-5568f584-72f8-11e7-942d-26af09be5f4a.png)

**Comment by steven-zou** [comment]
@reasonerjt 

Click 'scan' to trigger the scanning action and 200 ok returned. Follow on that, sending 'getTag' requests to get details of the tag by interval, but scan_overview info is missing in the json data returned. It will cause none-stopped 'getTag' requests at the front end.

**Comment by reasonerjt** [comment]
@steven-zou however before the job is scheduled there won't be any scan_overview info.
Will it help to return an empty json under that attribute?

**Comment by reasonerjt** [comment]
This is expected behavior.
The statemachine will initialize the data of scan_overview, so before the job is scheduled you won't get the info.
Or are you saying the job is never scheduled on job service?

**Comment by reasonerjt** [comment]
Checked the log:
Jul 28 16:42:26 172.18.0.1 jobservice[820]: 2017-07-28T08:42:26Z [DEBUG] [workerpool.go:79]: worker: {ID: 2, Type: Scan}, will handle job: {JobID: 36, JobType: Scan}
Jul 28 16:42:26 172.18.0.1 jobservice[820]: 2017-07-28T08:42:26Z [ERROR] [workerpool.go:101]: Worker {ID: 2, Type: Scan}, failed to re-initialize statemachine for job: {JobID: 36, JobType: Scan}, error: Error 1054: Unknown column ‘id’ in ‘field list’

which means the DB schema is incorrect.  So this is a environment issue.
However, it'd be better the UI get notified for such unexpected error, keep this open and set it as defer-candidate.

**Comment by reasonerjt** [comment]
This issue is fixed after migrating the db schema, closing.
