### ISSUE TITLE
scan can`t  stop

### ISSUE THREAD

**Issue by pengpengshui** [vmware/harbor#2899]
when scan a tag,then click other nav,  switch back to click scan ,several times, the scan can`t stop 

![image](https://user-images.githubusercontent.com/29880301/28666558-6bb958a4-72fa-11e7-8445-a4ce40f95c49.png)

**Comment by steven-zou** [comment]
There might be caused by the subscription timer is not successfully unsubscribe

**Comment by steven-zou** [comment]
Rechecked, after upgrade database schema, issue can not be reproduced! Close issue.
