### ISSUE TITLE
Support disabling LDAP referrals

### ISSUE THREAD

**Issue by SEJeff** [vmware/harbor#29]
This is needed to authenticate against Active Directory. Briefly scanning `auth/ldap/ldap.go`, there isn't a way to set this.

**Comment by ywk253100** [comment]
Sorry, I don't quite understand  what your meaning is. Harbor now supports LDAP, you can configure it by modifying harbor.cfg in Deploy directory. Does this meet your needs? Or you can explain your needs more clearly.

**Comment by SEJeff** [comment]
```diff
diff --git a/auth/ldap/ldap.go b/auth/ldap/ldap.go
index bc24cb8..153f0ee 100644
--- a/auth/ldap/ldap.go
+++ b/auth/ldap/ldap.go
@@ -60,25 +60,42 @@ func (l *Auth) Authenticate(m models.AuthModel) (*models.User, error) {
 
        ldap.SetOption(openldap.LDAP_OPT_PROTOCOL_VERSION, openldap.LDAP_VERSION3)
 
+       // For authenticating against Active Directory LDAP servers, referrals must be disabled
+       ldapReferrals := os.Getenv("LDAP_DISABLE_REFERRALS")
+       if len(ldapReferrals) > 0 {
+               beego.Info("Disabling LDAP Referrals")
+               ldap.SetOption(openldap.LDAP_OPT_REFERRALS, 0)
+       }
+
```

I successfully implemented this with the following diff, but looking more, I was able to work around this and keep them enabled. In the python ldap client, they have to be disabled. This isn't actually necessary anymore so closing.
