### ISSUE TITLE
panic: unable to configure authorization (token): token auth requires at least one token signing root certificate

### ISSUE THREAD

**Issue by justlooks** [vmware/harbor#2902]
**Environment:**

> For Kubernates
> 
> Kubernetes version (use kubectl version): v1.7.0
> Cloud provider or hardware configuration**:
> OS (e.g. from /etc/os-release): CentOS 7
> Kernel (e.g. uname -a): Linux k8s-master 3.10.0-514.6.2.el7.x86_64
> Install tools: Kubeadm
> Others:
> docker version : Docker version 1.12.6,
> My RPM version :
> docker-1.12.6-16.el7.centos.x86_64.rpm
> kubectl-1.7.0-0.x86_64.rpm
> kubernetes-cni-0.5.1-0.x86_64.rpm
> kubeadm-1.7.0-0.x86_64.rpm
> kubelet-1.7.0-0.x86_64.rpm
> 
> For Harbor
> harbor-offline-installer-v1.1.2.tgz
> git clone https://github.com/vmware/harbor.git
> 
> reference Doc
> https://github.com/vmware/harbor/blob/master/docs/kubernetes_deployment.md
> 

i have three node cluster 

```
[root@k8s-master tmp]# kubectl get nodes
NAME         STATUS    AGE       VERSION
k8s-master   Ready     2d        v1.7.0
k8s-node1    Ready     2d        v1.7.0
k8s-node2    Ready     2d        v1.7.0
```

as Doc said ,i uncompressed offline installer ,and get the harbor.tgz and uncompress add the image into docker on every node in the cluster using "docker load < harbor.tar"

and i have crt file and key file

```
[root@k8s-master tmp]# ls /data/cert/
secret.txt  STAR.epei360.com.crt  STAR.epei360.com.key 
```

first ,i modify the harbor.cfg file like this 
```
[root@k8s-master make]# egrep '^[^#]' harbor.cfg
hostname = harbor.epei360.com
ui_url_protocol = https
db_password = root123
max_job_workers = 3
customize_crt = on
ssl_cert = /data/cert/STAR.epei360.com.crt
ssl_cert_key = /data/cert/STAR.epei360.com.key
admiral_url = NA
clair_db_password = password
email_identity =
email_server = xxx
email_server_port = 25
email_username = xxx
email_password = xxx
email_from = admin <xxx
email_ssl = false
harbor_admin_password = Harbor12345
auth_mode = db_auth
ldap_url = ldaps://ldap.mydomain.com
ldap_basedn = ou=people,dc=mydomain,dc=com
ldap_uid = uid
ldap_scope = 3
ldap_timeout = 5
self_registration = on
token_expiration = 30
project_creation_restriction = everyone
verify_remote_cert = on
```
i do not know the following option function so i just comment it 
```
#The path of secretkey storage
#secretkey_path = /data/cert
```

and i modified all replication controller file under make/kubernetes/{jobservice,mysql,nginx,registry,ui},let the image option point to correct image 

```
[root@k8s-master harbor]# grep image: make/kubernetes/*/*.rc.yaml
make/kubernetes/jobservice/jobservice.rc.yaml:        image: vmware/harbor-jobservice:v1.1.2
make/kubernetes/mysql/mysql.rc.yaml:        image: vmware/harbor-notary-db:mariadb-10.1.10
make/kubernetes/nginx/nginx.rc.yaml:        image: vmware/nginx:1.11.5-patched
make/kubernetes/registry/registry.rc.yaml:        image: vmware/registry:2.6.1-photon
make/kubernetes/ui/ui.rc.yaml:        image: vmware/harbor-ui:v1.1.2
```

```
vmware/harbor-jobservice                                 v1.1.2              ac332f9bd31c        6 weeks ago         162.9 MB
vmware/harbor-ui                                         v1.1.2              803897be484a        6 weeks ago         182.9 MB
vmware/harbor-adminserver                                v1.1.2              360b214594e7        6 weeks ago         141.6 MB
vmware/harbor-db                                         v1.1.2              6f71ee20fe0c        6 weeks ago         328.5 MB
vmware/registry                                          2.6.1-photon        0f6c96580032        10 weeks ago        150.3 MB
vmware/harbor-notary-db                                  mariadb-10.1.10     64ed814665c6        3 months ago        324.1 MB
vmware/nginx                                             1.11.5-patched      8ddadb143133        3 months ago        199.2 MB
vmware/notary-photon                                     signer-0.5.0        b1eda7d10640        4 months ago        155.7 MB
vmware/notary-photon                                     server-0.5.0        6e2646682e3c        4 months ago        156.9 MB
vmware/harbor-log                                        v1.1.2              9c46a7b5e517        5 months ago        192.4 MB
```

and i keep the pv file and pvc untouched( for test install ,i do not change this two kinds of files),and i use script to produce new configmap file 

```
[root@k8s-master harbor]# python make/kubernetes/prepare
Warning: Key(crt_country) is not existing. Use empty string as default
Warning: Key(crt_state) is not existing. Use empty string as default
Warning: Key(crt_location) is not existing. Use empty string as default
Warning: Key(crt_organization) is not existing. Use empty string as default
Warning: Key(crt_organizationalunit) is not existing. Use empty string as default
Warning: Key(crt_commonname) is not existing. Use empty string as default
Warning: Key(crt_email) is not existing. Use empty string as default
Warning: Key(ldap_searchdn) is not existing. Use empty string as default
Warning: Key(ldap_search_pwd) is not existing. Use empty string as default
Warning: Key(ldap_filter) is not existing. Use empty string as default
Warning: Key(use_compressed_js) is not existing. Use empty string as default
```

and final step

```
# create pv & pvc
kubectl apply -f make/kubernetes/pv/log.pv.yaml
kubectl apply -f make/kubernetes/pv/registry.pv.yaml
kubectl apply -f make/kubernetes/pv/storage.pv.yaml
kubectl apply -f make/kubernetes/pv/log.pvc.yaml
kubectl apply -f make/kubernetes/pv/registry.pvc.yaml
kubectl apply -f make/kubernetes/pv/storage.pvc.yaml

# create config map
kubectl apply -f make/kubernetes/jobservice/jobservice.cm.yaml
kubectl apply -f make/kubernetes/mysql/mysql.cm.yaml
kubectl apply -f make/kubernetes/nginx/nginx.cm.yaml
kubectl apply -f make/kubernetes/registry/registry.cm.yaml
kubectl apply -f make/kubernetes/ui/ui.cm.yaml

# create service
kubectl apply -f make/kubernetes/jobservice/jobservice.svc.yaml
kubectl apply -f make/kubernetes/mysql/mysql.svc.yaml
kubectl apply -f make/kubernetes/nginx/nginx.svc.yaml
kubectl apply -f make/kubernetes/registry/registry.svc.yaml
kubectl apply -f make/kubernetes/ui/ui.svc.yaml

# create k8s rc
kubectl apply -f make/kubernetes/registry/registry.rc.yaml
kubectl apply -f make/kubernetes/mysql/mysql.rc.yaml
kubectl apply -f make/kubernetes/jobservice/jobservice.rc.yaml
kubectl apply -f make/kubernetes/ui/ui.rc.yaml
kubectl apply -f make/kubernetes/nginx/nginx.rc.yaml
```

and i check if all component work fine

```
[root@k8s-master harbor]# kubectl get configmaps
NAME                       DATA      AGE
harbor-jobservice-config   16        19h
harbor-mysql-config        1         22h
harbor-nginx-config        3         22h
harbor-registry-config     2         19h
harbor-ui-config           30        19h

[root@k8s-master harbor]# kubectl get services -o wide
NAME         CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE       SELECTOR
jobservice   10.104.177.147   <none>        80/TCP              19h       name=jobservice-apps
kubernetes   10.96.0.1        <none>        443/TCP             2d        <none>
mysql        10.96.125.222    <none>        3306/TCP            22h       name=mysql-apps
nginx        10.105.229.63    <none>        80/TCP,443/TCP      22h       name=nginx-apps
registry     10.102.85.53     <none>        5000/TCP,5001/TCP   19h       name=registry-apps
ui           10.104.163.65    <nodes>       80:30085/TCP        19h       name=ui-apps

[root@k8s-master harbor]# kubectl get pods -o wide
NAME                  READY     STATUS             RESTARTS   AGE       IP             NODE
busybox               1/1       Running            68         2d        172.16.1.112   k8s-node1
jobservice-rc-bfw50   0/1       CrashLoopBackOff   197        19h       172.16.1.114   k8s-node1
mysql-rc-q67xx        1/1       Running            1          22h       172.16.1.113   k8s-node1
nginx-rc-6v2gr        1/1       Running            40         22h       172.16.2.16    k8s-node2
registry-rc-330w8     0/1       CrashLoopBackOff   237        19h       172.16.1.110   k8s-node1
ui-rc-k7j93           0/1       CrashLoopBackOff   197        19h       172.16.2.13    k8s-node2


```it seems jobservice and ui crash because they all can not find adminserver

```
[root@k8s-master harbor]# kubectl logs jobservice-rc-bfw50
2017-07-28T01:54:49Z [INFO] Config path: /etc/jobservice/app.conf
2017-07-28T01:54:49Z [INFO] initializing configurations...
2017-07-28T01:54:49Z [INFO] key path: /etc/jobservice/key
2017-07-28T01:54:49Z [INFO] initializing client for adminserver http://adminserver ...
2017-07-28T01:54:49Z [ERROR] [utils.go:94]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp: lookup adminserver: no such host
2017-07-28T01:54:51Z [ERROR] [utils.go:94]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp: lookup adminserver: no such host
2017-07-28T01:54:53Z [ERROR] [utils.go:94]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp: lookup adminserver: no such host
2017-07-28T01:54:55Z [ERROR] [utils.go:94]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp: lookup adminserver: no such host
2017-07-28T01:54:57Z [ERROR] [utils.go:94]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp: lookup adminserver: no such host
2017-07-28T01:54:59Z [ERROR] [utils.go:94]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp: lookup adminserver: no such host

[root@k8s-master harbor]# kubectl logs ui-rc-k7j93
2017-07-28T01:54:48Z [INFO] Config path: /etc/ui/app.conf
2017-07-28T01:54:48Z [INFO] initializing configurations...
2017-07-28T01:54:48Z [INFO] key path: /etc/ui/key
2017-07-28T01:54:48Z [INFO] initializing client for adminserver http://adminserver ...
2017-07-28T01:54:48Z [ERROR] [utils.go:94]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp: lookup adminserver: no such host
2017-07-28T01:54:50Z [ERROR] [utils.go:94]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp: lookup adminserver: no such host
2017-07-28T01:54:52Z [ERROR] [utils.go:94]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp: lookup adminserver: no such host
2017-07-28T01:54:54Z [ERROR] [utils.go:94]: failed to connect to tcp://adminserver:80, retry after 2 seconds :dial tcp: lookup adminserver: no such host

```
is  http://adminserver registry address? and registry log seems difference content

```
[root@k8s-master harbor]# kubectl logs registry-rc-330w8
time="2017-07-28T01:59:32Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT"
time="2017-07-28T01:59:32Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5000_TCP"
time="2017-07-28T01:59:32Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5000_TCP_ADDR"
time="2017-07-28T01:59:32Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5000_TCP_PORT"
time="2017-07-28T01:59:32Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5000_TCP_PROTO"
time="2017-07-28T01:59:32Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5001_TCP"
time="2017-07-28T01:59:32Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5001_TCP_ADDR"
time="2017-07-28T01:59:32Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5001_TCP_PORT"
time="2017-07-28T01:59:32Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_PORT_5001_TCP_PROTO"
time="2017-07-28T01:59:32Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_SERVICE_HOST"
time="2017-07-28T01:59:32Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_SERVICE_PORT"
time="2017-07-28T01:59:32Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_SERVICE_PORT_DEBUG"
time="2017-07-28T01:59:32Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_SERVICE_PORT_REPO"
time="2017-07-28T01:59:32.063035045Z" level=info msg="debug server listening localhost:5001"
time="2017-07-28T01:59:32.064996602Z" level=info msg="configuring endpoint harbor (http://ui/service/notifications), timeout=3s, headers=map[]" go.version=go1.7.5 instance.id=bf0cf4f4-13f3-4f1e-9def-06d4ea5ae466 service=registry version=v2.6.1
time="2017-07-28T01:59:32.065081338Z" level=info msg="redis not configured" go.version=go1.7.5 instance.id=bf0cf4f4-13f3-4f1e-9def-06d4ea5ae466 service=registry version=v2.6.1
time="2017-07-28T01:59:32.093151758Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.7.5 instance.id=bf0cf4f4-13f3-4f1e-9def-06d4ea5ae466 service=registry version=v2.6.1
panic: unable to configure authorization (token): token auth requires at least one token signing root certificate
goroutine 1 [running]:
panic(0xb4cd00, 0xc4203a8110)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/docker/distribution/registry/handlers.NewApp(0x10667e0, 0xc42035af90, 0xc4201f5500, 0x10667e0)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:302 +0x1b6a
github.com/docker/distribution/registry.NewRegistry(0x7ff09f380198, 0xc42035af90, 0xc4201f5500, 0xe, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/registry.go:86 +0x213
github.com/docker/distribution/registry.glob..func1(0x108e160, 0xc420354250, 0x1, 0x1)
	/go/src/github.com/docker/distribution/registry/registry.go:55 +0x106
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x108e160, 0xc420354200, 0x1, 0x1, 0x108e160, 0xc420354200)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x190
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x108e300, 0xc4201abf40, 0xc4200001a0)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x3c3
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:24 +0x2d
```

am i miss config something ,or it just have some unknown problem on kubernentes v1.7.0?

**Comment by reasonerjt** [comment]
Currently we don't officially support k8s deployment, hopefully in the near future there will be some concrete plan for that.

**Comment by nMustaki** [comment]
Hi,
I know I am late, but if it may be of any help to someone else...
I got this error because I was giving the ssl key instead of the ssl certificate as the REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE parameter. This is in the registry configuration.

Have fun !
