### ISSUE TITLE
The statistics metric part need to be revised

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#2903]
From Paul:

In the next screen grab, “STORAGE” seems to be aligned with the REPOSITORIES line. “15 GB Limit” seems to be aligned with the PROJECTS line. It might look better if you lowered “15 GB Limit” (and the graphic above it) and raised “STORAGE”. This way they’d seem more connected to each other and neither will be lined up with PROJECTS or REPOSITORIES.

<img width="550" alt="2017-07-28 13 08 25" src="https://user-images.githubusercontent.com/5753287/28703315-e222db5a-7395-11e7-847f-f351757389bf.png">

**Comment by lweitzman** [comment]
i think the graphic should stay above the line of projects like it is. 2 options increase the vertical separator line color to make it more prominent. another is to just raise the STORAGE label a bit to be centered between the rows of projects and repositories numbers.

**Comment by lweitzman** [comment]
in this mockup i've done both, i've darkened the vertical separator and moved the "Storage" label up.
![screen shot 2017-07-28 at 11 34 08 am](https://user-images.githubusercontent.com/626032/28724786-3e072bcc-7389-11e7-8ec6-c182a09c68f0.png)

**Comment by steven-zou** [comment]
@lweitzman 

ok
