### ISSUE TITLE
vulnerability color error

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#2905]
v1.1.2-564-g9582637

it seems that the medium use yellow and low use orange
![vulvul](https://user-images.githubusercontent.com/23101283/28706968-0ba1f1ce-73a9-11e7-8a7b-ccc49b800885.PNG)

**Comment by steven-zou** [comment]
@lweitzman 

 Any suggestions?

**Comment by lweitzman** [comment]
see #2908

**Comment by steven-zou** [comment]
Duplicated with #2908
