### ISSUE TITLE
[s]

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#2907]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
3)Log files, you can get them by package the /var/log/harbor/ .

**Comment by reasonerjt** [comment]
what is it?

**Comment by wy65701436** [comment]
close it as typo
