### ISSUE TITLE
Inconsistent color for vulnerability overview and detail

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#2908]
![overview](https://user-images.githubusercontent.com/5835782/28709578-779dc970-73b3-11e7-9536-f35e730ad4f8.png)

![detail](https://user-images.githubusercontent.com/5835782/28709587-7cc40e0a-73b3-11e7-94e7-7ec85d0c3f0b.png)

**Comment by lweitzman** [comment]
not only the colors are inconsistent but also the labels. also
1) the unknown icon is the wrong size
2) the icon for low is not what tony provided (it was a triangle with nothing in the center) 
3) the orange color was for medium while the yellow was for low

**Comment by steven-zou** [comment]
Fixed, close it

**Comment by lweitzman** [comment]
fix doesn't show up on https://10.112.122.204/harbor/projects/1/repositories
