### ISSUE TITLE
[UI] The text "Scan Now" and "Scan All" are not clear to understand.   

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#2910]
1, When user to click Scan Now, user cannot know this will trigger an scan all job.
2, If I set None for Scan all, what does this mean?

![image](https://user-images.githubusercontent.com/2841473/28709825-a3ce7652-7336-11e7-8180-57b1105237c5.png)

**Comment by steven-zou** [comment]
@lweitzman 

  Any suggestions?

**Comment by steven-zou** [comment]
“Manual scan available again at 2017/09/01 1:30 pm”

**Comment by lweitzman** [comment]
@steven-zou i agree that the label should be explicit like you suggest above.
the tooltip explains what the "None" selection means so i don't think thats an issue.
the button that says "Scan Now" could be more explicit and say "Scan All Now" but don't think its critical.

**Comment by steven-zou** [comment]
2, If I set None for Scan all, what does this mean?
   None means disable scanning policy. There is tooltips to describe this thing.

**Comment by steven-zou** [comment]
@lweitzman 

  How about add a description header label before the "Scan All" button?
  "Manual Scan:"
   <button>Scan All</button> [availability timestamp text]

Additionally, I have some concerns about this part. As you know, 'Scan All' is a action, not configuration option. Currently it is placed in the configuration parts, it looks so weird.
How about append a new menu item named 'Vulnerability Scanning' at the left nav panel under 'Administration' and put that button and related labels there?

**Comment by lweitzman** [comment]
@steven-zou i don't think we should add another navigation item in the left navigation just for the scanning. like you said its not a configuration but i'm ok with leaving it under the vulnerability tab in the configuration section. 
i will create a new mockup with a variation of the current layout. 
one thought is that we could put the "scan now" button on the same line as "scan all" label. 
underneath it could be the description of when the next scan now time is available.

**Comment by lweitzman** [comment]
having the manual scan "Scan Now" button in the same row makes it clearer that its a scan of all the images. here is a mockup. also available at: https://vmware.invisionapp.com/share/AQBEENGUE#/229520032_Harbor_-_Admin_-_Configuration_-_Vulnerability
![screen shot 2017-08-02 at 11 09 00 am](https://user-images.githubusercontent.com/626032/28880466-214440cc-7773-11e7-84b9-c89ed27b35dc.png)

**Comment by steven-zou** [comment]
@lweitzman 

  That's a good alternative
