### ISSUE TITLE
Got 404 when refreshing browser in the tag detail page

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#2916]
![tag](https://user-images.githubusercontent.com/5835782/28711700-1c49db56-73bb-11e7-8a2c-0fcf4dc4a8f5.png)

![404](https://user-images.githubusercontent.com/5835782/28711774-68ef5fc6-73bb-11e7-885d-90a8ec3c65cb.png)

**Comment by steven-zou** [comment]
Will add this route in router.go

**Comment by steven-zou** [comment]
Fixed, close
