### ISSUE TITLE
Encounter error when using Harbor after a long idle time.

### ISSUE THREAD

**Issue by wknet123** [vmware/harbor#294]
Error logs as below

May 28 11:06:29 172.18.0.1 docker/ui[1875]: fatal error: concurrent map writes
May 28 11:06:29 172.18.0.1 docker/ui[1875]: 
May 28 11:06:29 172.18.0.1 docker/ui[1875]: goroutine 3441 [running]:
May 28 11:06:29 172.18.0.1 docker/ui[1875]: runtime.throw(0xc94bb0, 0x15)
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc820392f60 sp=0xc820392f48
May 28 11:06:29 172.18.0.1 docker/ui[1875]: runtime.mapassign1(0x9ce780, 0xc820118540, 0xc820393140, 0xc820393090)
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/usr/local/go/src/runtime/hashmap.go:540 +0x54b fp=0xc820393008 sp=0xc820392f60
May 28 11:06:29 172.18.0.1 docker/ui[1875]: github.com/vmware/harbor/vendor/github.com/astaxie/beego.BuildTemplate(0xc1a5c8, 0x5, 0xc820393350, 0x1, 0x1, 0x0, 0x0)
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/go/src/github.com/vmware/harbor/vendor/github.com/astaxie/beego/template.go:153 +0x8a4 fp=0xc820393230 sp=0xc820393008
May 28 11:06:29 172.18.0.1 docker/ui[1875]: github.com/vmware/harbor/vendor/github.com/astaxie/beego.(*Controller).RenderBytes(0xc820225e00, 0x0, 0x0, 0x0, 0x0, 0x0)
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/go/src/github.com/vmware/harbor/vendor/github.com/astaxie/beego/controller.go:259 +0x1746 fp=0xc8203934b8 sp=0xc820393230
May 28 11:06:29 172.18.0.1 docker/ui[1875]: github.com/vmware/harbor/vendor/github.com/astaxie/beego.(*Controller).Render(0xc820225e00, 0x0, 0x0)
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/go/src/github.com/vmware/harbor/vendor/github.com/astaxie/beego/controller.go:183 +0x4e fp=0xc820393518 sp=0xc8203934b8
May 28 11:06:29 172.18.0.1 docker/ui[1875]: github.com/vmware/harbor/controllers/ng.(*NavigationDetailController).Get(0xc820225e00)
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/go/src/github.com/vmware/harbor/controllers/ng/navigationdetail.go:33 +0x4f4 fp=0xc8203937c0 sp=0xc820393518
May 28 11:06:29 172.18.0.1 docker/ui[1875]: github.com/vmware/harbor/vendor/github.com/astaxie/beego.(*ControllerRegister).ServeHTTP(0xc820118630, 0x7f022a7f17b0, 0xc82044b790, 0xc8201d0d20)
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/go/src/github.com/vmware/harbor/vendor/github.com/astaxie/beego/router.go:760 +0x1d1d fp=0xc820393b60 sp=0xc8203937c0
May 28 11:06:29 172.18.0.1 docker/ui[1875]: net/http.serverHandler.ServeHTTP(0xc820084180, 0x7f022a7f17b0, 0xc82044b790, 0xc8201d0d20)
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/usr/local/go/src/net/http/server.go:2081 +0x19e fp=0xc820393bc0 sp=0xc820393b60
May 28 11:06:29 172.18.0.1 docker/ui[1875]: net/http.(*conn).serve(0xc820cb6f80)
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/usr/local/go/src/net/http/server.go:1472 +0xf2e fp=0xc820393f88 sp=0xc820393bc0
May 28 11:06:29 172.18.0.1 docker/ui[1875]: runtime.goexit()
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820393f90 sp=0xc820393f88
May 28 11:06:29 172.18.0.1 docker/ui[1875]: created by net/http.(*Server).Serve
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/usr/local/go/src/net/http/server.go:2137 +0x44e
May 28 11:06:29 172.18.0.1 docker/ui[1875]: 
May 28 11:06:29 172.18.0.1 docker/ui[1875]: goroutine 1 [chan receive, 188 minutes]:
May 28 11:06:29 172.18.0.1 docker/ui[1875]: github.com/vmware/harbor/vendor/github.com/astaxie/beego.(*App).Run(0xc82000b810)
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/go/src/github.com/vmware/harbor/vendor/github.com/astaxie/beego/app.go:182 +0xabb
May 28 11:06:29 172.18.0.1 docker/ui[1875]: github.com/vmware/harbor/vendor/github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/go/src/github.com/vmware/harbor/vendor/github.com/astaxie/beego/beego.go:67 +0x163
May 28 11:06:29 172.18.0.1 docker/ui[1875]: main.main()
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/go/src/github.com/vmware/harbor/ui/main.go:77 +0x17a
May 28 11:06:29 172.18.0.1 docker/ui[1875]: 
May 28 11:06:29 172.18.0.1 docker/ui[1875]: goroutine 17 [syscall, 188 minutes, locked to thread]:
May 28 11:06:29 172.18.0.1 docker/ui[1875]: runtime.goexit()
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1
May 28 11:06:29 172.18.0.1 docker/ui[1875]: 
May 28 11:06:29 172.18.0.1 docker/ui[1875]: goroutine 5 [syscall, 188 minutes]:
May 28 11:06:29 172.18.0.1 docker/ui[1875]: os/signal.signal_recv(0x0)
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/usr/local/go/src/runtime/sigqueue.go:116 +0x132
May 28 11:06:29 172.18.0.1 docker/ui[1875]: os/signal.loop()
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
May 28 11:06:29 172.18.0.1 docker/ui[1875]: created by os/signal.init.1
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
May 28 11:06:29 172.18.0.1 docker/ui[1875]: 
May 28 11:06:29 172.18.0.1 docker/ui[1875]: goroutine 6 [chan receive, 8 minutes]:
May 28 11:06:29 172.18.0.1 docker/ui[1875]: github.com/vmware/harbor/vendor/github.com/astaxie/beego/cache.(*MemoryCache).vaccuum(0xc8202a44e0)
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/go/src/github.com/vmware/harbor/vendor/github.com/astaxie/beego/cache/memory.go:216 +0x71
May 28 11:06:29 172.18.0.1 docker/ui[1875]: created by github.com/vmware/harbor/vendor/github.com/astaxie/beego/cache.(*MemoryCache).StartAndGC
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/go/src/github.com/vmware/harbor/vendor/github.com/astaxie/beego/cache/memory.go:206 +0x270
May 28 11:06:29 172.18.0.1 docker/ui[1875]: 
May 28 11:06:29 172.18.0.1 docker/ui[1875]: goroutine 7 [chan send, 188 minutes]:
May 28 11:06:29 172.18.0.1 docker/ui[1875]: github.com/vmware/harbor/dao.InitDB.func1(0xc82000a02b, 0x5, 0xc82000a04b, 0x4, 0xc8202dbea0)
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/go/src/github.com/vmware/harbor/dao/base.go:84 +0x140
May 28 11:06:29 172.18.0.1 docker/ui[1875]: created by github.com/vmware/harbor/dao.InitDB
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/go/src/github.com/vmware/harbor/dao/base.go:90 +0x4b5
May 28 11:06:29 172.18.0.1 docker/ui[1875]: 
May 28 11:06:29 172.18.0.1 docker/ui[1875]: goroutine 9 [chan receive, 188 minutes]:
May 28 11:06:29 172.18.0.1 docker/ui[1875]: database/sql.(*DB).connectionOpener(0xc820110bb0)
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/usr/local/go/src/database/sql/sql.go:727 +0x45
May 28 11:06:29 172.18.0.1 docker/ui[1875]: created by database/sql.Open
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/usr/local/go/src/database/sql/sql.go:493 +0x33f
May 28 11:06:29 172.18.0.1 docker/ui[1875]: 
May 28 11:06:29 172.18.0.1 docker/ui[1875]: goroutine 2219 [select, 11 minutes]:
May 28 11:06:29 172.18.0.1 docker/ui[1875]: net/http.(*persistConn).readLoop(0xc820b60410)
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/usr/local/go/src/net/http/transport.go:1182 +0xd52
May 28 11:06:29 172.18.0.1 docker/ui[1875]: created by net/http.(*Transport).dialConn
May 28 11:06:29 172.18.0.1 docker/ui[1875]: #011/usr/local/go/src/net/http/transport.go:857 +0x10a6

**Comment by reasonerjt** [comment]
should be fixed after upgrading beego to 1.6.1
