### ISSUE TITLE
how to get tag list while using harbor v1.1.1?

### ISSUE THREAD

**Issue by jeremywu0127** [vmware/harbor#2943]
I want to get tags according to this [page](https://github.com/vmware/harbor/issues/1038), I can get repos  like
```
curl -X GET https://myhub.com/api/repositories?project_id=5

[
"my-repo/nginx",
"my-repo/php"
]
```
but if I want to get tag list, it return 404 like
```
curl -X GET https://myhub.com/api/repositories/tags?repo_name=my-repo/nginx

404 Page Not Found
```
how can I get the tag list?

**Comment by steven-zou** [comment]
Have you tried "curl -X GET https://myhub.com/api/repositories/my-repo%2Fnginx/tags"?

**Comment by jeremywu0127** [comment]
it works when using  `curl -X GET https://myhub.com/api/repositories/my-repo%2Fnginx/tags`, thanks
