### ISSUE TITLE
After "scan all" some repositories are not scanned.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#2965]
On the env with 200G+ images, around 200 of them are not scanned after running a "scan all", seems the images under "myvv" project are not scanned.

The root cause is dao.GetAllRepositories() only returns 1000 records by default.

**Comment by reasonerjt** [comment]
Seems ideally dao.GetAllRepositories() should return a channel of array.

**Comment by Unstoppable94** [comment]
# What is the label in github?for examble`kind/bug`.can someone tell me the meaning?

**Comment by wy65701436** [comment]
Close it as fixed.
