### ISSUE TITLE
when i  push some images from localharobor to remote harobor  some thing go bad

### ISSUE THREAD

**Issue by 4680185** [vmware/harbor#2980]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
Server Version: 1.12.6
docker-compose version 1.14.0, build c7bdf9e

2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
3)Log files, you can get them by package the /var/log/harbor/ .

**Comment by reasonerjt** [comment]
Close due to inactivity.
