### ISSUE TITLE
images under library can not be shown 

### ISSUE THREAD

**Issue by cherry4477** [vmware/harbor#299]
[harbor.txt](https://github.com/vmware/harbor/files/292930/harbor.txt)

**Comment by reasonerjt** [comment]
Please package all log files under var/log/harbor and attach to this issue, thanks.

**Comment by cherry4477** [comment]
the container does not include  harbor in var/log. 

my environment is k8s,and what i attached above is through "oc logs harborcontainerid >harbor.txt",and that should be the log of harbor

**Comment by reasonerjt** [comment]
I see, but there are 4 or 5 containers in harbor, I believe you only get the log of one of them.

**Comment by reasonerjt** [comment]
@cherry4477  I don't see your env info during the weekend?

**Comment by reasonerjt** [comment]
dup to #398
