### ISSUE TITLE
Content trust interceptor failed to find signature when 'DOCKER_CONTENT_TRUST=1'

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#2991]
This happens when using vanilla docker

When the env for docker client set the env var to enable docker content trust:
```
export DOCKER_CONTENT_TRUST=1
```
And enable "project level content trust" on Harbor.
Then I issue docker pull to pull a signed image, the failure looks like this:
```
~# docker pull 10.160.247.138/default-project/ubuntu:14.04
Pull (1 of 1): 10.160.247.138/default-project/ubuntu:14.04@sha256:0204dc6e09fa57ab99ac40e415eb637d62c8b2571ecbbc9ca0eb5e2ad2b5c56f
Error response from daemon: unknown: The image is not signed in Notary.
```

The request to pull manifest looks like this:
```
GET /v2/default-project/ubuntu/manifests/sha256:0204dc6e09fa57ab99ac40e415eb637d62c8b2571ecbbc9ca0eb5e2ad2b5c56f
```

Seems in this case the interceptor fails to find the signature from notary.

**Comment by reasonerjt** [comment]
maybe related to #2993

**Comment by wy65701436** [comment]
close it as fixed.
