### ISSUE TITLE
 Get repository tags API error

### ISSUE THREAD

**Issue by Chenpipi** [vmware/harbor#2992]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
docker version: 17.03.2
2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
3)Log files, you can get them by package the /var/log/harbor/ .

I'm use rancher launch harbor and use python api,  Get repository tags return error: 
  ERROR:root:Fail to get tags with repo name: library/aaa
But through the search can see the results：
   u'repository_name': u'library/aaa',
   u'tags_count': 2},
How to solve this problem? 
thanks

**Comment by Chenpipi** [comment]
I found the cause of the problem, after using the new version of harbor, the harbor-py was reinstalled and found that the code was not updated, it's still old code, so the operation could not continue. my environment is python27. now update the code manually and run normally.

**Comment by WaterAndBread** [comment]
i also met this problem. ERROR:root:Fail to get tags with repo name: library/aaa. my environment is python27. Could you tell me what code you update?
