### ISSUE TITLE
Feature request: support for docker stack

### ISSUE THREAD

**Issue by demaniak** [vmware/harbor#2995]
If using [docker (native) swarm](https://docs.docker.com/engine/swarm/), there are several advantages to deploying an application as a [docker stack](https://docs.docker.com/engine/reference/commandline/stack/).

Implementing would required creating a modified version of the current docker-compose file, upgrading it to at least version 3 (pref 3.2), and then finding and fixing/working-around any incompatibilities found.

Ref:
- https://docs.docker.com/compose/compose-file/ 
- https://docs.docker.com/engine/swarm/

**Comment by bweston92** [comment]
Duplicate of #2868

**Comment by demaniak** [comment]
So it seems.
Closing in favor of older issue #2868
