### ISSUE TITLE
UI cannot load l18n context.

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#3005]
User report that l18n context cannot loaded in the latest master branch.

![wechatimg84](https://user-images.githubusercontent.com/1715683/29109417-7e46397c-7d15-11e7-94a7-770b6f815325.jpeg)

**Comment by steven-zou** [comment]
If code is from master, all the i18n messages should be there. Please let the user to clear the cache and force refresh the browser to try again. @yixingjia

**Comment by reasonerjt** [comment]
I see the same issue in the latest .ova, is it reported?
