### ISSUE TITLE
能通过api获取harbor中某个docker镜像的tag

### ISSUE THREAD

**Issue by sgr-smile2015** [vmware/harbor#3011]
看了好多的issues包括open,closed;都没看到提及到,
比如我现在想通过如下方式获取tag:
curl 'http://10.168.1.27:5000/registry/v2/repositories/common/java/tags/list'
能实现么,或者有其他的api接口?
非常感谢.

**Comment by sgr-smile2015** [comment]
运行 curl 'http://10.168.1.27:5000/registry/v2/_catalog'出现如下错误:
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Name":"catalog","Action":"*"}]}]}
harbor 版本是v1.1.1-rc4

**Comment by ywk253100** [comment]
Please refer to the API doc https://github.com/vmware/harbor/blob/master/docs/swagger.yaml.

**Comment by sgr-smile2015** [comment]
it's work to release v1.1.1-rc4 not v0.5.0 , thank you for you help! the 10086 of praise .

**Comment by ywk253100** [comment]
There are some changes for the API, 0.5.0 version of API doc https://github.com/vmware/harbor/blob/0.5.0/docs/swagger.yaml.

**Comment by sgr-smile2015** [comment]
thanks
