### ISSUE TITLE
The "view log" link under "vulnerability" not working.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#3050]
Version v1.2.0-rc1-10-gd010385

When I click the link UI is not sending any request.

**Comment by ywk253100** [comment]
Try the latest build https://storage.googleapis.com/vic-product-ova-builds/vic-73d10421-dev.ova, seems works well.
![scan_log](https://user-images.githubusercontent.com/5835782/29396924-988e088a-834d-11e7-9dee-7956a360f8df.png)

**Comment by reasonerjt** [comment]
I retried and it worked fine, downgrading the issue as it's highly un-reproducible.

**Comment by steven-zou** [comment]
Close this issue as it's un-reproducible.
