### ISSUE TITLE
Increase the length of username in table access_log to 256

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#3057]
The length of username returned by Admiral is bigger than 32.  It looks like "harbor-vic-a357adda-0f7a-43da-be1c-0663b3f7744d".

**Comment by ywk253100** [comment]
Maybe we should increase the length of all usernames in database

**Comment by ywk253100** [comment]
Tables contain property username: user, access_log, replication_target.

**Comment by reasonerjt** [comment]
Let's increase the length in DB to 256, and handle the case when it exceeds 256 chars in access log recorder, but yes it'll be a limitation for standalone user.

**Comment by steven-zou** [comment]
No action need to take at UI end

**Comment by wy65701436** [comment]
Close it as fixed.
