### ISSUE TITLE
Angular is running in the development mode. Call enableProdMode() to enable the production mode.

### ISSUE THREAD

**Issue by lazize** [vmware/harbor#3065]
If you are reporting a problem, please make sure the following information are provided:

1) Version of docker engine and docker-compose.
```shell
# docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:54:03 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:54:03 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
```shell
# docker-compose version
docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

2) Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.

3) Log files, you can get them by package the /var/log/harbor/ .

------------
4) Issue detail:
It shows the message below on chrome developer tools console:
```
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
```

5) Harbor version:
![harbour-version](https://user-images.githubusercontent.com/10844307/29363830-b2809134-8291-11e7-83ad-78b0faeb3ffa.png)

**Comment by steven-zou** [comment]
production mode has been enabled.
Please refer line 9 in 'harbor/src/ui_ng/src/main-aot.ts'.

**Comment by steven-zou** [comment]
If you run it through source code, please enable it yourself.

Set the value of line 20 to be true in file 'harbor/src/ui_ng/src/environments/environment.ts'.

**Comment by steven-zou** [comment]
@lazize 
As it cannot be reproduced in the normal Harbor installation environment, I'll close this issue. You can reopen it if you still have the problem.

**Comment by lazize** [comment]
Well, something is wrong, because I am using the official release. The one from this link: https://github.com/vmware/harbor/releases

It is not a custom one.
