### ISSUE TITLE
"Make Public" also need second confirmation

### ISSUE THREAD

**Issue by ccnupq** [vmware/harbor#3067]
Below is not issue or bug. it is just a small suggestion.

When I "**Delete**" project,

![image](https://user-images.githubusercontent.com/10127024/29396097-458cc766-8348-11e7-9af9-24481eb4dc77.png)

 the UI pops the page for second confirmation. 

![image](https://user-images.githubusercontent.com/10127024/29396104-5449a40e-8348-11e7-8788-c1dcb07f3f1c.png)

We hope "**Make Public**" also have the same  second confirmation to avoid incorrect clicking

Thanks.

**Comment by lweitzman** [comment]
i think that making a project public and deleting one are a bit different use cases. you can't undo a delete. but you can easily set the project to private again. so when the user clicks properly we don't add another step with a confirmation dialog simplifying that interaction. but when the user clicks the wrong item, we make them click an additional time to change it back to private.

**Comment by lweitzman** [comment]
want to close this issue but put on labels so someone could verify. it seems that this is no longer an issue since making a project public is done in the configuration page.

**Comment by reasonerjt** [comment]
@lweitzman I'll close this.
