### ISSUE TITLE
can not click add replication rule in integrate mode on firefox

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#3071]
can not click add replication rule in integrate mode, button was covered
![reprule](https://user-images.githubusercontent.com/23101283/29399000-eeb4e79a-8359-11e7-9cdc-8de8d1ebf12e.PNG)

**Comment by sigsbee** [comment]
close for this is not a standalone issue

**Comment by steven-zou** [comment]
As issue is fixed in harbro-ui@0.4.46, close this issue
