### ISSUE TITLE
Before the copy, all containers are in the up state, when the replication strategy is built and started, this container, harbor-jobservice / harbor / harbor_jobservice Restarting, and the UI interface copy task bar shows running in the state, copy function can not be achieved.

### ISSUE THREAD

**Issue by jiananjiang** [vmware/harbor#3079]
[root@host-192-168 ~]# docker version

Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      88a4867/1.12.6
 Built:           Mon Jul  3 16:02:02 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      88a4867/1.12.6
 Built:           Mon Jul  3 16:02:02 2017
 OS/Arch:         linux/amd64

[root@host-192-168 ~]# docker-compose version
docker-compose version 1.9.0, build 2585387
docker-py version: 1.10.6
CPython version: 2.7.5
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013

harbor版本： 1.1.2

2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same

use default config except the parameter hostname，
3)Log files, you can get them by package the /var/log/harbor/ .

see the attached file, there is a panic in jobservice.log，the jobservice docker instance become restarting
harbor.tar.gz

[root@host-192-168 2017-08-18]# vim jobservice.log 

Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [INFO] Config path: /etc/jobservice/app.conf
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [INFO] initializing configurations...
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [INFO] key path: /etc/jobservice/key
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [INFO] initializing client for adminserver http://adminserver ...
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [INFO] configurations initialization completed
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [INFO] initializing database: type-MySQL host-mysql port-3306 user-root database-registry
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [INFO] initialize database completed
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [DEBUG] [workerpool.go:126]: worker 0 started
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [DEBUG] [workerpool.go:126]: worker 1 started
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [DEBUG] [workerpool.go:126]: worker 2 started
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [DEBUG] [main.go:52]: Trying to resume halted jobs...
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [DEBUG] [main.go:60]: Resuming job: 1
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [DEBUG] [workerpool.go:137]: Trying to dispatch job: 1
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [DEBUG] [workerpool.go:62]: worker: 1, will handle job: 1
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017/08/18 01:35:30 #033[1;34m[asm_amd64.s:2086][I] http server Running on :80#033[0m
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [DEBUG] [statemachine.go:61]: Job id: 1, transiting from State: pending, to State: running
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [DEBUG] [statemachine.go:74]: Job id: 1, no handler found for state:pending, skip
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [DEBUG] [statemachine.go:88]: Job id: 1, transition succeeded, current state: running
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [DEBUG] [statemachine.go:97]: Job id: 1, next state from handler: _continue
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [DEBUG] [statemachine.go:109]: Job id: 1, Continue to state: initialize
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [DEBUG] [statemachine.go:61]: Job id: 1, transiting from State: running, to State: initialize
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [DEBUG] [statemachine.go:88]: Job id: 1, transition succeeded, current state: initialize
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [DEBUG] [statemachine.go:118]: Job id: 1, next state from handler: check
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: 2017-08-18T01:35:30Z [DEBUG] [statemachine.go:61]: Job id: 1, transiting from State: initialize, to State: check
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 18 09:35:30 172.18.0.1 jobservice[25463]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x72955d]

**Comment by ywk253100** [comment]
Does the image you replicating contain multiple namespaces? If it is, this should be a known issue and has been fixed in 1.2.

**Comment by ywk253100** [comment]
@jiananjiang According to your reaction, your situation is the same with the last comment described. So closing the issue, feel free to reopen it if not.
