### ISSUE TITLE
harbor 1.2.0rc1 - reboot, services do not all restart

### ISSUE THREAD

**Issue by choman** [vmware/harbor#3087]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.

- rhel 7.2
- Docker version 17.06.1-ce, build 874a737
- docker-compose version 1.16.0rc1, build 9bea70a
- harbor 1.2.0rc1

2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
located at: https://gist.github.com/8f6be32e626e6e59c4a430eb98f492f3

3)Log files, you can get them by package the /var/log/harbor/ .
located at: https://gist.github.com/828d362973e1b791c0c8f8512b08fbb9

On rebooting my VM,   all harbor related services do not restart.

Before reboot
- 6df9b7e31d90        vmware/harbor-jobservice:v1.2.0-rc1    "/harbor/harbor_jo..."   35 minutes ago      Up 35 minutes                                                                          harbor-jobservice
- 3ae85b1b455f        vmware/nginx-photon:1.11.13            "nginx -g 'daemon ..."   35 minutes ago      Up 35 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:4443->4443/tcp   nginx
- 487653f039c5        vmware/harbor-ui:v1.2.0-rc1            "/harbor/harbor_ui"      35 minutes ago      Up 35 minutes                                                                          harbor-ui
- 3a4ea7f6c424        vmware/registry:2.6.2-photon           "/entrypoint.sh se..."   35 minutes ago      Up 35 minutes       5000/tcp                                                           registry
- 4093efd01eba        vmware/harbor-db:v1.2.0-rc1            "docker-entrypoint..."   35 minutes ago      Up 35 minutes       3306/tcp                                                           harbor-db
- ce404c06984d        vmware/harbor-adminserver:v1.2.0-rc1   "/harbor/harbor_ad..."   35 minutes ago      Up 35 minutes                                                                          harbor-adminserver
- 9e7368d54f4d        vmware/harbor-log:v1.2.0-rc1           "/bin/sh -c 'crond..."   35 minutes ago      Up 35 minutes       127.0.0.1:1514->514/tcp                                            harbor-log

After Reboot
- 6df9b7e31d90        vmware/harbor-jobservice:v1.2.0-rc1    "/harbor/harbor_jo..."   37 minutes ago      Up 36 seconds                                                                                      harbor-jobservice
- 3ae85b1b455f        vmware/nginx-photon:1.11.13            "nginx -g 'daemon ..."   37 minutes ago      Up 37 seconds                   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:4443->4443/tcp   nginx
- 487653f039c5        vmware/harbor-ui:v1.2.0-rc1            "/harbor/harbor_ui"      37 minutes ago      Up 36 seconds                                                                                      harbor-ui
- 3a4ea7f6c424        vmware/registry:2.6.2-photon           "/entrypoint.sh se..."   37 minutes ago      Up 37 seconds                   5000/tcp                                                           registry
- 4093efd01eba        vmware/harbor-db:v1.2.0-rc1            "docker-entrypoint..."   37 minutes ago      Up 37 seconds                   3306/tcp                                                           harbor-db
- ce404c06984d        vmware/harbor-adminserver:v1.2.0-rc1   "/harbor/harbor_ad..."   37 minutes ago      Exited (2) About a minute ago                                                                      harbor-adminserver
- 9e7368d54f4d        vmware/harbor-log:v1.2.0-rc1           "/bin/sh -c 'crond..."   37 minutes ago      Up 37 seconds                   127.0.0.1:1514->514/tcp                                            harbor-log

NOTE: This is true with the clair and/or notary installs as well

**Comment by reasonerjt** [comment]
Could you provide the log files under /var/log/harbor? if the service fails to start there should be some error messages in the latest log files.

**Comment by choman** [comment]
should be in the gist log above.  Either way  I will recapture tonight

**Comment by choman** [comment]
Log files

[adminserver.log.txt](https://github.com/vmware/harbor/files/1243667/adminserver.log.txt)
[jobservice.log.txt](https://github.com/vmware/harbor/files/1243666/jobservice.log.txt)
[mysql.log.txt](https://github.com/vmware/harbor/files/1243662/mysql.log.txt)
[proxy.log.txt](https://github.com/vmware/harbor/files/1243665/proxy.log.txt)
[registry.log.txt](https://github.com/vmware/harbor/files/1243664/registry.log.txt)
[ui.log.txt](https://github.com/vmware/harbor/files/1243663/ui.log.txt)

**Comment by choman** [comment]
upgraded docker-compose to 1.16.0rc1, no help.  updated initial bug report

**Comment by wy65701436** [comment]
it's because that docker will boot all the no-stopped container but suppose not according to the sequence defined in the docker-compose yml files at the system start up phase.

If you want to ensure Harbor works, you probably need to add some logic in the systemd to control the lifecycle.

**Comment by choman** [comment]
Not to be blunt, but shouldn't this already be baked into harbor? from https://github.com/vmware/harbor "An enterprise-class container registry server...".   From that perspective, shouldn't harbor be able to recover from and outage, manual reboot, other?

second it fails in such a bad way, not even a docker-compose down; docker-compose up -d can 
get it back  on it's feet.  In fact the only recovery I have right now is docker-compose down.  then 
rerun sudo ./install [ my options ]

**Comment by choman** [comment]
OK i've been looking at harbor 1.2.0rc2

Basic install is much better at recovering from a reboot.  All services
still do not restart.  but at least it seems I can do a docker-compose start 
and they successfully restart without errors.  Although it would be extremely 
nice if they just all restarted.

Clair and Notary services differ at restarting.  Starting to research clair first

**Comment by choman** [comment]
So I'm definitely happier with harbor 1.2.0rc2,   the docker-compose will start everything without error

But I find it ironic that the docker-compose files say always restart, yet they won't on a reboot or powerhit

**Comment by wy65701436** [comment]
There is no update on installation and deployment in v1.2.0-rc2.

Harbor doesn't provide any solution for system reboot/outage so far. But for this, you can definitely use docker-compose down/up to resolve it(If not, please open an issue). No need to perform the install.sh here as all the docker images has already loaded into local system.

**Comment by reasonerjt** [comment]
The behavior over OS restart is beyond the scope of this project, closing.
