### ISSUE TITLE
Better developer story

### ISSUE THREAD

**Issue by SEJeff** [vmware/harbor#31]
For those of us who would like to build harbor from source and deploy it manually (perhaps not using docker), it is a bit tricky.

I've been reverse engineering how the source release is different from the binary releases and think it really should be documented better.

**Comment by SEJeff** [comment]
From reverse engineering the steps from [travis.yml](https://github.com/vmware/harbor/blob/master/.travis.yml), I came up with this:

```bash
export GO15VENDOREXPERIMENT=1
export DB_HOST=127.0.0.1
export DB_PORT=3306
export DB_USR=root
export DB_PWD=

go get -d github.com/docker/distribution
go get -d github.com/docker/libtrust
go get -d github.com/go-sql-driver/mysql
go get github.com/golang/lint/golint
go get github.com/GeertJohan/fgt

mysql < ./Deploy/db/registry.sql -uroot --verbose

# Download all of the deps such as beego
go get -d .

go list ./... | grep -v /vendor/ | xargs -L1 fgt golint
go list ./... | grep -v 'vendor' | xargs -L1 go vet
go list ./... | grep -v 'vendor' | xargs -L1 go test -v
go build .
```

My point is that not everyone might want to run this under docker. I'd like to run it on a RHEL7 server under systemd. Ideally, there would be documentation in the the README or a DEVELOPING.md so another new developer won't have to reverse engineer this.

I'll be sending a small PR this evening to fix a few small things which allow harbor to work in my environment.

**Comment by reasonerjt** [comment]
@SEJeff 
Thanks for raising this, currently we'd like to use docker-compose as the only deployment approach to avoid other env issues.  
But travis.yml is for CI and for reverse engineering I'd suggest looking at Deploy/docker-compose.yml

**Comment by SEJeff** [comment]
Thanks for getting back to me @reasonerjt. Docker compose is great for testing things out, but isn't great for production. We have existing beefcake mysql and galera clusters and a large mesos cluster that this would likely run ontop of. If I wrote a developer doc and sent a PR would you accept it? Some people simply don't consider single host docker to be production worthy. To sell using harbor to my management I have to deploy it to be resilient.

**Comment by hainingzhang** [comment]
@SEJeff Got your point on the production use. We are considering the installation through other approaches, such as Swarm, Mesos and K8s. Meanwhile, you are welcome to submit a PR. If it is helpful to other developers, we will consider to merge it. One thing to note is that the form  Contributor License Agreement should be signed by you before we can merge your PR. You can find it from README. Thanks.

**Comment by hainingzhang** [comment]
We will provide more production friendly approach for installation and deployment. Closing this for now.
