### ISSUE TITLE
UI should redirect to login page when encounter 401 http code

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#3106]
Login harbor ,  and try to make the current session invalid, then click links in current page, it will return 401 in backend, but from customer's point of view they will see harbor still stay on current page and nothing happens.  Ideally UI should redirect to login page when 401 received.

**Comment by reasonerjt** [comment]
If it doesn't it should be a regression, in 0.5.0 it will redirect to login page.

**Comment by steven-zou** [comment]
@yixingjia 
  Please confirm which links you clicked.  We support some pages which guests can access.

**Comment by yixingjia** [comment]
@steven-zou  all the links on the page has not response.

I find this in the follow scenario:

1>Setup 2 harbor. 
2>On top of the Harbor use keepalived as LB
3> Login Harbor and stay on the project page.
4> Stop the harbor instance which currently is serving the request.
5> Click any links on the Harbor page, no response.

I will set up a session share server like to Redis to recheck.

**Comment by steven-zou** [comment]
Not reproduced, close it.
