### ISSUE TITLE
harbor-1.2rc1 with clair and notary: retrying on pushing the image and then error 500

### ISSUE THREAD

**Issue by c6opuc** [vmware/harbor#3108]
I have newly installed harbor 1.2rc1 configured with clair and notary. On attempt to push the image the client goes into infinite loop retrying many times to upload the layers and never succeeds. 

The push refers to a repository [harbor.CENSORED.int/test]
ad78a1150a80: Retrying in 1 second 
60bb85a67a5e: Retrying in 1 second 
4aa68501f73a: Retrying in 1 second 
06e47d9440ee: Retrying in 1 second 
6637a9d9ceed: Retrying in 1 second 
375c197a487b: Waiting 
e85bdd461f05: Retrying in 5 seconds 
83b844b09c59: Waiting 
01853f32a710: Waiting 
fec1dc306713: Waiting 
received unexpected HTTP status: 500 Internal Server Error

In the logs I could only see strange messages in the notary server:

Aug 22 21:33:54 172.18.0.1 notary-server[2602]: {"level":"error","msg":"Trust not fully operational: rpc error: code = 13 desc = connection error: desc = \"transport: x509: certificate signed by unknown authority\"","time":"2017-08-22T21:33:54Z"}
Aug 22 21:34:04 172.18.0.1 notary-server[2602]: {"level":"error","msg":"Trust not fully operational: rpc error: code = 13 desc = connection error: desc = \"transport: x509: certificate signed by unknown authority\"","time":"2017-08-22T21:34:04Z"}
Aug 22 21:34:14 172.18.0.1 notary-server[2602]: {"level":"error","msg":"Trust not fully operational: rpc error: code = 13 desc = connection error: desc = \"transport: x509: certificate signed by unknown authority\"","time":"2017-08-22T21:34:14Z"}
Aug 22 21:34:24 172.18.0.1 notary-server[2602]: {"level":"error","msg":"Trust not fully operational: rpc error: code = 13 desc = connection error: desc = \"transport: x509: certificate signed by unknown authority\"","time":"2017-08-22T21:34:24Z"}
Aug 22 21:34:34 172.18.0.1 notary-server[2602]: {"level":"error","msg":"Trust not fully operational: rpc error: code = 13 desc = connection error: desc = \"transport: x509: certificate signed by unknown authority\"","time":"2017-08-22T21:34:34Z"}
Aug 22 21:34:44 172.18.0.1 notary-server[2602]: {"level":"error","msg":"Trust not fully operational: rpc error: code = 13 desc = connection error: desc = \"transport: x509: certificate signed by unknown authority\"","time":"2017-08-22T21:34:44Z"}

I did not change the certificates that came with the installation package.

**Comment by choman** [comment]
I'm having the exact issue in #3086

**Comment by reasonerjt** [comment]
This may not be the same issue as #3086
@c6opuc please provide the log files.

**Comment by c6opuc** [comment]
@choman: it does not look the same. I suspect I am having the problem with notary, and in your setup you don't use it, right?
@reasonerjt: the logs are attached. Thanks for looking!
[harbor.logs.tar.gz](https://github.com/vmware/harbor/files/1244335/harbor.logs.tar.gz)

**Comment by choman** [comment]
@c6opuc possibly, I will be using notary.  but I took it out to simplify my issue.  Not I'm moving back to include clair and notary

**Comment by reasonerjt** [comment]
@c6opuc you need to push an image to a project, such as 
**harbor.CENSORED.int/library/test **

This is the root cause of the 500 Error from notary and docker push.

**Comment by c6opuc** [comment]
Sorry I replaced the domain name opscloud.eumetsat.into by censored.into
when describing the problem but I did push the image certainly.

24 Авг 2017 г. 5:44 пользователь "Daniel Jiang" <notifications@github.com>
написал:

**Comment by reasonerjt** [comment]
Note it's $FQDN/library/test instead of $FQDN/test

To clarify if use $FQDN/**library**/test in your `docker push` command.
The 500 error should probably gone.

**Comment by c6opuc** [comment]
Yes you are right this error is gone - I was playing too much and somehow made a tag that did not match the available repositories. However when I corrected that I got another error500.
It turns out that the permission of the harbor/common/config/nginx folder is such that underlying folders such as client_body_temp cannot be accessed by the proxy! Changing the permissions to 755 fixed the error 500 issue.

**Comment by c6opuc** [comment]
[logs.tar.gz](https://github.com/vmware/harbor/files/1248609/logs.tar.gz)
No as I can upload the image I faced another issue with not being able to scan it for vulnerabilities.

The error in the harbor UI when clicking on View log:
2017-08-24T11:02:15Z [INFO] Entered scan initializer
2017-08-24T11:02:15Z [INFO] Image: qqq/ubuntu:latest, digest: sha256:f38a16a8dc4fed60debbae12c1b47eff1e33b6dfaa9eb45ddf7546c7004cff5f
2017-08-24T11:02:15Z [INFO] Entered scan layer handler, current: 0, layer name: 3973e022e93220f9212c18d0d0c543ae7c309e46640da93a4a0314de999f5112, layer path: http://registry:5000/v2/qqq/ubuntu/blobs/
2017-08-24T11:02:15Z [ERROR] [handlers.go:110]: Unexpected error: Unexpected status code: 400, text: {"Error":{"Message":"could not find layer"}}

The error in notary-server when clicking on "Scan" in UI :

Aug 24 11:07:18 172.18.0.1 notary-server[2602]: {"go.version":"go1.7.3","harbor.opscloud.eumetsat.int/qqq/ubuntu":"gun","http.request.host":"notary-server:4443","http.request.id":"2225cd3c-b147-4244-aac8-a2984d584feb","http.request.method":"GET","http.request.remoteaddr":"172.22.0.2:46148","http.request.uri":"/v2/harbor.opscloud.eumetsat.int/qqq/ubuntu/_trust/tuf/root.json","http.request.useragent":"Go-http-client/1.1","level":"info","msg":"404 GET root role","time":"2017-08-24T11:07:18Z"}
Aug 24 11:07:18 172.18.0.1 notary-server[2602]: {"go.version":"go1.7.3","http.request.host":"notary-server:4443","http.request.id":"2225cd3c-b147-4244-aac8-a2984d584feb","http.request.method":"GET","http.request.remoteaddr":"172.22.0.2:46148","http.request.uri":"/v2/harbor.opscloud.eumetsat.int/qqq/ubuntu/_trust/tuf/root.json","http.request.useragent":"Go-http-client/1.1","level":"info","msg":"metadata not found: You have requested metadata that does not exist.: No record found","time":"2017-08-24T11:07:18Z"}
Aug 24 11:07:18 172.18.0.1 notary-server[2602]: {"go.version":"go1.7.3","http.request.host":"notary-server:4443","http.request.id":"2225cd3c-b147-4244-aac8-a2984d584feb","http.request.method":"GET","http.request.remoteaddr":"172.22.0.2:46148","http.request.uri":"/v2/harbor.opscloud.eumetsat.int/qqq/ubuntu/_trust/tuf/root.json","http.request.useragent":"Go-http-client/1.1","http.response.contenttype":"application/json; charset=utf-8","http.response.duration":"1.684709ms","http.response.status":404,"http.response.written":116,"level":"info","msg":"response completed","time":"2017-08-24T11:07:18Z"}
Aug 24 11:07:18 172.18.0.1 notary-server[2602]: {"go.version":"go1.7.3","harbor.opscloud.eumetsat.int/qqq/ubuntu":"gun","http.request.host":"notary-server:4443","http.request.id":"fd8b6759-e533-4fab-a562-efd557e999ea","http.request.method":"GET","http.request.remoteaddr":"172.22.0.2:46158","http.request.uri":"/v2/harbor.opscloud.eumetsat.int/qqq/ubuntu/_trust/tuf/root.json","http.request.useragent":"Go-http-client/1.1","level":"info","msg":"404 GET root role","time":"2017-08-24T11:07:18Z"}
Aug 24 11:07:18 172.18.0.1 notary-server[2602]: {"go.version":"go1.7.3","http.request.host":"notary-server:4443","http.request.id":"fd8b6759-e533-4fab-a562-efd557e999ea","http.request.method":"GET","http.request.remoteaddr":"172.22.0.2:46158","http.request.uri":"/v2/harbor.opscloud.eumetsat.int/qqq/ubuntu/_trust/tuf/root.json","http.request.useragent":"Go-http-client/1.1","level":"info","msg":"metadata not found: You have requested metadata that does not exist.: No record found","time":"2017-08-24T11:07:18Z"}
Aug 24 11:07:18 172.18.0.1 notary-server[2602]: {"go.version":"go1.7.3","http.request.host":"notary-server:4443","http.request.id":"fd8b6759-e533-4fab-a562-efd557e999ea","http.request.method":"GET","http.request.remoteaddr":"172.22.0.2:46158","http.request.uri":"/v2/harbor.opscloud.eumetsat.int/qqq/ubuntu/_trust/tuf/root.json","http.request.useragent":"Go-http-client/1.1","http.response.contenttype":"application/json; charset=utf-8","http.response.duration":"1.425614ms","http.response.status":404,"http.response.written":116,"level":"info","msg":"response completed","time":"2017-08-24T11:07:18Z"}
Aug 24 11:07:22 172.18.0.1 notary-server[2602]: {"level":"error","msg":"Trust not fully operational: rpc error: code = 13 desc = connection error: desc = \"transport: x509: certificate signed by unknown authority\"","time":"2017-08-24T11:07:22Z"}


I attach the new set of logs

**Comment by c6opuc** [comment]
I guess I will open another issue for the vulnerability scans.
