### ISSUE TITLE
如何挂在到本地磁盘存储镜像文件

### ISSUE THREAD

**Issue by eguotangseng** [vmware/harbor#311]
如何挂在本地文件夹，存储上传的镜像文件？

**Comment by xiaods** [comment]
distribution 本身就是挂载本地文件存镜像层的。

**Comment by clyuan2016** [comment]
如何将镜像文件存储在指定的本地文件夹？

**Comment by xiaods** [comment]
@clyuan2016 细看https://docs.docker.com/registry/configuration/

```
storage:
  filesystem:
    rootdirectory: /var/lib/registry
```

**Comment by clyuan2016** [comment]
@xiaods  是指定的本地目录，貌似需要修改docker-compose.yml中的registry下，将/storage对应的/data/registry换成指定的目录，如/root/harbor

**Comment by clyuan2016** [comment]
@xiaods  现在部署的时候又出现了一个新问题，

harbor部署时出现ERROR: Service 'log' failed to build: mkdir /var/lib/docker/overlay/f3131e83d73405493773cb8227fdde8d6d669edc20391a9088f77a0f3a889d98-init/merged/dev/shm: invalid argument 

是什么原因，请问你知道怎么解决吗？

**Comment by reasonerjt** [comment]
dup to #575

**Comment by wkjun** [comment]
这个确实需要修改docker-compose.yml中的registry,新用户调整本地存储目录的需求比较多，看文档会误以为修改：
storage:
  filesystem:
    rootdirectory: /var/lib/registry
```
其实不是，如果文档这儿可以强调下，可能会帮助很多人.今天我也遇到了，研究了好一会儿
