### ISSUE TITLE
Harbor 1.2rc1: Vulnerability scan error "could not find layer"

### ISSUE THREAD

**Issue by c6opuc** [vmware/harbor#3116]
I faced issue of not being able to scan the uploaded image for vulnerabilities.

The error in the harbor UI when clicking on View log:
2017-08-24T11:02:15Z [INFO] Entered scan initializer
2017-08-24T11:02:15Z [INFO] Image: qqq/ubuntu:latest, digest: sha256:f38a16a8dc4fed60debbae12c1b47eff1e33b6dfaa9eb45ddf7546c7004cff5f
2017-08-24T11:02:15Z [INFO] Entered scan layer handler, current: 0, layer name: 3973e022e93220f9212c18d0d0c543ae7c309e46640da93a4a0314de999f5112, layer path: http://registry:5000/v2/qqq/ubuntu/blobs/
2017-08-24T11:02:15Z [ERROR] [handlers.go:110]: Unexpected error: Unexpected status code: 400, text: {"Error":{"Message":"could not find layer"}}

The error in notary-server when clicking on "Scan" in UI :

Aug 24 11:07:18 172.18.0.1 notary-server[2602]: {"go.version":"go1.7.3","harbor.opscloud.eumetsat.int/qqq/ubuntu":"gun","http.request.host":"notary-server:4443","http.request.id":"2225cd3c-b147-4244-aac8-a2984d584feb","http.request.method":"GET","http.request.remoteaddr":"172.22.0.2:46148","http.request.uri":"/v2/harbor.opscloud.eumetsat.int/qqq/ubuntu/_trust/tuf/root.json","http.request.useragent":"Go-http-client/1.1","level":"info","msg":"404 GET root role","time":"2017-08-24T11:07:18Z"}
Aug 24 11:07:18 172.18.0.1 notary-server[2602]: {"go.version":"go1.7.3","http.request.host":"notary-server:4443","http.request.id":"2225cd3c-b147-4244-aac8-a2984d584feb","http.request.method":"GET","http.request.remoteaddr":"172.22.0.2:46148","http.request.uri":"/v2/harbor.opscloud.eumetsat.int/qqq/ubuntu/_trust/tuf/root.json","http.request.useragent":"Go-http-client/1.1","level":"info","msg":"metadata not found: You have requested metadata that does not exist.: No record found","time":"2017-08-24T11:07:18Z"}
Aug 24 11:07:18 172.18.0.1 notary-server[2602]: {"go.version":"go1.7.3","http.request.host":"notary-server:4443","http.request.id":"2225cd3c-b147-4244-aac8-a2984d584feb","http.request.method":"GET","http.request.remoteaddr":"172.22.0.2:46148","http.request.uri":"/v2/harbor.opscloud.eumetsat.int/qqq/ubuntu/_trust/tuf/root.json","http.request.useragent":"Go-http-client/1.1","http.response.contenttype":"application/json; charset=utf-8","http.response.duration":"1.684709ms","http.response.status":404,"http.response.written":116,"level":"info","msg":"response completed","time":"2017-08-24T11:07:18Z"}
Aug 24 11:07:18 172.18.0.1 notary-server[2602]: {"go.version":"go1.7.3","harbor.opscloud.eumetsat.int/qqq/ubuntu":"gun","http.request.host":"notary-server:4443","http.request.id":"fd8b6759-e533-4fab-a562-efd557e999ea","http.request.method":"GET","http.request.remoteaddr":"172.22.0.2:46158","http.request.uri":"/v2/harbor.opscloud.eumetsat.int/qqq/ubuntu/_trust/tuf/root.json","http.request.useragent":"Go-http-client/1.1","level":"info","msg":"404 GET root role","time":"2017-08-24T11:07:18Z"}
Aug 24 11:07:18 172.18.0.1 notary-server[2602]: {"go.version":"go1.7.3","http.request.host":"notary-server:4443","http.request.id":"fd8b6759-e533-4fab-a562-efd557e999ea","http.request.method":"GET","http.request.remoteaddr":"172.22.0.2:46158","http.request.uri":"/v2/harbor.opscloud.eumetsat.int/qqq/ubuntu/_trust/tuf/root.json","http.request.useragent":"Go-http-client/1.1","level":"info","msg":"metadata not found: You have requested metadata that does not exist.: No record found","time":"2017-08-24T11:07:18Z"}
Aug 24 11:07:18 172.18.0.1 notary-server[2602]: {"go.version":"go1.7.3","http.request.host":"notary-server:4443","http.request.id":"fd8b6759-e533-4fab-a562-efd557e999ea","http.request.method":"GET","http.request.remoteaddr":"172.22.0.2:46158","http.request.uri":"/v2/harbor.opscloud.eumetsat.int/qqq/ubuntu/_trust/tuf/root.json","http.request.useragent":"Go-http-client/1.1","http.response.contenttype":"application/json; charset=utf-8","http.response.duration":"1.425614ms","http.response.status":404,"http.response.written":116,"level":"info","msg":"response completed","time":"2017-08-24T11:07:18Z"}
Aug 24 11:07:22 172.18.0.1 notary-server[2602]: {"level":"error","msg":"Trust not fully operational: rpc error: code = 13 desc = connection error: desc = \"transport: x509: certificate signed by unknown authority\"","time":"2017-08-24T11:07:22Z"}

I attach the set of logs
[logs.tar.gz](https://github.com/vmware/harbor/files/1248609/logs.tar.gz)

**Comment by reasonerjt** [comment]
the layer path is incorrect, how did you build this image? @c6opuc  is this image accessible from docker hub?

**Comment by c6opuc** [comment]
@reasonerjt You are right. Indeed it is a problem with only this particular image. I don't know how this image was build I just picked one that was available on the test machine and pushed it :-) 
I tried many other images and everything works! Sorry for bothering with silly problems :-)
