### ISSUE TITLE
update timezone error

### ISSUE THREAD

**Issue by timchenxiaoyu** [vmware/harbor#3120]
version 1.1.1

![wechatimg2025](https://user-images.githubusercontent.com/9782796/29707225-20dd0122-89b7-11e7-98d0-fa51f40ee3d7.jpeg)

**Comment by ywk253100** [comment]
@timchenxiaoyu Could you describe the steps about how to reproduce this issue?

**Comment by timchenxiaoyu** [comment]
I compile and  deploy harbor from source code，nothing special，when I pull images from registry,
i see repository table update_time timezone err

**Comment by ywk253100** [comment]
@timchenxiaoyu I can not reproduce this issue in both Harbor v1.1.1 and the latest codes. Could you test it with the latest codes?

**Comment by timchenxiaoyu** [comment]
https://github.com/go-sql-driver/mysql#loc   default is utc not cst

**Comment by ywk253100** [comment]
Could you try the latest codes?

**Comment by reasonerjt** [comment]
close due to inactivity.
