### ISSUE TITLE
harbor删除仓库返回404，提示仓库不存在

### ISSUE THREAD

**Issue by liang0411** [vmware/harbor#3122]
docker版本1.12
harbor registry 版本2.6.1
调用repo查询接口能返回repo_name正常
curl -X GET --header 'Accept: application/json' 'http://registry.test.com/api/repositories?project_id=14'
[
  "search/search_2104",
  "search/search_2111",
  "search/search_2124",
  "search/search_2133",
  "search/es_search_2143",
  "search/es_search_2216",
  "search/es_search_0053",
  "search/es_search_0117",
  "search/search_1027",
  "search/search_1343",
  "search/search_1620",
  "search/search_1622",
  "search/es_suggest_1018",
  "search/search_1359"
]
调用repo删除接口返回404，提示仓库不存在
curl -X DELETE --header 'Accept: text/html' 'http://registry.test.com/api/repositories/search%2Fsearch__2104'
<html>
<head>
<meta charset="utf-8">
<title>404 - Page Not Found</title>
<style>

**Comment by reasonerjt** [comment]
There's extra underscore in the url

**Comment by reasonerjt** [comment]
Closing as it's usage error.
