### ISSUE TITLE
Fix "0 of 0 package has known vulnerability" in repository vulnerability results

### ISSUE THREAD

**Issue by pdaigle** [vmware/harbor#3126]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.

This is present in version 1.2-rc1.

This can be reproduced using any version of Docker. Simply pull the `busybox` image from Docker Hub and push it to Harbor.

Harbor displays status green and "0 of 0 package has known vulnerability".

![image](https://user-images.githubusercontent.com/8586715/29799861-8622d6b8-8c1b-11e7-83fd-239ec491991e.png)

The message should reflect what was actually scanned and what yielded the "green" result. No packages were installed but did we scan the base image? If the vulnerability status is unknown, we should not display "green" as the status.

**Comment by reasonerjt** [comment]
@pdaigle Clair will scan the installed "packages" and report vuln based on the packages' names and versions.

In the case of busybox, it didn't find any packages hence 0 vulnerable packages.
If Clair fails to recognize the OS it will report an error, if you try to scan "photon"

**Comment by reasonerjt** [comment]
@pdaigle but I think what you suggest makes sense that if there's 0 packages recognized, the result of the scan be rendered as "unknown".

**Comment by reasonerjt** [comment]
Sorry we are too close to release, and the code may need to be frozen to meet the GA date.

**Comment by mdubya66** [comment]
marking high priority and required for 1.3 per @pdaigle

**Comment by steven-zou** [comment]
It is done, let's close this issue.

**Comment by steven-zou** [comment]
PR: https://github.com/vmware/harbor/pull/3277

**Comment by steven-zou** [comment]
Reopen to change the 0 of 0 text.

Change zh translation text of key "low" = (“一般=>较低")

**Comment by ninjadq** [comment]
fixed in pr #3461
