### ISSUE TITLE
can't filter project by name using GET /projects

### ISSUE THREAD

**Issue by fffffreedom** [vmware/harbor#3138]
harbor v1.1.2
i create a project named rule, and i use swagger and cmdline to test the api, but both way are failed .

![project](https://user-images.githubusercontent.com/26200904/29863511-7ebfd30c-8da2-11e7-8e7c-c3cff948a243.JPG)

[root@localhost harbor]# curl -u admin:Harbor12345 -X GET http://192.168.56.101/api/projects?name=rule
[
  {
    "project_id": 2,
    "owner_id": 1,
    "name": "base",
    "creation_time": "2017-08-30T06:14:26Z",
    "creation_time_str": "",
    "deleted": 0,
    "owner_name": "",
    "public": 1,
    "Togglable": true,
    "update_time": "2017-08-30T06:14:26Z",
    "current_user_role_id": 1,
    "repo_count": 1
  },
  {
    "project_id": 1,
    "owner_id": 1,
    "name": "library",
    "creation_time": "2017-08-30T06:13:43Z",
    "creation_time_str": "",
    "deleted": 0,
    "owner_name": "",
    "public": 1,
    "Togglable": true,
    "update_time": "2017-08-30T06:13:43Z",
    "current_user_role_id": 1,
    "repo_count": 0
  },
  {
    "project_id": 7,
    "owner_id": 1,
    "name": "rule",
    "creation_time": "2017-08-30T08:04:47Z",
    "creation_time_str": "",
    "deleted": 0,
    "owner_name": "",
    "public": 0,
    "Togglable": true,
    "update_time": "2017-08-30T08:04:47Z",
    "current_user_role_id": 1,
    "repo_count": 0
  }

**Comment by ywk253100** [comment]
The query should be "project_name" in Harbor v1.1 .

**Comment by fffffreedom** [comment]
it works when i use project_name to query, is this only a bug for v1.1.2? which to use in v1.2? thanks @ywk253100 
[root@localhost harbor]# curl -u admin:Harbor12345 -X GET --header 'Accept: application/json' 'http://192.168.56.101/api/projects?**project_name**=rule'
[
  {
    "project_id": 7,
    "owner_id": 1,
    "name": "rule",
    "creation_time": "2017-08-30T08:04:47Z",
    "creation_time_str": "",
    "deleted": 0,
    "owner_name": "",
    "public": 0,
    "Togglable": true,
    "update_time": "2017-08-30T08:04:47Z",
    "current_user_role_id": 1,
    "repo_count": 0
  }

**Comment by reasonerjt** [comment]
@fffffreedom why you think it's a bug?

**Comment by ywk253100** [comment]
Closing the issue, feel free to reopen it.

**Comment by fffffreedom** [comment]
yes @reasonerjt
