### ISSUE TITLE
harbor创建项目和注册登录时间utc时间获取错误

### ISSUE THREAD

**Issue by bainanan** [vmware/harbor#3147]
我centos7上跑的harbor1.1.2 ,harbor创建项目和注册登录时间utc时间获取错误
查看mysql时间是正确的
发现容器的时间都是utc  就在compose里增加了一些配置，使容器的系统时间正确为asia/shanghai时间 ，但是，我惊喜的发现问题并没有解决， 创建项目和注册登录时间还是utc时间

数据库里的 creation_time | update_time  依然是UTC时间 2017-09-01 04:00:05
 
/api/projects?project_name=&is_public=0&page=1&page_size=15  获取到的时间是 
creation_time	"2017-09-01T04:00:05+08:00"
update_time	"2017-09-01T04:00:05+08:00"

页面上显示的时间是 2017/9/1 上午4:33 

啊啊啊啊啊啊啊啊 ，求怎么破？

**Comment by bainanan** [comment]
升级版本到最新后项目创建时间就正常了 ，系统时间依然是UTC  ，是不是可以说明 harbor代码本身set到数据库的时间和不是系统本身的当前时间？ 在哪里控制修改？

**Comment by reasonerjt** [comment]
注册登录时间utc时间获取错误

Do you mean incorrect on UI? which component?

**Comment by bainanan** [comment]
是的，Projects 的 creation time 是UTC时间 并不是容器的系统时间

**Comment by reasonerjt** [comment]
on UI?  I believe it should be adjusted according to the browser's locale.

**Comment by steven-zou** [comment]
@bainanan 

在V1.1.2的版本中， 没有重现出这个问题，怀疑还是system得某些设置有出入。

---------
```
[{
    "project_id": 2,
    "owner_id": 1,
    "name": "pro1",
    "creation_time": "2017-09-08T06:13:58Z",
    "creation_time_str": "",
    "deleted": 0,
    "owner_name": "",
    "public": 0,
    "Togglable": true,
    "update_time": "2017-09-08T06:13:58Z",
    "current_user_role_id": 1,
    "repo_count": 0
  },
  {
    "project_id": 3,
    "owner_id": 1,
    "name": "pro2",
    "creation_time": "2017-09-08T06:14:26Z",
    "creation_time_str": "",
    "deleted": 0,
    "owner_name": "",
    "public": 0,
    "Togglable": true,
    "update_time": "2017-09-08T06:14:26Z",
    "current_user_role_id": 1,
    "repo_count": 0
  },
  {
    "project_id": 4,
    "owner_id": 1,
    "name": "pro3",
    "creation_time": "2017-09-08T06:15:04Z",
    "creation_time_str": "",
    "deleted": 0,
    "owner_name": "",
    "public": 0,
    "Togglable": true,
    "update_time": "2017-09-08T06:15:04Z",
    "current_user_role_id": 1,
    "repo_count": 0
  }
]

```
<img width="1124" alt="screen shot 2017-09-08 at 14 19 12" src="https://user-images.githubusercontent.com/5753287/30198522-bd5da972-94a0-11e7-9a85-f396e9721bc6.png">

**Comment by fffffreedom** [comment]
firefox will not show the local time. @steven-zou @reasonerjt

**Comment by reasonerjt** [comment]
close due to inactivity.
