### ISSUE TITLE
harbor (master-slave) Delete sync problem

### ISSUE THREAD

**Issue by yangzhiwen** [vmware/harbor#3150]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
```
harbor.v1.1.0
root@localhost:~/harbor# docker-compose --version
docker-compose version 1.7.1, build 0a9ab35
```
2)master-harbor-sync logs
2017-09-04T06:16:43Z [INFO] initialization completed: repository: test-harbor/test-harbor, tags: [test-0022], destination URL: http://38.83.109.203, insecure: false, destination user: admin
2017-09-04T06:16:43Z [WARNING] repository test-harbor/test-harbor does not exist on http://xxx.xxx.10.203

.
3)Log files
adminserver.log
Sep  4 14:22:27 172.18.0.1 adminserver[9174]: 172.18.0.6 - - [04/Sep/2017:06:22:27 +0000] "GET /api/systeminfo/capacity HTTP/1.1" 200 40
Sep  4 14:24:47 172.18.0.1 adminserver[9174]: 172.18.0.6 - - [04/Sep/2017:06:24:47 +0000] "GET /api/configurations HTTP/1.1" 200 902
Sep  4 14:24:50 172.18.0.1 adminserver[9174]: 172.18.0.7 - - [04/Sep/2017:06:24:50 +0000] "GET /api/configurations HTTP/1.1" 200 902
Sep  4 14:25:11 172.18.0.1 adminserver[9174]: 172.18.0.6 - - [04/Sep/2017:06:25:11 +0000] "GET /api/configurations HTTP/1.1" 200 902
Sep  4 14:26:48 172.18.0.1 adminserver[9174]: 172.18.0.6 - - [04/Sep/2017:06:26:48 +0000] "GET /api/systeminfo/capacity HTTP/1.1" 200 40
Sep  4 14:28:14 172.18.0.1 adminserver[9174]: 172.18.0.6 - - [04/Sep/2017:06:28:14 +0000] "GET /api/configurations HTTP/1.1" 200 902
Sep  4 14:28:14 172.18.0.1 adminserver[9174]: 172.18.0.6 - - [04/Sep/2017:06:28:14 +0000] "GET /api/systeminfo/capacity HTTP/1.1" 200 40
Sep  4 14:28:28 172.18.0.1 adminserver[9174]: 172.18.0.6 - - [04/Sep/2017:06:28:28 +0000] "GET /api/configurations HTTP/1.1" 200 902
Sep  4 14:38:07 172.18.0.1 adminserver[9174]: 172.18.0.6 - - [04/Sep/2017:06:38:07 +0000] "GET /api/configurations HTTP/1.1" 200 902
Sep  4 14:38:14 172.18.0.1 adminserver[9174]: 172.18.0.6 - - [04/Sep/2017:06:38:14 +0000] "GET /api/configurations HTTP/1.1" 200 902

anacron.log
Sep  4 03:01:01 9656f17c9640 anacron[8703]: Will run job `cron.daily' in 37 min.
Sep  4 03:01:01 9656f17c9640 anacron[8703]: Jobs will be executed sequentially
Sep  4 03:38:01 9656f17c9640 anacron[8703]: Job `cron.daily' started
Sep  4 03:38:01 9656f17c9640 anacron[8703]: Job `cron.daily' terminated
Sep  4 03:38:01 9656f17c9640 anacron[8703]: Normal exit (1 job run)
Sep  4 06:01:01 2aef2b43c1da anacron[28]: Anacron started on 2017-09-04
Sep  4 06:01:01 2aef2b43c1da anacron[28]: Will run job `cron.daily' in 49 min.
Sep  4 06:01:01 2aef2b43c1da anacron[28]: Will run job `cron.weekly' in 69 min.
Sep  4 06:01:01 2aef2b43c1da anacron[28]: Will run job `cron.monthly' in 89 min.
Sep  4 06:01:01 2aef2b43c1da anacron[28]: Jobs will be executed sequentially

CROND.log
==> CROND.log <==
Sep  4 01:01:01 9656f17c9640 CROND[8670]: (root) CMDOUT ()
Sep  4 02:01:01 9656f17c9640 CROND[8683]: (root) CMD (run-parts /etc/cron.hourly)
Sep  4 02:01:01 9656f17c9640 CROND[8682]: (root) CMDOUT (/etc/cron.hourly/0anacron:)
Sep  4 02:01:01 9656f17c9640 CROND[8682]: (root) CMDOUT ()
Sep  4 03:01:01 9656f17c9640 CROND[8695]: (root) CMD (run-parts /etc/cron.hourly)
Sep  4 03:01:01 9656f17c9640 CROND[8694]: (root) CMDOUT (/etc/cron.hourly/0anacron:)
Sep  4 03:01:01 9656f17c9640 CROND[8694]: (root) CMDOUT ()
Sep  4 06:01:01 2aef2b43c1da CROND[20]: (root) CMD (run-parts /etc/cron.hourly)
Sep  4 06:01:01 2aef2b43c1da CROND[19]: (root) CMDOUT (/etc/cron.hourly/0anacron:)
Sep  4 06:01:01 2aef2b43c1da CROND[19]: (root) CMDOUT ()
tail: cannot open 'tail' for reading: No such file or directory

==> CROND.log <==
Sep  4 01:01:01 9656f17c9640 CROND[8670]: (root) CMDOUT ()
Sep  4 02:01:01 9656f17c9640 CROND[8683]: (root) CMD (run-parts /etc/cron.hourly)
Sep  4 02:01:01 9656f17c9640 CROND[8682]: (root) CMDOUT (/etc/cron.hourly/0anacron:)
Sep  4 02:01:01 9656f17c9640 CROND[8682]: (root) CMDOUT ()
Sep  4 03:01:01 9656f17c9640 CROND[8695]: (root) CMD (run-parts /etc/cron.hourly)
Sep  4 03:01:01 9656f17c9640 CROND[8694]: (root) CMDOUT (/etc/cron.hourly/0anacron:)
Sep  4 03:01:01 9656f17c9640 CROND[8694]: (root) CMDOUT ()
Sep  4 06:01:01 2aef2b43c1da CROND[20]: (root) CMD (run-parts /etc/cron.hourly)
Sep  4 06:01:01 2aef2b43c1da CROND[19]: (root) CMDOUT (/etc/cron.hourly/0anacron:)
Sep  4 06:01:01 2aef2b43c1da CROND[19]: (root) CMDOUT ()

mysql.log
Sep  4 14:10:30 172.18.0.1 mysql[9174]: 2017-09-04 06:10:30 1 [Note] InnoDB: Waiting for purge to start
Sep  4 14:10:30 172.18.0.1 mysql[9174]: 2017-09-04 06:10:30 1 [Note] InnoDB: 5.6.35 started; log sequence number 2303094
Sep  4 14:10:30 172.18.0.1 mysql[9174]: 2017-09-04 06:10:30 1 [Note] Server hostname (bind-address): '*'; port: 3306
Sep  4 14:10:30 172.18.0.1 mysql[9174]: 2017-09-04 06:10:30 1 [Note] IPv6 is available.
Sep  4 14:10:30 172.18.0.1 mysql[9174]: 2017-09-04 06:10:30 1 [Note]   - '::' resolves to '::';
Sep  4 14:10:30 172.18.0.1 mysql[9174]: 2017-09-04 06:10:30 1 [Note] Server socket created on IP: '::'.
Sep  4 14:10:30 172.18.0.1 mysql[9174]: 2017-09-04 06:10:30 1 [Warning] 'proxies_priv' entry '@ root@6e6fe2398466' ignored in --skip-name-resolve mode.
Sep  4 14:10:30 172.18.0.1 mysql[9174]: 2017-09-04 06:10:30 1 [Note] Event Scheduler: Loaded 0 events
Sep  4 14:10:30 172.18.0.1 mysql[9174]: 2017-09-04 06:10:30 1 [Note] mysqld: ready for connections.
Sep  4 14:10:30 172.18.0.1 mysql[9174]: Version: '5.6.35'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)

proxy.log

Sep  4 14:28:28 172.18.0.1 proxy[9174]: 101.251.252.252 - "GET /api/repositories?project_id=7&q=&detail=1&page=1&page_size=15 HTTP/1.1" 200 189 "http://xx.xx.109.202/harbor/projects/7/repository" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" 0.034 0.034 .
Sep  4 14:28:29 172.18.0.1 proxy[9174]: 101.251.252.252 - "GET /api/projects/7 HTTP/1.1" 200 193 "http://xx.xx.109.202/harbor/projects/7/repository" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" 0.002 0.002 .
Sep  4 14:28:30 172.18.0.1 proxy[9174]: 101.251.252.252 - "GET /api/repositories/test-harbor/test-harbor/tags?detail=1 HTTP/1.1" 200 5384 "http://xx.xx.109.202/harbor/tags/7/test-harbor%2Ftest-harbor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" 0.040 0.040 .
Sep  4 14:38:06 172.18.0.1 proxy[9174]: 101.251.252.252 - "GET /api/projects/7/members HTTP/1.1" 200 193 "http://xx.xx.109.202/harbor/tags/7/test-harbor%2Ftest-harbor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" 0.004 0.004 .
Sep  4 14:38:06 172.18.0.1 proxy[9174]: 101.251.252.252 - "GET /api/projects/7 HTTP/1.1" 200 193 "http://xx.xx.109.202/harbor/tags/7/test-harbor%2Ftest-harbor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" 0.002 0.002 .
Sep  4 14:38:07 172.18.0.1 proxy[9174]: 101.251.252.252 - "GET /api/repositories?project_id=7&q=&detail=1&page=1&page_size=15 HTTP/1.1" 200 189 "http://xx.xx.109.202/harbor/projects/7/repository" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" 0.039 0.039 .
Sep  4 14:38:08 172.18.0.1 proxy[9174]: 101.251.252.252 - "POST /api/projects/7/logs/filter?page=1&page_size=15 HTTP/1.1" 200 307 "http://xx.xx.109.202/harbor/projects/7/log" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" 0.004 0.004 .
Sep  4 14:38:14 172.18.0.1 proxy[9174]: 101.251.252.252 - "GET /api/repositories?project_id=7&q=&detail=1&page=1&page_size=15 HTTP/1.1" 200 189 "http://xx.xx.109.202/harbor/projects/7/repository" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" 0.035 0.035 .
Sep  4 14:38:16 172.18.0.1 proxy[9174]: 101.251.252.252 - "GET /api/projects/7 HTTP/1.1" 200 193 "http://xx.xx.109.202/harbor/projects/7/repository" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" 0.002 0.002 .
Sep  4 14:38:16 172.18.0.1 proxy[9174]: 101.251.252.252 - "GET /api/repositories/test-harbor/test-harbor/tags?detail=1 HTTP/1.1" 200 5384 "http://xx.xx.109.202/harbor/tags/7/test-harbor%2Ftest-harbor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" 0.046 0.046 .

registry.log

Sep  4 14:38:16 172.18.0.1 registry[9174]: time="2017-09-04T06:38:16.861406194Z" level=debug msg=GetImageManifest auth.user.name=admin go.version=go1.7.3 http.request.host="registry:5000" http.request.id=af33246d-cf83-439e-b90a-32628efda511 http.request.method=GET http.request.remoteaddr="172.18.0.6:58110" http.request.uri="/v2/test-harbor/test-harbor/manifests/test-0022" http.request.useragent="Go-http-client/1.1" instance.id=ec163cba-897d-4da9-815f-f5e7d29259c7 service=registry vars.name="test-harbor/test-harbor" vars.reference=test-0022 version="v2.4.1+unknown" 
Sep  4 14:38:16 172.18.0.1 registry[9174]: time="2017-09-04T06:38:16.861559092Z" level=debug msg="filesystem.GetContent(\"/docker/registry/v2/repositories/test-harbor/test-harbor/_manifests/tags/test-0022/current/link\")" auth.user.name=admin go.version=go1.7.3 http.request.host="registry:5000" http.request.id=af33246d-cf83-439e-b90a-32628efda511 http.request.method=GET http.request.remoteaddr="172.18.0.6:58110" http.request.uri="/v2/test-harbor/test-harbor/manifests/test-0022" http.request.useragent="Go-http-client/1.1" instance.id=ec163cba-897d-4da9-815f-f5e7d29259c7 service=registry trace.duration=67.62µs trace.file="/root/gows/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent" trace.id=8b13814d-68e9-4e91-88f3-e965b8cac59c trace.line=82 vars.name="test-harbor/test-harbor" vars.reference=test-0022 version="v2.4.1+unknown" 
Sep  4 14:38:16 172.18.0.1 registry[9174]: time="2017-09-04T06:38:16.86163573Z" level=debug msg="(*manifestStore).Get" auth.user.name=admin go.version=go1.7.3 http.request.host="registry:5000" http.request.id=af33246d-cf83-439e-b90a-32628efda511 http.request.method=GET http.request.remoteaddr="172.18.0.6:58110" http.request.uri="/v2/test-harbor/test-harbor/manifests/test-0022" http.request.useragent="Go-http-client/1.1" instance.id=ec163cba-897d-4da9-815f-f5e7d29259c7 service=registry vars.name="test-harbor/test-harbor" vars.reference=test-0022 version="v2.4.1+unknown" 
Sep  4 14:38:16 172.18.0.1 registry[9174]: time="2017-09-04T06:38:16.861841301Z" level=debug msg="filesystem.GetContent(\"/docker/registry/v2/repositories/test-harbor/test-harbor/_manifests/revisions/sha256/a568c1fb93ed8a1b818024395b0079aedde72e532ef52d305817975f52364786/link\")" auth.user.name=admin go.version=go1.7.3 http.request.host="registry:5000" http.request.id=af33246d-cf83-439e-b90a-32628efda511 http.request.method=GET http.request.remoteaddr="172.18.0.6:58110" http.request.uri="/v2/test-harbor/test-harbor/manifests/test-0022" http.request.useragent="Go-http-client/1.1" instance.id=ec163cba-897d-4da9-815f-f5e7d29259c7 service=registry trace.duration=83.598µs trace.file="/root/gows/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent" trace.id=1c1df76f-38ac-4ef7-a7ea-3557bc28d581 trace.line=82 vars.name="test-harbor/test-harbor" vars.reference=test-0022 version="v2.4.1+unknown" 
Sep  4 14:38:16 172.18.0.1 registry[9174]: time="2017-09-04T06:38:16.862076231Z" level=debug msg="filesystem.GetContent(\"/docker/registry/v2/blobs/sha256/a5/a568c1fb93ed8a1b818024395b0079aedde72e532ef52d305817975f52364786/data\")" auth.user.name=admin go.version=go1.7.3 http.request.host="registry:5000" http.request.id=af33246d-cf83-439e-b90a-32628efda511 http.request.method=GET http.request.remoteaddr="172.18.0.6:58110" http.request.uri="/v2/test-harbor/test-harbor/manifests/test-0022" http.request.useragent="Go-http-client/1.1" instance.id=ec163cba-897d-4da9-815f-f5e7d29259c7 service=registry trace.duration=93.483µs trace.file="/root/gows/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent" trace.id=6ee84d78-73b5-4ab5-a116-ab47c7a9a41e trace.line=82 vars.name="test-harbor/test-harbor" vars.reference=test-0022 version="v2.4.1+unknown" 
Sep  4 14:38:16 172.18.0.1 registry[9174]: time="2017-09-04T06:38:16.862213033Z" level=debug msg="(*schema2ManifestHandler).Unmarshal" auth.user.name=admin go.version=go1.7.3 http.request.host="registry:5000" http.request.id=af33246d-cf83-439e-b90a-32628efda511 http.request.method=GET http.request.remoteaddr="172.18.0.6:58110" http.request.uri="/v2/test-harbor/test-harbor/manifests/test-0022" http.request.useragent="Go-http-client/1.1" instance.id=ec163cba-897d-4da9-815f-f5e7d29259c7 service=registry vars.name="test-harbor/test-harbor" vars.reference=test-0022 version="v2.4.1+unknown" 
Sep  4 14:38:16 172.18.0.1 registry[9174]: time="2017-09-04T06:38:16.862803191Z" level=info msg="rewriting manifest sha256:a568c1fb93ed8a1b818024395b0079aedde72e532ef52d305817975f52364786 in schema1 format to support old client" auth.user.name=admin go.version=go1.7.3 http.request.host="registry:5000" http.request.id=af33246d-cf83-439e-b90a-32628efda511 http.request.method=GET http.request.remoteaddr="172.18.0.6:58110" http.request.uri="/v2/test-harbor/test-harbor/manifests/test-0022" http.request.useragent="Go-http-client/1.1" instance.id=ec163cba-897d-4da9-815f-f5e7d29259c7 service=registry vars.name="test-harbor/test-harbor" vars.reference=test-0022 version="v2.4.1+unknown" 
Sep  4 14:38:16 172.18.0.1 registry[9174]: time="2017-09-04T06:38:16.862963903Z" level=debug msg="filesystem.GetContent(\"/docker/registry/v2/blobs/sha256/4a/4a93812cf3c40474ff9c35a8d07056506842f83dc41d6f4894076beb3438ed82/data\")" auth.user.name=admin go.version=go1.7.3 http.request.host="registry:5000" http.request.id=af33246d-cf83-439e-b90a-32628efda511 http.request.method=GET http.request.remoteaddr="172.18.0.6:58110" http.request.uri="/v2/test-harbor/test-harbor/manifests/test-0022" http.request.useragent="Go-http-client/1.1" instance.id=ec163cba-897d-4da9-815f-f5e7d29259c7 service=registry trace.duration=66.076µs trace.file="/root/gows/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent" trace.id=d5e0b58a-724f-4aad-baa3-a58119cd1068 trace.line=82 vars.name="test-harbor/test-harbor" vars.reference=test-0022 version="v2.4.1+unknown" 
Sep  4 14:38:16 172.18.0.1 registry[9174]: time="2017-09-04T06:38:16.867730662Z" level=info msg="response completed" go.version=go1.7.3 http.request.host="registry:5000" http.request.id=af33246d-cf83-439e-b90a-32628efda511 http.request.method=GET http.request.remoteaddr="172.18.0.6:58110" http.request.uri="/v2/test-harbor/test-harbor/manifests/test-0022" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/vnd.docker.distribution.manifest.v1+prettyjws" http.response.duration=8.203576ms http.response.status=200 http.response.written=17701 instance.id=ec163cba-897d-4da9-815f-f5e7d29259c7 service=registry version="v2.4.1+unknown" 
Sep  4 14:38:16 172.18.0.1 registry[9174]: 172.18.0.6 - - [04/Sep/2017:06:38:16 +0000] "GET /v2/test-harbor/test-harbor/manifests/test-0022 HTTP/1.1" 200 17701 "" "Go-http-client/1.1"

run-parts.log
Sep  4 00:01:01 9656f17c9640 run-parts[8659]: (/etc/cron.hourly) starting 0anacron
Sep  4 00:01:01 9656f17c9640 run-parts[8659][8669]: (/etc/cron.hourly) finished 0anacron
Sep  4 01:01:01 9656f17c9640 run-parts[8671]: (/etc/cron.hourly) starting 0anacron
Sep  4 01:01:01 9656f17c9640 run-parts[8671][8681]: (/etc/cron.hourly) finished 0anacron
Sep  4 02:01:01 9656f17c9640 run-parts[8683]: (/etc/cron.hourly) starting 0anacron
Sep  4 02:01:01 9656f17c9640 run-parts[8683][8693]: (/etc/cron.hourly) finished 0anacron
Sep  4 03:01:01 9656f17c9640 run-parts[8695]: (/etc/cron.hourly) starting 0anacron
Sep  4 03:01:01 9656f17c9640 run-parts[8695][8705]: (/etc/cron.hourly) finished 0anacron
Sep  4 06:01:01 2aef2b43c1da run-parts[20]: (/etc/cron.hourly) starting 0anacron

ui.log

Sep  4 14:38:16 172.18.0.1 ui[9174]: 2017-09-04T06:38:16Z [DEBUG] [transport.go:50]: 200 | GET http://registry:5000/v2/test-harbor/test-harbor/manifests/test-0022
Sep  4 14:38:16 172.18.0.1 ui[9174]: 2017/09/04 06:38:16 #033[1;34m[router.go:829][D] | GET        | /api/repositories/test-harbor/test-harbor/tags | 44.834925ms      | match      | /api/repositories/*/tags                 | #033[0m
Sep  4 14:38:16 172.18.0.1 ui[9174]: 2017-09-04T06:38:16Z [DEBUG] [notification.go:102]: receive an event: 
Sep  4 14:38:16 172.18.0.1 ui[9174]: ----ID: aad17aa3-5d27-4f81-a5b7-4254aa0bee79 
Sep  4 14:38:16 172.18.0.1 ui[9174]: ----target: test-harbor/test-harbor: 
Sep  4 14:38:16 172.18.0.1 ui[9174]: ----digest: sha256:4a93812cf3c40474ff9c35a8d07056506842f83dc41d6f4894076beb3438ed82 
Sep  4 14:38:16 172.18.0.1 ui[9174]: ----action: pull 
Sep  4 14:38:16 172.18.0.1 ui[9174]: ----mediatype: application/octet-stream 
Sep  4 14:38:16 172.18.0.1 ui[9174]: ----user-agent: Go-http-client/1.1
Sep  4 14:38:16 172.18.0.1 ui[9174]: 2017/09/04 06:38:16 #033[1;34m[router.go:829][D] | POST       | /service/notifications                   | 241.436µs        | match      | /service/notifications                   | #033[0m

**Comment by yangzhiwen** [comment]
2017-09-04T06:16:43Z [INFO] initialization completed: repository: test-harbor/test-harbor, tags: [test-0022], destination URL: http://xx.xxx.109.203, insecure: false, destination user: admin
2017-09-04T06:16:43Z [WARNING] repository test-harbor/test-harbor does not exist on http://xx.xxx.109.203

**Comment by ywk253100** [comment]
Please provide the logs of the remote Harbor. Packaging all logs and uploading it is better for debugging.

**Comment by ywk253100** [comment]
It's a known issue in v1.1.0, please update your Harbor.
