### ISSUE TITLE
After login, push image has been clearly signed, or show the cross, is the certificate problem

### ISSUE THREAD

**Issue by jiananjiang** [vmware/harbor#3153]
I am a self-signed certificate，According to https://github.com/vmware/harbor/blob/master/docs/configure_https.md ，operation, with the ip address is not the domain name

docker push 222.85.96.104/myregistry/docker.io/hello-world:0.1
The push refers to a repository [222.85.96.104/myregistry/docker.io/hello-world]
45761469c965: Pushed 
0.1: digest: sha256:f3b3b28a45160805bb16542c9531888519430e9e6d6ffc09d72261b0d26ff74f size: 524
Signing and pushing trust metadata
x509: certificate signed by unknown authority

**Comment by ywk253100** [comment]
Please follow the guide https://github.com/vmware/harbor/blob/master/docs/use_notary.md.

**Comment by jiananjiang** [comment]
Or not, I copy the ca.crt to /etc/docker/certs.d/222.85.96.104/ Lane, I was centos7, no ~ / .docker / tls file, I copied the ca.crt to / usr / lib64 / tls,

when the push, still can be displayed in the UI, but still cross. The command line shows Signing and pushing trust metadata
x509: certificate signed by unknown authority

**Comment by ywk253100** [comment]
Create it by yourself if the directory doesn't exist.
