### ISSUE TITLE
Images and replication endpoints/rules not appearing in UI after upgrade from 1.1.1 to 1.2

### ISSUE THREAD

**Issue by stuclem** [vmware/harbor#3163]
Per https://github.com/vmware/admiral/issues/193, images are not appearing in the unified VIC UI after upgrading from 1.1.1 to 1.2. @reasonerjt suggests that this is not related to the change of IP address, as I suspected in https://github.com/vmware/admiral/issues/193. I tested upgrade again by setting the same IP address on the 1.2 appliance, and images still did not show up.

**Comment by reasonerjt** [comment]
The root cause is that the project ID will be changed after migrating to Admiral, and Harbor does not reflect the change in its own DB for old data.

**Comment by stuclem** [comment]
Replication endpoints and rules also do not show up after the upgrade. I assumed that this was to be expected, but @reasonerjt tells me that they should migrate.

**Comment by wy65701436** [comment]
Passed on latest OVA RC3 build, close it.
