### ISSUE TITLE
【web UI】当项目数很多后，点击项目标签，一直转圈圈无法显示项目列表

### ISSUE THREAD

**Issue by dangzhiqiang** [vmware/harbor#3166]
**1、版本信息：**
docker版本
docker-engine-17.05.0.ce-1.el7.centos.x86_64
docker-compose-1.9.0-5.el7.noarch
harbor版本
harbor-offline-installer-v1.2.0-rc4.tgz

**2、问题描述**
迁移harbor到v1.2.0版本后，点击web UI界面中的 “项目” 按钮，显示项目列表非常缓慢，大多数情况下无法展示。当项目量较少时没这个问题（<30）。
当单击过滤项目等内容后，立马显示项目列表。通过浏览器调试发现，项目数据其实已经正常获取到，只是未展示出来，项目列表上方一直转圈圈。

**Comment by steven-zou** [comment]
@dangzhiqiang 
  
  View的responsive刷新可能出现滞后，导致数据拿到后页面依然不能刷新。这个问题，我们会check一下root cause，找到合适的方案来改进。

**Comment by dangzhiqiang** [comment]
@steven-zou 谢谢，建议尽快定位处理，已经影响使用。我们之前线上用的是v1.1.2版本没这个问题，后面迁移到v1.2.0-rc2和v1.2.0-rc4后，发现有这个问题，导致很尴尬。
**问题补充说明如下：**
在项目里，单击“公开项目”、“私有项目”都可以较快展示，单击“所有项目”就可能会出现一直转圈圈问题，项目多时，基本上必现。

**Comment by steven-zou** [comment]
@dangzhiqiang 
1.1 与1.2采用了不同的compilec&build方法，有可能是不同的方法导致编译出来的代码有差异。这个问题我们会尽快解决。

**Comment by steven-zou** [comment]
@pengpengshui 

  Please help to check and fix this problem, thanks.

**Comment by reasonerjt** [comment]
Confirm with @steven-zou this has no impact to .ova build, let's see if we can fix it before 1.2.0

**Comment by dangzhiqiang** [comment]
@steven-zou 非常谢谢！期待新版本。

**Comment by dangzhiqiang** [comment]
已升级到v1.2.0版本，经测试该问题依旧存在，需等待几秒钟后点击“过滤项目”等才能显示项目列表，如果从其他地方切换过来（比如点击完“日志”立马点击“项目”，然后紧接着点击“过滤项目”）立即点击也不能显示项目列表，需等待几秒钟后再次点击有效。

**Comment by steven-zou** [comment]
@dangzhiqiang 此issue会在后续的1.2.x版本中fix，请继续关注。

**Comment by dangzhiqiang** [comment]
@steven-zou 好的，谢谢！如有新版本，我会尽快迁移测试。

**Comment by dangzhiqiang** [comment]
更新一下该问题的最新现象（在v1.2.0版本），之前说在项目里单击“公开项目”还能显示项目列表，目前公开项目增加到46个，点击之后也开始一直一直转圈圈，无法直接显示项目列表，可以推测，当私有项目数量增多到一定量时，应该也有这个问题。

**Comment by dangzhiqiang** [comment]
@steven-zou 请问一下，该问题目前进展怎么样了？有没有什么临时的解决方案，可以直接用到v1.2.0版本上的？谢谢。

**Comment by steven-zou** [comment]
@dangzhiqiang 

Fix code is ready and trying to merge code back to master.

Seems no good workaround solution. Maybe rebuild the ui image with the fix code or compile the ui code and replace it in the ui container.

**Comment by steven-zou** [comment]
Code already merged to master, close this issue.

**Comment by dangzhiqiang** [comment]
@steven-zou Thanks. What time released a new version? I want to test it.

**Comment by dangzhiqiang** [comment]
v1.2.2 test is ok.
