### ISSUE TITLE
Create standalone .ova for Harbor

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#3175]
1. Streamline the offline installer to an .ova. **-p0**
2. Bootstrap Harbor when the .ova is deployed, need to support properly handling migration/upgrade cases in future.  **-p0**
3. Integration to CI and running E2E Automation test **p0**

**Comment by reasonerjt** [comment]
Please make sure the .ova is covered in automation test, and be part of the CI.

**Comment by reasonerjt** [comment]
Current completion rate: 25%
E2E .ova deployment works, need refinement on parameters.
CI is not started yet.

**Comment by wy65701436** [comment]
Close this issue : https://github.com/vmware/harbor/issues/3259, all the codes have already pushed  to the internal git issue.
