### ISSUE TITLE
After an image scan is successful (green) clicking on the tag link shows: no scanning results

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/harbor#3178]
@lcastellano commented on [Fri Sep 08 2017](https://github.com/vmware/admiral/issues/199)

![screen shot 2017-09-08 at 2 36 03 pm](https://user-images.githubusercontent.com/7454168/30232182-5d9b1d0a-94a3-11e7-9946-a6c2cde2a406.png)

---

@lcastellano commented on [Fri Sep 08 2017](https://github.com/vmware/admiral/issues/199#issuecomment-328220270)

This is on VIC 1.2 RC3 and vCenter 6.0

**Comment by reasonerjt** [comment]
If it's busybox, this is expected result because Clair didn't discover any installed packages, and hence, no vulnerabilities.

Here is some concern over this design, #3126  was raised.

**Comment by steven-zou** [comment]
If result is 0-packages, disable the tag detail link.

**Comment by steven-zou** [comment]
As it is done, close this issue.
