### ISSUE TITLE
BOSH release for Harbor.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#3184]
For PKS and PCF integration, we'll need a BOSH release for Harbor:
https://bosh.io/docs/release.html

1) Investigation 
2) Harbor architecture review
3) Harbor BOSH deployment structure design (jobs,packages, templates, releases, cloud configs etc)
4) DEV
5) Deployment manifest for PKS 1.0
6) BOSH deploy to verify

This will fall out of the scope of PKS 1.0.

**Comment by steven-zou** [comment]
All issues are done! Close it

**Comment by DRuggeri** [comment]
This is cool news... but where do folks find it?
It doesn't appear to be on http://bosh.io/releases, no mention in README.md, no apparent manifests or BOSH-related yml files in master...

**Comment by jessehu** [comment]
Hi @DRuggeri , currently we released the Harbor bosh release in the Harbor Tile https://network.pivotal.io/products/harbor-container-registry, you can use Harbor Tile or extract the Harbor bosh release from the tile. We will figure out a way to deliver Harbor bosh release separately.
