### ISSUE TITLE
Improve CI E2E test.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#3186]
We need to make continuous effort in improving the CI.

Some thoughts:
1)Automate building all docker images - **p0**
2)Better coverage.
3)Improvement in underlying library for robot.
4)Introduce API test.

We need discussion to finalize the scope.

**Comment by wy65701436** [comment]
1) automate build Clair and Notary(Signer and Server).  -- 1.5w
2) improve coverage of CI. -- 2w
3) improve library of robot. -- 1w
4) API test. -- 4w.

**Comment by wy65701436** [comment]
https://github.com/vmware/harbor/issues/3109

**Comment by mdubya66** [comment]
adding @mhagen-vmware for tracking purposes

**Comment by wy65701436** [comment]
1, Done for scripts to build Notary images.
2. Started to add more cases to Clair and LDAP.
3, 4 Pending Now.

**Comment by wy65701436** [comment]
2, Already add delete project, project policy and notary cases.
3, Keep working on the modification if get any misleading.
4, Pending.

**Comment by wy65701436** [comment]
2, Continue adding more test case for Clair.

**Comment by wy65701436** [comment]
What we did for E2E enhancement:

1, Revise all of tests for new UI.
2, Add new tests for batch deletion, notary, image scanning, LDAP.
3, Enable nightly and longevity test process.
4, Introduce new API framework with Go -- steven.
5, Update underlying library for robot.
6, Automate building all docker images.
