### ISSUE TITLE
Batch deletion ( wildcard in tag, remove all)

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#3190]
Let's support batch deletion and remove all in the Harbor console, will consider:

- Projects
- Image repositories
- Image tags
- Users

**Comment by lweitzman** [comment]
Note: Clarity uses a checkbox in the row of a datagrid to be able to select multiple rows for batch actions. https://vmware.github.io/clarity/documentation/datagrid/batch-action

**Comment by steven-zou** [comment]
@lweitzman 

Thanks Louise, we'll fully leverage the Clarity based related things to dev this feature.

**Comment by reasonerjt** [comment]
Per information from Henry this is a low priority, hence, I'll set the target to "vic"

**Comment by reasonerjt** [comment]
Resolved
