### ISSUE TITLE
Version Admiral data migration script

### ISSUE THREAD

**Issue by andrewtchin** [vmware/harbor#3191]
https://raw.githubusercontent.com/vmware/harbor/master/tools/migration/import

As part of the OVA build we pull this script in. This should be versioned and released to a bucket on GCP so that we can have reproducible builds. Version name should match the name of the corresponding offline installer.

**Comment by wy65701436** [comment]
This script is only for vic 1.2, and it could be removed from 1.3.

**Comment by andrewtchin** [comment]
Since this script is no longer needed this issue can be closed

**Comment by wy65701436** [comment]
Close it.
