### ISSUE TITLE
Replication service enhancement - P0.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#3193]
<img width="1121" alt="screen shot 2017-09-26 at 10 11 38" src="https://user-images.githubusercontent.com/5753287/30839238-2de270a0-a2a3-11e7-959a-3172b48b4b86.png">

More things:
1. The policy can be edited only and only if no corresponding replication is running.
2. Provide a way to let user stop the running replication (related jobs)
3. Check if we can support image tag alias/labeled function (leverage registry api | create new data model)
4. Replication must be incremental including the deletion
5. Certificate of destination Harbor should be verified
6. Deletion is replication settings which can be applied to Manual, Immediate and onSchedule triggeres
7. Deletion in src Harbor should be recorded (via log?) for future deletion replication

Dev things:
1. Keep the current code structure and just append enhancements
2. Move replication management to system level and left project level readonly.
3. Add repo and tag two filters (only official support *,? and |; backend parser can be use regexp)

Misc things:
1.Group the jobs under the same repo into a sub queue to avoid sequence issue
2.Make index for table access_log
3.Make sure the time of logs is accurate. Using the time of notification?
4.1)Replication all images under repo A to remote target
  2)Check the images of remote target that not exist in A
  3)Search the images from logs of A
  4)If log is found, replicate deletion operation to remote target

**Comment by steven-zou** [comment]
Draft estimation:
  core 4w
  filter 1w
  replicator 1w
  UI 2w
  test&fix 1w

**Comment by ywk253100** [comment]
Done
