### ISSUE TITLE
HA deployment support.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#3197]
This description involve quite a few items documented during internal discussion, may need to revise it to reflect the scope.

A document to help user deploy a HA Harbor, this requires some effort in different components. (worst case, no Notary, no Clair)  - P0
New component: introduce Redis in HA deployment, user will provide the Redis by default.   - P0
Not Considering HA of Harbor DB and shared storage for image blob.
AdminServer: Store conf in Harbor DB.  - P0
JobService:                             - P1
- In memory job queue → external jobqueue.
- Coordination in job reschedule.

Clair:                     - P1
- Communication between registry and Clair.
- Communication between UI and Clair/Clair DB

Notary:               - P2
- Communication between UI and Notary
- Need to decide on the UX and what to deliver (doc?Ansible playbook?)

_Not all of the work will be done before pks-1.0, but need to make sure there's feature hole or inconsistency for that release._

**Comment by yixingjia** [comment]
All issues related with this Epic
#3236
Identify a method to share secretkey, private_key and root.crt between Harbor nodes

#3237
store all the configuration items in Harbor to database
#3240
HA configure documentation.

#3316
KeepAlived setup instruction for harbor HA

#3317
Create docker registry config file for HA

#3318
Make change to job service to avoid replication conflicts in Active-Active mode

#3391
Create table to store configuration data

#3238
provide HA version of docker-compose file

#3239
provide script for generate shared keys/certs

#3315
Add -HA option in installation and prepare script

#3269
make harbor database configurable

**Comment by yixingjia** [comment]
https://github.com/vmware/harbor/issues/3582
HA solution proposal

**Comment by yixingjia** [comment]
Support Clair with HA setup
https://github.com/vmware/harbor/issues/3777

**Comment by yixingjia** [comment]
Support Notary in HA setup
https://github.com/vmware/harbor/issues/3791

**Comment by yixingjia** [comment]
https://github.com/vmware/harbor/issues/3895

Enable scan policy modification in HA setup

**Comment by yixingjia** [comment]
https://github.com/vmware/harbor/issues/3919

Support view job logs in HA installation.

**Comment by yixingjia** [comment]
https://github.com/vmware/harbor/issues/3938

**Comment by yixingjia** [comment]
Scheduler manager task sync
https://github.com/vmware/harbor/issues/3937

**Comment by yixingjia** [comment]
As we finished all the planned works for phase1. So close this issue. All the HA works for post 1.4 will be tracked by #4001
