### ISSUE TITLE
Checking enable content trust, but not checking prevent vuln images from running results in notary errors

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/harbor#3202]
@mhagen-vmware commented on [Fri Sep 08 2017](https://github.com/vmware/vic/issues/6259)

```
Error while pulling image manifest: download failed: Unexpected http code: 412 (Precondition Failed), URL: https://10.161.107.186:443/v2/definitely-not-default/ubuntu/manifests/test, Message: The image is not signed in Notary.
```

My understanding is that content trust should just be whitelist and the prevent vuln image should be the notary check? Independent?

---

@mhagen-vmware commented on [Fri Sep 08 2017](https://github.com/vmware/vic/issues/6259#issuecomment-328208884)

@reasonerjt Is this as expected?

---

@stuclem commented on [Tue Sep 12 2017](https://github.com/vmware/vic/issues/6259#issuecomment-328837964)

@mhagen-vmware I see the kind/note flag, but isn't this covered by https://github.com/vmware/vic/issues/6258? 

---

@mhagen-vmware commented on [Tue Sep 12 2017](https://github.com/vmware/vic/issues/6259#issuecomment-328844602)

Nope, 6258 is just dealing with enabling whitelisted mode, this issue is about whitelist/notary interaction. We have 2 check boxes. The first should just enable/disable whitelist, the second should just enable/disable vulnerability scanning. Right now the first one enables both.

**Comment by mhagen-vmware** [comment]
@stuclem moved here

**Comment by reasonerjt** [comment]
@mhagen-vmware I don't understand what this ossue is about.

**Comment by reasonerjt** [comment]
@mhagen-vmware 
After a discussion with George I think I can guess what you mean, but this is by design, when the "content trust" checkbox is checked, Harbor will only allow signed image under this project be pulled.
It does not only impact the whitelist of VCH.

**Comment by mhagen-vmware** [comment]
https://github.com/vmware/vic-product/issues/809

Closing in favor of vic-product issue to get this answered in a larger forum.
