### ISSUE TITLE
List of Environment Variables

### ISSUE THREAD

**Issue by vasartori** [vmware/harbor#3210]
Hi, there's a way to find a list of all supported environment variables and what each var does?

**Comment by steven-zou** [comment]
@vasartori as far as I know, we don't have a central place to list out all the env vars.

@ywk253100 Right?

**Comment by vasartori** [comment]
If you search on code for os.Getenv we found a lot of env vars but we don't know the behaviour of this vars. Some are intuitives, others not so much...

**Comment by steven-zou** [comment]
@vasartori  We'll have a discussion about adding ENV vars in the document soon.

**Comment by ywk253100** [comment]
@vasartori Env variables should be transparent to users, all configurations can be set by configuration file harbor.cfg, and some of them can be set on web UI either.

**Comment by vasartori** [comment]
@ywk253100 IMHO it not so good. If I want change a small thing, like the number job of workers or if I need put a new ldap filter, I need make a new deploy. In some cases It is not fast. It could be only a restart.
I like to know what an option do, just to understand what are happen in background.

**Comment by ywk253100** [comment]
@vasartori The new deploy is not needed. About the detail of reconfiguring Harbor, refer to the "Managing Harbor's lifecycle" part of installation guide [here](https://github.com/vmware/harbor/blob/master/docs/installation_guide.md#managing-harbors-lifecycle). And some common configuration items, such as LDAP filter, can be modified on the web UI directly.

You want to try the "hard way" to understand very well what happened, that's good. But for most of the users, they don't need it, so the guide may not be provided. If any detail you want to know, just open issues.

**Comment by vasartori** [comment]
@ywk253100 OK, I understand!
