### ISSUE TITLE
Need UX design for metadata/description of repository

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#3216]

**Comment by steven-zou** [comment]
@lweitzman 

Capture some screenshots from DTR for your reference:

<img width="803" alt="screen shot 2017-09-19 at 12 52 00" src="https://user-images.githubusercontent.com/5753287/30576300-8190a344-9d39-11e7-8cd8-fce8fe6f1b51.png">
<img width="767" alt="screen shot 2017-09-19 at 12 51 48" src="https://user-images.githubusercontent.com/5753287/30576301-81c7b262-9d39-11e7-8a42-dc4bbe2b707d.png">

**Comment by lweitzman** [comment]
here is a mockup for the info for a repository
https://vmware.invisionapp.com/share/PQDL0QBKN#/254408806_Harbor_-_Repositories_Copy

**Comment by lweitzman** [comment]
a mockup is here:
https://vmware.invisionapp.com/share/A7BYGL28Q#/238405133_Integrated_-_Project_Repositories 

an info summary is shown in the datagrid for the repo. 
a tooltip could show the complete info content.
then, click on the pink circle (pink circles are used to indicate where some of the non-obvious places to click are) to get a menu for the repo 
not sure if this is a complete set of actions on a repo. but clicking on info brings up a dialog to view the info content.
clicking on the edit in that dialog changes it to an edit dialog to do markdown.

**Comment by steven-zou** [comment]
Provided, close this issue
