### ISSUE TITLE
Administrator in UAA auth mode.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#3220]
In DB mode the admin username is hard coded.
But we need to make decision whether we should continue this behavior when the auth credentials are relayed to UAA.

**Comment by reasonerjt** [comment]
Per discussion, to avoid migration effort, as a workaround we'll provide a internal API that only allows the original admin (id == 1) to call, and when it's called the user `admin` will be renamed to `admin@local`

**Comment by jessehu** [comment]
How about provide a script to let user rename 'admin' to 'admin@local' in Harbor DB back and forth?
And is it admin@local or admin@harbor.local ? Seems admin@harbor.local is better.

**Comment by reasonerjt** [comment]
yes it's typo, the new name will be admin@harbor.local.

**Comment by reasonerjt** [comment]
API has been merged to master, UI will provide a button to support it.

**Comment by ninjadq** [comment]
Added in PR #4037
