### ISSUE TITLE
Replication 403 if swift as registry storage

### ISSUE THREAD

**Issue by mervynzhang** [vmware/harbor#3225]
Our harbor has swift as registry backend storage, replication gets error 403. 
`Sep 16 06:36:27 172.18.0.1 jobservice[1024]: 2017-09-16T06:36:27Z [DEBUG] [transport.go:51]: 403 | GET http://swift.datayes.com/v1/AUTH_XXXXX/files/docker/registry/v2/blobs/sha256/aa/aab39f0bc16d3c109d7017bcbc13ee053b9b1b1c6985c432ec9b5dde1eb0d066/data?temp_url_sig=111111111111111&temp_url_expires=1505544987`
Harbor's PullBlob function is using http.client, so I did some tests, if the http.client/request has auth info, 403 is returned when getting the swift temp url for the blob. If http.client/request has no auth info. 200 is returned. 

So, could you please check swift and remove auth info in the http.client/request in PullBlob? Thanks.

**Comment by reasonerjt** [comment]
@mervynzhang could you clarify does this issue only happen when the "source" registry points to swift?
Did you try the case when the "target" registry is set to swift?

**Comment by mervynzhang** [comment]
@reasonerjt this error occured when **pulling blobs from source registry**, it didn't reach the target registry yet.  
Based on my tests, when pulling blobs, registry swift driver return a temp url for the blobs, if the http.client/request visiting the temp url has auth info, swift will use the auth info wich is incorrect swift user/password and return 403. But if http.client/request has no auth info, swift will treat the visiting to temp url correctly and return 200.

**Comment by ywk253100** [comment]
What is the version of Harbor that you are testing? There is a similar issue #1006 in the early version of Harbor, but it's has been fixed.

**Comment by mervynzhang** [comment]
@ywk253100 It looks like fix for 1006 only works for aws s3, before filterReq use v2Index := strings.Index(req.URL.Path, "/v2/") as the filter, but swift url also has v2

Sep  6 02:27:19 172.18.0.1 jobservice[1024]: 2017-09-06T02:27:19Z [DEBUG] [transport.go:51]: 403 | 
GET http://swift.datayes.com/v1/datayes/harbor/files/docker/registry/**v2**/blobs/sha256/aa/aab39f0bc16d3c109d7017bcbc13ee053b9b1b1c6985c432ec9b5dde1eb0d066/data?temp_url_sig=7ae07f3997a1d918fc8a9074c7a6fc76f0d70a32&temp_url_expires=1504666039

while registry using local storage:
Sep 18 13:35:58 172.18.0.1 jobservice[946]: 2017-09-18T05:35:58Z [DEBUG] [transport.go:50]: 200 | GET http://registry:5000/**v2**/test/test/blobs/sha256:df74c0cea8ad6b25004db74b9829d513990ac7e219128594eb2b7df2d785f961

**Comment by ywk253100** [comment]
It does not only check the existence of "/v2/" but also check the host, scheme and URL path.

**Comment by mervynzhang** [comment]
@ywk253100 we're using version 0.5.

**Comment by mervynzhang** [comment]
@ywk253100  @reasonerjt  I just tested with version 1.20. replication with with swift. 

Sep 18 16:31:35 172.18.0.1 jobservice[946]: 2017-09-18T08:31:35Z [DEBUG] [tokenauthorizer.go:61]: the request http://swift.wmcloud.com/v1/AUTH_datayes/harbor-test/files/docker/registry/v2/blobs/sha256/e4/e485506b272ee957f6e0fe7b62bb4a2e1d5d2b5de3771029d0309af97dadd7c9/data?temp_url_sig=09996c1e113ba597efc76d0a8d1249b0e66e4421&temp_url_expires=1505724695 is not sent to registry, skip
Sep 18 16:31:35 172.18.0.1 jobservice[946]: 2017-09-18T08:31:35Z [DEBUG] [transport.go:50]: 200 | GET http://swift.wmcloud.com/v1/AUTH_datayes/harbor-test/files/docker/registry/v2/blobs/sha256/e4/e485506b272ee957f6e0fe7b62bb4a2e1d5d2b5de3771029d0309af97dadd7c9/data?temp_url_sig=09996c1e113ba597efc76d0a8d1249b0e66e4421&temp_url_expires=1505724695
