### ISSUE TITLE
Make the logo, header and the login background picture be configurable

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#3241]
Make the logo, header and the login background picture be configurable

**Comment by pengpengshui** [comment]
![1505885995 1](https://user-images.githubusercontent.com/29880301/30628530-82562f94-9e09-11e7-8752-989b8bea0798.jpg)

I create a setting.json file for user config, they can put the images what they want to replace into the images file.   I create a service to read setting.json  info and   do the homologous replacement.
