### ISSUE TITLE
Support batch deletion on UI

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#3242]
Let's support batch deletion and remove all in the Harbor console, will consider:

Projects
Image repositories
Image tags
Users

**Comment by pengpengshui** [comment]
![image](https://user-images.githubusercontent.com/29880301/30628686-58b465c4-9e0a-11e7-94d5-dd4548ab761e.png)
I do a demo about  batch deletion ,like upside image .  I thinks with a  checkbox and a  operation list in a row

**Comment by steven-zou** [comment]
@lweitzman 

Louis, what do you think of the screenshot @pengpengshui provided? Any suggestions? Thanks

**Comment by lweitzman** [comment]
originally the screenshot @pengpengshui shows is what the clarity team had suggested for multi-select + row actions. but now i see it not on the clarity site. i will follow up with them.
