### ISSUE TITLE
Provide mockup for project level policy of standalone Harbor

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#3243]
Please refer the design in VIC management portal:
<img width="806" alt="screen shot 2017-09-19 at 12 58 06" src="https://user-images.githubusercontent.com/5753287/30576415-53075b70-9d3a-11e7-8419-e0a2c62b9c84.png">

**Comment by lweitzman** [comment]
Here is a mockup for the project configuration page
https://vmware.invisionapp.com/share/A3DL0SC8V#/254408803_Harbor_-_Project_-_Configuration_Copy
