### ISSUE TITLE
Make Clair Postgres DB connection configurable

### ISSUE THREAD

**Issue by everett-toews** [vmware/harbor#3245]
https://github.com/vmware/harbor/blob/b0adf7e8d4df0ac380533bd412ceb8cb829fb959/src/common/dao/base.go#L47-L55

Clearly this is a known issue but I couldn't find an issue tracking it. 

It's definitely necessary to make this configurable.

**Comment by reasonerjt** [comment]
@everett-toews Given the use cases and deployment model of Harbor, we'll make this change when needed, but probably not in very near future.

**Comment by everett-toews** [comment]
@reasonerjt Thanks for taking a look at this. 

I suspect you might find a need for it when working on https://github.com/vmware/harbor/issues/3253 You'll wind up creating a lot of Kubernetes `Service` resources and it's nice to have the flexibility of configurable names.

**Comment by mrueg** [comment]
I'd like to second this request. Some might be interested in running these services standalone (without containers around) as well.

**Comment by reasonerjt** [comment]
notary and clair will likely fall out of scope of #3253.  But yes I understand have it configurable is helpful.

**Comment by jessehu** [comment]
@reasonerjt I think this issue is fixed in https://github.com/vmware/harbor/commit/f63588855f8d3b1b138d3be63ca165bb52ab930c ?

**Comment by reasonerjt** [comment]
I think so, I'm closing this issue.
