### ISSUE TITLE
With big screen resolution, UI looks bad

### ISSUE THREAD

**Issue by monicaw** [vmware/harbor#325]
![bigscreen](https://cloud.githubusercontent.com/assets/19568623/15886564/47d40372-2d90-11e6-8c66-44b8ac912d60.jpg)

**Comment by monicaw** [comment]
Related mockup: https://wiki.eng.vmware.com/wiki/images/1/15/Image-Sync.pdf

**Comment by xiaods** [comment]
we need designer to participate

**Comment by monicaw** [comment]
Already have a suggestion in previous review. And synced with Kun. Most page have the problem.
Solution:
Don't lock the height. Make the view size the same as the screen height. (自适应高度)
