### ISSUE TITLE
Make Clair connection configurable 

### ISSUE THREAD

**Issue by everett-toews** [vmware/harbor#3250]
https://github.com/vmware/harbor/blob/82dc75806447a2f3cc25d98502b91d45ef0cef3a/src/common/const.go#L72

It would be nice to have this value configurable instead of hardcoded.

**Comment by reasonerjt** [comment]
Please see https://github.com/vmware/harbor/issues/3245#issuecomment-330740543

**Comment by paulczar** [comment]
:+1:  We really need to be able to make the clair endpoint configurable.

**Comment by jessehu** [comment]
This is duplicated by https://github.com/vmware/harbor/issues/4269

**Comment by jessehu** [comment]
Assign to @yixingjia since he is working on something related.

**Comment by yixingjia** [comment]
Clair  endpoint is now configurable.
