### ISSUE TITLE
Verify and make the deployment solution on Kubernetes work.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#3253]
Make necessary change to make the solution work with 1.2.0 release: https://github.com/vmware/harbor/tree/master/make/kubernetes

And make change in doc accordingly.

**Comment by halfa** [comment]
I actually started to work on this 2 weeks ago, would be very interested by any progress. Documentation on this topic is vastly outdated and the overall architecture -with `clair`- is far from simple. Would be interested to compare any early draft with my own configuration!

**Comment by reasonerjt** [comment]
@halfa Enabling Clair is out of the scope of this issue.  We'll work iteratively to bring that in.

This issue will be closed once #3302 is merged.

**Comment by reasonerjt** [comment]
Fixed in #3302

**Comment by halfa** [comment]
I was able to finish my config (with `clair` fully working) with some help from #3302's commits. Thank you!

**Comment by reasonerjt** [comment]
@halfa
Glad to know.
Is your Clair also running on K8S
It'd be helpful if you can let us know how you get it work with Clair.

**Comment by halfa** [comment]
@reasonerjt here are some insights for your `clair` config files, courtesy of @naitways: [Gist](https://gist.github.com/halfa/fda3ba62f83e3ab405d9e3df7e9fcc17). Only the configmap and pvc are missing, but our setup is a bit specific anyway. Hope it'll helps you!
