### ISSUE TITLE
Install failed,please check code!

### ISSUE THREAD

**Issue by lijianwuming** [vmware/harbor#326]
1)# docker-compose -v
      docker-compose version 1.7.1, build 0a9ab35
   # docker version
     Client & Server
     Version:      1.11.2
   # cat /etc/redhat-release 
     CentOS Linux release 7.2.1511 (Core) 
2)# pwd
     /opt/harbor/Deploy
   # grep hostname harbor.cfg    ================>I just only change hostname
     hostname = registry.test.com
   #  ./prepare
       .......
     The configuration files are ready, please use docker-compose to start the service.
   # docker-compose up -d
Creating network "deploy_default" with the default driver
Building log
Step 1 : FROM library/ubuntu:14.04
14.04: Pulling from library/ubuntu
6c953ac5d795: Pull complete
3eed5ff20a90: Pull complete
f8419ea7c1b5: Pull complete
51900bc9e720: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:97421885f3da3b23f52eeddcaa9f8f91172a8ac3cd5d3cd40b51c7aad09f66cc
Status: Downloaded newer image for ubuntu:14.04
 ---> 8f1bd21bd25c
Step 2 : RUN mv /etc/cron.daily/logrotate /etc/cron.hourly/     && rm /etc/rsyslog.d/*         && rm /etc/rsyslog.conf
 ---> Running in 4ef12d6cf8ce
 ---> 4c756c8e0d55
Removing intermediate container 4ef12d6cf8ce
Step 3 : ADD rsyslog.conf /etc/rsyslog.conf
 ---> dff42e187ba0
Removing intermediate container 372fc52e1aa1
Step 4 : ADD logrotate_docker.conf /etc/logrotate.d/
 ---> 4f17d9b2d6f7
Removing intermediate container dc4abe3c2d7c
Step 5 : ADD rsyslog_docker.conf /etc/rsyslog.d/
 ---> d10e9beb1b3b
Removing intermediate container 5ddd26bb57a9
Step 6 : VOLUME /var/log/docker/
 ---> Running in 14bf4bbd7948
 ---> 86bd6d9a5d75
Removing intermediate container 14bf4bbd7948
Step 7 : EXPOSE 514
 ---> Running in dec79c353c69
 ---> e55e3231e943
Removing intermediate container dec79c353c69
Step 8 : CMD cron && rsyslogd -n
 ---> Running in 28c939772eff
 ---> e0b0286e3bae
Removing intermediate container 28c939772eff
Successfully built e0b0286e3bae
**_WARNING: Image for service log was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`._**
Building ui
Step 1 : FROM golang:1.6.2
1.6.2: Pulling from library/golang
51f5c6a04d83: Pull complete
65e9ddd8bd7a: Pull complete
c41545ebedf5: Pull complete
2bf007350a17: Pull complete
8534b4ecb14e: Pull complete
ac37d9d8babe: Pull complete
87c8bfcf9844: Pull complete
Digest: sha256:6f73057fbdb06326b76f83fa18c5942cb5b2bac53505967ef7657f75daeec2bb
Status: Downloaded newer image for golang:1.6.2
 ---> 5850add7ecc2
Step 2 : MAINTAINER jiangd@vmware.com
 ---> Running in 243c866f2009
 ---> 1e93c2501a85
Removing intermediate container 243c866f2009
Step 3 : RUN apt-get update     && apt-get install -y libldap2-dev     && rm -r /var/lib/apt/lists/*
 ---> Running in e258c21f1ee0
Ign http://httpredir.debian.org jessie InRelease
Get:1 http://httpredir.debian.org jessie-updates InRelease [142 kB]
Get:2 http://httpredir.debian.org jessie-updates/main amd64 Packages [17.3 kB]
Get:3 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:4 http://httpredir.debian.org jessie Release.gpg [2373 B]
Get:5 http://security.debian.org jessie/updates/main amd64 Packages [312 kB]
Get:6 http://httpredir.debian.org jessie Release [148 kB]
Get:7 http://httpredir.debian.org jessie/main amd64 Packages [9032 kB]
Fetched 9718 kB in 29s (330 kB/s)
W: Failed to fetch http://security.debian.org/dists/jessie/updates/main/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'ui' failed to build: The command '/bin/sh -c apt-get update     && apt-get install -y libldap2-dev     && rm -r /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by ywk253100** [comment]
It seems that the issue is caused by network problems. Have you tried again or change a network environment and re-install Harbor?

**Comment by wknet123** [comment]
It is always caused by DNS of Docker daemon configuration, please set it at /etc/default/docker, and then restart the Docker daemon service.

**Comment by lijianwuming** [comment]
I tried re-install in anothor network environment,and it's worked,thanks anyway.
