### ISSUE TITLE
跨公网镜像复制的安全性问题

### ISSUE THREAD

**Issue by fffffreedom** [vmware/harbor#3261]
你好
我们两个数据中心之间，通过公网连接。我看了下源码，镜像同步使用的是http协议，请问通过公网进行镜像同步是否存在安全问题？
谢谢！

**Comment by reasonerjt** [comment]
It is https if you are replication target is serving https with valid certificate.

**Comment by fffffreedom** [comment]
yes, i shoud turn on the `verify_remote_cert` entry, and use https on both side

**Comment by hainingzhang** [comment]
yes, that's the right way.
