### ISSUE TITLE
hide part of ui

### ISSUE THREAD

**Issue by jiananjiang** [vmware/harbor#3268]
我用的是harbor1.2.0版本，用的源码安装的，用的http。
centos7
go version go1.8.3 linux/amd64

[root@centjiang ~]# docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      88a4867/1.12.6
 Built:           Mon Jul  3 16:02:02 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      88a4867/1.12.6
 Built:           Mon Jul  3 16:02:02 2017
 OS/Arch:         linux/amd64
[root@centjiang ~]# docker-compose -v
docker-compose version 1.14.0, build c7bdf9e

现在，我想把UI上的最受欢迎的镜像隐藏掉，所以改了/root/harbor/src/ui_ng/src/app/account/sign-in里面的sign-in.component.html文件里的 
然后，运行命令
make install GOBUILDIMAGE=golang:1.7.3 COMPILETAG=compile_golangimage CLARITYIMAGE=vmware/harbor-clarity-ui-builder:1.2.7
出现错误：[root@centjiang harbor]#  make install GOBUILDIMAGE=golang:1.7.3 COMPILETAG=compile_golangimage CLARITYIMAGE=vmware/harbor-clarity-ui-builder:1.2.7

Note: golang version: 1.8.3

Note: docker version: 1.12.6

Note: docker-compose version: 1.14.0
compiling binary for clarity ui...
cat: ./package.json: Permission denied
make: *** [compile_clarity] Error 1

但是，我的/harbor/src/ui_ng/src/app/account/sign-in的目录全是最高权限了。
please~

**Comment by steven-zou** [comment]
We'll try to reproduce the issue on the centos OS and locate the root cause of this issue soon.

**Comment by jiananjiang** [comment]
thanks~
