### ISSUE TITLE
Harbor 1.2.0 repository UI fields overwrites

### ISSUE THREAD

**Issue by roldancer** [vmware/harbor#3275]
Hi, Some fields for example TAG/Pull Command  and Author/Creation Time overwrite, look at the following screenshoot.

![selection_361](https://user-images.githubusercontent.com/5012200/30773669-4f4dcd3c-a075-11e7-8a80-e4d237db3544.jpg)

**Comment by steven-zou** [comment]
@pengpengshui 

  Let's have a look and see if we have better way to fix it.

**Comment by roldancer** [comment]
Hi @steven-zou let me know if there is a workaround, I want to put in production two registries in two weeks...

Thanks.

**Comment by dangzhiqiang** [comment]
@steven-zou Harbor 1.2.0 also have alignment issues. ![image](https://raw.githubusercontent.com/dangzhiqiang/images/master/harbor/harbor-ui-project.png)

**Comment by roldancer** [comment]
Hi @steven-zou Is there any news about this issue?

Thanks.

**Comment by steven-zou** [comment]
@roldancer
We have trying to fix the issue and will merge the fix code after our National Day Holiday (Oct 9th), is that ok?

**Comment by roldancer** [comment]
Yes, many thanks !!!

**Comment by roldancer** [comment]
Hi, Is this improvement included in the latest release 1.2.2 ?

Thanks.
