### ISSUE TITLE
Scan image immediately when an image push happens

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#3278]
It will be nice that Harbor can provide the functionality like scan image immediately when an image push happens.

**Comment by vasartori** [comment]
On UI, if you set this environment variable, a scan will be schedule.... I don't know if this is the best approach, but works for me.

ENABLE_HARBOR_SCAN_ON_PUSH="1"

**Comment by yixingjia** [comment]
Yes, but currently it's hidden functionality. We need to support this from Harbor UI

**Comment by reasonerjt** [comment]
Closing as this is covered by Epic https://github.com/vmware/harbor/issues/3160
