### ISSUE TITLE
when re-run prepare harbor should remove the /data/config/config.json file if there is

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#3280]
When re-run prepare Harbor. It should remove the /data/config/config.json file. Otherwise some configuration file will not related.

As currently Harbor will only reload some parameters if the /data/config/config.json file exsit. Delete the file will force Harbor to load all the changed parameters.

**Comment by ywk253100** [comment]
If the config.json is removed, the configuration set on the web UI by users will lose. And there is already a `Reset` API used to load all configuration from the environment.
