### ISSUE TITLE
如果不用docker-proxy转发，将harbor各组件拆分，给每个容器单独设置固定IP，要怎么实现？

### ISSUE THREAD

**Issue by KeithTt** [vmware/harbor#3287]
具体地说，就是放弃iptables转发，改用网桥。

每个容器单独直接用docker run [OPTIONS]单独运行，然后用ip netns给容器分配IP。

是不是只需要把docker-compose.yml里的设置都跟在docker run后面，然后分别run起来就可以？

**Comment by reasonerjt** [comment]
It essentially how process communicate with each other via network, there are many ways... Please try it yourself.
