### ISSUE TITLE
Create deployment manifest of vSphere for harbor bosh release

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#3297]
deployment manifest on vsphere

**Comment by steven-zou** [comment]
manifest for vSphere is ready

**Comment by DRuggeri** [comment]
Cool! Is there a place folks can download and try it for early feedback?

**Comment by steven-zou** [comment]
@DRuggeri 

  Thanks for lettings us you also want to try Harbor BOSH release. However, it is still under development and restricted as internal project at present. Once it's ready, we'll announce the formal project repo. It will not be long.Please keep eyes on it.

**Comment by steven-zou** [comment]
It's already done! Close issue.
