### ISSUE TITLE
Add smoke test for harbor bosh release

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#3300]
Optional work

**Comment by steven-zou** [comment]
No time to start, move to the next sp22

**Comment by reasonerjt** [comment]
Please make sure the test is executed against a deployment of tile.

**Comment by steven-zou** [comment]
Work is in progress, but not completed yet. Let's move to next sp (23)

**Comment by steven-zou** [comment]
Ongoing, need to postponed to next SP (SP24).

Overall Summary:
  Case is ready
  Script: 30% done
  Dependant Packages: 50% done

**Comment by steven-zou** [comment]
Done! Code merged! See https://gitlab.eng.vmware.com/harbor/habo/merge_requests/1
