### ISSUE TITLE
Enable Clair be able to use external database 

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#3320]
We should support Clair to be able to use external database.
Some user has requirement to have a centralized database to store the data.

Currently we don't support user external Clair db

**Comment by reasonerjt** [comment]
This is essentially asking Harbor to customize Clair.
I don't think we'll handle it in near future.
If user wants he can always modify Harbor and make it talk to his customized Clair.

**Comment by yixingjia** [comment]
Fixed by https://github.com/vmware/harbor/pull/3831
