### ISSUE TITLE
Verify version upgrade with BOSH deployment

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#3341]
Create multiple versions of BOSH releases for Harbor and verify the version upgrading does work

**Comment by steven-zou** [comment]
Not started at SP19, MOVE to SP20

**Comment by steven-zou** [comment]
@jessehu will work on this issue.

Just started at end of sp20, let's postponed this issue to sp21

**Comment by jessehu** [comment]
It's almost completed. Move to next Sprint.

**Comment by jessehu** [comment]
code committed:
- http://url.eng.vmware.com/6d43
- http://url.eng.vmware.com/hd43
- http://url.eng.vmware.com/kd43
