### ISSUE TITLE
which protocol will be used during image replication if i set verify_remote_cert = off and ui_url_protocol = https

### ISSUE THREAD

**Issue by fffffreedom** [vmware/harbor#3346]
hi
i read the src code, and i think if i  set set verify_remote_cert = off, the images replication will use http to transfer images. But jt@vmware said, even if verify_remote_cert  is set to off,  https will be used.
But i don't think so ,  the following code shows:
statemachine.go 
	verify, err := config.VerifyRemoteCert() **# get the verify_remote_cert config**
	if err != nil {
		return err
	}
	sm.Parms = &RepJobParm{
		LocalRegURL: regURL,
		Repository:  job.Repository,
		Tags:        job.TagList,
		Enabled:     policy.Enabled,
		Operation:   job.Operation,
		Insecure:    !**verify**,  **# set insecure param, that is ture if verify_remote_cert = off** 
	}
authorizr.go
// NewAuthorizerStore ...
func NewAuthorizerStore(endpoint string, insecure bool, authorizers ...Authorizer) (*AuthorizerStore, error) {
	endpoint = utils.FormatEndpoint(endpoint)

	client := &http.Client{
		Transport: registry.GetHTTPTransport(insecure), 
		Timeout:   30 * time.Second,
	}
// GetHTTPTransport returns HttpTransport based on insecure configuration
func GetHTTPTransport(insecure bool) *http.Transport {
	if insecure {     **# if use insecureHttpTransport**
		return insecureHTTPTransport
	}
	return secureHTTPTransport
}

**Comment by reasonerjt** [comment]
Did you test?  Try blocking 80 port and see if it works :)
