### ISSUE TITLE
如何获取镜像列表

### ISSUE THREAD

**Issue by 1740024005** [vmware/harbor#3360]
你好，
用原生版本获取
curl -X GET --cacert /etc/docker/certs.d/xxx.com/ca.crt https://xxx.com/v2/_catalog
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]}
如果用swagger UI 获取
麻烦给一下请求uri
至此 敬礼。

**Comment by 1740024005** [comment]
docker  Version:      17.09.0-ce
docker-compose version 1.16.1, build 6d1ac219
harbor 1.2.0

**Comment by xiaods** [comment]
还是需要自己动手看看

**Comment by ywk253100** [comment]
You can use Harbor's API to get repository list. 
If you want to use the APIs of the registry directly, you need to get a valid token from Harbor's token service GET /service/token and then call registry's APIs with the token.

**Comment by 1740024005** [comment]
Thanks all. the problem has been solved.
e.g.
curl -k -i -u admin:xxx https://xxx/service/token?account=dev\&service=harbor-registry\&scope=registry:catalog:*
curl -k -H "authorization: bearer $token " https://xxx/v2/_catalog
or use Harbor API
GET /api/projects
GET /api/repositories?project_id=
GET /api/repositories/tags?repo_name=XXX

Thank again.

**Comment by KeithTt** [comment]
Good job, thanks a lot, I know how to use swagger-ui through this issue.
