### ISSUE TITLE
Docker Compose Version not right?

### ISSUE THREAD

**Issue by wkjun** [vmware/harbor#3380]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
```
docker-compose version 1.16.1, build 6d1ac21
docker version: 1.12.6
```
but when is use `sudo ./install.sh`
```
[Step 0]: checking installation environment ...
Note: docker version: 1.12.6
✖ Need to install docker-compose(1.7.1+) by yourself first and run this script again.

```
From the Installation Guide ,it  only say "Docker Compose needs to be version 1.6.0 or higher"

**Comment by wkjun** [comment]
i kow the reason:
Operation System:
`CentOS Linux release 7.3.1611 (Core)`

docker-compose In Linux default install way is 
```
sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
```
narmal user's PATH parameter:
```
/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/tutu/.local/bin:/home/user/bin
```
root's PATH parameter:

```
/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
```

use `sudo` to execute install.sh which use the root  system parameter `PATH`,which could't find `docker-compose` ,Ubuntu System does not have the problem.

how i solve the problem is change the install dir ,replaced  `/usr/local/bin`   with `/usr/local/sbin` in docker-compose install step:

```
sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/sbin/docker-compose
```

**Comment by reasonerjt** [comment]
Great, thanks.

**Comment by reasonerjt** [comment]
Great, thanks.
