### ISSUE TITLE
in UI capacity storage view is not correct?

### ISSUE THREAD

**Issue by wkjun** [vmware/harbor#3384]
1)Version of docker engine and docker-compose.
```
 docker engine   Version:         1.12.6
docker-compose   version 1.9.0
```
2)My docker-compose.yml  modify registry's volumes:
```
volumes:
      - /vss/data/registry:/storage:z
```
maybe ,this is related to  the code in `https://github.com/vmware/harbor/blob/8a23f0e0a188b6d63adc597005401cea1ed1e9e4/src/ui/api/systeminfo.go`

Capacity storage display  is still use my system storage ?

**Comment by ywk253100** [comment]
Refer to the method mentioned by #3356.

**Comment by wkjun** [comment]
thks,my situation is different from it,but it give me much associations, i only want change  registry's volume,so i keep the `adminserver` default env  `IMAGE_STORE_PATH`  which default value is `/data` in the container, i only modify the volume out of it  in docker-compose.yml : 
```
registry:
....
volumes:
      - /vss/data/registry:/storage:z
....
adminserver:
....
   volumes:
     - /vss/data:/data/:z
....
```
 it is ok.

**Comment by ywk253100** [comment]
Closing the issue as your problem is resolved according to your comment. Feel free to reopen it if not.
