### ISSUE TITLE
A way to change the timeout on the UI

### ISSUE THREAD

**Issue by randrewedwards** [vmware/harbor#3400]
Is there a way to change the timeout on the UI? I can't see any options in the Administrator Configuration settings or in harbor.cfg.

**Comment by ywk253100** [comment]
What timeout do you want to set? Did you meet some timeout issues?

**Comment by randrewedwards** [comment]
On the UI in browser, I find that it logs out too soon and I have to log in again.

This is just a QOL change, it doesn't impact us but would be nice if we could change it.

**Comment by ywk253100** [comment]
You can modifying the session timeout  by adding `sessiongcmaxlifetime = 3600` in common/config/ui/app.conf. The default value is 3600s, change it with yours.

**Comment by steven-zou** [comment]
Outdated, close issue

**Comment by rbkaspr** [comment]
I'd like to reopen this issue, there really needs to be a way to configure this through the UI, the default timeout is ridiculously low, and the configs have been restructured in 1.8 so I can't just apply the same fix that @ywk253100 suggested previously.

**Comment by rbkaspr** [comment]
Also, when running with OIDC authentication, my sessions will time out in between page loads.
