### ISSUE TITLE
the first copy task is fail

### ISSUE THREAD

**Issue by SILLKY** [vmware/harbor#3406]
I hava 2 harbor  in test cluster and product cluster.
I set a  task to copy in my test cluster.
when I push a image,the task is start but status is error

the log say:
2017-10-19T05:47:59Z [ERROR] [transfer.go:351]: an error occurred while pulling manifest of library/registry:latest from http://registry:5000: 404 {"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"Tag":"latest"}}]}

I try again  , is ok
I think the image is not push to registry complete but this time task is start and so not find manifest.
so when push again is ok.

so we need push 2 times same images every times or it is a bug  or I config error?

**Comment by SILLKY** [comment]
I know ，because I use  nfs  filesystem  . it  delay 10-30s  . so it not can find manifest

**Comment by reasonerjt** [comment]
Thanks, since it's due to configuration of NFS, closing this issue.
