### ISSUE TITLE
Browser does not pre-fill login credentials

### ISSUE THREAD

**Issue by cweiske** [vmware/harbor#3432]
When visiting the login page, my browser does not auto-fill username and password. When successfully logging in, it also does not ask me to save username+password. This makes it harder to use Harbor.

We're using harbor version 1.1.2. The problem happens on Chromium 61.

**Comment by steven-zou** [comment]
@ninjadq 

  Please take a look at this issue.

**Comment by ninjadq** [comment]
Hi @cweiske ,
I can't reproduce this. Are you tried A newer version of harbor?

**Comment by cweiske** [comment]
No, I cannot try a new version. I'm only a user here in our company.

**Comment by zhoumeina** [comment]
This can not reproduce. May be related with browser setting.

**Comment by zhoumeina** [comment]
close due to inactivity.
