### ISSUE TITLE
clair.log grow too fast every day  9.7G！！

### ISSUE THREAD

**Issue by Yeefoner** [vmware/harbor#3433]
version：v1.2.0
OS：CentOS  7.2
du -sh * /var/log/harbor/2017-10-22
36K	adminserver.log
4.0K	anacron.log
1.4M	clair-db.log
9.7G	clair.log
4.0K	crond.log
4.0K	CROND.log
664K	jobservice.log
52K	mysql.log
120K	proxy.log
5.4M	registry.log
4.0K	run-parts.log
1.1M	ui.log

---------------------------------
刷新频繁
Oct 23 16:09:07 172.18.0.1 clair[9892]: {"Event":"Handled HTTP request","Level":"info","Location":"router.go:57","Time":"2017-10-23 08:09:07.993535","elapsed time":6937237,"method":"GET","remote addr":"172.19.0.5:52213","request uri":"/v1/notifications/167f8469-34e0-4715-9a3b-beee5d96b988?limit=2","status":"200"}
Oct 23 16:09:07 172.18.0.1 clair[9892]: {"Event":"Handled HTTP request","Level":"info","Location":"router.go:57","Time":"2017-10-23 08:09:07.997718","elapsed time":1110168,"method":"DELETE","remote addr":"172.19.0.5:52213","request uri":"/v1/notifications/167f8469-34e0-4715-9a3b-beee5d96b988","status":"200"}
Oct 23 16:09:07 172.18.0.1 clair[9892]: {"Event":"successfully sent notification","Level":"info","Location":"notifier.go:184","Time":"2017-10-23 08:09:07.998208","notification name":"167f8469-34e0-4715-9a3b-beee5d96b988"}
Oct 23 16:09:08 172.18.0.1 clair[9892]: {"Event":"found and locked a notification","Level":"info","Location":"notifier.go:143","Time":"2017-10-23 08:09:08.034668","notification name":"16fb9c19-9253-4741-850c-300bd70bf9e5"}
Oct 23 16:09:08 172.18.0.1 clair[9892]: true
Oct 23 16:09:08 172.18.0.1 clair[9892]: {"Event":"Handled HTTP request","Level":"info","Location":"router.go:57","Time":"2017-10-23 08:09:08.041954","elapsed time":6322468,"method":"GET","remote addr":"172.19.0.5:52213","request uri":"/v1/notifications/16fb9c19-9253-4741-850c-300bd70bf9e5?limit=2","status":"200"}
Oct 23 16:09:08 172.18.0.1 clair[9892]: {"Event":"Handled HTTP request","Level":"info","Location":"router.go:57","Time":"2017-10-23 08:09:08.045305","elapsed time":828889,"method":"DELETE","remote addr":"172.19.0.5:52213","request uri":"/v1/notifications

**Comment by reasonerjt** [comment]
@Yeefoner The log content in your description doesn't seem problematic.   Are all of the 9.7 G log about notifications?  Could you gzip your log files and upload to a storage so we can check?

**Comment by Yeefoner** [comment]
@reasonerjt 
The log.gzip sent emails to jiangd@vmware.com

**Comment by reasonerjt** [comment]
@Yeefoner I didn't receive your Email, probably filtered out due to the large size, could you upload to some 3rd party storage (Google, Baidu) and share it to me?

**Comment by Yeefoner** [comment]
@reasonerjt 链接: https://pan.baidu.com/s/1mhVsDss 密码: q8fw

**Comment by reasonerjt** [comment]
@Yeefoner 
I see a lot of errors connecting "100.126.153.199:8089" and got connection refused.

Like this: 
```
Oct 23 08:00:00 172.18.0.1 clair[4915]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2017-10-23 00:00:00.113550","data feed name":"2013","error":"Get http://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2013.meta: proxyconnect tcp: dial tcp 100.126.153.199:8089: getsockopt: connection refused"}
```
Seems Clair's code has an issue that it keep retrying when encounter unexpected error.
We will refine the strategy to package log files to mitigate the problem but this is essentially a problem in your env.
