### ISSUE TITLE
Send email failed on password reset: 553 Invalid email address

### ISSUE THREAD

**Issue by totojack** [vmware/harbor#3435]
Hi.

We have problems on sending password reset emails. Test mail server from ui backend returns correct answer, so smtp connection configurations are correct, and also aws ses smtp service is already configured for sending emails using this domain sender. The log error is:

[ERROR] [base.go:179]: Send email failed: 553 <myemail <myemail@mydomain.com> Invalid email address.

Could it be the "<" symbol before "myemail" value that I can see into errog log the problem? 

These are some 

- Harbor release is vmware/harbor-adminserver:v1.2.0-rc3.

- Version of docker engine and docker-compose.

Docker version 17.03.2-ce, build 7392c3b/17.03.2-ce

docker-compose version 1.13.0, build 1719ceb

- Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.

(...)
#Email account settings for sending out password resetting emails.

#Email server uses the given username and password to authenticate on TLS connections to host and act as identity.
#Identity left blank to act as username.
email_identity =

email_server = email-smtp.eu-west-1.amazonaws.com
email_server_port = 587
email_username = awsuser
email_password = awspwd
email_from = myemail <myemail@mydomain.com>
email_ssl = false
(...)

- Log files, you can get them by package the /var/log/harbor/ .
==> ui.log <==
Oct 23 08:51:28 ip-172-20-0-1.eu-west-1.compute.internal ui[16152]: 2017-10-23T08:51:28Z [DEBUG] [security.go:283]: user information is nil

==> adminserver.log <==
Oct 23 08:51:28 ip-172-20-0-1.eu-west-1.compute.internal adminserver[16152]: 172.20.0.6 - - [23/Oct/2017:08:51:28 +0000] "GET /api/configurations HTTP/1.1" 200 1040

==> ui.log <==
Oct 23 08:51:28 ip-172-20-0-1.eu-west-1.compute.internal ui[16152]: 2017-10-23T08:51:28Z [DEBUG] [security.go:296]: using local database project manager
Oct 23 08:51:28 ip-172-20-0-1.eu-west-1.compute.internal ui[16152]: 2017-10-23T08:51:28Z [DEBUG] [security.go:298]: creating local database security context...
Oct 23 08:51:28 ip-172-20-0-1.eu-west-1.compute.internal ui[16152]: 2017/11/23 08:51:28 #033[1;34m[router.go:829][D] | GET        | /harbor/sign-in                          | 2.211271ms       | match      | /harbor/sign-in                          | #033[0m

==> proxy.log <==
Oct 23 08:51:28 ip-172-20-0-1.eu-west-1.compute.internal proxy[16152]: 172.20.0.1 - "GET /harbor/sign-in HTTP/1.0" 200 384 "-" "Sensu-HTTP-Check" 0.003 0.003 .

==> ui.log <==
Oct 23 08:51:30 ip-172-20-0-1.eu-west-1.compute.internal ui[16152]: 2017-10-23T08:51:30Z [DEBUG] [security.go:283]: user information is nil
Oct 23 08:51:30 ip-172-20-0-1.eu-west-1.compute.internal ui[16152]: 2017-10-23T08:51:30Z [DEBUG] [security.go:296]: using local database project manager
Oct 23 08:51:30 ip-172-20-0-1.eu-west-1.compute.internal ui[16152]: 2017-10-23T08:51:30Z [DEBUG] [security.go:298]: creating local database security context...
Oct 23 08:51:30 ip-172-20-0-1.eu-west-1.compute.internal ui[16152]: 2017-10-23T08:51:30Z [DEBUG] [mail.go:92]: establishing TCP connection with email-smtp.eu-west-1.amazonaws.com:587 ...
Oct 23 08:51:30 ip-172-20-0-1.eu-west-1.compute.internal ui[16152]: 2017-10-23T08:51:30Z [DEBUG] [mail.go:117]: creating SMTP client for email-smtp.eu-west-1.amazonaws.com ...
Oct 23 08:51:30 ip-172-20-0-1.eu-west-1.compute.internal ui[16152]: 2017-10-23T08:51:30Z [DEBUG] [mail.go:126]: switching the connection with email-smtp.eu-west-1.amazonaws.com:587 to SSL/TLS ...
Oct 23 08:51:30 ip-172-20-0-1.eu-west-1.compute.internal ui[16152]: 2017-10-23T08:51:30Z [DEBUG] [mail.go:139]: authenticating the client...
Oct 23 08:51:30 ip-172-20-0-1.eu-west-1.compute.internal ui[16152]: 2017-10-23T08:51:30Z [DEBUG] [mail.go:150]: create smtp client successfully
Oct 23 08:51:30 ip-172-20-0-1.eu-west-1.compute.internal ui[16152]: 2017-10-23T08:51:30Z [ERROR] [base.go:179]: Send email failed: 553 <myname <myname@mydomain.com> Invalid email address.

==> proxy.log <==
Oct 23 08:51:30 ip-172-20-0-1.eu-west-1.compute.internal proxy[16152]: 172.20.0.1 - "GET /sendEmail?email=usermail@mydomain.com HTTP/1.0" 500 17 "https://dockerhubdomain/harbor/sign-in" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" 0.098 0.098 .

Thanks.

**Comment by ywk253100** [comment]
Using `email_from = myemail <myemail@mydomain.com>` or `email_from = myemail@mydomain.com`

**Comment by totojack** [comment]
Leaving only the email into email_from field solved the problem. Thanks.
