### ISSUE TITLE
Notary signer fails in VIC Appliance

### ISSUE THREAD

**Issue by andrewtchin** [vmware/harbor#3440]
When deploying latest build https://storage.googleapis.com/vic-product-ova-builds/vic-2161-v1.2.0-rc1-132-g89afccc.ova

`journalctl -u harbor`
```
Oct 23 14:43:46 localhost.localdomain start_harbor.sh[2403]: notary-server exited with code 1
```

notary-signer.log
```
Oct 23 14:46:50 172.18.0.1 notary-signer[410]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Oct 23 14:46:51 172.18.0.1 notary-signer[410]: notarysigner database failed to come up within 30 seconds
```

**Comment by reasonerjt** [comment]
@morris-jason Thanks for the information.

Could be related to the recent change in docker image, but interesting it works in our CI in drone, I'll investigate.

**Comment by reasonerjt** [comment]
@andrewtchin 
I tried to deploy the .ova but saw error:
```
root@localhost [ ~ ]# systemctl status harbor_startup.service
● harbor_startup.service - Harbor Startup Configuration
   Loaded: loaded (/usr/lib/systemd/system/harbor_startup.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2017-10-24 06:19:04 UTC; 5s ago
     Docs: http://github.com/vmware/harbor
  Process: 965 ExecStartPre=/usr/bin/bash /etc/vmware/harbor/configure_harbor.sh (code=exited, status=1/FAILURE)

Oct 24 06:19:04 localhost.localdomain systemd[1]: Starting Harbor Startup Configuration...
Oct 24 06:19:04 localhost.localdomain bash[965]: cp: cannot stat ‘/data/admiral/cert/ca.crt’: No such file or directory
Oct 24 06:19:04 localhost.localdomain systemd[1]: harbor_startup.service: Control process exited, code=exited status=1
Oct 24 06:19:04 localhost.localdomain systemd[1]: Failed to start Harbor Startup Configuration.
Oct 24 06:19:04 localhost.localdomain systemd[1]: harbor_startup.service: Unit entered failed state.
Oct 24 06:19:04 localhost.localdomain systemd[1]: harbor_startup.service: Failed with result ‘exit-code’.
```

**Comment by reasonerjt** [comment]
@andrewtchin Did you see this issue in fresh install or upgrade?

**Comment by andrewtchin** [comment]
@reasonerjt it was in a fresh install of the linked build. What version of OVA did you deploy? We fixed an issue where the `ca.crt` file was not present a while ago and I haven't seen that in new builds. Could you provide the output of `ls -al /data/admiral/cert`?

**Comment by reasonerjt** [comment]
@andrewtchin doesn't matter, I fixed the issue, pushed a new mariadb image to docker hub and verified on the env you sent me.
It's a permission issue after moving from debian to photon.
The latest build should be taking the new image and the problem should be fixed.

**Comment by andrewtchin** [comment]
Cool thanks, once the new offline installer is uploaded you can pick up an OVA build from after that to verify

**Comment by reasonerjt** [comment]
Unfortunately I see some issues while verifying it on .ova, I'll fix it in my tomorrow, grab a new .ova and verify.

**Comment by reasonerjt** [comment]
Verified in build:
https://storage.googleapis.com/vic-product-ova-builds/vic-2226-v1.2.0-rc1-142-g26e46be.ova
