### ISSUE TITLE
[Customer report] UI enhancement, the access level of the project is a little misleading.

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#3443]
When create a project the current behavior is:
the check box label will change after click it. Some user suggested the label should be fixed to to the checkbox
<img width="579" alt="screen shot 2017-10-24 at 10 25 36 am" src="https://user-images.githubusercontent.com/1715683/31922172-25157490-b8a6-11e7-9e6d-52a291e08af7.png">

**Comment by lweitzman** [comment]
agree this is confusing the way its working. the label should say "Access level   [ ] Public" and not change depending on the state of the checkbox

**Comment by steven-zou** [comment]
@pengpengshui 

Please refer the updated design provided by @lweitzman  https://vmware.invisionapp.com/share/F6E331FJT#/screens/258627798.
