### ISSUE TITLE
A suggestion about finding useless repositories and deleting them

### ISSUE THREAD

**Issue by moooofly** [vmware/harbor#3456]
From `swagger.yaml`, I find GET `/repositories/top` API to get public repositories which are accessed **most**.

And I need such a feature that getting public repositories which are accessed **least**. So I can delete them manually at least.

Maybe LRU strategy is OK for me too.

tks in advance.

**Comment by steven-zou** [comment]
The same requirement with #4209, let's use that one to track the requirement.

Close this one.
