### ISSUE TITLE
ui missing port in address

### ISSUE THREAD

**Issue by Yonnug** [vmware/harbor#3458]
ui[3054]: 2017-10-25T11:44:20Z [ERROR] [utils.go:102]: failed to connect to tcp://registry.xx.com, retry after 2 seconds :dial tcp: missing port in address

**Comment by wy65701436** [comment]
Please provide the harbor.cfg and logs under /var/log/harbor/...

**Comment by Yonnug** [comment]
build version: harbor.v1.2.0

docker-compose.yml:
version: '2'
services:
  adminserver:
    image: vmware/harbor-adminserver:v1.2.0
    container_name: harbor-adminserver
    env_file:
      - ./common/config/adminserver/env
    restart: always
    volumes:
      - /data/config/:/etc/adminserver/config/:z
      - /data/secretkey:/etc/adminserver/key:z
      - /data/:/data/:z
    network_mode: "host"
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:514"
        tag: "adminserver"
  ui:
    image: vmware/harbor-ui:v1.2.0
    container_name: harbor-ui
    env_file:
      - ./common/config/ui/env
    restart: always
    volumes:
      - ./common/config/ui/app.conf:/etc/ui/app.conf:z
      - ./common/config/ui/private_key.pem:/etc/ui/private_key.pem:z
      - /data/secretkey:/etc/ui/key:z
      - /data/ca_download/:/etc/ui/ca/:z
      - /data/psc/:/etc/ui/token/:z
    network_mode: "host"
    depends_on:
      - adminserver
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:514"
        tag: "ui"
  jobservice:
    image: vmware/harbor-jobservice:v1.2.0
    container_name: harbor-jobservice
    env_file:
      - ./common/config/jobservice/env
    restart: always
    volumes:
      - /data/job_logs:/var/log/jobs:z
      - ./common/config/jobservice/app.conf:/etc/jobservice/app.conf:z
      - /data/secretkey:/etc/jobservice/key:z
    network_mode: "host"
    depends_on:
      - ui
      - adminserver
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:514"
        tag: "jobservice"

harbor.cfg:
hostname = reg.xx.com
ui_url_protocol = http
db_password = 123456
max_job_workers = 3
customize_crt = on
ssl_cert = /data/cert/server.crt
ssl_cert_key = /data/cert/server.key
secretkey_path = /data
admiral_url = NA
clair_db_password = password
email_identity =
email_server = smtp.mydomain.com
email_server_port = 25
email_username = sample_admin@mydomain.com
email_password = abc
email_from = admin <sample_admin@mydomain.com>
email_ssl = false
harbor_admin_password = Harbor12345
auth_mode = db_auth
ldap_url = ldaps://ldap.mydomain.com
ldap_basedn = ou=people,dc=mydomain,dc=com
ldap_uid = uid
ldap_scope = 3
ldap_timeout = 5
self_registration = on
token_expiration = 30
project_creation_restriction = everyone
verify_remote_cert = off

common/adminserver/env:
LOG_LEVEL=debug
EXT_ENDPOINT=http://reg.xx.com
AUTH_MODE=db_auth
SELF_REGISTRATION=on
LDAP_URL=ldaps://ldap.mydomain.com
LDAP_SEARCH_DN=
LDAP_SEARCH_PWD=
LDAP_BASE_DN=ou=people,dc=mydomain,dc=com
LDAP_FILTER=
LDAP_UID=uid
LDAP_SCOPE=3
LDAP_TIMEOUT=5
DATABASE_TYPE=mysql
MYSQL_HOST=10.0.0.1
MYSQL_PORT=3306
MYSQL_USR=harbor
MYSQL_PWD=123456
MYSQL_DATABASE=registry
REGISTRY_URL=http://registry.xx.com:5000
TOKEN_SERVICE_URL=http://harbor.xx.com:8080/service/token
EMAIL_HOST=smtp.mydomain.com
EMAIL_PORT=25
EMAIL_USR=sample_admin@mydomain.com
EMAIL_PWD=abc
EMAIL_SSL=false
EMAIL_FROM=admin <sample_admin@mydomain.com>
EMAIL_IDENTITY=
HARBOR_ADMIN_PASSWORD=Harbor12345
PROJECT_CREATION_RESTRICTION=everyone
VERIFY_REMOTE_CERT=off
MAX_JOB_WORKERS=3
UI_SECRET=P8hSgsBKEPjugsHy
JOBSERVICE_SECRET=0uU6Jk4DnmAa0WEo
TOKEN_EXPIRATION=30
CFG_EXPIRATION=5
GODEBUG=netdns=cgo

ui/env:
LOG_LEVEL=debug
CONFIG_PATH=/etc/ui/app.conf
UI_SECRET=P8hSgsBKEPjugsHy
JOBSERVICE_SECRET=0uU6Jk4DnmAa0WEo
ADMIN_SERVER_URL=http://harbor.xx.com:8091

ui/app.conf:
appname = Harbor
runmode = dev
enablegzip = true

[dev]
httpport = 8080

jobservice/env:
LOG_LEVEL=debug
CONFIG_PATH=/etc/jobservice/app.conf
UI_SECRET=P8hSgsBKEPjugsHy
JOBSERVICE_SECRET=0uU6Jk4DnmAa0WEo
ADMIN_SERVER_URL=http://harbor.xx.com:8091

jobservice/app.conf:
appname = jobservice
runmode = dev

[dev]
httpport = 8090

registry/config.yml:
version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: /storage
    maintenance:
        uploadpurging:
            enabled: false
    delete:
        enabled: true
http:
    addr: :5000
    secret: placeholder
    debug:
        addr: localhost:5001
auth:
  token:
    issuer: harbor-token-issuer
    realm: http://reg.xxx.com/service/token
    rootcertbundle: /etc/registry/root.crt
    service: harbor-registry

notifications:
  endpoints:
      - name: harbor
        disabled: false
        url: http://harbor.xx.com:8080/service/notifications
        timeout: 3000ms
        threshold: 5
        backoff: 1s

**Comment by ywk253100** [comment]
Refer to https://github.com/vmware/harbor/blob/master/docs/installation_guide.md#configuring-harbor-listening-on-a-customized-port to customize the listening ports.
