### ISSUE TITLE
Notary repo moving

### ISSUE THREAD

**Issue by endophage** [vmware/harbor#3460]
Hi. Notary has been accepted in to CNCF and will be moving from its current location to `GitHub.com/theupdateframework/notary`. As a downstream consumer you may want to update any references to use the new location. 

I'm aiming to complete the move in the next 48 hours including updating all the internal imports. A redirect will be in place and you appear to have pinned to a specific commit for your go vendoring. However I noticed in [this](https://github.com/vmware/harbor/blob/ddaad98526dbd708ee95d09a04ea0a4f278985a1/make/photon/notary/builder_public#L38) location you appear to be cloning the head of master before building the server and signer binaries, which is likely to break after the move due to the internal imports changing from `github.com/docker/notary/...` to `github.com/theupdateframework/notary/...`

**Comment by wy65701436** [comment]
I will do it once get the valid location of notary.  Thanks @endophage

**Comment by Evalle** [comment]
Hey, folks, I fixed this link in my code and I was thinking that it can be useful for everyone, so I created a PR ^ I hope it's OK with you @warthog9

**Comment by wy65701436** [comment]
@Evalle, Please rewords the commit message and squash it, then I will merge your PR.

**Comment by Evalle** [comment]
@wy65701436  Hi, is rewording from `ISSUE-3460 - Fix link to Notary repo` to `ISSUE-3460 - Fixes link to Notary repo` looking good for you?

**Comment by wy65701436** [comment]
"Fix link to Notary repo" is more reasonable.

**Comment by Evalle** [comment]
Ok, thanks, will reword it that way.

**Comment by Evalle** [comment]
fixed https://github.com/vmware/harbor/pull/3489

**Comment by wy65701436** [comment]
close it as https://github.com/vmware/harbor/pull/3489
