### ISSUE TITLE
Will OAuth be supported? 

### ISSUE THREAD

**Issue by acearth** [vmware/harbor#3468]
Currently, 3rd-party login is only supported for LDAP. 

But many services are using OAuth protocol to login from foreign services. So, will Harbor support OAuth or other similar 3rd login methods? 

I'd like to provide OAuth solution for Harbor, but I'm not sure can VMware offical accept OAuth request.  So I wait for your reply. Thank you.

**Comment by reasonerjt** [comment]
There is a WIP to integrate with UAA which calls UAA's oauth token api for authentication, we'll introduce more sophisticated SSO scenario if needed.

**Comment by acearth** [comment]
I heard many famous companies using OAuth as well as many startups supports OAuth.
So I think OAuth is really needed and helpful for open and connection. Please think about add this feature. If necessary, I can help to implement this feature.

**Comment by reasonerjt** [comment]
@acearth
By "support OAuth" it's not clear what use case you plan to address. 

If you have a use case that requires OAuth go ahead and implement it, we can later review and see if it can be merged upstream.

**Comment by acearth** [comment]
Thank you @reasonerjt .  By saying "Support OAuth", I mean one application can provide one callback URL for OAuth, and if authentication server called the callback URL with right  parameters, this application will treat the user( related information are provided in parameters of callback URL) as signed in. 

I maybe propose one solution in near future if I have some time to do it.  
Thanks for your kindly reply.

**Comment by dongcj** [comment]
I think OAuth is **really** needed, too  @acearth

**Comment by YunSangJun** [comment]
I am also looking forward the feature can be intergrated to OAuth.

**Comment by clouderati** [comment]
Keeping tabs on this particular feature request in https://github.com/goharbor/harbor/issues/4616.
