### ISSUE TITLE
Does the harbor-db-migrator tool support the upgrading of Harbor from v1.1.2 to v1.2.0?

### ISSUE THREAD

**Issue by Lynzabo** [vmware/harbor#3469]
I know that the data merge mirror supports the upgrading of Harbor from v1.1.2 to v1.2.0, but is it supported by the opposite function? If I have an application scenario, if Harbor is running properly in the 1.2.0 version, I'm going to roll it back to the 1.1.2 version, and how do I use the data merge mirror?
```shell
docker run -ti --rm -e DB_USR=root -e DB_PWD=xxxx -v /data/database:/var/lib/mysql vmware/harbor-db-migrator up 0.4.0
```
I tried to set the parameter after the up command to 0.4.0, but it went wrong and the database didn't change.

**Comment by wy65701436** [comment]
Unfortunately, the migrator doesn't support downgrade, you have to do it manually. Why do you want to downgrade?

**Comment by Lynzabo** [comment]
I now have several sets of Harbor environment needs to be upgraded, but I am a little worried about what compatibility issues will be.

**Comment by wy65701436** [comment]
What version are you using now? And the deploy mode?
There is no compatibility issue for image replication per our testing result from 0.4.5. But if you call the Harbor API, it has.

**Comment by Lynzabo** [comment]
We are now using version 1.1.2, using docker-compose deployment.

**Comment by wy65701436** [comment]
We do not have any open compatibility issue about 1.1.2 so far. Just refer to the migration guide for details.

**Comment by Lynzabo** [comment]
Thank you very much!
