### ISSUE TITLE
All POST requests have to contain header "Content-Type: application/json"

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#3488]
In an attempt to mitigate XSRF, a filter is added to enforce that all POST requests have to have "application/json" header.

https://github.com/vmware/harbor/pull/3483

In the CI a few failures've been discovered:
https://ci.vcna.io/vmware/harbor/958
relevant log messages:
```
......
Oct 30 07:16:30 172.19.0.1 proxy[179]: 172.19.0.1 - "POST /api/targets HTTP/1.1" 415 0 "http://localhost/harbor/projects/9/replications" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/58.0.3029.110 Safari/537.36" 0.001 0.001 .
......
Oct 30 07:18:19 172.19.0.1 proxy[179]: 172.19.0.1 - "POST /api/repositories/project101509347812/hello-world/tags/latest/scan HTTP/1.1" 415 0 "http://localhost/harbor/projects/10/repositories" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/58.0.3029.110 Safari/537.36" 0.001 0.001 .
```

In addition to these 2 requests please also make sure that ALL requests comply with this rule.

**Comment by reasonerjt** [comment]
Let's push the commit of UI to the same PR to make sure the CI will pass
```
Add more commits by pushing to the xsrf-filter branch on reasonerjt/harbor.
```

**Comment by steven-zou** [comment]
@pengpengshui Please help to add the missing 'content-type' header.

**Comment by YEXINGZHE54** [comment]
sorry, even when I upgrade to v1.5.1, the http header Content-Type still remains in "text/plain", when the browser make requesting POST /api/targets.  This seems that the ui client is not containing the Content-Type header?
