### ISSUE TITLE
"vmware/harbor-clarity-ui-builder[:tag]" 镜像名不合法

### ISSUE THREAD

**Issue by Lemon-Orange** [vmware/harbor#3493]
[root@localhost harbor]# make install

Note: golang version: 1.8.3

Note: docker version: 1.12.6

Note: docker-compose version: 1.16.1
compiling binary for clarity ui...
/usr/bin/docker-current: Error parsing reference: "vmware/harbor-clarity-ui-builder[:tag]" is not a valid repository/tag.
See '/usr/bin/docker-current run --help'.
make: *** [compile_clarity] 错误 125

**Comment by Lemon-Orange** [comment]
对应Makefile中第100行，tag是什么
100 CLARITYIMAGE=vmware/harbor-clarity-ui-builder[:tag]

**Comment by wy65701436** [comment]
please read the compile guid carefully.
