### ISSUE TITLE
Add LDAP group search configuration

### ISSUE THREAD

**Issue by stonezdj** [vmware/harbor#3507]
In order to assign LDAP group a harbor project role, need to search LDAP group. need to add the following parameters.

1 . LDAP base DN: the base DN from which to lookup group in LDAP 
2. LDAP filter: the filter to search group 
3. LDAP GroupID: the attribute to match the group name in harbor.
4. LDAP scope: the scope for search groups

**Comment by steven-zou** [comment]
Code ready, waiting for merging. move to next SP as placeholder.

**Comment by stonezdj** [comment]
Sample config in harbor.cfg
------------------------------
#The base dn from which to lookup a group in LDAP/AD    
ldap_group_basedn = ou=group,dc=mydomain,dc=com 
#filter to search LDAP/AD group  
ldap_group_filter = objectclass=group
#The attribute used to name a LDAP/AD group, it could be cn, name 
ldap_group_gid = cn
#The scope to search for ldap groups. 0-LDAP_SCOPE_BASE, 1-LDAP_SCOPE_ONELEVEL, 2-LDAP_SCOPE_SUBTREE
ldap_group_scope = 2
