### ISSUE TITLE
Broken GCS Builds

### ISSUE THREAD

**Issue by morris-jason** [vmware/harbor#3511]
Harbor builds to gcs are only 106.kb. They contain the archive file structure but no image contents.
See https://storage.googleapis.com/harbor-builds/harbor-offline-installer-v1.2.0-137-gf7b4218.tgz

**Comment by wy65701436** [comment]
I will have a check

**Comment by reasonerjt** [comment]
@wy65701436 the make should fail instead of uploading a incomplete package to GCS.

**Comment by wy65701436** [comment]
Fixed. please use the latest build to package OVA.

**Comment by morris-jason** [comment]
@wy65701436 Thanks!
