### ISSUE TITLE
 signature function can not be used

### ISSUE THREAD

**Issue by jiananjiang** [vmware/harbor#3516]
I was centos7, my signature function can not be used, notary the two containers can not get up, view the log display:
[root@centjiang 2017-11-01]# vim notary-server.log
Nov  1 13:37:54 bogon notary-server[2523]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  1 13:37:55 bogon notary-server[2523]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  1 13:37:56 bogon notary-server[2523]: notaryserver database failed to come up within 30 seconds

[root@centjiang 2017-11-01]# vim notary-signer.log

Nov  1 13:37:53 bogon notary-signer[2523]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  1 13:37:55 bogon notary-signer[2523]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  1 13:37:57 bogon notary-signer[2523]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  1 13:38:00 bogon notary-signer[2523]: notarysigner database failed to come up within 30 seconds

**Comment by jiananjiang** [comment]
please tell me what should I do? thanks~

**Comment by reasonerjt** [comment]
looks like a permission issue, could you try on other distro such as ubuntu?

Could you check the log of notary-db?

**Comment by jiananjiang** [comment]
but Our company uses centos7,

[root@centjiang 2017-11-01]# vim notary-db.log 

Nov  1 15:11:39 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:39 140251871455168 [Note] InnoDB: The InnoDB memory heap is disabled
Nov  1 15:11:39 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:39 140251871455168 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
Nov  1 15:11:39 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:39 140251871455168 [Note] InnoDB: Memory barrier is not used
Nov  1 15:11:39 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:39 140251871455168 [Note] InnoDB: Compressed tables use zlib 1.2.8
Nov  1 15:11:39 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:39 140251871455168 [Note] InnoDB: Using Linux native AIO
Nov  1 15:11:39 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:39 140251871455168 [Note] InnoDB: Using SSE crc32 instructions
Nov  1 15:11:39 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:39 140251871455168 [Note] InnoDB: Initializing buffer pool, size = 256.0M
Nov  1 15:11:39 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:39 140251871455168 [Note] InnoDB: Completed initialization of buffer pool
Nov  1 15:11:40 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:40 140251871455168 [Note] InnoDB: Highest supported file format is Barracuda.
Nov  1 15:11:40 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:40 140251871455168 [Note] InnoDB: The log sequence numbers 1617375 and 1617375 in ibdata files do not match the log sequence number 1617395 in the ib_logfiles!
Nov  1 15:11:40 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:40 140251871455168 [Note] InnoDB: Database was not shutdown normally!
Nov  1 15:11:40 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:40 140251871455168 [Note] InnoDB: Starting crash recovery.
Nov  1 15:11:40 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:40 140251871455168 [Note] InnoDB: Reading tablespace information from the .ibd files...
Nov  1 15:11:40 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:40 140251871455168 [Note] InnoDB: Restoring possible half-written data pages
Nov  1 15:11:40 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:40 140251871455168 [Note] InnoDB: from the doublewrite buffer...
Nov  1 15:11:40 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:40 140251871455168 [Note] InnoDB: 128 rollback segment(s) are active.
Nov  1 15:11:40 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:40 140251871455168 [Note] InnoDB: Waiting for purge to start
Nov  1 15:11:41 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:41 140251871455168 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.26-76.0 started; log sequence number 1617395
Nov  1 15:11:41 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:41 140251087472384 [Note] InnoDB: Dumping buffer pool(s) not yet started
Nov  1 15:11:42 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:42 140251871455168 [Note] Plugin 'FEEDBACK' is disabled.
Nov  1 15:11:42 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:42 140251871455168 [Note] Recovering after a crash using tc.log
Nov  1 15:11:42 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:42 140251871455168 [Note] Starting crash recovery...
Nov  1 15:11:42 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:42 140251871455168 [Note] Crash recovery finished.
Nov  1 15:11:43 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:43 140251871455168 [Note] Server socket created on IP: '::'.
Nov  1 15:11:45 172.19.0.1 notary-db[7610]: 2017-11-01  7:11:45 140251871455168 [Note] mysqld: ready for connections.
Nov  1 15:11:45 172.19.0.1 notary-db[7610]: Version: '10.1.10-MariaDB-1~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution

**Comment by jiananjiang** [comment]
@reasonerjt 

thanks,but Our company uses centos7,and This two containers are in a restart state ,

[root@centjiang 2017-11-01]# vim notary-db.log

Nov 1 15:11:39 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:39 140251871455168 [Note] InnoDB: The InnoDB memory heap is disabled
Nov 1 15:11:39 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:39 140251871455168 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
Nov 1 15:11:39 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:39 140251871455168 [Note] InnoDB: Memory barrier is not used
Nov 1 15:11:39 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:39 140251871455168 [Note] InnoDB: Compressed tables use zlib 1.2.8
Nov 1 15:11:39 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:39 140251871455168 [Note] InnoDB: Using Linux native AIO
Nov 1 15:11:39 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:39 140251871455168 [Note] InnoDB: Using SSE crc32 instructions
Nov 1 15:11:39 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:39 140251871455168 [Note] InnoDB: Initializing buffer pool, size = 256.0M
Nov 1 15:11:39 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:39 140251871455168 [Note] InnoDB: Completed initialization of buffer pool
Nov 1 15:11:40 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:40 140251871455168 [Note] InnoDB: Highest supported file format is Barracuda.
Nov 1 15:11:40 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:40 140251871455168 [Note] InnoDB: The log sequence numbers 1617375 and 1617375 in ibdata files do not match the log sequence number 1617395 in the ib_logfiles!
Nov 1 15:11:40 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:40 140251871455168 [Note] InnoDB: Database was not shutdown normally!
Nov 1 15:11:40 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:40 140251871455168 [Note] InnoDB: Starting crash recovery.
Nov 1 15:11:40 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:40 140251871455168 [Note] InnoDB: Reading tablespace information from the .ibd files...
Nov 1 15:11:40 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:40 140251871455168 [Note] InnoDB: Restoring possible half-written data pages
Nov 1 15:11:40 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:40 140251871455168 [Note] InnoDB: from the doublewrite buffer...
Nov 1 15:11:40 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:40 140251871455168 [Note] InnoDB: 128 rollback segment(s) are active.
Nov 1 15:11:40 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:40 140251871455168 [Note] InnoDB: Waiting for purge to start
Nov 1 15:11:41 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:41 140251871455168 [Note] InnoDB: Percona XtraDB (http://www.percona.com) 5.6.26-76.0 started; log sequence number 1617395
Nov 1 15:11:41 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:41 140251087472384 [Note] InnoDB: Dumping buffer pool(s) not yet started
Nov 1 15:11:42 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:42 140251871455168 [Note] Plugin 'FEEDBACK' is disabled.
Nov 1 15:11:42 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:42 140251871455168 [Note] Recovering after a crash using tc.log
Nov 1 15:11:42 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:42 140251871455168 [Note] Starting crash recovery...
Nov 1 15:11:42 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:42 140251871455168 [Note] Crash recovery finished.
Nov 1 15:11:43 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:43 140251871455168 [Note] Server socket created on IP: '::'.
Nov 1 15:11:45 172.19.0.1 notary-db[7610]: 2017-11-01 7:11:45 140251871455168 [Note] mysqld: ready for connections.
Nov 1 15:11:45 172.19.0.1 notary-db[7610]: Version: '10.1.10-MariaDB-1~jessie' socket: '/var/run/mysqld/mysqld.sock' port: 3306 mariadb.org binary distribution

**Comment by reasonerjt** [comment]
@jiananjiang 
See the timestamps, the notary-db log and notary-server log  are generated in different time?

**Comment by jiananjiang** [comment]
@ reasonerjt  
Sorry, it's my fault, I have a problem with it. I tried you said ubuntu, container can be activated, but centos not, please help us to look at the log:

[root@centjiang 2017-11-03]# vim   notary-server.log 

Nov  3 13:51:38 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:39 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:40 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:41 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:43 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:44 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:46 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:47 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:48 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:50 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:51 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:52 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:55 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:57 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:59 bogon notary-server[2585]: message repeated 2 times: [ waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.]
Nov  3 13:52:00 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:52:01 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:52:03 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:52:08 bogon notary-server[2585]: message repeated 4 times: [ waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.]
Nov  3 13:52:09 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:52:11 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:52:12 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:52:13 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:52:14 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:52:15 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:52:16 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:52:17 bogon notary-server[2585]: notaryserver database failed to come up within 30 seconds


[root@centjiang 2017-11-03]# vim   notary-signer.log 

Nov  3 13:51:05 bogon notary-signer[2585]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  3 13:51:08 bogon notary-signer[2585]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  3 13:51:09 bogon notary-signer[2585]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  3 13:51:10 bogon notary-signer[2585]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  3 13:51:37 bogon notary-signer[2585]: message repeated 20 times: [ waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.]
Nov  3 13:51:40 bogon notary-signer[2585]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  3 13:51:41 bogon notary-signer[2585]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  3 13:51:42 bogon notary-signer[2585]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  3 13:51:43 bogon notary-signer[2585]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  3 13:51:46 bogon notary-signer[2585]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  3 13:51:48 bogon notary-signer[2585]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  3 13:51:49 bogon notary-signer[2585]: notarysigner database failed to come up within 30 seconds
Nov  3 13:52:08 bogon notary-signer[2585]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.


[root@centjiang 2017-11-03]# vim notary-db.log 

Nov  3 13:49:45 bogon notary-db[2585]: 2017-11-03  5:49:45 139797936531200 [Note] mysqld: Normal shutdown
Nov  3 13:49:45 bogon notary-db[2585]:
Nov  3 13:49:46 bogon notary-db[2585]: 2017-11-03  5:49:46 139797936531200 [Note] Event Scheduler: Purging the queue. 0 events
Nov  3 13:49:46 bogon notary-db[2585]: 2017-11-03  5:49:46 139797133747968 [Note] InnoDB: FTS optimize thread exiting.
Nov  3 13:49:46 bogon notary-db[2585]: 2017-11-03  5:49:46 139797936531200 [Note] InnoDB: Starting shutdown...
Nov  3 13:49:48 bogon notary-db[2585]: 2017-11-03  5:49:48 139797936531200 [Note] InnoDB: Shutdown completed; log sequence number 1617471
Nov  3 13:49:48 bogon notary-db[2585]: 2017-11-03  5:49:48 139797936531200 [Note] mysqld: Shutdown complete
Nov  3 13:49:48 bogon notary-db[2585]:
Nov  3 13:50:36 bogon notary-db[2585]: 2017-11-03  5:50:36 139965021263808 [Note] mysqld (mysqld 10.1.10-MariaDB-1~jessie) starting as process 1 ...
Nov  3 13:50:37 bogon notary-db[2585]: 2017-11-03  5:50:37 139965021263808 [Note] InnoDB: Using mutexes to ref count buffer pool pages
Nov  3 13:50:37 bogon notary-db[2585]: 2017-11-03  5:50:37 139965021263808 [Note] InnoDB: The InnoDB memory heap is disabled
Nov  3 13:50:37 bogon notary-db[2585]: 2017-11-03  5:50:37 139965021263808 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
Nov  3 13:50:37 bogon notary-db[2585]: 2017-11-03  5:50:37 139965021263808 [Note] InnoDB: Memory barrier is not used
Nov  3 13:50:37 bogon notary-db[2585]: 2017-11-03  5:50:37 139965021263808 [Note] InnoDB: Compressed tables use zlib 1.2.8
Nov  3 13:50:37 bogon notary-db[2585]: 2017-11-03  5:50:37 139965021263808 [Note] InnoDB: Using Linux native AIO
Nov  3 13:50:37 bogon notary-db[2585]: 2017-11-03  5:50:37 139965021263808 [Note] InnoDB: Using SSE crc32 instructions
Nov  3 13:50:37 bogon notary-db[2585]: 2017-11-03  5:50:37 139965021263808 [Note] InnoDB: Initializing buffer pool, size = 256.0M
Nov  3 13:50:37 bogon notary-db[2585]: 2017-11-03  5:50:37 139965021263808 [Note] InnoDB: Completed initialization of buffer pool
Nov  3 13:50:37 bogon notary-db[2585]: 2017-11-03  5:50:37 139965021263808 [Note] InnoDB: Highest supported file format is Barracuda.
Nov  3 13:50:38 bogon notary-db[2585]: 2017-11-03  5:50:38 139965021263808 [Note] InnoDB: 128 rollback segment(s) are active.
Nov  3 13:50:38 bogon notary-db[2585]: 2017-11-03  5:50:38 139965021263808 [Note] InnoDB: Waiting for purge to start
Nov  3 13:50:38 bogon notary-db[2585]: 2017-11-03  5:50:38 139965021263808 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.26-76.0 started; log sequence number 1617471
Nov  3 13:50:38 bogon notary-db[2585]: 2017-11-03  5:50:38 139964234827520 [Note] InnoDB: Dumping buffer pool(s) not yet started
Nov  3 13:50:38 bogon notary-db[2585]: 2017-11-03  5:50:38 139965021263808 [Note] Plugin 'FEEDBACK' is disabled.
Nov  3 13:50:38 bogon notary-db[2585]: 2017-11-03  5:50:38 139965021263808 [Note] Server socket created on IP: '::'.
Nov  3 13:50:38 bogon notary-db[2585]: 2017-11-03  5:50:38 139965021263808 [Note] mysqld: ready for connections.
Nov  3 13:50:38 bogon notary-db[2585]: Version: '10.1.10-MariaDB-1~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution

**Comment by jiananjiang** [comment]
@ reasonerjt  
Sorry, it's my fault, I have a problem with it. I tried you said ubuntu, container can be activated, but centos not, please help us to look at the log:

[root@centjiang 2017-11-03]# vim   notary-server.log 

Nov  3 13:51:38 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:39 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:40 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:41 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:43 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:44 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:46 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:47 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:48 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:50 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:51 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:52 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:55 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:57 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:51:59 bogon notary-server[2585]: message repeated 2 times: [ waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.]
Nov  3 13:52:00 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:52:01 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:52:03 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:52:08 bogon notary-server[2585]: message repeated 4 times: [ waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.]
Nov  3 13:52:09 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:52:11 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:52:12 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:52:13 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:52:14 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:52:15 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:52:16 bogon notary-server[2585]: waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
Nov  3 13:52:17 bogon notary-server[2585]: notaryserver database failed to come up within 30 seconds


[root@centjiang 2017-11-03]# vim   notary-signer.log 

Nov  3 13:51:05 bogon notary-signer[2585]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  3 13:51:08 bogon notary-signer[2585]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  3 13:51:09 bogon notary-signer[2585]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  3 13:51:10 bogon notary-signer[2585]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  3 13:51:37 bogon notary-signer[2585]: message repeated 20 times: [ waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.]
Nov  3 13:51:40 bogon notary-signer[2585]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  3 13:51:41 bogon notary-signer[2585]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  3 13:51:42 bogon notary-signer[2585]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  3 13:51:43 bogon notary-signer[2585]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  3 13:51:46 bogon notary-signer[2585]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  3 13:51:48 bogon notary-signer[2585]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
Nov  3 13:51:49 bogon notary-signer[2585]: notarysigner database failed to come up within 30 seconds
Nov  3 13:52:08 bogon notary-signer[2585]: waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.


[root@centjiang 2017-11-03]# vim notary-db.log 

Nov  3 13:49:45 bogon notary-db[2585]: 2017-11-03  5:49:45 139797936531200 [Note] mysqld: Normal shutdown
Nov  3 13:49:45 bogon notary-db[2585]:
Nov  3 13:49:46 bogon notary-db[2585]: 2017-11-03  5:49:46 139797936531200 [Note] Event Scheduler: Purging the queue. 0 events
Nov  3 13:49:46 bogon notary-db[2585]: 2017-11-03  5:49:46 139797133747968 [Note] InnoDB: FTS optimize thread exiting.
Nov  3 13:49:46 bogon notary-db[2585]: 2017-11-03  5:49:46 139797936531200 [Note] InnoDB: Starting shutdown...
Nov  3 13:49:48 bogon notary-db[2585]: 2017-11-03  5:49:48 139797936531200 [Note] InnoDB: Shutdown completed; log sequence number 1617471
Nov  3 13:49:48 bogon notary-db[2585]: 2017-11-03  5:49:48 139797936531200 [Note] mysqld: Shutdown complete
Nov  3 13:49:48 bogon notary-db[2585]:
Nov  3 13:50:36 bogon notary-db[2585]: 2017-11-03  5:50:36 139965021263808 [Note] mysqld (mysqld 10.1.10-MariaDB-1~jessie) starting as process 1 ...
Nov  3 13:50:37 bogon notary-db[2585]: 2017-11-03  5:50:37 139965021263808 [Note] InnoDB: Using mutexes to ref count buffer pool pages
Nov  3 13:50:37 bogon notary-db[2585]: 2017-11-03  5:50:37 139965021263808 [Note] InnoDB: The InnoDB memory heap is disabled
Nov  3 13:50:37 bogon notary-db[2585]: 2017-11-03  5:50:37 139965021263808 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
Nov  3 13:50:37 bogon notary-db[2585]: 2017-11-03  5:50:37 139965021263808 [Note] InnoDB: Memory barrier is not used
Nov  3 13:50:37 bogon notary-db[2585]: 2017-11-03  5:50:37 139965021263808 [Note] InnoDB: Compressed tables use zlib 1.2.8
Nov  3 13:50:37 bogon notary-db[2585]: 2017-11-03  5:50:37 139965021263808 [Note] InnoDB: Using Linux native AIO
Nov  3 13:50:37 bogon notary-db[2585]: 2017-11-03  5:50:37 139965021263808 [Note] InnoDB: Using SSE crc32 instructions
Nov  3 13:50:37 bogon notary-db[2585]: 2017-11-03  5:50:37 139965021263808 [Note] InnoDB: Initializing buffer pool, size = 256.0M
Nov  3 13:50:37 bogon notary-db[2585]: 2017-11-03  5:50:37 139965021263808 [Note] InnoDB: Completed initialization of buffer pool
Nov  3 13:50:37 bogon notary-db[2585]: 2017-11-03  5:50:37 139965021263808 [Note] InnoDB: Highest supported file format is Barracuda.
Nov  3 13:50:38 bogon notary-db[2585]: 2017-11-03  5:50:38 139965021263808 [Note] InnoDB: 128 rollback segment(s) are active.
Nov  3 13:50:38 bogon notary-db[2585]: 2017-11-03  5:50:38 139965021263808 [Note] InnoDB: Waiting for purge to start
Nov  3 13:50:38 bogon notary-db[2585]: 2017-11-03  5:50:38 139965021263808 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.26-76.0 started; log sequence number 1617471
Nov  3 13:50:38 bogon notary-db[2585]: 2017-11-03  5:50:38 139964234827520 [Note] InnoDB: Dumping buffer pool(s) not yet started
Nov  3 13:50:38 bogon notary-db[2585]: 2017-11-03  5:50:38 139965021263808 [Note] Plugin 'FEEDBACK' is disabled.
Nov  3 13:50:38 bogon notary-db[2585]: 2017-11-03  5:50:38 139965021263808 [Note] Server socket created on IP: '::'.
Nov  3 13:50:38 bogon notary-db[2585]: 2017-11-03  5:50:38 139965021263808 [Note] mysqld: ready for connections.
Nov  3 13:50:38 bogon notary-db[2585]: Version: '10.1.10-MariaDB-1~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution

**Comment by ReidWeb** [comment]
What did you do to fix this?

**Comment by jiananjiang** [comment]
@ReidWeb  I check  two  notary containers  are always in the restart state, so I deleted the / data directory, reinstall on it, you can try。
