### ISSUE TITLE
Can not replication images to hub.docker.com

### ISSUE THREAD

**Issue by cooljsz** [vmware/harbor#3522]
version:1.2.2
When i replication to hub.docker.com,it's failed with these logs.
I was confuse with "source URL: http://registry:5000",is this cause the error?
2017-11-01T10:59:29Z [INFO] initializing: repository: library/hello, tags: [], source URL: http://registry:5000, destination URL: https://hub.docker.com/dockerhubusername, insecure: false, destination user: dockerhubusername
2017-11-01T10:59:30Z [INFO] initialization completed: project: library, repository: library/hello, tags: [latest v1], source URL: http://registry:5000, destination URL: https://hub.docker.com/dockerhubusername, insecure: false, destination user: dockerhubusername
2017-11-01T10:59:33Z [INFO] project library is created on https://hub.docker.com/dockerhubusername with user dockerhubusername
2017-11-01T10:59:33Z [INFO] manifest of library/hello:latest pulled successfully from http://registry:5000: sha256:467af83b77759844196762fc8d9e981a0c3d4fa3c59d76445b7e35a6ee5ca916
2017-11-01T10:59:33Z [INFO] all blobs of library/hello:latest from http://registry:5000: [sha256:05a3bd381fc2470695a35f230afefd7bf978b566253199c4ae5cc96fafa29b37 sha256:0e8205f2763136ae97a4e1d00e2eb939a97e01c0cee8b3f2fa4bd593d16e779f]
2017-11-01T10:59:35Z [INFO] blob sha256:05a3bd381fc2470695a35f230afefd7bf978b566253199c4ae5cc96fafa29b37 of library/hello:latest already exists in https://hub.docker.com/dockerhubusername
2017-11-01T10:59:36Z [INFO] blob sha256:0e8205f2763136ae97a4e1d00e2eb939a97e01c0cee8b3f2fa4bd593d16e779f of library/hello:latest already exists in https://hub.docker.com/dockerhubusername
2017-11-01T10:59:36Z [INFO] blobs of library/hello:latest need to be transferred to https://hub.docker.com/dockerhubusername: []
2017-11-01T10:59:36Z [INFO] manifest of library/hello:latest exists on source registry http://registry:5000, continue manifest pushing
2017-11-01T10:59:37Z [ERROR] [transfer.go:491]: an error occurred while pushing manifest of library/hello:latest to https://hub.docker.com/dockerhubusername : 301 Moved Permanently. Redirecting to /dockerhubusername/v2/library/hello/manifests/latest/

**Comment by cooljsz** [comment]
In $harboe_home/common/config/nginx/nginx.conf
I can not see Https config,excpt
server {
      listen 80;
      #server_name harbordomain.com;
      return 301 https://$host$request_uri;
  }

**Comment by cooljsz** [comment]
## Configuration file of Harbor

#The IP address or hostname to access admin UI and registry service.
#DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
hostname = dockerhub.mycompany.com

#The protocol for accessing the UI and token/notification service, by default it is http.
#It can be set to https if ssl is enabled on nginx.
ui_url_protocol = https

#The password for the root user of mysql db, change this before any production use.
db_password = root123

#Maximum number of job workers in job service  
max_job_workers = 3 

#Determine whether or not to generate certificate for the registry's token.
#If the value is on, the prepare script creates new root cert and private key 
#for generating token to access the registry. If the value is off the default key/cert will be used.
#This flag also controls the creation of the notary signer's cert.
customize_crt = on

#显示的认证及组织信息
crt_country = CN
crt_state = Jilin
crt_location = Changchun
crt_organization = jc
crt_organizationalunit = pr
crt_commonname = dockerhub.mycompany.com
crt_email = jiaosz@mycompany.com

#The path of cert and key files for nginx, they are applied only the protocol is set to https
#ssl_cert = /data/cert/server.crt
#ssl_cert_key = /data/cert/server.key
ssl_cert = /data/cert/dockerhub.mycompany.com.crt
ssl_cert_key = /data/cert/dockerhub.mycompany.com.key
#The path of secretkey storage
secretkey_path = /data

#Admiral's url, comment this attribute, or set its value to NA when Harbor is standalone
admiral_url = NA

#The password of the Clair's postgres database, only effective when Harbor is deployed with Clair.
#Please update it before deployment, subsequent update will cause Clair's API server and Harbor unable to access Clair's database.
clair_db_password = password

#NOTES: The properties between BEGIN INITIAL PROPERTIES and END INITIAL PROPERTIES
#only take effect in the first boot, the subsequent changes of these properties 
#should be performed on web ui

#************************BEGIN INITIAL PROPERTIES************************

#Email account settings for sending out password resetting emails.

#Email server uses the given username and password to authenticate on TLS connections to host and act as identity.
#Identity left blank to act as username.
email_identity = 

email_server = smtp.mydomain.com
email_server_port = 25
email_username = sample_admin@mydomain.com
email_password = abc
email_from = admin <sample_admin@mydomain.com>
email_ssl = false

##The initial password of Harbor admin, only works for the first time when Harbor starts. 
#It has no effect after the first launch of Harbor.
#Change the admin password from UI after launching Harbor.
harbor_admin_password = Harbor12345

##By default the auth mode is db_auth, i.e. the credentials are stored in a local database.
#Set it to ldap_auth if you want to verify a user's credentials against an LDAP server.
auth_mode = db_auth

#The url for an ldap endpoint.
ldap_url = ldaps://ldap.mydomain.com

#A user's DN who has the permission to search the LDAP/AD server. 
#If your LDAP/AD server does not support anonymous search, you should configure this DN and ldap_search_pwd.
#ldap_searchdn = uid=searchuser,ou=people,dc=mydomain,dc=com

#the password of the ldap_searchdn
#ldap_search_pwd = password

#The base DN from which to look up a user in LDAP/AD
ldap_basedn = ou=people,dc=mydomain,dc=com

#Search filter for LDAP/AD, make sure the syntax of the filter is correct.
#ldap_filter = (objectClass=person)

# The attribute used in a search to match a user, it could be uid, cn, email, sAMAccountName or other attributes depending on your LDAP/AD  
ldap_uid = uid 

#the scope to search for users, 1-LDAP_SCOPE_BASE, 2-LDAP_SCOPE_ONELEVEL, 3-LDAP_SCOPE_SUBTREE
ldap_scope = 3 

#Timeout (in seconds)  when connecting to an LDAP Server. The default value (and most reasonable) is 5 seconds.
ldap_timeout = 5

#Turn on or off the self-registration feature
self_registration = on

#The expiration time (in minute) of token created by token service, default is 30 minutes
token_expiration = 30

#The flag to control what users have permission to create projects
#The default value "everyone" allows everyone to creates a project. 
#Set to "adminonly" so that only admin user can create project.
project_creation_restriction = everyone

#Determine whether the job service should verify the ssl cert when it connects to a remote registry.
#Set this flag to off when the remote registry uses a self-signed or untrusted certificate.
verify_remote_cert = on
#************************END INITIAL PROPERTIES************************
#############

**Comment by steven-zou** [comment]
@cooljsz 

Replicating images from Harbor to dockerhub is not supported yet, but it's already in planning. Thanks.

**Comment by cooljsz** [comment]
thx,我这么蹩脚的英文都看懂了,真难为了

**Comment by DavidRodHub** [comment]
The above message indicated in the planning is support for replicating Harbor to dockerhub.   Will this include replicating to AWS registry?

**Comment by anairinac** [comment]
Are there any updates with supporting this in Harbor? If there is some progress, will it include just DockerHub, or does it include Amazon ECR as well?
