### ISSUE TITLE
Improve log rotation configurability

### ISSUE THREAD

**Issue by andrewtchin** [vmware/harbor#3525]
My current understanding is that logs are compressed every 3 days, but there isn't any way to limit the disk space that logs take up.
Based on Bugzilla 1968901 and the VIC Appliance design doc (https://github.com/vmware/vic-product/blob/master/installer/DESIGN.md#logging) I would recommend adding configuration options to limit the maximum size on disk such as options for max log file size and max number of log files to store
These config options should have reasonable defaults (Admiral uses 5x1GB log files) and should be configurable by VIC Appliance users.

**Comment by reasonerjt** [comment]
@ywk253100 please investigate.

**Comment by ywk253100** [comment]
@andrewtchin  PR #3571 is opened to fix this. Two parameters `log_rotate_count ` and `log_rotate_size ` are provided to configure log file size and number.

**Comment by ywk253100** [comment]
Done.

**Comment by andrewtchin** [comment]
@stuclem This probably needs documentation

**Comment by stuclem** [comment]
Thanks @andrewtchin
