### ISSUE TITLE
Confused about why we have adminserver when harbor-ui already exists?

### ISSUE THREAD

**Issue by cmingxu** [vmware/harbor#3539]
Last time I saw harbor there were still no adminserver, kinda of confused why adminserver as we already have harbor-ui as API server, do we have too much services to care about when deployed into a production environment?

**Comment by steven-zou** [comment]
@cmingxu 

At present harbor architecture,

  harbor-ui provides api services and harbor core services
  admin-service provide capabilities of managing system and user related configurations

These two have different considerations and functions.

**Comment by steven-zou** [comment]
Outdated, close
