### ISSUE TITLE
in openstack env,docker push image error authorization token required

### ISSUE THREAD

**Issue by lklkxcxc** [vmware/harbor#3548]
The harbor was deployed in openstack vm.vm contions flat ip (10.0.0.20)and floating ip (192.168.1.188)
in the docker client that perform docker push or pull image error. docker was login harbor successed：
docker client error：
root@mockserver:~# docker pull reg.docker.gaia/test/try-on
Using default tag: latest
Error response from daemon: Get http://reg.docker.gaia/v2/test/try-on/manifests/latest: EOF

harbor registry error：
Nov  3 10:12:09 172.18.0.1 registry[1054]: time="2017-11-03T10:12:09.773422967Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.3 http.request.host=reg.docker.gaia http.request.id=8a309d0b-4451-4f63-9d25-0465437f01c1 http.request.method=GET http.request.remoteaddr=192.168.1.28 http.request.uri="/v2/" http.request.useragent="docker/1.12.6 go/go1.6.2 git-commit/78d1802 kernel/4.4.0-89-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \\(linux\\))" instance.id=4c78e562-be28-494c-8dc4-0736e0cf8164 service=registry version=v2.6.2 
Nov  3 10:12:09 172.18.0.1 registry[1054]: 172.18.0.6 - - [03/Nov/2017:10:12:09 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/1.12.6 go/go1.6.2 git-commit/78d1802 kernel/4.4.0-89-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \\(linux\\)) 

But in harbor local performed push and pull image ok.

**Comment by steven-zou** [comment]
@ywk253100 
  Please take a look at if bugs existing in the token service when handling float IP

**Comment by ywk253100** [comment]
Provide all logs of Harbor.

**Comment by lklkxcxc** [comment]
@ywk253100 
[harbor.tar.gz](https://github.com/vmware/harbor/files/1448964/harbor.tar.gz)

**Comment by ywk253100** [comment]
According to the logs of Nov. 3th, it seems that docker pull/push operations succeed on some hosts (such as 192.168.1.10, 192.168.1.236), failed on 192.168.1.28, is it right?

Harbor received the token request from 192.168.1.28 and responded it successfully, but Harbor didn't receive any following request for pulling images. So the problem may be in client end.

**Comment by lklkxcxc** [comment]
@ywk253100  Before Harbor was moved from custom host docker to Openstack host docker ,client hosts （192.168.1.10，92.168.1.236）docker pull/push operations succeed. Now all client(expect Harbor local client) always failing.

**Comment by ywk253100** [comment]
You should debug on the host where docker is installed to find why the following requests are not sent to Harbor.

**Comment by lklkxcxc** [comment]
root@mockserver:~# docker -D pull reg.docker.gaia/test/provider
Using default tag: latest
Error response from daemon: Get http://reg.docker.gaia/v2/test/provider/manifests/latest: EOF

**Comment by lklkxcxc** [comment]
@ywk253100 Beause client posted a big package size (>1500)and marked "don't fragment",tcpip  shard transmission failed.please to view  the attachment.
![qq 20171114174850](https://user-images.githubusercontent.com/10216780/32774062-133fc0d8-c966-11e7-9cd5-aa9a07eb89b2.png)
[tcpdump.zip](https://github.com/vmware/harbor/files/1470288/tcpdump.zip)

**Comment by lklkxcxc** [comment]
@ywk253100  you remind me to check docker bridge MTU size so that I check my env docker0's MTU size.The openstack VM host interface set MTU size1450,but docker0 set MTU size 1500 result TCP MSS size set 1500 is greater than 1450.
The solution：
`networks:
  harbor:
    external: false
    driver_opts:
      com.docker.network.driver.mtu: 1400`

**Comment by ywk253100** [comment]
So the MTU of docker client host network is 1450, the MTU of Harbor host network is 1450, but the MTU of the bridge network used by Harbor is 1500, this causes that the transmission of ACK returned by Harbor fails as the data size is greater than 1450. Is it right?

**Comment by lklkxcxc** [comment]
@ywk253100 The MTU of docker client host network is 1500 that docker client  MTU size doesn't affect the result.The bridge network used by Harbor is 1500 must modify equal MTU host network. plase close this problem.

**Comment by lklkxcxc** [comment]
看了下你的github原来你在北京啊，就是客户端MTU值是多少不会导致这次出现的问题。问题原因是openstack虚拟机网卡默认MTU不是1500而是1450，但是harbor所在的docker0网桥的MTU是1500需要修改成1450就可以了。

**Comment by ywk253100** [comment]
所以是服务器端成功收到了客户端的请求，但是服务器端的ACK没有发送出去。

**Comment by lklkxcxc** [comment]
是的
