### ISSUE TITLE
Username does not exist.

### ISSUE THREAD

**Issue by caipengtao** [vmware/harbor#3553]
hello guys,I use the ldap,then I add a user 'test' in the ldap, with the user I can login the harbor web,and I find the user in the administrator of users,but when I add the user to one project,it says "Username does not exist.".How can I slove this problem. 

![6583a92a-c8ed-4838-a14a-b4f0258aa95e](https://user-images.githubusercontent.com/19907364/32422590-c18a09e8-c266-11e7-9ad7-a43b06c720b4.png)

**Comment by stonezdj** [comment]
Root cause: there is a leading space in username, need to remove it before insert user.

**Comment by stonezdj** [comment]
Fixed in PR: https://github.com/vmware/harbor/pull/3683
