### ISSUE TITLE
Harbor forces to use tls using smtp though email_tls is false.

### ISSUE THREAD

**Issue by odg0318** [vmware/harbor#3566]
Hello.

I installed `vmware/harbor v1.2.2` and tested smtp feature.
I set `email_ssl` false in `harbor.cfg` but validating tls error is shown in the following log.

```
Nov  8 02:51:27 172.18.0.1 ui[1946]: 2017-11-08T02:51:27Z [DEBUG] [security.go:240]: using local database project manager
Nov  8 02:51:27 172.18.0.1 ui[1946]: 2017-11-08T02:51:27Z [DEBUG] [security.go:242]: creating local database security context...
Nov  8 02:51:27 172.18.0.1 ui[1946]: 2017-11-08T02:51:27Z [DEBUG] [mail.go:92]: establishing TCP connection with 172.16.5.45:30025 ...
Nov  8 02:51:27 172.18.0.1 ui[1946]: 2017-11-08T02:51:27Z [DEBUG] [mail.go:117]: creating SMTP client for 172.16.5.45 ...
Nov  8 02:51:27 172.18.0.1 ui[1946]: 2017-11-08T02:51:27Z [DEBUG] [mail.go:126]: switching the connection with 172.16.5.45:30025 to SSL/TLS ...
Nov  8 02:51:27 172.18.0.1 ui[1946]: 2017-11-08T02:51:27Z [DEBUG] [email.go:106]: ping 172.16.5.45:30025 failed: x509: cannot validate certificate for 172.16.5.45 because it doesn't contain any IP SANs
```

So I examined a code related to email and found something like a bug in my opinion.

https://github.com/vmware/harbor/blob/v1.2.2/src/common/utils/email/mail.go#L104
The above code skips tls validation check.

https://github.com/vmware/harbor/blob/v1.2.2/src/common/utils/email/mail.go#L124
But this code forces to use tls validation check even though I set `email_tls` false.

**Comment by ywk253100** [comment]
The configuration item `email_tls` is used to determine whether to establish TLS connection with the email server. There will be a new configuration item `email_insecure` to skip the certificate verification and will be available in the next release.

**Comment by odg0318** [comment]
Thanka. I expect next release.

**Comment by odg0318** [comment]
@ywk253100 I have a question to send email with my ca certification.
I installed my ca certification to photon but email connection still failed.
I think that harbor is written by `golang` and `crypto/tls`, one of its packages, cannot find root CA certification.

I installed my ca certification to `/etc/pki/tls/certs/ca-bundle.crt`.
Do you know what path is valid?

**Comment by ywk253100** [comment]
Run `cat your_ca.crt >> /etc/pki/tls/certs/ca-bundle.crt` and restart container `harbor-ui`.
