### ISSUE TITLE
star_count seems not working nowing.

### ISSUE THREAD

**Issue by moooofly** [vmware/harbor#3568]
I want to use `star_count` to identify which projects or repositories are more popular, but there is nothing related to it in the Web UI, and it's always 0 when i make a `curl` request.

After some codes digging, I find `star_count` not being used yet.
So I want to know when i can use it as wish.

Thanks in advance.

**Comment by reasonerjt** [comment]
This column is not used, we don't have plan to leverage it in near future.

**Comment by moooofly** [comment]
ok, tks
