### ISSUE TITLE
Read Only mode in Harbor

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#3569]
This issue will not cover GC but readonly mode.

System admin could set Harbor into readonly, it's system level not project.

P0: Disable API: User could pull image but push is blocked, and other API to modify data should be have a 503 response. This could be done by interceptor.
P0: Disable UI: Under readonly mode, needs to define the viewable scope of UI or only gives a maintenance page to point "Harbor is coming soon."

**Comment by sec9** [comment]
can we  use the opportunity to add with the GC a  lifecycle-policies page to delete images  older than xx days or when their count is > y

**Comment by wy65701436** [comment]
Issue in harbor-planning: https://github.com/vmware/harbor-planning/issues/3

1 , Set Harbor to Read maintenance mode
1.1 Disable API: User could pull image but push is blocked, and other API should be have a 503 response. This could be done by interceptor.
1.2 Disable UI:  Under maintenance mode, needs to define the viewable scope of UI or only gives a maintenance page to point "Harbor is coming soon."

2, Run GC: Investigate, this dependencies on the capacity of docker registry v2.6.2. 
2.1 In GC,  pull can be executed but push cannot
2.2 GC can be scheduled like "Scan Now", and can also be run manually by system admin. 
2.3 UI will show "Harbor is running GC."
2.4 Stop GC? Dependencies on docker registry, needs investigate.

**Comment by wy65701436** [comment]
API code has already been merged per PR https://github.com/vmware/harbor/pull/4433

**Comment by wy65701436** [comment]
Will open another issue to track run GC.
