### ISSUE TITLE
List harbor privileges/resource requirement 

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#3572]
We should have a doc to list the resources needed to setup a harbor.

1> Hardware,
2>Software
3> Network ports used

**Comment by stuclem** [comment]
@yixingjia we document the required ports for Harbor in the VIC docs here: https://github.com/vmware/vic-product/blob/master/docs/user_doc/vic_vsphere_admin/security_reference.md#open_ports

The other items would certainly be useful to include in the VIC docs, so I have opened https://github.com/vmware/vic-product/issues/1048 to track the doc update.

**Comment by yixingjia** [comment]
Should be fixed by
https://github.com/vmware/harbor/pull/3669
