### ISSUE TITLE
I get info "authentication required" and "Status 405 trying to push repository" when I pull or push images from harbor

### ISSUE THREAD

**Issue by zsmlinux** [vmware/harbor#3573]
I have a problem for using harbor as docker repo. 
docker version:
Docker version 17.03.1-ce, build c6d412e

harbor version:
Harbor version 1.1.0 GA

Event if "Login Succeeded" by docker login, I still can't pull or push images.
When I pull a image,it says 
"Pulling repository img-lan.xxx.com/dba/dba_django_aduit
unauthorized: authentication required"
 
or I push a image:
"The push refers to a repository [img-lan.xxx.com/dba/dba_django_aduit]
0bd515bec820: Preparing 
51e6915a6d7d: Preparing 
db372f24b7bd: Preparing 
61711d4ab940: Preparing 
a48ec327d21f: Preparing 
e2ebf2df2769: Waiting 
7bceefc4c5d4: Waiting 
500742de5484: Waiting 
0a5e2b2ddeaa: Waiting 
53c779688d06: Waiting 
60a0858edcd5: Waiting 
b6ca02dfe5e6: Waiting 
Error: Status 405 trying to push repository dba/dba_django_aduit: "<html><body>HTTP Method not supported</body></html>""

AND I can't find any other useful info from /var/log/harbor/.

Thank you so much!

**Comment by reasonerjt** [comment]
```
AND I can't find any other useful info from /var/log/harbor/.

```
How did you install?

**Comment by stonezdj** [comment]
Please upload the logs in /var/log/harbor?

**Comment by zsmlinux** [comment]
cat /var/log/harbor/2017-12-14/*
Dec 14 00:01:01 09d42964a4d0 anacron[9212]: Anacron started on 2017-12-14
Dec 14 00:01:01 09d42964a4d0 anacron[9212]: Normal exit (0 jobs run)
Dec 14 01:01:01 09d42964a4d0 anacron[9224]: Anacron started on 2017-12-14
Dec 14 01:01:01 09d42964a4d0 anacron[9224]: Normal exit (0 jobs run)
Dec 14 02:01:01 09d42964a4d0 anacron[9236]: Anacron started on 2017-12-14
Dec 14 02:01:01 09d42964a4d0 anacron[9236]: Normal exit (0 jobs run)
Dec 14 03:01:01 09d42964a4d0 anacron[9248]: Anacron started on 2017-12-14
Dec 14 03:01:01 09d42964a4d0 anacron[9248]: Will run job `cron.daily' in 37 min.
Dec 14 03:01:01 09d42964a4d0 anacron[9248]: Jobs will be executed sequentially
Dec 14 03:38:01 09d42964a4d0 anacron[9248]: Job `cron.daily' started
Dec 14 03:38:01 09d42964a4d0 anacron[9248]: Job `cron.daily' terminated
Dec 14 03:38:01 09d42964a4d0 anacron[9248]: Normal exit (1 job run)
Dec 14 00:01:01 09d42964a4d0 CROND[9204]: (root) CMD (run-parts /etc/cron.hourly)
Dec 14 00:01:01 09d42964a4d0 CROND[9203]: (root) CMDOUT (/etc/cron.hourly/0anacron:)
Dec 14 00:01:01 09d42964a4d0 CROND[9203]: (root) CMDOUT ()
Dec 14 01:01:01 09d42964a4d0 CROND[9216]: (root) CMD (run-parts /etc/cron.hourly)
Dec 14 01:01:01 09d42964a4d0 CROND[9215]: (root) CMDOUT (/etc/cron.hourly/0anacron:)
Dec 14 01:01:01 09d42964a4d0 CROND[9215]: (root) CMDOUT ()
Dec 14 02:01:01 09d42964a4d0 CROND[9228]: (root) CMD (run-parts /etc/cron.hourly)
Dec 14 02:01:01 09d42964a4d0 CROND[9227]: (root) CMDOUT (/etc/cron.hourly/0anacron:)
Dec 14 02:01:01 09d42964a4d0 CROND[9227]: (root) CMDOUT ()
Dec 14 03:01:01 09d42964a4d0 CROND[9240]: (root) CMD (run-parts /etc/cron.hourly)
Dec 14 03:01:01 09d42964a4d0 CROND[9239]: (root) CMDOUT (/etc/cron.hourly/0anacron:)
Dec 14 03:01:01 09d42964a4d0 CROND[9239]: (root) CMDOUT ()
Dec 14 04:01:01 09d42964a4d0 CROND[9254]: (root) CMD (run-parts /etc/cron.hourly)
Dec 14 04:01:01 09d42964a4d0 CROND[9253]: (root) CMDOUT (/etc/cron.hourly/0anacron:)
Dec 14 04:01:01 09d42964a4d0 CROND[9253]: (root) CMDOUT ()
Dec 14 04:02:01 09d42964a4d0 CROND[9264]: (root) CMD ([ ! -f /etc/cron.hourly/0anacron ] && run-parts /etc/cron.daily)
Dec 14 05:01:01 09d42964a4d0 CROND[9266]: (root) CMD (run-parts /etc/cron.hourly)
Dec 14 05:01:01 09d42964a4d0 CROND[9265]: (root) CMDOUT (/etc/cron.hourly/0anacron:)
Dec 14 05:01:01 09d42964a4d0 CROND[9265]: (root) CMDOUT ()
Dec 14 06:01:01 09d42964a4d0 CROND[9276]: (root) CMD (run-parts /etc/cron.hourly)
Dec 14 06:01:01 09d42964a4d0 CROND[9275]: (root) CMDOUT (/etc/cron.hourly/0anacron:)
Dec 14 06:01:01 09d42964a4d0 CROND[9275]: (root) CMDOUT ()
Dec 14 08:25:45 172.18.0.1 proxy[13079]: 172.82.166.210 - "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1090 "-" "Mozilla" 0.003 0.003 .
Dec 14 09:20:36 172.18.0.1 proxy[13079]: 219.68.239.150 - "GET / HTTP/1.1" 200 817 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36" 0.002 0.002 .
Dec 14 09:56:38 172.18.0.1 proxy[13079]: 172.104.137.252 - "\x16\x03\x01\x01,\x01\x00\x01(\x03\x03u\x00\x94\x96\x8E~\x82B\xE8\xE99\xCB\x14\x89\xCE\xFE\x05\xCA\xF9S\x09k\x0E=.<\xFD\xA6r\xF1R\x89\x00\x00\xAA\xC00\xC0,\xC0(\xC0$\xC0\x14\xC0" 400 173 "-" "-" 0.212 - .
Dec 14 12:35:01 172.18.0.1 proxy[13079]: 106.92.59.78 - "GET / HTTP/1.1" 200 817 "http://106.75.131.34:81" "Mozilla/4.0 (compatible; MSIE 9.0; Windows NT 6.1)" 0.003 0.003 .
Dec 14 00:01:01 09d42964a4d0 run-parts[9204]: (/etc/cron.hourly) starting 0anacron
Dec 14 00:01:01 09d42964a4d0 run-parts[9204][9214]: (/etc/cron.hourly) finished 0anacron
Dec 14 01:01:01 09d42964a4d0 run-parts[9216]: (/etc/cron.hourly) starting 0anacron
Dec 14 01:01:01 09d42964a4d0 run-parts[9216][9226]: (/etc/cron.hourly) finished 0anacron
Dec 14 02:01:01 09d42964a4d0 run-parts[9228]: (/etc/cron.hourly) starting 0anacron
Dec 14 02:01:01 09d42964a4d0 run-parts[9228][9238]: (/etc/cron.hourly) finished 0anacron
Dec 14 03:01:01 09d42964a4d0 run-parts[9240]: (/etc/cron.hourly) starting 0anacron
Dec 14 03:01:01 09d42964a4d0 run-parts[9240][9250]: (/etc/cron.hourly) finished 0anacron
Dec 14 04:01:01 09d42964a4d0 run-parts[9254]: (/etc/cron.hourly) starting 0anacron
Dec 14 04:01:01 09d42964a4d0 run-parts[9254][9262]: (/etc/cron.hourly) finished 0anacron
Dec 14 05:01:01 09d42964a4d0 run-parts[9266]: (/etc/cron.hourly) starting 0anacron
Dec 14 05:01:01 09d42964a4d0 run-parts[9266][9274]: (/etc/cron.hourly) finished 0anacron
Dec 14 06:01:01 09d42964a4d0 run-parts[9276]: (/etc/cron.hourly) starting 0anacron
Dec 14 06:01:01 09d42964a4d0 run-parts[9276][9284]: (/etc/cron.hourly) finished 0anacron
Dec 14 08:25:45 172.18.0.1 ui[13079]: 2017/13/14 00:25:45 #033[1;34m[router.go:829][D] | GET        | /cache/global/img/gs.gif                 | 977.035µs        | notmatch   | #033[0m

=============
I tried to push image again，and also return ：
db372f24b7bd: Preparing 
61711d4ab940: Preparing 
a48ec327d21f: Preparing 
e2ebf2df2769: Preparing 
7bceefc4c5d4: Preparing 
500742de5484: Waiting 
0a5e2b2ddeaa: Waiting 
53c779688d06: Waiting 
60a0858edcd5: Waiting 
b6ca02dfe5e6: Waiting 
Error: Status 405 trying to push repository dba/dba_django_aduit: "<html><body>HTTP Method not supported</body></html>"

**Comment by stonezdj** [comment]
Checked the logs, error log of 405 error not found, Is it possible that the connection between harbor  
and the docker client passes through a proxy server, this proxy server doesn't support PATCH method.
