### ISSUE TITLE
Why I can perform the pull and push operation, but in the harbor has uploaded image web page can't see

### ISSUE THREAD

**Issue by easyforit** [vmware/harbor#3576]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
root@uk234:~# docker --version
Docker version 17.03.2-ce, build f5ec1e2
root@uk234:~# docker-compose --version
docker-compose version 1.17.0, build ac53b73
2)截图
![image](https://user-images.githubusercontent.com/33481727/32583293-cf08b38e-c52d-11e7-823c-7f0bad2eebc9.png)
3)Log files, you can get them by package the /var/log/harbor/ .
[2017-11-08.zip](https://github.com/vmware/harbor/files/1455982/2017-11-08.zip)

**Comment by stonezdj** [comment]
It is the database table version is not compatible with the program, please refer[ migrate guide](https://github.com/vmware/harbor/blob/master/docs/migration_guide.md) to upgrade the database. 
I checked the ui.log, found error message "failed to add access log: Error 1054: Unknown column 'username' in 'field list'".

**Comment by xiaoy110** [comment]
in the docker-compose.yml file, every image with version, why it still has the version compatible problem?
