### ISSUE TITLE
Why after set up,in the harbor of a web page to send email for reset your password , prompt server internal error, request failure

### ISSUE THREAD

**Issue by easyforit** [vmware/harbor#3577]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
2)
![wxd6 5dhbz 7im93ax 9](https://user-images.githubusercontent.com/33481727/32584378-f5464e26-c532-11e7-89d3-ab459e654786.png)
![iyww2m bd es mq 91fd0 8](https://user-images.githubusercontent.com/33481727/32584384-f6b6644e-c532-11e7-926a-a1319e42ddee.png)
![61k sokusz t5tax0j g](https://user-images.githubusercontent.com/33481727/32584388-f8668f62-c532-11e7-98e4-06ce9bfe0424.png)
3)Log files, you can get them by package the /var/log/harbor/ .
[2017-11-09.zip](https://github.com/vmware/harbor/files/1456044/2017-11-09.zip)

**Comment by ywk253100** [comment]
Got logs: `Send email failed: 550 Invalid User`.

According to the doc http://help.163.com/09/1224/17/5RAJ4LMH00753VB8.html, the error is caused by an invalid user.

So make sure the credential configured is correct.
