### ISSUE TITLE
Certificate problem

### ISSUE THREAD

**Issue by jiananjiang** [vmware/harbor#3578]
Hello, I have a question to ask: I use https and self-signed certificate, the configuration is used ldap, the company colleagues log in through the ldap account, what needs to be configured to push and pull the images? In addition, I also used notary function. Is the same with http, just configure --insecure-registry myregistrydomain.com? Or still need a certificate? Do not quite understand, I hope someone can tell me.

**Comment by yixingjia** [comment]
Please see the follow docs which should solve your issue.
https://github.com/vmware/harbor/blob/master/docs/configure_https.md

After setting up HTTPS for Harbor, you can verify it by the following steps:

    Open a browser and enter the address: https://reg.yourdomain.com . It should display the user interface of Harbor.

    On a machine with Docker daemon, make sure the option "-insecure-registry" does not present, and you must copy ca.crt generated in the above step to /etc/docker/certs.d/reg.yourdomain.com(or your registry host IP), if the directory does not exist, create it. If you mapped nginx port 443 to another port, then you should instead create the directory /etc/docker/certs.d/reg.yourdomain.com:port(or your registry host IP:port). Then run any docker command to verify the setup, e.g.

  docker login reg.yourdomain.com

**Comment by jiananjiang** [comment]
Sorry, your point is that the harbor is already configured on my machine, including the steps you just said. Then my colleagues log in using the ldap account, he did not install the harbor operation of the machine, also need to be a certificate, and then copy the ca.crt generated  to /etc/docker/certs.d/reg.yourdomain. com  and then can  normal pull and push operation?
