### ISSUE TITLE
在docker可以上传、下载镜像都提升成功，但在harbor的UI里看不到镜像。

### ISSUE THREAD

**Issue by Debris2017** [vmware/harbor#3579]
1）Docker version 1.12.6, build 78d1802
docker-compose version 1.8.1, build 878cff1
2)
[harbor.cfg.zip](https://github.com/vmware/harbor/files/1456130/harbor.cfg.zip)
3）log
[2017-11-09.zip](https://github.com/vmware/harbor/files/1456131/2017-11-09.zip)

**Comment by ywk253100** [comment]
Refer to the upgrade guide to upgrade your database.
