### ISSUE TITLE
invalid parameter

### ISSUE THREAD

**Issue by clyuan2016** [vmware/harbor#358]
harbor部署时出现ERROR: Service 'log' failed to build: mkdir /var/lib/docker/overlay/f3131e83d73405493773cb8227fdde8d6d669edc20391a9088f77a0f3a889d98-init/merged/dev/shm: invalid argument 是什么原因，怎么解决呢？

**Comment by reasonerjt** [comment]
should be issue in docker daemon.

**Comment by reasonerjt** [comment]
dup to #575
