### ISSUE TITLE
Unable to login/push/pull images except on harbor localhost (+HTTPS)

### ISSUE THREAD

**Issue by zwindler** [vmware/harbor#3583]
Hello, 

I have installed Harbor using the official install.sh, without notary and clair, BUT with HTTPS support

Harbor seems to work fine, I can login on the HTTPS webpage, I can create repositories, manage harbor configuration, add users. I can also login/push/pull correctly when I'm on the local machine (harbor01.domain.tld). There is no issue with the CA (imported in /etc/docker/certs.d/harbor01.domain.tld/ca.crt).

Everything is working on this local machine BUT I'm unable to log, push, or pull from any other machine on my LAN

DNS resolution is OK and ports are open : I can curl/wget harbor webpage
```
[root@random_lan_host ~]# curl https://harbor01.domain.tld
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <title>Harbor</title>
[...]
```

```
[root@random_lan_host ~]# docker login harbor01.domain.tld
Username: admin
Password:
Error response from daemon: Get https://harbor01.domain.tld/v1/users/: net/http: TLS handshake timeout
[root@random_lan_host ~]# docker pull harbor01.domain.tld/rhel7/rhel
Using default tag: latest
Error response from daemon: Get https://harbor01.domain.tld/v1/_ping: net/http: TLS handshake timeout
```

1)Version of docker engine and docker-compose.
```
docker --version
Docker version 17.03.0-ce, build 3a232c8
docker-compose --version
docker-compose version 1.16.1, build 6d1ac21
```

2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.

```
cat harbor.cfg
## Configuration file of Harbor
hostname =  harbor01.domain.tld
ui_url_protocol = https

db_password = XXXXXXXXXX

max_job_workers = 3
customize_crt = on

ssl_cert = /etc/ssl/public/harbor01.domain.tld.crt
ssl_cert_key = /etc/ssl/private/harbor01.domain.tld.key

secretkey_path = /data
admiral_url = NA

clair_db_password = XXXXXXXXXX
#************************BEGIN INITIAL PROPERTIES************************
email_identity =
email_server = mail.domain.tld
email_server_port = 25
email_username = harbor@domain.tld
email_from = harbor admin <harbor@domain.tld>
email_ssl = false
email_password =

harbor_admin_password = XXXXXXXXXX
auth_mode = db_auth

#The url for an ldap endpoint.
ldap_url = ldaps://ldap.mydomain.com
#A user's DN who has the permission to search the LDAP/AD server.
#If your LDAP/AD server does not support anonymous search, you should configure this DN and ldap_search_pwd.
ldap_searchdn = uid=searchuser,ou=people,dc=mydomain,dc=com
#the password of the ldap_searchdn
ldap_search_pwd = password
#The base DN from which to look up a user in LDAP/AD
ldap_basedn = ou=people,dc=mydomain,dc=com
#Search filter for LDAP/AD, make sure the syntax of the filter is correct.
ldap_filter = (objectClass=person)
# The attribute used in a search to match a user, it could be uid, cn, email, sAMAccountName or other attributes depending on your LDAP/AD
ldap_uid = uid
#the scope to search for users, 1-LDAP_SCOPE_BASE, 2-LDAP_SCOPE_ONELEVEL, 3-LDAP_SCOPE_SUBTREE
ldap_scope = 3
#Timeout (in seconds)  when connecting to an LDAP Server. The default value (and most reasonable) is 5 seconds.
ldap_timeout = 5

self_registration = on
token_expiration = 30
project_creation_restriction = everyone
verify_remote_cert = on
#************************END INITIAL PROPERTIES************************
#############
```

3)Log files, you can get them by package the /var/log/harbor/ .
I found nothing worth in the logs (no log output is produced when I try to login/pull/push)

**Comment by reasonerjt** [comment]
Hi,
could you try `https://harbor01.domain.tld/v1/users/` from local and remote and let us know the result?

**Comment by zwindler** [comment]
You mean, try to curl/wget this URL ?

**Comment by reasonerjt** [comment]
@zwindler yes, as it seems a network issue to me...

**Comment by zwindler** [comment]
On **both** local and remote:
```
curl https://harbor01.domain.tld/v1/users/
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.11.13</center>
</body>
</html>
```

**Comment by zwindler** [comment]
I looked into nginx configuration files in photon-nginx. In the default/generated configuration, v1 is disabled by 404

```
docker exec -it xxxxxxx bash
vi /etc/nginx/nginx.conf
    location /v1/ {
      return 404;
    }
```

So it's "normal" that I can't curl v1 on either hosts. 

With that knowledge, I tried to force docker to use only v2 registries by adding on remote the following option in */etc/docker/daemon.json*

```
cat /etc/docker/daemon.json
{ "disable-legacy-registry":true }
systemctl restart docker
```

But I get a similar error
```
docker pull harbor01.domain.tld/rhel7/rhel
Using default tag: latest
Error response from daemon: Get https://harbor01.domain.tld/v2/: net/http: TLS handshake timeout
```

**Comment by reasonerjt** [comment]
It didn't hit 404, the `TLS handshake timeout` indicates a networking issue.

So are you saying you can curl the url but failed to communicate with same url via docker daemon?
Could you check if there's configuration in docker daemon that may cause that issue?

**Comment by zwindler** [comment]
Ok, found it. This issue is 100% caused by a network problem on our part. 

I don't have the solution (because it's related to how our network has been built) but there is nothing wrong with Harbor.

Thanks for the help and sorry for the inconvenience. (Closing the issue)

**Comment by catscarlet** [comment]
Hello @zwindler ,I got the same problem today.

- curl can get the access
- docker-cli doesn't

```
root@ubuntu-docker-dev:~# docker push harbor131.catscarlet.com/test1/php-www-data:20180726153027 
The push refers to repository [harbor131.catscarlet.com/test1/php-www-data]
Get https://harbor131.catscarlet.com/v2/: net/http: TLS handshake timeout

root@ubuntu-docker-dev:~# curl https://harbor131.catscarlet.com/v2/                              
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
```

Can you tell me more about your network problem?

**Comment by cwelde** [comment]
I am also having this problem. However, I can't curl or push to the harbor registry. I can pull/push images from dockerhub. I suspect that the problem may be with our corp network/proxy as well.....

**Comment by saisunil2303** [comment]
I am also facing the same issue. I can curl to harbor on both port 80 and 443. But I am unable to do docker login as I am facing the net/http: TLS handshake timeout. Please let me know what ports need to be open?
