### ISSUE TITLE
Some labels in UI missing after upgrading from 1.1.2 to 1.2.2

### ISSUE THREAD

**Issue by eliu** [vmware/harbor#3584]
Upgrading from 1.1.2 to 1.2.2 according to the migration_guide including db upgrade. Some labels in web pages are missing ( becoming CODE or something ), examples as follow:

In `harbor/projects` page, the result table column title `Access Level` now displaying as `PROJECT.ACCESS_LEVEL`.

Kindly help. Anything else you guys need me to provide, just let me know.

ps: im no problem with communication in Chinese, feel free to do that ~

If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.

** Docker version **
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:49 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

** Docker Compose version **
```
docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
3)Log files, you can get them by package the /var/log/harbor/ .

**Comment by steven-zou** [comment]
Have you clear the cache of browser to let browser to re-download the i18n message files?
@eliu

**Comment by steven-zou** [comment]
@ninjadq 

  Please help to track this issue.

**Comment by eliu** [comment]
@steven-zou you're right. it's a browser cache issue. everything turns back to normal after clearing the cache. i'm closing this issue now since it's already been solved. thanks again.
