### ISSUE TITLE
The TC "User View Logs" is not stable.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#3590]
I see intermittent failure of "Do Log Advanced Search"

the same build after a restart passed.

I'll upload the log when I have better internet

**Comment by reasonerjt** [comment]
[integration_logs_1122_19a13e8575776afb699b641f21168875dbbf6002.tar.gz](https://github.com/vmware/harbor/files/1460012/integration_logs_1122_19a13e8575776afb699b641f21168875dbbf6002.tar.gz)

**Comment by wy65701436** [comment]
https://github.com/vmware/harbor/pull/3602

Let's use this PR to monitor the TC execution.

**Comment by reasonerjt** [comment]
I don't reproduce this issue recently, closing.
