### ISSUE TITLE
Improper message when delete a LDAP user in harbor admin console

### ISSUE THREAD

**Issue by stonezdj** [vmware/harbor#3593]
Configure Authentication mode to ldap_auth.
Login with a LDAP user 'test'
Login with admin and go to Administration --> Users --> Select  'test' to delete
Prompt message is 'You do not have the proper privileges to perform the action'
It should be "Current user is a LDAP user, it can not be removed in Harbor admin console"

**Comment by stonezdj** [comment]
![screen shot 2017-11-10 at 2 34 05 pm](https://user-images.githubusercontent.com/2696760/32646721-8c0e4de2-c5b3-11e7-89f2-81152b5be19c.png)

**Comment by reasonerjt** [comment]
I think we better not show the delete button at all.

**Comment by steven-zou** [comment]
User should not removed when auth mode is 'ldap_auth'.
Disable delete button when auth mode is 'ldap_auth'.

**Comment by pengpengshui** [comment]
the latest version of harbor has already disabled delete when auth mode is 'ldap_auth'
