### ISSUE TITLE
Use button instead of link

### ISSUE THREAD

**Issue by stonezdj** [vmware/harbor#3595]
In Harbor admin console, create a non exist user and it will prompt this user does not exist,
Click cancel button, the prompt message is 
"Some changes are not saved yet, Do you want to cancel? No Yes "
The "No", "Yes" is in hyper link style. 

Refer
http://uxmovement.com/buttons/when-to-use-a-button-or-link/

**Comment by stonezdj** [comment]
![screen shot 2017-11-10 at 2 34 54 pm](https://user-images.githubusercontent.com/2696760/32646909-7c734ac6-c5b4-11e7-84d4-c44520f168d5.png)

**Comment by lweitzman** [comment]
when not a system wide warning, the proper Clarity way to provide actions in the warning message is to have text in the right side that is underlined and not capitalized. see: https://vmware.github.io/clarity/documentation/alerts

**Comment by steven-zou** [comment]
It's clarity style. Won't change!
