### ISSUE TITLE
go get github.com/mqu/openldap  in mac os  error

### ISSUE THREAD

**Issue by zhwenh** [vmware/harbor#36]
mac os 10.11.1 
go get github.com/mqu/openldap
show error  Cannot compile
# github.com/mqu/openldap
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/add-modify-delete.go:48:9: warning: 'ldap_add_ext_s' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1160:1: note: 'ldap_add_ext_s' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/add-modify-delete.go:54:9: warning: 'ldap_modify_ext_s' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1430:1: note: 'ldap_modify_ext_s' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/add-modify-delete.go:60:9: warning: 'ldap_rename_s' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1467:1: note: 'ldap_rename_s' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/add-modify-delete.go:65:9: warning: 'ldap_mods_free' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:2014:1: note: 'ldap_mods_free' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/add-modify-delete.go:166:23: warning: 'ldap_delete_s' is deprecated: first deprecated in OS X 10.10 - use ldap_delete_ext_s [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1363:1: note: 'ldap_delete_s' has been explicitly marked deprecated here
# github.com/mqu/openldap
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/openldap.go:86:23: warning: 'ldap_bind_s' is deprecated: first deprecated in OS X 10.10 - use ldap_sasl_bind_s [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1275:1: note: 'ldap_bind_s' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/openldap.go:101:23: warning: 'ldap_initialize' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1541:1: note: 'ldap_initialize' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/openldap.go:123:23: warning: 'ldap_search_s' is deprecated: first deprecated in OS X 10.10 - use ldap_search_ext_s [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1925:1: note: 'ldap_search_s' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/openldap.go:139:23: warning: 'ldap_start_tls_s' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1569:1: note: 'ldap_start_tls_s' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/openldap.go:153:23: warning: 'ldap_unbind' is deprecated: first deprecated in OS X 10.10 - use ldap_unbind_ext [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1967:1: note: 'ldap_unbind' has been explicitly marked deprecated here
# github.com/mqu/openldap
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/options-errors.go:71:42: warning: 'ldap_err2string' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1384:1: note: 'ldap_err2string' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/options-errors.go:88:23: warning: 'ldap_get_option' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:978:1: note: 'ldap_get_option' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/options-errors.go:105:23: warning: 'ldap_set_option' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:984:1: note: 'ldap_set_option' has been explicitly marked deprecated here
# github.com/mqu/openldap
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/results.go:111:23: warning: 'ldap_count_entries' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1633:1: note: 'ldap_count_entries' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/results.go:126:23: warning: 'ldap_count_messages' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1588:1: note: 'ldap_count_messages' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/results.go:140:23: warning: 'ldap_count_values_len' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1826:1: note: 'ldap_count_values_len' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/results.go:155:42: warning: 'ldap_first_attribute' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1804:1: note: 'ldap_first_attribute' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/results.go:169:42: warning: 'ldap_first_entry' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1623:1: note: 'ldap_first_entry' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/results.go:183:42: warning: 'ldap_first_message' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1578:1: note: 'ldap_first_message' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/results.go:197:42: warning: 'ldap_get_dn' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1662:1: note: 'ldap_get_dn' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/results.go:212:42: warning: 'ldap_get_values_len' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1820:1: note: 'ldap_get_values_len' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/results.go:226:23: warning: 'ldap_msgfree' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1869:1: note: 'ldap_msgfree' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/results.go:241:42: warning: 'ldap_next_attribute' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1810:1: note: 'ldap_next_attribute' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/results.go:255:42: warning: 'ldap_next_entry' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1628:1: note: 'ldap_next_entry' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/results.go:269:42: warning: 'ldap_next_message' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1583:1: note: 'ldap_next_message' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/results.go:287:23: warning: 'ldap_result' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1853:1: note: 'ldap_result' has been explicitly marked deprecated here
/Users/wenhuazhang/GoProjects/src/github.com/mqu/openldap/results.go:298:2: warning: 'ldap_value_free_len' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ldap.h:1830:1: note: 'ldap_value_free_len' has been explicitly marked deprecated here

**Comment by reasonerjt** [comment]
Hi, openldap is implemented via cgo, so it's possible some c library on mac is not compatible with linux.  
That's why we build the code in docker container, see Deploy/docker-compose.yml

**Comment by zhwenh** [comment]
thank  a  lot

**Comment by reasonerjt** [comment]
Closing this issue
