### ISSUE TITLE
proposal: provide easier support for external database

### ISSUE THREAD

**Issue by paulczar** [vmware/harbor#3600]
The MySQL/Mariadb database is going to be an issue for HA environments, and many cloud environments will want to use the cloud's native mysql service ( RDS etc ).

Proposal:

The existing database image is reduced a minimal alpine image with mysqlclient installed and the database schema files added. When run this image would connect to the actual database and perform any install/upgrade operations to the database schema via a script that takes db url/credentials from env and exits out.

The default mariadb database image can then be used in docker-compose and kubernetes manifests.  An external database could be used instead by passing its url and credentials to the provided image to be set up.

**Comment by yixingjia** [comment]
@paulczar  Thanks for the proposal.

Currently Harbor support config external database , you can  specify the follow properties in the harbor.cfg. 

db_host = mysql
#The port of mysql database host
db_port = 3306
#The user name of mysql database
db_user = root


For HA part we are already start the work to refactor Harbor to adapt to HA scenario. 

You can find more information by https://github.com/vmware/harbor/issues/3582
https://github.com/vmware/harbor/issues/3197

**Comment by yixingjia** [comment]
Close as Harbor already support external database.

**Comment by paulczar** [comment]
I understand Harbor already supports external database, my request was to make it easier. 

Currently to use an external database I need to grab the files from https://github.com/vmware/harbor/tree/master/make/photon/db and perform the migrations.  What I want to see is a docker image that contains just these files that I can mount as a volume to a mysql image to run them from there.
