### ISSUE TITLE
Docker login failed in OVA

### ISSUE THREAD

**Issue by stonezdj** [vmware/harbor#3603]
**Steps to reproduce**

1) Deploy harbor by OVA.
2) Copy /data/ca_download/harbor_ca.crt  and install it refer: https://github.com/vmware/harbor/blob/master/docs/configure_https.md
3) docker login to harbor registry
docker login 10.160.28.233
Username: admin
Password: 
Error response from daemon: Get https://10.160.28.233/v2/: Get https://sc-rdops-vm01-dhcp-28-233.eng.abc.com/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: x509: certificate is valid for HarborManager, not sc-rdops-vm01-dhcp-28-233.eng.abc.com

**Root Cause**

The hostname is configured with dns name in harbor.cfg
hostname = sc-rdops-vm01-dhcp-28-233.eng.abc.com 

But the server.crt is generated with IP Address:10.160.28.233, they should be consistent.

**Comment by wy65701436** [comment]
also needs to name the crt with ca.crt.

**Comment by wy65701436** [comment]
fixed.
