### ISSUE TITLE
Respect Proxy PR failing Code coverage

### ISSUE THREAD

**Issue by everydaynerd** [vmware/harbor#3606]
I opened a PR for fixing proxy issues, but the code coverage bot declined.  I added 5 lines of code, so not sure how to get this PR in front of a human to help get this approved.  Any help is appreciated.  We're running this fix in house and it works wonderfully.

https://github.com/vmware/harbor/pull/3474

Thanks again.

**Comment by reasonerjt** [comment]
You can ignore the coverage issue it is not accurate in some cases.

**Comment by everydaynerd** [comment]
OK great. So how does the PR get reviewed?  Thanks!
