### ISSUE TITLE
Stop pushing new image versions to existing tags

### ISSUE THREAD

**Issue by everett-toews** [vmware/harbor#3607]
I really appreciate you making the Harbor images available to all but please stop pushing new image versions to existing tags.

Twice now my deployments have been broken because of changes to images that have been pushed to existing tags.

1. The [vmware/clair:v2.0.1-photon](https://hub.docker.com/r/vmware/clair/tags/) image was updated with commit https://github.com/vmware/harbor/commit/e9d1b89936a1e04cfddf3bd758a2d708b8be0684 which changed the expected location of the config file.
1. The [vmware/registry:2.6.2-photon](https://hub.docker.com/r/vmware/registry/tags/) image was updated with commit https://github.com/vmware/harbor/commit/6f335bdb1a7d4099fb20cb743ef1e0c0b5c80b32 which changed the expected location of the config file.

In both cases a breaking change (the location of the config file) was made but the image was pushed to an existing tag, instead of a new tag being created.

And, yes, I know I can pin images to a sha like [this](https://stackoverflow.com/questions/32046334/what%C2%B4s-the-sha256-code-of-a-docker-image) but it's something consumers of the Harbor images shouldn't have to do as pushing a new image version to an existing tag is an anti-pattern.

Please consider creating a versioning scheme for your image tags to prevent this in the future. Something like `registry:2.6.2-harbor-1.2.3` or whatever makes sense for the project.

**Comment by reasonerjt** [comment]
@everett-toews Thanks for this issue, we're working to refine this process, but we are close to a release and this build process may not be introduced to this release, so in next couple of weeks there may be some subtle change to the image on docker hub again.

But in future this will be fixed.

**Comment by wy65701436** [comment]
Working on this item, 80% is done.

**Comment by wy65701436** [comment]
Done with PR, under review.

**Comment by wy65701436** [comment]
Close it as fixed.
