### ISSUE TITLE
Any advice about upgrading Harbor version from v0.5.0 to v1.2.x

### ISSUE THREAD

**Issue by moooofly** [vmware/harbor#3615]
The production environment of my place is running with Harbor version v0.5.0 for a long while. After doing some researches in a few days, I want to upgrade Harbor version from v0.5.0 to v1.2.0+.

I'v not found any advice or warnings about what I should do or not, so my question is: is there a guideline I can follow??

tks a lot.

**Comment by cbarzu** [comment]
Hi @moooofly,

at my company we are using 4 Harbor instances, each one is storing more than 1500 images / 300GB. Following the official migrating guide we had no problem. But in our case, we migrate from 0.5 to 1.1 and from 1.1 to 1.2.

**Comment by reasonerjt** [comment]
Thanks @cbarzu 
If no further issues here I'm closing this one.

**Comment by moooofly** [comment]
FYI, I did harbor version upgrade from v0.5.0 to v1.2.2 directly last night.

It is running good till now..

tks again.

@cbarzu @reasonerjt
