### ISSUE TITLE
[Question]Project name too long

### ISSUE THREAD

**Issue by cbarzu** [vmware/harbor#3617]
Hi everybody, a quick question.

At our company for each kubernetes namespace we are creating a harbor project, but recently we got this problem trying to create one.

`Project name is illegal in length. (greater than 2 or less than 30)`

Do you know any way to workaround this? If I submit a PR to increase the length of the field, would you approve it?

Thanks and regards,
Claudiu

**Comment by reasonerjt** [comment]
@cbarzu  thanks for raising this issue.
We are really close to next release, so it may not be accepted for 1.3
but yes we'll review and consider to extend the length.

**Comment by reasonerjt** [comment]
@ninjadq Could you also update the length of the project to 255?

**Comment by ninjadq** [comment]
fixed on #4072

**Comment by parin921996** [comment]
I am seeing same issue when it try to use project name consist of more than 30 characters. I am using Harbor v1.4.0 . 
![image](https://user-images.githubusercontent.com/8746551/36911798-a986d238-1e12-11e8-8bad-cb70d12d8252.png)
Error I am seeing when I try following request 
`curl 'https://HARBOR_ADRESS/api/projects' -u username:password -H 'Content-Type: application/json' -d '{"project_name":"abcdefghigklmnopqabcdefghigklmnopq","metadata":{"public":"true"}}'`
Response 
`invalid request: Project name is illegal in length. (greater than 2 or less than 30)`
