### ISSUE TITLE
Dashboard Top 10 Repositories Count Error

### ISSUE THREAD

**Issue by wemeya** [vmware/harbor#362]
From the below picture, you can see the count is 8 and 6.
![image](https://cloud.githubusercontent.com/assets/12540577/16188996/c97f2c5c-370a-11e6-838b-146289f7c6dc.png)

Then I click Projects->myproject->logs, and return to Dashboard, you can see below. Besides, I find the logs in the db increased.

![image](https://cloud.githubusercontent.com/assets/12540577/16189169/99a2eab8-370b-11e6-8b89-2b6543d4a4f1.png)

**Comment by reasonerjt** [comment]
could you check the response of API?

**Comment by wemeya** [comment]
@reasonerjt 
The API returns:
![image](https://cloud.githubusercontent.com/assets/12540577/16189700/4a9c5ad2-370e-11e6-80da-d2cac85c23e7.png)
I think the reason is when the user view the logs, it inserts into db a pull log.

**Comment by reasonerjt** [comment]
probably same root cause as #372

**Comment by wknet123** [comment]
fixed.
