### ISSUE TITLE
./install.sh => ERROR: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:

### ISSUE THREAD

**Issue by aduntong** [vmware/harbor#3627]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
Docker: 

> Client:
>  Version:      17.09.0-ce
>  API version:  1.32
>  Go version:   go1.8.3
>  Git commit:   afdb6d4
>  Built:        Tue Sep 26 22:41:23 2017
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      17.09.0-ce
>  API version:  1.32 (minimum version 1.12)
>  Go version:   go1.8.3
>  Git commit:   afdb6d4
>  Built:        Tue Sep 26 22:42:49 2017
>  OS/Arch:      linux/amd64
>  Experimental: false

docker-compose:

> docker-compose version 1.17.1, build 6d101fb
> docker-py version: 2.5.1
> CPython version: 2.7.13
> OpenSSL version: OpenSSL 1.0.1t  3 May 2016

2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.

> see attached, I just updated hostname and db_password.

3)Log files, you can get them by package the /var/log/harbor/ .

> no log of harbor at /var/log/harbor/ yet.

After update the harbor.cfg file, and run ./install.sh, I get the following error.
The environment is centos 7 on Aliyun Cloud.
Thank you.
Adun

> [Step 4]: starting Harbor ...
> Creating network "harbor_harbor" with the default driver
> ERROR: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-a97ac2fc79ca -j RETURN: iptables: No chain/target/match by that name.
>  (exit status 1))

**Comment by aduntong** [comment]
Attach harbor.cfg in a zip.

[harbor.zip](https://github.com/vmware/harbor/files/1481534/harbor.zip)

**Comment by reasonerjt** [comment]
The error happened when docker creates the network.
Could you check: https://github.com/moby/moby/issues/16816

**Comment by aduntong** [comment]
Thanks a lot.
The issue is resolved by restart docker daemon.
systemctl restart docker

**Comment by nurhun** [comment]
restarting docker service solved it for me.
