### ISSUE TITLE
Tips is not friendly when creating new project.

### ISSUE THREAD

**Issue by wemeya** [vmware/harbor#363]
See picture below, it says project name is invalid. Why invalid, because it already exists or the name must be in lower case? The user can't figure out what the reason is.
![image](https://cloud.githubusercontent.com/assets/12540577/16189609/b2e44092-370d-11e6-89bd-e7ca2b6f34c2.png)

**Comment by wemeya** [comment]
Also, the checkbox of public is not in middle. Should it locate a little lower look better?

**Comment by wknet123** [comment]
fixed.

**Comment by wemeya** [comment]
fixed.
