### ISSUE TITLE
scan schedule time cannot input seconds

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#3631]
Version v1.2.0-219-gdb6def3
scan schedule time cannot input seconds
![schedule](https://user-images.githubusercontent.com/23101283/32944789-aabfb474-cbcb-11e7-86f9-97a5d435da31.PNG)

**Comment by steven-zou** [comment]
assigned to @pengpengshui to fix

**Comment by pengpengshui** [comment]
no need to fix
