### ISSUE TITLE
issues deploying standalone harbor tile

### ISSUE THREAD

**Issue by quantumraindrop** [vmware/harbor#3633]
The Harbor tile in its current state seems to demand the presence of ERT when non-default values are used in `harbor-tile.yml`.

Please see the following conversation between Merlin and Pivotal's QE team:

> @naderziada
We are trying to add a radio button to the tile optionally get information from cf or from user input. harbor-tile.yml file with that change attached
But we are currently stuck on trying to install the tile in ops manager without having cf-runtime present. We get an error saying you must configure one or more PCF components before installing
Trying to figure out how PKS tile can get installed without cf-runtime
>
>harbor-tile.yml
Processing
31 kB yml
>
>ReplyCopy linkCopied
Nov 16, 1:57 pm
NZ
@naderziada
The error message You must configure one or more PCF components before installing is because there were properties in the harbor-tile.yml file that were not set by the form or had any default values.
Once I set defaults for everything, I'm now able to deploy the tile without cf-runtime being present

Any thoughts on what may be causing this?

**Comment by steven-zou** [comment]
Add option selector later. @quantumraindrop

**Comment by steven-zou** [comment]
Checked, no cf dependency issue existing in the current harbor tile, you can try : https://storage.cloud.google.com/harbor-releases/harbor-0.0.7.pivotal?_ga=2.249141127.-1619785408.1507777217

Close this issue as not reproduced
