### ISSUE TITLE
项目下有8个镜像，开启同步后harbor-jobservice无限重启

### ISSUE THREAD

**Issue by MRwangyd** [vmware/harbor#3635]
[Uploading registry.log…]()

使用的Harbor V1.1.2版本
一个新项目创建的时候没有开启复制规则，使用一段时间后需要同步到另一个Harbor中，开启规则后harbor-jobservice始终处于Restarting状态。
关闭这个项目的复制，在library中上传一个镜像测试，复制同步没有问题。
是由于一次同步太多镜像压力过大，还是其他的原因
请大神支持一下

**Comment by MRwangyd** [comment]
[Uploading jobservice.log…]()

**Comment by MRwangyd** [comment]
![image](https://user-images.githubusercontent.com/27405334/32999865-83ee5164-cddf-11e7-9c37-aaf4d562fd00.png)

**Comment by MRwangyd** [comment]
会一直刷这样的日志，然后jobservice就处于jobservice状态了

**Comment by MRwangyd** [comment]
[jobservice.log](https://github.com/vmware/harbor/files/1486329/jobservice.log)

**Comment by MRwangyd** [comment]
[registry.log](https://github.com/vmware/harbor/files/1486330/registry.log)

**Comment by MRwangyd** [comment]
有人在看么

**Comment by ywk253100** [comment]
It's a known issue and has been fixed in 1.2.0. Please upgrade your Harbor to the latest version.

**Comment by MRwangyd** [comment]
哦  好的，

**Comment by MRwangyd** [comment]
昨天已经将版本升级了，我这个项目有9个镜像，只同步了5个，复制任务显示已经全部完成，但是对端只接收到5个，

**Comment by MRwangyd** [comment]
![image](https://user-images.githubusercontent.com/27405334/33051109-5134b1ea-cea3-11e7-9ff8-ab26aafde97a.png)

**Comment by MRwangyd** [comment]
这个是源端的

**Comment by MRwangyd** [comment]
![image](https://user-images.githubusercontent.com/27405334/33051131-67c4b8e2-cea3-11e7-9991-ea8c0c5cbf2e.png)

**Comment by MRwangyd** [comment]
这个是对端的

**Comment by MRwangyd** [comment]
![image](https://user-images.githubusercontent.com/27405334/33051153-83ed74f0-cea3-11e7-9ef7-146a52fbc95c.png)

**Comment by MRwangyd** [comment]
这个是源端看到的日志，都显示完成了

**Comment by MRwangyd** [comment]
[jobservice.log](https://github.com/vmware/harbor/files/1489773/jobservice.log)

**Comment by MRwangyd** [comment]
这个是源端jobserveice的日志，请协助解决

**Comment by MRwangyd** [comment]
而且我现在推送到Harbor的镜像，在页面上不展示也没有同步了

**Comment by MRwangyd** [comment]
![image](https://user-images.githubusercontent.com/27405334/33051964-86c5561c-cea7-11e7-9cd4-7123c5c3a7d0.png)
push成功了，在其他机器上pull也可以下载，但是页面上看不到，
![image](https://user-images.githubusercontent.com/27405334/33052003-a591d0f2-cea7-11e7-9ad8-c53a8d059e1a.png)

**Comment by MRwangyd** [comment]
同步的目标端也看不到，pull不到

**Comment by MRwangyd** [comment]
测试了几遍，只是页面展示看不到镜像，实际镜像已经push到仓库，已经同步到对端

**Comment by MRwangyd** [comment]
我这边测试了一下，同步问题从1.1.2升级到1.2.2版本已经解决，但是返现1.2.2版本页面中项目展示的镜像数与实际不符，新上传的在页面上不显示

**Comment by ywk253100** [comment]
Please upgrade your database first.
