### ISSUE TITLE
To remove this image label you must first remove it from the Notary

### ISSUE THREAD

**Issue by jiananjiang** [vmware/harbor#3641]
I type in the command line：
notary -s https//192.168.56.1034443 --tlscacert ~ / .docker / tls / 192.168.56.103 \ 4443 / harbor_ca.crt -d ~ / .docker / trust remove -p 192.168.56.103/library/busybox  0.1

But the command line prompts me：

bash notary command not found

Do I need to install notary component? and  the container is started as follows：

[root@centjiang make]# docker ps -a
CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS                    PORTS                                                              NAMES
54a911abe478        vmware/harbor-jobservice:dev              "/harbor/harbor_jobse"   3 hours ago         Up 15 minutes                                                                                harbor-jobservice
c3aead6bcd0f        vmware/nginx-photon:1.11.13               "nginx -g 'daemon off"   3 hours ago         Up 16 minutes             0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:4443->4443/tcp   nginx
272aee39bc50        vmware/notary-photon:server-0.5.0         "/usr/bin/env sh -c '"   3 hours ago         Up 15 minutes                                                                                notary-server
1acf905af7bd        vmware/harbor-ui:dev                      "/harbor/harbor_ui"      3 hours ago         Up 15 minutes                                                                                harbor-ui
d27e720e245e        vmware/notary-photon:signer-0.5.0         "/usr/bin/env sh -c '"   3 hours ago         Up 15 minutes                                                                                notary-signer
0ba7435517f2        vmware/clair:v2.0.1-photon                "/docker-entrypoint.s"   3 hours ago         Up 16 minutes (healthy)   6060-6061/tcp                                                      clair
7f549ca059b2        vmware/harbor-notary-db:mariadb-10.1.10   "/docker-entrypoint.s"   3 hours ago         Up 15 minutes             3306/tcp                                                           notary-db
7a91db730f40        vmware/harbor-adminserver:dev             "/harbor/harbor_admin"   3 hours ago         Up 16 minutes                                                                                harbor-adminserver
d63421c34560        vmware/registry:2.6.2-photon              "/entrypoint.sh serve"   3 hours ago         Up 16 minutes (healthy)   5000/tcp                                                           registry
4402dcb004f2        vmware/postgresql:9.6.4-photon            "/entrypoint.sh postg"   3 hours ago         Up 16 minutes             5432/tcp                                                           clair-db
a6ac5a0164ac        vmware/harbor-db:dev                      "docker-entrypoint.sh"   3 hours ago         Up 15 minutes             3306/tcp                                                           harbor-db
5231d242e920        vmware/harbor-log:dev                     "/bin/sh -c 'crond &&"   3 hours ago         Up 16 minutes             127.0.0.1:1514->514/tcp

**Comment by reasonerjt** [comment]
It's not a component it's a client binary, download it from here:
https://github.com/theupdateframework/notary/releases

On how to use notary please refer to https://github.com/theupdateframework/notary/blob/master/docs/command_reference.md
and 
https://github.com/vmware/harbor/blob/master/docs/use_notary.md
