### ISSUE TITLE
Harbor Opsman 'Tile' Should Allow deployment w/out setting up UAA

### ISSUE THREAD

**Issue by virtmerlin** [vmware/harbor#3645]
Opsman Version: Opsman 2.0 Build 148
Harbor Tile Version: harbor-0.0.6.pivotal

Desired Behaviour:   User should be bale to select UAA or Local auth
Obsewrved Behaviour:  Tile forces config of UAA auth backend

Notes:

Guys we want to offer option to use local or other auth for Harbor tile.

**Comment by jessehu** [comment]
Thanks @virtmerlin. Will do it soon.  cc @steven-zou

**Comment by jessehu** [comment]
UAA config is removed by #3700 . It will be added later once implemented.
