### ISSUE TITLE
生产环境harbor登陆不上

### ISSUE THREAD

**Issue by YangShuailing** [vmware/harbor#3646]
问题描述：
测试环境安装／测试正常，
生产安装正常，测试环境连生产一直连不上（测试和生产有防火墙），端口（80/443）已开，telnet，ping，wget都是可以的；／etc/docker/daemon.json 已经加
1. 页面添加复制目标主机报错日志
[ERROR] [transfer.go:383]: an error occurred while checking existence of blob sha256:eedd55ebc566c965995f23b2f55e8684cf42bf09e2a5b6dfa967300766c82433 of library/tomcat7:latest on http://172.27.128.11: Head http://172.27.128.11/v2/library/tomcat7/blobs/sha256:eedd55ebc566c965995f23b2f55e8684cf42bf09e2a5b6dfa967300766c82433: Get http://szdockerrepo01/service/token?scope=repository%3Alibrary%2Ftomcat7%3Apull&service=harbor-registry: dial tcp: lookup szdockerrepo01: Temporary failure in name resolution
2.docker login本地日志

Nov 21 10:11:01 registry dockerd: time="2017-11-21T10:11:01.898530657+08:00" level=info msg="Error logging in to v2 endpoint, trying next endpoint: Get https://172.27.128.11/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
Nov 21 10:11:06 registry dockerd: time="2017-11-21T10:11:06.901786113+08:00" level=info msg="Error logging in to v2 endpoint, trying next endpoint: Get http://172.27.128.11/v2/: EOF"
Nov 21 10:11:11 registry dockerd: time="2017-11-21T10:11:11.904335979+08:00" level=info msg="Error logging in to v1 endpoint, trying next endpoint: Get https://172.27.128.11/v1/users/: unexpected EOF"
Nov 21 10:11:27 registry NetworkManager[740]: <warn>  (vethe71eb8d): failed to find device 20282 'vethe71eb8d' with udev
Nov 21 10:11:27 registry NetworkManager[740]: <info>  (vethe71eb8d): new Veth device (carrier: OFF, driver: 'veth', ifindex: 20282)
Nov 21 10:11:27 registry kernel: br-83034399e866: port 2(vethef853ed) entered disabled state
Nov 21 10:11:27 registry kernel: br-83034399e866: port 2(vethef853ed) entered disabled state
Nov 21 10:11:27 registry kernel: device vethef853ed left promiscuous mode
Nov 21 10:11:27 registry kernel: br-83034399e866: port 2(vethef853ed) entered disabled state
Nov 21 10:11:27 registry NetworkManager[740]: <info>  (vethef853ed): link disconnected
Nov 21 10:11:27 registry kernel: XFS (dm-6): Unmounting Filesystem
Nov 21 10:11:27 registry NetworkManager[740]: <warn>  (vethe71eb8d): failed to disable userspace IPv6LL address handling
Nov 21 10:11:27 registry NetworkManager[740]: <info>  (br-83034399e866): bridge port vethef853ed was detached
Nov 21 10:11:27 registry NetworkManager[740]: <info>  (vethef853ed): released from master br-83034399e866
Nov 21 10:11:27 registry NetworkManager[740]: <warn>  (vethef853ed): failed to disable userspace IPv6LL address handling
Nov 21 10:11:27 registry kernel: XFS (dm-6): Mounting V4 Filesystem
Nov 21 10:11:27 registry kernel: XFS (dm-6): Ending clean mount
Nov 21 10:11:27 registry kernel: device vethe9b5f18 entered promiscuous mode
Nov 21 10:11:27 registry kernel: IPv6: ADDRCONF(NETDEV_UP): vethe9b5f18: link is not ready
Nov 21 10:11:27 registry kernel: br-83034399e866: port 2(vethe9b5f18) entered forwarding state
Nov 21 10:11:27 registry kernel: br-83034399e866: port 2(vethe9b5f18) entered forwarding state
Nov 21 10:11:27 registry NetworkManager[740]: <warn>  (vethbca5142): failed to find device 20284 'vethbca5142' with udev
Nov 21 10:11:27 registry NetworkManager[740]: <info>  (vethbca5142): new Veth device (carrier: OFF, driver: 'veth', ifindex: 20284)
Nov 21 10:11:27 registry NetworkManager[740]: <warn>  (vethe9b5f18): failed to find device 20285 'vethe9b5f18' with udev
Nov 21 10:11:27 registry NetworkManager[740]: <info>  (vethe9b5f18): new Veth device (carrier: OFF, driver: 'veth', ifindex: 20285)
Nov 21 10:11:27 registry NetworkManager[740]: <info>  (br-83034399e866): bridge port vethe9b5f18 was attached
Nov 21 10:11:27 registry NetworkManager[740]: <info>  (vethe9b5f18): enslaved to br-83034399e866
Nov 21 10:11:28 registry NetworkManager[740]: <warn>  (vethbca5142): failed to disable userspace IPv6LL address handling
Nov 21 10:11:28 registry NetworkManager[740]: <info>  (vethe9b5f18): link connected
Nov 21 10:11:28 registry kernel: IPv6: ADDRCONF(NETDEV_CHANGE): vethe9b5f18: link becomes ready
Nov 21 10:11:42 registry kernel: br-83034399e866: port 2(vethe9b5f18) entered forwarding state
Nov 21 10:12:01 registry dockerd: time="2017-11-21T10:12:01.912107627+08:00" level=info msg="Error logging in to v1 endpoint, trying next endpoint: Get http://172.27.128.11/v1/users/: EOF"
Nov 21 10:12:01 registry dockerd: time="2017-11-21T10:12:01.912199235+08:00" level=error msg="Handler for POST /v1.29/auth returned error: Get http://172.27.128.11/v1/users/: EOF"

**Comment by ywk253100** [comment]
Please make sure the hostname `szdockerrepo01` can be resolved inside the container `jobservice`.

**Comment by reasonerjt** [comment]
@YangShuailing does your issue remain?

**Comment by YangShuailing** [comment]
replace “szdockerrepo01”with IP，and it does work，3Q
