### ISSUE TITLE
'Test LDAP Server' button does not work well

### ISSUE THREAD

**Issue by jessehu** [vmware/harbor#3653]
After installing offline installer harbor.v1.2.0-229, login as 'admin', go to 'Administrator' -> 'Configuration' -> 'Authentication' Tab, select 'LDAP' Click 'Test LDAP Server', it reports error like "Auth Mode is not LDAP ..."
Expected: it should do the LDAP connection test

**Comment by steven-zou** [comment]
Assigned to @ninjadq to fix.

**Comment by ninjadq** [comment]
discussed with @steven-zou we think this may not a bug. Because you are editing LDAP config and these config not saved yet.

**Comment by mlh78750** [comment]
If we're not fixing, then can we close this issue.

**Comment by reasonerjt** [comment]
@mlh78750 we still need to discuss and confirm with the creator of this issue.

**Comment by mlh78750** [comment]
I just saw the wontfix label. I'm fine either way, but if we decide we're not fixing, lets close the issue.

**Comment by reasonerjt** [comment]
@stonezdj I think it's a bug in ping ldap api, please work with Jesse to investigate.

**Comment by reasonerjt** [comment]
Fixed in #3796
