### ISSUE TITLE
The configuration "Project Creation" shoud not belong to "Authentication"

### ISSUE THREAD

**Issue by jessehu** [vmware/harbor#3654]
After installing offline installer harbor.v1.2.0-229, login as 'admin', go to 'Administrator' -> 'Configuration' -> 'Authentication' Tab, it contains 3 items:

Auth Mode
Project Creation
Allow Self-Registration

The configuration "Project Creation" should not belong to "Authentication", because it's kind of privilege setting. Maybe move it under 'System Settings' or 'Users' panel?

**Comment by steven-zou** [comment]
Assigned to @pengpengshui to fix.

**Comment by pengpengshui** [comment]
@lweitzman  what do you think about this suggestion?

**Comment by lweitzman** [comment]
sorry missed this ... i don't have strong feelings either way. like mentioned above, its a privilege settings and that could be seen as a type of authentication.  and on the other hand, we have privilege settings under system settings for the "repository read only" flag

**Comment by pengpengshui** [comment]
Don't do anything and close the issue.
