### ISSUE TITLE
Author and Creation time is "NA" on index page

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#366]
Need to double check if the API is working as expected.
<img width="1212" alt="screen shot 2016-06-20 at 6 23 08 pm" src="https://cloud.githubusercontent.com/assets/2390463/16190877/11f94f90-3714-11e6-9d47-e32b4a469b42.png">

**Comment by wknet123** [comment]
fixed.

**Comment by reasonerjt** [comment]
verified.
