### ISSUE TITLE
ERROR: Tag v1.3.0-rc1 not found

### ISSUE THREAD

**Issue by iRobertas** [vmware/harbor#3668]
Hello, I tried to install harbor,  used installation_guide, but getting error.
ERROR: Tag v1.3.0-rc1 not found in repository docker.io/vmware/harbor-log

OS: CentOS 7.4.1708 (Core)
python-2.7.5
docker version: 1.12.6
docker-compose version: 1.17.1

/var/log/messages
Nov 22 15:19:46 localhost dockerd-current: time="2017-11-22T15:19:46.909503686+02:00" level=info msg="{Action=harbor_harbor, Username=user, LoginUID=1000, PID=3734}"
Nov 22 15:19:46 localhost dockerd-current: time="2017-11-22T15:19:46.935600990+02:00" level=error msg="Handler for GET /v1.22/images/vmware/harbor-log:v1.3.0-rc1/json returned error: No such image: vmware/harbor-log:v1.3.0-rc1"
Nov 22 15:19:46 localhost dockerd-current: time="2017-11-22T15:19:46.937865052+02:00" level=info msg="{Action=create, Username=user, LoginUID=1000, PID=3734}"
Nov 22 15:19:48 localhost dockerd-current: time="2017-11-22T15:19:48.446609922+02:00" level=error msg="Attempting next endpoint for pull after error: manifest unknown: manifest unknown"
Nov 22 15:19:50 localhost dockerd-current: time="2017-11-22T15:19:50.864782818+02:00" level=error msg="Not continuing with pull after error: Tag v1.3.0-rc1 not found in repository docker.io/vmware/harbor-log"

I checked https://hub.docker.com/r/vmware/harbor-log/tags/ and v1.3.0-rc1 tag is missing.

**Comment by reasonerjt** [comment]
@iRobertas what installer did you use to see this error?

**Comment by iRobertas** [comment]
@reasonerjt I downloaded https://github.com/vmware/harbor/releases/tag/v1.3.0-rc1. Now when you asked, I checked and saw that first link v1.3.0-rc1 is "Pre-release". Sorry for the inconvenience.

**Comment by reasonerjt** [comment]
@iRobertas but which link did you use?  Did you use online or offline installer?

**Comment by wy65701436** [comment]
if you use the online installer, please try it again. I have reviewed all the rc1 images.

**Comment by iRobertas** [comment]
Yes I was using online installer https://storage.googleapis.com/harbor-releases/harbor-online-installer-v1.3.0-rc1.tgz

Tried now, all works.
