### ISSUE TITLE
add admin password confirmation inputbox in config form of harbor

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#3675]
add admin password confirmation inputbox in config form of harbor

**Comment by steven-zou** [comment]
@virtmerlin "freeze_on_deploy: true" will be in next build.

**Comment by steven-zou** [comment]
Confirm with @virtmerlin, this function is 'nice to have' one.

**Comment by jessehu** [comment]
"freeze_on_deploy: true" at the admin_password properties is already added.
I think we can move this out of pks-0.8.

**Comment by reasonerjt** [comment]
We decided it's won't fix.
