### ISSUE TITLE
中文显示bug

### ISSUE THREAD

**Issue by robinwangrubin** [vmware/harbor#3690]
最新稳定版本Harbor 1.2.2
![image](https://user-images.githubusercontent.com/24934186/33252216-b39b77dc-d377-11e7-84c5-3658e24499b5.png)
![image](https://user-images.githubusercontent.com/24934186/33252225-c07d2f18-d377-11e7-836a-7bbabce52d8f.png)

**Comment by stonezdj** [comment]
请提供截图？

**Comment by steven-zou** [comment]
@ninjadq 

  Please take a look! Thanks!

**Comment by ninjadq** [comment]
@robinwangrubin 
Are you install v1.2.2 from scratch or upgraded from other earlier version?

**Comment by robinwangrubin** [comment]
@ninjadq  Yes i am, I update v1.2.2 From v 1.1.1

**Comment by robinwangrubin** [comment]
@ninjadq  Do you have any update solutions to solve this problem?

**Comment by ninjadq** [comment]
This issue seems like i18n file not upgrade properly. You should clear cache first if it still exist you can try to restore and upgrade again.
