### ISSUE TITLE
clair environment couldn't connect internet

### ISSUE THREAD

**Issue by like-inspur** [vmware/harbor#3694]
I create an environment that couldn't connect internet, so I can't analyze image vulnerability. How can I create a local CVE environment? Thank you !

**Comment by reasonerjt** [comment]
Hi,
Please see this doc.
https://github.com/vmware/harbor/blob/master/docs/import_vulnerability_data.md

**Comment by like-inspur** [comment]
@reasonerjt I used clear.sql and vulnerability.sql to load data, but found error in postgres.log

Nov 28 09:58:26 172.19.11.1 postgres[10946]: STATEMENT:
Nov 28 09:58:26 172.19.11.1 postgres[10946]: #011#011#011INSERT INTO Layer(name, engineversion, parent_id, namespace_id, created_at)
Nov 28 09:58:26 172.19.11.1 postgres[10946]: #011    VALUES($1, $2, $3, $4, CURRENT_TIMESTAMP)
Nov 28 09:58:26 172.19.11.1 postgres[10946]: #011    RETURNING id
Nov 28 09:58:29 172.19.11.1 postgres[10946]: ERROR:  duplicate key value violates unique constraint "layer_name_key"
Nov 28 09:58:29 172.19.11.1 postgres[10946]: DETAIL:  Key (name)=(2d32f5a9c26458c19cc9d07241b4655a20f0a3af6b682ed587c00fee4b11a038) already exists

Is there any bug in dumping vulnerability database, and is it affects  scanning vulnerabilities in images

**Comment by yixingjia** [comment]
@like-inspur this issue seems that there are clair cron jobs are running while you import the offline data.

You can try to run the clear.sql again to make the db to clean statue and reload the data.

By the way please make sure you use clair 2.0.1 release to dump the data.

**Comment by like-inspur** [comment]
@yixingjia It seems that there are clair scan all image job are running while I export sql, so how can I to suspend or stop scan job, then I can export right sql to import the offline data to another environment.

**Comment by yixingjia** [comment]
@like-inspur 
You can disable the scan all by Configuration>Vulnerablity and disable the scan ALL temporally. 

After you successfully export the data, you can enable the daily scanning.
