### ISSUE TITLE
Use Bosh link to propagate Harbor's CA

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#3701]
Need following ways to support configuring Harbor's Cert:

When hostname is set: 
1)User can choose to use ops manager to generate cert based on hostname, using CA from ops manager
2)User can generate a certificate offline and paste in the text area, if he's using a self-signed CA, the CA cert also needs to be pasted.

When hostname is not set:
Bosh should generate a certificate using the IP.

The CA should be exported via "bosh link" in order to be consumed by PKS.

**Comment by virtmerlin** [comment]
We might want to mod this story for .8 target.  The approach we validated is to pass the Harbor cert's signing CA (external CA or Opsman's root CA if it gens the harbor cert) to the Opsman Director tiles security field will get the job done for .8,  so we wont need the certs exposed via a bosh `provides` for .8.   We may decide at later date we need as we progress with PKS 1.0 & later deliverables.   Can u guys remove the 0.8 tag on this issue for now?

**Comment by jessehu** [comment]
tag 0.8  removed. Steven will give more tech solution on it.

**Comment by reasonerjt** [comment]
@jessehu shall we close this?  I don't think we'll want more work on this.

**Comment by jessehu** [comment]
I will verify it on PKS 0.5.0 and update this.

**Comment by steven-zou** [comment]
Based on current solution, we don't need pass cert/ca info to other deployment via bosh links. This one can be closed. @reasonerjt @jessehu

**Comment by reasonerjt** [comment]
OK, let's open bug if we see any problem in pks 0.5 tile.
