### ISSUE TITLE
Cant log into Harbor via docker login - HTTP or HTTPS

### ISSUE THREAD

**Issue by robotica72** [vmware/harbor#3717]
Tried Harbor v1.3.0-rc2 and 1.2.2.
Engine: 1.12.6
Compose: 1.17.0, build ac53b73

Sorry I cant post config files - too much internal information, but no matter what config I try - HTTP or HTTPS all docker login attempts fail : v1/users/: Forbidden

I can curl with http and http to receive:

<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <title>Harbor</title>
    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="favicon.ico?v=2">
</head>

<body style="overflow-y: hidden;">
    <harbor-app>
        <div class="spinner spinner-lg app-loading">
            Loading...
        </div>
    </harbor-app>

<link rel="stylesheet" href="/static/clarity-ui.min.css">
<link rel="stylesheet" href="/static/clarity-icons.min.css">
<link rel="stylesheet" href="/static/styles.css">

<script src="/static/mutationobserver.min.js"></script>
<script src="/static/custom-elements.min.js"></script>
<script src="/static/clarity-icons.min.js"></script>

<script src="/static/build.min.js"></script>
</body>

</html>

but if I do try to curl to the url with /v1 returns information but /v1/user throws a 404 
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.11.13</center>
</body>
</html>

I can edit the daemon.json to disable v1 so a /v2 throws errors as well:
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.11.13</center>
</body>
</html>

From this information - Any ideas??

**Comment by reasonerjt** [comment]
@robotica72 
What command did you use to login and curl?  and what's the output?

**Comment by reasonerjt** [comment]
Close due to inactivity.
