### ISSUE TITLE
Deploying Harbor Tile sometimes failed

### ISSUE THREAD

**Issue by jessehu** [vmware/harbor#3719]
Deploying Harbor Tile sometimes failed, both on 1st deploy and afterward deploy. It failed due to harbor job started failed, or dockerd can't stop or other reasons.
Need to find out the root cause, and fix it by PKS 0.8.
@steven-zou @reasonerjt

**Comment by steven-zou** [comment]
Discussed with @jessehu , the root cause may from the 'docker login' checking in status_check script with spec.ip.

**Comment by steven-zou** [comment]
Reassigned this issue to @jessehu as he is taking look at it.

**Comment by jessehu** [comment]
"the root cause may from the 'docker login' checking in status_check script with spec.ip." -> this bug is already fixed. We will use https://github.com/vmware/harbor/issues/3735 to track other random deployment failure due to timeout.
