### ISSUE TITLE
Fix the intermittent failure of Project Level Policy Public in test case.

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#3725]

**Comment by reasonerjt** [comment]
@wy65701436 could you specify in which testcase do you see intermittent failures?

**Comment by wy65701436** [comment]
Test Case - Project Level Policy Public

**Comment by reasonerjt** [comment]
@wy65701436 I think we better provide more information in this issue, such as: which build is impacted?  
@sigsbee  is it being worked on?

**Comment by sigsbee** [comment]
closed, add logout and login step to avoid it since it only happens in autotest
