### ISSUE TITLE
Harbor Opsman Tile should not allow HTTP

### ISSUE THREAD

**Issue by virtmerlin** [vmware/harbor#3727]
**Given**: Alan (PRE) has a Harbor tile & Ops Manager
**When**: Harbor tile is configured
**Then**: HTTP should not be presented as a configurable option

**Acceptance Criteria**:

- HTTP is not allowed for Harbor tile config

Target:  PKS 0.8

**Comment by jessehu** [comment]
Steven already made a patch to not showing the HTTP/HTTPS config on Tile UI, but hard-coded to HTTPS.
