### ISSUE TITLE
1.3.0.rc2 online installer link is broken

### ISSUE THREAD

**Issue by odg0318** [vmware/harbor#3729]
I tried to download 1.3.0.rc2-online-installer but it failed.
The link to download seems to be broken on below page.
https://github.com/vmware/harbor/releases/tag/v1.3.0-rc2

https://storage.googleapis.com/harbor-releases/harbor-`onine`-installer-v1.3.0-rc2.tgz

When I change `onine` to `online`, it works fine.

Best regards

**Comment by wy65701436** [comment]
Close it as fixed. Thanks.
