### ISSUE TITLE
Harbor UI fails to load ID or email when there are several users on VCSA

### ISSUE THREAD

**Issue by lgayatri** [vmware/harbor#3731]
@reasonerjt 

Build: https://storage.googleapis.com/vic-product-ova-releases/vic-v1.3.0-rc2-2628-9e2a95b6.ova
I have about 1000 users on VCSA and one such user is lgayatri1

![image](https://user-images.githubusercontent.com/25006749/33482177-caa485a6-d6bd-11e7-96f5-0093f3a6cf0c.png)

For a given project in Harbor , I cannot add this user as UI fails to load all matched user names. There are double entries for the users shown.

![image](https://user-images.githubusercontent.com/25006749/33482169-c1b1e826-d6bd-11e7-91eb-0234dc91f4ea.png)

Harbor logs attached.
[Harbor.zip](https://github.com/vmware/harbor/files/1521530/Harbor.zip)

**Comment by reasonerjt** [comment]
@lgayatri in VIC this part belongs to Admiral, I opened: https://github.com/vmware/admiral/issues/225
