### ISSUE TITLE
MAINTAINER is deprecated, new format does not display in UI

### ISSUE THREAD

**Issue by nlowe** [vmware/harbor#3733]
The [`MAINTAINER` directive is deprecated](https://docs.docker.com/engine/reference/builder/#maintainer-deprecated). If you add a `maintainer` label as suggested by the documentation, it is not displayed in the UI:

```dockerfile
FROM busybox
LABEL maintainer="Nathan.Lowe@hyland.com"
```

![image](https://user-images.githubusercontent.com/794251/33507116-fb551e88-d6c0-11e7-8f27-5a14ae2c7074.png)

The `MAINTAINER` directive seems to be supported still:

```dockerfile
FROM busybox
MAINTAINER "Nathan.Lowe@hyland.com"
```

![image](https://user-images.githubusercontent.com/794251/33507112-f75e4c14-d6c0-11e7-9232-e8657fb809ae.png)

(Pardon the table formatting, seems to be related to #3275 )

We are running harbor `1.2.0`.

**Comment by ywk253100** [comment]
Fixed by #3790.
