### ISSUE TITLE
404 returned when calling harbor API

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#3734]
Deploy Harbor with tile

Curl host/api/system 404 returned
Curl ui8080/api/system data returned 
docker ps
  starting timestamps of image containers may diff 1 min
The images might be started by compose in different times

**Comment by reasonerjt** [comment]
Is it a tile only issue?

**Comment by reasonerjt** [comment]
I can't reproduce in non-tile environment.
root cause for this issue is probably #3735

**Comment by reasonerjt** [comment]
Closing as this seems a problem in bosh release, and it has been fixed.
