### ISSUE TITLE
Harbor Ops Manager Tile re-branding

### ISSUE THREAD

**Issue by virtmerlin** [vmware/harbor#3743]
Given: Alan (PRE) has a Harbor tile & Ops Manager
When: Harbor tile is configured
Then: Harbor Tile should be labels "VMware Harbor Registry"

Acceptance Criteria:

- Rename Tile string to "VMware Harbor Registry"
- Set Tile Version == to current release of Harbor (assume 1.3.0)

**Comment by steven-zou** [comment]
Rebrand to "VMware Harbor Registry"
Version changed to "1.3.0", but with pre suffix "rc". Once it's ready for release, the version can be changed to 1.3.0

**Comment by steven-zou** [comment]
Latest tile build is : https://storage.cloud.google.com/harbor-ci-pipeline-store/tile-releases/harbor-tile-1.3.0-rc.2.pivotal?authuser=2&_ga=2.54310376.-1192896719.1510815040

**Comment by steven-zou** [comment]
Work done, close it
