### ISSUE TITLE
Investigate building Harbor into a helm chart.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#3746]

**Comment by nuzz** [comment]
I've created a helm chart for Harbor over the past few weeks that I could submit as a PR. It needs a little more refinement but it goes from zero to running instance pretty quickly (that includes certificate and secret creation). So far I've tested it on AWS, GKE and AKS clusters.

**Comment by reasonerjt** [comment]
Yes please! 
You can PR it to `/contrib` and we can take over to refine it!

Thanks a lot!!

**Comment by nuzz** [comment]
Yep, I haven't forgotten about this, I should be able to submit a first draft to /contrib by early next week.

**Comment by reasonerjt** [comment]
It's an ongoing effort, move to Sprint 24.

**Comment by xeor** [comment]
Glad to see this being done! Would it end up as an official helm chart, or it's own repo?

**Comment by nuzz** [comment]
@xeor unclear, but I will submit here first and then maybe we can discuss how it would live in the official helm repo. Sorry I haven't submitted this yet, I have been on holiday and there are some proprietary things I need to strip out of this chart before I can submit.

**Comment by ghaskins** [comment]
@nuzz Very interested in a Helm Chart for Harbor myself.  If you get it to a point that you'd be willing to share, I would be grateful (and can possibly help refine).

**Comment by reasonerjt** [comment]
Here's a prototype:
https://github.com/reasonerjt/harbor-helm

It'll be refined intermittently.
Removing the milestone as this is a continuous effort and there's no target date for this work.

**Comment by owenhaynes** [comment]
@reasonerjt is it possible for this helm chart not to include the databases servers or at least make it optional, want to be able to use cloud sql, or one of the other few mysql servers I have running.

**Comment by nuzz** [comment]
Sorry for the delay, I was on holiday/moving and had to generalize a few things with the helm/bootstrap but I've made a PR here for the full thing: https://github.com/vmware/harbor/pull/3987

**Comment by reasonerjt** [comment]
Thanks @nuzz！

**Comment by orenam** [comment]
gr8 initiative

**Comment by reasonerjt** [comment]
Closing this issue as we've pushed the code of helm chart into `contrib` folder and further work is tracked by #4247
