### ISSUE TITLE
Investigate and design the final job service architecture

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#3747]
**Issue:**

1. Multiple job services cannot co-work.

**Requirement**

1. Job service itself should be stateless.
2. Be able to reschedule job to live job services instances when a job service instance is down
3. Job status data should be saved to a persistent storage( DB or Etcd, or Redis or others)

**Effort estimate**
1.5 month/person ?

Old disscussions: 
Issue: 
In HA mode When a node restart/startup it will fetch all the none finished replication jobs and start execute the jobs, even the jobs are already executed by other work nodes. This is because we don’t store job executor’s information. 

To fix the issue we need to solve the follow two item:
1> Identify a method to distinguish whether a job has an executor
2> Identify a method to re-dispatch job when the executor is no response for a long time(either dead or stuck)

Solutions 1

1> Use db to store the executor information 
2> each harbor worker node will have process to check the timeout/stuck job and take the job owner.

Solution 2
1> use a shared keystore eg( redis) to store the jobs already have an executor 
2> the work will be response update the jobs in the keystore when job status changes.
3> the jobs in keystore will have a expire time to deal with case that executor dead( when expire time reach it will removed from keystore and other work can automatically take over

Solution 3>
bind the jobs to worker node, jobs will continue execute when work node recovered.

**Comment by reasonerjt** [comment]
There's solution 4, just let the job run twice, the status may look weird but eventually things should look OK :)

**Comment by yixingjia** [comment]
That will need more testing, especially when there are more than 2 nodes , the situation will be even worse. So we should not consider do nothing unless we can't finish either of the solution 1-3.

**Comment by steven-zou** [comment]
The design doc is located here: https://confluence.eng.vmware.com/display/HARBOR/New+Job+Service

I'll close this issue now.
