### ISSUE TITLE
Offline Installer (in pre-release) Incomplete

### ISSUE THREAD

**Issue by Lerentis** [vmware/harbor#3748]
Hey there,

i wanted to try out harbor with the pre-release offline installer, but noticed some things:

- the mysql image in the docker-compose points to vmware/harbor-db, but the image provided in the offline installer is called vmware/mariadb-photon
- vmware/harbor-jobservice is missing in the offline installer or is called different
- vmware/nginx-photon is missing in the offline installer or is called different

docker images 
```
vmware/harbor-log           v1.3.0-rc2          2b39f3fd1f2f        6 days ago          199MB
vmware/harbor-ui            v1.3.0-rc2          9034e7649eaa        6 days ago          203MB
vmware/harbor-adminserver   v1.3.0-rc2          2662cdda3a55        6 days ago          166MB
vmware/postgresql           9.6.5-photon        a5c79b0473d9        2 weeks ago         285MB
vmware/registry             2.6.2-photon        c38af846a0da        2 weeks ago         240MB
vmware/mariadb-photon       10.2.10             eaaae71dea19        2 weeks ago         586MB
vmware/notary-photon        server-0.5.1        b8cc51024379        2 weeks ago         247MB
vmware/photon               1.0                 efceca798007        2 weeks ago         129MB
```
harbor-offline-installer-v1.3.0-rc2

**Comment by wy65701436** [comment]
We cannot reproduce it on our side.

Can you show me the install console log? 
How do you install the offline？

**Comment by sigsbee** [comment]
```
root@harbor:~# sha1sum harbor-offline-installer-v1.3.0-rc2.tgz
b5af1568088c77400150169afb993467d7ac0d74  harbor-offline-installer-v1.3.0-rc2.tgz
root@harbor:~# ls -l harbor-offline-installer-v1.3.0-rc2.tgz
-rw-r--r-- 1 root root 929062516 Nov 29 04:55 harbor-offline-installer-v1.3.0-rc2.tgz
```

**Comment by Lerentis** [comment]
didn't check for file integrity and noticed a wrong hash in the offline installer i downloaded yesterday. downloaded the offline installer again and verified the checksum, and now it is complete. 
thank you for the fast replys and sorry for the false alarm :/
