### ISSUE TITLE
Unable to add an AWS ECR Registry as replication endpoint

### ISSUE THREAD

**Issue by sec9** [vmware/harbor#3749]
Harbor version 1.2.2.
I try to add an Amazon ECR registry as a  replication endpoint but it fails when testing connection.
log from ui.log: 
```
[DEBUG] [security.go:231]: got user information from session
[DEBUG] [security.go:240]: using local database project manager
[DEBUG] [security.go:242]: creating local database security context...
[DEBUG] [tokenauthorizer.go:197]: scopses parsed from request: 
[WARNING] schemes [{basic map[realm:https://xxxx.dkr.ecr.us-west-1.amazonaws.com/ service:ecr.amazonaws.com]}] are unsupportted
[WARNING] empty realm, skip
[DEBUG] [transport.go:50]: 401 | GET https://xxxx.dkr.ecr.us-west-1.amazonaws.com/v2/
```
Any help appreciate.

**Comment by reasonerjt** [comment]
@sec9 This is working as design, as currently the replication works only between Harbor instances.

**Comment by DavidRodHub** [comment]
Are there future plans to enhance harbor to replicate to Amazon ECR registry or other non-harbor docker-registries?

**Comment by pappnase99** [comment]
Agreed, this would be a nice feature. Any comment on this?

**Comment by Bharathkumarraju** [comment]
Any update on this guys?
