### ISSUE TITLE
Installed release 1.3.0-rc2, now as admin, not able to make projects public

### ISSUE THREAD

**Issue by DavidRodHub** [vmware/harbor#3750]
docker --version
Docker version 17.09.0-ce, build afdb6d4

Harbor Version v1.3.0-rc2

Upgraded from rel 1.2.0 to rel 1.3.0-r2 successfully which included migrating the database first.   As admin,  I can create new projects which defaults to private.  But if I try to change them to public, the drop down doesn't give me the public option. It presents the following for private project.:
- Replication Rule
- Make Private
- Delete 

With release 1.2.0, I didn't have this problem.

**Comment by DavidRodHub** [comment]
Install release 1.3.0-r1. Get the same behavior.    Created a project named "test" and selected  make private even though the access level was already Private.   Got message "Your request cannot be completed because the object does not exist"

**Comment by ninjadq** [comment]
Hi @DavidRodHub ,
Could you provide your data in Project and ProjectMetadata table?

**Comment by wy65701436** [comment]
Please package and upload harbor logs.

**Comment by DavidRodHub** [comment]
Attached harbor home dir, harbor data dir, and harbor logs.

[harbor-1.3.0-rc2_logs_case-3750.tar.gz](https://github.com/vmware/harbor/files/1540967/harbor-1.3.0-rc2_logs_case-3750.tar.gz)
[harbor-1.3.0-rc2_logs_case-3750.tar.gz](https://github.com/vmware/harbor/files/1540969/harbor-1.3.0-rc2_logs_case-3750.tar.gz)
[data_case-3750.tar.gz](https://github.com/vmware/harbor/files/1540979/data_case-3750.tar.gz)

**Comment by ninjadq** [comment]
Hi, @DavidRodHub 
I can't reproduce you issue on my environments. 

It seems the other part of harbor not upgrade properly although your db schema is upgraded to the latest version.

**Comment by DavidRodHub** [comment]
Hi @ninjadq 

This time I did a clean install of 1.3.0-rc2 (no migration) and do not have the issue on a new installation.  I will try another upgrade again from 1.2.0 to 1.3.0-rc2 and let you know the results.

Thanks for your help and support.

**Comment by DavidRodHub** [comment]
Question about which migrator-image to use. I'm upgrading from 1.2 to 1.3-rc2. The guide says the following:

Before upgrading Harbor, perform database migration first. The migration tool is delivered as a docker image, so you should pull the image from docker hub. Replace [tag] with the release version of Harbor (e.g. 1.2) in the below command:  docker pull vmware/harbor-db-migrator:[tag]

The example given (e.g. 1.2).  Should I use tag 1.3 because that's what I want to upgrade to?  Please confirm because I believe the last migrator image I used was tag 1.3.

**Comment by DavidRodHub** [comment]
Attempted another try at the upgrade using harbor-db-migrator:1.3.   Still have the same issue with not being able to change the repositories to public.  Noticed when doing the upgrade i get "[ERROR] Missing system table mysql.roles_mapping; please run mysql_upgrade to create it".    I attached 2 files, that shows the output of the database backup and  database upgrade.  Followed the steps in the migration guide.   Now I believe the database migration might be the issue.  

[Database_backup_output.txt]
(https://github.com/vmware/harbor/files/1550099/Database_backup_output.txt)
[database_upgrade_output.txt](https://github.com/vmware/harbor/files/1550100/database_upgrade_output.txt)

**Comment by ninjadq** [comment]
Hi @DavidRodHub,
I reproduced you issue on my env. There is a UI bug in 1.3-rc2. please using 1.3-rc3 instead.

while 1.2 to 1.3, we changed our db from Mysql to MariaDB. There are lit bit compatible issues when data backed in 1.3 restore to 1.2. #3737 

So if your current version is 1.2, then backup & restore data using  vmware/harbor-db-migrator:1.2. And when upgrade db schema using vmware/harbor-db-migrator:1.3

**Comment by DavidRodHub** [comment]
Did as suggested. Restored back to 1.2 and then upgraded the db using vmware/harbor-db-migrator:1.3.  Then installed  1.3-rc3 .  Still have the same issue.  Harbor was  installed successfully and started .   

When doing the backup of 1.2 before the upgrade to 1.3.  I ran this command:
--> docker run -ti --rm -e DB_USR=root -e DB_PWD=root123 -v /opt/data/database:/var/lib/mysql -v /opt/backup/harbor/backup:/harbor-migration/backup vmware/harbor-db-migrator:1.3 backup

See this error bewlo when doing the backup command.  Should I be seeing errors at this point.

[Note] InnoDB: Cannot open '/var/lib/mysql/ib_buffer_pool' for reading: No such file or directory
[Note] Plugin 'FEEDBACK' is disabled.
[Note] Server socket created on IP: '::'.
[ERROR] Missing system table mysql.roles_mapping; please run mysql_upgrade to create it
[ERROR] Incorrect definition of table mysql.event: expected column 'sql_mode' at position 14 to have type set('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','IGNORE_BAD_TABLE_OPTIONS','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','POSTGRESQL','ORACLE','MSSQL','DB2','MAXDB','NO_KEY_OPTIONS','NO_TABLE_OPTIONS','NO_FIELD_OPTIONS','MYSQL323','MYSQL40','ANSI','NO_AUTO_VALUE_ON_ZERO','NO_BACKSLASH_ESCAPES','STRICT_TRANS_TABLES','STRICT_ALL_TABLES','NO_ZERO_IN_DATE','NO_ZERO_DATE','INVALID_DATES','ERROR_FOR_DIVISION_BY_ZERO','TRADITIONAL','NO_AUTO_CREATE_USER','HIGH_NOT_PRECEDENCE','NO_ENGINE_SUBSTITUTION','PAD_CHAR_TO_FULL_LENGTH'), found type set('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','NOT_USED','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','POSTGRESQL','ORACLE','MSSQL','DB2','MAXDB','NO_KEY_OPTIONS','NO_TABLE_OPTIONS','NO_FIELD_OPTIONS','MYSQL323','MYSQL40','ANSI','NO_AUTO_VALUE_ON_ZERO','NO_BACKSLASH_ESCAPES','STRICT_TRANS_TABLES','STRICT_A
[ERROR] mysqld: Event Scheduler: An error occurred when initializing system tables. Disabling the Event Scheduler.
[Warning] Failed to load slave replication state from table mysql.gtid_slave_pos: 1146: Table 'mysql.gtid_slave_pos' doesn't exist
[Note] Reading of all Master_info entries succeded
[Note] Added new Master_info '' to hash table
[Note] mysqld: ready for connections.
Version: '10.2.10-MariaDB'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Source distribution
Performing backup...
Backup performed.

**Comment by DavidRodHub** [comment]
Also, I need to add that I seeing this issue on 2 different machines.

**Comment by ninjadq** [comment]
I mean you should using `vmware/harbor-db-migrator:1.2` to backup & restore DB for your harbor 1.2
Using `vmware/harbor-db-migrator:1.3` when you wanna upgrade db schema from 1.2 to 1.3

**Comment by DavidRodHub** [comment]
Do I need to upgrade the db schema to 1.3 in order to install 1.3-rc3?  Or can I leave the db schema at 1.2, and upgrade harbor to 1.3-rc3.   Reading the migration doc, when upgrading from version 1.2 to 1.3, requires the db schema to be upgraded.  My problem is when I upgrade the schema to 1.3, I'm getting errors as reported in previous comments.  Are the error not to worry about?

**Comment by ninjadq** [comment]
Yes, you need upgrade 1.3-rc3 first. you can ignore error messages you mentioned when upgrading scheme.
