### ISSUE TITLE
1.3.0 RC2 chmod and indentions 

### ISSUE THREAD

**Issue by stalhood** [vmware/harbor#3751]
Photon OS 2.0 w/ Docker 17.06.0 and docker-compose 1.17.1

1. Due to Python 3.6, the chmod commands need to to change to 0o600 instead of 0600

2. Starting on line 370, the chmod commands have indention issues because tabs and spaces were both used.

**Comment by wy65701436** [comment]
Thanks, we will provide fix.

**Comment by reasonerjt** [comment]
@wy65701436  let's try to fix it in vic-1.3 timeframe.

**Comment by reasonerjt** [comment]
@wy65701436 This is fixed right?

**Comment by wy65701436** [comment]
Close it as fixed.
