### ISSUE TITLE
Change db_host in harbor.cfg, but it doesn't work

### ISSUE THREAD

**Issue by kidnet** [vmware/harbor#3752]
When I install Harbor, as my request, I need change the configuration of db_host in harbor.cfg and follow the instraction stop and remove all containers then run script to reload the config , but it doesn't work.
I have to manually change the configuration of mysql_host in /data/config/config.json.then start container, the new part works .

**Comment by reasonerjt** [comment]
That's by design, the `db_host` attribute is for HA deployment (we'll provide in future) only.

**Comment by reasonerjt** [comment]
https://github.com/vmware/harbor/blob/master/make/harbor.cfg#L112
