### ISSUE TITLE
I cann't push some images into the harbor's registry,always retrying，get stuck in pushing, and EOF.

### ISSUE THREAD

**Issue by YangShuailing** [vmware/harbor#3753]
[2017-12-07.zip](https://github.com/vmware/harbor/files/1537659/2017-12-07.zip)

[2017-12-07.zip](https://github.com/vmware/harbor/files/1537658/2017-12-07.zip)
[root@szautodeploy5 ~]# docker push 192.168.9.117/rancher/agent:latest   
The push refers to a repository [192.168.9.117/rancher/agent]
da9f45a1a82f: Layer already exists 
b3e14099ad4a: Layer already exists 
131926e86d5d: Layer already exists 
34c32605199e: Pushing [==================================================>]  2.048kB
5972ebe5b524: Pushing [==================================================>]  3.072kB
3d515508d4eb: Pushing [==================================================>]  4.608kB
bbe6cef52379: Pushing  11.78kB
87f743c24123: Pushing [==================================================>]  15.87kB
32d75bc97c41: Pushing [==================================================>]  134.6MB
EOF
1)Version of docker engine and docker-compose.
docker:17.05
docker-compose:1.17.0
harbor:1.2.2
2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.

harbor.cfg only modify：
hostname = 192.168.9.117

3)Log files, you can get them by package the /var/log/harbor/ .

attachment

**Comment by reasonerjt** [comment]
Are you seeing EOF for all images or only `192.168.9.117/rancher/agent:latest`?
Does it fail at the same point everytime?

**Comment by YangShuailing** [comment]
Some successes and others fail like this，fail at different point ，i don't know why？

**Comment by ywk253100** [comment]
The logs contain no information about your pushing operation. Could you reproduce the error, package the logs and upload it again?

**Comment by YangShuailing** [comment]
I know the reason now, i start dockerd "nohup docker daemon -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock &" and proxy , i remove them all ,and work fine. Thanks

**Comment by rizwan-kh** [comment]
I am getting the same error while pushing to my private harbor registry. I tried tweaking nginx and registry config but to no avail. 
It retries for a certain time and then gives an EOF message and fails to upload. Uploading a end snippet of the registry logs with masked values.

Let me know if more details are required. The log file contains the version details

[registry.log](https://github.com/vmware/harbor/files/2158199/registry.log)
