### ISSUE TITLE
push image error unauthorized: authentication required

### ISSUE THREAD

**Issue by 272909106** [vmware/harbor#3756]
docker 1.12.3
harbor v1.1.2
harbor server 10.100.17.94
the auth token in  /root/.docker/config.json 
{
	"auths": {
		"10.100.17.94": {
			"auth": "YWRtaW46SGFyYm9yMTIzNDU="
		}
	}
------------------------------------------------------------
when i run command  : `docker push 10.100.17.94/library/study-center-service:latest`

the error : unauthorized: authentication required

ui log:

```
Dec  8 10:09:20 localhost ui[981]: 2017-12-08T02:09:20Z [DEBUG] [token.go:35]: URL for token request: /service/token?account=admin&scope=repository%3Alibrary%2Fsurvey-service%3Apull&service=harbor-registry
Dec  8 10:09:20 localhost ui[981]: 2017-12-08T02:09:20Z [DEBUG] [creator.go:206]: scopes: [repository:library/survey-service:pull]
Dec  8 10:09:20 localhost ui[981]: 2017-12-08T02:09:20Z ## [WARNING] Failed to get secret cookie, error: http: named cookie not present
Dec  8 10:09:20 localhost ui[981]: 2017-12-08T02:09:20Z [DEBUG] [authenticator.go:59]: Current AUTH_MODE is db_auth
Dec  8 10:09:20 localhost ui[981]: 2017-12-08T02:09:20Z [DEBUG] [authutils.go:46]: scopes: [repository:library/survey-service:pull]
Dec  8 10:09:20 localhost ui[981]: 2017-12-08T02:09:20Z [DEBUG] [authutils.go:87]: user: admin, access: &{repository  library/survey-service [push * pull]}
Dec  8 10:09:20 localhost ui[981]: 2017/13/08 02:09:20 #033[1;34m[router.go:829][D] | GET        | /service/token                           | 111.569658ms     | match      | /service/token                           | #033[0m
Dec  8 10:09:20 localhost ui[981]: 2017-12-08T02:09:20Z [DEBUG] [notification.go:102]: receive an event: 

```
this question not often

**Comment by reasonerjt** [comment]
in the log, docker client requests a token for `library/survey-service` not the one you are trying to push.

**Comment by 272909106** [comment]
so every project 
docker login 10.100.17.94/library/study-center-service
like this the  error will solve
@reasonerjt

**Comment by reasonerjt** [comment]
@272909106 
no, you only need to `docker login 10.100.17.94`
and run `docker push 10.100.17.94/library/study-center-service:latest`

What I'm saying is that the log you attached doesn't match the command you run.

**Comment by reasonerjt** [comment]
@272909106 any update?
