### ISSUE TITLE
fail to auth MS ActiveDirectory with ldap-auth

### ISSUE THREAD

**Issue by blackjack550** [vmware/harbor#3757]
i try to auth my user with mode ldap-auth.but i cant login successful. pls help me check my configuretion.Are there some thing wrong in this?
my harbor config:
![image](https://user-images.githubusercontent.com/4535903/33749772-9e4ddbc2-dc0a-11e7-8c13-bd4921348e68.png)

the info is ok  in nginx-ldap-auth:
url ldap://xxxx:389/OU=总部,OU=enterprise,DC=intra,DC=nsfocus,DC=com?samaccountname?sub?(objectClass=user);
        binddn user@intra.nsfocus.com;
        binddn_passwd xxxx;
        group_attribute uniquemember;
        group_attribute_is_dn on;
    }
i got error:
LDAP search errorLDAP Result Code 32 "No Such Object": 0000208D: NameErr: DSID-031001CD, problem 2001 (NO_OBJECT), data 0, best match of:
Dec  8 03:10:43 172.18.0.1 ui[21757]: #011'OU=؜²¿,OU=Enterprise,DC=intra,DC=nsfocus,DC=com'
Dec  8 03:10:43 172.18.0.1 ui[21757]: 
Dec  8 03:10:43 172.18.0.1 ui[21757]: 2017-12-08T03:10:43Z [WARNING] ldap search fail: LDAP Result Code 32 "No Such Object": 0000208D: NameErr: DSID-031001CD, problem 2001 (NO_OBJECT), data 0, best match of:

**Comment by reasonerjt** [comment]
probably because the OU has Chinese characters?

**Comment by blackjack550** [comment]
I dont know，but i had configre this information in another system ,Its worked. do you wanna fixed it?

**Comment by reasonerjt** [comment]
We need to understand what's the root cause first, could you try with a DN without Chinese?

**Comment by blackjack550** [comment]
I reslove this problem.i found that sAMAccountName is option.i change my config to that。As shown below.
![image](https://user-images.githubusercontent.com/4535903/33755309-249e8bde-dc2b-11e7-8d6a-66218441a29e.png)

**Comment by blackjack550** [comment]
i test the problem by ldapadmin tools. i can login DN without OU.and then i try to do this in harbor,too。the big problem is LDAP UID。i has been failed in uid/cn/email。
