### ISSUE TITLE
Support clair on Harbor K8s installation

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#3758]
Request from Harbor community user.
It will be nice that the K8S installation can support clair.

**Comment by owenhaynes** [comment]
I Tried manually installing Clair to try this. But the ui service is hard coded to talk to a database called postgres and the same user. So if you want to share a database server between many different projects your out of luck. 

I noticed this is the same for most of the harbor configuration, there are a few hard coded names.

**Comment by reasonerjt** [comment]
I use this repo to store the code of Harbor helm chart: https://github.com/reasonerjt/harbor-helm.

I'll try to enable Clair in the chart but currently there's no ETA.

**Comment by neith00** [comment]
indeed hostname endpoints are hardcoded.
We had to create custom namespaces and database for harbor in order to avoid collision.
Would be nice if it could be configurable

**Comment by jessehu** [comment]
@neith00 it's tracked by https://github.com/vmware/harbor/issues/3250

**Comment by jessehu** [comment]
Clair is supported in the latest Harbor Helm Chart 1.4.0 beta https://github.com/vmware/harbor/tree/master/contrib/helm/harbor
