### ISSUE TITLE
Harbor Admin should be able to reset other user's password

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#3759]
Some request from community that Admin should be able to reset other user's password.

**Comment by moooofly** [comment]
yes, because mail function is not always available.

**Comment by steven-zou** [comment]
add to rel 1.6 candidate

**Comment by lweitzman** [comment]
the ui hangs when changing the password to the existing password.
![screen shot 2018-05-31 at 10 18 17 am](https://user-images.githubusercontent.com/626032/40788087-378260d4-64bd-11e8-9966-f5e703bca5cc.png)
