### ISSUE TITLE
删除用户后再添加会导致失败

### ISSUE THREAD

**Issue by fsword** [vmware/harbor#376]
提示用户邮箱已存在，查看数据库记录，发现user表的相关记录标记为 delete=1

**Comment by hainingzhang** [comment]
this works as design. A user cannot be physically deleted due to auditting reason. @fsword

**Comment by xiaods** [comment]
yeah. alternative, we can use reactive workflow to guide user to re-active the mail

**Comment by hainingzhang** [comment]
Will change this in next release. Closing it for now. Please reopen if needed.
