### ISSUE TITLE
镜像复制x509错误

### ISSUE THREAD

**Issue by xiaoxiaoMZ** [vmware/harbor#3767]
原仓库：https://10.199.204.138
目标仓库：https://10.199.204.159
Docker version 1.13.1 , docker-compose version 1.13.0 
在原仓库配置镜像复制，
复制管理-测试连接时 出现如下错误：
![image](https://user-images.githubusercontent.com/29880446/33766940-af6e4afe-dc5a-11e7-8eb9-f7b9907da7c2.png)
![image](https://user-images.githubusercontent.com/29880446/33766884-733555dc-dc5a-11e7-89e8-bc9e68bd32c9.png)

![image](https://user-images.githubusercontent.com/29880446/33767088-3abb2ab4-dc5b-11e7-8a5f-9dca1f80379d.png)

**Comment by reasonerjt** [comment]
您好出错原因是10.119.204.159那台机器上的证书有问题 （不包含IP SAN）
请尝试在配置管理页面中关掉证书验证：
https://github.com/vmware/harbor/blob/release-1.2.0/docs/img/new_remote_cert.png

**Comment by reasonerjt** [comment]
@xiaoxiaoMZ  Hi, any update on this issue?

**Comment by xiaoxiaoMZ** [comment]
It's done, You helped. Thank you @reasonerjt
