### ISSUE TITLE
Ping replication endpoint failure when there's only one saved endpoint.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#3770]
When there's only one saved target when creating a new replication rule the target will be selected by default.  As in attachment.

But when I click "Test Connection" the browser sent the following request:
```
POST /api/targets/ping

{ "endpoint": "", "name": "", "username": "", "password": "", "insecure": false, "type": 0, "id": 1 }

```

But backend returns http status 400, error text: `empty endpoint`

**Comment by ywk253100** [comment]
@pengpengshui Only `id` property should be passed to the backend API, or other properties will replace the values stored in the database.

**Comment by reasonerjt** [comment]
If we can't make it to 1.3 release, we need a reasonable workaround.

**Comment by mdubya66** [comment]
Per @reasonerjt, making this a ship stopper.

**Comment by luguang** [comment]
We are not the last yet to reach RTM of VIC 1.3, so please fix this asap.
