### ISSUE TITLE
Support Clair in HA installation

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#3777]
In HA mode we make Clair as Optional. 
Currently when setup Harbor HA, it will only include the harbor core service. 
We should support setup an standalone Clair instance to work with the Harbor HA cluster.

1> modify Clair db export port ( currently Harbor UI will access clair DB to check vulnerability update info)
2> Clair don't support Auth. So the  Clair instance must be deployed in the management network. 

1>We should at least provide an document that instruct user how to setup Clair to work with Harbor HA P0
2> We should make Clair also HA with Harbor core service P1

**Comment by yixingjia** [comment]
![hanext](https://user-images.githubusercontent.com/1715683/33979891-63164842-e0e1-11e7-809f-c4320444d449.png)

**Comment by yixingjia** [comment]
1> Clair endpoint is hardcode in Harbor code, we need to make the clair endpoint configurable if we want Harbor cluster share the same Clair instance.

2> The PostgreSQL DB address is hard code in Harbor. We need to make it configurable and also expose the DB port so that all the harbor node in the cluster can connect.

**Comment by yixingjia** [comment]
code merged. Close as fixed

**Comment by gunboe** [comment]
Hi everybody,

What and where are the enviroment values to set up and configure an external Clair service?
I mean, I'd like to config a Clair server out of Harbor, but I don't know what and where must I have change to make it. Can some one help me?
I have already a Harbor v1.8.3 installed with a external Database.
Tks
Gunther
