### ISSUE TITLE
Updating tile configuration with SSL certificate causes deployment error

### ISSUE THREAD

**Issue by singhshwetaQE** [vmware/harbor#3779]
Harbor tile version: v0.0.48

**Steps to reproduce -**
Deploy tile
Update Certificate- used SSL
Click apply

**Result:**
Expected - Harbor should be updated/redeployed with new changes
Actual - Deployment errors out 

Note: This error only happened when SSL certificate was used and reconfigure tile,  in case of new External/Ops manager certificate change it worked fine.

**Logs:**
[harbor-app-3e502db1fc97.zip](https://github.com/vmware/harbor/files/1553567/harbor-app-3e502db1fc97.zip)
[harbor-app-d61fa1449922.zip](https://github.com/vmware/harbor/files/1553568/harbor-app-d61fa1449922.zip)

**Comment by jessehu** [comment]
Hi @singhshwetaQE , could you please check #3774 which might be the same issue as yours ?

> I think we can close this. I was testing with a certificate with a common name that was not the hostname. This was causing the issue in updating the deployment since the certificate was invalid.
> 
> Repeating the process with an autogenerated cert or with a custom certificate with a valid common name and subject alternative name allowed the tile to get installed successfully.

**Comment by steven-zou** [comment]
@singhshwetaQE Your harbor version is outdated, please try to use the latest one to do testing.
The version should be 1.3.0-*.pivotal

Here is the latest build of harbor tile: https://storage.googleapis.com/harbor-ci-pipeline-store/tile-releases/harbor-1.3.0-rc.21.pivotal

**Comment by reasonerjt** [comment]
@singhshwetaQE any update?

**Comment by singhshwetaQE** [comment]
Still having same issue with build harbor-container-registry-1.3.0-build.37.pivotal

Deploy tile
Update Certificate- used SSL
Click apply

Deployment errors out, attaching new logs
[harbor-app-a62c623ef443.zip](https://github.com/vmware/harbor/files/1572824/harbor-app-a62c623ef443.zip)

**Comment by jessehu** [comment]
@singhshwetaQE how do you "Update Certificate- used SSL" ?  Is your issue the same as #3823 ?

**Comment by singhshwetaQE** [comment]
Looks similar issue to me

**Comment by reasonerjt** [comment]
Closing as #3823 is fixed, the change is contained in master branch not 0.8
