### ISSUE TITLE
镜像复制错误

### ISSUE THREAD

**Issue by chenqifeng28** [vmware/harbor#3786]
我用域名的方式搭建了两个基于HTTPS的harbor，但是在创建复制规则时测试连接失败。请高手帮忙告知下原因和解决方法，谢谢！
# docker --version
Docker version 1.12.6, build ec8512b/1.12.6
#docker-compose --version
docker-compose version 1.17.0, build ac53b73
原仓库：  harbor1.test.com（192.168.10.19）
目标仓库：harbor2.test.com（192.168.10.22）
![image](https://user-images.githubusercontent.com/32876594/33940517-3b7575fc-e04a-11e7-9e20-c34a7cf72158.png)

[harbor_log.tar.gz](https://github.com/vmware/harbor/files/1555573/harbor_log.tar.gz)

**Comment by ywk253100** [comment]
`
Dec 13 20:49:49 bogon ui[4325]: 2017-12-13T12:49:49Z [DEBUG] [transport.go:50]: 302 | GET https://harbor2.test.com/v2/
Dec 13 20:49:49 bogon ui[4325]: 2017-12-13T12:49:49Z [DEBUG] [tokenauthorizer.go:61]: the request https://www.test.com/ is not sent to registry, skip
Dec 13 20:50:10 bogon ui[4325]: 2017-12-13T12:50:10Z [ERROR] [target.go:87]: failed to ping registry https://harbor2.test.com: Get https://www.test.com/: dial tcp 69.172.200.235:443: getsockopt: connection refused
`

Why is the request sent to `https://harbor2.test.com/v2/`redirected to `https://www.test.com/`?

**Comment by chenqifeng28** [comment]
I do not know why it redirected to https://www.test.com/
The attachment is my harbor.cfg
[harbor_cfg.txt](https://github.com/vmware/harbor/files/1557823/harbor_cfg.txt)

**Comment by ywk253100** [comment]
```
curl -i https://harbor2.test.com/v2/
HTTP/1.1 302 Moved Temporarily
Server: nginx/1.13.4
Date: Thu, 14 Dec 2017 03:23:10 GMT
Content-Type: text/html
Content-Length: 161
Connection: keep-alive
Keep-Alive: timeout=20
Location: https://www.test.com/
X-DIS-Request-ID: 219877c2db35e834c29afe06391d3a26

<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.13.4</center>
</body>
</html>
```

**Comment by chenqifeng28** [comment]
I think this is because the container of harbor  can not resolve the domainname harbor2.test.com ,so the request redirected to the www.test.com.
Before that I tried to manually add records to each container of the master node, this problem can be solved
echo "nameserver 192.168.10.2" >> /etc/resolv.conf
echo "192.168.10.22 harbor2.test.com" >> / etc / hosts
but when the harbor restarted ,these records will disappear，i have to add again.
I want to know how to solve the problem completely,thx.

**Comment by ywk253100** [comment]
Refer to `extra_hosts` of docker-compse.

**Comment by chenqifeng28** [comment]
thx,i have solved this problem by using extra_hosts.
Why is there such a problem? Some people did not have this problem with this test
cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)

**Comment by ywk253100** [comment]
If the domain name can be resolved by your DNS server correctly, the `extra_hosts ` is not needed. Or you should do the mapping work manually.

**Comment by As9530272755** [comment]
你们两个不累吗？中国人用英文交流
