### ISSUE TITLE
Harbor Tile should support AWS S3 as the storage for Docker Registry

### ISSUE THREAD

**Issue by jessehu** [vmware/harbor#3792]
S3 is supported as the storage for Docker Registry in standard Harbor.
Need to allow the users of Harbor Tile to config S3 as the storage.
@steven-zou @reasonerjt @virtmerlin

**Comment by jessehu** [comment]
By default, Harbor stores images on your local filesystem. In a production environment, you may consider using other storage backend instead of the local filesystem, like S3, OpenStack Swift, Ceph, etc. What you need to update is the section of storage in the file common/templates/registry/config.yml. For example, if you use AWS S3 as your storage backend, the section may look like this:

storage:
  s3:
    accesskey: awsaccesskey
    secretkey: awssecretkey
    region: us-west-1
    regionendpoint: http://myobjects.local
    bucket: bucketname
    encrypt: true
    keyid: mykeyid
    secure: true
    v4auth: true
    chunksize: 5242880
    multipartcopychunksize: 33554432
    multipartcopymaxconcurrency: 100
    multipartcopythresholdsize: 33554432
    rootdirectory: /s3/object/name/prefix

NOTE: For detailed information on storage backend of a registry, refer to [Registry Configuration Reference](https://docs.docker.com/registry/configuration/).

**Comment by steven-zou** [comment]
I'll take a look at this work as @jessehu is working on uaa. @reasonerjt

**Comment by jessehu** [comment]
Thanks Steven. I can first take care of related Harbor Tile piece. We can have a  discussion after the new year holiday.

**Comment by steven-zou** [comment]
@jessehu You can cover this issue.

**Comment by jessehu** [comment]
Patches are ready for review.

**Comment by jessehu** [comment]
Fixed by https://git.eng.vmware.com/harbor/harbor-tile/merge_requests/9
