### ISSUE TITLE
Harbor Tile should support authentication with UAA in PKS 

### ISSUE THREAD

**Issue by jessehu** [vmware/harbor#3793]
Harbor Tile should support authentication with UAA in PKS, in addition to current internal db auth and LDAP auth.
@steven-zou @reasonerjt @virtmerlin

**Comment by jessehu** [comment]
depends on https://github.com/vmware/harbor/issues/3185

**Comment by reasonerjt** [comment]
short term, I'll add an option so user can set the endpoint, client ID, client secret, so we can make progress in dev and test.

When the UAA in PKS tile is ready, we'll switch to "bosh-link" approach so the credentials can be propagated from PKS.

The readiness of UAA in PKS may be around or after end of Jan 2018, so for 1.0 we may not support it.

**Comment by jessehu** [comment]
Already worked out a prototype of Harbor Tile for demonstrating how Harbor authenticates with UAA in PAS (Pivotal Application Service). Because UAA in PKS is still not ready until later Jan 2018, so Todd Ritchie tritchie@pivotal.io suggested to verify with UAA in PAS first.

**Comment by steven-zou** [comment]
Blocking on PKS team, move to next sp

**Comment by jessehu** [comment]
Design finalized after discussion within the team, Ferran, and Merlin. Doing the test now. 
Depends on #4186 .

**Comment by jessehu** [comment]
Fixed in 
https://git.eng.vmware.com/harbor/harbor-tile/merge_requests/14
https://git.eng.vmware.com/harbor/harbor-tile/merge_requests/18
