### ISSUE TITLE
Get "MANIFEST_UNKNOWN" error now and then.

### ISSUE THREAD

**Issue by moooofly** [vmware/harbor#3795]
## env

```
# docker -v
Docker version 17.09.0-ce, build afdb6d4
# docker-compose -v
docker-compose version 1.16.1, build 6d1ac21
#
```

## log

```
2017-12-14T05:32:46Z [ERROR] [transfer.go:351]: an error occurred while pulling manifest of backend-rls/checki-cron:0.1.5 from http://registry:5000: 404 {"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"Tag":"0.1.5"}}]}
```

In my scenario,  from time to time I can see the error message as above.

The backend of my registry is AWS S3.

**Comment by ywk253100** [comment]
Is the image `backend-rls/checki-cron:0.1.5` in your system?
Please provide all logs so that we can look into what happened.

**Comment by moooofly** [comment]
yes
which part should i provide?

PS: I think it is image irrelevant, a number of images encounter this situation.

**Comment by moooofly** [comment]
"View Replication Job Log" shows:

```
2017-12-14T05:32:46Z [INFO] initializing: repository: backend-rls/checki-cron, tags: [0.1.5], source URL: http://registry:5000, destination URL: https://prod-reg.llsops.com, insecure: false, destination user: admin
2017-12-14T05:32:46Z [INFO] initialization completed: project: backend-rls, repository: backend-rls/checki-cron, tags: [0.1.5], source URL: http://registry:5000, destination URL: https://prod-reg.llsops.com, insecure: false, destination user: admin
2017-12-14T05:32:46Z [WARNING] the status code is 409 when creating project backend-rls on https://prod-reg.llsops.com with user admin, try to do next step
2017-12-14T05:32:46Z [ERROR] [transfer.go:351]: an error occurred while pulling manifest of backend-rls/checki-cron:0.1.5 from http://registry:5000: 404 {"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"Tag":"0.1.5"}}]}
```

**Comment by moooofly** [comment]
by https://github.com/vmware/harbor/blob/v1.2.2/src/jobservice/replication/transfer.go#L351 , err is "404 {"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"Tag":"0.1.5"}}]}"

```
func (m *ManifestPuller) enter() (string, error) {
	if len(m.tags) == 0 {
		m.logger.Infof("no tag needs to be replicated, next state is \"finished\"")
		return models.JobFinished, nil
	}

	name := m.repository
	tag := m.tags[0]

	acceptMediaTypes := []string{schema1.MediaTypeManifest, schema2.MediaTypeManifest}
	digest, mediaType, payload, err := m.srcClient.PullManifest(tag, acceptMediaTypes)
	if err != nil {
		m.logger.Errorf("an error occurred while pulling manifest of %s:%s from %s: %v", name, tag, m.srcURL, err)
		return "", err
	}
...
```

by https://github.com/vmware/harbor/blob/v1.2.2/src/jobservice/replication/transfer.go#L330

```
// Enter pulls manifest of a tag and checks if all blobs exist in the destination registry
func (m *ManifestPuller) Enter() (string, error) {
	state, err := m.enter()
	if err != nil && retry(err) {
		m.logger.Info("waiting for retrying...")
		return models.JobRetrying, nil
	}

	return state, err

}
```

the return value of `retry(err)` is **false**,  so no retrying will proceed, leading to current images replication failed~~

**Comment by moooofly** [comment]
I think the root case is about the latency of backend storage, as NFS ([#3406](https://github.com/vmware/harbor/issues/3406)), AWS S3, and so on. But I can't inspect the details on it.

**Comment by ywk253100** [comment]
Could you package the logs under directory `/var/log/harbor` and upload it?

**Comment by moooofly** [comment]
[harbor_error_log.tar.gz](https://github.com/vmware/harbor/files/1566781/harbor_error_log.tar.gz)

original files are too large, the content of harbor_error_log.tar.gz is truncated by the error happened time.

@ywk253100

**Comment by qianmoke** [comment]
I have the same problem, [new registry docker image](https://github.com/vmware/harbor/commit/6f335bdb1a7d4099fb20cb743ef1e0c0b5c80b32) which change the config file's path( /etc/docker/registry -> /etc/registry), I change my k8s  deployment yaml file and work well. I suggest when change the Dockerfile, should use a new tag.

**Comment by moooofly** [comment]
@ywk253100 any progress?

@qianmoke tks, but not follow what your meaning is.

**Comment by ywk253100** [comment]
Package all logs, cannot get enough information from the logs you provided.

**Comment by moooofly** [comment]
@ywk253100 sorry, the original files have already gone, maybe next time.

**Comment by ywk253100** [comment]
I'm closing this issue now, reopen it if you get this error again.
