### ISSUE TITLE
Make sure the Harbor container will trust the certificate of UAA instance.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#3799]
When Harbor tile and PKS tile are deployed via one ops-man, the docker host of Harbor will automaticly trust the certs in opsman's truststore, including the cert of UAA instance.
However, this doesn't guarantee that the Harbor container will trust the cert of UAA.

This is required to make sure Harbor container can access the UAA within PKS

**Comment by jessehu** [comment]
The solutin is : Harbor Tile will get the UAA CA certificate and set it in harbor.cfg, then Harbor container is able to read the UAA CA certificate.
Will verify when UAA in PKS is ready.
