### ISSUE TITLE
missing description.

### ISSUE THREAD

**Issue by xiaods** [vmware/harbor#38]
<img width="447" alt="2016-03-24 3 40 54" src="https://cloud.githubusercontent.com/assets/37678/14011135/0799f608-f1d7-11e5-95b4-8743b774abad.png">

**Comment by bobbyjunzhang** [comment]
@xiaods Thanks for the suggestion! We are asking our organization admin to add the description for us.

**Comment by bobbyjunzhang** [comment]
The description has been added. Project Harbor does not have an independent website yet and such will be added to the description when available.
