### ISSUE TITLE
Harbor with glusterfs push error. Please help.

### ISSUE THREAD

**Issue by Chinaxiang** [vmware/harbor#3801]
I have run harbor success. can login success. can view ui success, but when I push image to library, It occur error.

I store registry with 3 replia gluster volume.

mount -t glusterfs ip:/volume /data/harbor/registry

> docker-compose.yml

```
...
- /data/harbor/registry:/storage
...
```

when I push an image to hub. It logs:

```
686a085da152: Pushing [==================================================>] 36.63 MB
22f71f461ac8: Retrying in 1 second 
ac66a5c581a8: Pushing [==================================================>]   362 kB
b87261cc1ccb: Pushing [==================================================>]  2.56 kB
5bef08742407: Retrying in 1 second 
received unexpected HTTP status: 500 Internal Server Error
```

push again:

```
The push refers to a repository [10.255.1.101/library/k8s-dns-dnsmasq-nanny-amd64]
686a085da152: Layer already exists 
22f71f461ac8: Pushing 3.072 kB
ac66a5c581a8: Layer already exists 
b87261cc1ccb: Pushing [==================================================>]  2.56 kB
5bef08742407: Retrying in 1 second 
blob upload unknown
```

It will retry many times. Finally failed. 
When I use local filesystem, It will run good. Harbor does not support glusterfs????

other way, I use docker registry use gluster volume can run good. It can push success, but it alse retry some times, It may be glusterfs replia is 3, it will push 3 times to 3 replia.

Anyone can solve harbor use glusterfs problems?? Thank u very much.

**Comment by yixingjia** [comment]
Can you please provide the docker registry log under /var/log/harbor/

**Comment by yixingjia** [comment]
Also you can you please check your gluster cluster log to see if there is any exceptions when you push image failed.

**Comment by yixingjia** [comment]
Assume you have already solved the issue. please reopen it if you still questions.
