### ISSUE TITLE
Harbor's  some container sometimes restart and keep on being restarting or Exit status?

### ISSUE THREAD

**Issue by wkjun** [vmware/harbor#3807]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
```
docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:49 2017
 OS/Arch:      linux/amd64
 Experimental: false

docker-compose version
docker-compose version 1.9.0, build 2585387
docker-py version: 1.10.6
CPython version: 2.7.5
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013

Harbor version: 1.2.0 GA
```

2)Log files, you can get them by package the /var/log/harbor/ .

i have the same problem like #3276 ,when adminserver.log stop output 200 status log like :
`adminserver[25935]: 172.19.0.3 - - [06/Dec/2017:10:16:56 +0000] "GET /api/configurations HTTP/1.1" 200 957`

jobservice.log will be input like:
`jobservice[1141]: 2017-09-22T20:43:58Z [ERROR] [utils.go:94]: failed to connect to 
tcp://adminserver:80, retry after 2 seconds :dial tcp: lookup adminserver: no such host`

Can someone provide some  method to debug this problem? 

It seem adminserver container's exiting cause the problem but it doesn't give some error log.

**Comment by wy65701436** [comment]
please provide the harbor log.

**Comment by ywk253100** [comment]
Closing due to no inactivity.
