### ISSUE TITLE
Error response from daemon: Get https://xx.xxx.xxx.xx/v1/users/: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by jiangshouzhuang** [vmware/harbor#3808]
Now，I use the command, docker login xx.xxx.xxx.xx , to login harbor, but some errors happen as followings:
[root@xxxxx ~]# docker login xx.xxx.xxx.xx
Username: admin
Password: 
Error response from daemon: Get https://xx.xxx.xxx.xx/v1/users/: x509: certificate has expired or is not yet valid

Because Harbor opens HTTPS, so maybe the certificate is expired, but I don't know how to handle it. Do I need to re-generate the certificate and restart the service? Thank you

Note：
1. Docker version：1.12.3
2. Harbor version：0.5.0

**Comment by wy65701436** [comment]
How do you generate the certificate? 

Please follow the installation guile to refer the HTTPs part.

**Comment by jiangshouzhuang** [comment]
@wy65701436 
Thanks. I re-generate the certificate and restart the service.
