### ISSUE TITLE
Add post-deploy errands for Harbor Tile

### ISSUE THREAD

**Issue by jessehu** [vmware/harbor#3810]
Add post-deploy errands for Harbor Tile to verify the basic Harbor functions work well, such as push a image as 'admin' or normal user, then delete the image.

**Comment by steven-zou** [comment]
This should be a optional enhancement work, move to enhancement epic and remove pks-1.0 label.

**Comment by steven-zou** [comment]
Done！Code merged. https://gitlab.eng.vmware.com/harbor/harbor-tile/merge_requests/6
