### ISSUE TITLE
[Issue] Unexpected Scroll Bar

### ISSUE THREAD

**Issue by yhua123** [vmware/harbor#382]
Page: http://10.117.4.227/dashboard
Resolution: 1366x768

![untitled](https://cloud.githubusercontent.com/assets/19166125/16254655/c4d6ff7a-3874-11e6-9e94-e42ba9cf4da6.png)

**Comment by reasonerjt** [comment]
I've update the popular repositories list to show 5 repositories, see #430

**Comment by yhua123** [comment]
verified
