### ISSUE TITLE
ui看不到push的镜像

### ISSUE THREAD

**Issue by caffrey2016** [vmware/harbor#3825]
k8s部署harbour，登录push镜像没问题，但是ui中却看不到push的镜像，通过后端服务可以看到仓库是正常可以拉取的

**Comment by wy65701436** [comment]
Please help to upload harbor log.

**Comment by caffrey2016** [comment]
time="2017-12-19T08:23:30Z" level=info msg="response completed" go.version=go1.7.3 http.request.host=10.10.10.53 http.request.id=c32bec7e-93b4-4175-9176-39070d302315 http.request.method=PATCH http.request.remoteaddr=10.244.0.1 http.request.uri="/v2/wbg/centos/blobs/uploads/7464c2de-81ae-49f8-80db-e62d2045997d?_state=ip6ZyzLLMYqyYd0ABRTONEJIWH_48sd6hiPEs-fPYgN7Ik5hbWUiOiJ3YmcvY2VudG9zIiwiVVVJRCI6Ijc0NjRjMmRlLTgxYWUtNDlmOC04MGRiLWU2MmQyMDQ1OTk3ZCIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNy0xMi0xOVQwODoyMjo1OC4yNTE3MDc0MjVaIn0%3D" http.request.useragent="docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))" http.response.duration=24.782486742s http.response.status=202 http.response.written=0 instance.id=175389ac-ff73-43e8-b76f-848964aa8ddb version=v2.6.2 
10.244.0.32 - - [19/Dec/2017:08:23:05 +0000] "PATCH /v2/wbg/centos/blobs/uploads/7464c2de-81ae-49f8-80db-e62d2045997d?_state=ip6ZyzLLMYqyYd0ABRTONEJIWH_48sd6hiPEs-fPYgN7Ik5hbWUiOiJ3YmcvY2VudG9zIiwiVVVJRCI6Ijc0NjRjMmRlLTgxYWUtNDlmOC04MGRiLWU2MmQyMDQ1OTk3ZCIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNy0xMi0xOVQwODoyMjo1OC4yNTE3MDc0MjVaIn0%3D HTTP/1.1" 202 0 "" "docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))"
time="2017-12-19T08:23:37Z" level=info msg="response completed" go.version=go1.7.3 http.request.host=10.10.10.53 http.request.id=f55ecc03-32b0-46c5-a25e-f5a428e80b83 http.request.method=PUT http.request.remoteaddr=10.244.0.1 http.request.uri="/v2/wbg/centos/blobs/uploads/7464c2de-81ae-49f8-80db-e62d2045997d?_state=RV7mW7PQmhkR2rvB51ItomaZPj6HIpsiAsUm-xB2B7R7Ik5hbWUiOiJ3YmcvY2VudG9zIiwiVVVJRCI6Ijc0NjRjMmRlLTgxYWUtNDlmOC04MGRiLWU2MmQyMDQ1OTk3ZCIsIk9mZnNldCI6NzMzODY5NDcsIlN0YXJ0ZWRBdCI6IjIwMTctMTItMTlUMDg6MjI6NThaIn0%3D&amp;digest=sha256%3A9f4819a016a92dc5400eae9d01ab3d75722e3021c6d5126b8dce5f7f770ce6a5" http.request.useragent="docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))" http.response.duration=6.871940567s http.response.status=201 http.response.written=0 instance.id=175389ac-ff73-43e8-b76f-848964aa8ddb version=v2.6.2

**Comment by wy65701436** [comment]
hi, full log is more reasonable that can help us to get more clue.

**Comment by caffrey2016** [comment]
10.244.0.32 - - [19/Dec/2017:08:30:35 +0000] "HEAD /v2/library/centos/blobs/sha256:196e0ce0c9fbb31da595b893dd39bc9fd4aa78a474bbdc21459a3ebe855b7768 HTTP/1.1" 404 157 "" "docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))"
time="2017-12-19T08:30:50Z" level=info msg="response completed" go.version=go1.7.3 http.request.host=10.10.10.53 http.request.id=a30a1a7a-6785-487d-87ff-60618458424a http.request.method=POST http.request.remoteaddr=10.244.0.1 http.request.uri="/v2/library/centos/blobs/uploads/" http.request.useragent="docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))" http.response.duration=14.973059672s http.response.status=202 http.response.written=0 instance.id=175389ac-ff73-43e8-b76f-848964aa8ddb version=v2.6.2 
10.244.0.32 - - [19/Dec/2017:08:30:35 +0000] "POST /v2/library/centos/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))"
time="2017-12-19T08:30:55Z" level=info msg="response completed" go.version=go1.7.3 http.request.host=10.10.10.53 http.request.id=36c5e250-9d4e-4fe9-a29e-18875b087de0 http.request.method=PATCH http.request.remoteaddr=10.244.0.1 http.request.uri="/v2/library/centos/blobs/uploads/bec40341-9411-4b7f-b025-f14b1cde9bf8?_state=ePQEMXuEaDtFBJ3Req_ufXXMgBAJTvk85eYoZB7gBtl7Ik5hbWUiOiJsaWJyYXJ5L2NlbnRvcyIsIlVVSUQiOiJiZWM0MDM0MS05NDExLTRiN2YtYjAyNS1mMTRiMWNkZTliZjgiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTctMTItMTlUMDg6MzA6MzUuMjUzMTQ5Mzg1WiJ9" http.request.useragent="docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))" http.response.duration=5.612352499s http.response.status=202 http.response.written=0 instance.id=175389ac-ff73-43e8-b76f-848964aa8ddb version=v2.6.2 
10.244.0.32 - - [19/Dec/2017:08:30:50 +0000] "PATCH /v2/library/centos/blobs/uploads/bec40341-9411-4b7f-b025-f14b1cde9bf8?_state=ePQEMXuEaDtFBJ3Req_ufXXMgBAJTvk85eYoZB7gBtl7Ik5hbWUiOiJsaWJyYXJ5L2NlbnRvcyIsIlVVSUQiOiJiZWM0MDM0MS05NDExLTRiN2YtYjAyNS1mMTRiMWNkZTliZjgiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTctMTItMTlUMDg6MzA6MzUuMjUzMTQ5Mzg1WiJ9 HTTP/1.1" 202 0 "" "docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))"
time="2017-12-19T08:31:00Z" level=info msg="response completed" go.version=go1.7.3 http.request.host=10.10.10.53 http.request.id=596fe7da-520d-4118-97da-4acc86c93eec http.request.method=PUT http.request.remoteaddr=10.244.0.1 http.request.uri="/v2/library/centos/blobs/uploads/bec40341-9411-4b7f-b025-f14b1cde9bf8?_state=gDar8rXB8sor6YjxKxu9ZhIPSXj1vi1U2Wg6FxX8xBF7Ik5hbWUiOiJsaWJyYXJ5L2NlbnRvcyIsIlVVSUQiOiJiZWM0MDM0MS05NDExLTRiN2YtYjAyNS1mMTRiMWNkZTliZjgiLCJPZmZzZXQiOjE4NjMsIlN0YXJ0ZWRBdCI6IjIwMTctMTItMTlUMDg6MzA6MzVaIn0%3D&amp;digest=sha256%3A196e0ce0c9fbb31da595b893dd39bc9fd4aa78a474bbdc21459a3ebe855b7768" http.request.useragent="docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))" http.response.duration=4.430568292s http.response.status=201 http.response.written=0 instance.id=175389ac-ff73-43e8-b76f-848964aa8ddb version=v2.6.2 
10.244.0.32 - - [19/Dec/2017:08:30:55 +0000] "PUT /v2/library/centos/blobs/uploads/bec40341-9411-4b7f-b025-f14b1cde9bf8?_state=gDar8rXB8sor6YjxKxu9ZhIPSXj1vi1U2Wg6FxX8xBF7Ik5hbWUiOiJsaWJyYXJ5L2NlbnRvcyIsIlVVSUQiOiJiZWM0MDM0MS05NDExLTRiN2YtYjAyNS1mMTRiMWNkZTliZjgiLCJPZmZzZXQiOjE4NjMsIlN0YXJ0ZWRBdCI6IjIwMTctMTItMTlUMDg6MzA6MzVaIn0%3D&amp;digest=sha256%3A196e0ce0c9fbb31da595b893dd39bc9fd4aa78a474bbdc21459a3ebe855b7768 HTTP/1.1" 201 0 "" "docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))"
time="2017-12-19T08:31:00Z" level=info msg="response completed" go.version=go1.7.3 http.request.host=10.10.10.53 http.request.id=acfe426a-cffa-4abb-acd8-24ce511e57db http.request.method=HEAD http.request.remoteaddr=10.244.0.1 http.request.uri="/v2/library/centos/blobs/sha256:196e0ce0c9fbb31da595b893dd39bc9fd4aa78a474bbdc21459a3ebe855b7768" http.request.useragent="docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))" http.response.contenttype="application/octet-stream" http.response.duration=2.356398ms http.response.status=200 http.response.written=0 instance.id=175389ac-ff73-43e8-b76f-848964aa8ddb version=v2.6.2 
10.244.0.32 - - [19/Dec/2017:08:31:00 +0000] "HEAD /v2/library/centos/blobs/sha256:196e0ce0c9fbb31da595b893dd39bc9fd4aa78a474bbdc21459a3ebe855b7768 HTTP/1.1" 200 0 "" "docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))"
time="2017-12-19T08:31:10Z" level=info msg="response completed" go.version=go1.7.3 http.request.contenttype="application/vnd.docker.distribution.manifest.v2+json" http.request.host=10.10.10.53 http.request.id=786baa1e-4f41-4a4d-81ba-dc2c94657d5c http.request.method=PUT http.request.remoteaddr=10.244.0.1 http.request.uri="/v2/library/centos/manifests/v0.2" http.request.useragent="docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))" http.response.duration=9.924621909s http.response.status=201 http.response.written=0 instance.id=175389ac-ff73-43e8-b76f-848964aa8ddb version=v2.6.2 
10.244.0.32 - - [19/Dec/2017:08:31:00 +0000] "PUT /v2/library/centos/manifests/v0.2 HTTP/1.1" 201 0 "" "docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))"
time="2017-12-19T08:32:17Z" level=info msg="response completed" go.version=go1.7.3 http.request.host=10.10.10.53 http.request.id=a5afd453-d815-4be3-bb93-52ed31d37fc6 http.request.method=GET http.request.remoteaddr=10.244.0.1 http.request.uri="/v2/" http.request.useragent="docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=3.750555ms http.response.status=200 http.response.written=2 instance.id=175389ac-ff73-43e8-b76f-848964aa8ddb version=v2.6.2 
10.244.0.32 - - [19/Dec/2017:08:32:17 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))"
time="2017-12-19T08:32:20Z" level=info msg="response completed" go.version=go1.7.3 http.request.host=10.10.10.53 http.request.id=b8cafd83-0092-497f-8db3-f1a9bf9824bd http.request.method=POST http.request.remoteaddr=10.244.0.1 http.request.uri="/v2/wbg_new/centos/blobs/uploads/?from=library%2Fcentos&amp;mount=sha256%3A9f4819a016a92dc5400eae9d01ab3d75722e3021c6d5126b8dce5f7f770ce6a5" http.request.useragent="docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))" http.response.duration=3.133879516s http.response.status=201 http.response.written=0 instance.id=175389ac-ff73-43e8-b76f-848964aa8ddb version=v2.6.2 
10.244.0.32 - - [19/Dec/2017:08:32:17 +0000] "POST /v2/wbg_new/centos/blobs/uploads/?from=library%2Fcentos&amp;mount=sha256%3A9f4819a016a92dc5400eae9d01ab3d75722e3021c6d5126b8dce5f7f770ce6a5 HTTP/1.1" 201 0 "" "docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))"
time="2017-12-19T08:32:20Z" level=info msg="response completed" go.version=go1.7.3 http.request.host=10.10.10.53 http.request.id=0beb560a-c3e2-4be9-8958-ceaabe5e42f6 http.request.method=HEAD http.request.remoteaddr=10.244.0.1 http.request.uri="/v2/wbg_new/centos/blobs/sha256:9f4819a016a92dc5400eae9d01ab3d75722e3021c6d5126b8dce5f7f770ce6a5" http.request.useragent="docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))" http.response.contenttype="application/octet-stream" http.response.duration=3.210245ms http.response.status=200 http.response.written=0 instance.id=175389ac-ff73-43e8-b76f-848964aa8ddb version=v2.6.2 
10.244.0.32 - - [19/Dec/2017:08:32:20 +0000] "HEAD /v2/wbg_new/centos/blobs/sha256:9f4819a016a92dc5400eae9d01ab3d75722e3021c6d5126b8dce5f7f770ce6a5 HTTP/1.1" 200 0 "" "docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))"
time="2017-12-19T08:32:20Z" level=error msg="response completed with error" err.code="blob unknown" err.detail=sha256:196e0ce0c9fbb31da595b893dd39bc9fd4aa78a474bbdc21459a3ebe855b7768 err.message="blob unknown to registry" go.version=go1.7.3 http.request.host=10.10.10.53 http.request.id=cd9d329e-574a-4b84-aa74-1138eed47fb5 http.request.method=HEAD http.request.remoteaddr=10.244.0.1 http.request.uri="/v2/wbg_new/centos/blobs/sha256:196e0ce0c9fbb31da595b893dd39bc9fd4aa78a474bbdc21459a3ebe855b7768" http.request.useragent="docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=4.180732ms http.response.status=404 http.response.written=157 instance.id=175389ac-ff73-43e8-b76f-848964aa8ddb vars.digest="sha256:196e0ce0c9fbb31da595b893dd39bc9fd4aa78a474bbdc21459a3ebe855b7768" vars.name="wbg_new/centos" version=v2.6.2 
10.244.0.32 - - [19/Dec/2017:08:32:20 +0000] "HEAD /v2/wbg_new/centos/blobs/sha256:196e0ce0c9fbb31da595b893dd39bc9fd4aa78a474bbdc21459a3ebe855b7768 HTTP/1.1" 404 157 "" "docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))"
time="2017-12-19T08:32:30Z" level=info msg="response completed" go.version=go1.7.3 http.request.host=10.10.10.53 http.request.id=f8511eb1-5f1d-4d7b-bd0c-03ea234cb20d http.request.method=POST http.request.remoteaddr=10.244.0.1 http.request.uri="/v2/wbg_new/centos/blobs/uploads/" http.request.useragent="docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))" http.response.duration=10.288665958s http.response.status=202 http.response.written=0 instance.id=175389ac-ff73-43e8-b76f-848964aa8ddb version=v2.6.2 
10.244.0.32 - - [19/Dec/2017:08:32:20 +0000] "POST /v2/wbg_new/centos/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))"
time="2017-12-19T08:32:35Z" level=info msg="response completed" go.version=go1.7.3 http.request.host=10.10.10.53 http.request.id=28008984-2f3b-4dc7-be59-100402b13bb1 http.request.method=PATCH http.request.remoteaddr=10.244.0.1 http.request.uri="/v2/wbg_new/centos/blobs/uploads/d027b5ab-f461-43ff-9318-2790903ba1de?_state=U-UZI01JUEKMLANJqp8j43f0ghFzfNiMwq-xjdLs_It7Ik5hbWUiOiJ3YmdfbmV3L2NlbnRvcyIsIlVVSUQiOiJkMDI3YjVhYi1mNDYxLTQzZmYtOTMxOC0yNzkwOTAzYmExZGUiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTctMTItMTlUMDg6MzI6MjAuMjU4MjkzNzcxWiJ9" http.request.useragent="docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))" http.response.duration=4.670754031s http.response.status=202 http.response.written=0 instance.id=175389ac-ff73-43e8-b76f-848964aa8ddb version=v2.6.2 
10.244.0.32 - - [19/Dec/2017:08:32:30 +0000] "PATCH /v2/wbg_new/centos/blobs/uploads/d027b5ab-f461-43ff-9318-2790903ba1de?_state=U-UZI01JUEKMLANJqp8j43f0ghFzfNiMwq-xjdLs_It7Ik5hbWUiOiJ3YmdfbmV3L2NlbnRvcyIsIlVVSUQiOiJkMDI3YjVhYi1mNDYxLTQzZmYtOTMxOC0yNzkwOTAzYmExZGUiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTctMTItMTlUMDg6MzI6MjAuMjU4MjkzNzcxWiJ9 HTTP/1.1" 202 0 "" "docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))"
time="2017-12-19T08:32:40Z" level=info msg="response completed" go.version=go1.7.3 http.request.host=10.10.10.53 http.request.id=052e7f14-447d-4b71-b65c-5662da8a5be8 http.request.method=PUT http.request.remoteaddr=10.244.0.1 http.request.uri="/v2/wbg_new/centos/blobs/uploads/d027b5ab-f461-43ff-9318-2790903ba1de?_state=6erV-cvduvnRZISY3Z1qWNEflhuSAeje4sBnueGfY0h7Ik5hbWUiOiJ3YmdfbmV3L2NlbnRvcyIsIlVVSUQiOiJkMDI3YjVhYi1mNDYxLTQzZmYtOTMxOC0yNzkwOTAzYmExZGUiLCJPZmZzZXQiOjE4NjMsIlN0YXJ0ZWRBdCI6IjIwMTctMTItMTlUMDg6MzI6MjBaIn0%3D&amp;digest=sha256%3A196e0ce0c9fbb31da595b893dd39bc9fd4aa78a474bbdc21459a3ebe855b7768" http.request.useragent="docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))" http.response.duration=5.050028853s http.response.status=201 http.response.written=0 instance.id=175389ac-ff73-43e8-b76f-848964aa8ddb version=v2.6.2 
10.244.0.32 - - [19/Dec/2017:08:32:35 +0000] "PUT /v2/wbg_new/centos/blobs/uploads/d027b5ab-f461-43ff-9318-2790903ba1de?_state=6erV-cvduvnRZISY3Z1qWNEflhuSAeje4sBnueGfY0h7Ik5hbWUiOiJ3YmdfbmV3L2NlbnRvcyIsIlVVSUQiOiJkMDI3YjVhYi1mNDYxLTQzZmYtOTMxOC0yNzkwOTAzYmExZGUiLCJPZmZzZXQiOjE4NjMsIlN0YXJ0ZWRBdCI6IjIwMTctMTItMTlUMDg6MzI6MjBaIn0%3D&amp;digest=sha256%3A196e0ce0c9fbb31da595b893dd39bc9fd4aa78a474bbdc21459a3ebe855b7768 HTTP/1.1" 201 0 "" "docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))"
time="2017-12-19T08:32:40Z" level=info msg="response completed" go.version=go1.7.3 http.request.host=10.10.10.53 http.request.id=6df2333d-0d65-42f1-9160-ff3417cac675 http.request.method=HEAD http.request.remoteaddr=10.244.0.1 http.request.uri="/v2/wbg_new/centos/blobs/sha256:196e0ce0c9fbb31da595b893dd39bc9fd4aa78a474bbdc21459a3ebe855b7768" http.request.useragent="docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))" http.response.contenttype="application/octet-stream" http.response.duration=2.53206ms http.response.status=200 http.response.written=0 instance.id=175389ac-ff73-43e8-b76f-848964aa8ddb version=v2.6.2 
10.244.0.32 - - [19/Dec/2017:08:32:40 +0000] "HEAD /v2/wbg_new/centos/blobs/sha256:196e0ce0c9fbb31da595b893dd39bc9fd4aa78a474bbdc21459a3ebe855b7768 HTTP/1.1" 200 0 "" "docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))"
time="2017-12-19T08:32:48Z" level=info msg="response completed" go.version=go1.7.3 http.request.contenttype="application/vnd.docker.distribution.manifest.v2+json" http.request.host=10.10.10.53 http.request.id=3ef56e1c-5359-41c9-996a-fc86c5db5fb9 http.request.method=PUT http.request.remoteaddr=10.244.0.1 http.request.uri="/v2/wbg_new/centos/manifests/v0.2" http.request.useragent="docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))" http.response.duration=8.509645449s http.response.status=201 http.response.written=0 instance.id=175389ac-ff73-43e8-b76f-848964aa8ddb version=v2.6.2 
10.244.0.32 - - [19/Dec/2017:08:32:40 +0000] "PUT /v2/wbg_new/centos/manifests/v0.2 HTTP/1.1" 201 0 "" "docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))"
time="2017-12-19T08:43:04Z" level=info msg="PurgeUploads starting: olderThan=2017-12-12 08:43:04.374624166 +0000 UTC, actuallyDelete=true" 
time="2017-12-19T08:43:04Z" level=info msg="Purge uploads finished.  Num deleted=0, num errors=0" 
time="2017-12-19T08:43:04Z" level=info msg="Starting upload purge in 24h0m0s" go.version=go1.7.3 instance.id=175389ac-ff73-43e8-b76f-848964aa8ddb version=v2.6.2

**Comment by caffrey2016** [comment]
[logs-from-registry-app-in-registry-rc-zb9w4.txt](https://github.com/vmware/harbor/files/1571032/logs-from-registry-app-in-registry-rc-zb9w4.txt)

**Comment by caffrey2016** [comment]
http.request.uri="/v2/wbg_new/tomcat8/blobs/sha256:5b8cbbdea091d954969e930de61aca8496d3c8b47d767e540a5e7a7c8be3bd3f" http.request.useragent="docker/1.12.1 go/go1.6.3 git-commit/23cf638 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.1 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=2.401736ms http.response.status=404 http.response.written=157 instance.id=175389ac-ff73-43e8-b76f-848964aa8ddb vars.digest="sha256:5b8cbbdea091d954969e930de61aca8496d3c8b47d767e540a5e7a7c8be3bd3f" vars.name="wbg_new/tomcat8" version=v2.6.2 
10.244.0.32 - - [19/Dec/2017:10:27:09 +0000] "HEAD /v2/wbg_new/tomcat8/blobs/sha256:5b8cbbdea091d954969e930de61aca8496d3c8b47d767e540a5e7a7c8be3bd3f HTTP/1.1" 404 157 "" "docker/1.12.1 go/go1.6.3 git-commit/23cf638 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.1 \\(linux\\))"
time="2017-12-19T10:27:09Z" level=error msg="response completed with error" err.code="blob unknown" err.detail=sha256:6f5a0ce383c605e64a963b8523fa118e9b02c86dcb12d97800aa2fd9af69bcdb err.message="blob unknown to registry" go.version=go1.7.3 http.request.host=10.10.10.53 http.request.id=13756b17-17c2-4519-ba59-9bc4c081b51e http.request.method=HEAD http.request.remoteaddr=10.244.0.1 http.request.uri="/v2/wbg_new/tomcat8/blobs/sha256:6f5a0ce383c605e64a963b8523fa118e9b02c86dcb12d97800aa2fd9af69bcdb" http.request.useragent="docker/1.12.1 go/go1.6.3 git-commit/23cf638 kernel/3.10.0-327.10.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.1 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=2.417846ms http.response.status=404 http.response.written=157 instance.id=175389ac-ff73-43e8-b76f-848964aa8ddb vars.digest="sha256:6f5a0ce383c605e64a963b8523fa118e9b02c86dcb12d97800aa2fd9af69bcdb" vars.name="wbg_new/tomcat8" version=v2.6.2 



上面日志里面发现个报错，麻烦看看是什么问题？

**Comment by rockwyc992** [comment]
Have you read #3637 ? 
There is a bug in the yaml files, it will cause that `registry` cannot hook to `ui` and `mysql`.

I fix that with PR #3638 , and also modify these yaml more compatible with Kubernetes.

**Comment by caffrey2016** [comment]
非常感谢 @rockwyc992 @wy65701436  ！！，按照 @rockwyc992 的 #3638 修改后，重启所有服务，果然可以了。
