### ISSUE TITLE
project still empty in the UI

### ISSUE THREAD

**Issue by de13** [vmware/harbor#3829]
If you are reporting a problem, please make sure the following information are provided:

**1)Version of docker engine and docker-compose.**

Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64
 Experimental: false

I use Harbor on K8s, and since 10 days (around), the images pulled in the repo are not  observable in the UI (but present in the registry).

I don't know which logs contains the relevant informations about that, I suspect something wrong between registry and mysql, but nothing obvious.

**Comment by reasonerjt** [comment]
Hi, the k8s support is not currently official, we'll investigate it when we have time.

**Comment by rockwyc992** [comment]
Have you read #3637 ? 
There is a bug in the yaml files, it will cause that `registry` cannot hook to `ui` and `mysql`.

I fix that with PR #3638 , and also modify these yaml more compatible with Kubernetes.

**Comment by de13** [comment]
It's working. Thanks!
