### ISSUE TITLE
no response after I  click the send button when I forgot my password.

### ISSUE THREAD

**Issue by wemeya** [vmware/harbor#383]
See below pictures:
![image](https://cloud.githubusercontent.com/assets/12540577/16256824/499bafbe-3887-11e6-9fd3-300c137ddcc8.png)

**Comment by wknet123** [comment]
Have you made the right configuration about STMP in harbor.cfg?

**Comment by wemeya** [comment]
@wknet123 
After I configured the STMP. I tried the function, it worked well. But I have some suggestions:
I think we should remind the owner of the email, for example:
Warning: You're receiving this because you're requesting for changing password in Harbor. If it is not your operation, please ignore.
![image](https://cloud.githubusercontent.com/assets/12540577/16261564/af1dc6ee-389e-11e6-82f3-e8be9f207cc3.png)

**Comment by reasonerjt** [comment]
@wemeya good suggestion, could you fix this?

**Comment by wemeya** [comment]
@reasonerjt 
No problem.

**Comment by wemeya** [comment]
@reasonerjt 
how about this?
![image](https://cloud.githubusercontent.com/assets/12540577/16299693/3b398800-396e-11e6-935f-dc62d00b7447.png)

**Comment by reasonerjt** [comment]
yes looks good

**Comment by wemeya** [comment]
fixed.
