### ISSUE TITLE
cannot make nginx work with other upstream

### ISSUE THREAD

**Issue by wei-hai** [vmware/harbor#3830]
I am trying to add upstream conf file to ./common/config/nginx/conf.d so that nginx can work for my other service, but after I restart nginx and open the url, e.g., jenkins.example.com, it is redirected to harbor, e.g., registry.example.com. Then I took a look at nginx.conf and found that the `server_name` is commented out, then I added `server_name registry.example.com` in nginx.conf for both 80 and 443 and restarted nginx, however, it didn't work, jenkins.example.com is redirected to registry.example.com again. What is wrong with the nginx config file?

nginx.conf
```
    server {
      listen 80;
      #server_name harbordomain.com;
      server_name registry.example.com;
      return 301 https://$host$request_uri;
  }
```

jenkins.server.conf
```
upstream jenkins {
    ip_hash;
    server  localhost:8081;
}

server {
    listen  80;
    server_name jenkins.example.com;
    location / {
	    proxy_set_header        Host $host:$server_port;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_pass  http://jenkins;
	    proxy_read_timeout  90;
        proxy_redirect      http://jenkins http://jenkins.example.com;
    }
}
```

**Comment by liuerfire** [comment]
@wei-hai I have the same problem. Did you solve this?
