### ISSUE TITLE
[feature Request]  multi LDAP Base DN needed

### ISSUE THREAD

**Issue by sinycn** [vmware/harbor#3843]
hi：
   i am using LDAP auth for harbor v1.1.1, our company have two Active directory   aa.com and bb.com  my account have the privileges to access both aa.com and bb.com but harbor`s ldap just support one LDAP Base DN so could you please add more LDAP Base DN to support multi ldap

**Comment by stonezdj** [comment]
Is aa.com  or bb.com locate in the same Active Directory server?

**Comment by sinycn** [comment]
two ad server but they are One-Way Trust or two-way trust,  in our DTR (docker trust registry) it can add one ldap server but multi LDAP Base DN with different usrname&password to meet our multi ldap

**Comment by sinycn** [comment]
hi all 
after test for 6 month, i solved this issue, when use active directory GC as ldap server, and LDAP Base DN DC=abc,DC=com   i can add user in tw.abc.com and us.abc.com,eu.abc.com
