### ISSUE TITLE
page does not change after click the public projects link

### ISSUE THREAD

**Issue by wemeya** [vmware/harbor#385]
When I click the users tab, it lists below:

![image](https://cloud.githubusercontent.com/assets/12540577/16257167/33c2105a-3889-11e6-9bdd-b2b67800d33a.png)
 
However, when I click the public tab, it's still there, I don't know whether this is right:
![image](https://cloud.githubusercontent.com/assets/12540577/16257206/8500b840-3889-11e6-8264-0cda87a59598.png)

**Comment by wknet123** [comment]
Fixed
