### ISSUE TITLE
v1.3.0-rc4 Interface does not look good

### ISSUE THREAD

**Issue by dangzhiqiang** [vmware/harbor#3854]
eg：
![image](https://github.com/dangzhiqiang/images/blob/master/harbor/harbor-ui-v1.3.0-rc4.jpg?raw=true)

**Comment by wy65701436** [comment]
Can you give more detail as I cannot get your point?

**Comment by dangzhiqiang** [comment]
默认显示不太好看。
1、标签通常很短，给的长度空间太大。
2、pull命令可以像之前版本一样，显示完整的命令，如果只保留复制标签，也不用留太大空间。
3、作者通常很长，可以默认给长一些显示长度。
