### ISSUE TITLE
How to use restApi to authenticated

### ISSUE THREAD

**Issue by yn425611317** [vmware/harbor#3855]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
3)Log files, you can get them by package the /var/log/harbor/ .

**Comment by yn425611317** [comment]
How to use restApi to authenticated

**Comment by wy65701436** [comment]
Can you explained your questions in detail?

**Comment by ywk253100** [comment]
The APIs support basic auth.
