### ISSUE TITLE
Harbor bosh release enhancement

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#3869]
Adding errand job to run smoke testing
  -Mainly focus on image pulling/pushing

Add post-errand to harbor tile
Provide manifest template for GCP/AWS

Support registry backend storage configuration in tile

**Comment by jessehu** [comment]
This should be split into several sub tasks for easy tracking.

**Comment by jessehu** [comment]
sub tasks: #3810 #3792

**Comment by steven-zou** [comment]
Work done, close issue.
