### ISSUE TITLE
Username does't match when add members.

### ISSUE THREAD

**Issue by wemeya** [vmware/harbor#387]
When I add memebers, something weird happened:
![image](https://cloud.githubusercontent.com/assets/12540577/16257354/96366546-388a-11e6-9047-f1b15f013d44.png)

The username changed to admin in the list. 
After that, I continue to add members. When I add another user, it says user already exist, but I can't see the user in the list:
![image](https://cloud.githubusercontent.com/assets/12540577/16257454/4e0dd032-388b-11e6-8697-c1631f487573.png)

**Comment by wknet123** [comment]
@wemeya please pull the latest codes, and rebuild it.

**Comment by wemeya** [comment]
ok.
