### ISSUE TITLE
Make sure the skinnable configuration file setting.json is built into the image

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#3879]
"projects": {
    "companyName": "vmware",
    "projectName": "Harbor",
    "introduction": {
      "zh-cn": "",
      "es-es": "",
      "en-us": ""
    }
  }

**projects** should be changed to 'product'

**Comment by reasonerjt** [comment]
@steven-zou I believe this is fixed in release 1.3.0 correct?

**Comment by pengpengshui** [comment]
done
