### ISSUE TITLE
docker login error

### ISSUE THREAD

**Issue by wemeya** [vmware/harbor#389]
When I tried to login, Harbor returned an error:
![image](https://cloud.githubusercontent.com/assets/12540577/16258823/1402c60c-3892-11e6-9c46-be3ec983bfa8.png)
The relevant log:
![image](https://cloud.githubusercontent.com/assets/12540577/16258835/27ed40b6-3892-11e6-8028-6cbacd0907f9.png)

**Comment by reasonerjt** [comment]
are your sure you typed the correct password？

**Comment by wemeya** [comment]
quite sure.

**Comment by wemeya** [comment]
Closing as unreproduceable
