### ISSUE TITLE
DB container is not starting

### ISSUE THREAD

**Issue by jegger** [vmware/harbor#3896]
I just wanted to try out harbor but I fail quite early: 
The harbor-db container seems not to start properly (restarts all the time). 
A docker-ps indicates it: "Restarting (137) 32 seconds ago". 

**What I did:**
- Downloaded 1.2.2 (I also tried 1.2.0) stable version offline and online installer
- Changed the hostname in the harbor.cfg file
- ./install.sh 

My docker version: 17.12.0
My docker-compose version: 1.8.0
Docker is running on a fresh ubuntu 16.04 digitalocean droplet. 

**Some lines of the mysql.log file:**
Dec 31 17:07:57 172.18.0.1 mysql[4069]: Maria DB flag not found, the DB was created in mysql image, running upgrade...
Dec 31 17:07:58 172.18.0.1 mysql[4069]: Waiting for MySQL start...
Dec 31 17:08:00 172.18.0.1 mysql[4069]: message repeated 2 times: [ Waiting for MySQL start...]
Dec 31 17:08:01 172.18.0.1 mysql[4069]: Waiting for MySQL start...
Dec 31 17:08:02 172.18.0.1 mysql[4069]: Waiting for MySQL start...
Dec 31 17:08:28 172.18.0.1 mysql[4069]: message repeated 26 times: [ Waiting for MySQL start...]
Dec 31 17:08:29 172.18.0.1 mysql[4069]: MySQL failed to start.
Dec 31 17:08:32 172.18.0.1 mysql[4069]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-updatedb.d/upgrade.sh
Dec 31 17:08:32 172.18.0.1 mysql[4069]: Maria DB flag not found, the DB was created in mysql image, running upgrade...
Dec 31 17:08:32 172.18.0.1 mysql[4069]: Waiting for MySQL start...

Here is a zip file containing all the logs:
[harbor-logs.zip](https://github.com/vmware/harbor/files/1597076/harbor-logs.zip)

If I should upload the config files, please tell me. But I don't think that makes any sense here as I did not alter them in any way (except the hostname).

My guess is that I am doing something wrong here. I would be glad if you could help me out.
Thanks

**Comment by steven-zou** [comment]
Please take a look at this issue, thanks

**Comment by ywk253100** [comment]
Seems a migration/upgrade issue? @ninjadq

**Comment by jegger** [comment]
I do not think that this is a migration issue as I did not had any older version installed previously. (at least no from a users point of view)

**Comment by ninjadq** [comment]
hi @jegger ,
Your mysql service seems not start up properly. 
But I can't reproduce this problem on my local ubuntu 16.04. 
And sorry that I don't have digital ocean environment. 
Are you tried on another machine?

**Comment by ninjadq** [comment]
hi @jegger,
 If you have install older version. you need upgrade first. plz refer [this](https://github.com/vmware/harbor/blob/master/docs/migration_guide.md)

if you just wanna have a try. You can remove you db dir first. The location is  `/data/database`

**Comment by jegger** [comment]
@ninjadq Which version of the release (on https://github.com/vmware/harbor/releases) are you using when you try to reproduce it? I may try it on a physical server ubuntu 16.04 again then to see if it makes any difference.

**Comment by jegger** [comment]
I tried to install the newest version. It works now without any issue. Thanks for your support anyway!
