### ISSUE TITLE
Wrong path of setting.json

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#3909]
When getting the setting.json, should add prefix path 'static/'

If setting.json failed to load, default styles should be applied. But bug found in the background image of login page;

style="background-image: url("undefined");"

**Comment by reasonerjt** [comment]
@steven-zou How does this relates to #3879 ?

**Comment by mdubya66** [comment]
is this a 1.3 Ship stopper? @reasonerjt?

**Comment by reasonerjt** [comment]
@mdubya66 It's not.

**Comment by mdubya66** [comment]
thanks, i saw the target/vic-1.3 label

**Comment by reasonerjt** [comment]
@mdubya66 it only impacts a use case of community user using standalone Harbor,

there is a PR opened to fix it, if we can merge it, we fix it and tag 1.3 release.

if we cannot, we can delay it to 1.3.1

**Comment by pengpengshui** [comment]
done
