### ISSUE TITLE
It's better to put "tooltip messge" into the middle of screen.

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#3913]
![image](https://user-images.githubusercontent.com/2841473/34551307-7117c6fe-f0cd-11e7-9141-bc791a965b81.png)

**Comment by lweitzman** [comment]
not sure if a tooltip is the right way to notify the user. this banner should push the content down. another option is to use a "toast" notification. its a feature request for clarity at this point https://github.com/vmware/clarity/issues/365
