### ISSUE TITLE
there should be two buttons in cancle dialog,and confirm button does not work

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#3922]
Version v1.3.0-rc1-123-g5340fed 
Edit repository  information, click cancel, in the dialog click confirm nothing happens
![screenshot-2018-1-4 harbor 1](https://user-images.githubusercontent.com/23101283/34552238-43db977c-f15b-11e7-8f76-d4e3c9156f97.png)

**Comment by lweitzman** [comment]
i think in this case if we need a confirmation, we should use "CANCEL" and "OK"
