### ISSUE TITLE
[Issue] The Cursor on Harbor Log Changed to Hand, no Any Link Under It.

### ISSUE THREAD

**Issue by yhua123** [vmware/harbor#394]
Browser: Firefox 46.0.1
Link: http://10.117.4.227/dashboard
![untitled](https://cloud.githubusercontent.com/assets/19166125/16289279/4e87bc12-3926-11e6-9664-2c16d42859a1.png)

**Comment by wknet123** [comment]
fix later

**Comment by yhua123** [comment]
done
