### ISSUE TITLE
OVA questions

### ISSUE THREAD

**Issue by davenport** [vmware/harbor#3948]
Greetings,

I have several questions about the OVA option of version 1.3

- is vIC required
- are the Harbor services deployed as containers within the OVA, if not then how
- what distro does the OVA run (Photon or ?)
- are Clair and/or Notary supported, if so then how are they configured and started
- why are you collecting contact info before allowing the OVA to be downloaded
- how should the Harbor services and the OVA be started and stopped
- how do you upgrade an OVA install
- Harbor's history of providing an OVA release seems inconsistent, what is the future direction and commitment to providing OVA releases
- what should be backed up and how: DBs, regesitry, logs, VM, ...
- how would you restore or recover an OVA
- is iptables available

Thank you,

Doug

**Comment by yixingjia** [comment]
- is VIC required
[A] No

- are the Harbor services deployed as containers within the OVA, if not then how
[A] They are deployed as containers in the OVA.

- what distro does the OVA run (Photon or ?)
[A] Photon

- are Clair and/or Notary supported, if so then how are they configured and started
[A]Both will be installed by default. the principle of configuration and life-cycle management is the same as offline installer.

- why are you collecting contact info before allowing the OVA to be downloaded.
[A]We want to better understand how vSphere Users use Harbor for improve Harbor on vSphere.
 
- how should the Harbor services and the OVA be started and stopped
[A]Login to the VM and execute systemctl stop/start harbor.service
Or you can simply restart the VM

- how do you upgrade an OVA install
[A] The upgrade solution document will be provided later. The basic workflow should be: back up the data disk of old OVA, replace it in new OVA and run upgrade script.
 
- Harbor's history of providing an OVA release seems inconsistent, what is the future direction and commitment to providing OVA releases.
[A] We'd like to provide one more installation option for the community user. And we plan to provide OVA release from Harbor 1.3.0
 
- what should be backed up and how: DBs, regesitry, logs, VM, ...
[A] In OVA packages. All the persistent data are stored under /data directory.  You can simply backup this directory.
 
- How would you restore or recover an OVA
[A] From vSphere’s point of view it’s same as other OVA. You can back up the VM, or take snapshot of the VM for backup purpose.  You can also setup VM HA to protect it.
From Harbor itself If you have backup the /data directory. The recover is simple as follow:
1> Install a new OVA with same version.
2> Stop the harbor by systemctl stop harbor.service
3> replace the /data directory with your backup
4> Start Harbor by systemctl start harbor.service
We will provide a more detail document on the recover steps later. 

- is iptables available
[A] Not clear on what's you point of this question. As this OVA base on Photon, you can refer the Photon document for iptables usage.

**Comment by davenport** [comment]
Thank you!

**Comment by wy65701436** [comment]
@davenport, please re-download the ova as I have refresh the back-end build.
