### ISSUE TITLE
ldap_scope is is changed to 0,1,2 instead of 1, 2,3

### ISSUE THREAD

**Issue by stonezdj** [vmware/harbor#3958]
LDAP search level is refactored:

0.Base Level
1. One Level
2. Subtree

Following files need to update

1.Comments in harbor.cfg
2.Harbor tiles
3.OVA configure properties.
4.The script which migrates admin.json to properties table. 
5.The script which migrates 1.3 to 1.4

**Comment by stonezdj** [comment]
Fixed in #3974 #3965

**Comment by jessehu** [comment]
required change in Harbor Tile is done 
https://gitlab.eng.vmware.com/harbor/harbor-tile/merge_requests/10

**Comment by stonezdj** [comment]
When migrating harbor 1.3  to 1.4, the SearchScope is 1,2,3, we need to convert it to 0,1,2

**Comment by stonezdj** [comment]
fixed
