### ISSUE TITLE
Missing hostname or IP in Pull Command

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#3966]
Click the button got `docker pull /library/hello-world:1.0`

**Comment by steven-zou** [comment]
@ninjadq Please take a look at this bug. Pay attention if the object returned by the systeminfo is changed.

**Comment by jessehu** [comment]
Another improvement suggestion: show a 'copied to clipboard' flash notice when user clicks the button

**Comment by jessehu** [comment]
@reasonerjt which sprint or release should this be fixed?
