### ISSUE TITLE
The "SCAN" button can be clicked even though Clair isn't deployed.

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#3967]
<img width="1190" alt="scan" src="https://user-images.githubusercontent.com/5835782/34665174-2dbae5b4-f49a-11e7-97df-62e7ef94825b.png">

**Comment by steven-zou** [comment]
@pengpengshui Please take a look at this bug.And also pat attention to the layout things.

**Comment by steven-zou** [comment]
@ywk253100 The button can be clicked even the clair db is not ready before. There should be no errors.

**Comment by steven-zou** [comment]
Related with this issue https://github.com/vmware/harbor/issues/3925
