### ISSUE TITLE
Problems about calling the API: registry:5000/v2/_catalog

### ISSUE THREAD

**Issue by cherry4477** [vmware/harbor#398]
hey, when calling the API registry:5000/v2/_catalog, the result returns all repos and images that under repos. however, the result is limited within 100 rows, which results in repos and images behind 100 are not shown. If the API is called like this: curl registry:5000/v2/_catalog?n=10000, problem can be solved.

**Comment by reasonerjt** [comment]
Thanks for reporting， will fix it.

**Comment by reasonerjt** [comment]
PR #405 will fix this issue, but currently blocked by internal error in travis-ci, we'll see if the error is temporary, if not we'll try to work around it.

**Comment by reasonerjt** [comment]
fixed in pr #405
