### ISSUE TITLE
Got 404 when switching language on "Registries" page

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#3991]
![language_01](https://user-images.githubusercontent.com/5835782/34758998-75a2b3f4-f614-11e7-9931-36070298a72f.png)

After switching language:
![language_02](https://user-images.githubusercontent.com/5835782/34759002-76f1fd46-f614-11e7-881b-6ec2ffb4f188.png)

**Comment by steven-zou** [comment]
Same with #3992

**Comment by ywk253100** [comment]
Fixed by #4011.
