### ISSUE TITLE
Got "404 Page Not Found" when refreshing browser

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#3992]
Got "404 Page Not Found" when refreshing browser:
1. on`Registries` page
![404_registry](https://user-images.githubusercontent.com/5835782/34759179-4077c3b2-f615-11e7-91d9-deaee29bf0b4.png)

2. on `New Replication Rule` page
![404_new_rule](https://user-images.githubusercontent.com/5835782/34759180-41e15358-f615-11e7-86eb-cfb0f4c56cae.png)

**Comment by steven-zou** [comment]
This is the new frontend route, need add corresponding route at the backend.

@ywk253100 Please help to add the route

**Comment by ywk253100** [comment]
Fixed by #4011.
