### ISSUE TITLE
Harbor tile should register to UAA as a client during deployment.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#3998]
The code in Harbor tile should be able to reference a "seed client" via the attributes of PKS tile and register a new client with it during the deployment.

**Comment by steven-zou** [comment]
Errand job for unregistering harbor uaa client should also be supported in the pre-delete of harbor tile. When harbor is deleted, harbor uaa client will be removed from the uaa server.

**Comment by steven-zou** [comment]
Work done and code merged, see https://gitlab.eng.vmware.com/harbor/habo/merge_requests/13.
Close!
