### ISSUE TITLE
HA works for Harbor 1.5.0

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#4001]
**1>Refactor Job service**
**Issue:**
1. Multiple job services cannot co-work.

**Requirement**
1. Job service itself should be stateless. 
2. Be able to reschedule job to live job services instances when a job service instance is down
3. Job status data should be saved to a persistent storage( DB or Etcd, or Redis or others)

**Effort estimate**
1.5 month/person ?

**2>Make all services' access endpoint configurable**
**Issue**

1. Currently all the services endpoint is hardcode. 

**Requirements**

1. Service endpoint should be configurable.
2. (Do we need to consider service discover, registry mechanism?)
**Effort estimate**
1 week/person

**3>Job log should be saved to a centralized place**
**Issue**
1. Replication/Scan job logs are stored in local filesystem.
2. In multiple instances scenario user will not be able to view replication/scan logs when a request redirect to the jobservices that don’t have the log file

**Requirement** 
1. All the replication/scan job logs should be saved to a centralized place. All the jobservice instances should be able to access the job logs

**Effort estimate**
2 week/p

**4>Service health status check**

**Issue**
1. There is no good method to monitor the services in Harbor

**Requirement**
1. Each service should be able to provide a status API to reflect the status of the services
2. The API will always return 200 if it is reachable( do not require complicated logic for short term)

**Effort estimate**
3 days/p

**5>Log tracking in HA environment**

**Issue**

1. Harbor lack of request process tracking mechanism. 
2. When a request dispatched between different services. Logs will be write to different nodes. Currently it’s difficult to identify which service instances get the request and where the log is stored.

**Requirement**

1. Each request should be assign a unique ID
2. Services should log the request ID along with the logs.
3. Request context should always include the ID

**Estimate**
?

**Subtasks**
#3946 Job service refactor.
#4002 Make all services' access endpoint configurable.
#3919 Job log should be saved to a centralized place.
#4231 Health monitor API for Harbor services.
#4145 Migrate Harbor DB to PostgreSQL 

Due to scheduler changes some task are moving out of Harbor 1.5 scope. This Epic https://github.com/vmware/harbor/issues/4320  will used to tracking all those issues.

**Comment by reasonerjt** [comment]
@yixingjia let's move out the issues that are not in 1.5 scope

**Comment by yixingjia** [comment]
Close this epic as all the planed works has been done.

Migrate to postgres has been rescheduled to 1.6 release.
