### ISSUE TITLE
The running jobs can not be stopped correctly in HA environment

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#4012]
When users try to stop running jobs on the instance A,  the jobs that are running on the instance B cannot be stopped.

**Comment by reasonerjt** [comment]
@yixingjia

**Comment by reasonerjt** [comment]
We'd probably document this limitation?

**Comment by yixingjia** [comment]
This is cause by the limitation in our job service design. 

When we fix issue #3747

**Comment by yixingjia** [comment]
Reassign to Steven as he will responsible to Jobservice refactor.

**Comment by steven-zou** [comment]
As the job service will be refactored for HA, this problem will be considered in the new design, so close this issue.
