### ISSUE TITLE
Clair update from Harbor 1.2.0 to 1.3.0

### ISSUE THREAD

**Issue by roldancer** [vmware/harbor#4025]
Hi All, I have a doubt about Clair update, we have a Harbor V1.2.0 installation and we want to update to V1.3.0, I was looking at the the migration guide https://github.com/vmware/harbor/blob/master/docs/migration_guide.md , but this doc doesn't mention anything about Clair update.

Is there any strategic or recommendation about Clair update ?

Many thanks.

**Comment by reasonerjt** [comment]
We are using Clair V2 in both 1.2.0 and 1.3.0, also 1.4.0 so no migration's needed.

**Comment by roldancer** [comment]
oki, thanks !!!
