### ISSUE TITLE
License confusion!

### ISSUE THREAD

**Issue by paulczar** [vmware/harbor#4026]
Why is the LICENSE.md file so large? It looks like it contains every software license that's ever been created. Surely it should be a fairly simple Apache2 as the source code for Harbor appears to be apache2 licensed (https://github.com/vmware/harbor/blob/master/src/adminserver/main.go#L1-L13).  

If there are supplemental licenses for the software that is installed alongside this when fully packaged and shipped as an artifact then I would recomment having a supplemental license file so that LICENSE.md can be kept clean and be specific for just the source code found in this repository.

**Comment by reasonerjt** [comment]
@paulcza
Thanks a lot for raising this issue.

I talked to the legal contact, and there will be a revised license soon.
I'll keep this open until the license is updated.
