### ISSUE TITLE
The storage widget should not show when the registry is using S3 storage.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#4029]
There's storage widget to show the storage usage of Harbor, but it's by reading the /data volume, 
 so when the tile is deployed with setting registry to use S3 storage it should not be shown.

We probably should propagate the storage type to adminserver and return it in `/systeminfo` API.

**Comment by jessehu** [comment]
Daniel means the storage usage widget on 'Projects' page.
![image](https://user-images.githubusercontent.com/10006/34973198-70eab67a-fac1-11e7-9a1f-edd2f54cf657.png)

**Comment by steven-zou** [comment]
Duplicated issue with #2425, close this one.
