### ISSUE TITLE
Upgrade beego 

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#403]
"concurrent map read and map write" error occurs sometimes in Harbor, this is a bug of beego. Upgrade it to version 1.6.1 can solve this issue.

**Comment by reasonerjt** [comment]
thanks wenkai, please add the link to the beego issue.

**Comment by ywk253100** [comment]
https://github.com/astaxie/beego/issues/1682

**Comment by reasonerjt** [comment]
fixed in #423
