### ISSUE TITLE
Support add disk space on the OVA build 

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#4034]
In VIC there is a service "resizefs.service"  which can extend the disk size.

Harbor should also include this service into OVA installation packages.

**Comment by stonezdj** [comment]
The disk format in VIC is ext4, the data disk in harbor OVA is lvm. we can not refer resizefs.service. 
Refer the previous guide: https://github.com/vmware/harbor/blob/v1.1.0/docs/expand_hard_disk.md
to create a script.

**Comment by stonezdj** [comment]
Add it in #4058
