### ISSUE TITLE
Clair not running after 1.2.2 to 1.3.0 migration

### ISSUE THREAD

**Issue by SteveOss** [vmware/harbor#4040]
Have migrated from 1.2.2 to version 1.3.0 using both notary and clair. Database converted fine and
preparing with notary and clair generated no errors. Everything is running apart from the clair container that is in a restart loop with a fatal error messages in /var/log/harbor/clair.log

Jan 16 13:26:08 172.18.0.1 clair[755]: time="2018-01-16T13:26:08Z" level=fatal msg="failed to load configuration" error="open /etc/clair/config.yaml: no such file or directory" 

Looks like some sort of configuration has failed but not obvious to me what?

docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:54 2017
  OS/Arch:      linux/amd64
  Experimental: false

docker-compose version 1.16.1, build 6d1ac21
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

System: debian 9.3 4.9.0-5-amd64

**Comment by gregorkistler** [comment]
Ran into the same issue about two weeks ago.
Your Clair Docker image is outdated. Simply pull it again via 

```docker pull vmware/clair:v2.0.1-photon```

**Comment by SteveOss** [comment]
Sorted the problem. Thanks Gregor
