### ISSUE TITLE
Will Harbor delete the images from harddisk after I delete it from admin UI?

### ISSUE THREAD

**Issue by sirius1024** [vmware/harbor#4041]
If harbor cannot do it by herself, How we do this for saving space of my disk?

Harbor version: 1.3.0
Docker version:  17.12.0-ce

Thanks.

**Comment by tomsherrod** [comment]
Is this question answer here?  https://github.com/vmware/harbor/blob/master/docs/user_guide.md#deleting-repositories

**Comment by sirius1024** [comment]
@tomsherrod Thanks for your help and this's what I want. Sorry for my careless for read the document.

**Comment by rahbal** [comment]
Above link not found !

https://goharbor.io/docs/2.1.0/working-with-projects/working-with-images/pulling-pushing-images/#deleting-repositories
Updated Link.
