### ISSUE TITLE
Misc UI issues of replication

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#4049]
1. Column name should be `Mode`:
![column_name](https://user-images.githubusercontent.com/5835782/35026865-79cea1ee-fb88-11e7-854d-abfd1d121f74.png)

2. The `REPLCATE` isn't translated in Chinese env.
![translate](https://user-images.githubusercontent.com/5835782/35026898-a51256ac-fb88-11e7-83ff-3de39c5fdf1c.png)

**Comment by lweitzman** [comment]
I think the column should be called "Replication Schedule"

**Comment by steven-zou** [comment]
@lweitzman "Manual" and "Immediate" are not "Schedule" scope. The name should be 'Trigger Mode'
