### ISSUE TITLE
Replication can't be resumed after network outages

### ISSUE THREAD

**Issue by likunbyl** [vmware/harbor#4081]
I'm now deploying harbor 1.3.0 in a kubernetes cluster, I setup two harbors to replicate to each other.

I simulated a network outage by delete registry service of one harbor, say harborB, and pushed some image to harborA, then the replication stopped with errors.  After an hour I recovered the registry service of harborB, the replication stopped before didn't resume, I had to disable then enable the rule to replicate the whole project. 

Is this the way to do replication, or has I missed some configurations ?

likun

**Comment by reasonerjt** [comment]
This is by design, currently the error state is not recoverable.

**Comment by likunbyl** [comment]
Does anyone feel some inconvenience about this? suppose I have 100+ projects to replicate , after network outage, I have to disable and enable replication rules one by one, or is there any simple way that I don't know to handle this ?

**Comment by reasonerjt** [comment]
I see your point, in 1.4 we introduced schedule to replication policy, so the replication will happen daily/weekly, it should be helpful in your case?

**Comment by likunbyl** [comment]
I think so. thank you
