### ISSUE TITLE
Upgrade stemcell if needed.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#4082]
There's not a new stemcell on bosh.io

But assumably there should be one to fix the spectre and meltdown bugs.

We need to double check before releasing the tile.

**Comment by jessehu** [comment]
The latest stemcell version is 3468.19 https://bosh.io/stemcells/bosh-vsphere-esxi-ubuntu-trusty-go_agent
Harbor Tile now specified stemcell version '3468' which includes all "3468.*".

**Comment by reasonerjt** [comment]
Yep, so there's no further work needed, thanks.

**Comment by jessehu** [comment]
Per https://docs.pivotal.io/pivotalcf/2-0/stemcells/stemcell-v3468x.html, the latest 3468.21 stemcell contains a fix for Spectre vulnerability. Meltdown vulnerability is not covered yet.
Harbor Tile requires '3468' stemcell. So no tile change needed as long as the Harbor Tile users use the latest 3468.* stemcell.
