### ISSUE TITLE
Tile should collect the logs of Harbor containers.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#4089]
Currently if user sees an issue and wanna collect the log files of Harbor container after deployment, he has to pass a tedious process using `bosh`

We should try to enable opsman to collect log files under `/var/log/harbor`, to help user debug the issue or provide necessary information for support.

**Comment by jessehu** [comment]
Fixed by https://gitlab.eng.vmware.com/harbor/habo/merge_requests/14
