### ISSUE TITLE
sometimes there is a 504 error after login

### ISSUE THREAD

**Issue by cherry4477** [vmware/harbor#409]
during the process of showing projects after login, sometimes there is a 504 error .
here is the logs:
2016/06/24 06:35:12 [router.go:828][D] | GET        | /api/projects                            | 1m30.201684584s  | match      | /api/projects/
2016/06/24 06:36:18 [router.go:828][D] | GET        | /api/projects                            | 781.523896ms     | match      | /api/projects/
2016/06/24 06:38:34 [router.go:828][D] | GET        | /api/projects                            | 24.005764ms      | match      | /api/projects/

the logs above shows that the /api/projects runs unstablely and we guess this is the reason which causes the problem

**Comment by reasonerjt** [comment]
Thanks for reporting, I guess the time was spent to poll tags for every image.

Does it happen only after restarting the instance or does it happen all the time?

**Comment by reasonerjt** [comment]
BTW how many images are there in the registry?

**Comment by cherry4477** [comment]
it happens occasionally.  we have many projects and images.

**Comment by reasonerjt** [comment]
merged pr #434 
please try and see if this resolves the issue, 
further work will be tracked by #435

**Comment by reasonerjt** [comment]
this is a dup for #588 I'll close this issue and use #588 to track the fix.
