### ISSUE TITLE
Date format in filter is different with date format in replication logs

### ISSUE THREAD

**Issue by stonezdj** [vmware/harbor#4091]
Date format in filter is different with date format in replication logs

**Comment by stonezdj** [comment]
<img width="1293" alt="screen shot 2018-01-22 at 5 06 32 pm" src="https://user-images.githubusercontent.com/2696760/35212941-ddde4ea2-ff96-11e7-8d7b-0eec50186ac9.png">

**Comment by pengpengshui** [comment]
it‘s component's issue ,in ohter word ,it’s clarity's issue.
