### ISSUE TITLE
Justify the layout of replication policy creating/editing form based on the new mockup

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#4105]
mockup: https://vmware.invisionapp.com/share/B8FFF2MQ5XR#/screens/273227831

**Comment by lweitzman** [comment]
this image shows the clean up that should be easy to do in the next release for the full page creation / edit page.
![screen shot 2018-01-24 at 11 12 29 am](https://user-images.githubusercontent.com/626032/35343035-9b48374e-00f7-11e8-8d87-fcef66279ae8.png)

**Comment by lweitzman** [comment]
The cancel button should be enabled and work like the back breadcrumb at the top of the page.
