### ISSUE TITLE
No scroll bar when there are many repositories.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#411]
For example there are 180 repositories in this project.

<img width="1211" alt="screen shot 2016-06-24 at 7 18 48 pm" src="https://cloud.githubusercontent.com/assets/2390463/16336522/d0cf1f88-3a40-11e6-9132-d2102fee3395.png">

**Comment by wknet123** [comment]
fixed.

**Comment by reasonerjt** [comment]
verified, thanks
