### ISSUE TITLE
Harbor tile deploy failed when using self-signed cert and CA in concourse pipeline

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#4122]
Task 9 | 10:18:02 | Preparing deployment: Preparing deployment (00:00:01)
Task 9 | 10:18:04 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 9 | 10:18:04 | Updating instance harbor-app: harbor-app/13ba99d3-29e4-4dc1-acaf-a94b87cf491e (0) (canary) (00:11:43)
                   L Error: 'harbor-app/13ba99d3-29e4-4dc1-acaf-a94b87cf491e (0)' is not running after update. Review logs for failed jobs: harbor, bosh-dns, bosh-dns-healthcheck
Task 9 | 10:29:47 | Error: 'harbor-app/13ba99d3-29e4-4dc1-acaf-a94b87cf491e (0)' is not running after update. Review logs for failed jobs: harbor, bosh-dns, bosh-dns-healthcheck

Task 9 Started  Wed Jan 24 10:18:02 UTC 2018
Task 9 Finished Wed Jan 24 10:29:47 UTC 2018
Task 9 Duration 00:11:45
Task 9 error

Updating deployment:
  Expected task '9' to succeed but state is 'error'
Exit code 1
===== 2018-01-24 10:29:47 UTC Finished "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=30.0.0.11 --deployment=harbor-container-registry-1b868965d192d02f3781 deploy /var/tempest/workspaces/default/deployments/harbor-container-registry-1b868965d192d02f3781.yml"; Duration: 706s; Exit Status: 1
{"type": "step_finished", "id": "bosh.deploying.harbor-container-registry-1b868965d192d02f3781"}
Exited with 1.
could not execute "apply-changes": installation was unsuccessful

**Comment by steven-zou** [comment]
Issue found, the harbor_ca property is deleted by mistake in the commit https://gitlab.eng.vmware.com/harbor/habo-ci/commit/3d9983a901412cb49120deb533e87b2522d43acd

```
".properties.server_cert_ca": {
        "value": $harbor_ca
    },

```

@jessehu

**Comment by jessehu** [comment]
Thanks for the fix! Code review is very important.

**Comment by steven-zou** [comment]
close as issue is fixed
