### ISSUE TITLE
The default project in 'projects' textbox on 'New Replication Rule' should be removed

### ISSUE THREAD

**Issue by jessehu** [vmware/harbor#4127]
1) I have only 1 project 'library' and it's by default selected in the 'projects' textbox. This default value doesn't make any sense to the users, and may confuse the users (e.g. @wy65701436 and @jessehu) , so should be removed.
![image](https://user-images.githubusercontent.com/10006/35371903-d9d2e358-01d1-11e8-98ef-bfb74814d2a0.png)
2) The 'projects' textbox can only contain 1 single project, so its name should be 'Project', not 'Projects'.
@steven-zou @reasonerjt

**Comment by steven-zou** [comment]
@pengpengshui can help to fix it. We have talk about this issue just now.
