### ISSUE TITLE
repository descriptin  confirm problem

### ISSUE THREAD

**Issue by pengpengshui** [vmware/harbor#4129]
1. when click edit  and edit something , then click other module like logs .shoud have a confirm to leave dialog.

2. when click edit,  the cancel should disabled first .

**Comment by lweitzman** [comment]
I think it depends on what you are editing. some dialogs don't need a confirmation to leave the dialog. its more of an annoyance then being helpful. some content is easy to reproduce and no confirmation to close the dialog is necessary.
