### ISSUE TITLE
When testing connection for destination, when the password is invalid UI should display more readable error

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#413]
Currently I only see this:
<img width="511" alt="screen shot 2016-06-24 at 7 27 32 pm" src="https://cloud.githubusercontent.com/assets/2390463/16336687/cc51b960-3a41-11e6-96ee-1b938f063b79.png">

**Comment by wknet123** [comment]
Add error messages under the 'test connection' button.

**Comment by reasonerjt** [comment]
thanks
