### ISSUE TITLE
HA fails to start registry and load wrong harbor images

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#4130]
1, add one more space to the swift url, it makes Harbor crash.
2, wrong registry and nginx images, please refer to the harbor offline installer

vmware/nginx-photon:1.11.13
vmware/registry:2.6.2-photon

**Comment by yixingjia** [comment]
https://github.com/vmware/harbor/pull/4132

**Comment by wy65701436** [comment]
Close it as fixed.
