### ISSUE TITLE
Gas scan result for latest master code

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#4148]
{
	"issues": [
		{
			"severity": "HIGH",
			"confidence": "LOW",
			"details": "Potential hardcoded credentials",
			"file": "../src/github.com/vmware/harbor/src/common/const.go",
			"code": "UAAClientSecret             = \"uaa_client_secret\"",
			"line": 80
		},
		{
			"severity": "LOW",
			"confidence": "HIGH",
			"details": "Errors unhandled.",
			"file": "../src/github.com/vmware/harbor/src/common/notifier/scan_policy_notitification_handler.go",
			"code": "schedulePolicy.AttachTasks(attachTask)",
			"line": 103
		},
		{
			"severity": "HIGH",
			"confidence": "LOW",
			"details": "Potential hardcoded credentials",
			"file": "../src/github.com/vmware/harbor/src/common/security/admiral/authcontext/authcontext.go",
			"code": "AuthTokenHeader  = \"x-xenon-auth-token\"",
			"line": 35
		},
		{
			"severity": "HIGH",
			"confidence": "LOW",
			"details": "TLS InsecureSkipVerify may be true.",
			"file": "../src/github.com/vmware/harbor/src/common/utils/ldap/ldap.go",
			"code": "InsecureSkipVerify: !session.ldapConfig.LdapVerifyCert",
			"line": 238
		},
		{
			"severity": "HIGH",
			"confidence": "HIGH",
			"details": "TLS InsecureSkipVerify set true.",
			"file": "../src/github.com/vmware/harbor/src/common/utils/registry/registry.go",
			"code": "InsecureSkipVerify: true",
			"line": 48
		},
		{
			"severity": "LOW",
			"confidence": "HIGH",
			"details": "Errors unhandled.",
			"file": "../src/github.com/vmware/harbor/src/common/utils/test/test.go",
			"code": "io.Copy(w, bytes.NewReader(resp.Body))",
			"line": 75
		},
		{
			"severity": "HIGH",
			"confidence": "LOW",
			"details": "Potential hardcoded credentials",
			"file": "../src/github.com/vmware/harbor/src/common/utils/uaa/client.go",
			"code": "TokenURLSuffix = \"/oauth/token\"",
			"line": 35
		},
		{
			"severity": "HIGH",
			"confidence": "LOW",
			"details": "TLS InsecureSkipVerify may be true.",
			"file": "../src/github.com/vmware/harbor/src/common/utils/uaa/client.go",
			"code": "InsecureSkipVerify: cfg.SkipTLSVerify",
			"line": 184
		},
		{
			"severity": "LOW",
			"confidence": "HIGH",
			"details": "Errors unhandled.",
			"file": "../src/github.com/vmware/harbor/src/common/utils/utils.go",
			"code": "conn.Close()",
			"line": 103
		},
		{
			"severity": "MEDIUM",
			"confidence": "HIGH",
			"details": "Expect directory permissions to be 0700 or less",
			"file": "../src/github.com/vmware/harbor/src/jobservice/job/logger.go",
			"code": "os.MkdirAll(d, 0755)",
			"line": 31
		},
		{
			"severity": "HIGH",
			"confidence": "HIGH",
			"details": "TLS InsecureSkipVerify set true.",
			"file": "../src/github.com/vmware/harbor/src/jobservice/replication/delete.go",
			"code": "InsecureSkipVerify: insecure",
			"line": 175
		},
		{
			"severity": "HIGH",
			"confidence": "LOW",
			"details": "TLS InsecureSkipVerify may be true.",
			"file": "../src/github.com/vmware/harbor/src/jobservice/replication/transfer.go",
			"code": "InsecureSkipVerify: c.insecure",
			"line": 298
		},
		{
			"severity": "LOW",
			"confidence": "HIGH",
			"details": "Errors unhandled.",
			"file": "../src/github.com/vmware/harbor/src/ui/auth/ldap/ldap.go",
			"code": "dao.ChangeUserProfile(*u, \"Email\")",
			"line": 161
		},
		{
			"severity": "HIGH",
			"confidence": "LOW",
			"details": "Potential hardcoded credentials",
			"file": "../src/github.com/vmware/harbor/src/ui/config/config.go",
			"code": "defaultTokenFilePath string = \"/etc/ui/token/tokens.properties\"",
			"line": 40
		},
		{
			"severity": "HIGH",
			"confidence": "HIGH",
			"details": "TLS InsecureSkipVerify set true.",
			"file": "../src/github.com/vmware/harbor/src/ui/config/config.go",
			"code": "InsecureSkipVerify: true",
			"line": 131
		},
		{
			"severity": "LOW",
			"confidence": "HIGH",
			"details": "Errors unhandled.",
			"file": "../src/github.com/vmware/harbor/src/ui/main.go",
			"code": "notifier.Subscribe(notifier.ScanAllPolicyTopic, \u0026notifier.ScanPolicyNotificationHandler{})",
			"line": 119
		},
		{
			"severity": "LOW",
			"confidence": "HIGH",
			"details": "Errors unhandled.",
			"file": "../src/github.com/vmware/harbor/src/ui/main.go",
			"code": "notifier.Publish(notifier.ScanAllPolicyTopic, notifier.ScanPolicyNotification{Type: scanAllPolicy.Type, DailyTime: (int64)(dailyTime)})",
			"line": 132
		},
		{
			"severity": "HIGH",
			"confidence": "HIGH",
			"details": "Subprocess launching with variable.",
			"file": "../src/github.com/vmware/harbor/tests/apitests/api-testing/client/docker_client.go",
			"code": "exec.Command(cmdName, args...)",
			"line": 71
		},
		{
			"severity": "HIGH",
			"confidence": "HIGH",
			"details": "Subprocess launching with variable.",
			"file": "../src/github.com/vmware/harbor/tests/apitests/api-testing/client/docker_client.go",
			"code": "exec.Command(cmdName, args...)",
			"line": 75
		},
		{
			"severity": "LOW",
			"confidence": "HIGH",
			"details": "Errors unhandled.",
			"file": "../src/github.com/vmware/harbor/tests/apitests/api-testing/client/harbor_api_client.go",
			"code": "resp.Body.Close()",
			"line": 103
		}
	],
	"metrics": {
		"files": 282,
		"lines": 30003,
		"nosec": 0,
		"found": 20
	}
}

**Comment by ywk253100** [comment]
Fixed by #4157.
