### ISSUE TITLE
failed to initialize the system: unexpected database schema version, expected 1.4.0, got 0.4.0

### ISSUE THREAD

**Issue by zhanhuanxi** [vmware/harbor#4153]
failed to initialize the system: unexpected database schema version, expected 1.4.0, got 0.4.0

**Comment by reasonerjt** [comment]
Your DB is not updated.
Please refer to:
https://github.com/vmware/harbor/blob/master/docs/migration_guide.md

**Comment by zhanhuanxi** [comment]
版本不一致导致的，可以更换docker-compose.yml里面mysql的路径解决var/lib/mysql这个修改就可以，然后重新安装
