### ISSUE TITLE
0 items shows even I have repos and project members.

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#4163]
![image](https://user-images.githubusercontent.com/2841473/35498897-23c59e46-0485-11e8-9ecb-d2e0add56574.png)

![image](https://user-images.githubusercontent.com/2841473/35498924-3e1a6c22-0485-11e8-8cfe-3af62afac244.png)

**Comment by wy65701436** [comment]
But in the log page, it shows 1-15 when I do not have any logs.

![image](https://user-images.githubusercontent.com/2841473/35499313-acf74970-0486-11e8-83bc-bf14963e1669.png)

**Comment by ywk253100** [comment]
Verified.
