### ISSUE TITLE
Issue when changing or deleting member role of user himself

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#4164]
Login as user02 and try to change the role of himself:
![member_01](https://user-images.githubusercontent.com/5835782/35498956-8b6b489e-050b-11e8-97a4-42a89672d307.png)

Got error:
![member_02](https://user-images.githubusercontent.com/5835782/35498959-8d7510ca-050b-11e8-924e-870820b34ea1.png)

The `REMOVE` should be disabled when trying to delete himself:
![member_delete](https://user-images.githubusercontent.com/5835782/35499279-a481f836-050c-11e8-9d79-14745d31514e.png)

**Comment by wy65701436** [comment]
Encounter the same issue.

**Comment by pengpengshui** [comment]
had already change to when delete himself ,the remove button can't be clicked
