### ISSUE TITLE
Update vendor folder

### ISSUE THREAD

**Issue by zmlcc** [vmware/harbor#417]
The files under vendor folder are disordered. 
   1. By  the command `govendor list`, we can see some vendored packages are unused and some are missing.  
   2. Some additional third-party, e.g. `github.com/docker/distribution`, `github.com/docker/libtrust` and `github.com/go-sql-driver/mysql`,  need to be downloaded when building  docker image.  It wastes a log of time while the network is not good

I suggest reorder the vendor folder with `govendor` tool, adding all dependent third-party project files under vendor folder.  So in the dockerfile, do not need to download other packages  but just copy harbor source files.

**Comment by reasonerjt** [comment]
@zmlcc thanks for raising this.  
github.com/docker/distribution, github.com/docker/libtrust and github.com/go-sql-driver/mysql are not in the vendor folder because it's advised by our legal team that we can not put the source code in our repo due to license issue.

**Comment by zmlcc** [comment]
@reasonerjt   What a pity
But partial adding file into vendor folder may cause problems of  dependency relationship of third-party project. And a litte hard for maintenance.

BTW,  what is the upgrade strategy for the vendors?    If I suggest to update some vendor projects (e.g.  beego), should I add open a new issue ?

**Comment by reasonerjt** [comment]
I've updated to 1.6.1

**Comment by hainingzhang** [comment]
fixed.
