### ISSUE TITLE
Issue when clicking the project name in replication rule list

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#4176]
When clicking the project name in the replication rule list, UI loads its jobs first, and then jumps to the project page:
![click_pro_name_01](https://user-images.githubusercontent.com/5835782/35509900-f698628a-0530-11e8-94e7-262de3c4acdf.png)

![click_pro_name_02](https://user-images.githubusercontent.com/5835782/35509901-f7a55930-0530-11e8-9c0c-fc69d062b8f3.png)

**Comment by reasonerjt** [comment]
This seems a limitation of the component in clarity?

**Comment by pengpengshui** [comment]
had solved
