### ISSUE TITLE
SELinux label for Clair and Notary volumes

### ISSUE THREAD

**Issue by ianharrier** [vmware/harbor#4178]
**Problem:** On a Docker host with SELinux enabled, if installing Harbor with Clair and/or Notary, the Clair/Notary containers will have volume permission issues.

**Diagnosis:** In the `docker-compose.yml` file, all of the volume mounts use [the SELinux label (i.e. `:z`)](https://docs.docker.com/engine/admin/volumes/bind-mounts/#configure-the-selinux-label) to get around this issue, but the volume mounts in the `docker-compose.clair.yml` and `docker-compose.notary.yml` files do not (as of [Harbor 1.3.0](https://github.com/vmware/harbor/releases/tag/v1.3.0)).

**Recommended solution:** Add `:z` to all of the volume mounts in the `docker-compose.clair.yml` and `docker-compose.notary.yml` files. I tried this on a clean install of CentOS 7 with Docker 1.12.6 and Docker Compose 1.18.0, and everything works as expected.

**Comment by ywk253100** [comment]
@ianharrier Thanks.
Fixed by #4183, closing this issue.
