### ISSUE TITLE
Add REST API for adding LDAP group to project member

### ISSUE THREAD

**Issue by stonezdj** [vmware/harbor#4182]
1.  LDAP group information configuration API
2. Maintain group member

> GET /api/ldap/groups  -- Get all groups in LDAP
> GET /api/groups?type=ldap -- Get all LDAP groups in local DB
> POST /api/groups Payload {group_name:"harbor_users", group_type:"ldap", group_dn:"CN=harbor_users,OU=sample,OU=vmware,DC=harbor,DC=com" -- Create ldap group in local DB
> DELETE /api/groups/<groupid> Delete group from local DB
>

**Comment by reasonerjt** [comment]
After reviewing the PR there some change needed, let's delay this to Sprint 30.
