### ISSUE TITLE
User search should clean selection cache 

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#4185]
1, Select all users.
2, Search User1.
3, Click Delete.

![image](https://user-images.githubusercontent.com/2841473/35553562-3bd81a0e-054d-11e8-9b69-39f154f0c384.png)

**Comment by reasonerjt** [comment]
The proposed solution: when the user triggers a search, unselect all items.
Please make sure all data grids apply this change.

However, there's confirmation dialog to mitigate the risk, this is low-priority, will re-visit.
