### ISSUE TITLE
/etc/jobservice/key does not exist when deploy harbor on kubernetes 

### ISSUE THREAD

**Issue by garyyang85** [vmware/harbor#4199]
I am deploying harbor 1.2 on kubernetes 1.8.3, when tried to copy repository, it reports error:
**2018-01-31T08:14:40Z [ERROR] [workerpool.go:101]: Worker {ID: 2, Type: Replication}, failed to re-initialize statemachine for job: {JobID: 3, JobType: Replication}, error: open /etc/jobservice/key: no such file or directory**

But this function work on the harbor which is setup with **docker compose**, and I checked the /etc/jobservice/key is there in the container.

**Comment by likunbyl** [comment]
In kubernetes, you should mount the SECRET_KEY to the /etc/jobservice/key , SECRET_KEY is defined in your jobservice.cm.yaml

**Comment by reasonerjt** [comment]
Is this fixed? @garyyang85

**Comment by reasonerjt** [comment]
Close due to inactivity.
