### ISSUE TITLE
Pagenation of User search doesn't work

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#4205]
![image](https://user-images.githubusercontent.com/2841473/35660435-cc4cd10a-06c0-11e8-8fbd-3b86f7ab1cc3.png)

**Comment by steven-zou** [comment]
Pagination of user list is driven by front end at present.
The filter function is based on the front end users data.
The filter does not support pagination yet, that means all the search results will be listed in the list together and the pagination is kept as it was. 

Plan to use backend pagination in next release.
