### ISSUE TITLE
The size of the repositories is not correct in harbor 1.3.0

### ISSUE THREAD

**Issue by likunbyl** [vmware/harbor#4213]
The size of some repositories in not correct in harbor 1.3.0,  like this one: 

![image](https://user-images.githubusercontent.com/20676359/35714512-0b37d4da-0808-11e8-868c-19af7a67ffe4.png)

While actually I pull the image to my host, it's 722MB:

![image](https://user-images.githubusercontent.com/20676359/35714544-54c0ba0e-0808-11e8-9cda-84d7a2ccd35e.png)

Any hints?

likun

**Comment by ywk253100** [comment]
The images saved in Harbor are compressed, so the size should be less than that you get in docker client, but it shouldn't diff so much.
Could you push the image to docker hub so that we can pull it and check what happened?

**Comment by likunbyl** [comment]
Sorry , this image should keep private. I noticed that this image is pushed from a centos 6.6 server, which is running docker client version 1.7.1, and the registry data is transfered from a harbor 0.5.0 server, does this have any relations with this problem  ?

**Comment by ywk253100** [comment]
Yes, the docker client 1.9 or older only supports manifest version1, while the image size is calculated according to version2. You can pull the image with docker 1.10+ and push it back, the size should be corrected.

**Comment by likunbyl** [comment]
thanks. I will try it after upgrade.

**Comment by stevenyslin** [comment]
Dear @ywk253100 

In docker 17.12.0-ce also have this problem,
Can Harbor just only use docker 1.10 ?
Thank you for your help.
