### ISSUE TITLE
can not see  the tag

### ISSUE THREAD

**Issue by fangdaidai** [vmware/harbor#4219]
pushed  successed  ，it also  support pull，but i can not see  the  tag  and version，and i  can not   delete   it
![image](https://user-images.githubusercontent.com/10492443/35786636-93d29eda-0a63-11e8-944d-7394299be306.png)

**Comment by reasonerjt** [comment]
Please provide more details, such as what installation package was used, etc.

**Comment by fangdaidai** [comment]
![image](https://user-images.githubusercontent.com/10492443/35787755-7ec8ed66-0a6b-11e8-9b6c-ee7ed726dbb6.png)
and  change the  name， i can see
![image](https://user-images.githubusercontent.com/10492443/35787778-a82d8dba-0a6b-11e8-80d6-71db14fb4951.png)

when  "/" more than 2 times, it has a bug???

**Comment by reasonerjt** [comment]
what do you mean by `when "/" more than 2 times`

Could you provide more docker commands to elaborate?

**Comment by fangdaidai** [comment]
yes   i  use the offline installer  ;
for example:
1.   docker tag  SOURCE_IMAGE[:TAG]    xxx.xx/td/adbox-report:0.0.5.28
      docker push xxx.xx/td/adbox-report:0.0.5.28
 it is worked,from the UI  ,i can  see  the  tag and version;

2.  docker tag  SOURCE_IMAGE[:TAG]  xxx.xx/td/adbox/report:0.0.5.28
    docker push xxx.xx/td/adbox/report:0.0.5.28
it pushed successfully,But i can not see the tag and version from the harbor-UI

**Comment by ywk253100** [comment]
Provide the logs under directory `/var/log/harbor`.

**Comment by fangdaidai** [comment]
[Uploading registry.log.gz…]()
[Uploading mysql.log.gz…]()

[Uploading proxy.log.gz…]()
[Uploading jobservice.log.gz…]()
[Uploading adminserver.log.gz…]()


![image](https://user-images.githubusercontent.com/10492443/35790620-51f443e0-0a7e-11e8-82b2-aee5cc056fd9.png)

**Comment by fangdaidai** [comment]
[adminserver.log](https://github.com/vmware/harbor/files/1694016/adminserver.log)
[ui.log](https://github.com/vmware/harbor/files/1694017/ui.log)
[registry.log](https://github.com/vmware/harbor/files/1694018/registry.log)
[mysql.log](https://github.com/vmware/harbor/files/1694019/mysql.log)
[proxy.log](https://github.com/vmware/harbor/files/1694020/proxy.log)
[jobservice.log](https://github.com/vmware/harbor/files/1694021/jobservice.log)


![image](https://user-images.githubusercontent.com/10492443/35790771-06a94088-0a7f-11e8-9467-8343a6cea1a3.png)

**Comment by ywk253100** [comment]
Seems that there is something wrong with frontend pages. Can you try to clear the cache of the browser? If this has no effect, you can open the debugger of the browser and check if there is any error.

**Comment by fangdaidai** [comment]
yes，it is  the cache of the browser，thank you！
