### ISSUE TITLE
Firefox browser can not save a replication rule using an existing endpoint

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#4233]
Firefox browser can not save a replication rule using an existing endpoint

![rrrep](https://user-images.githubusercontent.com/23101283/35847723-6645307e-0b56-11e8-81ee-7b1eb3a79e9c.PNG)

**Comment by pengpengshui** [comment]
the  new/edit replication rule module had change to diaplay in dialog mode. let's check it in  the latest version.
