### ISSUE TITLE
docker-1.12 removed "syslog-tag" option from log driver

### ISSUE THREAD

**Issue by tinytub** [vmware/harbor#424]
docker-1.12 have removed syslog-tag
I have try to change "syslog-tag" to "tag" in docker-compose.yml but it dosen't work.
So from docker-1.12 I can not get harbor's logs.

How can I get harbor's logs back?

**Comment by reasonerjt** [comment]
I haven't tried 1.12 yet, let's keep this issue open.

**Comment by reasonerjt** [comment]
I assume there's update in API of docker daemon and the docker-compose has to be updated accordingly.

**Comment by SolarisYan** [comment]
i use docker on win10 and have error as follow:

deploy_log_1 is up-to-date
Creating deploy_ui_1
Creating deploy_mysql_1
Creating deploy_registry_1

ERROR: for ui  unknown log opt 'syslog-tag' for syslog log driver

ERROR: for registry  unknown log opt 'syslog-tag' for syslog log driver

ERROR: for mysql  unknown log opt 'syslog-tag' for syslog log driver
ERROR: Encountered errors while bringing up the project.

**Comment by reasonerjt** [comment]
fixed in #506 and #507
