### ISSUE TITLE
Manifest for vmware/harbor-db:v1.4.0 not found

### ISSUE THREAD

**Issue by jared-w** [vmware/harbor#4243]
The install script will attempt to pull the harbor-db:v1.4.0 image (as specified in the docker-compose.yml) but currently there is no tag for v1.4.0 (https://hub.docker.com/r/vmware/harbor-db/tags/ 1.4.0-rc2 is the latest).

I'm guessing this is likely already on the radar, but I couldn't find anything on the tracker.

**Comment by wy65701436** [comment]
thanks for reporting, it has been fixed, just try again.
