### ISSUE TITLE
Replication rule endpoint layout error  on Firefox

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#4245]
![rule](https://user-images.githubusercontent.com/23101283/35960509-dc2834b4-0ce4-11e8-9dc6-824626891dd6.PNG)

This issue happens on Firefox 
When add a new replication rule, in endpoint select part, add a new endpoint after add a new end point, there will two drop-down select, if you continue add new endpoints, there will more and more
This will happen on source project part

![rule1](https://user-images.githubusercontent.com/23101283/35965114-d10b0808-0cf4-11e8-8b76-3456f41e7e72.PNG)

**Comment by pengpengshui** [comment]
I had't reappear the scene you mentioned ahead, my firefox version is 58.0.2(32 Bit),   what I want to say is the  new/edit replication rule module had change to diaplay in dialog mode. let's check it in  the latest version.
