### ISSUE TITLE
Create Helm Chart for Harbor.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#4247]
1)  Use helm script to generate certificate/secret.
2)  Bottom line Integrate with 1.4.0 release.  Try to integrate with 1.5.0 release, no commit in quality.
3)  Contribute to `incubator` repository. -- p2
4)  No CI, No migration support.

**Comment by reasonerjt** [comment]
https://github.com/vmware/harbor-planning/issues/4

**Comment by jessehu** [comment]
Please find more request and design details on https://github.com/vmware/harbor-planning/issues/4

**Comment by jessehu** [comment]
We now support Harbor 1.4.0 GA release in the chart.
