### ISSUE TITLE
Harbor builds on new drone infra

### ISSUE THREAD

**Issue by mdharamadas1** [vmware/harbor#4250]
There are few changes as part of Drone 0.8. This is to investigate those changes and make necessary updates. Also, this will involve making sure all drone secrets are updated and all build steps run as expected.

A/C:
- Harbor build steps run on new drone infra as expected

**Comment by mdharamadas1** [comment]
Can someone add this issue to an epic vic#6834?

**Comment by mdubya66** [comment]
Added @mdharamadas1.
