### ISSUE TITLE
Implement Helm Chart for Harbor 1.4.0

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#4254]
- [x] Merge Harbor Helm Chart PR https://github.com/vmware/harbor/pull/4271 which works for Harbor 1.3 without Notary support.
- [x] Make Harbor Helm Chart works for Harbor 1.4.0 release
- [x] Use external postgres database chart for Clair to remove unnecessary postgres chart code

**Comment by paulczar** [comment]
I have fully working helm charts that I'm working with the upstream helm community with. 
 https://github.com/kubernetes/charts/pull/3383

**Comment by paulczar** [comment]
* [ ]  use external postgres database chart for clair
* [ ]   use external percona / percona-xtradb-cluster chart for database
* [ ]   build a image for just the .sql and migration scripts for database that can be used to set up external database as a kubernetes job.

**Comment by jessehu** [comment]
Track Notary support in https://github.com/vmware/harbor/issues/4394

**Comment by jessehu** [comment]
Use external postgres database chart for Clair https://github.com/vmware/harbor/pull/4389/ is merged.
