### ISSUE TITLE
Complete Harbor section in vic-product SUPPORT.md

### ISSUE THREAD

**Issue by andrewtchin** [vmware/harbor#4263]
This guide is targeted to GSS and VIC product developers who may handle escalations related to Harbor in the VIC appliance
https://github.com/vmware/vic-product/blob/master/installer/docs/SUPPORT.md

Please fill out this section https://github.com/vmware/vic-product/blob/master/installer/docs/SUPPORT.md#harbor

**Comment by reasonerjt** [comment]
Fixed by https://github.com/vmware/vic-product/pull/1457
