### ISSUE TITLE
Bad Interpreter : Python No such File or Directory 

### ISSUE THREAD

**Issue by AntFuller** [vmware/harbor#4265]
Docker verison: 17.05.0
Docker-compose version: 1.19.0
Ubuntu Ubuntu 16.04

When running the instal shell command I get a bad interpreter command . I have tried two builds now and this has always worked for me ..

root@nfweng:/etc/harbor# ./install.sh: ./prepare: /usr/bin/python: bad interpreter: No such file or directory

**Comment by AntFuller** [comment]
Docker verison: 17.05.0
Docker-compose version: 1.19.0
Ubuntu Ubuntu 16.04 

When running the instal shell command I get a bad interpreter command . I have tried two builds now and this has always worked for me ..

root@nfweng:/etc/harbor# ./install.sh: ./prepare: /usr/bin/python: bad interpreter: No such file or directory

**Comment by AntFuller** [comment]
Sorry user error I had Python3 installed .

**Comment by aboyaniv** [comment]
hi,

I have the same problem and python3 is installed, 
what to do ?

**Comment by aboyaniv** [comment]
I did
tdnf install python2

**Comment by chance2021** [comment]
In my case, the error shows in Github action and the root cause is the broken python symbolic link. As a workaround, I just simply re-create it during the process.
```
Error：
home/runner/work/_temp/810926a2-36c5-4488-ac84-6f3f57713147.sh: /home/runner/work/dataops/dataops/.venv/bin/pytest: /home/runner/work/dataops/dataops/.venv/bin/python: bad interpreter: No such file or directory

Root Cause:
/home/runner/work/dataops/dataops/.venv/bin/python: broken symbolic link to /opt/hostedtoolcache/Python/3.9.15/x64/bin/python3.9

Solution:
Add below scripts into wherever has broken link:
        PYTHON_PATH=$(which python3)
        source .venv/bin/activate
        PYTHON_BROKEN_PATH=$(dirname $(which pip))
        rm $PYTHON_BROKEN_PATH/python
        ln -s $PYTHON_PATH $PYTHON_BROKEN_PATH/python
        export PATH=$PATH:$(dirname $PYTHON_BROKEN_PATH)
```

**Comment by herminejuanjuan** [comment]
I also only installed python3, but I successfully solved the problem by executing: **sudo ln -s /usr/bin/python3.10 /usr/bin/python** to create a software link.
