### ISSUE TITLE
Optional clair endpoint

### ISSUE THREAD

**Issue by a-kinder** [vmware/harbor#4269]
We've just deployed Harbor and Clair on our dev Kubernetes cluster and added TLS to Clair, but it appears that there is not option to set the Clair endpoint to anything other than http://clair:6060 as it seems to be hard coded in [const.go](https://github.com/vmware/harbor/blob/8cda2d8d651d1678f1e0e96ea6043dd37bb98770/src/common/const.go#L82). Can an option be added to override this variable?

**Comment by jessehu** [comment]
cc @yixingjia

**Comment by reasonerjt** [comment]
@yixingjia could you confirm if we can close this issue?

**Comment by yixingjia** [comment]
clair endpoint is now configurable.
