### ISSUE TITLE
[Help] UI exit after timeout to clair -- Clair configuration should be reloaded.

### ISSUE THREAD

**Issue by Angelinsky7** [vmware/harbor#4277]
Hi,
i'm trying to make Harbor works in a Rancher Environment and everything is working very fine but the connection to clair.

```
[ERROR] [utils.go:98]: failed to connect to tcp://clair:3306, retry after 2 seconds :dial tcp 172.28.0.4:3306: getsockopt: connection refused
```

I don't understand why i got this error and why...
it's obvious that the connection to the clair is either 6060 (the api) or 5432 (postgres) but this attempt does not make any sense for me...

I checked the code and it's seems clear the it's a configuration on my side issue but i don't understand what i need to give to the ui container...
https://github.com/vmware/harbor/blob/be397eb1572902128cd00ffacca53826a5c4d5e7/src/ui/main.go#L97-L105

I know it's not a "conventional" use of Harbor because i don't use the installer but everything is working perfectly fine but clair and it's really very frustrating not understanding why. Could someone help me with this ?

Thanks a lot in advance for all the hint that you could give me... (but i would really appreciate that you don't say, could you re-run the installer, because... i don't/can't use it !!! + clair is correctly working i had tested it...)

Here's my ui container config :
```
ui:
    image: vmware/harbor-ui:v1.4.0
    volumes:
      - ./ui.app.conf:/etc/ui/app.conf:z
      - ./ui.private_key.pem:/etc/ui/private_key.pem:z
      - ./certificates/:/etc/ui/certificates/:z
      - ./harbor.secretkey:/etc/ui/key:z
      # - ./data/ca_download/:/etc/ui/ca/:z
      # - ./data/psc/:/etc/ui/token/:z
    links:
      - adminserver
      - registry
      - postgres:clair
    environment: 
      LOG_LEVEL: debug
      CONFIG_PATH: /etc/ui/app.conf
      UI_SECRET: 1111222233334444
      JOBSERVICE_SECRET: 5555666677778888
      GODEBUG: netdns=cgo
      ADMINSERVER_URL: http://adminserver:8080
      UAA_CA_ROOT: /etc/ui/certificates/uaa_ca.pem
      # _REDIS_URL: $redis_url
```

/ui.app.conf :
```
appname = Harbor
runmode = dev
enablegzip = true

[dev]
httpport = 8080
```
Docker : 
Docker version 17.12.0-ce, build c97c6d6 (Window 10 and Linux Debian)
Docker-compose :
docker-compose version 1.18.0, build 8dd22a96

Harbor config :
```
PORT: 8080
LOG_LEVEL: debug

EXT_ENDPOINT: http://10.138.222.53
AUTH_MODE: db_auth
SELF_REGISTRATION: 'on'
HARBOR_ADMIN_PASSWORD: Harbor12345
PROJECT_CREATION_RESTRICTION: everyone
MAX_JOB_WORKERS: 3
UI_SECRET: 1111222233334444
JOBSERVICE_SECRET: 5555666677778888
TOKEN_EXPIRATION: 30
CFG_EXPIRATION: 5
GODEBUG: netdns=cgo
ADMIRAL_URL: NA

# LDAP_URL: $ldap_url
# LDAP_SEARCH_DN: $ldap_searchdn
# LDAP_SEARCH_PWD: $ldap_search_pwd
# LDAP_BASE_DN: $ldap_basedn
# LDAP_FILTER: $ldap_filter
# LDAP_UID: $ldap_uid
# LDAP_SCOPE: $ldap_scope
# LDAP_TIMEOUT: $ldap_timeout
# LDAP_VERIFY_CERT: $ldap_verify_cert

DATABASE_TYPE: mysql
MYSQL_HOST: mysql
MYSQL_PORT: 3306
MYSQL_USR: harbor
MYSQL_PWD: harbor_password
MYSQL_DATABASE: harbor

REGISTRY_URL: http://registry:5000
TOKEN_SERVICE_URL: http://10.138.222.53/service/token
UI_URL: http://ui:8080
JOBSERVICE_URL: http://jobservice:8080
      
EMAIL_HOST: mail.darkink.ch
EMAIL_PORT: 465
EMAIL_USR: harbo@darkink.ch
EMAIL_PWD: email_pwd
EMAIL_SSL: 'true'
EMAIL_FROM: harbo@darkink.ch
EMAIL_IDENTITY: harbo@darkink.ch
EMAIL_INSECURE: 'false'

WITH_NOTARY: 'false'

WITH_CLAIR: 'true'
CLAIR_DB_PASSWORD: clair_password
CLAIR_DB_HOST: postgres
CLAIR_DB_PORT: 5432
CLAIR_DB_USERNAME: clair
CLAIR_DB: clair

RESET: 'false'

# UAA_ENDPOINT: $uaa_endpoint
# UAA_CLIENTID: $uaa_clientid
# UAA_CLIENTSECRET: $uaa_clientsecret
# UAA_VERIFY_CERT: $uaa_verify_cert
      
REGISTRY_STORAGE_PROVIDER_NAME: filesystem
```

**Comment by Angelinsky7** [comment]
Found the issue after jours of research...
it seems that "you" don't update the database table properties with the new values.

```
clair_db
clair_db_host
clair_db_port
clair_db_username
```

only **clair_db_password** is regenerated each time the container is run

that was why this error appears the first time i launched harbor i set the clair variables with dummy values and even if i changed them, the container didn't update them automatically....

i think it's a bug...
i checked with the installer and the prepare script it's the same behaviour (seems logical)

**Comment by reasonerjt** [comment]
Root cause adminserver is not reloading the data about clair.
@Angelinsky7 thanks for reporting!

**Comment by yixingjia** [comment]
https://github.com/vmware/harbor/pull/4349 should fix this.
