### ISSUE TITLE
The "Confirm Repository Deletion" modal dialog does not close when the "Delete" button is pressed

### ISSUE THREAD

**Issue by AntonioFilipov** [vmware/harbor#4278]
In Admiral, we are using **harbor-ui: 0.6.9**. If this issue is already fixed, could you point us to the right version of the dependency. This is a recording of the issue - https://jira.eng.vmware.com/secure/attachment/134873/confirm-repositry-deletion.webm.

Thanks,
Antonio.

**Comment by ninjadq** [comment]
Stack view is deprecated and the deleting process is redesigned.
