### ISSUE TITLE
点击【配置管理】后，再点击其他标签提示弹出“配置更改”对话框

### ISSUE THREAD

**Issue by dangzhiqiang** [vmware/harbor#4281]
harbor版本v1.4.0，离线安装包安装。

**问题描述：**
当点击【配置管理】后，不做任何修改，再点击其他标签，会弹出如下“配置更改”对话框，显然未做任何更改，不应该弹出这个对话框。
![image](https://github.com/dangzhiqiang/images/blob/master/harbor/v1.4.0-notify.jpg?raw=true)

**Comment by pengpengshui** [comment]
测试人员测试了1.4.0版本，并没有发现你提到的问题。你是否能提供更详细的信息或者操作步骤？ @dangzhiqiang

**Comment by dangzhiqiang** [comment]
@pengpengshui 谢谢反馈，清除浏览器缓存后我又测试了一下，没有了，测试服务器之前部署过低版本的harbor，浏览器登陆过，升级后再次用同一个浏览器访问发现的问题，估计是浏览器缓存造成的。
该问题我先关闭，后面如果遇到，再打开该问题。
