### ISSUE TITLE
Change of 'Allow Self-Registration' can not be saved

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#4284]
IHAC that is reporting the following:
Harbor was deployed using Harbor tile version v1.4.1, this is not a tile issue but when we interact with Harbor UI

Under https://<harbor-ui-fqdn>/harbor/configs or from harbor UI when you navigate to Administration -> Configuration when trying to disable `Allow Self-Registration`, on unchecking the box   the save button on the screen remains disabled and user is not able to save the configuration.

This issue has not been reported by any customer yet but it is a potential security concern.

I am not finding anything related in JIRA https://jira.eng.vmware.com/secure/RapidBoard.jspa?rapidView=2192&projectKey=PKS&view=planning.nodetail&quickFilter=10489&epics=visible

**Comment by reasonerjt** [comment]
I don't reproduce with 1.4.0 offline installer, probably a cross-browser issue?

**Comment by rtindallarkin** [comment]
used chrome and firefox so far, the issue is same with both the browsers

**Comment by reasonerjt** [comment]
@steven-zou @pengpengshui Let's try to reproduce with a tile.

**Comment by rtindallarkin** [comment]
Safari as well same issue. If team needs to see a reproduction of this issue and it helps, am open to a webex session.

**Comment by steven-zou** [comment]
Comparing the harbor version and related images sha256, totally same. But harbor installed through offline installer does work well, but the harbor installed via tile does not work. Will do further investigations.

**Comment by steven-zou** [comment]
@rtindallarkin 
  I think we got the root cause: there might be existing invalid input fields in the 'email' tab, please confirm the mandatory fields are input valid values and then try again. The status of 'Save' button is controlled by all the sections in the config page at present.

  We'll raise new issue to refactor this component, the status of buttons only influenced by the widgets in current section/tab.

**Comment by rtindallarkin** [comment]
I have asked them to validate if this makes a difference for them. I am currently awaiting their response

**Comment by rtindallarkin** [comment]
Update from Customer on this issue
hat was the issue. After I entered email the Save button on each tab is working as expected. As you mentioned in your last update that you will be creating a new issue to refactor this component, the status of buttons should only be influenced by the widgets in current section/tab. This should be good enough and there are no further questions from my side.

**Comment by steven-zou** [comment]
@rtindallarkin 
 Got it, thanks. I'll close this issue.
