### ISSUE TITLE
how to run: make build

### ISSUE THREAD

**Issue by rootdeep** [vmware/harbor#4289]
Recently, I planed to build the harbor image by myself.  I downloaded the  source code of harvor v1.4. 
and my source code path is:  /root/go/src/github.com/vmware/harbor. I did the 2 steps:
1. cd   /root/go/src/github.com/vmware/harbor
2.  make build

when building  the  adminserver , I encountered the problem. Follow is the output.

building adminserver container for photon...
/usr/bin/docker build -f /root/go/src/github.com/vmware/harbor/make/photon/adminserver/Dockerfile -t vmware/harbor-adminserver:dev .
Sending build context to Docker daemon  67.58MB
Step 1/7 : FROM vmware/photon:1.0
 ---> 9b411d78ad9e
Step 2/7 : RUN tdnf erase vim -y     && tdnf distro-sync -y || echo     && tdnf install -y sudo     && tdnf clean all     && groupadd -r -g 10000 harbor && useradd --no-log-init -r -g 10000 -u 10000 harbor     && mkdir /harbor/
 ---> Using cache
 ---> 499e41619170
Step 3/7 : COPY ./make/dev/adminserver/harbor_adminserver ./make/photon/adminserver/start.sh /harbor/
lstat make/dev/adminserver/harbor_adminserver: no such file or directory
make[1]: *** [_build_adminiserver] Error 1
make[1]: Leaving directory `/root/go/src/github.com/vmware/harbor'
make: *** [build] Error 2

As the output said, there is no harbor_adminserver  under make/dev/adminserver/.
In fact, the harbor_adminserver is  not existed under make/dev/adminserver/ both in source code v1.2 and v1.4. 

So, how to solve it ? 

1)Version of docker engine and docker-compose.
2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
3)Log files, you can get them by package the /var/log/harbor/ .

**Comment by wy65701436** [comment]
@rootdeep, these binary files was created by "Make compile". 

The easiest way for you to build your own harbor image is to use "Make install", but it will build all harbor images. 

You can refer to the compile guide for details, just run "make install" in your source root.

**Comment by rootdeep** [comment]
Actually, I  did "make install" or "make compile" command. But both  are failed.  Bellow is the output.
--------------------------------------------------------------------
Note: golang version: 1.10

Note: docker version: 17.05.0

Note: docker-compose version: 1.19.0
compiling binary for clarity ui...
/usr/bin/docker: invalid reference format.
See '/usr/bin/docker run --help'.
make: *** [compile_clarity] Error 125
--------------------------------------------------------------------

I  read the Makefile under harbor, replaced the variables in compile command for clarity ui and run the command alone,  I get the same error . The command is :
/usr/bin/docker run  --rm -v /root/go/src/github.com/vmware/harbor/src:/harbor_src  vmware/harbor-clarity-ui-builder[:tag] /bin/bash  /entrypoint.sh

I finally narrowed down the problem to the format of  image name. The "  [:tag]  " in vmware/harbor-clarity-ui-builder[:tag]  is not replaces by any real value when running "make install" or "make compile" . So the error happened. But how to resolve this error. Another  similar format are existed in Makefile, 
 GOBUILDIMAGE=reg.mydomain.com/library/harborgo[:tag].

**Comment by wy65701436** [comment]
Use this command to build your source, set NOTARYFLAG or CLAIRFLAG to false if you don't need it, and remove the httpproxy setting if no need.

make install GOBUILDIMAGE=golang:1.9.2 COMPILETAG=compile_golangimage CLARITYIMAGE=vmware/harbor-clarity-ui-builder:1.3.0 NOTARYFLAG=true CLAIRFLAG=true HTTPPROXY=

**Comment by rootdeep** [comment]
Ok , thanks.
