### ISSUE TITLE
[Issue] Harbor Database Migration Document Have a Error

### ISSUE THREAD

**Issue by yhua123** [vmware/harbor#429]
on step 2: build image from dockerfile

- cd harbor-migration
- docker build -t migrate-tool 

console:

_unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat .../harbor/migration/migration_harbor/Dockerfile: no such file or directory_

.

**Comment by reasonerjt** [comment]
@yhua123 thanks I will remove the step "cd harbor-migration"

**Comment by yhua123** [comment]
verified
