### ISSUE TITLE
nginx constantly restarting

### ISSUE THREAD

**Issue by choman** [vmware/harbor#4290]
## nginx constantly restarting
This somehow just started happening, having problems getting into the container to spot check the existance of libz.so

- Redhat 7.4
- Harbor 1.2.0
- Docker 17.09.0
- docker-compose 1.16.1

## from prox.log
Feb 25 12:48:35 172.18.0.1 proxy[984]: nginx: [emerg] PEM_read_bio_X509_AUX("/etc/nginx/cert/local.net.crt") failed (SSL: error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:filename(libz.so): libz.so: cannot open shared object file: No such file or directory error:25070067:DSO support routines:DSO_load:could not load the shared library error:0906D06C:PEM routines:PEM_read_bio:no start line)

## Configuration file of Harbor

#The IP address or hostname to access admin UI and registry service.
#DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
hostname = reg2.local.net

#The protocol for accessing the UI and token/notification service, by default it is http.
#It can be set to https if ssl is enabled on nginx.
ui_url_protocol = https

#The password for the root user of mysql db, change this before any production use.
db_password = root123

#Maximum number of job workers in job service
max_job_workers = 3

#Determine whether or not to generate certificate for the registry's token.
#If the value is on, the prepare script creates new root cert and private key
#for generating token to access the registry. If the value is off the default key/cert will be used.
#This flag also controls the creation of the notary signer's cert.
customize_crt = on

#The path of cert and key files for nginx, they are applied only the protocol is set to https
ssl_cert = /data/cert/local.net.crt
ssl_cert_key = /data/cert/local.net.key

#The path of secretkey storage
secretkey_path = /data

#Admiral's url, comment this attribute, or set its value to NA when Harbor is standalone
admiral_url = NA
#The password of the Clair's postgres database, only effective when Harbor is deployed with Clair.
#Please update it before deployment, subsequent update will cause Clair's API server and Harbor unable to access Clair's database.
clair_db_password = password

#NOTES: The properties between BEGIN INITIAL PROPERTIES and END INITIAL PROPERTIES
#only take effect in the first boot, the subsequent changes of these properties
#should be performed on web ui

#************************BEGIN INITIAL PROPERTIES************************

#Email account settings for sending out password resetting emails.

#Email server uses the given username and password to authenticate on TLS connections to host and act as identity.
#Identity left blank to act as username.
email_identity =

email_server = smtp.mydomain.com
email_server_port = 25
email_username = sample_admin@mydomain.com
email_password = abc
email_from = admin <sample_admin@mydomain.com>
email_ssl = false

##The initial password of Harbor admin, only works for the first time when Harbor starts.
#It has no effect after the first launch of Harbor.
#Change the admin password from UI after launching Harbor.
harbor_admin_password = Harbor12345

##By default the auth mode is db_auth, i.e. the credentials are stored in a local database.
#Set it to ldap_auth if you want to verify a user's credentials against an LDAP server.
auth_mode = db_auth

#The url for an ldap endpoint.
ldap_url = ldaps://ldap.mydomain.com

#A user's DN who has the permission to search the LDAP/AD server.
#If your LDAP/AD server does not support anonymous search, you should configure this DN and ldap_search_pwd.
#ldap_searchdn = uid=searchuser,ou=people,dc=mydomain,dc=com

#the password of the ldap_searchdn
#ldap_search_pwd = password

#The base DN from which to look up a user in LDAP/AD
ldap_basedn = ou=people,dc=mydomain,dc=com

#Search filter for LDAP/AD, make sure the syntax of the filter is correct.
#ldap_filter = (objectClass=person)

# The attribute used in a search to match a user, it could be uid, cn, email, sAMAccountName or other attributes depending on your LDAP/AD
ldap_uid = uid

#the scope to search for users, 1-LDAP_SCOPE_BASE, 2-LDAP_SCOPE_ONELEVEL, 3-LDAP_SCOPE_SUBTREE
ldap_scope = 3

#Timeout (in seconds)  when connecting to an LDAP Server. The default value (and most reasonable) is 5 seconds.
ldap_timeout = 5
#Turn on or off the self-registration feature
self_registration = on

#The expiration time (in minute) of token created by token service, default is 30 minutes
token_expiration = 30

#The flag to control what users have permission to create projects
#The default value "everyone" allows everyone to creates a project.
#Set to "adminonly" so that only admin user can create project.
project_creation_restriction = everyone

#Determine whether the job service should verify the ssl cert when it connects to a remote registry.
#Set this flag to off when the remote registry uses a self-signed or untrusted certificate.
verify_remote_cert = off

#************************END INITIAL PROPERTIES************************
#############

**Comment by choman** [comment]
Apologies, self inflicted. closing

**Comment by akiherb** [comment]
Can you share more details about what was causing this please?

**Comment by fir3wall** [comment]
@choman Can you share your solution to this? Got same issue.

**Comment by entryword** [comment]
@choman Could you share how you solve this issue?

**Comment by Aaronshuai** [comment]
我也遇到了这样的情况。这个情况可能是我这边自己生产CA证书导致的harbor出的问题，我通过先将harbor的启动为http protocol ，容器确实能启动，后又改成https protocol 启动。发现离奇的好了（这期间可是 质疑过证书问题、质疑过Nginx配置文件等等尝试）。不知道我这种解决办法有没有帮助到各位。
问题详细内容如下：
Aug 27 11:41:01 172.21.0.1 proxy[21813]: nginx: [emerg] PEM_read_bio_X509_AUX("/etc/nginx/cert/harbor.***.com.crt") failed (SSL: error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:filename(libz.so): libz.so: cannot open shared object file: No such file or directory error:25070067:DSO support routines:DSO_load:could not load the shared library error:0906D06C:PEM routines:PEM_read_bio:no start line)

**Comment by mweigel** [comment]
Just ran into this when building a new Harbor server, and even though the error seems to indicate that a shared library is missing, this wasn't the case. The issue was with the certificates I was using. I haven't looked into it in depth yet but the PEM encoded certificates were slightly unusual as they were encoded on a single line. After generating a self signed certificate and key to test with using "openssl req -x509 -newkey rsa:4096 -keyout key.pem -nodes -out cert.pem -days 365" Nginx started without issue. File modes and permissions were kept the same throughout. I may take a closer look if I have time.
