### ISSUE TITLE
Document Harbor integration with VIC appliance

### ISSUE THREAD

**Issue by andrewtchin** [vmware/harbor#4303]
To document integration with the VIC appliance, please complete this template and make a PR to the vic-product repo to place it in the "integration" directory.
https://github.com/vmware/vic-product/blob/master/installer/docs/INTEGRATION.md

Here is an example I completed for vic-machine-server. https://github.com/vmware/vic-product/blob/master/installer/docs/integration/vic-machine-server.md

This is also a good opportunity to review the appliance design doc https://github.com/vmware/vic-product/blob/master/installer/docs/DESIGN.md

Please discuss with me during this process, especially if anything isn't clear or there are points that we need to come to an agreement on.

**Comment by andrewtchin** [comment]
This should include documentation on the CI build for both master and release branches. This includes standards for the `harbor-builds` and `harbor-releases` buckets.

**Comment by wy65701436** [comment]
PR has submitted, https://github.com/vmware/vic-product/pull/1719, it needs review @andrewtchin

**Comment by wy65701436** [comment]
close it as PR merged.
