### ISSUE TITLE
[Question] On notary

### ISSUE THREAD

**Issue by choman** [vmware/harbor#4305]
Currently running
- Harbo1.2 on RHEL 7.4
- docker 17.12
- docker-compose 1.19

The guide under docs does not mention anything, but is there after outside of vmware harbor that needs to be downloaded and installed?

Barring the above, is following the use_notary guide it?

**Comment by wy65701436** [comment]
Please refer to this: https://github.com/vmware/harbor/blob/master/docs/use_notary.md

**Comment by wy65701436** [comment]
@choman, I'll close this issue, please reopen it if any question on notary.
