### ISSUE TITLE
Support Harbor Tile upgrade

### ISSUE THREAD

**Issue by jessehu** [vmware/harbor#4311]
Refer to https://github.com/vmware/harbor-planning/issues/17
- [x] Harbor Tile should be able to upgrade from v1.4.x to v1.5.0 without data lost.
- [ ] Setup CI pipeline for testing upgrade (CI will be added later)

**Comment by reasonerjt** [comment]
Need final verification when there's a 1.5 rc.

**Comment by jessehu** [comment]
Fixed in https://storage.googleapis.com/harbor-ci-pipeline-store/tile-releases/harbor-container-registry-1.5.0-build.27.pivotal
