### ISSUE TITLE
Replication rule can not be saved.

### ISSUE THREAD

**Issue by doctormacky** [vmware/harbor#4321]
When create an replication rule for an project, after input all parameters in the dialog. the "save" button is disabled. 
when I switch an new endpoint with an old version(harbor 1.3), it can be saved.  then I delete the rule and recreate it. the "save" button's status is also "disabled".

If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
docker version: 17.12.0-ce, build c97c6d6
docker-compose version: 1.19.0, build 9e633ef
2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
[harbor-config.zip](https://github.com/vmware/harbor/files/1769661/harbor-config.zip)

3)Log files, you can get them by package the /var/log/harbor/ .
[harbor-log.zip](https://github.com/vmware/harbor/files/1769668/harbor-log.zip)

**Comment by ywk253100** [comment]
Clear the cache of your browser and try again. If the issue still exists, open the debug console of your browser and check whether some errors occur.

**Comment by doctormacky** [comment]
I have cleaned the cache again and again. but nothing happened, still the error. I am sorry that I destroyed the instance, will install another one to debug it.

**Comment by doctormacky** [comment]
![replication-error](https://user-images.githubusercontent.com/3380539/36893046-a2ac814a-1e41-11e8-8891-9c77f44bd711.jpeg)

**Comment by doctormacky** [comment]
It's very easy to reproduce this issue:
step 1: create an replication rule and do not save it(create an new endpoint during creating the rule)
step 2: create the replication rule again and you can meet this issue.

**Comment by ywk253100** [comment]
I cannot reproduce it in my env. Could you provide detailed steps to reproduce it? It's better if you can upload some screenshots.

**Comment by doctormacky** [comment]
Steps for reproduce the issues:
1, login harbor
2, navigate to projects.(click project on the navigation bar on the left)
3, click one project in the project list.(I use harbor default  project named library as an example)
4, click the replication tab.
5, click the "new replication rule" button, then will come to an wizard page.
6, input parameters. in the "Endpoint" field, click the new button. then create an new endpoint. 
7, click cancel button in the "new replication rule" wizard page. 
8, repeat 2 to 6, then you may find that you can not save the rule. 

Looking forward your reply. 

<img width="725" alt="image" src="https://user-images.githubusercontent.com/3380539/36954745-f7b5acf6-205e-11e8-9448-0e04dc6cd457.png">

**Comment by ywk253100** [comment]
What browser do you use?

**Comment by doctormacky** [comment]
firefox.

**Comment by ywk253100** [comment]
Duplicate of #4233. You can create the replication rule using the chrome browser for now.
Thank you for your detailed steps.

**Comment by doctormacky** [comment]
Guys, Yes, It's duplicate with the error you paste. and I tried to use chrome, It works. Thanks a lot. Let me close this issue first.
