### ISSUE TITLE
[Question]Project name too long (is it fixed ???)

### ISSUE THREAD

**Issue by parin921996** [vmware/harbor#4336]
I am seeing same issue when it try to use project name consist of more than 30 characters. I am using Harbor v1.4.0 .
![image](https://user-images.githubusercontent.com/8746551/36912414-9565c208-1e14-11e8-8930-85c3bb0d0c43.png)

Error I am seeing when I try following request
`curl 'https://HARBOR_ADRESS/api/projects' -u username:password -H 'Content-Type: application/json' -d '{"project_name":"abcdefghigklmnopqabcdefghigklmnopq","metadata":{"public":"true"}}'`
Response
`invalid request: Project name is illegal in length. (greater than 2 or less than 30)`

According to #3617 it says that it is fixed in v1.4.0 that's why i am creating issue.

**Comment by reasonerjt** [comment]
Fixed in #4395
