### ISSUE TITLE
how to avoid downloading data every time when building harbor image

### ISSUE THREAD

**Issue by rootdeep** [vmware/harbor#4347]
When I run  command "make build "  to build harbor images every time ,   the program will download some package every  time . such as :

Downloading:
bash                                    885988    100%
bzip2                                   525934    100%
curl                                    882242    100%
elfutils-libelf                         339766    100%
expat                                    91378    100%
filesystem                               16247    100%
glibc                                 19395489    100%
hawkey                                   51710    100%
libassuan                                47930    100%
libgcc                                   48996    100%
libgpg-error                            183636    100%
librepo                                 140724    100%
libsolv                                 397795    100%
libstdc++                               479164    100%

Is  there any way to cache thees packages and make the program to  avoid downloading the packages from Internet every time?

If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
3)Log files, you can get them by package the /var/log/harbor/ .

**Comment by rootdeep** [comment]
But I found that after I successfully build the adminserver image first time,  and **don't remove the image**. Then I compile  adminserver source code and build the  adminserver image again, the output of the build process as follow. it used the cached data in step 2.   So this may be a shortcut  for saving time when building  the images.

Sending build context to Docker daemon  443.2MB
Step 1/7 : FROM vmware/photon:1.0
 ---> 9b411d78ad9e
Step 2/7 : RUN tdnf erase vim -y     && tdnf distro-sync -y || echo     && tdnf install -y sudo     && tdnf clean all     && groupadd -r -g 10000 harbor && useradd --no-log-init -r -g 10000 -u 10000 harbor     && mkdir /harbor/
 ---> Using cache
 ---> d92004fe43ff
Step 3/7 : COPY ./make/dev/adminserver/harbor_adminserver ./make/photon/adminserver/start.sh /harbor/
 ---> 3edfa150a0b1
Removing intermediate container 2b7a724773e6
Step 4/7 : HEALTHCHECK CMD curl -s -o /dev/null -w "%{http_code}" 127.0.0.1:8080/api/configurations|grep 401
 ---> Running in 82be8d5b49c7
 ---> fd39378a1017
Removing intermediate container 82be8d5b49c7
Step 5/7 : RUN chmod u+x /harbor/harbor_adminserver /harbor/start.sh
 ---> Running in 0074118950b6
 ---> 3d6d5aa77398
Removing intermediate container 0074118950b6
Step 6/7 : WORKDIR /harbor/
 ---> 3edb7da82bfe
Removing intermediate container 542f8581fb09
Step 7/7 : ENTRYPOINT /harbor/start.sh
 ---> Running in 389b1cb1f940
 ---> 1c552ac90bf1
Removing intermediate container 389b1cb1f940
Successfully built 1c552ac90bf1
Successfully tagged vmware/harbor-adminserver:v1.4.0-dev3

**Comment by wy65701436** [comment]
Yes, if you don't remove the newly build-ed image, it helps to save time.

@rootdeep , is it still a problem for you? If not, let me close this issue.
