### ISSUE TITLE
combine upgrade scripts into one docker image for vic-appliance.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#4348]
For VIC 1.4 release, we should try to combine all necessary steps into one docker image, including the migration of data and configuration.

So for VIC appliance it will issue a `docker run` to handle upgrade/migration of Harbor.

We should try to avoid **DinD** though we need somehow call the code in migrator image to do the DB schema migration.

**Comment by wy65701436** [comment]
It has already been passed test on VIC and Tile, will remove the test tag later in RC.

**Comment by wy65701436** [comment]
Close it.
