### ISSUE TITLE
When testing an endpoint the dialog should not resize and move

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#4359]
@lweitzman commented on [Tue Mar 06 2018](https://github.com/vmware/harbor-planning/issues/37)

When testing an endpoint the dialog jumps because it changes sizes to show notification. It should remain consistent.

![Screen Shot 2018-03-06 at 10.32.11 AM.png](https://images.zenhubusercontent.com/56afa7c46caf56c9d38c1f12/49aa60c1-78e9-4116-a390-1322204d2279)

![Screen Shot 2018-03-06 at 10.32.18 AM.png](https://images.zenhubusercontent.com/56afa7c46caf56c9d38c1f12/a83d6814-0eb9-42ff-b8ff-5f48cd237631)

**Comment by lweitzman** [comment]
it still resizes when the warning is added to the dialog. but its better.
