### ISSUE TITLE
Filtering of Logs should search additional attributes

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#4360]
@lweitzman commented on [Tue Mar 06 2018](https://github.com/vmware/harbor-planning/issues/36)

Filtering the logs only searches on the repository name. It should also search the username, tags and operation.

**Comment by lweitzman** [comment]
the drop down menu includes a scroll bar and shouldn't (on a mac using chrome)
![screen shot 2018-05-18 at 3 07 51 pm](https://user-images.githubusercontent.com/626032/40253313-48d86974-5aad-11e8-8424-0a519278f1d4.png)
