### ISSUE TITLE
Confusing replication rule and jobs datagrid interaction

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#4361]
@lweitzman commented on [Tue Mar 06 2018](https://github.com/vmware/harbor-planning/issues/34)

When selecting a rule row, the jobs datagrid is shown. Then clicking on a checkbox the jobs datagrid is removed but the previous selected row is still selected. Unchecking the checkbox leaves the row selected but no jobs datagrid is displayed. When selecting a checkbox, remove the selected row.

**Comment by pengpengshui** [comment]
The checkbox had already changed to radiobutton. the confusion had gone.
