### ISSUE TITLE
In-page editing of new replication rule should be fixed

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#4362]
@lweitzman commented on [Tue Mar 06 2018](https://github.com/vmware/harbor-planning/issues/33)

The in-page editing should be replaced by a modal dialog. Other form modifications should be addressed. See https://vmware.invisionapp.com/share/B8FFF2MQ5XR#/screens/274835797_Administration_-_Project_-_Replication_Rule_Manual

![Screen Shot 2018-03-06 at 10.21.51 AM.png](https://images.zenhubusercontent.com/56afa7c46caf56c9d38c1f12/2698873f-a61a-4e76-82d8-fe13510ab9eb)

**Comment by steven-zou** [comment]
@lweitzman, I think @pengpengshui  has fixed this issue.

**Comment by pengpengshui** [comment]
The new replication rule had changed to dialog mode .
