### ISSUE TITLE
Inconsistent use of left navigation when creating a new replication rule

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#4363]
@lweitzman commented on [Tue Mar 06 2018](https://github.com/vmware/harbor-planning/issues/32)

When adding a new replication rule, the left navigation switches to "Replications" temporarily. After completing the creation of the rule, navigation returns to "Projects". Clicking on the back button it also returns to "Projects"

**Comment by pengpengshui** [comment]
The create  new replication rule had turned to modal mode. so I think the issue mentioned above had gone

**Comment by lweitzman** [comment]
waiting for an environment to review and verify this
