### ISSUE TITLE
Actions on members datagrid should be fixed

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#4365]
@lweitzman commented on [Tue Mar 06 2018](https://github.com/vmware/harbor-planning/issues/30)

Move "Delete" to the end of the actions and rename it "Remove"
Role drop down (3 dots) should be renamed to "Set Role" and disabled when no members are selected.
See: https://vmware.invisionapp.com/share/B8FFF2MQ5XR#/screens/273227819_Harbor_-_Project_-_Users 
![Screen Shot 2018-03-06 at 10.14.04 AM.png](https://images.zenhubusercontent.com/56afa7c46caf56c9d38c1f12/31358bd2-5a87-4393-af09-c6c4ff679036)

**Comment by lweitzman** [comment]
verified in https://10.160.51.81/harbor/projects/1/members
