### ISSUE TITLE
Modify action bar above datagrid removing tab bar and use separate buttons

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#4366]
@lweitzman commented on [Tue Mar 06 2018](https://github.com/vmware/harbor-planning/issues/24)

Modify the action bar above datagrids to use buttons. Use icons for add, edit, delete (remove). In terms of language, use "Delete" when deleting objects and "Remove" when removing a relationship (e.g., removing a user from a project). 
![Screen Shot 2018-03-06 at 9.54.34 AM.png](https://images.zenhubusercontent.com/56afa7c46caf56c9d38c1f12/549df920-3803-4744-8077-e19aaa5d5852)

**Comment by lweitzman** [comment]
mostly fixed but "Delete" should be renamed to "Remove"

**Comment by steven-zou** [comment]
@ninjadq Please change the text 'Delete' to 'Remove'
