### ISSUE TITLE
Re-implement notifications to the user

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#4367]
@lweitzman commented on [Tue Mar 06 2018](https://github.com/vmware/harbor-planning/issues/25)

The banner that indicates success or failure should not extend the complete width of the application and should not cover the content. See https://vmware.invisionapp.com/share/B8FFF2MQ5XR#/274028073_Harbor_-_Project_-_Users_-_Error

![Screen Shot 2018-03-06 at 9.56.24 AM.png](https://images.zenhubusercontent.com/56afa7c46caf56c9d38c1f12/68119f5b-052b-43de-8ec3-27b866c5cb2d)

**Comment by pengpengshui** [comment]
need code review #5108

**Comment by zhoumeina** [comment]
![error-message](https://user-images.githubusercontent.com/4946616/43059388-c36c62b2-8e7e-11e8-8503-dbf259935a06.png)
Is this ok?

**Comment by lweitzman** [comment]
could you provide the full screen in the screenshot. thks

**Comment by zhoumeina** [comment]
fix by #5389.
