### ISSUE TITLE
Datagrid item count is wrong

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#4369]
@lweitzman commented on [Tue Mar 06 2018](https://github.com/vmware/harbor-planning/issues/27)

For example, the item count shows 0 when there are items in the datagrid for Members in a project.
![Screen Shot 2018-03-06 at 10.05.34 AM.png](https://images.zenhubusercontent.com/56afa7c46caf56c9d38c1f12/32b0df1a-9f4f-430b-9366-8b233b227732)

**Comment by lweitzman** [comment]
Verified in https://10.160.51.81/harbor/projects/1/members
