### ISSUE TITLE
No tooltip to indicate the problem when creating a project

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#4370]
@lweitzman commented on [Tue Mar 06 2018](https://github.com/vmware/harbor-planning/issues/28)

When creating a project, the validation doesn't provide a tooltip to indicate why the project name is invalid.

![Screen Shot 2018-03-06 at 10.09.43 AM.png](https://images.zenhubusercontent.com/56afa7c46caf56c9d38c1f12/c7b65655-cb3a-4c1b-bd84-66e1d9a5d79d)

**Comment by lweitzman** [comment]
Verified https://10.160.51.81/harbor/projects
