### ISSUE TITLE
Don't use modal dialogs to indicate progress

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#4371]
@lweitzman commented on [Tue Mar 06 2018](https://github.com/vmware/harbor-planning/issues/29)

Don't use modal dialogs for indication of progress. This is also true when removing a user. This will lock the UI until the progress is complete. Use the datagrid to show progress or in the case of simple actions e.g. removal of a user, no progress is needed since its very fast. If there is an issue with the deletion, then provide a notification banner if there is an issue.

![Screen Shot 2018-03-06 at 10.11.57 AM.png](https://images.zenhubusercontent.com/56afa7c46caf56c9d38c1f12/2a37a6b0-7505-4a80-b825-7e2f552e871d)

**Comment by reasonerjt** [comment]
Please make sure the nightly passed before closing this issue!

**Comment by lweitzman** [comment]
when its complete, put it into "Verify" and add the "pending-ux-review" label 
don't close it.

**Comment by pengpengshui** [comment]
testcase verified

**Comment by lweitzman** [comment]
Deleting a project causes an issue in the Events slide out.
![screen shot 2018-05-30 at 8 19 48 am](https://user-images.githubusercontent.com/626032/40719708-5a8ed746-63e2-11e8-9467-0e9b32c74b9a.png)

**Comment by pengpengshui** [comment]
new issue #5049  for tracking the layout problem.
