### ISSUE TITLE
UI has no response after deleting an image

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#438]
1.There should be message whether the deletion was successful or not.
2.The remove icon shoud be removed when an image has no tags.
<img width="1070" alt="screen shot 2016-06-29 at 12 09 58 pm" src="https://cloud.githubusercontent.com/assets/2390463/16440236/736ef772-3df2-11e6-920f-112aa5b9a64e.png">

**Comment by wknet123** [comment]
fixed.

**Comment by reasonerjt** [comment]
Need to consider the case when api returns error.

**Comment by reasonerjt** [comment]
Also there has to be an icon or gif to indicate the action is in progress

**Comment by reasonerjt** [comment]
verified
