### ISSUE TITLE
Can you set permissions on individual repositories in a project? Or only at the project level.

### ISSUE THREAD

**Issue by RothAndrew** [vmware/harbor#4381]
Can you set different permissions on individual repositories in a project? Or only at the project level?

As far as I know, I can only set user permissions on the project level. Meaning:
* BobTheUser receives permissions to Project "foobar"
* BobTheUser may now run:
  * `docker pull myregistry.com/foobar/repo1`
  * `docker pull myregistry.com/foobar/repo2`

Is it possible for me to only allow BobTheUser to pull repo1 and not repo2?

**Comment by reasonerjt** [comment]
By the design, the permission is set at the project level.
