### ISSUE TITLE
Error trying to build Harbor from code - CreateProcess (checkenv.sh) failed. Error 193

### ISSUE THREAD

**Issue by RothAndrew** [vmware/harbor#4383]
Environment:
Windows 10 Enterprise

If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.

Docker:
Docker version 18.03.0-ce-rc1, build c160c73
Docker-Compose:
docker-compose version 1.19.0, build 9e633ef3

2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.

n/a

3)Log files, you can get them by package the /var/log/harbor/ .

```
PS C:\Users\rothandr\repos\mrp\harbor> make install GOBUILDIMAGE=golang:1.7.3 COMPILETAG=compile_golangimage CLARITYIMAGE=vmware/harbor-clarity-ui-builder:1.2.7
process_begin: CreateProcess(C:\Users\rothandr\repos\mrp\harbor\make\checkenv.sh, C:/Users/rothandr/repos/mrp/harbor/make/checkenv.sh, ...) failed.
make (e=193): Error 193
make: *** [check_environment] Error 193
```

**Comment by wy65701436** [comment]
we do not support build harbor on windows so far.
