### ISSUE TITLE
建议：新增docker-compose的链接配置

### ISSUE THREAD

**Issue by mds1455975151** [vmware/harbor#4409]
[root@node2 harbor]# ./install.sh -h

Note: Please set hostname and other necessary attributes in harbor.cfg first. DO NOT use localhost or 127.0.0.1 for hostname, because Harbor needs to be accessed by external clients.
Please set --with-notary if needs enable Notary in Harbor, and set ui_url_protocol/ssl_cert/ssl_cert_key in harbor.cfg bacause notary must run under https. 
Please set --with-clair if needs enable Clair in Harbor
[root@node2 harbor]# ./install.sh --with-clair
安装过程中选择--with-clair或者--with-notary以后会调用不同的docker-compose的yml文件，如果重启默认会调用docker-compose.yml文件，建议如下：
根据用户选择参数不同，以软链接的形式将选择的yaml与默认docker-compose配置文件名做关联
例如：
安装过程中使用 ./install.sh --with-clair参数则进行如下软链接，使用--with-notary参数类似
-rw-r--r--. 1 root root      1133 2月   6 13:18 docker-compose.clair.yml
-rw-r--r--. 1 root root      1725 2月   6 13:18 docker-compose.notary.yml
lrwxrwxrwx  1 root root        24 3月  14 12:03 docker-compose.yml -> docker-compose.clair.yml
-rw-r--r--. 1 root root      3314 2月   6 13:18 docker-compose.yml.bak
请评估。

**Comment by wy65701436** [comment]
Thanks for your suggestion, but we have already mentioned the exactly steps and matters needing attention in installation guide. 

It's not necessary to add this soft link in installation script. I'll close this issue as defer.

**Comment by mds1455975151** [comment]
ok
