### ISSUE TITLE
kubernetes deployment harbor 1.4.0 failed

### ISSUE THREAD

**Issue by shajc0504** [vmware/harbor#4411]
# docker version
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:15:20 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:17:54 2018
  OS/Arch:      linux/amd64
  Experimental: false

# kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

**When deply adminserver,there was an error as follow:**
2018-03-14T09:07:10Z [INFO] initializing system configurations...
2018-03-14T09:07:10Z [INFO] the path of json configuration storage: /etc/config/config.json
2018-03-14T09:07:10Z [INFO] initializing database: type-MySQL host-xxxx port-3306 user-harbork8s database-registry_k8s
2018-03-14T09:07:10Z [INFO] initialize database completed
2018-03-14T09:07:10Z [FATAL] [main.go:46]: failed to initialize the system: strconv.Atoi: parsing "": invalid syntax

**Comment by reasonerjt** [comment]
Have you tried the helm chart?

**Comment by shajc0504** [comment]
I have resolved this problem after update docker version to 17.12.1-ce on kubernetes master and work nodes.

**Comment by jessehu** [comment]
@shajc0504 You are encouraged to use the Harbor Helm Chart 1.4.0 beta https://github.com/vmware/harbor/tree/master/contrib/helm/harbor. It will be updated to support future harbor release.

**Comment by shajc0504** [comment]
@jessehu Thanks.I will have a try. 
I used harbor/ha/registry.sql to create the registry database. 
The function CfgStore.Read() in /harbor-release-1.4.0/src/adminserver/systemcfg/systemcfg.go read something from table registry.properties. 
After regenerating this table from harbor-db image, this problem have been resolved .

**Comment by svagner** [comment]
+1 similar issue

**Comment by a-kinder** [comment]
Similar issue. Was on v1.2.0, upgrade failed with same error. Can't find any empty string env variables that might be causing it

**Comment by svagner** [comment]
I've started with follow envs:
  LOG_LEVEL: debug
  AUTH_MODE: ldap_auth
  SELF_REGISTRATION: "off"
  LDAP_URL: ldaps://dc
  LDAP_SEARCH_DN:
  LDAP_SEARCH_PWD:
  LDAP_BASE_DN: "dc=domain,dc=net"
  LDAP_GROUP_SCOPE: "3"
  LDAP_FILTER: "(objectClass=User)"
  LDAP_UID: sAMAccountName
  LDAP_SCOPE: "3"
  LDAP_TIMEOUT: "5"
  DATABASE_TYPE: mysql
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  PORT: "8080"
  MYSQL_USR: root
  MYSQL_PWD: ""
  MYSQL_DATABASE: registry
  REGISTRY_URL: http://registry:5000
  TOKEN_SERVICE_URL: http://ui/service/token
  EMAIL_HOST: "relay"
  EMAIL_PORT: "25"
  EMAIL_USR: ""
  EMAIL_PWD: ""
  EMAIL_SSL: "false"
  EMAIL_FROM: "Docker Registry <docker_registry>"
  EMAIL_IDENTITY: ""
  HARBOR_ADMIN_PASSWORD: ""
  PROJECT_CREATION_RESTRICTION: everyone
  VERIFY_REMOTE_CERT: "on"
  MAX_JOB_WORKERS: "3"
  UI_SECRET: ""
  JOBSERVICE_SECRET: ""
  TOKEN_EXPIRATION: "30"
  CFG_EXPIRATION: "5"
  GODEBUG: "netdns=cgo"
  ADMIRAL_URL: NA
  WITH_NOTARY: "False"
  RESET: "true"
  EXT_ENDPOINT: "https://docker-registry"
  TOKEN_URL: http://ui
  JSON_CFG_STORE_PATH: "/etc/config/config.json"
  SECRET_KEY: ""
  CLAIR_DB_PORT: "5432"

Hope it will help

**Comment by a-kinder** [comment]
We were able to solve our issue, our config was being loaded into and read from the properties table of the db, and the clair port was empty. (https://github.com/vmware/harbor/blob/ae257433cc5bfd4f6617e2a2596025cc0ff5e7a5/src/adminserver/systemcfg/store/database/driver_db.go#L75) 

 once we entered in that value into the db, the error message went away.

**Comment by Goend** [comment]
![image](https://user-images.githubusercontent.com/40394339/97847709-ffa88c00-1d2a-11eb-9528-ee0082b9a6c7.png),it's wrong again.
![image](https://user-images.githubusercontent.com/40394339/97847849-354d7500-1d2b-11eb-8092-fb1d28d689f1.png)
