### ISSUE TITLE
Cannot see the output of processes (dockerd, docker-compose) started by "start-stop-daemon" in bosh deployment 

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#4416]
On bosh deployment the output of `docker-compose` and `dockerd` is eaten, they are not shown in ctl.stdout.log nor the redirection target set in `ctl` script, such as `dockerd.stdout.log`.

This is a problem for debugging.

**Comment by reasonerjt** [comment]
It seems that when `--background` is used with `start-stop-daemon` all output to stdout or stderr will be gone.
A workaround after quick search:
https://stackoverflow.com/questions/8251933/how-can-i-log-the-stdout-of-a-process-started-by-start-stop-daemon

**Comment by jessehu** [comment]
Fixed in https://git.eng.vmware.com/harbor/habo/merge_requests/28 and https://git.eng.vmware.com/harbor/habo/merge_requests/29
