### ISSUE TITLE
Vulnerability scanning summary information is wrong

### ISSUE THREAD

**Issue by qihanglys** [vmware/harbor#4421]
In the process of using version(harbor-offline-installer-v1.4.0)harbor, vulnerability scanning information on image details do not agree with statistics, is this a bug?

![1111](https://user-images.githubusercontent.com/30495353/37502813-f7edea6c-290f-11e8-8a1d-1c39f2c708d6.jpg)

**Comment by wy65701436** [comment]
@sigsbee  can you have a try?

@qihanglys  please help to upload Harbor log.

**Comment by wy65701436** [comment]
@qihanglys  the total count in the detail is not for the count of CVEs. 

It indicates the count of packages, in other word, there are 5 packages with high vulnerably.

**Comment by qihanglys** [comment]
@wy65701436 
But serious vulnerability details shown below has been more than 5, screenshot just show part, the actual quantity is more than a dozen

**Comment by qihanglys** [comment]
The same image, harbor and clair display respectively as follows
harbor info : 
![ttt](https://user-images.githubusercontent.com/30495353/37588144-5742b37e-2b9c-11e8-8fb6-7783f17913f8.jpg)
![qqq](https://user-images.githubusercontent.com/30495353/37588100-2f34ba30-2b9c-11e8-919c-6e8de529f1bd.jpg)

clair info:
![yyyy](https://user-images.githubusercontent.com/30495353/37588275-b56ca978-2b9c-11e8-893d-760ab68c16e0.jpg)

**Comment by wy65701436** [comment]
@qihanglys , do you mean that you have scanned a image both with Harbor and Clair, but got the different results?

**Comment by wy65701436** [comment]
For the vulnerabilities details, if one package has both high and medium vulnerabilities, it's identified as High. This will answer your question.
