### ISSUE TITLE
Add metadata on harbor after replication when backen registry is already up to date

### ISSUE THREAD

**Issue by aladjadj** [vmware/harbor#4429]
When two instances of harbor are replicated but the Docker registry has the same backend ( s3 ).
The replication response is "image already up to date"
But the harbor instance is not updated with metadata, so image or tag doesn't appear

**Comment by ywk253100** [comment]
The two Harbors are using a shared storage backend but they don't share the database, is it right? Why do you deploy the instances like that? What's your use case?

**Comment by aladjadj** [comment]
Hi, 
I working  to deploy harbor in my company.
Harbor work perfectly without HA , so I want deploy two master harbor in two data center ( or more ) with same shared backend ( s3 in my case )

I deploy same configuration to all instances ( ansible roles to codifying API configuration, i share soon the WIP to open source  ) .

The docker registry configuring with middleware proxy cache when action is pull .

And i want create DNS with failover.

So if the replication can duplicate the metadatas without images blob it's perfect.

Thank you for your comment.

**Comment by ywk253100** [comment]
You can refer to this guide to deploy HA Harbor https://github.com/vmware/harbor/blob/master/docs/high_availability_installation_guide.md. The instances should share the same database.
