### ISSUE TITLE
Clair template missing database variable

### ISSUE THREAD

**Issue by BruiserT** [vmware/harbor#4432]
I believe there's an issue with the clair template missing the dbname value.

The harbor.cfg file gives off the impression that you can change the database name for clair if you use an external database. However the database name change is never picked up as there's no template variable to update the postgresql URI string.

**1) Versions**
docker-engine version:  17.12.1-ce
docker-compose version:  1.19.0
harbor online install: 1.4.0

**2) Harbor.cfg changes:**
Everything is default but the following changes:

##########Clair DB configuration############

#Clair DB host address. Only change it when using an external DB.
**clair_db_host = harbor.test.com**

#The password of the Clair's postgres database. Only effective when Harbor is deployed with Clair.
#Please update it before deployment. Subsequent update will cause Clair's API server and Harbor unable to access Clair's database.
**clair_db_password = testing**

#Clair DB connect port
clair_db_port = 5432

#Clair DB username
**clair_db_username = harbor**

#Clair default database
**clair_db = clair**

**3) Log output:**

018-03-18 18:33:24.846331"}
Mar 18 18:33:31 172.18.0.1 clair[1260]: {"Event":"pgsql: could not open database: pq: database \"harbor\" does not exist","Level":"fatal","Location":"main.go:96","Time":"2018-03-18 18:33:31.585771"}
Mar 18 18:33:44 172.18.0.1 clair[1260]: {"Event":"pgsql: could not open database: pq: database \"harbor\" does not exist","Level":"fatal","Location":"main.go:96","Time":"2018-03-18 18:33:44.720366"}
Mar 18 18:34:10 172.18.0.1 clair[1260]: {"Event":"pgsql: could not open database: pq: database \"harbor\" does not exist","Level":"fatal","Location":"main.go:96","Time":"2018-03-18 18:34:10.648880"}
Mar 18 18:35:02 172.18.0.1 clair[1260]: {"Event":"pgsql: could not open database: pq: database \"harbor\" does not exist","Level":"fatal","Location":"main.go:96","Time":"2018-03-18 18:35:02.189687"}

**Steps to reproduce the problem:**

Clean online install:

1) Make the config changes that I did
2) Run ./prepare --with-clair
3) Check common/config/clair/config.yaml

postgresql source URI is incorrect it's missing /clair from the template generated URI:

source: postgresql://harbor:testing@harbor.test.com:5432?sslmode=disable

Should be:

source: postgresql://harbor:testing@harbor.test.com:5432/**clair**?sslmode=disable

**Note: Clair template in location: common/templates/clair/config.yaml**

source: postgresql://$username:$password@$host:$port?sslmode=disable

Should be something like ?:

source: postgresql://$username:$password@$host:$port/**$dbname**?sslmode=disable

**Comment by yixingjia** [comment]
https://github.com/vmware/harbor/pull/4624
