### ISSUE TITLE
Use random icon generating algorithm to generate icons for the images when harbor working in standalone mode 

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#4441]

**Comment by lweitzman** [comment]
I don't think we should be putting in random graphic images as icons for objects. as stated by another designer in the group:
"icons should be used to provide quick recognition when there is meaning associated. For example, an icon used to represent an object such as “VM” is useful when scanning a group of objects or universally recognized such as a logo. [In this example], it appears as if each icon holds no meaning on its own and is merely used as decoration; this adds to visual clutter and the space can be better utilized to display the full title.
