### ISSUE TITLE
Unable to garbage collect deleted images

### ISSUE THREAD

**Issue by SteveOss** [vmware/harbor#4467]
Am seeing this behaviour with both versions 1.3 and 1.4. Have pushed multiple different images
to the registry with the same name/tag (as part of a CI process)
Have then deleted image from UI and run garbage collector. However looks like
have multiple manifest entries for the image with associated blobs that are not garbage collected.
Effectively means registry keeps growing with old copies of images. Is there a way to clean them out?

docker version
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:10:06 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:08:35 2018
  OS/Arch:	linux/amd64
  Experimental:	false

 docker-compose version
docker-compose version 1.16.1, build 6d1ac21
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

**Comment by steven-zou** [comment]
@reasonerjt / @ywk253100, please help to take a look to confirm if we have problems in the described scenario.

**Comment by ywk253100** [comment]
Dup of #3344.
