### ISSUE TITLE
modify ui

### ISSUE THREAD

**Issue by fenghui2013** [vmware/harbor#4470]
If I want to modify ui, what should I do? 
I modify locally harbor/src/ui_ng/src/app/base/navigator/navigator.component.html and make install, but it does not work!
ui using ui_ng?
why?
I use harbor 1.2.2

**Comment by steven-zou** [comment]
@fenghui2013 

  Can we know which parts you need to change? All the UI code is in the ui_ng folder. And some of the UI components are built into lib folder as sharable components which are imported into harbor by npm package.

**Comment by fenghui2013** [comment]
thank you for your answer. I knew how to build.
The target "compile_clarity" in Makefile failed when running "make install".
