### ISSUE TITLE
[Helm Chart's Error]: Unable to deploy Harbor on K8s using Helm chart

### ISSUE THREAD

**Issue by vielktus** [vmware/harbor#4484]
After execute this command:
<code>helm install . --debug --name harbor --set externalDomain=my.domain.local,insecureRegistry=true</code>

I got this error message:

<code>Error: error validating "": error validating data: found invalid field component for v1.PodTemplateSpec</code>

Is our helm chart working fine ? In the mean time, is there any other ways that I can use to deploy harbor on K8s ?

**Comment by jessehu** [comment]
What's the version of your kubectl, helm, and k8s cluster ?
There is a k8s guide https://github.com/vmware/harbor/blob/master/docs/kubernetes_deployment.md working with Harbor 1.2.0. But we recommend using the harbor  chart now.

**Comment by jessehu** [comment]
Does the secure mode command (without insecureRegistry=true) work for you ? "helm install . --debug --name harbor --set externalDomain=my.domain.local"

**Comment by vielktus** [comment]
I figured out. I'm not using the canary image in `helm init` command. After using this, I can install it without any problems. Btw, do I MUST use canary-image ?

**Comment by jessehu** [comment]
Thanks @vielktus. I will check your issue of using 'helm init'.

**Comment by jessehu** [comment]
I don't have issue using 'helm init'.

$ helm init
$HELM_HOME has been configured at /Users/huh/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.
Happy Helming!

huh-m01:vmware-harbor huh$ helm version
Client: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
