### ISSUE TITLE
How to contribute to harbor source code , is it has a gerrit or directly push  ?

### ISSUE THREAD

**Issue by rootdeep** [vmware/harbor#4493]
How to contribute to harbor source code , dose it has a review site likes gerrit or directly push  ?

1)Version of docker engine and docker-compose.
2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
3)Log files, you can get them by package the /var/log/harbor/ .

**Comment by ninjadq** [comment]
Hi @rootdeep, you are welcome to contribute to harbor.
we follow the git workflow.  Fork our repo then create a new branch on your forked repo. Coding on your own branch. Finally, send a pull request to harbor's repo. We will review your work. thanks & regards

**Comment by rootdeep** [comment]
I created my own branch named "adminserver-configmap" and push the code with follow commad

$ git push  origin  adminserver-configmap

The output is  :
Username for 'https://github.com': zhiguo.lee@foxmail.com
**remote: Permission to vmware/harbor.git denied to rootdeep.**
fatal: unable to access 'https://github.com/vmware/harbor.git/': The requested URL returned error: 403

It says I don't have right to access https://github.com/vmware/harbor.git/.

**Comment by ninjadq** [comment]
@rootdeep you need fork harbor to your own repo, I find that you already forked. you need push your branch to you own repo.
Maybe you can try this
`git remote add rootdeep https://github.com/rootdeep/harbor`
then 
`git push rootdeep adminserver-configmap`
finally you can send a pull request to harbor

**Comment by ninjadq** [comment]
@rootdeep we create a doc, you can refer [this](https://github.com/vmware/harbor/blob/master/CONTRIBUTING.md) to contribute. thanks
