### ISSUE TITLE
Can not dock login to Harbor deployed via Harbor Helm Chart

### ISSUE THREAD

**Issue by vielktus** [vmware/harbor#4499]
I executed `docker login harbor.my.domain`

The error is: 
```
Error response from daemon: Get https://harbor.my.domain/v2/: error parsing HTTP 404 response body: invalid character 'd' looking for beginning of value: "default backend - 404"
```

The log I found in harbor-registry pod:
```
time="2018-03-27T06:59:19.476252948Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.3 http.request.host=harbor.my.domain http.request.id=33727901-96e6-4c31-b588-29121dcce0cf http.request.method=GET http.request.remoteaddr=10.100.7.180 http.request.uri="/v2/" http.request.useragent="docker/17.12.0-ce go/go1.9.2 git-commit/c97c6d6 kernel/4.9.60-linuxkit-aufs os/linux arch/amd64 UpstreamClient(Docker-Client/17.12.0-ce \\(darwin\\))" instance.id=fa13cead-e633-4558-8d5e-ac8001c3a444 service=registry version=v2.6.2
100.65.198.193 - - [27/Mar/2018:06:59:19 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/17.12.0-ce go/go1.9.2 git-commit/c97c6d6 kernel/4.9.60-linuxkit-aufs os/linux arch/amd64 UpstreamClient(Docker-Client/17.12.0-ce \\(darwin\\))"
```
Output when try to curl this URL:
```
curl -L https://harbor.my.domain/v2                                                                                             
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
```

I deployed harbor on my Minikube as an Insecure Registry and already added "harbor.my.domain" to my docker config (Im using Docker version 17.12.0-ce, build c97c6d6 on Mac) as in the document. The ingress is set as well as `/etc/hosts` file

Same results if I do `docker push [blah][blah]` (skipped login)

**Comment by jessehu** [comment]
@vielktus Does secure registry mode work in your env ? And could you try docker login on a linux machine ? The insecury registry config is different on Mac and Linux.

**Comment by vielktus** [comment]
Secure Registry works for me. So ... Insecure Registry got some problems ?

**Comment by jessehu** [comment]
Thanks. Need to check it. BTW the secure mode is recommended.

**Comment by zhoulouzi** [comment]
i change the log level to debug ,the i got 
```
2018-04-02T13:02:01Z [DEBUG] [security.go:153]: got user information via basic auth
2018-04-02T13:02:01Z [DEBUG] [user.go:304]: Check if user admin is super user
2018-04-02T13:02:01Z [DEBUG] [authenticator.go:96]: Current AUTH_MODE is db_auth
2018-04-02T13:02:01Z [DEBUG] [authenticator.go:109]: Login failed, locking admin, and sleep for 1.5s
2018-04-02T13:02:02Z [DEBUG] [security.go:211]: basic auth user is nil
2018-04-02T13:02:02Z [DEBUG] [security.go:286]: user information is nil
2018-04-02T13:02:02Z [DEBUG] [security.go:300]: using local database project manager
2018-04-02T13:02:02Z [DEBUG] [security.go:302]: creating local database security context...
2018-04-02T13:02:02Z [DEBUG] [token.go:35]: URL for token request: /service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry
2018-04-02T13:02:02Z [DEBUG] [creator.go:200]: scopes: []
```

the scopes is [] 



refers to [](https://docs.docker.com/registry/spec/auth/token/#requesting-a-token) it's unauthorized so what the wrong

**Comment by reasonerjt** [comment]
@vielktus 

The root cause, seems is that the ingress on k8s will return a 404 while we don't host registry with `https`, and docker daemon can not handle the `404` error correctly.

We currently are considering remove the `InsecureRegistry` option in the helm chart.
Could you let us know what's your intention to set it?

**Comment by vielktus** [comment]
It's ok for me. I'm just doing some experiments and lazy to openssl gen. Luckily this helm chart did it for me. Awesome! This can be closed now.

**Comment by zhoulouzi** [comment]
@reasonerjt  yes, the ingress default backend return a 404 when the registry host not enabel with https  
refer to the document test an insecure registry，

With insecure registries enabled, Docker goes through the following steps:
First, try using HTTPS.
If HTTPS is available but the certificate is invalid, ignore the error about the certificate.
If HTTPS is not available, fall back to HTTP.

**Comment by yujiaao** [comment]
Use **https** instead **http** fix the error
