### ISSUE TITLE
Harbor 1.4.0 support redis cluster?

### ISSUE THREAD

**Issue by hmails** [vmware/harbor#4500]
When I configured HA with harbor 1.4.0, I used redis cluster and the UI was not normal.
harbor.cfg   
redis_url = redis_ip:6379,100,redis_password,0

Harbor 1.4.0 support redis cluster?

**Comment by yixingjia** [comment]
It support  Redis cluster. But due to limitation of Beego you can only specify one Node address in the redis_url. So one work around is that add a LB in front of the Redis cluster.

Can you please describe what issues you have encountered?

**Comment by hmails** [comment]
Thanks for your reply. When I configured HA, it was not normal to share the session with the redis cluster. Now it is normal to share sessions with redis.
