### ISSUE TITLE
spinner does not disappear after data is shown

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#4509]
spinner does not disappear after data is shown

![capture](https://user-images.githubusercontent.com/23101283/38010407-779f786e-328b-11e8-9894-940103933ed0.PNG)

**Comment by wy65701436** [comment]
It should be high priority as if i navigate to another page, it appends the page.

**Comment by wy65701436** [comment]
Harbor version: Version v1.5.0-cbcca015

**Comment by wy65701436** [comment]
![image](https://user-images.githubusercontent.com/2841473/38010560-7903a1e4-320e-11e8-8980-f49c9e7e6f83.png)
