### ISSUE TITLE
How to set Simple Authentication LDAP？

### ISSUE THREAD

**Issue by gzvince** [vmware/harbor#451]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

2)Config files of harbor, you can get them by packaging "Deploy/config" directory
## Configuration file of Harbor

#The IP address or hostname to access admin UI and registry service.
#DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
hostname = r.bd.com

#The protocol for accessing the UI and token/notification service, by default it is http.
#It can be set to https if ssl is enabled on nginx.
ui_url_protocol = http

#Email account settings for sending out password resetting emails.
email_server = mail.a.com.cn
email_server_port = 25
email_username = a@a.com.cn
email_password = aaa
email_from = admin <a@a.com.cn>

##The password of Harbor admin, change this before any production use.
harbor_admin_password= admin

##By default the auth mode is db_auth, i.e. the credentials are stored in a local database.
#Set it to ldap_auth if you want to verify a user's credentials against an LDAP server.
auth_mode = ldap_auth

#The url for an ldap endpoint.
ldap_url = ldap://10.16.26.198:389

#The basedn template to look up a user in LDAP and verify the user's password.
ldap_basedn = uid=%s,ou=People,o=a.com.cn,o=isp

#The password for the root user of mysql db, change this before any production use.
db_password = admin

#Turn on or off the self-registration feature
self_registration = on
#####

3)Log files, you can get them by package the /var/log/harbor/ 
Jun 30 11:34:25 172.18.0.1 docker/ui[9771]: 2016-06-30T03:34:25Z [DEBUG] [authenticator.go:52]: Current AUTH_MODE is ldap_auth
Jun 30 11:34:25 172.18.0.1 docker/ui[9771]: 2016-06-30T03:34:25Z [DEBUG] [ldap.go:47]: ldapURL:ldap://10.16.26.198:389
Jun 30 11:34:25 172.18.0.1 docker/ui[9771]: 2016-06-30T03:34:25Z [DEBUG] [ldap.go:69]: baseDn:uid=vince,ou=People,o=a.com.cn,o=isp
Jun 30 11:34:25 172.18.0.1 docker/ui[9771]: 2016-06-30T03:34:25Z [WARNING] Found more than one entry.

##################################

As usual, my company LDAP server need to config the LDAP admin login information. Such as admin account & password. After that configure, user can login through LDAP server. How can I set admin account & password in Harbor config?

**Comment by reasonerjt** [comment]
@gzvince as the log implies:

It found more than one entry with the dn: uid=vince,ou=People,o=a.com.cn,o=isp 

Normally, there should be only one entry mapped to a givne dn, you need to figure out how to bind the single entry with **ldapsearch** and config the template for that dn in your harbor.cfg.

**Comment by reasonerjt** [comment]
You can see some details in #254

**Comment by gzvince** [comment]
More than one entry means more than one result with that dn?

But I think the point is harbor has no rights to read the LDAP. Because of harbor didn't set the admin account & password.

**Comment by gzvince** [comment]
Thanks for your reply. @reasonerjt 

Can I add the Simple Authentication in the LDAP config?

**Comment by reasonerjt** [comment]
Honestly I don't quite understand your environment, do you need to bind twice using ldap to get the user entry?

You can fork the repo and try to fix it in the code, submit a PR if you think you have a good fix!

**Comment by gzvince** [comment]
In my company LDAP environment is no encryption(NO SSL) and need Simple Authentication(Need Bind user and Bind pw).

**Comment by wemeya** [comment]
@gzvince 
You mean this: when you access the LDAP server, you need a user and password?  Like below:
![image](https://cloud.githubusercontent.com/assets/12540577/16511117/505ff810-3f7f-11e6-9604-eaf31d54dbe3.png)

I suggest that you use JXplorer to login you LDAP server, and then search someone like below: 

![image](https://cloud.githubusercontent.com/assets/12540577/16511142/bd003c50-3f7f-11e6-9b53-608013cdb24c.png)

Then you configure harbor.cfg like demonstrated in the JXplorer, just change CN=%s or uid=%s, 
I see other configuration are no problem. 
When login to Harbor, you just need to input the CN or the uid, and his password in the LDAP server.  You can retry.

**Comment by gzvince** [comment]
@wemeya Yes, my company LDAP also need the username & password. Similar like the Jxplorer, I use Apache Directory Studio.
![image](https://cloud.githubusercontent.com/assets/1761912/16539543/155ad956-4079-11e6-8153-514ee35a88d7.png)
![image](https://cloud.githubusercontent.com/assets/1761912/16539564/bbc098da-4079-11e6-9ce1-f126440bba8d.png)

You mean is: I don't need to fill the LDAP login user & password in harbor.cfg?

**Comment by wemeya** [comment]
@gzvince 
Yes，you needn't configure the login information in the harbor.cfg. 
You just type them when you login the Harbor.
