### ISSUE TITLE
Super Shady OVA Download Email

### ISSUE THREAD

**Issue by jnovack** [vmware/harbor#4552]
After filling out the OVA Download Form, I received the following:

![image](https://user-images.githubusercontent.com/387006/38139017-a298112c-33fb-11e8-8098-af2660d0bba5.png)

From: "registryharbor@gmail.com"
Subject: "Harbor Download Addres" (yes, without the last 's')

This is SUPER SHADY.  Can a Contributor or someone from VMware confirm this is a legimate From/Subject for the OVA Download?

**Comment by jnovack** [comment]
Much like #4553, the root cause for concern is a lack of hash posted for the OVA.

**Comment by yixingjia** [comment]
@jnovack  Thanks for reaching, this is the email for download Harbor OVA build.

**Comment by yixingjia** [comment]
The email address subject has been fixed. Close this issue.
