### ISSUE TITLE
"Untrusted Certificate" Publisher on OVA

### ISSUE THREAD

**Issue by jnovack** [vmware/harbor#4553]
Just downloaded the OVA last night from the link. The publisher for the OVA is self-signed cert by `test`.

![image](https://user-images.githubusercontent.com/387006/38138874-f78450e8-33fa-11e8-9d9a-6e258cd93c7a.png)

Seems sloppy from VMware.

Can a Contributor or someone from VMware confirm the OVA hashes?  Can hashes for the images and downloads be posted in the repo?

```
$ md5 harbor-v1.4.0.ova
MD5 (harbor-v1.4.0.ova) = 84bedf146786f995b10760108163a55b
$ shasum harbor-v1.4.0.ova
1a9ef41b89aefe1f767d09f4ae7a183879c5c11e  harbor-v1.4.0.ova
```

**Comment by stonezdj** [comment]
Will provide the md5sum and sha1sum in email

**Comment by jnovack** [comment]
Thank you sir, but I disagree.  #4552 is my other major concern. A bad actor or middle-man would tell you that his download is secure and safe.  The problem is I'm getting a randomly misspelled email from `registryharbor@gmail.com`.

I feel the OVA Hash should be in the docs on github somewhere or on a `.vmware.com` domain somewhere.

**Comment by yixingjia** [comment]
@stonezdj  Please update the download page to include the MD5 thumbprint of the ova.

**Comment by stonezdj** [comment]
Add md5 and sha  to harbor official release page: https://github.com/vmware/harbor/releases
