### ISSUE TITLE
harbor replication can work without web?

### ISSUE THREAD

**Issue by inetkiller** [vmware/harbor#4559]
my harbor replication destination is in different datacenter, so i need expose replication destination to Internet, problem is here, expose web service need to be registered in my company, the process of  registry  is very long, so i don't want to do the registry. that means the web ui should not turn on. there are any way that don't use web ui but can do the replication operation?

**Comment by jessehu** [comment]
@inetkiller What does this mean ? "that means the web ui should not turn on. there are any way that don't use web ui but can do the replication operation?"  The source harbor must be able to connect to the target harbor to do replication.

**Comment by inetkiller** [comment]
@jessehu 我看你在北京，就直接中文吧。我的意思是镜像复制这个功能可以在关闭web ui的情况下进行吗。因为我需要将目标Harbor暴露到外网，如果有web ui的话就要备案（公司硬性规定。。。），所以我想把web ui关闭。从我目前接触到的资料来看，harbor的core components包括的ui,token,webhook服务，貌似都集成到ui这个docker image中了，镜像里面就一个二进制文件，也就是说core components是集成在一个二进制中，无法单独关闭其中某个core components？

**Comment by jessehu** [comment]
Thanks @inetkiller. 你的意思是 你们公司不允许开放Web界面访问，但是可以开放API访问(jobservice是暴露的API)? 现在确实不能单独关闭web ui, 不然replication就不能工作了。

**Comment by inetkiller** [comment]
@jessehu 嗯，看来这条路行不通，只能想其它办法了。谢谢你的回答。
