### ISSUE TITLE
Vulnerability hint does not show when data is not ready

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#4564]
There should be a hint when vulnerability data is not ready

![capture](https://user-images.githubusercontent.com/23101283/38189681-ce50a488-3693-11e8-8b2e-ae9ebcbea83a.PNG)

**Comment by wy65701436** [comment]
@sigsbee , can you input the harbor version?

**Comment by ninjadq** [comment]
This is a ui bug in gridview, I'll fix it
