### ISSUE TITLE
push images has same tag multi  .when I delete gc , Space is not released

### ISSUE THREAD

**Issue by xjr100419** [vmware/harbor#4566]
Problem description
push images has same tag multi .when I delete gc , Space is not released

in my Dashboard
images had delete and run
docker run -it --name gc --rm --volumes-from registry vmware/registry:2.6.2-photon garbage-collect /etc/registry/config.yml

![tim 20180402171514](https://user-images.githubusercontent.com/8691355/38191191-4aa09204-369a-11e8-8fa7-7b84560f6a9b.png)

but in the container
![tim 20180402171545](https://user-images.githubusercontent.com/8691355/38191200-557ebe9e-369a-11e8-83e1-65c94aeb9f5b.png)

the project is not delete all

**Comment by jessehu** [comment]
@xjr100419 could you describe the steps to reproduce your issue more clearly? And it's OK to use Chinese if you like.

**Comment by reasonerjt** [comment]
@xjr100419 in the screenshot you are using the parm `--dry-run` , which only marks the blobs not removing it.

**Comment by xjr100419** [comment]
@jessehu 
是这样的 我每次构建玩镜像 推送到私库的时候 tag 都是一样的：
docker push 192.168.80.180:5000/******/gps-service:5.0.0
就是每次更新都覆盖同一个标签。

但这样好像有个问题。。当我删除镜像对应的标签 并且执行 Gc 后。registry 的空间没有完全释放出来。还占着好多空间 导致硬盘都占满了

**Comment by xjr100419** [comment]
@reasonerjt 
I had run like this 
docker run -it --name gc --rm --volumes-from registry vmware/registry:2.6.2-photon garbage-collect  /etc/registry/config.yml
![tim 20180403090245](https://user-images.githubusercontent.com/8691355/38223581-325a960c-371e-11e8-81ad-9432bd3b8954.png)

**Comment by xjr100419** [comment]
https://gbougeard.github.io/blog.english/2017/05/20/How-to-clean-a-docker-registry-v2.html
找了 相关的描述 

f you update 10 times your Pull Request, there will be 10 references for the tag myPullRequest in the DR. Only one will be fetchable by the tag 

但还不知道怎么删除呢。。

**Comment by ywk253100** [comment]
It's a known issue #3344, you can try the workaround mentioned in the issue.

**Comment by xjr100419** [comment]
ok ths

**Comment by jessehu** [comment]
Thanks! Mark as duplicated of #3344.
