### ISSUE TITLE
After adding a replication rule, the confirmation of successful rule creation can not be removed

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#4579]
After adding a replication rule the green confirmation at the top of the page can not be removed. after refreshing the screen, the spinner progress indicator is never removed. their might have been an error in the rule, but the UI shouldn't have this behavior. here are the 2 screen shots.

![Screen Shot 2018-04-03 at 10.48.58 AM.png](https://images.zenhubusercontent.com/56afa7c46caf56c9d38c1f12/dde85e2c-592c-444e-ac8e-ab8899cfa306)

![Screen Shot 2018-04-03 at 10.53.19 AM.png](https://images.zenhubusercontent.com/56afa7c46caf56c9d38c1f12/3223eb24-1513-4e2c-8004-78294b31ca98)

**Comment by reasonerjt** [comment]
@lweitzman did you have a chance to verify?
