### ISSUE TITLE
HA Installation Guide has wrong link to registry.sql

### ISSUE THREAD

**Issue by ArcticSnowman** [vmware/harbor#4588]
Doc https://github.com/vmware/harbor/blob/master/docs/high_availability_installation_guide.md

has 

https://github.com/vmware/harbor/blob/release-1.4.0/make/common/db/registry.sql

but should be

https://github.com/vmware/harbor/blob/release-1.4.0/make/photon/db/registry.sql

**Comment by jessehu** [comment]
Thanks @ArcticSnowman. Will fix it.
