### ISSUE TITLE
No Dockercompose file found when execute install.sh

### ISSUE THREAD

**Issue by vielktus** [vmware/harbor#4601]
I'm following this guide `docs/installation_guide.md`. After finished configuring `harbor.cfg` in `make/harbor.cfg`, I executed `install.sh` and ran into this problem:
```
ERROR: .IOError: [Errno 2] No such file or directory: u'./docker-compose.yml'
[Step 3]: starting Harbor ...
ERROR: .IOError: [Errno 2] No such file or directory: u'./docker-compose.yml'
```
I checked and figured out that there were no dockercompose YML files, they were TPL files instead. I tried to create ones like `cp docker-compose.tpl docker-compose.yml`. That error was gone, then. However, it said something like docker image value `__version__` in yml is not found. Seems I have to do some preprations like setting the version. But I can't find this section in the guide.

git blame docker-compose.yml output:
```
44cd3ec85 make/docker-compose.tpl   (Tan Jiang    2017-03-22 20:56:08 +0800   4)     image: vmware/harbor-log:__version__
311cf8da0 make/docker-compose.yml   (yhua         2016-10-19 14:32:00 +0800   5)     container_name: harbor-log
```
Did I miss anything ?

**Comment by reasonerjt** [comment]
Did you download the offline installer? the guide is for the installer.

**Comment by vielktus** [comment]
Sorry my bad. This can be closed now.
