### ISSUE TITLE
Can I access the docker registry API? How about the authentication?

### ISSUE THREAD

**Issue by linkmancheng** [vmware/harbor#461]
Is there any facility to help me access the docker registry API with existing account? Thanks.

**Comment by reasonerjt** [comment]
Could you please elaborate your question?

**Comment by linkmancheng** [comment]
I want to use the manifest API of Harbor to get the docker image detail information, but I found the information is not enough. The docker registry manifest API can provide more information such as history field. Can Harbor return that information? If not, can I access the docker registry directly to get that information and can harbor help me to generate the Bearer token for me? I found the API of service/token but not sure it can provide that token.  Thank you.

**Comment by reasonerjt** [comment]
@ywk253100 I think we can update the API to contain more info.

**Comment by linkmancheng** [comment]
Great. Is there any temporary solution for that?

**Comment by reasonerjt** [comment]
You can write script to get token according to this doc:
https://github.com/docker/distribution/blob/master/docs/spec/auth/token.md

This is indeed how docker client works.

**Comment by linkmancheng** [comment]
Thanks @reasonerjt After check the code, I found harbor convert the docker registry manifest return result to RepoItem object and filter some information. It will be great if harbor return all the result directly.

**Comment by ywk253100** [comment]
OK, I will update it.

**Comment by ywk253100** [comment]
The manifest in branch new-ui-with-sync-image contains more informations, and it will be merged into master soon.

**Comment by reasonerjt** [comment]
@ywk253100 does UI display the new informations?

**Comment by ywk253100** [comment]
The new manifest API which will return complete manifests has been merged into branch dev by #622 .
