### ISSUE TITLE
Fix the scanned vulnerabilities of job service

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#4612]
{
"issues": [
{
"severity": "HIGH",
"confidence": "LOW",
"details": "Potential hardcoded credentials",
"file": "/home/yan/Workspace/src/github.com/vmware/harbor/src/common/const.go",
"code": "UAAClientSecret             = \"uaa_client_secret\"",
"line": 93
},
{
"severity": "HIGH",
"confidence": "LOW",
"details": "Potential hardcoded credentials",
"file": "/home/yan/Workspace/src/github.com/vmware/harbor/src/common/security/admiral/authcontext/authcontext.go",
"code": "AuthTokenHeader  = \"x-xenon-auth-token\"",
"line": 35
},
{
"severity": "HIGH",
"confidence": "LOW",
"details": "TLS InsecureSkipVerify may be true.",
"file": "/home/yan/Workspace/src/github.com/vmware/harbor/src/common/utils/ldap/ldap.go",
"code": "InsecureSkipVerify: !session.ldapConfig.LdapVerifyCert",
"line": 242
},
{
"severity": "HIGH",
"confidence": "HIGH",
"details": "TLS InsecureSkipVerify set true.",
"file": "/home/yan/Workspace/src/github.com/vmware/harbor/src/common/utils/registry/registry.go",
"code": "InsecureSkipVerify: true",
"line": 48
},
{
"severity": "LOW",
"confidence": "HIGH",
"details": "Errors unhandled.",
"file": "/home/yan/Workspace/src/github.com/vmware/harbor/src/common/utils/test/test.go",
"code": "io.Copy(w, bytes.NewReader(resp.Body))",
"line": 75
},
{
"severity": "HIGH",
"confidence": "LOW",
"details": "Potential hardcoded credentials",
"file": "/home/yan/Workspace/src/github.com/vmware/harbor/src/common/utils/uaa/client.go",
"code": "TokenURLSuffix = \"/oauth/token\"",
"line": 35
},
{
"severity": "HIGH",
"confidence": "LOW",
"details": "TLS InsecureSkipVerify may be true.",
"file": "/home/yan/Workspace/src/github.com/vmware/harbor/src/common/utils/uaa/client.go",
"code": "InsecureSkipVerify: cfg.SkipTLSVerify",
"line": 184
},
{
"severity": "HIGH",
"confidence": "LOW",
"details": "Potential hardcoded credentials",
"file": "/home/yan/Workspace/src/github.com/vmware/harbor/src/jobservice/config/config.go",
"code": "jobServiceAuthSecret          = \"JOBSERVICE_SECRET\"",
"line": 32
},
{
"severity": "MEDIUM",
"confidence": "HIGH",
"details": "Expect file permissions to be 0600 or less",
"file": "/home/yan/Workspace/src/github.com/vmware/harbor/src/jobservice/job/impl/logger/job_logger.go",
"code": "os.OpenFile(logPath, os.O_CREATE|os.O_WRONLY, 0644)",
"line": 20
},
{
"severity": "LOW",
"confidence": "HIGH",
"details": "Errors unhandled.",
"file": "/home/yan/Workspace/src/github.com/vmware/harbor/src/jobservice/job/impl/logger/job_logger.go",
"code": "jl.streamRef.Close()",
"line": 37
},
{
"severity": "HIGH",
"confidence": "HIGH",
"details": "TLS InsecureSkipVerify set true.",
"file": "/home/yan/Workspace/src/github.com/vmware/harbor/src/jobservice/opm/hook_client.go",
"code": "InsecureSkipVerify: true",
"line": 42
},
{
"severity": "HIGH",
"confidence": "LOW",
"details": "Potential hardcoded credentials",
"file": "/home/yan/Workspace/src/github.com/vmware/harbor/src/ui/config/config.go",
"code": "defaultTokenFilePath string = \"/etc/ui/token/tokens.properties\"",
"line": 42
},
{
"severity": "LOW",
"confidence": "HIGH",
"details": "Errors unhandled.",
"file": "/home/yan/Workspace/src/github.com/vmware/harbor/src/ui/filter/readonly.go",
"code": "resp.Write([]byte(\"The system is in read only mode. Any modification is not prohibited.\"))",
"line": 45
},
{
"severity": "HIGH",
"confidence": "HIGH",
"details": "Subprocess launching with variable.",
"file": "/home/yan/Workspace/src/github.com/vmware/harbor/tests/apitests/api-testing/client/docker_client.go",
"code": "exec.Command(cmdName, args...)",
"line": 71
},
{
"severity": "HIGH",
"confidence": "HIGH",
"details": "Subprocess launching with variable.",
"file": "/home/yan/Workspace/src/github.com/vmware/harbor/tests/apitests/api-testing/client/docker_client.go",
"code": "exec.Command(cmdName, args...)",
"line": 75
},
{
"severity": "LOW",
"confidence": "HIGH",
"details": "Errors unhandled.",
"file": "/home/yan/Workspace/src/github.com/vmware/harbor/tests/apitests/api-testing/client/harbor_api_client.go",
"code": "resp.Body.Close()",
"line": 103
}
],
"metrics": {
"files": 330,
"lines": 36224,
"nosec": 0,
"found": 16
}
}

**Comment by reasonerjt** [comment]
@wy65701436  please also fix the issue introduce in the readonly filter.

**Comment by wy65701436** [comment]
my part is done by PR https://github.com/vmware/harbor/pull/4627, remove from assignee.

**Comment by steven-zou** [comment]
**## None-fix parts:**
{
"severity": "HIGH",
"confidence": "LOW",
"details": "Potential hardcoded credentials",
"file": "/home/yan/Workspace/src/github.com/vmware/harbor/src/jobservice/config/config.go",
"code": "jobServiceAuthSecret = "JOBSERVICE_SECRET"",
"line": 32
},

{
"severity": "MEDIUM",
"confidence": "HIGH",
"details": "Expect file permissions to be 0600 or less",
"file": "/home/yan/Workspace/src/github.com/vmware/harbor/src/jobservice/job/impl/logger/job_logger.go",
"code": "os.OpenFile(logPath, os.O_CREATE|os.O_WRONLY, 0644)",
"line": 20
},

**Comment by steven-zou** [comment]
Fix parts:
{
"severity": "LOW",
"confidence": "HIGH",
"details": "Errors unhandled.",
"file": "/home/yan/Workspace/src/github.com/vmware/harbor/src/jobservice/job/impl/logger/job_logger.go",
"code": "jl.streamRef.Close()",
"line": 37
},

{
"severity": "HIGH",
"confidence": "HIGH",
"details": "TLS InsecureSkipVerify set true.",
"file": "/home/yan/Workspace/src/github.com/vmware/harbor/src/jobservice/opm/hook_client.go",
"code": "InsecureSkipVerify: true",
"line": 42
},

**Comment by steven-zou** [comment]
Vul of jobservice is fixed, close this issue.

**Comment by xu-xiang** [comment]
What tools used to get this security scan report?
@steven-zou
