### ISSUE TITLE
reset user password problem

### ISSUE THREAD

**Issue by rusirenye** [vmware/harbor#462]
when reset my password, I input new password and  confirm password with the same one. Then I update the new password with another string, I find the password confirm mechanism invalid.

**Comment by reasonerjt** [comment]
@rusirenye , do you mean the mechanism on UI is invalid?

**Comment by wknet123** [comment]
Due to the backend update user password SQL in DAO checking the same new password as old password take it as none of rows affected and throw a error to the front-end, it would show a error message dialog as I have fixed. Thanks.
