### ISSUE TITLE
Jobservice should read redis config from harbor.cfg for standalone installation 

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#4632]
Since we support configure redis in harbor.cfg. so we should read the configure in prepare scripts and set it to config.yml for job servercie in standalone modle.

Also should use the standard redis connection formation

redis_ip:6379,100,password,0

**Comment by steven-zou** [comment]
Please confirm the standard redis adderss format should be : "redis://arbitrary_usrname:password@ipaddress:port/database_index"

**Comment by steven-zou** [comment]
format 'address:port[,weight,password,db_index]' is supported and will be translated to "redis://u:password@address:port/db_index"

**Comment by steven-zou** [comment]
Work done, close it
