### ISSUE TITLE
Job service will report cross slot error when work with redis cluster

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#4633]
Apr 11 22:53:03 172.18.0.1 jobservice[971]: message repeated 439 times: [ ERROR: worker.fetch - CROSSSLOT Keys in request don't hash to the same slot]
Apr 11 22:53:03 172.18.0.1 jobservice[971]: ERROR: requeuer.process - CROSSSLOT Keys in request don't hash to the same slot
Apr 11 22:53:03 172.18.0.1 jobservice[971]: ERROR: requeuer.process - CROSSSLOT Keys in request don't hash to the same slot
Apr 11 22:53:03 172.18.0.1 jobservice[971]: ERROR: worker.fetch - CROSSSLOT Keys in request don't hash to the same slot

https://stackoverflow.com/questions/38042629/redis-cross-slot-error

**Comment by yixingjia** [comment]
The redis cluster is 3 master+ 3 slave case. this can be reproduce with only two master node.

**Comment by steven-zou** [comment]
This issue is from the dependant library and we may need time to let the maintainers or submit PR to fix it. Probably, it would become a limitation of v 1.5.0.

**Comment by steven-zou** [comment]
No time to complete it at SP34, move to SP35

**Comment by ywk253100** [comment]
Try the version 0.5.1 of package github.com/gocraft/work, the issue still there. Move this out of target 1.6.0.

**Comment by reasonerjt** [comment]
set to priority HA as it blocks HA.

**Comment by ywk253100** [comment]
Done
