### ISSUE TITLE
The labels which are not added to the image are checked

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#4636]
<img width="1640" alt="label_issue" src="https://user-images.githubusercontent.com/5835782/38662432-d932a9fc-3e66-11e8-9b44-939d207e8371.png">

Steps to reproduce the issue:
1. Add label `development` to tag `busybox`
2. Add label `produce` to tag `1.0`
3. Try to add labels to tag `2.0`

**Comment by lweitzman** [comment]
This may be related to https://github.com/vmware/harbor/issues/4617
