### ISSUE TITLE
Helm chart : generation of ingress TLS certificates overrides external certificate

### ISSUE THREAD

**Issue by draeron** [vmware/harbor#4644]
Right now, the way the chart is written, if you enable TLS for the ingress, the ingress secrets get populated with self signed certificate. If using an external certificate manager (ex: https://github.com/jetstack/cert-manager), these will be overwritten with an helm update.

Suggested solution: add a generation option toggle for ingress-secret.yaml

```
Helm Chart Version : 0.1.1
```

**Comment by jessehu** [comment]
@draeron do you have more details on how to use an external certificate manager in K8s. I'm not familiar with it.
Adding a generation option toggle for ingress-secret.yaml is straightforward.

**Comment by draeron** [comment]
it's really quite simple, well as simple as tls certificate can be. The service _cert-manager_ (which is installed on the k8s cluster) will connect to [acme / let's encrypt](https://letsencrypt.org/) to make dns challenge with the authority and once a certificate has been emitted, it will be saved in the secrets specified in the ingress's definition.

The certificate then get renewed automagically when they are close to expire.

More info : 
Doc: https://cert-manager.readthedocs.io/en/latest/

**Comment by jessehu** [comment]
Thanks @draeron . BTW, would like to create a Pull Request for this change ?

**Comment by draeron** [comment]
will do, let me update the readme with some extra infos.

**Comment by draeron** [comment]
Question @jessehu : i have other various improvements i've been adding the helm chart and i would be happy to push them back to the repository. Would you prefer one pull request with all of them or have them reviewed separately ?

here's the commits : 
https://github.com/draeron/harbor/commits/helm-improvement

**Comment by jessehu** [comment]
Fixed by https://github.com/vmware/harbor/pull/4682
