### ISSUE TITLE
The label editor should be closed after editing action succeeded

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#4655]
<img width="1158" alt="screen shot 2018-04-13 at 16 15 32" src="https://user-images.githubusercontent.com/5753287/38724222-209c94ae-3f36-11e8-95ca-4c2766b6e8ba.png">

**Comment by pengpengshui** [comment]
I think  user may want to add some labels at  a time, and it does`t take much place . so  it is best to keep open when click ok . what`s your suggestion? @lweitzman

**Comment by lweitzman** [comment]
i was thinking the same, the user might want to create multiple tags at the same time (especially in the beginning) so i thought it could stay open as well. github does the opposite where each time a label is created, the form is closed.
