### ISSUE TITLE
The filter of clarity grid at the "labels" column of image grid  does not work.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#4663]
We should consider disable the filter of this column:

<img width="459" alt="screen shot 2018-04-13 at 5 35 37 pm" src="https://user-images.githubusercontent.com/2390463/38728647-086c380a-3f43-11e8-80b5-41ab1b048e7e.png">

**Comment by pengpengshui** [comment]
had already repealed the column filter
