### ISSUE TITLE
repositories listing spinner is never removed

### ISSUE THREAD

**Issue by doctori** [vmware/harbor#4664]
Hi, 
the more I add project/repositories inside this wonderful project that is Harbor,
the slower it gets (which is fine, it's mostly based on the fact that the registry storage is based on S3)
after a certain point, the spinner that hide the empty list of repostories is never removed and the repositories list is never displayed like this : 
![image](https://user-images.githubusercontent.com/3294449/38728143-544a58e4-3f0f-11e8-8248-b347f95669bf.png)
I'm using harbor those images : 
```
vmware/nginx-photon:v1.4.0             
vmware/harbor-ui:v1.4.0                
vmware/clair-photon:v2.0.1-v1.4.0      
vmware/harbor-adminserver:v1.4.0       
vmware/registry-photon:v2.6.2-v1.4.0   
vmware/postgresql-photon:v1.4.0        
vmware/harbor-db:v1.4.0                
vmware/harbor-log:v1.4.0               
vmware/harbor-jobservice:v1.4.0        
```
with this docker version : 
```
root@pebitdocreg01:/var/log/harbor# docker info
Containers: 16
 Running: 9
 Paused: 0
 Stopped: 7
Images: 204
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 403
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 3.16.0-5-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.804GiB
Name: xxxxxxxxxxxxxx
ID: LSED:OOLL:RKVR:XBY7:6E47:7LZI:GPJ3:2A75:Q4XG:4VZU:J3ND:ND3A
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://isp-xxxxxxxx:3128/
No Proxy: localhost,127.0.0.1
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
[this is the harbor](https://github.com/vmware/harbor/files/1907199/harbor.txt) configuration  

[These are the logs](https://github.com/vmware/harbor/files/1907203/harbor_logs.txt) from the UI engine, nothing wrong from my point of view

no logs from the JS client, and the call to `/api/repositories?page=1&page_size=15&project_id=3` returns successfully in 8 seconds like stated in the logs from the UI.

Is there a way to specify a bigger timeout in the JS or something ? 
Thank you for you work on this project.

**Comment by reasonerjt** [comment]
@doctori could you provide the proxy.log?

**Comment by ywk253100** [comment]
Fixed.
