### ISSUE TITLE
Project admin can not change the role of some developer users

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#4665]
User02 can not change the role of user03:
<img width="1671" alt="member_issue_01" src="https://user-images.githubusercontent.com/5835782/38729200-bd16cdb4-3f44-11e8-989b-b69c62be4500.png">
But user02 can change the role of user06:
<img width="1668" alt="member_issue_02" src="https://user-images.githubusercontent.com/5835782/38729202-bff18092-3f44-11e8-9701-57a3fd4ee9a9.png">

**Comment by stonezdj** [comment]
It is a UI issue.
