### ISSUE TITLE
Harbor tile upgrade from 1.4 to 1.5 failed

### ISSUE THREAD

**Issue by stonezdj** [vmware/harbor#4669]
1.Deploy Harbor Registry 1.4.0 in Ops Manager
2.Login and create project and push images to harbor 
3.Deploy Harbor Registry 1.5.0 to upgrade the 1.4.0

Apply change failed with error: 
"Action Failed get_task:"
"result 1 of 3 pre-start scripts failed. Failed Jobs: harbor.
Successful Jobs: enable-bosh-dns, bosh-dns.

**Comment by jessehu** [comment]
Fixed in https://storage.googleapis.com/harbor-ci-pipeline-store/tile-releases/harbor-container-registry-1.5.0-build.27.pivotal
