### ISSUE TITLE
Branding?

### ISSUE THREAD

**Issue by bergtwvd** [vmware/harbor#4681]
I wonder what kind of branding is possible with Harbor and how to accomplish this?

E.g. what files to edit change logo?

Thanks.

**Comment by bergtwvd** [comment]
Thanks. However, this requires me to rebuild the product. I am looking for similar options for an already built product.  How to accomplish this?

**Comment by steven-zou** [comment]
@bergtwvd 

 we do NOT support that way yet. If you want to brand new logo, re-building code is the only supporting way so far.

**Comment by steven-zou** [comment]
No other thing to discuss, close this issue now.

**Comment by steven-zou** [comment]
Reopen for more discussion

**Comment by steven-zou** [comment]
@bergtwvd 

  If we implement the configurable rebranding like you described as a commercial enhancement, will your organization accept that and pay for it?

**Comment by bergtwvd** [comment]
No, I won't be able to get this funded.  I guess you have to shelve this on the list of feature requests 😃

**Comment by steven-zou** [comment]
@bergtwvd Got it. It may be a long time waiting. ^_^

I'll close this issue. If needed, let's raise a new detailed one for tracking.
