### ISSUE TITLE
Read Only Mode Shouldn't show in VIC

### ISSUE THREAD

**Issue by ninjadq** [vmware/harbor#4697]
![image](https://user-images.githubusercontent.com/1069785/38867988-2ccfc4cc-4278-11e8-9a22-b5777080f0b6.png)

**Comment by lweitzman** [comment]
Tooltip needs to be reworded

**Comment by reasonerjt** [comment]
Agreed, @ninjadq let's reword the tooltip.

**Comment by alextopuzov** [comment]
Do you mean that rewording is needed on the Harbor standalone side?
Is the checkbox going to be hidden in VIC?

**Comment by ninjadq** [comment]
@alexellis yes, rewording is for harbor standalone. On VIC, read-only will be hidden.

**Comment by ninjadq** [comment]
fixed on #4700 and #4696

**Comment by alexellis** [comment]
@ninjadq - I think the ping was for @alextopuzov ?

**Comment by ninjadq** [comment]
@alexellis oh, you are right 😱,  sorry to bother you
