### ISSUE TITLE
Disable sign up and invite users instead?

### ISSUE THREAD

**Issue by AlexZeitler** [vmware/harbor#47]
First: thanks for harbor :+1: 

Is it possible to disable the sign up and let user join only by admin invite?

**Comment by reasonerjt** [comment]
We will consider to implement this feature.  Thanks for the suggestion.

**Comment by reasonerjt** [comment]
#66 implements a simpler approach to allow admin to add user directly and add a switch in harbor.cfg to turn off the sign up.

**Comment by AlexZeitler** [comment]
@reasonerjt Tested it using b0bd7c4 - works like a charm! :+1:
