### ISSUE TITLE
Notary init

### ISSUE THREAD

**Issue by vielktus** [vmware/harbor#4729]
Hi,
I'm new to Notary. I installed Harbor with docker-compose (with Clair and Notary), used my self-signed certificate. I already copied CA cert to my macbook's docker client as mentioned in your guide.

When pushing image, I use this command:
```
docker push reg.test.local/test-project/test-app:2.0
```
Set all the required passphrases:
```
The push refers to repository [reg.test.local/test-project/test-app]
cd7100a72410: Layer already exists
2.0: digest: sha256:8c03bb07a531c53ad7d0f6e7041b64d81f99c6e493cb39abba56d956b40eacbc size: 528
Signing and pushing trust metadata:
Enter passphrase for root key with ID 67b7b71:
Enter passphrase for new repository key with ID 1e63a1a:
Repeat passphrase for new repository key with ID 1e63a1a:
```
And finally, got this error:
```
Error: trust data missing for remote repository reg.test.local/test-project/test-app or remote repository not found: timestamp key trust data unavailable.  Has a notary repository been initialized?
```
Did I miss anything ? Do I have to init the Notary repo. How should I achieve this ?

Thanks in advance.

**Comment by vielktus** [comment]
Was able to fix this by using https://docs.docker.com/notary/advanced_usage/#initialize-a-trusted-collection.
Can be closed now.

**Comment by reasonerjt** [comment]
@vielktus glad it does not block you.

However, `notary init` should not be necessary.

If you have time could you try `docker --debug push xxxx` 

Could you also let us know your docker version?

**Comment by danielzhanghl** [comment]
hi, I got the same error,  output as below is the deubg infor, please help on this.thanks!

docker -v
Docker version 19.03.4, build 9013bf583a

docker --debug push 10.75.210.80:4483/test-project/golang:1.9.2
The push refers to repository [10.75.210.80:4483/test-project/golang]
73d61bf022fd: Mounted from library/golang
5bbc5831d696: Mounted from library/golang
d5974ddb5a45: Mounted from library/golang
f641ef7a37ad: Mounted from library/golang
d9ff549177a9: Mounted from library/golang
1.9.2: digest: sha256:b1165286043f2745f45ea637873d61939bff6d9a59f76539d6228abf79f87774 size: 1363
Signing and pushing trust metadata
DEBU[0000] reading certificate directory: /root/.docker/tls/10.75.210.80:4483
DEBU[0001] No yubikey found, using alternative key storage: no library found
DEBU[0001] Making dir path: /root/.docker/trust/tuf/10.75.210.80:4483/test-project/golang/changelist
DEBU[0001] received HTTP status 404 when requesting root.
DEBU[0001] No yubikey found, using alternative key storage: no library found
DEBU[0001] No yubikey found, using alternative key storage: no library found
Enter passphrase for root key with ID ae90263:
DEBU[0020] generated ECDSA key with keyID: 7baa29c9ede0a2ce7a9cf3eb1570e2040983ea01bf82be45471e52f06c093855
DEBU[0020] generated new ecdsa key for role: targets and keyID: 7baa29c9ede0a2ce7a9cf3eb1570e2040983ea01bf82be45471e52f06c093855
Enter passphrase for new repository key with ID 7baa29c:
Repeat passphrase for new repository key with ID 7baa29c:
Error: trust data missing for remote repository 10.75.210.80:4483/test-project/golang or remote repository not found: timestamp key trust data unavailable.  Has a notary repository been initialized?
[root@danieldev /var/log/harbor]$ cd /root/.docker/trust/tuf/10.75.210.80:4483/test-project/golang/changelist
[root@danieldev ~/.docker/trust/tuf/10.75.210.80:4483/test-project/golang]$ tree
.
|-- changelist
`-- metadata

2 directories, 0 files
