### ISSUE TITLE
When search users in public projects, then switch to another project , the page pop up a  error  window 

### ISSUE THREAD

**Issue by rusirenye** [vmware/harbor#475]
the popped windows hint Error:Failed to get current project member.

**Comment by reasonerjt** [comment]
if the user is not logged in, UI should redirect to login page

**Comment by reasonerjt** [comment]
A non-admin user may not be a member of a public project in this case he should not see the member of the project.

So I think the options like "users" "logs" "replications" should be hidden when the tab is switched to "public project"
