### ISSUE TITLE
Multi-language change to French does not work

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#4752]
when change language to French, it does not change to French
![french](https://user-images.githubusercontent.com/23101283/39043536-466ff808-44c0-11e8-82ef-0c41f73721b2.PNG)

**Comment by aditr** [comment]
@pengpengshui Sorry, I don't work on harbor so please unassign me from the issue.

**Comment by pengpengshui** [comment]
I just wana test the Labels funcion , sorry  for my action to disturb you @aditr

**Comment by steven-zou** [comment]
We ONLY support three languages, but I saw four menu items in the sceenshot
