### ISSUE TITLE
Can not push signed image for notary signer is restarting

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#4765]
Version v1.5.0-a342c31a

Can not push signed image for notary signer is restarting
{"level":"fatal","msg":"Could not read config at :/etc/notary/signer-config.json, viper error: open /etc/notary/signer-config.json: permission denied","time":"2018-04-23T06:50:20Z"}

**Comment by reasonerjt** [comment]
I'll need to check the env, if the signer is restarting the travis-ci should fail.

**Comment by wy65701436** [comment]
fixed in ova.
