### ISSUE TITLE
Harbor API "automatically_scan_images_on_push" not work

### ISSUE THREAD

**Issue by jeffweilee** [vmware/harbor#4770]
Harbor create project API:
POST /project
{
  "project_name": "string",
  "public": 0,
  "enable_content_trust": true,
  "prevent_vulnerable_images_from_running": true,
  "prevent_vulnerable_images_from_running_severity": "string",
  "automatically_scan_images_on_push": true
}

Response 201 Created but the following project settings did not take affect
 "automatically_scan_images_on_push": true not work
 "prevent_vulnerable_images_from_running_severity" not work
 "prevent_vulnerable_images_from_running" not work

1) docker 17.03.2-ce, docker-compose 1.16.1
2) HTTPS enabled

**Comment by ywk253100** [comment]
Dup of #4771, closing this one.
