### ISSUE TITLE
[LDAP]Shall we redesign the admin change name button? or just keep current design

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#4772]
Some user may need to change the default admin name to login the user named admin in ldap mode
current design is this
![current](https://user-images.githubusercontent.com/23101283/39174279-d88840a8-47d9-11e8-9e91-28cab742c2d4.PNG)

and the new design is this
![new](https://user-images.githubusercontent.com/23101283/39174285-dd88ed8c-47d9-11e8-8ede-6a32cb389f02.PNG)

the new design looks a little strange, if possible, we should have a new design or just keep current

**Comment by steven-zou** [comment]
@ninjadq 

Please apply the new ui of changing admin account

**Comment by reasonerjt** [comment]
Closing as it's fixed.
