### ISSUE TITLE
Cannot refresh repository view

### ISSUE THREAD

**Issue by lazarin** [vmware/harbor#4786]
Using harbor-ui version **0.6.89**
Users open a harbor repo and see the current content. Then through docker cli a new image is pushed to the repo, but the UI does not show the new image - the 'Refresh' button seems disabled.
Workaround is to exit from the repo and enter again. Then new images are shown, however the 'Refresh' continues to be disabled.

Screen shot is attached: 
![screenshot at 2018-04-26-12-47-09](https://user-images.githubusercontent.com/676880/39299051-828fbb18-4950-11e8-8c41-f5f83f1f0af1.png)

**Comment by steven-zou** [comment]
@lazarin checked, this is a bug from admiral side, I will close this one and raise a new one @admiral GitHub repo https://github.com/vmware/admiral/issues/270
