### ISSUE TITLE
Maybe need improvement for the design of the "DEPLOY" button in card view

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#4787]
Below is the `PROVISION` button of Admiral's card view component:
<img width="1674" alt="pv1" src="https://user-images.githubusercontent.com/5835782/39303133-a4ae6956-4987-11e8-975a-ed23cb20d32b.png">

And below is the `DEPLOY` button of Harbor's card view component:
<img width="1673" alt="pv2" src="https://user-images.githubusercontent.com/5835782/39303134-a74fe482-4987-11e8-9c66-1a16934de1da.png">

The `Add additional info` should be in a group with `DEPLOY` rather than with `Delete`as the `Add additional info` is the extention of `DEPLOY`.

**Comment by reasonerjt** [comment]
@lweitzman An more severe problem currently is that when there's multiple tags and none of the tags is "latest" the deployment will fail.  Maybe we should remove the `deploy` button and only leave the button `add additional info`, so user always have a chance to update the tag in the flow of deployment.

**Comment by reasonerjt** [comment]
Close this as a dup of #4788
