### ISSUE TITLE
Click the "DEPLOY" button directly will fail if the repository contain no image whose tag is latest

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#4788]
If the repository `library/hello-world` contains no image whose tag is latest, clicking the `DEPLOY` buttion will fail as the `latest` is the default value if no tag is specified:
<img width="1665" alt="deploy" src="https://user-images.githubusercontent.com/5835782/39305079-69b76e68-498e-11e8-8c21-a03eca3310b1.png">
Users can click the `Add addtional info` and choose an existing tag to work around this issue:
<img width="1675" alt="deploy_02" src="https://user-images.githubusercontent.com/5835782/39305122-8c29aa2e-498e-11e8-98b6-af20c1206e87.png">

**Comment by steven-zou** [comment]
@lweitzman The button style should be kept consistent with the button in Admiral side

**Comment by ninjadq** [comment]
@lweitzman I agree with you, but Admiral does not strictly obey the clarity standard. Most of the engineering work of your design is on Admiral side. But currently, we should follow their style, or can you pursuit them?

**Comment by lweitzman** [comment]
@ninjadq asking PM and eng leads about consistency of menus with the hope that i can persuade them

**Comment by reasonerjt** [comment]
Before we reach agreement with Admiral.
On Harbor's UI we can mitigate the issue by:
When there's no "latest" tag of the repo, the deploy button will be disabled and a tooltip will be shown to ask user set the "additional info"

**Comment by lweitzman** [comment]
Instead of "additional info" i recommend that we rename that option to "Deploy with options" as stated above. I think its much clearer as to what the action is going to do.

**Comment by stuclem** [comment]
Proposed release note:

- <b>Clicking Deploy for an image in the Internal Repositories view fails if no `latest` tag is present. [#4788](https://github.com/vmware/harbor/issues/4788)</b>This will be fixed in an update release.

@reasonerjt is this OK?

**Comment by reasonerjt** [comment]
We'll use this issue to track the text change, will close it once we confirm the text in the label and make necessary change.
