### ISSUE TITLE
Hardcoded endpoints in project.service.ts and replication.service.ts

### ISSUE THREAD

**Issue by shadjiiski** [vmware/harbor#4790]
In `project.service.ts` there is a hardcoded endpoint `/api/projects`, [here for example](https://github.com/vmware/harbor/blob/7bf277df6ebbc020134a72b73a7dcf91ac25d696/src/ui_ng/lib/src/service/project.service.ts#L90). Also, there is a hardcoded endpoint `/api/replications` in replication.service.ts [here](https://github.com/vmware/harbor/blob/7bf277df6ebbc020134a72b73a7dcf91ac25d696/src/ui_ng/lib/src/service/replication.service.ts#L156). These should be extracted to be part of the service configuration ([example](https://github.com/vmware/harbor/blob/c33ed6f9578cf19c1bc79c0a47cef3e056bb812e/src/ui_ng/lib/src/harbor-library.module.ts#L73)). This issue is blocking [Admiral#268](https://github.com/vmware/admiral/issues/268)

**Comment by steven-zou** [comment]
Thanks, @shadjiiski. Checked, hardcoded URL existing. Will fix soon.
