### ISSUE TITLE
Label color picker can not open in Firefox and icon has offset

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#4796]
If you create a new label, click the color picker, it can not open on Firefox, and the color picker drop down button icon has offset
![color](https://user-images.githubusercontent.com/23101283/39343946-3449d412-4a12-11e8-9912-73d5dd84ba5a.PNG)

**Comment by wy65701436** [comment]
same as chrome

**Comment by steven-zou** [comment]
@pengpengshui Is it already fixed. If YES, please close it.
