### ISSUE TITLE
New Label doesn't work at sometimes.

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#4805]
Click "New Label"
![image](https://user-images.githubusercontent.com/2841473/39349952-95d2495a-49b1-11e8-916e-3d59a826793f.png)

**Comment by reasonerjt** [comment]
@zhoumeina  please sync with @wy65701436 to triage

**Comment by zhoumeina** [comment]
@wy65701436  
what is the browser ? I tried it in chrome. It works well.

**Comment by zhoumeina** [comment]
fix by #5392
