### ISSUE TITLE
[LDAP]  Add ability to define harbor admins via LDAP group.

### ISSUE THREAD

**Issue by ArcticSnowman** [vmware/harbor#4828]
At present to set anyone as a admin, request the default 'harbor' account or an existing admin to setup the user.  It would be better if it was possible to define a mapping from a LDAP group to admin.

Some like `ldap_admin_dn`?

**Comment by choman** [comment]
I was just gonna ask if something like this was possible

**Comment by stonezdj** [comment]
We are developing the feature of assigning role to LDAP group, and will discuss it later

**Comment by reasonerjt** [comment]
UI is not done, let's see if we can incoporate this in 1.6
