### ISSUE TITLE
Datagrid columns don't align after resizing 

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#4834]
after resizing the datagrid, the column headings don't align with their content.

![Screen Shot 2018-05-01 at 10.59.35 AM.png](https://images.zenhubusercontent.com/56afa7c46caf56c9d38c1f12/b15de49a-a465-4b98-a11f-c4b4b7ff87fa)

**Comment by steven-zou** [comment]
We'll check if it's caused by the fixed column settings.

**Comment by lweitzman** [comment]
could you add scanned images into a project. and add more than 1 tag to that image. then close down the viewport horizontally.  it looks like the content in the datagrid doesn't move with the column titles

**Comment by lweitzman** [comment]
i can not reproduce this now on https://10.193.22.115/ on a mac.
