### ISSUE TITLE
How to get raw manifest list from remote harbor docker registry via API

### ISSUE THREAD

**Issue by DavidRodHub** [vmware/harbor#4835]
Docker version 18.03.1-ce, build 9ee9f40

I can get the raw manifest list from AWS registry  using the following API from the command line:
     $ curl -u uersid:password -X GET https://aws-registry.domain.com/v2/library/my-repo/manifests/1.0

The output to the above command is below..  How can this be done for a docker image in a remote harbor registry?

{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 8471,
      "digest": "sha256:df5d50464b39a6796de3f435ce0367f2d3749ed9e9c4a7457e2f6b4e3befce13"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 52608519,
         "digest": "sha256:f2b6b4884fc8b2f1fcef843f92f7c82c9c149df85ac77e5f0de7a342ae442412"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 223,
         "digest": "sha256:b58fe2a5c9f1c2efb33bd7bf3983887f36d666824be7da83233248b00c02ba10"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 154,
         "digest": "sha256:e797fea70c453eca2b2d126fc354c385a832a94171fbbd33d7aa90431cb93e04"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 338,
         "digest": "sha256:6c7b4723e810785acaece3ccdcc252800ee7843b0c91af0abf0334bc66b2a634"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 13388806,
         "digest": "sha256:02074013c987c6a9823f25f513c6813bd81efeaab23150ccd710c69114bd7cbd"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 2986059,
         "digest": "sha256:4ad329af1f9eb8519a7a1cf77f45fe91137188a3caf891015e8be755d4383800"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 303,
         "digest": "sha256:0cc56b739fe0d60f0beac850d795a4556c5d14a1a7f9673598c1993dd7760701"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 274,
         "digest": "sha256:f5c7c67f9c106a7e38365234e8586d573ca76f3da343a5eed250663c48f77b6b"
      }
   ]

**Comment by ywk253100** [comment]
Harbor supports the standard docker registry API. But you need to get a valid token by calling `GET /service/token` first. About the detail of token, please refer to https://github.com/docker/distribution/blob/master/docs/spec/auth/token.md.

**Comment by DavidRodHub** [comment]
**Thanks for the quick response.    I able to get the token by doing the following command:**

$ curl -i -k -u userid:password https://docker-reg.int.com/service/token?account=admin\&service=harbor-registry\&scope=repository:library/hello-world/1.0:pull,push

**Get the following output that contains the Token:**

HTTP/1.1 200 OK
Server: nginx
Date: Thu, 03 May 2018 00:08:51 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 1221
Connection: keep-alive
Keep-Alive: timeout=5
Set-Cookie: beegosessionID=a3884e97a38a12b77c21f851b9e64c9b; Path=/; secure; HttpOnly

{
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjVRV0c6SUFSUTpNRDVWOlBQVks6UkNYSjo3WkhZOk9EN0E6TEdUVTpWWDc3OjdFWkU6N1FMTzpCS1RDIn0.eyJpc3MiOiJoYXJib3ItdG9rZW4taXNzdWVyIiwic3ViIjoiYWRtaW4iLCJhdWQiOiJoYXJib3ItcmVnaXN0cnkiLCJleHAiOjE1MjUzMDc5MzEsIm5iZiI6MTUyNTMwNjEzMSwiaWF0IjoxNTI1MzA2MTMxLCJqdGkiOiJEbmtkbGNOMWxQR2NwOHczIiwiYWNjZXNzIjpbeyJ0eXBlIjoicmVwb3NpdG9yeSIsIm5hbWUiOiJzYW5kYm94L2VhYS1ueC1hbS1kcm9kLXRlc3QvMTIuMSIsImFjdGlvbnMiOlsicHVzaCIsIioiLCJwdWxsIl19XX0.jZv8goxIRHxteO1PHVr0LDR3wNCeZsdbal8qXboIYzBuRWgp6UzP52J9mJBnB6y_gZT9nnUFNB4l2O2bi-3QKarkUChd2KaK6nnyHK8AQFxd7QDeV_vvA_itLGEjNhoYAp-MHAb-PWCEhPgt9uIc957iG0PHq7tL3HIkbbc-IlfCgSkfIMlxUNMLcBa2PQg6T0x5pZ4oJJrC1Ntl0Zpa-F9sbFRby-4ii4vPM0GvmHKP_kRd0Ow5IxP64BjjQ-wONOAFgWYF2mTyAnQr8mq5Ah5HeiVAoT4de7fmo_uF7u7jFdxLPtjo7UfgQqsy8nPJZpFFOuUC4JAPja2A5fcABblWip_UybU-vm9hsYot68R6NF_GVym1FENGOzYXF--ObKHLHegLjOdQBauT95FX5Gaf3Fz5FI_z9lxX-yz0jIg1t-RE-Vnzf2FwYH8nrH4TtebKPDSNewiAPybJEpNd9wZPT9bZM0NXKOuTzk5pcrYlSSqzsaiU--PEXkRPSvypZR25OP2YQy1FapRwO-lm6sV_TlObZ_fehG2tYqwAr4e97VHBXTDmO6XSxxb1I_pVmUmxTP5DeSPIVfGxVhBjas2ppPqbC8Tc2noHHhR2_3MSrVFJ5i5nVo29Po7UyR9leRRn6YMH9E6iMFtR3xRj9kpJwLdePFC4AxZXnDYVUhk",
  "expires_in": 1800,
  "issued_at": "2018-05-03T00:08:51Z"

**Entered the following command that includes the token.    It returns ">"  like the command is missing something.  Not sure what.**

curl -k -v -H "Content-Type: application/json" -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjVRV0c6SUFSUTpNRDVWOlBQVks6UkNYSjo3WkhZOk9EN0E6TEdUVTpWWDc3OjdFWkU6N1FMTzpCS1RDIn0.eyJpc3MiOiJoYXJib3ItdG9rZW4taXNzdWVyIiwic3ViIjoiYWRtaW4iLCJhdWQiOiJoYXJib3ItcmVnaXN0cnkiLCJleHAiOjE1MjUzMDc5MzEsIm5iZiI6MTUyNTMwNjEzMSwiaWF0IjoxNTI1MzA2MTMxLCJqdGkiOiJEbmtkbGNOMWxQR2NwOHczIiwiYWNjZXNzIjpbeyJ0eXBlIjoicmVwb3NpdG9yeSIsIm5hbWUiOiJzYW5kYm94L2VhYS1ueC1hbS1kcm9kLXRlc3QvMTIuMSIsImFjdGlvbnMiOlsicHVzaCIsIioiLCJwdWxsIl19XX0.jZv8goxIRHxteO1PHVr0LDR3wNCeZsdbal8qXboIYzBuRWgp6UzP52J9mJBnB6y_gZT9nnUFNB4l2O2bi-3QKarkUChd2KaK6nnyHK8AQFxd7QDeV_vvA_itLGEjNhoYAp-MHAb-PWCEhPgt9uIc957iG0PHq7tL3HIkbbc-IlfCgSkfIMlxUNMLcBa2PQg6T0x5pZ4oJJrC1Ntl0Zpa-F9sbFRby-4ii4vPM0GvmHKP_kRd0Ow5IxP64BjjQ-wONOAFgWYF2mTyAnQr8mq5Ah5HeiVAoT4de7fmo_uF7u7jFdxLPtjo7UfgQqsy8nPJZpFFOuUC4JAPja2A5fcABblWip_UybU-vm9hsYot68R6NF_GVym1FENGOzYXF--ObKHLHegLjOdQBauT95FX5Gaf3Fz5FI_z9lxX-yz0jIg1t-RE-Vnzf2FwYH8nrH4TtebKPDSNewiAPybJEpNd9wZPT9bZM0NXKOuTzk5pcrYlSSqzsaiU--PEXkRPSvypZR25OP2YQy1FapRwO-lm6sV_TlObZ_fehG2tYqwAr4e97VHBXTDmO6XSxxb1I_pVmUmxTP5DeSPIVfGxVhBjas2ppPqbC8Tc2noHHhR2_3MSrVFJ5i5nVo29Po7UyR9leRRn6YMH9E6iMFtR3xRj9kpJwLdePFC4AxZXnDYVUhk“ -X GET https://docker-reg.int.com/v2/library/hello-world/manifests/1.0
>

**Comment by ywk253100** [comment]
Wrong `"` is used before `-X GET`.

Besides, the scope used to request token should be `scope=repository:library/hello-world:pull,push`, no tag `1.0` is needed.
