### ISSUE TITLE
harbor中配置https，在harbor0.10版本中需要做调整

### ISSUE THREAD

**Issue by kinglion811** [vmware/harbor#484]
https://github.com/vmware/harbor/blob/master/docs/configure_https.md
这个小细节在harbor0.10版本需要调整，
![image](https://cloud.githubusercontent.com/assets/6119243/16613902/078d88ca-43a1-11e6-946c-bf5fbfa52287.png)
nginx镜像中，/etc/nginx/目录下没有cert目录，应该是
/etc/nginx/yourdomain.com.crt
/etc/nginx/yourdomain.com.key
且需要修改docker-compose.yml 文件
我修改成
![image](https://cloud.githubusercontent.com/assets/6119243/16613985/73f9435a-43a1-11e6-8e50-a18ac5b608dc.png)
或者直接挂./config/nginx 目录
![image](https://cloud.githubusercontent.com/assets/6119243/16642137/444bd386-443a-11e6-87d2-d6aad642b1a6.png)

本地的443端口也也映射nginx的443端口

**Comment by reasonerjt** [comment]
There should be /etc/nginx/cert/ if you follow the guide.

Before your screenshot there's a section to create the **cert/** directory:

<img width="941" alt="screen shot 2016-07-06 at 8 10 22 pm" src="https://cloud.githubusercontent.com/assets/2390463/16617347/c466c498-43b5-11e6-8010-78398ca450f2.png">

**Comment by mritd** [comment]
我书读的少，你可不要骗我 


![image](https://cloud.githubusercontent.com/assets/13043245/16617465/6202e362-43b6-11e6-85d6-125da9833c26.png)


http://mritd.me/2016/07/03/Harbor-%E4%BC%81%E4%B8%9A%E7%BA%A7-Docker-Registry-HTTPS%E9%85%8D%E7%BD%AE/

**Comment by kinglion811** [comment]
@mritd 你哪些都没错，我这些也没错，主要原因是我git 下代码后chechout 出0.10版本，里面的docker-compose .yml文件，proxy是这么挂的vloume:
![image](https://cloud.githubusercontent.com/assets/6119243/16640977/eab64fb4-442e-11e6-808e-83a2c833eda4.png)
不是挂的./config/nginx 目录
现在git上已经改了
![image](https://cloud.githubusercontent.com/assets/6119243/16640995/1aaed1be-442f-11e6-9687-8d5d18281b3f.png)
你可以看看0.10版本里面的compose文件是否是我所说的？

**Comment by reasonerjt** [comment]
@kinglion811 @mritd 
是如您所说，但是请看我的回复，在文档里说了 “Create a directory cert/, if it does not exist"
也就是说这个cert/目录是后来建的

**Comment by kinglion811** [comment]
@reasonerjt  在./config/nginx/下创建cert目录，然后挂载时
![image](https://cloud.githubusercontent.com/assets/6119243/16645713/626e083e-4458-11e6-838f-0aca5ff426aa.png)
是这样的

**Comment by hainingzhang** [comment]
Not an issue. Please refer to the document. Closing it for now. Please reopen if needed.
