### ISSUE TITLE
Harbor Appliance / second NIC and LDAP config after deployment

### ISSUE THREAD

**Issue by GreyhoundHH** [vmware/harbor#4842]
I've got questions regarding the Harbor Appliance.

1) Is it possible to set up LDAP/AD-authentication after the deployment of the appliance?
2) Is it possible to setup a second NIC with a different network on that appliance?

**Comment by stonezdj** [comment]
1. If you did not create any user in harbor after deployment, you can switch the config from DB to LDAP auth mode.
2. You can setup second NIC, but you can not access harbor through this NIC. because Harbor server is bind to a specific IP address already.
