### ISSUE TITLE
Can't delete project in Harbor

### ISSUE THREAD

**Issue by dmajere** [vmware/harbor#486]
Good day,

It seem's that there is no possibility to delete project from harbor.

**Comment by reasonerjt** [comment]
This is currently a limitation, due to auditing purpose you can not delete a project as the audit logs are associated to the project by id.

**Comment by dmajere** [comment]
I think that this limitation can be mitigated by introducing an additional field `Deleted` or `Dropped` to the project structure. It can be set to true, when project is deleted. This way we won't loose project Id.
Probably name of the deleted project should be set to 'None' or something like this, so the real name could be reused by another project.

**Comment by dmajere** [comment]
Sorry, I've noticed that this one is a duplicate of #112 
I will continue discussion in #112

**Comment by fuhbar** [comment]
Since this is a duplicate issue, we might close this one @reasonerjt
