### ISSUE TITLE
Support of web anchor for proxies?

### ISSUE THREAD

**Issue by robertrbruno** [vmware/harbor#4864]
Does harbor currently support setting an anchor on all urls?  Such as /harbor/  at the beginning of all web calls?  I have to put harbor behind a nginx proxy that proxies data for many uis so there is a need for a unique pattern to match on for each ui.  I can't use patterns like "/".  An anchor like this would help a lot.

If it does not support this, could a config be added to set one?  Or is there another recommended way to tackle this problem?

**Comment by reasonerjt** [comment]
Currently it does not.
There are two parts you may need to update I can think of:

1. The conf file of nginx
2. The config.yml of registry, which redirects docker to the URL of token service.

**Comment by reasonerjt** [comment]
I'm closing it as the question  is answered, feel free to re-open if you need further help.
