### ISSUE TITLE
配置oss存储,不能通过官方推荐的命令删除registry镜像

### ISSUE THREAD

**Issue by legolas-zeng** [vmware/harbor#4866]
配置了阿里云的oss存储，然后用：
> docker run -it --name gc --rm --volumes-from registry vmware/registry-photon:v2.6.2-v1.4.0 garbage-collect --dry-run /etc/registry/config.yml

命令查看能删除的镜像文件，还是显示的是本地的registry。不显示oss上面的。

**Comment by wy65701436** [comment]
@legolas-zeng  please provide the harbor.cfg and config.yml in the ./common folder

**Comment by legolas-zeng** [comment]
我用的是1.4版本。
harbor.cfg 只修改了hostname，ssl_cert，ssl_cert_key，config.yml配置如下：
> version: 0.1
log:
  level: info
  fields:
    service: registry
storage:
  cache:
    layerinfo: inmemory
  filesystem:
    rootdirectory: /storage
  maintenance:
    uploadpurging:
      enabled: false
  delete:
    enabled: true
http:
  addr: :5000
  secret: placeholder
  debug:
    addr: localhost:5001
auth:
  token:
    issuer: harbor-token-issuer
    realm: https://********/service/token
    rootcertbundle: /etc/registry/root.crt
    service: harbor-registry
notifications:
  endpoints:
  - name: harbor
    disabled: false
    url: http://ui:8080/service/notifications
    timeout: 3000ms
    threshold: 5
    backoff: 1s
就这些，然后就是docker-compose.yml上面就配置阿里云oss。

**Comment by ywk253100** [comment]
You need to configure the oss in harbor.cfg https://github.com/vmware/harbor/blob/v1.4.0/make/harbor.cfg#L156.
