### ISSUE TITLE
Additional information about image.

### ISSUE THREAD

**Issue by dmajere** [vmware/harbor#487]
There is no information about image size, number of image layers, commands that were used during layer creation.

**Comment by reasonerjt** [comment]
@ywk253100 I think it's already addressed via manifest api?  could you dup it?

**Comment by ywk253100** [comment]
The manifest does not contains these information now, we will add them later.

**Comment by ywk253100** [comment]
Fixed by #622 .

**Comment by dmajere** [comment]
Hi, will this information be available in harbor UI?

**Comment by ywk253100** [comment]
They are only available by calling API.
