### ISSUE TITLE
harbor镜像相关数据存储问题

### ISSUE THREAD

**Issue by fenggolang** [vmware/harbor#4871]
我发现下载官方的harbor安装包部署的时候，不能在一个地方指定好harbor镜像数据存储位置，而需要修改docker-compose.yml文件的许多地方，甚至harbor.cfg和prepare文件也是修改修改，不然默认安装完之后，都在/data目录下:
[root@harbor data]# ls -l
总用量 16
drwxr-xr-x  2   10000   10000    6 4月  23 14:12 ca_download
drwx------ 19 polkitd polkitd 4096 4月  23 15:31 clair-db
drwxr-xr-x  2   10000   10000    6 4月  23 14:11 config
drwxr-xr-x  5   10000   10000 4096 4月  23 15:31 database
drwxr-xr-x  3   10000   10000 4096 4月  25 17:22 job_logs
drwxr-xr-x  2   10000   10000    6 4月  23 14:12 psc
drwxr-xr-x  3   10000   10000   19 4月  23 14:40 registry
-rw-------  1   10000   10000   16 4月  23 14:11 secretkey
[root@harbor data]# 

请问，目前只能一个一个地方修改哇？

**Comment by ninjadq** [comment]
Yes, currently if you want to change installation directory you should change config files in multiple places manually.

**Comment by ninjadq** [comment]
@fenggolang  you can link `/data` to other dirs as a workaround
