### ISSUE TITLE
二进制安装失败

### ISSUE THREAD

**Issue by cw2018** [vmware/harbor#4874]
centos7.3
二进制安装失败，报以下错误(配置文件只修改了hostname)：

File "./prepare", line 398, in
[storage_provider_name + ':'] + map(string.strip, storage_provider_config.split(",")))
AttributeError: module 'string' has no attribute 'strip'

**Comment by reasonerjt** [comment]
Please let us know the version of your python

**Comment by cw2018** [comment]
python : v3.7

**Comment by wy65701436** [comment]
@cw2018 we did have a test on centos.  We will have a debug on this, but if possible, PR to fix it is welcome.

**Comment by jessehu** [comment]
Close it . Duplicated of #5053.
