### ISSUE TITLE
[Helm] fullname not included in Clair service definition

### ISSUE THREAD

**Issue by draeron** [vmware/harbor#4876]
In file `clair-svc.yaml`, the name of the service for clair doesn't include the release fullname, this will provoke a name collision if trying to install 2 releases of harbor in the same namespace.

This : 
```yaml
metadata:
  name: clair
```

Should be like this :
```yaml
metadata:
  name: "{{ template "harbor.fullname" . }}-clair"
```

Helm Chart : 0.1.2
Harbor version : 1.4.0

**Comment by jessehu** [comment]
Because the hostname 'clair' for clair service is hardcoded in Harbor 1.4.0, so we can not use "{{ template "harbor.fullname" . }}-clair". It will be fixed in Harbor 1.5.0.
