### ISSUE TITLE
V1.5.0 docker login error

### ISSUE THREAD

**Issue by sakufo** [vmware/harbor#4882]
安装后启动正常，web ui登录也正常
在使用docker login登录时出现以下错误，请帮助我！

[16:18:25 root@harbor131 harbor]#docker login harbor.yun-gui.com
Username: admin
Password: 
Error response from daemon: Get https://harbor.yun-gui.com/v2/: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.11.10</center>\r\n</body>\r\n</html>\r\n"

**Comment by sakufo** [comment]
上面的日志是前端nginx反向代理的错误，我查了harbor proxy上的日志是401错误。验证失败？我确信我输入的用户和密码都是正确的。

May  8 17:33:14 172.18.0.1 proxy[10307]: 172.19.1.130 - "GET /v2/ HTTP/1.0" 401 87 "-" "docker/18.03.0-ce go/go1.9.4 git-commit/0520e24 kernel/3.10.0-327.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/18.03.0-ce \x5C(linux\x5C))" 0.004 0.004 .

**Comment by reasonerjt** [comment]
How did you install Harbor? via offline installer or helm chart?

**Comment by sakufo** [comment]
offline installer

**Comment by sakufo** [comment]
我在harbor前端有一个nginx proxy
架构是：
docker --> nginx proxy：https  --> harbor nginx：http

**Comment by sakufo** [comment]
取消前端自己安装的nginx proxy反向代理后现在可以正常使用了，前端不能经过自己的反向代理吗

**Comment by reasonerjt** [comment]
There should be some misconfiguration in proxy or configuration files, but you need to debug yourself, as there are many factors to consider in the env...

**Comment by reasonerjt** [comment]
Closing as there's no further action to take.

**Comment by little-humor** [comment]
出于安全考虑，harbor服务器只能内网连接，我在上层配置了nginx作为入口，通过119.18.193.77:1952（上层nginx转发的是harbor服务器的内网地址10.6.52.5）可以正常访问harbor的ui界面，但是无法docker login 119.18.193.77:1952；该命令执行后的日志信息是：Error response from daemon: Get http://119.18.193.77:1952/v2/: Get http://10.6.52.5/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: net/http: request canceled (Client.Timeout exceeded while awaiting headers) (Client.Timeout exceeded while awaiting headers)harbor.cfg内容片段：_version = 1.5.0hostname = 10.6.52.5ui_url_protocol = httpno_proxy = 127.0.0.1,localhost,uiauth_mode = db_auth...
--

@sakufo @reasonerjt 
目前解决了吗？求帮助 非常感谢🙏
