### ISSUE TITLE
When there is no 'latest' tag, the 'Deploy' button will trigger a 'add info' event

### ISSUE THREAD

**Issue by ninjadq** [vmware/harbor#4883]
When there's no "latest" tag of the repo
the deploy button will be disabled and a tooltip will be shown to ask user set the "additional info"

**Comment by lweitzman** [comment]
duplicate of #4788

**Comment by steven-zou** [comment]
@lweitzman This one is not duplicated with #4788.
This one is used to track the work of disabling the 'DEPLOY' button when no `latest` tag existing
#4788 is to track the working of keeping consistent with Admiral UX
