### ISSUE TITLE
notary-server failed to start on K8s 1.10

### ISSUE THREAD

**Issue by shayulei** [vmware/harbor#4886]
Error: failed to start container "notary-server": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:364: container init caused \"rootfs_linux.go:54: mounting \\\"/var/lib/kubelet/pods/7981c0e7-5351-11e8-8197-00505688f21e/volume-subpaths/root-certificate/notary-server/1\\\" to rootfs \\\"/var/lib/docker/overlay2/7f7af74be5dbd6e31fd3561da7ea3e9e7609426b0b412580a9a3dd7d5ccaf1c1/merged\\\" at \\\"/var/lib/docker/overlay2/7f7af74be5dbd6e31fd3561da7ea3e9e7609426b0b412580a9a3dd7d5ccaf1c1/merged/config/root.crt\\\" caused \\\"not a directory\\\"\"" : Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
Back-off restarting failed container

**Comment by jessehu** [comment]
@shayulei what's your kubernetes server version ? e.g. the output of `kubectl version`

**Comment by jessehu** [comment]
Fixed in master branch
