### ISSUE TITLE
Unable to connect to notary server through notary CLI

### ISSUE THREAD

**Issue by kyrogue** [vmware/harbor#4887]
notary -v -s https://myserver.com list myserver.com/repo/image
Results in * fatal: .. does not have trust data for ...

When signing content with 
export DOCKER_CONTENT_TRUST=1 
export DOCKER_CONTENT_TRUST_SERVER=https://myserver.com:4443

The signing is successful and pushed to Harbor as a signed image.
However when i try use the notary CLI to view the notary server it is empty, is there another URL for the notary server?

**Comment by reasonerjt** [comment]
I think it should be `notary -v -s https://myserver.com:4443 ....` as it has to point to the notary server

**Comment by kyrogue** [comment]
When i put 4443, it says
* fatal: received unexpected HTTP status: 500 Internal Server Error
Im not sure why it happens, since using i am able to push images that are signed, which means notary is working.
