### ISSUE TITLE
Support replication filter in UI

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#4894]
We need to consider that the label is disabled in integration mode.

**Comment by wy65701436** [comment]
move it to sprint 36, not ready for E2E.

**Comment by reasonerjt** [comment]
There's big problem with this estimation, in review of PR #5154 , I feel at least it took more than 1 week.
There are a few issues in #5154  so it will be merged to a feature branch and be further reviewed.

**Comment by reasonerjt** [comment]
code merged to:
https://github.com/vmware/harbor/tree/replication_by_label_ui

**Comment by steven-zou** [comment]
Delegate @pengpengshui's work. As code merged in, let's close this issue.
