### ISSUE TITLE
UAA user see a lot of forbidden error after promoted to admin.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#4895]
Customer found that after login with UAA user, and promote this user to system admin in Harbor.  Login with UAA user again he see a lot of forbidden errors on the UI.

**root cause**
The authenticator of UAA didn't populate all data into the user model in subsequent login of UAA user.  And this is not covered in the TC.

**Comment by reasonerjt** [comment]
Fixed in #4900 and cherry picked to 1.4 and 1.5 branch respectively.

**Comment by nlowe** [comment]
@reasonerjt I see a `1.4.1` point release that contains this. Will `1.5` get a point release as well?

**Comment by reasonerjt** [comment]
@nlowe 
Yes, but we'll need a couple of more weeks to include other fixes in `1.5.1`

Are you using UAA?

**Comment by nlowe** [comment]
No. is that the only fix in `1.4.1`? I'm planning on upgrading to `1.5.0` here in 15ish minutes. If there's nothing else in that patch release I'll just go ahead with the upgrade.

**Comment by reasonerjt** [comment]
@nlowe 
Yes the only fix in 1.4.1 is the UAA bug fix.

There will be a few UI fixes going into 1.5.1 in a addition to the UAA fix.  I don't think you have to skip 1.5.0

**Comment by eymriseFrance** [comment]
Thanks hope I can make it...
