### ISSUE TITLE
Can not open details for own images on harbor

### ISSUE THREAD

**Issue by AlexZeitler** [vmware/harbor#49]
When I pull / push images from the Docker hub like ```ubuntu:14:04``` or  ```node:4.2.3``` and push them to harbor, everything works fine and I can see the images with their tags etc. inside the repositories.

If I publish my own images the same way, I get an error when clicking the image name inside the repository:

<!DOCTYPE html> <html> <head> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> <title>beego application error</title> <style> html, body, body * {padding: 0; margin: 0;} #header {background:#ffd; border-bottom:solid 2px #A31515; padding: 20px 10px;} #header h2{ } #footer {border-top:solid 1px #aaa; padding: 5px 10px; font-size: 12px; color:green;} #content {padding: 5px;} #content .stack b{ font-size: 13px; color: red;} #content .stack pre{padding-left: 10px;} table {} td.t {text-align: right; padding-right: 5px; color: #888;} </style> <script type="text/javascript"> </script> </head> <body> <div id="header"> <h2>registry:runtime error: index out of range</h2> </div> <div id="content"> <table> <tr> <td class="t">Request Method: </td><td>GET</td> </tr> <tr> <td class="t">Request URL: </td><td>/api/repositories/tags?repo_name=test/customerservice</td> </tr> <tr> <td class="t">RemoteAddr: </td><td>172.17.0.1</td> </tr> </table> <div class="stack"> <b>Stack</b> <pre>/usr/local/go/src/runtime/asm_amd64.s:437 /usr/local/go/src/runtime/panic.go:423 /usr/local/go/src/runtime/panic.go:12 /go/src/github.com/vmware/harbor/service/utils/registryutils.go:74 /go/src/github.com/vmware/harbor/api/repository.go:132 /usr/local/go/src/runtime/asm_amd64.s:437 /usr/local/go/src/reflect/value.go:432 /usr/local/go/src/reflect/value.go:300 /go/src/github.com/vmware/harbor/vendor/github.com/astaxie/beego/router.go:777 /usr/local/go/src/net/http/server.go:1862 /usr/local/go/src/net/http/server.go:1361 /usr/local/go/src/runtime/asm_amd64.s:1696 </pre> </div> </div> <div id="footer"> <p>beego 1.6.0 (beego framework)</p> <p>golang version: go1.5.1</p> </div> </body> </html>

**Comment by reasonerjt** [comment]
This looks like a bug, could you reproduce this issue and zip the latest log and attach to this issue?
The log should be available at /var/log/harbor by default.

**Comment by AlexZeitler** [comment]
@reasonerjt Thanks for your reply. Attached please find the logs.
[harbor.logs.tar.gz](https://github.com/vmware/harbor/files/191736/harbor.logs.tar.gz)

**Comment by stvolkov** [comment]
It's happing if repository name contains word "service"
testcase https://play.golang.org/p/NVdcyKO5Oz

To fix need in https://github.com/vmware/harbor/pull/60/files#diff-0dfe3281a64f72db168125d9965cb89aR70
change 

`if strings.Contains(s, "service") {`
`} else if strings.Contains(s, "scope") {`

to

`if strings.Contains(s, "service=\"") {`
`} else if strings.Contains(s, "scope=\"") {`

**Comment by reasonerjt** [comment]
Thanks @stvolkov !

**Comment by AlexZeitler** [comment]
Using b0bd7c4 this now works as expected even with `service` in the image name. :+1:
