### ISSUE TITLE
Jobservice doesn't support redis cluster

### ISSUE THREAD

**Issue by caiotedim** [vmware/harbor#4903]
On Harbor 1.5 when I use redis in cluster, the jobservice doesn't support it. Firing this error:

> 2018-05-09T20:45:44Z [ERROR] [service_logger.go:63]: Unlock key 'harbor_job_service_namespace:period:lock' failed with error: MOVED 8758 x.x.x.x:6379
> 2018-05-09T20:45:44Z [ERROR] [service_logger.go:63]: Clear outdated data before pool starting failed with error:MOVED 8758 x.x.x.x:6379
> 2018-05-09T20:45:44Z [INFO] Load 0 periodic job policies
> 2018-05-09T20:45:44Z [INFO] Periodic enqueuer is started
> 2018-05-09T20:45:44Z [INFO] Redis scheduler is started
> 2018-05-09T20:45:44Z [INFO] Subscribe redis channel harbor_job_service_namespace:period:policies:notifications
> 2018-05-09T20:45:44Z [ERROR] [service_logger.go:63]: periodic_enqueuer.should_enqueue:MOVED 5788 x.x.x.x:6379
> 2018-05-09T20:45:44Z [ERROR] [service_logger.go:63]: periodic_enqueuer.loop.enqueue:MOVED 5788 x.x.x.x:6379
> ERROR: write_known_jobs - MOVED 14881 10.147.38.15:6381
2018-05-09T20:45:44Z [INFO] Redis worker pool is started
> ERROR: periodic_enqueuer.should_enqueue - MOVED 5788 x.x.x.x:6379
> ERROR: worker.fetch - CROSSSLOT Keys in request don't hash to the same slot
> ERROR: worker.fetch - CROSSSLOT Keys in request don't hash to the same slot

Is there in backlog to correct this?!

**Comment by steven-zou** [comment]
Known issue. It's a limitation in 1.5. We have started the work to fix it. Please keep eyes on it.
Use existing issue #4633. Mark this one as duplicated and close it.
