### ISSUE TITLE
Add basic CI for Harbor Helm Chart

### ISSUE THREAD

**Issue by jessehu** [vmware/harbor#4931]
Setup a Jenkins job to detect harbor chart code change, then 
create the chart from source code, 
deploy the chart with default value (only need to specify Harbor FQDN) on an existing K8s cluster (can use Minikube to set up K8s cluster on a VM)
ensure 'docker login' and 'docker push/pull' work well
ensure https://harbor-fqdn/ is accessable
delete the chart.

We need to support at least 2 latest release of K8s, e.g. v1.9.x and v1.10.x as of 2018/5/11.

**Comment by reasonerjt** [comment]
Once there's a job extracted to run test cases against arbitrary Harbor instance, we can run almost all test cases against chart.

**Comment by ywk253100** [comment]
Done.
