### ISSUE TITLE
Use one single database for Harbor Helm Chart

### ISSUE THREAD

**Issue by jessehu** [vmware/harbor#4932]
This is described in https://github.com/kubernetes/charts/pull/3383. Once Harbor moves to the single database, so does Harbor Chart. Now Harbor Chart uses external postgresql chart to create postgresql database.

> There are a number of dependencies all bundled up here. MySQL, PostgreSQL, Clair, etc. Some of these could be deployed as their own chart (Clair, for example). Would you be interested in breaking this up and maybe using some of the good stuff you have here (e.g., StatefulSets) to improve some of the existing charts?

**Comment by ywk253100** [comment]
Done.
