### ISSUE TITLE
how to use harbor push/build image api? 

### ISSUE THREAD

**Issue by yaoice** [vmware/harbor#4951]

**Comment by stonezdj** [comment]
You can refer the [swagger.yaml](https://github.com/vmware/harbor/blob/master/docs/swagger.yaml)

**Comment by yaoice** [comment]
@stonezdj sorry, I can't find that. Could you give me an example?

**Comment by stonezdj** [comment]
https://github.com/vmware/harbor/blob/master/docs/swagger.yaml

**Comment by stonezdj** [comment]
你可以参考这个文档，配置如何使用swagger.yaml
https://github.com/vmware/harbor/blob/10199c10efe5dff3479ddc174e287b34cb39b306/docs/configure_swagger.md
