### ISSUE TITLE
Migration scripts to migrate data from MariaDB to pgSQL

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#4957]
this script is target to migrate v1.5.0 mysql to v1.5.0 pgsql, then to run the upgrade script to update scheme.

**Comment by wy65701436** [comment]
Done by PR: https://github.com/vmware/harbor/pull/5029

**Comment by reasonerjt** [comment]
There's some work needed to refine #5029, let's reopen this issue and assign it to sprint 35

**Comment by wy65701436** [comment]
As PR merged, close it.
