### ISSUE TITLE
DB migrator image to support pgsql schema upgrade.

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#4958]
currently, the DB migrator is for mysql schema. We need to investigate that how to support pgsql schema upgrading.

**Comment by wy65701436** [comment]
@ninjadq, please add the estimation.

**Comment by reasonerjt** [comment]
This is mainly a verification to ensure the current migrator based on alembic will work for pgsql, if not we need a solution in 1.6.0 timeframe.
