### ISSUE TITLE
Display issue with vulnerabilty data

### ISSUE THREAD

**Issue by bergtwvd** [vmware/harbor#4966]
Just upgraded from 140 to 150. I had vulnerability sanning on in 140, and now also in 150.
When I navigate to an image I get the error message ``We are unable to perform your action because internal server errors have occurred.``. I suspect this is because the vulnerabillty scan was done in 140 and the results of the scan in 140 do not show up in 150. When I redo the scan the error disappears.

There is however a display issue in the image data: the email address of the author is overlayed on top of the Architecture value (amd64).

**Comment by reasonerjt** [comment]
Verified the scan result over 1.4 -> 1.6 migration.
