### ISSUE TITLE
Deleting a tag deletes all tags if they point to the same image

### ISSUE THREAD

**Issue by isyarov** [vmware/harbor#4997]
Steps to reproduce:

1. Run harbor (i used the v1.5.0-rc5 offline installer)
2. On a docker host pull an image 
3. Tag the image for harbor with two different tags:
    docker tag harbor-ip/project-name/image:tag1
    docker tag harbor-ip/project-name/image:tag2
4. Push the two tags to harbor
5. Open the harbor ui and login
6. Navigate to the repository and see the two tags
7. Delete one of the tags
8. Validate the other tag is removed too

**Comment by ywk253100** [comment]
It's a limitation of docker registry. See #2663.

**Comment by xaleeks** [comment]
we are fixing this on https://github.com/goharbor/harbor/issues/2663 @isyarov
