### ISSUE TITLE
the Deploy folder name is should  lower-case

### ISSUE THREAD

**Issue by xiaods** [vmware/harbor#50]
we need follow a general convention to adjust the project layout. the lower-case is fine in linux culture. please consider it. thanks a lot.

**Comment by reasonerjt** [comment]
Thanks for the suggestion.  But we intentionally name it with a upper-case letter to inform user it's not a go package.

**Comment by xiaods** [comment]
Docker project use https://github.com/docker/docker/tree/master/contrib as folder name. you can consider it.

**Comment by liubin** [comment]
+1

**Comment by reasonerjt** [comment]
This is no longer valid as we don't have `deploy` folder anymore.
