### ISSUE TITLE
Fail to connet to slave harbor registry 

### ISSUE THREAD

**Issue by ZhengRongTan** [vmware/harbor#5017]
I have 2 harbor registry . when I building the replication, and test the connect , fail.

i have added the extra_hosts， but not effect . the log show it dial tcp 66.96.162.92:1080, but why ?

docker-compose.yml

ui:
image: vmware/harbor-ui:v1.3.0
container_name: harbor-ui
extra_hosts:
- "k8sregistry.domain.com:10.116.109.2"
- "bak1registry.domain.com:10.116.109.1"
- "bak2registry.domain.com:10.116.109.3"

logs:
May 21 16:42:50 172.18.0.1 ui[480267]: 2018-05-21T08:42:50Z [DEBUG] [security.go:231]: got user information from session
May 21 16:42:50 172.18.0.1 ui[480267]: 2018-05-21T08:42:50Z [DEBUG] [security.go:240]: using local database project manager
May 21 16:42:50 172.18.0.1 ui[480267]: 2018-05-21T08:42:50Z [DEBUG] [security.go:242]: creating local database security context...
May 21 16:42:50 172.18.0.1 ui[480267]: 2018-05-21T08:42:50Z [DEBUG] [tokenauthorizer.go:197]: scopses parsed from request:
May 21 16:42:52 172.18.0.1 ui[480267]: 2018-05-21T08:42:52Z [ERROR] [target.go:82]: failed to ping registry http://bak1registry.domain.com:1080: Get http://bak1registry.domain.com:1080/v2/: Get http://bak1registry.domain.com:1080/v2/: dial tcp 66.96.162.92:1080: getsockopt: network is unreachable
May 21 16:42:59 172.18.0.1 ui[480267]: 2018-05-21T08:42:59Z [DEBUG] [security.go:286]: user information is nil
May 21 16:42:59 172.18.0.1 ui[480267]: 2018-05-21T08:42:59Z [DEBUG] [security.go:300]: using local database project manager
May 21 16:42:59 172.18.0.1 ui[480267]: 2018-05-21T08:42:59Z [DEBUG] [security.go:302]: creating local database security context...

**Comment by steven-zou** [comment]
@ywk253100 please help to take a look. Seems the network is not reachable or the hostname bound to another ip?

**Comment by ywk253100** [comment]
The `bak1registry.domain.com` is a valid domain name on the Internet, you can try `ping bak1registry.domain.com`.

You need to find out why the `extra_hosts ` didn't work as expected. Run `docker run -it harbor-ui bash` to enter the harbor-ui container inside, and check whether the items are saved in`/etc/hosts`.

**Comment by ZhengRongTan** [comment]
Refer to https://github.com/vmware/harbor/blob/master/docs/installation_guide.md#configuring-harbor-listening-on-a-customized-port to customize the listening ports.

fixed!
