### ISSUE TITLE
support ignore event in notifications

### ISSUE THREAD

**Issue by klbjlabs** [vmware/harbor#5035]
## When will this feature can be support in Harbor？
* https://github.com/docker/distribution/pull/2501
* https://github.com/docker/distribution/commit/fc1d3647c6a148a0dbab2c6c4c20a2c1b7874bf2

In current version ( [v1.5.0](https://github.com/vmware/harbor/releases/tag/v1.5.0) ), The jobservice auto trigger so many pull events. (this morning I get 1000+ events post)

And if you click this button, you will get 82 pull events (The number depends on how many versions you have.). 
![default](https://user-images.githubusercontent.com/4111893/40480279-81a5634c-5f80-11e8-81c1-1c634e42ff8c.PNG)
[

**Comment by klbjlabs** [comment]
@steven-zou

**Comment by reasonerjt** [comment]
@klbjlabs 
1) The patch is not part of a released registry, I don't think we want to build the master branch to put it in Harbor' release.
2) I didn't have a chance to test, but if only filters out `application/octet-stream` mediatype it probably doesn't fix the problem you are seeing.  If it's configured to filter out all pull notifications the access log will not work.

Do you see any perf issues when there are many events?  I suggest you patch Harbor with latest registry code and manually edit config.yml for now.
