### ISSUE TITLE
Harbor can not copy images form itself to the other harbor when changing nginx port from 80 to any other port.

### ISSUE THREAD

**Issue by LELEFIVE** [vmware/harbor#5038]
## 1)Version of docker engine and docker-compose.
**$ docker version**
~~~
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-58.git87f2fab.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      87f2fab/1.13.1
 Built:           Fri May 11 14:30:13 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-58.git87f2fab.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      87f2fab/1.13.1
 Built:           Fri May 11 14:30:13 2018
 OS/Arch:         linux/amd64
 Experimental:    false
~~~
**$ docker-compose version**
~~~
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.7.0
CPython version: 2.7.5
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
~~~
**harbor version**   
harbor-offline-installer-v1.5.0.tgz

## 2)Config files of harbor
**harbor.cfg**
I only change the"hostname = 172.30.66.28:5000"
and "project_creation_restriction = adminonly"
**docker-compose.yml**
I only change the nginx 80 port to 5000.
~~~
  proxy:
    image: vmware/nginx-photon:v1.5.0
    container_name: nginx
    restart: always
    volumes:
      - ./common/config/nginx:/etc/nginx:z
    networks:
      - harbor
    ports:
      - 5000:80
~~~
**other files change nothing.**

## 3)errors
the main error is like this:
~~~
2018-05-25T02:03:43Z [INFO] initialization completed: repository: deployment1/registry, tags: [latest], source registry: URL-http://172.30.66.28:5000 insecure-true, destination registry: URL-http://172.20.36.217 insecure-true
2018-05-25T02:03:44Z [ERROR] [job_logger.go:81]: failed to get project deployment1 from source registry: Get http://172.30.66.28:5000/api/projects?name=deployment1: dial tcp 172.30.66.28:5000: getsockopt: no route to host
~~~
harbor logs are all here:  
[harborlog.tar.gz](https://github.com/vmware/harbor/files/2037682/harborlog.tar.gz)

Is this a bug? please help me. Thank you!

**Comment by ywk253100** [comment]
It seems that your issue is not caused by the customized port according to the log:
`dial tcp 172.30.66.28:5000: getsockopt: no route to host`.
You should make sure the host `172.30.66.28` is reachable inside the jobservice contianer.

**Comment by LELEFIVE** [comment]
@ywk253100 
After changing the port to 5000, every function of Harbor works well, only this function can not work.

**Comment by ywk253100** [comment]
As I mentioned above, please make sure the host `172.30.66.28` is reachable inside the jobservice contianer.

**Comment by LELEFIVE** [comment]
@ywk253100 
yes, it can not access 172.30.66.28.
Then how to solve this problem in the job-service container?

**Comment by LELEFIVE** [comment]
I only change the config files according to Vmvare Harbor of how to change port 80. After setup, the job service can't access the local ip.  Why does this happen? I need help.

**Comment by LELEFIVE** [comment]
I have solved this problem.
method:
Firstly,  setup Harbor by default.  
Secondly, 
~~~
docker-compose stop
~~~
Thirdly, change 80 port according to the Harbor indicator.
~~~
. install.sh
~~~
Finished!

**Comment by LELEFIVE** [comment]
I have solved this problem. Maybe it's Harbor's install.sh is not very exactly, I doesn't look deep into it.
Please refer to my last comment.
