### ISSUE TITLE
Replication job doesn't give the exactly http error code throwed by job service.

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#5043]
My replication job log is not find by job service, but the /api/jobs/replication/ gives a 500. See the log below.

From the code:
logBytes, err := utils.GetJobServiceClient().GetJobLog(job.UUID)
if err != nil {
	ra.HandleInternalServerError(fmt.Sprintf("failed to get log of job %s: %v",
		job.UUID, err))
	return
}

Any http error will be wrapped to HandleInternalServerError. Is it a by design scenario?

May 28 03:43:11 172.18.0.1 ui[1778]: 2018-05-28T10:43:11Z [ERROR] [base.go:88]: failed to get log of job : http error: code 404, message {"code":10013,"message":"object is not found","details":"job 'log'"}

May 28 03:43:11 172.18.0.1 ui[1778]: 2018/05/28 10:43:11 #033[1;44m[D] [server.go:2619] |   10.166.17.43|#033[41m 500 #033[0m|  12.891041ms|   match|#033[44m GET     #033[0m /api/jobs/replication/1/log   r:/api/jobs/replication/:id([0-9]+)/log#033[0m

**Comment by ywk253100** [comment]
Dup of #5047, closing this one.
