### ISSUE TITLE
Longer repository names are not displayed correctly in card view

### ISSUE THREAD

**Issue by isyarov** [vmware/harbor#5045]
Longer repository names are weirdly truncated when viewed in card-view.

Steps to reproduce:
1. Create a project, i used the name **some-project**
2. Tag some images for the project with long paths and push them. I used:
**{harbor-ip}/some-project/some-path/some-image**
**{harbor-ip}/some-project/somepath/someimage**
3. Open the project repositories in card-view and verify the repositories names are truncated

Repository names are differently truncated depending on the browser. (See the screenshots below)
The truncation seems to happen on a **-** (dash) or on a **/** (forward slash) symbol
The html tag contains the full repository name
To reproduce i used the [harbor 1.5.0 offline installer](https://storage.googleapis.com/harbor-releases/release-1.5.0/harbor-offline-installer-v1.5.0.tgz)
![list-view](https://user-images.githubusercontent.com/36737126/40613847-e949e3e6-6288-11e8-8106-272515e1312b.png)
![card-view-chrome](https://user-images.githubusercontent.com/36737126/40613985-7078e2a4-6289-11e8-8484-e5ec8d03f618.png)
![card-view-firefox](https://user-images.githubusercontent.com/36737126/40613986-70993612-6289-11e8-9ed6-d70124ca4926.png)

**Comment by wy65701436** [comment]
Thanks for raising, @ninjadq please have a look.

**Comment by zhoumeina** [comment]
fixed by #5045
