### ISSUE TITLE
Get internal error when to view job log after success upgrading to latest release.

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#5047]
As the new implementation of job service, the log path has changed which lead to the internal error when to view job log after updating from the previous releases.

[Impact]
The user who upgrades from the previous releases. 

[Workaround]
NA

It should be documented in release notes.

**Comment by wy65701436** [comment]
@sigsbee  please consider it in the upgrade auto test.

**Comment by ywk253100** [comment]
It's a known limitation that the job log cannot be viewed after upgrading, but the 500 error should not be returned. 
Can you upload the logs?

**Comment by wy65701436** [comment]
for the log, just refer to https://github.com/vmware/harbor/issues/5043.
