### ISSUE TITLE
Unexpected database schema version. when starting adminserver.

### ISSUE THREAD

**Issue by mJace** [vmware/harbor#5048]
I was installing harbor v1.5 by docker-compose.  
but I received an error during the initial state of adminserver, which says   

> [FATAL] [main.go:46]: failed to initialize the system: unexpected database schema version, expected 1.5.0, got 0.4.0

Even if I changed to harbor v1.4 the problem still exists, only the error message change from version 1.5.0 to 1.4.0.
I would like to ask what's this version about?
How do I update this?

```
docker engine : 17.09.0-ce, build afdb6d4
docker-compose :  1.21.2, build a133471
```

[cfgLog.zip](https://github.com/vmware/harbor/files/2047094/cfgLog.zip)

**Comment by mJace** [comment]
I leave the hostname unchanged, because I don't have dns or hostname setup for harbor/ui container.
Instead, I edit my /etc/hosts for the default hostname reg.yourdomain.com to the IP of harbor/ui container.  

I did't alter the redis_url filed , what is its default value?

[harborLog.zip](https://github.com/vmware/harbor/files/2047573/harborLog.zip)

**Comment by wy65701436** [comment]
Is it a fresh install or upgrade from previous release? Please tell what you did.

**Comment by mJace** [comment]
It's fresh install, I followed the instruction from https://github.com/vmware/harbor/blob/master/docs/installation_guide.md 
and I only change the harbor.cfg for these fields on v1.5 and v1.4, just same as [here] (https://github.com/vmware/harbor/blob/master/docs/configure_https.md) shows.
```
  #set hostname
  hostname = reg.yourdomain.com
  #set ui_url_protocol
  ui_url_protocol = https
  ......
  #The path of cert and key files for nginx, they are applied only the protocol is set to https 
  ssl_cert = /root/cert/yourdomain.com.crt
  ssl_cert_key = /root/cert/yourdomain.com.key
```
Here is my harbor.cfg of version 1.5, 
[harbor1.5.txt](https://github.com/vmware/harbor/files/2052052/harbor1.5.txt)

I've tried v1,5 and v1,4, but they both pop up the same database error the starting adminserver.

**Comment by ywk253100** [comment]
There should be some old data in your environment. Harbor checks the version of database scheme when starting up. So try to clean the data directory(`/data` by default) and try again.

**Comment by mJace** [comment]
@ywk253100  Indeed! after I clean the `/data`, and start over again. harbor just works fine.
It would be helpful if the error message can tell user to check if there is any old file in `/data` .

**Comment by ywk253100** [comment]
Great.
