### ISSUE TITLE
The installer fails with Python 3

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#5053]
the installer fails with Python 3 because they changed the way to handle strings.

Traceback (most recent call last):
  File "./prepare", line 398, in <module>
    [storage_provider_name + ':'] + map(string.strip, storage_provider_config.split(",")))
AttributeError: module 'string' has no attribute 'strip'

**Comment by CHIP0K** [comment]
```
Traceback (most recent call last):
  File "./prepare", line 406, in <module>
    [storage_provider_name + ':'] + map(string.strip, storage_provider_config.split(",")))
AttributeError: module 'string' has no attribute 'strip'
```
harbor-offline-installer-v1.5.2.tgz
harbor-online-installer-v1.5.2.tgz
