### ISSUE TITLE
harbor ui, still call clair API when clair not installed

### ISSUE THREAD

**Issue by QuSongtao** [vmware/harbor#5055]
harbor ui oper: 
Projects > Repositories > library/myimage > images > mytag
![image](https://user-images.githubusercontent.com/15939134/40704372-769e00b4-641a-11e8-84e1-36c8ad402823.png)

the http request info:

Request URL: http://192.168.2.136/api/repositories/library/mysql/tags/5.7/vulnerability/details
Request Method: GET
Status Code: **503 Service Unavailable**
Remote Address: 192.168.2.136:80
Referrer Policy: no-referrer-when-downgrade

harbor version:  1.5.0
docker version:
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false

docker-compose version:   docker-compose version 1.21.2, build a133471

in harbor.cfg, I only change the hostname

I can not find any help by check the logs in '/var/log/harbor' ,who can help me ,thranks!

**Comment by wy65701436** [comment]
Please help to upload the logs and harbor.cfg, and did you install the clair component?

**Comment by QuSongtao** [comment]
thanks @wy65701436 
I didn't install the clair component before, just run `{harbor_path}/install.sh`. 
now I re-install it by `{harbor_path}/install.sh --with-clair`  have resolved this problem, but there is a warn in the repositories list page.
![image](https://user-images.githubusercontent.com/15939134/40716221-c5689d56-643a-11e8-9d30-fbdaafbfdb37.png)

backend status is:
![image](https://user-images.githubusercontent.com/15939134/40716271-f71e0a3e-643a-11e8-854d-e7c2c3c01c26.png)
what is wrong with this,though not effect use it.
虽然不影响使用,但是为什么呢,总觉得有警告不爽.

**Comment by wy65701436** [comment]
The warning is to tell the Clair dB is not ready yet. Actually, it’s pull data in the backend and it needs several hour to be finished, and the warning will be disappeared once it done.

**Comment by ywk253100** [comment]
The tag should not be clicked when installing Harbor without Clair. 
@ninjadq Please check the UI code. This works well in 1.4.

**Comment by ywk253100** [comment]
@QuSongtao There is a bug in Harbor, let's keep the issue open to track it Thank you for your reporting.

**Comment by zhoumeina** [comment]
Fixed in #5372

**Comment by kpiedvelop** [comment]
Hello, 
I have the same error. Is there any solution without installing clair?

Thanks a lot.

**Comment by kpiedvelop** [comment]
@clouderati i have wiped all harbor cookies and bypassed the cacke.... The issue is the same..... Any other idea?

**Comment by clouderati** [comment]
Hi @kpiedvelop – not completely certain. @zhoumeina can you ptal?

**Comment by hack0072008** [comment]
Hello,
I have the same error. Is there any solution without installing clair?
(Note: I was installed harbor which version is v1.5.3 release  of offline with out installing clair)

Thanks a lot.

**Comment by kpiedvelop** [comment]
@hack0072008 here is the current issue: [https://github.com/goharbor/harbor/issues/5975](url)

**Comment by hack0072008** [comment]
> @hack0072008 here is the current issue: [https://github.com/goharbor/harbor/issues/5975](url)

when i try to clean the cookie and login again, the error still exist, do you know the reason?

**Comment by kpiedvelop** [comment]
I have the same problem, too

**Comment by kpiedvelop** [comment]
@hack0072008 look at the referenced issue #5975
