### ISSUE TITLE
Limite CPU usage for Clair as it's performance issue

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#5072]
See https://github.com/coreos/clair/issues/548 to get details, before it's resolved, we have to add the limitation of CPU usage on Clair.

Can refer to: https://github.com/vmware/vic-product/pull/1813

**Comment by clouderati** [comment]
Would be nice to have a fix for this in non-VIC deployments. Can we also see about `nicing` the container or (less preferred) limiting its CPU utilization?

**Comment by reasonerjt** [comment]
Does `nicing` require certain configuration in kernel?
