### ISSUE TITLE
docker login harbor failed with 502 Bad Gateway

### ISSUE THREAD

**Issue by charlesgogo01** [vmware/harbor#5081]
[harborlog.zip](https://github.com/vmware/harbor/files/2067535/harborlog.zip)
docker login 49.4.11.187
Username: admin
Password:
Error response from daemon: login attempt to http://49.4.11.187/v2/ failed with status: 502 Bad Gateway

#This attribute is for migrator to detect the version of the .cfg file, DO NOT MODIFY!
_version = 1.5.0
#The IP address or hostname to access admin UI and registry service.
#DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
hostname = 49.4.11.187

#The protocol for accessing the UI and token/notification service, by default it is http.
#It can be set to https if ssl is enabled on nginx.
ui_url_protocol = http

#Maximum number of job workers in job service
max_job_workers = 50

**Comment by wy65701436** [comment]
please upload harbor logs.

**Comment by charlesgogo01** [comment]
I have update the log,thanks very much for your help

**Comment by charlesgogo01** [comment]
@ywk253100  can you help me?

**Comment by ywk253100** [comment]
According to the logs `panic: No region parameter provided`, seems that you didn't configure the storage of registry correctly.
