### ISSUE TITLE
docker-compose up error

### ISSUE THREAD

**Issue by duyanghao** [vmware/harbor#509]
with docker 1.10+,docker-compose 1.6.2,python 2.7.3
when i run the command: `docker-compose up`
then error appears below:
```
Creating network "deploy_default" with the default driver
ERROR: failed to parse pool request for address space "LocalDefault" pool "" subpool "": could not find an available predefined network
```

**Comment by reasonerjt** [comment]
Hi, are you using vpn?

https://github.com/docker/libnetwork/issues/779

**Comment by duyanghao** [comment]
no,I am not using vpn!
the docker can start successfully!
but the docker-compose up fails!

**Comment by duyanghao** [comment]
another error:
```
[root@sa1 ~/HARBOR_dir/harbor]# docker-compose up 
Starting harbor_log_1
ERROR: Cannot start container 0e895de1f98b7b448074f76727fe473c69285e26597b817180ba89d15a78642e: [0] Id already in use: container with id exists: 0e895de1f98b7b448074f76727fe473c69285e26597b817180ba89d15a78642e
```

**Comment by duyanghao** [comment]
another question:
what is your registry token authentication server? 
Is it the  `cesanta/docker_auth`?
https://github.com/cesanta/docker_auth
or any other token authentication server project?

**Comment by reasonerjt** [comment]
No, we write our own token generator.

**Comment by reasonerjt** [comment]
As for the error in your previous comment, please try 
"docker-compose down" then "docker-compose up -d" again.
I find sometimes the container won't exit after the introduction of containerd, didn't dig into it though.

**Comment by duyanghao** [comment]
Do you mean that you self achieved the registry token authentication server(like docker_auth)?
Could we get it from github? @reasonerjt

**Comment by reasonerjt** [comment]
I haven't checked docker_auth it's probably more comprehensive
it's under /service/token/

**Comment by reasonerjt** [comment]
@duyanghao 
Do we need to leave this issue open?

**Comment by duyanghao** [comment]
no, thank for your reply! @reasonerjt
