### ISSUE TITLE
Got error when checking vulnerabilities of an image after upgrading to PGSQL

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#5097]
<img width="1676" alt="scan_detail" src="https://user-images.githubusercontent.com/5835782/40962432-10d40022-68d8-11e8-8300-1fa3f5c6f358.png">

Even though  the Clair data gets ready, still got the same error:
```
Jun  5 00:46:02 172.18.0.1 ui[1065]: 2018-06-05T07:46:02Z [ERROR] [base.go:88]: Failed to get scan details from Clair, error: Unexpected status code: 404, text: {"Error":{"Message":"the resource cannot be found"}}
```

Rescan can fix this.

**Comment by wy65701436** [comment]
It's a know issue as we didn't migrate clair DB. As @ywk253100 mentioned, user can fix it by re-scan.

It should be document.

**Comment by wy65701436** [comment]
fixed.
