### ISSUE TITLE
Harbor should expose REST api to interacting with 3rd application

### ISSUE THREAD

**Issue by xiaods** [vmware/harbor#51]
just list docker server, we would like the harbor can serv a rest api to interact with 3rd app. it's fine to do integration work

**Comment by hainingzhang** [comment]
@xiaods Could you explain what this API is for? What docker server to be listed?

**Comment by xiaods** [comment]
just like here: https://ciscoshipped.io/shipped/api-docs/build/index.html#api-reference

**Comment by hainingzhang** [comment]
We have a swagger page for the API. Does that help in any way? 
https://github.com/vmware/harbor/blob/master/docs/configure_swagger.md

**Comment by xiaods** [comment]
i will update more details requirement on it.
