### ISSUE TITLE
Harbor can not start up after upgrading from 1.2 to the latest version

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#5100]
Set up Harbor with `root` user and after upgrading 1.2 to the latest version the adminserver can not start up due to permission issue:
`Jun  5 01:16:40 172.18.0.1 adminserver[1065]: 2018-06-05T08:16:40Z [FATAL] [main.go:46]: failed to initialize the system: open /etc/adminserver/key: permission denied`

**Comment by wy65701436** [comment]
it should be introduced by v1.5.0, and impact the upgrade scenario.

**Comment by reasonerjt** [comment]
This is impacts only `master` not v1.5
Fixed by #5111
