### ISSUE TITLE
LDAP error message incomplete

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#5101]
Version v1.5.0-bf6192f3

when test ldap server, if the configuration is not correct, there will be an error message, but the message seems incomplete, remove the colon or complete the message.
![colon](https://user-images.githubusercontent.com/23101283/41018924-f10fc372-698e-11e8-8274-5bf5c2b48b34.PNG)

**Comment by ninjadq** [comment]
UI fixed, but  api shouldn't response a 500 error when test failure

**Comment by reasonerjt** [comment]
@ninjadq Is it fixed?

**Comment by reasonerjt** [comment]
This is fixed.
