### ISSUE TITLE
Confusing UI code in  ui_ng/lib/src/i18n/translate.spec.ts

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#5122]
https://github.com/vmware/harbor/blob/master/src/ui_ng/lib/src/i18n/translate.spec.ts

I occationally found in this file there seems to be a variable `localI18nMessageVariableMap` which has only English and Chinese, however in the real env there are other language options.

Is the code in this file obsolete?

**Comment by steven-zou** [comment]
en and ch are officially supported, others are from the community, so they're not included in the test cases. Let's keep it as it was until there are new requirements incoming
