### ISSUE TITLE
Refine the group management dialog

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#5128]
In `add group` dialog there should be more tips to inform user that the group name is optional, if it's left empty the `gid` will be used as group name.
Should refine the labels and messages to explicitly tell user the group is to be imported, in contrast to added.

**Comment by lweitzman** [comment]
I don't think we need a signpost to help the user understand that the name is optional. It should get filled in automatically when the Group DN is filled in. the only required field is designated by the red asterisk (*)

![screen shot 2018-06-13 at 1 27 41 pm](https://user-images.githubusercontent.com/626032/41367651-a5daa104-6f0d-11e8-928e-10b50163ac94.png)

**Comment by stonezdj** [comment]
I will create a REST API to check the GroupDN is valid and retrieve its group name in LDAP. see
#5145
