### ISSUE TITLE
Make the port of ingress controller configurable in helm chart

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#5133]
The default NodePort range for service in k8s is 30000-32767. When creating an ingress controller using NodePort, a random port in this range rather than 80/443 will be allocated. In this case, the docker and notary commands will fail. 
The root cause is that the authentication service configured in the config files of registry and notary server is the externalDomain in the value.yaml, and it doesn't contain the port of ingress controller.

**Comment by reasonerjt** [comment]
Isn't NodePort is selected randomly?

**Comment by ywk253100** [comment]
The NodePort used by a service can be specified, or it will be allocated a random one from the port range.
