### ISSUE TITLE
Correct the ingress rules in helm chart

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#5134]
```
/ -> /ui/
/v2 -> /ui/registryproxy/v2/
/service/notifications -> 404
```

**Comment by reasonerjt** [comment]
Did a little investigation seems re-writing the path for ingress is a little tricky.

**Comment by reasonerjt** [comment]
move to sprint 37 as we need to do more investigation for the best way to do the `target-rewrite`

**Comment by ywk253100** [comment]
Done with #5177.
