### ISSUE TITLE
netstat / nc / telnet commands not enabled on images running in Harbor

### ISSUE THREAD

**Issue by deshab** [vmware/harbor#5144]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
3)Log files, you can get them by package the /var/log/harbor/ .

**Comment by reasonerjt** [comment]
This is working as designed, you can modify the Dockerfile, or use `docker exec` to enter the container and use `tdnf install` to install the software packages.
