### ISSUE TITLE
Incorrect error message when the project name is non-exist.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#5156]
The current error message is `Please add a project name first`

![image](https://user-images.githubusercontent.com/2390463/41453156-3584e2c0-70a7-11e8-9986-a779be80c89a.png)

**Comment by lweitzman** [comment]
also, this shouldn't be displayed below the input field. it should use the standard form validation error handling by putting an alert on the right side of the input field. 

![screen shot 2018-06-15 at 8 33 25 am](https://user-images.githubusercontent.com/626032/41468120-d95879ce-7076-11e8-9b8d-23d018a6bd71.png)

**Comment by zhoumeina** [comment]
fixed by #5397
