### ISSUE TITLE
swagger config not compatible with 1.5.0

### ISSUE THREAD

**Issue by drduker** [vmware/harbor#5168]
Many of the API objects are not working.  For example the project create isn't working.  I've noticed the version for swagger at https://raw.githubusercontent.com/vmware/harbor/master/docs/swagger.yaml has not been updated from 1.4.0 to 1.5.0.  Without this update fully configuring this application is not possible in an automated way.

When will there be an update to this file that fixes this broken swagger file?  Using the python harborclient isn't an option because it does not have the ability to modify members of a project.  Only view members.

If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
latest version
2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
3)Log files, you can get them by package the /var/log/harbor/ .

**Comment by steven-zou** [comment]
@ywk253100 Plese confirm if the swagger file is outdated. If yes, let's make a plan to update it. Thanks
