### ISSUE TITLE
Harbor tile for PKS missing "Project Creation" Dropdown

### ISSUE THREAD

**Issue by nvpnathan** [vmware/harbor#5174]
When configuring AD integration with Harbor with the PKS tile we need the option to change the "Project Creation" from "Everyone" to "Admin".

**Comment by clouderati** [comment]
Thanks @nvpnathan.

@reasonerjt – can we please try to get this into the next release? @nvpnathan reminded me that we lock out the Harbor config if deployed via tile, so without surfacing this toggle we're pretty much forcing a user to accept the default behavior.

Thanks!

**Comment by steven-zou** [comment]
@stonezdj should be the right person to fix it.

**Comment by reasonerjt** [comment]
@clouderati User can login as admin and update the configuration via Harbor's UI, so he's not blocked.
So this is an improvement to expose this configuration on tile.

**Comment by clouderati** [comment]
@nvpnathan – I believe you mentioned that you were unable to change the setting after deployment. Can you please confirm?

**Comment by stonezdj** [comment]
Because harbor UI already provide this feature, there is no need to add this configure to harbor tile.
