### ISSUE TITLE
Add support to assign administration access based on LDAP group / acl

### ISSUE THREAD

**Issue by GrantKlassy** [vmware/harbor#5178]
In #1305 and #3115 requests were made to be able to assign project level permissions based on LDAP groups. It seems like this is currently being worked on in #3506. However, I was surprised to see that no one had requested the ability to assign harbor administrator access based on an LDAP group / acl.

For instance, in harbor.cfg there could be a setting "ldap_admin_acl". When a user with that acl logs in through the web UI, they would get access to the "Administration" tab on the left side and all of the privileges that come along with it.

Thanks

**Comment by reasonerjt** [comment]
@stonezdj please dup.

**Comment by stonezdj** [comment]
duplicated with #4828, close
