### ISSUE TITLE
Docker login fail with helm installed harbor.

### ISSUE THREAD

**Issue by mJace** [vmware/harbor#5191]
Docker :  18.03.1-ce, build 9ee9f40
Minikube version: v0.28.0
Helm : "v2.9.1"

I followed the helm installation guide on master branch commit e51d6cc707c83e9eea36ece0d2f9d66b1a71fac8
The Harbor web works fine, but when I try to login the registry it return me some error like this.

```bash
sudo docker login harbor.my.domain
Username (admin): admin
Password:
Error response from daemon: Get https://harbor.my.domain/v2/: Get https://harbor.my.domain:32700/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: dial tcp 192.168.99.100:32700: getsockopt: connection refused
```

And here's the error part of the log of registry pod

```bash
kubectl log my-release-harbor-registry-0
172.17.0.7 - - [26/Jun/2018:09:01:50 +0000] "GET /v2/_catalog?n=1000 HTTP/1.1" 200 20 "" "Go-http-client/1.1"
time="2018-06-26T09:04:37.249138662Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.3 http.request.host=harbor.my.domain http.request.id=4e4f44aa-8933-44fc-a726-e153413d41ad http.request.method=GET http.request.remoteaddr=192.168.99.1 http.request.uri="/v2/" http.request.useragent="docker/18.03.1-ce go/go1.9.5 git-commit/9ee9f40 kernel/4.4.0-128-generic os/linux arch/amd64 UpstreamClient(Docker-Client/18.03.1-ce \\(linux\\))" instance.id=e11bfd4c-b6e7-4443-9dae-3ff808b53b0d service=registry version=v2.6.2
172.17.0.7 - - [26/Jun/2018:09:04:37 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/18.03.1-ce go/go1.9.5 git-commit/9ee9f40 kernel/4.4.0-128-generic os/linux arch/amd64 UpstreamClient(Docker-Client/18.03.1-ce \\(linux\\))"
```

I even tried the commit dd4c565aff34a941db2c4c2113b0e313ba76a3e1 
but also, same error happened.  

BTW, I was able to run harbor helm about 2 weeks ago with commit c13f2f6948c32738d1b5c48b417ce5c80327e950  
Both website and the docker CLI works fine in this old version.

**Comment by ywk253100** [comment]
Leave the `externalPort ` empty if your ingress controller is bound to port 80/443 in values.yaml https://github.com/vmware/harbor/blob/master/contrib/helm/harbor/values.yaml#L38.

**Comment by mJace** [comment]
This note might added to the installation guide of the helm since it's default environment is based on minikube, which's ingress controller is bound to port 80/443.

**Comment by ywk253100** [comment]
Open #5297 to track the doc issue. Closing this one.
