### ISSUE TITLE
new policy issue in the  project

### ISSUE THREAD

**Issue by rusirenye** [vmware/harbor#520]
when new policy in the project, we checked new destination checkbox to create a new destination. we find that we can create the same endpoint by different user and destination name,  but it should't be allowed.
@wknet123

**Comment by reasonerjt** [comment]
You could create duplicate endpoints under same project or different?

**Comment by rusirenye** [comment]
we test situation is under the same project

**Comment by reasonerjt** [comment]
@ywk253100 should we check it on API?

**Comment by ywk253100** [comment]
I will check it.
