### ISSUE TITLE
Local Events dialog doesn't work

### ISSUE THREAD

**Issue by stonezdj** [vmware/harbor#5202]
1. The layout is wrong, event content is stricken through by line
2. When clicking Running, failed table, the table should switch to the different event categories

**Comment by stonezdj** [comment]
![screen shot 2018-06-28 at 4 08 03 pm](https://user-images.githubusercontent.com/2696760/42021807-2a434a5e-7aee-11e8-8717-7add28930d36.png)

**Comment by reasonerjt** [comment]
@ninjadq please verify and close if it's fixed.
