### ISSUE TITLE
docker-compose.yaml:  wrong redis volume setting ?

### ISSUE THREAD

**Issue by kulong0105** [vmware/harbor#5208]
Hi, 

when i check the docker-compose.tpl file (https://github.com/vmware/harbor/blob/master/make/docker-compose.tpl), i find a issue about the volume configuration for redis, the content is below:
```
redis:
    image: vmware/redis-photon:__redis_version__
    container_name: redis
    restart: always
    volumes:
      - /data/redis:/data             <======
    networks:
      - harbor
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "redis"
```

i try to start the redis container, and check the config file for redis server, like below:
```
$ cat /etc/redis.conf
....
# The working directory.
# The DB will be written inside this directory, with the filename specified
# above using the 'dbfilename' configuration directive.
# The Append Only File will also be created inside this directory.
# Note that you must specify a directory here, not a file name.
dir /var/lib/redis        <======
```

the redis container use "/var/lib/redis" to store data, not "data" directory.
so this is a wrong configuration in docker-compose.tpl file?

**Comment by kulong0105** [comment]
@steven-zou  ping, please help confirm this  issue

**Comment by kulong0105** [comment]
Sure， I submit a PR before, and not get response for several days (https://github.com/vmware/harbor/pull/5224)

i just updated the config file, and push to my repo.
i need to close the previous PR, and file a new PR ? since i cannot create a new PR for this issue for now.

BTW: i am not familiar with github PR mechanism :)

**Comment by steven-zou** [comment]
@kulong0105 

Seems #5171 is not related to this issue. Would you please raise a new PR to fix only this bug?

**Comment by kulong0105** [comment]
@steven-zou 

done,  https://github.com/vmware/harbor/pull/5246

**Comment by steven-zou** [comment]
Merged. Close this issue. Thanks @kulong0105
