### ISSUE TITLE
Project publicity changed when sync to the destination

### ISSUE THREAD

**Issue by wemeya** [vmware/harbor#521]
When I sync a public project to the destination, it changed to private. See below:
src: ![image](https://cloud.githubusercontent.com/assets/12540577/16766770/88990b02-486e-11e6-99ee-9e8f704c80e7.png)
dst: ![image](https://cloud.githubusercontent.com/assets/12540577/16766777/98668050-486e-11e6-885b-20b2c821eff2.png)

**Comment by reasonerjt** [comment]
@ywk253100 I think this is the design decision?  Maybe we want to mention that in doc?

**Comment by ywk253100** [comment]
Maybe we can keep the publicity of destination project same with source, I will fix it.

**Comment by reasonerjt** [comment]
ok thanks!

**Comment by wemeya** [comment]
fixed after check, closed.
