### ISSUE TITLE
Can harbor helm now running without ingress?

### ISSUE THREAD

**Issue by mJace** [vmware/harbor#5212]
I saw a commit in master about to disable ingress in helm of harbor.  
so, I tried this on my minikube. But somehow the registry could not be logged in successfully.  

> Minikube version:  v0.28  
k8s: v1.10  
helm: v2.9.1  
git version : master - 7d6f8f9

minikube ingress addon disabled  
```bash
> minikube addons list
- addon-manager: enabled
- coredns: disabled
- dashboard: enabled
- default-storageclass: enabled
- efk: disabled
- freshpod: disabled
- heapster: disabled
- ingress: disabled
- kube-dns: enabled
- metrics-server: disabled
- registry: disabled
- registry-creds: disabled
- storage-provisioner: enabled

```

turn off ingress my values.yml 
```yaml
# These annotations allow the registry to work behind the nginx
# ingress controller.
ingress:
  enabled: false
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
```

and to access the ui and registry pod I add the nodePort in their svc.yml  
**ui-svc.yml**  
```yaml
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.fullname" . }}-ui"
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30020
      targetPort: 8080
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: ui
```  

**registry-svc.yaml**
```yaml
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.fullname" . }}-registry"
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30010
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: registry
```

After helm installation, the webUI works normally.
but when I login to registry.....
```bash
sudo docker login harbor.my.domain:30010
Username (admin): admin
Password: 
Error response from daemon: Get https://harbor.my.domain:30010/v2/: http: server gave HTTP response to HTTPS client
```

Which is odd, since I didn't set up the insecure mode in values.yml
But still, I added an insecure exception in my docker daemon.json and restart docker daemon.

And then try to login again.
```bash
sudo docker login harbor.my.domain:30010
Username (admin): admin
Password: 
Error response from daemon: Get http://harbor.my.domain:30010/v2/: Get https://harbor.my.domain:32700/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: dial tcp 192.168.99.100:32700: getsockopt: connection refused
```

And it seems like external port setting issue, so I clean the externalPort in values.yml
```yaml
# The FQDN for Harbor service.
externalDomain: harbor.my.domain
# externalPort is the Port for Harbor service, leave empty if the service is to be bound to
# port 80/443
externalPort: 
```

and login again...  still unsuccess.
```bash
sudo docker login harbor.my.domain:30010
Username (admin): admin
Password: 
Error response from daemon: Get http://harbor.my.domain:30010/v2/: Get https://harbor.my.domain:443/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: dial tcp 192.168.99.100:443: getsockopt: connection refused
```

Is there anything I did wrong or miss?

**Comment by ywk253100** [comment]
Set the `externalPort = 30020 `. There is a token service in UI container that the docker client will connect to.

BTW, why don't you use the ingress of minikube?

**Comment by mJace** [comment]
Thank you. I will try to set externalPort to 30020.
Our environment is a bear metal k8s without ingress support, so I try to setup harbor by helm without ingress in minikube first.

**Comment by mJace** [comment]
Ok, it seems like I can just add a nodePort to UI container ,eg. 30020
and set externalPort to 30020, then docker login to harbor.my.domain:30020 right?
But I get an error response like this, even if I didn't set up insecure mode.
```
sudo docker login https://harbor.my.domain:30020
Username: admin
Password: 
Error response from daemon: Get https://harbor.my.domain:30020/v2/: http: server gave HTTP response to HTTPS client  
```
And when I add insecure exception to daemon.json 
```bash
sudo docker login harbor.my.domain:30020
Username: admin
Password:
Error response from daemon: login attempt to http://harbor.my.domain:30020/v2/ failed with status: 404 Not Found
```

**Comment by reasonerjt** [comment]
@mJace 
The ingress serves as a LB, the `ingress.enable` attribute was introduced for users who wants to setup their own LB.
So by default the ingress is a must.

**Comment by mJace** [comment]
Ok thank you. 
If you don't might, does harbor rely on ingress to do the TLS termination?

**Comment by reasonerjt** [comment]
correct
