### ISSUE TITLE
Sync error: tag the same image with lots of tags, can't see all the tags in destination 

### ISSUE THREAD

**Issue by wemeya** [vmware/harbor#522]
I tagged the hello-world from 1 to 100, and pushed them to the source host.  It displayed correctly in the UI of the source host. Also, I can see a lot of sync records. However, when I turned to the UI of the destination host, it only showed two tags of the image. See below:
src:
![image](https://cloud.githubusercontent.com/assets/12540577/16767090/5a10126a-4870-11e6-93d5-060c4e434ffa.png)
![image](https://cloud.githubusercontent.com/assets/12540577/16767100/6bc9d4dc-4870-11e6-8b4e-b463b123b474.png)
dst:
![image](https://cloud.githubusercontent.com/assets/12540577/16767124/7a0d3656-4870-11e6-83e0-74ca74754de8.png)

**Comment by reasonerjt** [comment]
@ywk253100 I guess this is because the tags have the identical digests?  Could you revisit the logic so even the tags have same digest they should be synced to destination?

**Comment by ywk253100** [comment]
I will fix it.

**Comment by wemeya** [comment]
fixed after check, closed.
