### ISSUE TITLE
Helm: REGISTRY_STORAGE_PROVIDER_NAME is hardcoded

### ISSUE THREAD

**Issue by jkroepke** [vmware/harbor#5220]
Hi,

https://github.com/vmware/harbor/blob/1afb09b6cf54295bf5d967b7045f8fc66754c85b/contrib/helm/harbor/templates/adminserver/adminserver-cm.yaml#L62

I'm using S3 as backend for our registry, there are any reason why its hardcoded to 'filesystem'?

Goes something wrong with our registry, if the adminserver has filesystem configured?

**Comment by ninjadq** [comment]
hi @jkroepke ,
You should edit the `harbor.cfg` file If you want to use s3 as storage.

**Comment by jkroepke** [comment]
Why helm can't do it?

Helm does already configure the S3 storage for the registry.

**Comment by reasonerjt** [comment]
We'll add support for other storage backends, thanks

**Comment by reasonerjt** [comment]
@ywk253100 this can be dupped?

**Comment by jkroepke** [comment]
Looks like done w/ https://github.com/vmware/harbor/commit/5772a61e5d1b8cc38a976b5906507e53d6ba6755#diff-0d7c681341249d6f8532236796ece5bbR58
