### ISSUE TITLE
duplicate records when enable policy after disabled

### ISSUE THREAD

**Issue by wemeya** [vmware/harbor#523]
I created a policy, after it finished sync process, I disabled the policy. After a while, I enabled it, duplicate records appeared:
![image](https://cloud.githubusercontent.com/assets/12540577/16768063/34774ad2-4875-11e6-8864-72d025e1e695.png)

**Comment by reasonerjt** [comment]
This is by design, and the dialog has informed user all repositories will be synced.

**Comment by wemeya** [comment]
I see, closed.
