### ISSUE TITLE
No image to migrate from v1.2.0 to higher version for Harbor

### ISSUE THREAD

**Issue by rizwan-kh** [vmware/harbor#5232]
I am using Harbor v1.2.0 and we are facing issue while pushing the image to private Harbor registry. So I was thinking to upgrade the Harbor to latest available which is v1.5.0.

In the upgrade notes, it's mention to use **_vmware/migratorharbor-db-migrator:1.2_** as DB engine is replaced by MariaDB. while doing a docker pull I am getting the below response

`docker pull vmware/migratorharbor-db-migrator:1.2`

`Error response from daemon: pull access denied for vmware/migratorharbor-db-migrator, repository does not exist or may require 'docker login'`

Can someone guide me if I can use the existing vmware/harbor-migrator:v1.5.0 image to do the migration? If not, where can I get the step for migration from v1.2.0 to higher.

**Comment by SysAdmLS** [comment]
I think the upgrade docs need to be corrected. Try using this repository.
https://hub.docker.com/r/vmware/harbor-db-migrator/tags/

"vmware/migratorharbor-db-migrator:1.2" is outdated, I guess.

So you should probably try to use vmware/harbor-db-migrator:1.2 (only for backing up your DB)
If you want to upgrade your DB, use the command from the upgrade notes with the matching tag (for example "v1.5.0" for version 1.5)

https://hub.docker.com/r/vmware/harbor-migrator/ seems to hold the latest images for the 1.5 version.

**Comment by rizwan-kh** [comment]
@SysAdmLS - as per the documentation, there is a DB change from V1.2 so we need to use the image mentioned to perform proper DB upgrade to MariaDB. Not sure if it's just for backup of DB or to perform a complete data migration as well to the new DB. Anyway, I tried with the V1.5 image and it gives me an error. I am currently facing another issue #5240 due which I am not planning an upgrade now (Hoping for the other one to get resolve first)

**Comment by reasonerjt** [comment]
@rizwan-kh 

I'm closing the issue, if there's further problem please re-open.

**Comment by jinghuaz** [comment]
@rizwan-kh  i think you can use replication function is better！
