### ISSUE TITLE
The env variable PGDATA should be pre-set in migrator image.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#5250]
For migrating  clair data, I had to run command like this 

```
docker run -it -e PGDATA=/var/lib/postgresql/data -v /data/clair-db/:/clair-db -v /data/database:/var/lib/postgresql/data vmware/harbor-migrator:v1.5.0-build.4779 --db up
```
The env var `PGDATA` should not be necessary.  As we can set it as default in the image.

Same issue with migrating notary data.

**Comment by wy65701436** [comment]
already did in the docker file: https://github.com/vmware/harbor/blob/master/tools/migration/Dockerfile#L3
