### ISSUE TITLE
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes while sourcing registry.sql

### ISSUE THREAD

**Issue by choldrim** [vmware/harbor#5251]
In this guid, there is an error while importing registry.sql into mysql instance:
https://github.com/vmware/harbor/blob/master/docs/high_availability_installation_guide.md#load-harbor-db-schema

I got `ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes` error while sourcing this sql:

https://github.com/vmware/harbor/blob/3b0c8c6c4e60799cfc96f04b51014189f95d3f80/make/photon/db/registry.sql#L284-L300

It seems that UNIQUE index has a 255 limitation on length.
[stackoverflow](https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes#16820166)

**Comment by reasonerjt** [comment]
What's the version of your mysql instance?

**Comment by choldrim** [comment]
Okay, got it, I used mysql 5.7.
