### ISSUE TITLE
Helm install via insecureRegistry=true

### ISSUE THREAD

**Issue by yakbulut** [vmware/harbor#5252]
In my environment, I have an nginx ingress controller that exposes two node ports one forwarding to 80 and another one to 443.

Goal: To be able to reach harbor using the kubernetes ingress IP <FQDN for now> via nodeport for 443, let ingress handle SSL termination. Internally, harbor should run on insecure registry and the docker client should only need the certificate for the kubernetes ingress and not the one generated by harbor.

Installing harbor using the helm chart with insecureRegistry=true, and externalPort=<nodePort for 80> I can reach the UI just fine. However, docker login fails with the following
```
Error response from daemon: Get http://harbor.my.domain:30314/v2/: Get https://harbor.my.domain:30314/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: http: server gave HTTP response to HTTPS client
```
I have added insecure-registries harbor.my.domain:30314 to my docker daemon.

Note: installing harbor with insecureRegistry=false with externalPort=<nodePort for 443> works fine as I can reach the UI, and docker login works with FQDN:<nodePort for 443>. However, this goes against my design goal where I want the docker client to only need the certificate for kubernetes ingress.

1) Is my design goal possible with harbor ? If so, what changes do I need to make to values.yaml or helm charts ?
2) If insecureRegistry is not supported, is there a way to switch off SSL termination in harbor so kubernetes ingress controller handles this ? In other words, docker client only needs certificates to my nginx ingress.

**Comment by reasonerjt** [comment]
Hi,
The helm chart by default leverages the ingress for SSL termination.

**Comment by yakbulut** [comment]
@reasonerjt Thanks for the reply.
Are you suggesting to install harbor with `generateCertificates=false` and harbor FQDN to the certificate I'm using for the nginx ingress controller ?

**Comment by reasonerjt** [comment]
Ye, I think that's a better way to solve your problem.

**Comment by reasonerjt** [comment]
Closing, if there's further issue please re-open or open new ones.
