### ISSUE TITLE
Can't push a image which does not belong to any project will service-500 occur.

### ISSUE THREAD

**Issue by hanbaga** [vmware/harbor#5255]
harbor members:

I want to transfer images from other registry to harbor. 

By history, My image name like  xxxx:5000/image-name:tag-name.  the image is top one, not belongs to any project.  First of all. I can't rename the images.   so I just want to ask how to handle the issue through harbor.

**Comment by reasonerjt** [comment]
you can retag it and push to Harbor's library project

**Comment by hanbaga** [comment]
I doesn't want to change the image name.   I just want to push xxxx:5000/image-name:tag-name to harbor registry successfully.

do retag not equal rename image?

**Comment by reasonerjt** [comment]
In Harbor every image needs a namespace, this is current design.

**Comment by LinAnt** [comment]
Is there a reason harbor does not use 'library' as the default namespace like DockerHub does?

**Comment by reasonerjt** [comment]
I recall the code was in docker client to add `library` namespace, it would be possible to add `library` by intercepting the request, but there will be inconsistency between registry and notary as the request was sent from docker client to notary server, I don't think want to introduce interceptors to notary.

**Comment by LinAnt** [comment]
It is a bit tedious when you have to create a lot of custom hacks for projects that rely on images like nginx:<version> or busybox:<> 

Is there any good workaround for this? I would like to pull all images from our local harbor instances.

**Comment by reasonerjt** [comment]
Closing the issue as no actions will be taken.

**Comment by panpan0000** [comment]
But it makes life harder to migrate some internet-access code into non-internet-acccess enviroments with harbor..
