### ISSUE TITLE
Replication Jobs log  page 404 in some cancel status

### ISSUE THREAD

**Issue by rusirenye** [vmware/harbor#527]
I disable replication policy , then tag an image and push it . Next  I enable the policy, and quickly disable it,  Then replication job  log  item at cancel status  can't find  log detail

**Comment by reasonerjt** [comment]
This is because the job is canceled before the logger is initialized, I will write a message to job log file even it's canceled.

**Comment by rusirenye** [comment]
there is another situation that  push same image  twice or more.  404 page also show up. @reasonerjt

**Comment by rusirenye** [comment]
cancel status log  end time is ahead of creation time @ywk253100
