### ISSUE TITLE
Can harbor be used as helm chart repository besides container registry

### ISSUE THREAD

**Issue by mailzyok** [vmware/harbor#5284]
Hi, 

I saw a directory named chartserver under src, does it mean harbor can be used as helm chart repository besides container registry? I didn't see this feature is mentioned in any documents

Thanks,
yzha

**Comment by reasonerjt** [comment]
It's a WIP targeting 1.6.0
https://github.com/vmware/harbor/issues/4947

**Comment by reasonerjt** [comment]
It will leverage the current mechanism of Harbor for authentication. 
And the RBAC will be consistent with current implementation against docker images.
Audit logs will fall out of the scope of 1.6
As for HA, the HA doc is a reference, as long as the chart museum can be configured against HA or cloud storage, it should be easy to scale out.

**Comment by mailzyok** [comment]
Thanks for your quick response. Additional question on OAuth2, i see it in the Roadmap.md, but i didn't find any other documentation and release info. Could you help me with it?

**Comment by reasonerjt** [comment]
It's not supported yet.

**Comment by mailzyok** [comment]
Really thanks for the quick response. We are now evaluating Harbor as Container Registry in our product, Good to know Harbor is in CNCF, and harbor is integrating Chat repo as well which is a very important feature for K8S ecosystem. 

May i know the target date for harbor 1.6.0, and any plan for OAuth2 support? 

In another thread, i have asked questions on the database backend.

I see harbor is now mirgrating maria DB to postgres DB. Its good to see one database backend is used. Why postgres is choosed, i think it is due to Clair, but what confusing me is that:

Mysql DB is also listed in the license area of readme besides Photon OS, What is the usage of Mysql DB, will it be mirgrating to postgres as well? 
What is the relationship between Mysql DB and MariaDB?


Thanks,
yzha

**Comment by steven-zou** [comment]
@mailzyok 

As the question is clarified, I'll close this issue. For more details about Helm chart supporting, please check the progress of epic https://github.com/vmware/harbor/issues/4947 or raise a new question. Thanks.
