### ISSUE TITLE
The type of SearchRepository.project_public in docs/swagger.yaml SHOULD update from integer to boolean

### ISSUE THREAD

**Issue by moooofly** [vmware/harbor#5286]
This issue comes from the modification of https://github.com/vmware/harbor/commit/66b2d0d3f3b3fd8c295ca444c013f7631b010796#diff-ba44be8be3c79f4e4b337277b408cd68 

This issue will cause the compatibility problem if harbor cli tools are implemented basing on harbor v1.2.2 (swagger.yaml) and before.

Details:

------

- error message

```
error: json: cannot unmarshal bool into Go struct field repoSearch.project_public of type int
```

- https://github.com/vmware/harbor/commit/66b2d0d3f3b3fd8c295ca444c013f7631b010796#diff-ba44be8be3c79f4e4b337277b408cd68

<img width="1330" alt="project_public change from int32 to bool - 1" src="https://user-images.githubusercontent.com/7439290/42549365-548ad088-84fe-11e8-8e94-5af247fd1c81.png">

- https://github.com/vmware/harbor/blob/master/docs/swagger.yaml#L2664

<img width="1287" alt="project_public change from int32 to bool - 2" src="https://user-images.githubusercontent.com/7439290/42549379-686bb694-84fe-11e8-805f-9b5100b236da.png">

Related:

- https://github.com/moooofly/harbor-go-client/issues/2
- https://github.com/vmware/harbor/issues/5085

**Comment by stonezdj** [comment]
fixed in #5402
