### ISSUE TITLE
**docker login harbor error**

### ISSUE THREAD

**Issue by little-humor** [vmware/harbor#5292]
出于安全考虑，harbor服务器只能内网连接，我在上层配置了nginx作为入口，通过119.18.193.77:1952（上层nginx转发的是harbor服务器的内网地址10.6.52.5）可以正常访问harbor的ui界面，但是无法docker login 119.18.193.77:1952；该命令执行后的日志信息是：Error response from daemon: Get http://119.18.193.77:1952/v2/: Get http://10.6.52.5/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: net/http: request canceled (Client.Timeout exceeded while awaiting headers) (Client.Timeout exceeded while awaiting headers)

harbor.cfg内容片段：
_version = 1.5.0
hostname = 10.6.52.5
ui_url_protocol = http
no_proxy = 127.0.0.1,localhost,ui
auth_mode = db_auth
...
@vito @jessehu @edevil @jsr @fsword 
thank you！

**Comment by little-humor** [comment]
<img width="1162" alt="wx20180711-224248 2x" src="https://user-images.githubusercontent.com/40624244/42581024-7017632e-855e-11e8-9e5a-03ff4ab35df2.png">
<img width="1051" alt="wx20180711-224443 2x" src="https://user-images.githubusercontent.com/40624244/42581031-72e3f090-855e-11e8-88a4-10ee790b9761.png">

**Comment by ywk253100** [comment]
Please configure the `hostname` with the external endpoint `119.18.193.77:1952` in `harbor.cfg`. Run `prepare` script and restart Harbor.
