### ISSUE TITLE
Feature request: Automatically add newly registered user as member to project

### ISSUE THREAD

**Issue by LoLei** [vmware/harbor#5302]
I wanted to ask if it is possible to have an option to automatically add users as a member with a role to a project upon user creation.

My use case is that I have a private project, of which I want every new user to be a Guest member. A workaround is having this as a public project, but then everyone could pull the repositories, even if they do not have an account. Of course this implies that self-registration is disabled, otherwise it would then function the same as a public repository. 

This might be related to https://github.com/vmware/harbor/issues/3115, but I'm not sure, since I'm using not using LDAP but db_auth at the moment.

It seems like the user does not have this functionality at the moment:

```
{
  "user_id": 0,
  "username": "string",
  "email": "string",
  "password": "string",
  "realname": "string",
  "comment": "string",
  "deleted": 0,
  "role_name": "string",
  "role_id": 0,
  "has_admin_role": 0,
  "reset_uuid": "string",
  "Salt": "string",
  "creation_time": "string",
  "update_time": "string"
}
```
Either a field here where one specifies a project and member role to added automatically, or an option from within the project to have all new users added to it with a specific member role automatically.

Anyway, just asking if this is somehow possible yet, and if not if it can be added, appreciate any response!

**Comment by reasonerjt** [comment]
I don't think we'll add user as member once it's created.
Let's discuss your requirement in #5447
