### ISSUE TITLE
[Question] features and release plan

### ISSUE THREAD

**Issue by mailzyok** [vmware/harbor#5305]
Hi

We are evaluating Harbor as Container Registry in our product. Good to know Harbor is in CNCF, and harbor is integrating Chat repo as well which is a very important feature for K8S ecosystem.

Please help to answer the following questions. Your prompt support is highly appreciated.

1. What is the release date for harbor 1.6.0?
2. Any timeline for OAuth2 support?
3. Besides Photon OS, can harbor be built on Rhel OS or alphine OS?
4. Regarding on database backend, I see harbor is now mirgrating maria DB to postgres DB. Does it mean from 1.6.0, only PostgreSQL is need to be deployed?
5. Does harbor support accessing external PostgreSQL, not requiring a harbor db image?

Thanks,
yzha

**Comment by mailzyok** [comment]
Could you please help to answer these questions? Thanks.

**Comment by reasonerjt** [comment]
1. For 1.6 we are targeting mid-late august.
2. Currently no timeline for OAuth2 support but we are considering it.
3. In addition to PhotonOS.  I believe you can build Harbor images on top of other distro, but so far we don't plan to provide the Dockerfile
4. It's correct after 1.6 only postgreSQL will be needed.
5. It does, you need to configure the endpoint of postgreSQL and create the DB yourself, after that Harbor will populate the schema, create tables, etc.

**Comment by mailzyok** [comment]
Thanks a lot for your help.  @reasonerjt
