### ISSUE TITLE
Is COMPILETAG still in use?

### ISSUE THREAD

**Issue by silenceshell** [vmware/harbor#5316]
I try to compile harbor with my own Golang environment flowing this [guide](https://github.com/vmware/harbor/blob/master/docs/compile_guide.md#ii-compile-code-with-your-own-golang-environment-then-build-harbor) , but I met with this problem:

```
$ make install

Note: golang version: 1.9.7

Note: docker version: 18.03.1

Note: docker-compose version: 1.21.2
compiling binary for clarity ui...
/usr/bin/docker: invalid reference format.
See '/usr/bin/docker run --help'.
Makefile:252: recipe for target 'compile_clarity' failed
make: *** [compile_clarity] Error 125
```

It seems that `CLARITYIMAGE` is the origin value `vmware/harbor-clarity-ui-builder[:tag]` which is defined in Makefile.

I can not find any codes who will update `CLARITYIMAGE` when `COMPILETAG` is the default value `compile_normal`. 

So, is `COMPILETAG` still in use? And how can I build harbor with my own go env?

**Comment by wy65701436** [comment]
Use the following to build master code:

make package_offline GOBUILDIMAGE=golang:1.9.2 COMPILETAG=compile_golangimage CLARITYIMAGE=vmware/harbor-clarity-ui-builder:1.4.0 NOTARYFLAG=true CLAIRFLAG=true MIGRATORFLAG=true CHARTFLAG=true HTTPPROXY=
