### ISSUE TITLE
wrong name for ldap search in values.yaml for helm installation

### ISSUE THREAD

**Issue by philosifer** [vmware/harbor#5326]
When using ldap_auth helm install fails with.

Error: render error in "harbor/templates/adminserver/adminserver-secrets.yaml": template: harbor/templates/adminserver/adminserver-secrets.yaml:17:47: executing "harbor/templates/adminserver/adminserver-secrets.yaml" at <b64enc>: wrong number of args for b64enc: want 1 got 0

Looking in adminserver-secrets.yaml it is looking for searchPwd but the option in values.yaml says

ldap:
...
  searchPassword: ""

Changing values.yaml for searchPwd: seems to resolve the issue.

**Comment by ywk253100** [comment]
Fixed.
