### ISSUE TITLE
Customizing look and feel without building possible?

### ISSUE THREAD

**Issue by LoLei** [vmware/harbor#5329]
According to [this](https://github.com/vmware/harbor/blob/master/docs/customize_look%26feel_guide.md), the look and feel can be customized, and [it says](https://github.com/vmware/harbor/blob/master/docs/customize_look%26feel_guide.md#build) it needs to be rebuild from source afterwards, although the link is broken, I assume it should lead [here](https://github.com/vmware/harbor/blob/master/docs/compile_guide.md).

Is there a way to do this without building Harbor? 

Having this `setting.json` file in the release build directory structure or the same options in `harbor.cfg` and having it apply with `install.sh` or `prepare` would be great.

**Comment by SysAdmLS** [comment]
You can add a new volume mount (in the docker-compose.yml) to the UI Container including the customized setting.json and maybe a new headerLogo, which you have to define in the new config of course.

Example config for docker-compose.yml:
ui:
    image: vmware/harbor-ui:v1.5.0
    env_file:
      - ./common/config/ui/env
    volumes:
      - /your_path/headerLogo.png:/harbor/static/images/headerLogo.png:z 
      - /your_path/settings.json:/harbor/static/setting.json:z
      ....

**Comment by LoLei** [comment]
Thank you, I will do that. Since this is apparently possible this way, I will close this issue.
