### ISSUE TITLE
Unable to see newly created projects in UI, however searching explicitly is listing them

### ISSUE THREAD

**Issue by lgayatri** [vmware/harbor#5366]
1.4.2 RC3

1. I created three projects after upgrading OVA from 1.3.1 to 1.4.2 
2. Cant find them on the Projects page
![image](https://user-images.githubusercontent.com/25006749/43064755-7a79ec74-8e7d-11e8-9c69-aa0ca84276a7.png)
3. But when I search explicitly, I can find them (using the Search on the Projects page)
![image](https://user-images.githubusercontent.com/25006749/43064701-53980636-8e7d-11e8-8fee-2b716c11b5e9.png)

@renmaosheng @reasonerjt @zjs

**Comment by reasonerjt** [comment]
And this seems a limitation I double checked UI will always send a request:
https://vic-st-h2-182.eng.vmware.com:8282/projects?$limit=50&expand=true&documentType=true&$count=true

Note `limit=50` in the request, that's why the newly created projects are not shown.

**Comment by reasonerjt** [comment]
Issue moved to [vmware/admiral #282](https://github.com/vmware/admiral/issues/282) via [**ZenHub**](https://www.zenhub.com/)

**Comment by bansalrajat** [comment]
i am having the same issue.
