### ISSUE TITLE
Vulnerability scan 302 redirect Issue behind proxy

### ISSUE THREAD

**Issue by dnewhook** [vmware/harbor#5370]
When configuring a proxy for clair in Harbor 1.5.2, the default settings result in the requests towards the clair api (http://registry:5000/v2) being redirected to http://www.registry.com/v2.  As a result, the uploaded images are not scanned.

The image 'vulnerability column' shows 'view log' and the error inside shows:
2018-07-23T09:41:12Z [ERROR] [job_logger.go:81]: Failed to scan layer: xxxxxxxxx, error: Unexpected status code: 400, text: {"Error":{"Message":"could not find layer"}}

I was able to fix this issue by adjusting the no_proxy directive in harbor.cfg:
From:
`no_proxy = 127.0.0.1,localhost,ui`
To:
`no_proxy = 127.0.0.1,localhost,ui,registry`

Harbor Version: v1.5.2
OS: CentOS Linux release 7.5.1804 (Core)
Docker Engine: docker-1.13.1-68
Docker Compose: 1.21.2

**Comment by reasonerjt** [comment]
Thanks for raising this issue.

**Comment by reasonerjt** [comment]
Fixed in #5400
