### ISSUE TITLE
Containers not found when start 

### ISSUE THREAD

**Issue by 7ussana** [vmware/harbor#5381]
Hello,

I have a problem after the upgrade 1.5.1 to 1.5.2

```
./prepare
docker-compose up -d
```

```
Pulling log (vmware/harbor-log:v1.5.2)...
ERROR: manifest for vmware/harbor-log:v1.5.2 not found

```

**Comment by SysAdmLS** [comment]
They haven't uploaded the 1.5.2 image to docker-hub yet. 
I already asked if they could upload them here: https://github.com/vmware/harbor/issues/5231

A workaround would be to extract the images from the offline-installer package (they are includes as harbor.v1.5.2.tar.gz) and run `docker load harbor.v1.5.2.tar.gz` manually.
Or you run the install.sh script.
