### ISSUE TITLE
Cannot push image to the private registry

### ISSUE THREAD

**Issue by rootsongjc** [vmware/harbor#54]
After I followed the instructions and installed harbor, I can't push my image to the private registry.
Environment: CentOS 7.1 / Docker 1.10 / IP 172.17.1.31
I appended this line to /etc/sysconfig/docker.
OPTIONS='--selinux-enabled --ipv6=false --insecure-registry=172.17.1.31:5001'
But when I push a image,
docker push 172.17.1.31:5001/ubuntu:14.04
I got these logs.
The push refers to a repository [172.17.1.31:5001/ubuntu]
unable to ping registry endpoint https://172.17.1.31:5001/v0/
v2 ping attempt failed with error: Get https://172.17.1.31:5001/v2/: dial tcp 172.17.1.31:5001: getsockopt: connection refused
 v1 ping attempt failed with error: Get https://172.17.1.31:5001/v1/_ping: dial tcp 172.17.1.31:5001: getsockopt: connection refused
Anyone have idea?

**Comment by hainingzhang** [comment]
By default, Harbor's port is 80, so the command should look like this: 

push 172.17.1.31/ubuntu:14.04

Hope this helps.

**Comment by rootsongjc** [comment]
I have tried this but it does't work. I edited /etc/sysconfig/docker with this line
OPTIONS='--selinux-enabled --ipv6=false --insecure-registry=172.17.1.31'

Run docker push 172.17.1.31/ubuntu:14.04
Got these:
The push refers to a repository [172.17.1.31/ubuntu]
unable to ping registry endpoint https://172.17.1.31/v0/
v2 ping attempt failed with error: Get https://172.17.1.31/v2/: dial tcp 172.17.1.31:443: getsockopt: connection refused
 v1 ping attempt failed with error: Get https://172.17.1.31/v1/_ping: dial tcp 172.17.1.31:443: getsockopt: connection refused

**Comment by reasonerjt** [comment]
seems docker client is still trying to access https, have you restarted docker daemon?

**Comment by rootsongjc** [comment]
@reasonerjt Yes, I restarted docker daemon, but the same error happened. 

The docker client do try to access https, what should I do to fix this?

$docker push 172.17.1.31/ubuntu:14.04
The push refers to a repository [172.17.1.31/ubuntu]
unable to ping registry endpoint https://172.17.1.31/v0/
v2 ping attempt failed with error: Get https://172.17.1.31/v2/: dial tcp 172.17.1.31:443: getsockopt: connection refused
 v1 ping attempt failed with error: Get https://172.17.1.31/v1/_ping: dial tcp 172.17.1.31:443: getsockopt: connection refused

**Comment by rootsongjc** [comment]
Before I push an image whether I should login first? I signup on my harbor site.
I added "OPTIONS='--selinux-enabled --ipv6=false --insecure-registry 172.17.1.31'" on my /etc/sysconfig/docker, but I login failed at the same time.

$docker login 172.17.1.31
Username: xxx
Password: 
Email: xxx@xxx.com
Error response from daemon: invalid registry endpoint https://172.17.1.31/v0/: unable to ping registry endpoint https://172.17.1.31/v0/
v2 ping attempt failed with error: Get https://172.17.1.31/v2/: dial tcp 172.17.1.31:443: getsockopt: connection refused
 v1 ping attempt failed with error: Get https://172.17.1.31/v1/_ping: dial tcp 172.17.1.31:443: getsockopt: connection refused. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 172.17.1.31` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/172.17.1.31/ca.crt

**Comment by reasonerjt** [comment]
**--insecure-registry=172.17.1.31**  :)

**Comment by rootsongjc** [comment]
Thank you all, I got the answer. The docker's configuration file is not in /etc/sysconfig/docker, so the config not work. The right place is /usr/lib/systemd/system/docker.service

**Comment by reasonerjt** [comment]
Good to know, closing this issue.
