### ISSUE TITLE
Latest harbor 1.5.2 tarball is not found.

### ISSUE THREAD

**Issue by MasashiTeruya** [vmware/harbor#5422]
I cannot download harbor 1.5.2 tarball listed on release page while previous 1.5.1 is available.

$ wget https://storage.googleapis.com/harbor-releases/harbor-online-installer-v1.5.{1,2}.tgz
--2018-07-28 16:24:04--  https://storage.googleapis.com/harbor-releases/harbor-online-installer-v1.5.1.tgz
Resolving storage.googleapis.com (storage.googleapis.com)... 2404:6800:4004:815::2010, 216.58.221.16
Connecting to storage.googleapis.com (storage.googleapis.com)|2404:6800:4004:815::2010|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 31106 (30K) [application/x-compressed-tar]
Saving to: ‘harbor-online-installer-v1.5.1.tgz’

harbor-online-installer-v1.5.1.tgz                          100%[========================================================================================================================================>]  30.38K  --.-KB/s    in 0.002s

2018-07-28 16:24:04 (12.4 MB/s) - ‘harbor-online-installer-v1.5.1.tgz’ saved [31106/31106]

--2018-07-28 16:24:04--  https://storage.googleapis.com/harbor-releases/harbor-online-installer-v1.5.2.tgz
Reusing existing connection to [storage.googleapis.com]:443.
HTTP request sent, awaiting response... **404 Not Found**
2018-07-28 16:24:04 ERROR 404: Not Found.

FINISHED --2018-07-28 16:24:04--
Total wall clock time: 0.4s
Downloaded: 1 files, 30K in 0.002s (12.4 MB/s)

**Comment by forging2012** [comment]
1.5.2 image is  not published.

**Comment by forging2012** [comment]
Just try 1.5.1 or 1.5.2

**Comment by wy65701436** [comment]
fixed, please try it again.
