### ISSUE TITLE
项目中点击tag 报错： 发生未知错误,请稍后再试。

### ISSUE THREAD

**Issue by cherick** [vmware/harbor#5443]
接口无法访问，配置是官网默认配置
registry 端口也是默认的，没有修改
harbor版本：1.5.2
Request URL: http://一个ip/api/repositories/devenv/helloworld/tags/0.1/vulnerability/details
Request Method: GET
Status Code: 503 Service Unavailable

**Comment by ywk253100** [comment]
Check that whether all containers start successfully. If not, find the reason why the container doesn't start according to the logs.

**Comment by aurthurxlc** [comment]
I have the same error, all containers are running

**Comment by aurthurxlc** [comment]
harbor version: 1.5.2
I have the some error, when I click the image tag, the harbor-ui component output the two warning.
```bash
[WARNING] Failed to get pmid from path, error strconv.ParseInt: parsing "": invalid syntax
...
[WARNING] Harbor is not deployed with Clair, it's not impossible to get vulnerability details.
```

**Comment by ywk253100** [comment]
It's a known issue #5055 and has been fixed in the master branch.

The link on the tags should be disabled if Clair is not installed. You can re-install Harbor with Clair if you want to enable the "image scan" feature.

Closing it, feel free to reopen it.
