### ISSUE TITLE
[LDAP Group UI] Add an group with existing group DN has strange behaviour

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#5492]
Go to library -> New Group -> Add a existing DN -> Save

It could be saved, but actually it updates the existing group's role. This behaviour is strange for end user.

![image](https://user-images.githubusercontent.com/2841473/43575408-5980af72-9679-11e8-85d4-49efdf372d47.png)

**Comment by stonezdj** [comment]
Fixed #5520, will return 409 error
