### ISSUE TITLE
[UI Chart] Source Repository URL render issue

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#5497]
Uploaded MariaDB, it has two urls to view.

![image](https://user-images.githubusercontent.com/2841473/43578871-c8fa1240-9682-11e8-9b40-191f1d5a465d.png)

![image](https://user-images.githubusercontent.com/2841473/43578850-b8a447da-9682-11e8-8a47-6c3b013065c4.png)

**Comment by ninjadq** [comment]
Fixed in #5459
