### ISSUE TITLE
Update the tooltip of LDAP 

### ISSUE THREAD

**Issue by stonezdj** [vmware/harbor#5512]
LDAP Group Base DN:  The base DN from which to look up a group in LDAP/AD
LDAP Group Filter:  The filter to look up an LDAP/AD group, use objectclass=groupOfNames by default.
LDAP Group GID: The attribute used in a search to match a user, it could be uid, cn or other attributes depending on your LDAP/AD. the group in Harbor is named with this attribute by default.
LDAP Group Admin DN:  Specify an LDAP group DN. all LDAP user in this group will have harbor admin privilege.  Keep it blank if you do not want to.
LDAP Group Scope: The scope to search for groups, select Subtree by default.

**Comment by zhoumeina** [comment]
Ok. @stonezdj .
