### ISSUE TITLE
关于registry和mysql的迁移问题

### ISSUE THREAD

**Issue by qq511700505** [vmware/harbor#552]
我们之前用的harbor的版本是旧的UI那一版，现在想要更换到新版UI,数据库这边直接copy的方式貌似不是完美的解决方式。会遇到下面的问题：
      
**切换到System Management 页面： Error  Failed to list destinations.**

应该是数据库表不全造成的吧

请问如何解决迁移过程中的这种问题呢，谢谢。

**Comment by reasonerjt** [comment]
There's migration tool, please refer to:
https://github.com/vmware/harbor/blob/master/docs/migration_guide.md

**Comment by reasonerjt** [comment]
@qq511700505 does it fix your problem?

**Comment by qq511700505** [comment]
Yes, I have done this correctly according to the guide you mentioned.

Let's close this issue, thanks

**Comment by Huimintai** [comment]
:)

**Comment by qq511700505** [comment]
tai hui min  你也在搞Harbor么 @Huimintai
