### ISSUE TITLE
Refine LDAP Group UI text

### ISSUE THREAD

**Issue by stonezdj** [vmware/harbor#5532]
<img width="1280" alt="screen shot 2018-08-06 at 2 47 54 pm" src="https://user-images.githubusercontent.com/2696760/43702793-6abfbf6e-998d-11e8-8e5d-ed01ad09f80c.png">

**Comment by stonezdj** [comment]
The operation doesn't create any user or any group, buttons should named with  + User, + Group,

**Comment by stonezdj** [comment]
<img width="579" alt="screen shot 2018-08-06 at 2 48 07 pm" src="https://user-images.githubusercontent.com/2696760/43702874-b710f86a-998d-11e8-90be-1866ffa42fe4.png">

**Comment by stonezdj** [comment]
This dialog title is confusing, it should be "Add user member"

**Comment by stonezdj** [comment]
Screen Shot 2018-08-06 at 3.33.08 PM

**Comment by stonezdj** [comment]
The title should be: Add Group Member

Option 1. Add an existing user group to project member 
Option 2. Add a group from LDAP to project member

**Comment by ninjadq** [comment]
Fixed in #5459
