### ISSUE TITLE
Helm Chart Card View Refactor

### ISSUE THREAD

**Issue by ninjadq** [vmware/harbor#5534]
1. card view of chart
![image](https://user-images.githubusercontent.com/1069785/43704368-ff83d35c-9991-11e8-8377-144fd76e9d04.png)
2. card view of chart versions 
![image](https://user-images.githubusercontent.com/1069785/43704403-219be970-9992-11e8-85dc-9ed3efe0d8ce.png)

**Comment by ninjadq** [comment]
card view of chart version
![image](https://user-images.githubusercontent.com/1069785/43715187-31c3093a-99b2-11e8-9196-a7be9a8375b1.png)

**Comment by zhoumeina** [comment]
implemented in pr #5551
