### ISSUE TITLE
Swagger.yaml shows errors when it is loaded in browser

### ISSUE THREAD

**Issue by sshyamal** [vmware/harbor#555]
I have successfully deployed Harbor engine. Now, to make use of REST API, I want to read swagger.yaml. I am following this link: https://github.com/vmware/harbor/blob/master/docs/configure_swagger.md

When I load it in Swagger editor, I get these swagger errors: 

✖ Swagger Error
Not a valid op_time definition
Details
 Object
code:  "ANY_OF_MISSING"
 params: Array [0]
message:  "Not a valid op_time definition"
 path: Array [5]
schemaId:  "http://swagger.io/v2/schema.json#"
 inner: Array [2]
level: 900
type:  "Swagger Error"
description:  "Not a valid op_time definition"
lineNumber: -1
✖ Swagger Error
Not a valid response definition
Details
 Object
✖ Swagger Error
Not a valid response definition
Details
 Object

These are from the master branch.
Also, when I load it in browser, I get following error: 

{"schemaValidationMessages":[{"level":"error","message":"Can't read from file http://10.112.252.114/static/resources/yaml/swagger.yaml"}]}

Please help in this.

Regards,
Sudarshan

**Comment by yhua123** [comment]
Hi Sudarshan,
Please click 'Products" on screen, you can see the detail API info.
This version swagger.yaml only have part of APIs, will update in couple of weeks.

BR,
Yong

![untitled](https://cloud.githubusercontent.com/assets/19166125/16869800/39800c1a-4ab1-11e6-8ede-7f40f1575575.png)

**Comment by sshyamal** [comment]
Thanks Yong. It is showing API info.
