### ISSUE TITLE
Get more push logs than image tags when sync to destination

### ISSUE THREAD

**Issue by wemeya** [vmware/harbor#560]
See below:
![image](https://cloud.githubusercontent.com/assets/12540577/16912322/efc75e72-4d15-11e6-907d-1bc945fd8ec9.png)

![image](https://cloud.githubusercontent.com/assets/12540577/16912334/07a959f0-4d16-11e6-83a9-ed88a5c61b87.png)

**Comment by reasonerjt** [comment]
Please clarify, are you seeing the access log on destination?

**Comment by wemeya** [comment]
@reasonerjt 
yes, it's the log on destination.

**Comment by ywk253100** [comment]
Did not reproduce the issue. And some codes which help debug the issue are added into branch master and if it occurs again, we can track it.

**Comment by wemeya** [comment]
Reoccurred.  I pulled the newest code and did the test. See below: 
![image](https://cloud.githubusercontent.com/assets/12540577/17213465/ed65cf44-5506-11e6-8486-6417609050f5.png)
![image](https://cloud.githubusercontent.com/assets/12540577/17213492/0f942cdc-5507-11e6-95c2-f4f2185f0fa1.png)

**Comment by ywk253100** [comment]
Fixed by #615 .
