### ISSUE TITLE
Error occured while refreshing the ui of destination in a going on sync process 

### ISSUE THREAD

**Issue by wemeya** [vmware/harbor#561]
The error seems like: Failed to get [object][object] 
I didn't capture the screen when it occured, it can be reproduced when syncing several repos to a destination and refreshing the ui of detination.

**Comment by ywk253100** [comment]
It's a bug of registry https://github.com/docker/distribution/issues/777. When listing the tags of a repository which is being pushed, a "NAME_UNKNOWN" error will been returned, while the catalog API can list this repository.
I will make a workaround for this bug.
