### ISSUE TITLE
error to create project since the key name is not unique when syncing a project with several repos to a destination.

### ISSUE THREAD

**Issue by wemeya** [vmware/harbor#562]
It is happened because several threads are checking if the project exist in the destination DB concurrently, if not, they create the project simultaneously.

**Comment by reasonerjt** [comment]
I don't think it's worthy to introduce coordination or dependency to jobs.  This issue could be worked around by updating the API to return 409 so the state handler knows the project is created by some other.

**Comment by reasonerjt** [comment]
should be fixed via #565

**Comment by reasonerjt** [comment]
please re-open if this re-occur.
