### ISSUE TITLE
Prepare script throws error "Fail to generate ./config/registry/root.crt"

### ISSUE THREAD

**Issue by pcgeek86** [vmware/harbor#570]
I followed the directions to customize `harbor.cfg`. When I run the `./prepare` script, I get an error: 

> Fail to generate ./config/registry/root.crt

Any thoughts?

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by reasonerjt** [comment]
Hi, some errors by openssl were ignored please use this script to retry.

[prepare.zip](https://github.com/vmware/harbor/files/372841/prepare.zip)

**Comment by rajcheval** [comment]
I did replace the old prepare file with prepare.zip file. 
I got a different error about generating key.
We are on ubuntu.
I did verify that internet connectivity is there.
I did verify that all pre-reqs are already installed.

Let us know if you have any other suggestions.

~/vmwareharbor/Deploy$ ./prepare
Clearing the configuration file: ./config/ui/app.conf
Clearing the configuration file: ./config/ui/env
Clearing the configuration file: ./config/registry/config.yml
Clearing the configuration file: ./config/db/env
Clearing the configuration file: ./config/jobservice/env
Generated configuration file: ./config/ui/env
Generated configuration file: ./config/ui/app.conf
Generated configuration file: ./config/registry/config.yml
Generated configuration file: ./config/db/env
Generated configuration file: ./config/jobservice/env
Clearing the configuration file: ./config/ui/private_key.pem
Generating RSA private key, 4096 bit long modulus
.......................................................................................................++
..........................................................................++
e is 65537 (0x10001)
Generated configuration file: ./config/ui/private_key.pem
problems making Certificate Request
140448945669792:error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:a_mbstr.c:154:maxsize=2
Fail to generate ./config/registry/root.crt

**Comment by rajcheval** [comment]
I was able to get past this error. It was happening because country code was too long.

**Comment by pcgeek86** [comment]
Thanks @rajcheval

**Comment by yuxingxin** [comment]
Duplicate of #2920
