### ISSUE TITLE
Service 'log' failed to build

### ISSUE THREAD

**Issue by liuq4360** [vmware/harbor#575]
i use prebuild harbor,when i start it , it comes to an error:
ERROR: Service 'log' failed to build: mkdir /var/lib/docker/overlay/f3131e83d73405493773cb8227fdde8d6d669edc20391a9088f77a0f3a889d98-init/merged/dev/shm: invalid argument

my os is  centos 7, docker version 1.11.2 compose version 1.7.1,

i don't know what's wrong?

**Comment by reasonerjt** [comment]
Looks like some error by docker daemon, is it reproducible?

**Comment by liuq4360** [comment]
i try on two hosts, the same problem, when i restart docker , don't solve the problem.

**Comment by reasonerjt** [comment]
a bit google, and found this:

https://github.com/docker/docker/issues/10294

scroll down, and seems this is kernel issue for cetnos + overlayfs.
