### ISSUE TITLE
failed to trigger replication of 1: 403

### ISSUE THREAD

**Issue by juicy12345** [vmware/harbor#579]
when add new policy,after click OK ,it will have error in /var/log/harbor/2016-07-20/docker_ui.log,
but test connection is ok.
error is:
2016-07-20T07:25:49Z [ERROR] [replication_policy.go:144]: failed to trigger replication of 1: 403

**Comment by juicy12345** [comment]
when add new policy,after click OK ,it will have error in /var/log/harbor/2016-07-20/docker_ui.log,
 but test connection is ok.
error is:
2016-07-20T07:25:49Z [ERROR] [replication_policy.go:144]: failed to trigger replication of 1: 403

**Comment by reasonerjt** [comment]
please attache the complete log file of docker_ui.log

**Comment by juicy12345** [comment]
Jul 20 15:25:31 SZV1000051614 docker/ui[110789]: 2016/07/20 07:25:31 #033[1;34m[router.go:829][D] | GET        | /api/projects                            | 91.630089ms      | match      | /api/projects/                           | #033[0m
Jul 20 15:25:31 SZV1000051614 docker/ui[110789]: 2016/07/20 07:25:31 #033[1;34m[router.go:829][D] | GET        | /api/policies/replication/               | 3.540509ms       | match      | /api/policies/replication                | #033[0m
Jul 20 15:25:31 SZV1000051614 docker/ui[110789]: 2016/07/20 07:25:31 #033[1;34m[router.go:829][D] | GET        | /api/projects/1/members/current          | 3.717925ms       | match      | /api/projects/:pid([0-9]+)/members/?:mid | #033[0m
Jul 20 15:25:39 SZV1000051614 docker/ui[110789]: 2016/07/20 07:25:39 #033[1;34m[router.go:829][D] | GET        | /api/targets/                            | 2.014065ms       | match      | /api/targets/                            | #033[0m
Jul 20 15:25:48 SZV1000051614 docker/ui[110789]: 2016-07-20T07:25:48Z [DEBUG] [transport.go:51]: 200 | GET http://10.183.160.247/v2/
Jul 20 15:25:48 SZV1000051614 docker/ui[110789]: 2016/07/20 07:25:48 #033[1;34m[router.go:829][D] | POST       | /api/targets/ping                        | 263.767458ms     | match      | /api/targets/ping                        | #033[0m
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: 2016/07/20 07:25:49 #033[1;34m[router.go:829][D] | POST       | /api/targets                             | 12.214594ms      | match      | /api/targets/                            | #033[0m
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: 2016/07/20 07:25:49 #033[1;34m[router.go:829][D] | POST       | /api/policies/replication                | 12.975444ms      | match      | /api/policies/replication                | #033[0m
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: 2016-07-20T07:25:49Z [DEBUG] [utils.go:116]: buildReplicationURL11111111111:http://jobservice/api/jobs/replication
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: 2016-07-20T07:25:49Z [DEBUG] [utils.go:117]: 222222222222222222222222222222:{"policy_id":1,"repository":"","operation":"transfer","tags":null}
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: 2016/07/20 07:25:49 #033[1;34m[router.go:829][D] | GET        | /api/policies/replication/               | 3.722528ms       | match      | /api/policies/replication                | #033[0m
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: 2016-07-10 07:25:49.247851145 +0000 UTC
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: 2016/07/20 07:25:49 #033[1;34m[router.go:829][D] | GET        | /api/jobs/replication/                   | 2.529237ms       | match      | /api/jobs/replication/                   | #033[0m
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: 2016-07-20T07:25:49Z [DEBUG] [utils.go:132]: 4444444 resp.StatusCode:403
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: 2016-07-20T07:25:49Z [ERROR] [replication_policy.go:144]: failed to trigger replication of 1: 403 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: <html xmlns="http://www.w3.org/1999/xhtml">
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: <head>
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]:   <meta http-equiv="X-UA-Compatible" content="IE=7" />
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: <meta name="keywords" content="MWG,Proxy" />
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: <title>Huawei Proxy Notification</title>
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: <style type=text/css>
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: body {
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: #011float: none;
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: #011background-color: #CCCCCC;
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: #011text-align: center;
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: #011font-size: 0.75em;
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: #011padding-top: 20px;
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: #011margin: 0 auto;
Jul 20 15:25:49 SZV1000051614 docker/ui[110789]: }

**Comment by juicy12345** [comment]
http://jobservice/api/jobs/replication is access to local  or remote?

**Comment by ywk253100** [comment]
The request "http://jobservice/api/jobs/replication" is sent to a container named jobservice which is running in local.
Recording the logs, the 403 error is returned by Huawei Proxy, not the jobservice, could you check your environment?

**Comment by juicy12345** [comment]
the environment  configures the company proxy, I want to konw how  the request "http://jobservice/api/jobs/replication"  is  sent  to jobservice,  do not need ip? How to access between the container.

**Comment by ywk253100** [comment]
There is an embedded DNS in docker, containers can find each other through it by name.
And what is the error occurred in jobservice?

**Comment by juicy12345** [comment]
Recording to the logs in docker_jobservice.log, there is no error
The logs in docker_jobservice.log :
Jul 20 15:24:56 SZV1000051614 docker/jobservice[110789]: 2016-07-20T07:24:56Z [INFO] Config path: /etc/jobservice/app.conf
Jul 20 15:24:56 SZV1000051614 docker/jobservice[110789]: 2016-07-20T07:24:56Z [DEBUG] [config.go:89]: config: maxJobWorkers: 3
Jul 20 15:24:56 SZV1000051614 docker/jobservice[110789]: 2016-07-20T07:24:56Z [DEBUG] [config.go:90]: config: localUIURL: http://ui
Jul 20 15:24:56 SZV1000051614 docker/jobservice[110789]: 2016-07-20T07:24:56Z [DEBUG] [config.go:91]: config: localRegURL: http://registry:5000
Jul 20 15:24:56 SZV1000051614 docker/jobservice[110789]: 2016-07-20T07:24:56Z [DEBUG] [config.go:92]: config: verifyRemoteCert: off
Jul 20 15:24:56 SZV1000051614 docker/jobservice[110789]: 2016-07-20T07:24:56Z [DEBUG] [config.go:93]: config: logDir: /var/log/jobs
Jul 20 15:24:56 SZV1000051614 docker/jobservice[110789]: 2016-07-20T07:24:56Z [DEBUG] [config.go:94]: config: uiSecret: ******
Jul 20 15:24:56 SZV1000051614 docker/jobservice[110789]: 2016-07-20T07:24:56Z [DEBUG] [base.go:54]: db url: mysql:3306, db user: root
Jul 20 15:24:56 SZV1000051614 docker/jobservice[110789]: 2016-07-20T07:24:56Z [DEBUG] [workerpool.go:123]: worker 0 started
Jul 20 15:24:56 SZV1000051614 docker/jobservice[110789]: 2016-07-20T07:24:56Z [DEBUG] [workerpool.go:123]: worker 1 started
Jul 20 15:24:56 SZV1000051614 docker/jobservice[110789]: 2016-07-20T07:24:56Z [DEBUG] [workerpool.go:123]: worker 2 started
Jul 20 15:24:56 SZV1000051614 docker/jobservice[110789]: 2016-07-20T07:24:56Z [DEBUG] [main.go:36]: Trying to resume halted jobs...
Jul 20 15:24:56 SZV1000051614 docker/jobservice[110789]: 2016/07/20 07:24:56 #033[1;34m[asm_amd64.s:1998][I] http server Running on :80#033[0m

**Comment by reasonerjt** [comment]
seems the jobservice didn't receive the request, could you try remove the proxy and restart harbor?

**Comment by juicy12345** [comment]
根据部署的各个组件的日志文件，没有发现error，push和pull镜像、ldap认证都没有问题，目前就是ui发送给jobservice的请求无法到达jobservice，restart harbor也不起作用，为什么ui 的post 请求http://jobservice/api/jobs/replication找不到jobservice

**Comment by ywk253100** [comment]
把proxy暂时关闭这个问题还会存在吗？

**Comment by reasonerjt** [comment]
@juicy12345 are you still seeing this issue?

**Comment by juicy12345** [comment]
如果把公司proxy关闭也不行，依然会访问公司代理了，但是容器ui  ping  jobservice（ip和容器name）是没有问题的
