### ISSUE TITLE
Error when clicking on a repository

### ISSUE THREAD

**Issue by Benniu** [vmware/harbor#58]
If, for some reason, uploading the first image of a repository failed, you can still see the repository created on UI. However, when click on the repository, an error with HTML code will show up. Please see the snapshot.

<img width="1393" alt="screenshot" src="https://cloud.githubusercontent.com/assets/895096/14097675/2cf01446-f5a6-11e5-9cdc-37600f49241d.png">

**Comment by Benniu** [comment]
Even worse, this happens all the time even if you had successfully pushed an image to that repository. You will never see the images on UI.

**Comment by reasonerjt** [comment]
@Benniu  Could you show me the config.yml of the registry?  Its default location is  **harbor/Deploy/config/registry/config.yml**

**Comment by reasonerjt** [comment]
This seems a bug after upgrading docker registry.

**Comment by reasonerjt** [comment]
I don't reproduce the issue, but seems sometimes the registry will return url without quotes,  will update the code to make it more defensive...
