### ISSUE TITLE
镜像为library/registry:2.4.0的容器STATUS，一直是Restarting (1) xxxxx

### ISSUE THREAD

**Issue by XuChao-918** [vmware/harbor#583]
1）Docker version
# docker --version
Docker version 1.11.2, build b9f10c9

#  docker-compose --version
docker-compose version 1.7.1, build 6c29830

2）Deploy/config/registry/config.yml 文件内容
version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: /datas/harbor_storage
    maintenance:
        uploadpurging:
            enabled: false
    delete:
        enabled: true
http:
    addr: :5009
    secret: placeholder
    debug:
        addr: localhost:5009
auth:
  token:
    issuer: registry-token-issuer
    realm: http://172.16.71.113/service/token
    rootcertbundle: /etc/registry/root.crt
    service: token-service

notifications:
  endpoints:
      - name: harbor
        disabled: false
        url: http://ui/service/notifications
        timeout: 500ms
        threshold: 5
        backoff: 1s

3） docker-compose.yml 文件
version: '2'
services:
  log:
    build: ./log/
    restart: always
    volumes:
      - /var/log/harbor/:/var/log/docker/
    ports:
      - 1514:514
  registry:
    image: library/registry:2.4.0
    restart: always
    volumes:
      - /data/registry:/storage
      - ./config/registry/:/etc/registry/
    environment:
      - GODEBUG=netdns=cgo
    ports:
      - 5001:5001
    command:
      ["serve", "/etc/registry/config.yml"]
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "registry"
  mysql:
    build: ./db/
    restart: always
    volumes:
      - /data/database:/var/lib/mysql
    env_file:
       - ./config/db/env
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "mysql"
  ui:
    build:
      context: ../
      dockerfile: Dockerfile.ui
    env_file:
      - ./config/ui/env
    restart: always
    volumes:
      - ./config/ui/app.conf:/etc/ui/app.conf
      - ./config/ui/private_key.pem:/etc/ui/private_key.pem
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "ui"
  jobservice:
      build:
      context: ../
      dockerfile: Dockerfile.job
    env_file:
      - ./config/jobservice/env
    restart: always
    volumes:
      - /data/job_logs:/var/log/jobs
      - ./config/jobservice/app.conf:/etc/jobservice/app.conf
    depends_on:
      - ui
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "jobservice"
  proxy:
    image: library/nginx:1.9
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
      - registry
      - ui
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "proxy"

4）# tailf /var/log/harbor/2016-07-25/docker_registry.log 
Jul 25 14:31:00 172.19.0.1 docker/registry[21494]: time="2016-07-25T06:31:00.200998815Z" level=info msg="redis not configured" go.version=go1.6.1 instance.id=0c38c542-5b58-481c-9d81-88b1240bfbd9 service=registry version=v2.4.0 
Jul 25 14:31:00 172.19.0.1 docker/registry[21494]: time="2016-07-25T06:31:00.227663906Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.6.1 instance.id=0c38c542-5b58-481c-9d81-88b1240bfbd9 service=registry version=v2.4.0 
Jul 25 14:31:00 172.19.0.1 docker/registry[21494]: time="2016-07-25T06:31:00.228046852Z" level=debug msg="configured \"token\" access controller" go.version=go1.6.1 instance.id=0c38c542-5b58-481c-9d81-88b1240bfbd9 service=registry version=v2.4.0 
Jul 25 14:31:00 172.19.0.1 docker/registry[21494]: time="2016-07-25T06:31:00.228134315Z" level=fatal msg="listen tcp :5009: bind: address already in use" 
Jul 25 14:32:43 172.19.0.1 docker/registry[21494]: time="2016-07-25T06:32:43.123125536Z" level=info msg="debug server listening localhost:5009" 
Jul 25 14:32:43 172.19.0.1 docker/registry[21494]: time="2016-07-25T06:32:43.124324067Z" level=info msg="configuring endpoint harbor (http://ui/service/notifications), timeout=500ms, headers=map[]" go.version=go1.6.1 instance.id=4642282c-cac2-439d-b382-a527f717dc7f service=registry version=v2.4.0 
Jul 25 14:32:43 172.19.0.1 docker/registry[21494]: time="2016-07-25T06:32:43.124402728Z" level=info msg="redis not configured" go.version=go1.6.1 instance.id=4642282c-cac2-439d-b382-a527f717dc7f service=registry version=v2.4.0 
Jul 25 14:32:43 172.19.0.1 docker/registry[21494]: time="2016-07-25T06:32:43.149493501Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.6.1 instance.id=4642282c-cac2-439d-b382-a527f717dc7f service=registry version=v2.4.0 
Jul 25 14:32:43 172.19.0.1 docker/registry[21494]: time="2016-07-25T06:32:43.149911883Z" level=debug msg="configured \"token\" access controller" go.version=go1.6.1 instance.id=4642282c-cac2-439d-b382-a527f717dc7f service=registry version=v2.4.0 
Jul 25 14:32:43 172.19.0.1 docker/registry[21494]: time="2016-07-25T06:32:43.150005243Z" level=fatal msg="listen tcp :5009: bind: address already in use" 

5）备注，安装harbor的机器，同时也安装了OpenStack

6）希望能有专门的文档，介绍harbor哪些服务，使用了哪些端口；如果用户需要修改，应该修改哪里的配置文件，谢谢！

**Comment by reasonerjt** [comment]
The log explains itself quite clearly, there's port conflict on 5009.
 Due to this chunk based on your config file:
http:
**addr: :5009**
secret: placeholder
debug:
**addr: localhost:5009**

**Comment by xiaods** [comment]
this is typo, please update your host port
