### ISSUE TITLE
The API document to create new project is wrong

### ISSUE THREAD

**Issue by tobegit3hub** [vmware/harbor#585]
We're writing harbor Python SDK and found the API document of `POST /projects` to create new project is wrong.

All the parameters are list here and the `name` should be `project_name`.

```
Project {
project_id:	integer
owner_id:	      integer
name:	string
creation_time:	     string
update_time:	  string
deleted:	 integer
user_id:	 integer
owner_name:	 string
public:	 boolean
togglable:	 boolean
current_user_role_id:	integer
repo_count:	integer
}
```

**Comment by reasonerjt** [comment]
@tobegit3hub
We have been focusing on features for new version and some the doc is not accurate, we are walking through to fix them.

Thanks for reporting the issue!

**Comment by tobegit3hub** [comment]
Thanks for all your work. Most document is accurate and we're happy to develop [harbor-py](https://github.com/tobegit3hub/harbor-py), the Python SDK for harbor with the APIs.

**Comment by hainingzhang** [comment]
Thanks for pointing out the error. @tobegit3hub

**Comment by tobegit3hub** [comment]
Thanks for fixing 😃
