### ISSUE TITLE
Can harbor create a new  project name(by default,use username)when  users  use docker commands to login and push private images?

### ISSUE THREAD

**Issue by juicy12345** [vmware/harbor#587]

**Comment by bobbyjunzhang** [comment]
@reasonerjt What do you think?

**Comment by reasonerjt** [comment]
This is just a shortcut, user can always create a project with his username via UI or API.

I personally don't think we need to implement this with hight priority
From architecture perspective, I don't think the token service should bother to create project, it should only generate token based on permission granted to user.
