### ISSUE TITLE
GetRepoFromCache may make APIs reponse 504

### ISSUE THREAD

**Issue by yaxinlx** [vmware/harbor#588]
Now, if Cache.Get("catalog") is missed in GetRepoFromCache function, then the APIs will spend a long time to return. 

It would be better to increase the cache duration and refresh the catalog periodically.

**Comment by reasonerjt** [comment]
yes there's another issue, and will be worked on.

**Comment by reasonerjt** [comment]
What storage are you using and how many images?

**Comment by yaxinlx** [comment]
S3 storage, all docker hub official images.

**Comment by reasonerjt** [comment]
Could you try disable the security of registry and try to list the repositories of the registry?  
How long does it take?

**Comment by reasonerjt** [comment]
Could you list the repositories by calling the API of registry?

**Comment by reasonerjt** [comment]
@yaxinlx , are you working with the one who opened #409

**Comment by yaxinlx** [comment]
@reasonerjt, yes, cherry is my workmate.

> Could you list the repositories by calling the API of registry?

I didn't try other APIs, I just tried the "/api/repositories?project_id=1" API.
"project_id=1" means the project containing the images maintained by docker official.
Repositories can be listed if caching is not missed. Otherwise, 504 is responded.

**Comment by yaxinlx** [comment]
Now in our forked project, we just set the catalog cache never expire and refresh catalog periodically: https://github.com/asiainfoLDP/harbor/commit/a66cf508bddeb81fb9968bd600e345a97edbd575

**Comment by reasonerjt** [comment]
This is no longer a valid code path.
