### ISSUE TITLE
UI issue of administrator view

### ISSUE THREAD

**Issue by hainingzhang** [vmware/harbor#596]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose
2)Config files of harbor, you can get them by packaging "Deploy/config" directory
3)Log files, you can get them by package the /var/log/harbor/ 

If an administrator gives sysAdmin role to a normal user, the user will show "on" for the admin role. When refreshing the page, the user becomes "off" again even though the user is sysadmin already.

**Comment by wknet123** [comment]
Fixed #597

**Comment by reasonerjt** [comment]
Thanks @wknet123
