### ISSUE TITLE
Harbor如何指定Registry地址端口号？

### ISSUE THREAD

**Issue by XuChao-918** [vmware/harbor#607]
假定，我的Registry地址为，my.registry.com；那么镜像则是，my.registry.com/image_name。这是默认部署出来的情况。

现有一个需求，即Registry地址需要为，my.registry.com：端口号的格式 ，比如my.registry.com:4000 ，镜像则为my.registry.com:4000/mysql  .

请问工程师们，怎么做呢？

**Comment by tuxknight** [comment]
改一下compose文件，在 registry 的 ports 里增加       - 4000:5000 的端口映射就好了。
当然这个是compose最基础的用法。

在和harbor的集成中发现的问题是
     
    harbor UI中镜像信息中显示的 Pull命令为 ``docker pull 10.2.4.33/test/mysql:5.6``

因此，加一行配置就能够实现你的需求，但是harbor需要增加对于这类形式的镜像的支持。

**Comment by XuChao-918** [comment]
compose文件里，在 registry 的 ports 里增加 - 4000:5000 的端口映射就好了。
但是在harbor UI中镜像信息中显示的 Pull命令为 ``docker pull 10.2.4.33/test/mysql:5.6``，这应该是一个bug问题吧。
上次，我修改了config/ui/env文件中的REGISTRY_URL=http://registry:5000  为REGISTRY_URL=http://registry:4000   发现./prepare 后，再启动或docker-compose up -d 并不生效。

**Comment by hainingzhang** [comment]
界面中暂时不支持端口现实，我们可以考虑修改一下。

**Comment by XuChao-918** [comment]
谢谢，海宁和众多贡献者

**Comment by tuxknight** [comment]
@XuChao-918  config/ui/env 是给程序用的，prepare程序会根据harbor.cfg的配置替换 config/ui/env 中的某些值，乱改的话肯定会出问题。还是建议把harbor还有registry的这一套东西都理清楚，然后很多问题就能够自己解决了。

**Comment by reasonerjt** [comment]
@tuxknight Thanks for chiming in!

**Comment by ruizhipeng** [comment]
还是稍微想了解下ui db nginx之间的端口方面的配置 有哪些在自定义时可以修改而哪些又是尽量不要变更的呢，感谢
