### ISSUE TITLE
Cannot push image to harbor if using an extra http layer

### ISSUE THREAD

**Issue by Benniu** [vmware/harbor#61]
If setting up harbor behind an nginx proxy or ELB, pushing image to harbor will fail.

That is because in harbor's nginx config, x-fowarded-XXX headers were set again. So harbor nginx will reset the values from first layer nginx or ELB, and the requests will not be routed properly.

Please see this issue: https://github.com/docker/distribution/issues/970

It would be nice if it could be configured in harbor.cfg to indicate where x-forwarded-XXX headers should be set in harbor's nginx.conf

**Comment by reasonerjt** [comment]
@Benniu Thanks for letting us know this issue!  But I don't think it's easy to set that in .cfg file.  We probably will document this and ask user to update the nginx.conf.
Your thought?

**Comment by Benniu** [comment]
Sure, document it is fine.
Maybe you can also think of releasing different versions for different environments. I think running harbor behind ELB/SLB on AWS/Aliyun is a common user case. 
Just my two cents.

**Comment by xiahaoshawn** [comment]
@Benniu Registry will set the upload URL in the Location header which use the value of X-Forwarded-Proto header. Harbor proxy will reset this value. Document this in the troubleshooting section of installation_guide.md
