### ISSUE TITLE
Registry 之间无法连接

### ISSUE THREAD

**Issue by XuChao-918** [vmware/harbor#611]
1）创建了2个Registry ，A和B；
2）在A Registry的项目下，创建一个到B的复制策略，点击测试连接，总是提示连接失败。但是在A机器上能ping通B节点的主机名和IP地址（B也关闭防火墙和selinux）；
3）确定B机器的用户名和密码都是填写正确了的；

4）日志提示

2016-07-30T10:51:37Z [INFO] initializing: repository: library/hello-world, tags: [], source URL: http://registry:5000, destination URL: http://172.16.74.202:4000, insecure: false, destination user: admin

2016-07-30T10:51:37Z [INFO] initialization completed: project: library, repository: library/hello-world, tags: [], source URL: http://registry:5000, destination URL: http://172.16.74.202:4000, insecure: false, destination user: admin

2016-07-30T10:51:37Z [ERROR] [transfer.go:209]: an error occurred while creating project library on http://172.16.74.202:4000 with user admin : failed to create project library on http://172.16.74.202:4000 with user admin: 404 404 page not found

**Comment by XuChao-918** [comment]
![01](https://cloud.githubusercontent.com/assets/12166405/17269916/58b306ea-5688-11e6-96e5-ab184279b8c8.png)

**Comment by ywk253100** [comment]
The endpoint of destination should be the URL of Habor, not the registry. So is B an instance of Harbor? It listens on port 4000? Or it is just a registry.

Besides, please provide the logs under directory /var/log/harbor/.

**Comment by XuChao-918** [comment]
有Registery A（172.16.70.22）和Registery B（172.16.74.202）两个Harbor实例。
在A上创建复制目标到B，点击测试连接时，一直提示“测试连接目标失败，请检查设置。:Internal Server Error”。
1）查看目标B的4000端口是否正常（结果正常）
# ps -ef | grep 4000
root     19800     1  0 Jul30 ?        00:01:28 /usr/bin/docker daemon -H fd:// --insecure-registry autodeploy.huacloud.com:4000 --insecure-registry 172.16.74.202:4000 --insecure-registry autodeploy.chinacloud.com:4000 --insecure-registry 172.16.70.22:4000
root     20107 19800  0 Jul30 ?        00:00:00 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 4000 -container-ip 172.18.0.3 -container-port 5000
root     22424 22394  0 13:53 pts/0    00:00:00 grep --color=auto 4000

2）查看目标B的日志
# tailf /var/log/harbor/2016-08-01/docker_registry.log 
Aug  1 14:04:33 172.18.0.1 docker/registry[19800]: time="2016-08-01T06:04:33.164261541Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.6.1 http.request.host="172.16.74.202:4000" http.request.id=8e4a9e4e-7723-4045-b740-5f0dbaaeb5fa http.request.method=GET http.request.remoteaddr="172.16.70.22:49700" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=67f88a22-510c-44b5-92b9-0feb71c2bac1 service=registry version=v2.4.0 
Aug  1 14:04:33 172.18.0.1 docker/registry[19800]: 172.16.70.22 - - [01/Aug/2016:06:04:33 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "Go-http-client/1.1"
日志内容中，有错误信息，但是看不懂

谢谢！

**Comment by ywk253100** [comment]
Could you package all logs under directory /var/log/harbor for both A and B?

**Comment by XuChao-918** [comment]
[Uploading Harbor_Registry_B.tar.gz…]()
请查阅，谢谢

**Comment by ywk253100** [comment]
The links are invalid.
