### ISSUE TITLE
Error response from daemon: Get https://gradyhost1.eng.platformlab.ibm.com/v1/users/: Service Unavailable

### ISSUE THREAD

**Issue by gradywang** [vmware/harbor#612]
After installing harbor, the portal can login successfully and can create project and user. bur run `docker login gradyhost1.eng.platformlab.ibm.com` failed:
```
# docker login gradyhost1.eng.platformlab.ibm.com
Username: admin
Password:
Error response from daemon: Get https://gradyhost1.eng.platformlab.ibm.com/v1/users/: Service Unavailable
```

I installed harbor on `gradyhost1.eng.platformlab.ibm.com` host, the installation information as following:
```
# docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

# python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

# docker-compose --version
docker-compose version 1.8.0-rc2, build c72c966
```

Attach harbor configuration files:
[config.zip](https://github.com/vmware/harbor/files/391876/config.zip)

Attach log files:
[log.zip](https://github.com/vmware/harbor/files/391879/log.zip)

Cloud someone can do me a favour on this issue? Thanks!

**Comment by reasonerjt** [comment]
please unset proxy in docker configuration file and restart docker

**Comment by gradywang** [comment]
@reasonerjt Thanks a lot, this issue has gone after restarting the docker service.
