### ISSUE TITLE
呼吁Harbor增加删除功能

### ISSUE THREAD

**Issue by openstack-test** [vmware/harbor#616]
Harbor作为一个开源项目，能取得如此骄人成绩，实属不错，也非常好，想开发者们表示崇高敬意。以下几点，纯属一个harbor忠实用户的观点：
1）一个软件的基本功能是具备“增、删、改、查”。使用harbor一段时间后，一直非常苦恼如何删除不需要的东西。

2）比如，这个镜像、这个项目仓库、这个复制策略、这个复制目标，可能是用户在测试时创建的；也有可能创建错了，也可能一段时间后，并不需要了等，出于一个或多个原因，需要有相应的删除功能；

3）删除的一个流程或前提是：当用户停用一个复制策略、仓库时，那么才能执行删除操作；

谢谢

**Comment by bobbyjunzhang** [comment]
@XuChao-918 谢谢你的建议。我们在研究如何在保证审计信息不丢失的情况下提供删除的功能。看你有什么想法。

**Comment by zht452432830** [comment]
http://www.tuicool.com/articles/y26nyar之前一直听说v2的registry也并不支持删除镜像，今天偶然看到这篇文章@bobbyjunzhang

**Comment by zht452432830** [comment]
@bobbyjunzhang 大力支持开发删除功能，看了官方V2的API文档，官方删除镜像功能也是够麻烦的

**Comment by reasonerjt** [comment]
@zht452432830 There's API on harbor to support deleting image.

This issue is for deleting user/rep policy/project

**Comment by zht452432830** [comment]
@reasonerjt Thank you for your reply.I think I should learn more about harbor.

**Comment by ora04301** [comment]
@bobbyjunzhang 要不先提供一个关闭审计的选项吧，不能删除实在是太蛋疼了。。。

**Comment by reasonerjt** [comment]
Closing the issue since the project deletion is supported since 0.4.0
