### ISSUE TITLE
两个registery复制镜像错误

### ISSUE THREAD

**Issue by XuChao-918** [vmware/harbor#624]
1）两个Harbor实例的docker版本都是1.11.2，操作系统都是centos 7.2；
2）两个Registery A和B都可以互相，“新建目标”测试连接成功；
3）在Registery A的library项目下，创建复制策略到B。状态始终提示错误；
如图1
![1](https://cloud.githubusercontent.com/assets/12166405/17321129/90e5fc28-58c9-11e6-8193-2e80128d5a0d.png)
![01](https://cloud.githubusercontent.com/assets/12166405/17321705/8dc47760-58cc-11e6-9c16-79a8de736efa.png)

**说明：**
我的两个Registery端口，都是4000。是否是因为修改了默认的5000端口，而后端的复制功能代码因为读不到5000默认端口而报错呢

**Comment by XuChao-918** [comment]
附件为harbor registry A的日志
[log_harbor_registry_A.tar.gz](https://github.com/vmware/harbor/files/395524/log_harbor_registry_A.tar.gz)

我在Harbor开源项目微信群里的昵称是，徐超@ETITES，谢谢

**Comment by pshizhsysu** [comment]
最后解决了吗？我也遇到了差不多一样的问题，在A上创建到B的复制策略成功，从B创建到A时出错
