### ISSUE TITLE
镜像下载后无法启动

### ISSUE THREAD

**Issue by wangfeiping** [vmware/harbor#626]
操作系统是 CentOS 7 / CentOS-7-x86_64-Minimal-1511.iso
Docker version 1.10.3, build 9419b24-unsupported
docker-compose version 1.8.0, build f3628c7
[config.zip](https://github.com/vmware/harbor/files/398558/config.zip)

镜像下载后无法正常启动
[root@bogon harbor]# docker ps -a
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                      PORTS                   NAMES
b2f154a33ea1        library/nginx:1.9        "nginx -g 'daemon off"   44 seconds ago      Exited (1) 41 seconds ago                           harbor_proxy_1
6a6a4207d7bb        harbor_jobservice        "/go/bin/harbor_jobse"   45 seconds ago      Up 41 seconds                                       harbor_jobservice_1
45a64237f87c        harbor_ui                "/go/bin/harbor_ui"      49 seconds ago      Exited (2) 44 seconds ago                           harbor_ui_1
5e806779fd5e        library/registry:2.4.0   "/bin/registry serve "   49 seconds ago      Exited (1) 44 seconds ago                           harbor_registry_1
e5614152a547        harbor_mysql             "docker-entrypoint.sh"   49 seconds ago      Exited (1) 46 seconds ago                           harbor_mysql_1
bbda266efa3a        harbor_log               "/bin/sh -c 'cron && "   51 seconds ago      Up 49 seconds               0.0.0.0:1514->514/tcp   harbor_log_1
3f947a8131bc        c31768bbdd38             "/bin/sh -c 'apt-get "   22 hours ago        Exited (100) 22 hours ago                           cranky_poitras
78182c0ef970        c31768bbdd38             "/bin/sh -c 'apt-get "   22 hours ago        Exited (100) 22 hours ago                           cocky_turing

harbor_jobservice_1几秒后也会停止，
只有 harbor_log_1 一直运行，
但是登入 harbor_log_1 发现，root账户没有 /var/log/docker 的任何操作权限。
宿主系统下 /var/log/harbor 目录 root权限可以操作，但是没有任何日志。
是在虚拟机中安装的，所以是全root部署操作的，因为完全没有日志，所以无法找到问题在哪里。

查看docker 日志全部是如下信息

[root@bogon harbor]# docker logs -f harbor_log_1
_
rsyslogd: Could not open dynamic file '/var/log/docker/2016-08-03/docker-current_jobservice.log' [state -3000] - discarding message
rsyslogd: Could not open dynamic file '/var/log/docker/2016-08-03/docker-current_jobservice.log' [state -3000] - discarding message
rsyslogd: Could not open dynamic file '/var/log/docker/2016-08-03/CRON.log' [state -3000] - discarding message
rsyslogd: Could not open dynamic file '/var/log/docker/2016-08-03/CRON.log' [state -3000] - discarding message
_

请问是docker版本不正确么？
我通过 yum install docker-io 安装的docker

If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose
2)Config files of harbor, you can get them by packaging "Deploy/config" directory
3)Log files, you can get them by package the /var/log/harbor/

**Comment by reasonerjt** [comment]
Seems these 2 different issues, even the rsyslog failed to write to files other container should not fail.  To debug, you can update the docker-compose.yml remove the log container and remove all the log related settings for different containers and retry.

**Comment by wangfeiping** [comment]
仍然无法启动。
我部署了一个hekad 代替harbor_log_1的日志服务，用nc确认hekad 在tcp 1514端口运行正常。
但是通过docker-compose up -d 启动和之前情况一样，都没有正常启动，hekad接收到的日志：
<30>2016-08-02T23:43:00-04:00 bogon docker-current/ui[2161]: 2016-08-03T03:43:00Z [INFO] Config path: /etc/ui/app.conf
<27>2016-08-02T23:43:00-04:00 bogon docker-current/ui[2161]: panic: runtime error: invalid memory address or nil pointer dereference
<27>2016-08-02T23:43:00-04:00 bogon docker-current/ui[2161]: [signal 0xb code=0x1 addr=0x0 pc=0x4b2412]
<27>2016-08-02T23:43:00-04:00 bogon docker-current/ui[2161]: 
<27>2016-08-02T23:43:00-04:00 bogon docker-current/ui[2161]: goroutine 1 [running]:
<27>2016-08-02T23:43:00-04:00 bogon docker-current/ui[2161]: panic(0xb4f040, 0xc82000a0e0)
<27>2016-08-02T23:43:00-04:00 bogon docker-current/ui[2161]: 	/usr/local/go/src/runtime/panic.go:481 +0x3e6
<27>2016-08-02T23:43:00-04:00 bogon docker-current/ui[2161]: github.com/vmware/harbor/vendor/github.com/astaxie/beego.(*beegoAppConfig).String(0x0, 0xc60ba0, 0xb, 0x0, 0x0)
<27>2016-08-02T23:43:00-04:00 bogon docker-current/ui[2161]: 	/go/src/github.com/vmware/harbor/vendor/github.com/astaxie/beego/config.go:349 +0x172
<27>2016-08-02T23:43:00-04:00 bogon docker-current/ui[2161]: github.com/vmware/harbor/controllers.init.1()
<27>2016-08-02T23:43:00-04:00 bogon docker-current/ui[2161]: 	/go/src/github.com/vmware/harbor/controllers/base.go:218 +0x28b
<27>2016-08-02T23:43:00-04:00 bogon docker-current/ui[2161]: github.com/vmware/harbor/controllers.init()
<27>2016-08-02T23:43:00-04:00 bogon docker-current/ui[2161]: 	/go/src/github.com/vmware/harbor/controllers/signup.go:19 +0x81
<27>2016-08-02T23:43:00-04:00 bogon docker-current/ui[2161]: main.init()
<27>2016-08-02T23:43:00-04:00 bogon docker-current/ui[2161]: 	/go/src/github.com/vmware/harbor/ui/router.go:89 +0x68
<27>2016-08-02T23:43:03-04:00 bogon docker-current/registry[2161]: configuration error: open /etc/registry/config.yml: permission denied
<27>2016-08-02T23:43:03-04:00 bogon docker-current/registry[2161]: 
<27>2016-08-02T23:43:03-04:00 bogon docker-current/registry[2161]: Usage: 
<27>2016-08-02T23:43:03-04:00 bogon docker-current/registry[2161]:   registry serve <config> [flags]
<27>2016-08-02T23:43:03-04:00 bogon docker-current/registry[2161]: Flags:
<27>2016-08-02T23:43:03-04:00 bogon docker-current/registry[2161]:   -h, --help=false: help for serve
<27>2016-08-02T23:43:03-04:00 bogon docker-current/registry[2161]: 
<27>2016-08-02T23:43:03-04:00 bogon docker-current/registry[2161]: 
<27>2016-08-02T23:43:03-04:00 bogon docker-current/registry[2161]: Additional help topics:
<27>2016-08-02T23:43:03-04:00 bogon docker-current/registry[2161]: 
<30>2016-08-02T23:43:03-04:00 bogon docker-current/mysql[2161]: FATAL ERROR: Could not chown directory /var/lib/mysql
<30>2016-08-02T23:43:05-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:05Z [INFO] Config path: /etc/jobservice/app.conf
<30>2016-08-02T23:43:05-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:05Z [DEBUG] [config.go:89]: config: maxJobWorkers: 3
<30>2016-08-02T23:43:05-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:05Z [DEBUG] [config.go:90]: config: localUIURL: http://ui
<30>2016-08-02T23:43:05-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:05Z [DEBUG] [config.go:91]: config: localRegURL: http://registry:5000
<30>2016-08-02T23:43:05-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:05Z [DEBUG] [config.go:92]: config: verifyRemoteCert: on
<30>2016-08-02T23:43:05-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:05Z [DEBUG] [config.go:93]: config: logDir: /var/log/jobs
<30>2016-08-02T23:43:05-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:05Z [DEBUG] [config.go:94]: config: uiSecret: ******
<30>2016-08-02T23:43:05-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:05Z [DEBUG] [base.go:54]: db url: mysql:3306, db user: root
<30>2016-08-02T23:43:05-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:05Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<27>2016-08-02T23:43:06-04:00 bogon docker-current/proxy[2161]: 2016/08/03 03:43:06 [emerg] 1#1: open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
<27>2016-08-02T23:43:06-04:00 bogon docker-current/proxy[2161]: nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
<30>2016-08-02T23:43:07-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:07Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:09-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:09Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:11-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:11Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:13-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:13Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:15-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:15Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:17-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:17Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:20-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:20Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:22-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:22Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:24-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:24Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:26-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:26Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:28-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:28Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:30-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:30Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:32-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:32Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:34-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:34Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:36-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:36Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:38-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:38Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:40-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:40Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:42-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:42Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:44-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:44Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:46-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:46Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:48-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:48Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:50-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:50Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:52-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:52Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:54-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:54Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:56-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:56Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:43:58-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:43:58Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:44:00-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:44:00Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:44:02-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:44:02Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<30>2016-08-02T23:44:04-04:00 bogon docker-current/jobservice[2161]: 2016-08-03T03:44:04Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp: lookup mysql: no such host
<27>2016-08-02T23:44:05-04:00 bogon docker-current/jobservice[2161]: panic: Failed to connect to DB after 60 seconds
<27>2016-08-02T23:44:05-04:00 bogon docker-current/jobservice[2161]: 
<27>2016-08-02T23:44:05-04:00 bogon docker-current/jobservice[2161]: goroutine 1 [running]:
<27>2016-08-02T23:44:05-04:00 bogon docker-current/jobservice[2161]: panic(0x999dc0, 0xc82032a270)
<27>2016-08-02T23:44:05-04:00 bogon docker-current/jobservice[2161]: 	/usr/local/go/src/runtime/panic.go:481 +0x3e6
<27>2016-08-02T23:44:05-04:00 bogon docker-current/jobservice[2161]: github.com/vmware/harbor/dao.InitDB()
<27>2016-08-02T23:44:05-04:00 bogon docker-current/jobservice[2161]: 	/go/src/github.com/vmware/harbor/dao/base.go:74 +0x66e
<27>2016-08-02T23:44:05-04:00 bogon docker-current/jobservice[2161]: main.main()
<27>2016-08-02T23:44:05-04:00 bogon docker-current/jobservice[2161]: 	/go/src/github.com/vmware/harbor/jobservice/main.go:27 +0x18


[root@bogon harbor]# docker-compose start
Starting registry ... done
Starting ui ... done
Starting jobservice ... done
Starting mysql ... done
Starting proxy ... done
ERROR: No containers to start

**Comment by reasonerjt** [comment]
Hmm....my guess is it maybe related to selinux, could you try disabling it on docker daemon?
I run docker daemon with selinux enabled on ubuntu and things work, not sure if something's changed on centos, could you investigate it?

**Comment by wangfeiping** [comment]
@reasonerjt 非常感谢，现在可以启动了，应该是SELinux的问题，禁用重启后，可以启动了。
