### ISSUE TITLE
init mysql tables on local (not run with docker, just for development on Mac), registry.sql report error for timestamp data type (Invalid default value)

### ISSUE THREAD

**Issue by ScorpioCPH** [vmware/harbor#629]
1)Version of docker engine and docker-compose

```
$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64
```

```
$ docker-compose version
docker-compose version 1.8.0, build f3628c7
docker-py version: 1.9.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.2h  3 May 2016
```

2)Config files of harbor, you can get them by packaging "Deploy/config" directory

**_nothing changed**_

3)Log files, you can get them by package the /var/log/harbor/ 

**_no log files**_
# 

**reproduce steps:**

just run `mysql < ./Deploy/db/registry.sql -uroot --verbose`

**erro messager:**

`ERROR 1067 (42000) at line 39: Invalid default value for 'update_time'`

**Comment by ScorpioCPH** [comment]
I think maybe we should specify `DEFAULT CURRENT_TIMESTAMP` after each `timestamp` column

**Comment by reasonerjt** [comment]
We'll review this before next release, since you have a workaround, this maybe low priority.

**Comment by ScorpioCPH** [comment]
@reasonerjt good, i will send my PR for this issue .

**Comment by reasonerjt** [comment]
Closing as fixed.
