### ISSUE TITLE
self_registration configure not work

### ISSUE THREAD

**Issue by seanchann** [vmware/harbor#630]
hi:
   I set self_registration = off in harbor.cfg and exec prepare, but this is not work. In web browser can sign up by self (I clean my local cache on my browser)

 docker： 1.11.1   docker compose：1.7.1, build 0a9ab35

[config.tar.gz](https://github.com/vmware/harbor/files/398821/config.tar.gz)

**Comment by wknet123** [comment]
Fix #632
