### ISSUE TITLE
How to join slack discussion group without vmware.com email

### ISSUE THREAD

**Issue by ScorpioCPH** [vmware/harbor#637]
I want to join discussion group of Project Harbor, but as i have no `@vmware.com` or `@emc.com` email address, how can i create an `vmwarecode.slack.com` account? is there anyway to invite others to join slack? thanks.

**Comment by reasonerjt** [comment]
It's on wechat, please send me an email to tell me your wechat account, I'll send you invitation.

**Comment by ScorpioCPH** [comment]
Good, i have send an email to you, please check it, thanks.

**Comment by ScorpioCPH** [comment]
Done, close.
