### ISSUE TITLE
harbor.cfg and some others local files (certs, keys, nginx.conf) should be "git ignored"

### ISSUE THREAD

**Issue by ecirtap** [vmware/harbor#661]
Hello,

I think it would be better if the following files are git-ignored:

- Deploy/harbor.cfg (renamed to harbor.cfg.dist)
- Deploy/config/nginx/cert/*
- Deploy/config/nginx.conf (renamed to nginx.http.conf)
- Deploy/config/ui/private_key.pem
- Deploy/config/registry/root.crt

They are part of a local configuration, and they should not be on the way of a git pull, neither they should be visible in a git status message. 

Thus, it would be easier to test new versions of Harbor as they are delivered.

Thanks for your feedback !

**Comment by hainingzhang** [comment]
Hi, 

Thanks for your suggestion. 

You can use "git stash" and "git stash pop" commands to preserve and restore your configuration. However, doing so may miss any changes to the config files (such as harbor.cfg) in the new version. We normally suggest users to back up existing Harbor directory and do a clean clone. Then copy back or reference the content in the config files when necessary. Here is a guide for upgrade and migration for your reference:

https://github.com/vmware/harbor/blob/master/docs/migration_guide.md

**Comment by ecirtap** [comment]
Hi
I will not use git to deploy harbor but a tar.gz of harbor and provision over its extraction. 
Thank you for your answer !
