### ISSUE TITLE
docker-compose.yml -- issues with relative context for UI/jobservice

### ISSUE THREAD

**Issue by leepfrog** [vmware/harbor#662]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose
```
docker-compose version 1.8.0, build f3628c7
docker-py version: 1.9.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2h  3 May 2016

Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        
 OS/Arch:      linux/amd64
```

2)Config files of harbor, you can get them by packaging "Deploy/config" directory
N/A

3)Log files, you can get them by package the /var/log/harbor/ 
N/A

Running `docker-compose up` yields:
```
Building ui
ERROR: Cannot locate specified Dockerfile: Dockerfile.ui
```

-- as a workaround --
I've modified the docker-compose.yml by moving it up a directory, and renaming the context paths / mount paths.  It seems like the docker-compose should work with a context path of ../ though.

**Comment by reasonerjt** [comment]
@leepfrog Are you running docker-compose from the **xxx/Deployer** directory?

**Comment by leepfrog** [comment]
I am running from the Deploy directory

**Comment by reasonerjt** [comment]
@leepfrog This is really weird I just double checked with docker-compose 1.8.0 and the context "../" works as expected and I can run "**docker-compose build**" with no errors...

**Comment by leepfrog** [comment]
I believe it might be a centos thing.  I can easily replicate this bug on a fresh install of CentOS 7.0, but not on 7.2.  

Going to go ahead and close for now.
