### ISSUE TITLE
deploy_mysql_1‘s state always be restarting

### ISSUE THREAD

**Issue by zht452432830** [vmware/harbor#665]
docker version 1.11.2 docker-compose version 1.7.1

docker_mysql.log:
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 0 [Note] mysqld (mysqld 5.6.32) starting as process 1 ...
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Plugin 'FEDERATED' is disabled.
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: mysqld: Table 'mysql.plugin' doesn't exist
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] InnoDB: Using atomics to ref count buffer pool pages
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] InnoDB: The InnoDB memory heap is disabled
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] InnoDB: Memory barrier is not used
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] InnoDB: Compressed tables use zlib 1.2.8
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] InnoDB: Using Linux native AIO
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] InnoDB: Using CPU crc32 instructions
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] InnoDB: Initializing buffer pool, size = 128.0M
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] InnoDB: Completed initialization of buffer pool
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [ERROR] InnoDB: auto-extending data file ./ibdata1 is of a different size 0 pages (rounded down to MB) than specified in the .cnf file: initial 768 pages, max 0 (relevant if non-zero) pages!
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [ERROR] InnoDB: Could not open or create the system tablespace. If you tried to add new data files to the system tablespace, and it failed here, you should now edit innodb_data_file_path in my.cnf back to what it was, and remove the new ibdata files InnoDB created in this failed attempt. InnoDB only wrote those files full of zeros, but did not yet use them in any way. But be careful: do not remove old data files which contain your precious data!
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [ERROR] Plugin 'InnoDB' init function returned error.
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [ERROR] Unknown/unsupported storage engine: InnoDB
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [ERROR] Aborting
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Binlog end
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'partition'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_FT_DELETED'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_METRICS'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_CMPMEM'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_CMP_RESET'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_CMP'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_LOCKS'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'INNODB_TRX'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'BLACKHOLE'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'ARCHIVE'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'MRG_MYISAM'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'MyISAM'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'CSV'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'MEMORY'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'sha256_password'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'mysql_old_password'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'mysql_native_password'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] Shutting down plugin 'binlog'
Aug  9 14:47:28 172.22.0.1 docker/mysql[1100]: 2016-08-09 06:47:28 1 [Note] mysqld: Shutdown complete

**Comment by yhua123** [comment]
Hi zht452432830,
Can you give me more detail for this issue? Thanks~
Q: 1) When you found this issue? New install or already run sometimes?
     2) What's your install environment? Ubuntu, Debain or someelse?
    3) Did you change install script? Please post modify part.
    4) docker runtime infomation (docker ps)
    5) host process information (ps -A|grep mysql)
Analysis your posted info, maybe your MYSQL data locked by other process.

**Comment by zht452432830** [comment]
@yhua123 
1)New Install.I just knew the code updated.
2)Centos7.2
3)No.I changed nothing except the "hostname" in harbor.cfg.
4)Only those containers is running:
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                         PORTS                                      NAMES
c84dc72eda69        library/nginx:1.9        "nginx -g 'daemon off"   About an hour ago   Up 10 seconds                  0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   deploy_proxy_1
27bfaa9dd852        deploy_jobservice        "/go/bin/harbor_jobse"   About an hour ago   Up 10 seconds                                                             deploy_jobservice_1
368c2ac17493        deploy_ui                "/go/bin/harbor_ui"      About an hour ago   Up 11 seconds                  80/tcp                                     deploy_ui_1
c1b004557aba        deploy_mysql             "docker-entrypoint.sh"   About an hour ago   Restarting (1) 2 seconds ago   3306/tcp                                   deploy_mysql_1
42da74f0b80e        library/registry:2.4.0   "/bin/registry serve "   About an hour ago   Up 10 seconds                  5000/tcp, 0.0.0.0:5001->5001/tcp           deploy_registry_1
cb2a151d7fc7        deploy_log               "/bin/sh -c 'cron && "   About an hour ago   Up 12 seconds                  0.0.0.0:1514->514/tcp                      deploy_log_1
5)This command got nothing.
There was no problem with running harbor before.But after I update the code and reinstall,the problem has emerged. Before reinstall, I deleted all images and files about harbor including "/data/*".

**Comment by zht452432830** [comment]
While deploy_mysql_1‘s state always be restarting,if I run `docker login myip`:
`Error response from daemon: Get http://myip/v2/: received unexpected HTTP status: 502 Bad Gateway`

**Comment by yhua123** [comment]
Hi Zht,
I tried this issue in our lab,  but can't reproduce.
We use CentOS version: CentOS Linux release 7.2.1511 (Core).
docker ps:
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                      NAMES
f1301f6782dd        library/nginx:1.9        "nginx -g 'daemon off"   2 minutes ago       Up 2 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   deploy_proxy_1
7ad47dc22dc8        deploy_jobservice        "/go/bin/harbor_jobse"   2 minutes ago       Up 2 minutes                                                   deploy_jobservice_1
c5aeab925e09        library/registry:2.4.0   "/bin/registry serve "   2 minutes ago       Up 2 minutes        5000/tcp, 0.0.0.0:5001->5001/tcp           deploy_registry_1
b5abd7c559a0        deploy_ui                "/go/bin/harbor_ui"      2 minutes ago       Up 2 minutes        80/tcp                                     deploy_ui_1
a8a38ea993f6        deploy_mysql             "docker-entrypoint.sh"   2 minutes ago       Up 2 minutes        3306/tcp                                   deploy_mysql_1
7c50a868f5cc        deploy_log               "/bin/sh -c 'cron && "   2 minutes ago       Up 2 minutes        0.0.0.0:1514->514/tcp                      deploy_log_1

Can you check the disk free space? Sometime no use docker images will left on your disk.
my server df status:
Filesystem              1K-blocks    Used Available Use% Mounted on
/dev/mapper/centos-root  52403200 8402836  44000364  17% /
devtmpfs                  3995400       0   3995400   0% /dev
tmpfs                     4005732       0   4005732   0% /dev/shm
tmpfs                     4005732    8964   3996768   1% /run
tmpfs                     4005732       0   4005732   0% /sys/fs/cgroup
/dev/mapper/centos-home  43617476   32928  43584548   1% /home
/dev/sda1                  508588  156796    351792  31% /boot
tmpfs                      801148       0    801148   0% /run/user/0


Another problem is you can't use docker login. 
Harbor supports HTTP by default and Docker client trys to connect to Harbor using HTTPS first, so if you encounter an error as below when you pull or push images, you need to add '--insecure-registry' option to  /etc/sysconfig/docker. And then restart the docker service.

**Comment by zht452432830** [comment]
@yhua123 
I also guess is the old version of the harbor led to the problem.I successfully installed a new version of harbor on another machine.I will try your advice.

**Comment by zht452432830** [comment]
@yhua123 
I found that the disk `/dev/mapper/VolGroup-LogVol01` is full, and then I expand it.Now:
Filesystem                    1K-blocks     Used Available Use% Mounted on
/dev/mapper/VolGroup-LogVol01 459225264 25265572 415005360   6% /
devtmpfs                        1872308        0   1872308   0% /dev
tmpfs                           1887736        0   1887736   0% /dev/shm
tmpfs                           1887736     9212   1878524   1% /run
tmpfs                           1887736        0   1887736   0% /sys/fs/cgroup
/dev/sda2                      20511312    45080  19401272   1% /usr/log
/dev/sda1                        194235   119633     60266  67% /boot
tmpfs                            377548        0    377548   0% /run/user/0
I run `docker rmi deploy_XXX` and rebuild them , but the problem still exists.

**Comment by yhua123** [comment]
sorry, missing your new comments.
after remove deploy_xxx, do you delete the directory of date? [/data]. mySQL put some database files under this directory.

**Comment by zht452432830** [comment]
@yhua123 I remember that I did `[/data]rm * -rf` before updating the code of harbor. After seeing your answer, I did it again. And then there was a miracle. Maybe I forgot to delete the data before.
The problem is solved. Thank you very much.
