### ISSUE TITLE
can't push images

### ISSUE THREAD

**Issue by pennpeng** [vmware/harbor#667]
# docker push  192.168.83.250/docoreos/ubuntu
The push refers to a repository [192.168.83.250/docoreos/ubuntu]
9a39129ae0ac: Retrying in 1 second 
98305c1a8f5e: Retrying in 1 second 
0185b3091e8e: Retrying in 1 second 
ea9f151abb7e: Retrying in 1 second 
unsupportede: Preparing 

The log:
 time="2016-08-10T06:00:03.969547535Z" level=error msg="response completed with error" auth.user.name=admin err.code=unsupported err.message="The operation is unsupported." go.version=go1.6.1 http.request.host=192.168.83.250 http.request.id=a8ccf8c6-3454-4f4f-ab72-2e104d95a9d8 http.request.method=POST http.request.remoteaddr=192.168.83.250 http.request.uri="/v2/docoreos/ubuntu/blobs/uploads/" http.request.useragent="docker/1.12.0 go/go1.6.3 git-commit/8eab29e kernel/4.4.0-34-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=79.803981ms http.response.status=405 http.response.written=78 instance.id=879098df-c9d5-4fc2-a54d-9166ed419b4d service=registry vars.name="docoreos/ubuntu" version=v2.4.0

**Comment by reasonerjt** [comment]
the 405 may be caused by http  proxy, could you double check are you using any proxies on the machine you run the docker command?

**Comment by pennpeng** [comment]
is it a bug?
when i open the registry mirror,it can't push any images ,but when i delete the "proxy remoteurl: https://registry-1.docker.io",it works!!!
some one tell me why??

**Comment by reasonerjt** [comment]
It's the design of docker/distribution, not a bug.

**Comment by reasonerjt** [comment]
see https://docs.docker.com/registry/configuration/

> Pushing to a registry configured as a pull through cache is currently unsupported.
