### ISSUE TITLE
How to login registry when harbor is deploy on kubernetes

### ISSUE THREAD

**Issue by blackpiglet** [vmware/harbor#669]
I use the most recently harbor code to deploy on kubernetes 1.2. 
Harbor works fine. 
I found the access point is at the proxy pod. proxy pod is assigned loadbalancer as the service type, so it has nodePort that can be accessed from network out of kubernetes. 
The problem is when I want to push a image to my project, I don't know docker login to which URL. The proxy's nodePort is used for UI. 

This is the output of proxy svc detail:
kubectl describe svc proxy
Name:			proxy
Namespace:		default
Labels:			name=proxy
Selector:		name=proxy
Type:			LoadBalancer
IP:			10.254.47.44
Port:			http	80/TCP
NodePort:		http	31073/TCP
Endpoints:		10.254.45.9:80
Port:			https	443/TCP
NodePort:		https	31067/TCP
Endpoints:		10.254.45.9:443
Session Affinity:	None
No events.

docker login [host]:31073 will fail. 
I found a workaround. I added "Type: LoadBalancer" in registry-rc.yaml, as a result, registry also had a nodePort, so I had a URL to docker login, but that seems not a perfect solution.
I suppose this should be related to Nginx rule setting, but I am not familiar with that area. Could anyone give some advise?

**Comment by blackpiglet** [comment]
Sorry, guys. I figured it out. 
docker login 10.254.47.44:31067/v2 
This command does what I expect.

**Comment by panpan0000** [comment]
no, it's not the correct way. 
refer to https://github.com/goharbor/harbor/issues/6319

first of all ,the externalURL should be set IP:port, e.g :      `https://10.123.4.5:30402`
you can also `kubectl -n ${namespace} edit  cm my-harbor-core-envvars` to modify `EXT_ENDPOINT` then restart harbor-core pod

then you can 
`docker login  10.123.4.5:30402  -u admin -p  xxxx`
`docker push 10.123.4.5:30402/test/nginx`
