### ISSUE TITLE
Remote Login Issue

### ISSUE THREAD

**Issue by tristanguo** [vmware/harbor#686]
Hey, I deploy Harbor in a remote machine, I use HTTP via port 80.
I can login registry.mydomain.com locally in that machine, but if I try to do the same on my machine, it fails, the error is:

$ docker login registry.mydomain.com
Username: admin
Password:
Error response from daemon: Login: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>

 (Code: 404; Headers: map[Server:[nginx/1.4.6 (Ubuntu)] Date:[Tue, 16 Aug 2016 08:57:25 GMT] Content-Type:[text/html]])

Please Note that I can Login Harbor UI from my machine, only login docker registry fails.

**Comment by ywk253100** [comment]
Provide the logs of Harbor and docker daemon, you can find Harbor's logs in /var/log/harbor.

**Comment by tristanguo** [comment]
Hey, I don't see any log there triggered by my remote login. I am wondering if it doesn't support remote login via http?

**Comment by tristanguo** [comment]
by the way, my machine is Mac, running docker-machine.

if i try:
$ docker login  registry.mydomain.com:80

I got:
Error response from daemon: Get https://registry.bottlesxo.com:80/v1/users/: tls: oversized record received with length 28012

Why it is trying https and v1?

**Comment by ywk253100** [comment]
No log in docker daemon?  Are you running docker in debug mode?

**Comment by tristanguo** [comment]
There are logs of course.
I meant when I do remote login, I see no new logs.

**Comment by ywk253100** [comment]
Maybe you should check your network environment first if there is no any logs in both docker daemon and Harbor.

**Comment by reasonerjt** [comment]
Guys, any update?

**Comment by tristanguo** [comment]
I think Non-HTTPS registry is not allowed for remote access right? If yes, this issue can be closed.

**Comment by ywk253100** [comment]
It is supported. 

There is no log in Harbor, that means the request did not reach the Harbor. So you should check the client's configuration and environment.

Is registry.mydomain.com available in your MAC, trying ping registry.mydomain.com.
If ping works well, make sure the url used in docker login command matches the configuration in "insecure registry". Noted the port 80 in the end of url.

**Comment by tristanguo** [comment]
Hey, I am navigate Harbor UI and do whatever I want, that means the domain has no problem.
And, I can do $ docker login registry.....com on server machine, meaning the registry setting on config is also correct.
I don't know what else I can check, It seems in my local machine, when doing docker login, it is trying to access V1 of the registry so gets 404...

**Comment by ywk253100** [comment]
Docker client will try V2 first, if it fails it will try V1. So the V1 error is not the cause of the issue. You need to set "insecure registry" in client side(your docker), not the registry side(Harbor).
