### ISSUE TITLE
How can view the release notes for each release

### ISSUE THREAD

**Issue by rajpolaris** [vmware/harbor#696]
We are currently on 0.3.0 and we saw a new release. We are trying to determine what changed between the 0.3.0 and latest release.

Thanks

**Comment by reasonerjt** [comment]
The 0.3.5 is bugfix release, no new features to be introduced

**Comment by biolounge** [comment]
Where can I find the installed version of Harbor in the Harbour-UI?
Is there a release roadmap page available?

**Comment by hainingzhang** [comment]
Release note can be found here: https://github.com/vmware/harbor/blob/master/CHANGELOG.md
Roadmap is here: https://github.com/vmware/harbor/blob/master/ROADMAP.md

In the latest version of Harbor, you can check version of Harbor under "About" menu.
