### ISSUE TITLE
Harbor是否支持私有仓库

### ISSUE THREAD

**Issue by marvelliu** [vmware/harbor#700]
hi 开发者：

昨天试用了一下harbor，非常不错。不过我有一个需求没得到答案。

假设系统有多个用户，用户A可以上传自己的私有镜像（如devel/apache2、devel/mysql），默认不能给别人（如用户B）下载。只有当用户A授权用户B下载devel/apache2，用户B才可以下载，但不能更新。

目前我看harbor是允许有私有的project，如上例的devel，但貌似没有私有仓库，所以如果我要做控制，只能对devel整个做访问控制，而不能对单个镜像/仓库做控制，不知这个能否解决？

@bobbyjunzhang

**Comment by reasonerjt** [comment]
Currently the granularity is per project , not per repo/image

**Comment by marvelliu** [comment]
so is there any blueprint that individual repo/image can be controlled?

**Comment by reasonerjt** [comment]
No

**Comment by hainingzhang** [comment]
Not an issue. Close it for now. Please reopen if needed.
