### ISSUE TITLE
Call Harbor Api and get 401 error

### ISSUE THREAD

**Issue by gf-chen40** [vmware/harbor#703]
I call harbor api with java. And I wrote RestMethod like GET,POST,PUT,DELETE.
First calling api on swagger ui is ok.
Then I try to call api with java and got error "401 User need to log in first." I had login with docker login -u admin -p Harbor ip and can push image to the registry. Do I need another login in java code?
**here is the logs**

**ERROR(calling GET /api/users?username=cgf)**
==> ./docker_ui.log <==
Aug 22 16:16:38 172.19.0.1 docker/ui[937]: 2016-08-22T08:16:38Z [DEBUG] [base.go:127]: No valid user id in session.
Aug 22 16:16:38 172.19.0.1 docker/ui[937]: 2016-08-22T08:16:38Z [WARNING] No user id in session, canceling request

==> ./docker_proxy.log <==
Aug 22 16:16:38 172.19.0.1 docker/proxy[937]: 10.19.157.59 - - [22/Aug/2016:08:16:38 +0000] "GET /api/projects/1/members/ HTTP/1.1" 401 0 "-" "Apache-HttpClient/4.1.3 (java 1.5)"

**SUCCESS(calling GET /api/projects?project_name=lib)**
==> ./CRON.log <==
Aug 22 08:17:01 b3b62d943250 CRON[18]: pam_env(cron:session): Unable to open env file: /etc/default/locale: No such file or directory
Aug 22 08:17:01 b3b62d943250 CRON[18]: pam_unix(cron:session): session opened for user root by (uid=0)
Aug 22 08:17:01 b3b62d943250 CRON[19]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 22 08:17:01 b3b62d943250 CRON[18]: pam_unix(cron:session): session closed for user root

==> ./docker_ui.log <==
Aug 22 16:17:02 172.19.0.1 docker/ui[937]: 2016/08/22 08:17:02 #033[1;34m[router.go:829][D] | GET        | /api/projects                            | 2.715177ms       | match      | /api/projects/                           | #033[0m

==> ./docker_proxy.log <==
Aug 22 16:17:02 172.19.0.1 docker/proxy[937]: 10.19.157.59 - - [22/Aug/2016:08:17:02 +0000] "GET /api/projects?project_name=lib&is_public=1 HTTP/1.1" 200 323 "-" "Apache-HttpClient/4.1.3 (java 1.5)"

1)Version of docker engine and docker-compose
Docker version 1.11.2, build b9f10c9
docker-compose version 1.6.2, build 4d72027

2)Config files of harbor, you can get them by packaging "Deploy/config" directory
Nothing special change in harbor.cfg. only changed the hostname = ip

**Comment by ywk253100** [comment]
You can call the APIs of Harbor with basic auth.
