### ISSUE TITLE
db容器无法正常启动

### ISSUE THREAD

**Issue by yujianglei** [vmware/harbor#707]
1.环境说明
[root@Docker Deploy]# docker-compose  --version
docker-compose version 1.8.0, build f3628c7
[root@Docker Deploy]# docker  --version
Docker version 1.10.3, build d381c64-unsupported

2.报错日志
log_1         | rsyslogd: Could not open dynamic file '/var/log/docker/2016-08-22/docker-current_jobservice.log' [state -3000] - discarding message
log_1         | rsyslogd: Could not open dynamic file '/var/log/docker/2016-08-22/docker-current_jobservice.log' [state -3000] - discarding message
log_1         | rsyslogd: Could not open dynamic file '/var/log/docker/2016-08-22/docker-current_mysql.log' [state -3000] - discarding message
ui_1          | 2016-08-22T17:38:35Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp 172.18.0.4:3306: getsockopt: connection refused
log_1         | rsyslogd: Could not open dynamic file '/var/log/docker/2016-08-22/docker-current_ui.log' [state -3000] - discarding message
ui_1          | 2016-08-22T17:38:37Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp 172.18.0.4:3306: getsockopt: connection refused
log_1         | rsyslogd: Could not open dynamic file '/var/log/docker/2016-08-22/docker-current_ui.log' [state -3000] - discarding message
ui_1          | 2016-08-22T17:38:40Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp 172.18.0.4:3306: getsockopt: connection refused
log_1         | rsyslogd: Could not open dynamic file '/var/log/docker/2016-08-22/docker-current_ui.log' [state -3000] - discarding message
ui_1          | 2016-08-22T17:38:42Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp 172.18.0.4:3306: getsockopt: connection refused
log_1         | rsyslogd: Could not open dynamic file '/var/log/docker/2016-08-22/docker-current_ui.log' [state -3000] - discarding message
ui_1          | 2016-08-22T17:38:44Z [ERROR] [base.go:66]: failed to connect to db, retry after 2 seconds :dial tcp 172.18.0.4:3306: getsockopt: connection refused
log_1         | rsyslogd: Could not open dynamic file '/var/log/docker/2016-08-22/docker-current_ui.log' [state -3000] - discarding message
jobservice_1  | Error running logs job: configured logging reader does not support reading
deploy_jobservice_1 exited with code 0
log_1         | rsyslogd: Could not open dynamic file '/var/log/docker/2016-08-22/docker-current_jobservice.log' [state -3000] - discarding message
log_1         | rsyslogd: Could not open dynamic file '/var/log/docker/2016-08-22/docker-current_jobservice.log' [state -3000] - discarding message
log_1         | rsyslogd: Could not open dynamic file '/var/log/docker/2016-08-22/docker-current_jobservice.log' [state -3000] - discarding message

**Comment by ywk253100** [comment]
It seems that you have no permissions to read or write the directory /var/log/docker inside container log_1. The directory is mapped into /var/log/harbor on host. Could you check whether you have the right permissions to the directory both in and out container?

**Comment by reasonerjt** [comment]
Looks like selinux, try disabling it.

**Comment by yujianglei** [comment]
Problems caused by docker version。Now it has been resolved.  @ywk253100   @reasonerjt   thank you.
