### ISSUE TITLE
Replicating images ERROR

### ISSUE THREAD

**Issue by feblilac** [vmware/harbor#708]
I have setup Harbor on Azure's VM and use Azure's storage account.
When I test image replication,I got some error as belows:

2016-08-23T03:43:24Z [INFO] transferring blob sha256:12345xxxxxxxxx of test/php-example:v1.0 to http://xxxxxxxxxxxx ...
2016-08-23T03:43:24Z [ERROR] [transfer.go:379]: an error occurred while pulling blob sha256:12345xxxxxxxxx of test/php-example:v1.0 from http://registry:5000: 400 <?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidAuthenticationInfo</Code><Message>Authentication information is not given in the correct format. Check the value of Authorization header.
RequestId:f45c05cd-0001-004e-66f0-fc36b3000000
Time:2016-08-23T03:43:24.7990208Z

The project "test" is belongs to admin,it's a private project.
docker version: 1.12.0, build 8eab29e
docker-compose version: 1.7.1, build 0a9ab35
harbor branch: master

**Comment by reasonerjt** [comment]
@feblilac  thanks for reporting.
Is "test" also hosted on Harbor?
Did you set the credentials of the destination correctly?

**Comment by feblilac** [comment]
I have setup two Harbor. The project "test" is belongs to admin. When I use "filesystem" storage ,replication is success. If I change storage to "Azure account" (both two Harbor has changed),some error(as mentioned earlier) occurs.BTW I have modified proxy's port map use 8080
ports:
      - 8080:80
      - 443:443

**Comment by ywk253100** [comment]
Have you modified the config.yml of registry to listen on a customized port as mentioned  in https://github.com/vmware/harbor/blob/master/docs/installation_guide.md#configuring-harbor-listening-on-a-customized-port?

**Comment by feblilac** [comment]
Yes,I modify config.yml like this:
auth:
  token:
    issuer: registry-token-issuer
    realm: $ui_url:8080/service/token
    rootcertbundle: /etc/registry/root.crt
    service: token-service

Everything is well when I use "filesystem" storage,but if change to "Azure",it has error.

**Comment by ywk253100** [comment]
Did you set the credentials for Azure correctly? Could you call Azure service directly to verify the configuration?
If it does not work, please provide the source Harbor's logs of ui and registry under directory /var/log/harbor.

**Comment by ywk253100** [comment]
Closing due to no further details provided.
