### ISSUE TITLE
Should project public be int or boolean?

### ISSUE THREAD

**Issue by gf-chen40** [vmware/harbor#710]
In a project class, public should be boolean
Project {
...
**public (boolean, optional): The public status of the project. ,**
...
}
But in a json which GET /project return, it will be a int
  {
....
    **"public": 1,**
...
  }
Is it reasonable?
harbor 0.3.0

**Comment by reasonerjt** [comment]
@yhua123 seems we should clean that up?

**Comment by yhua123** [comment]
done.
already submit code on harbor/dev

**Comment by reasonerjt** [comment]
let's know the pr No. and you can close this issue @yhua123

**Comment by yhua123** [comment]
#750
