### ISSUE TITLE
Access manifests via token got error="insufficient_scope"

### ISSUE THREAD

**Issue by vickiyan** [vmware/harbor#714]
execute curl -i http://10.45.32.169/v2/yw12345/nginx/manifests/latest got error:
----
HTTP/1.1 401 Unauthorized
Server: nginx/1.9.15
Date: Wed, 24 Aug 2016 11:17:18 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 145
Connection: keep-alive
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Bearer realm="http://10.45.32.169/service/token",service="token-service",scope="repository:yw12345/nginx:pull"

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Name":"yw12345/nginx","Action":"pull"}]}]}
-----------------------------------------
then I execute "http://10.45.32.169/service/token?service=token-service&scope=repository:yw12345/nginx:pull" and got token returned.
---------------
{
  "expires_in": 300,
  "issued_at": "2016-08-24T11:17:52Z",
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJS....
}

then i request manifest with the token like below:-
$TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJS....
$curl -i -H "Authorization: Bearer $TOKEN" http://10.45.32.169/v2/yw12345/nginx/manifests/latest
it still return error:
---------------
HTTP/1.1 401 Unauthorized
Server: nginx/1.9.15
Date: Wed, 24 Aug 2016 10:47:01 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 145
Connection: keep-alive
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Bearer realm="http://10.45.32.169/service/token",service="token-service",scope="repository:yw12345/nginx:pull",error="insufficient_scope"

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Name":"yw12345/nginx","Action":"pull"}]}]}
---------------------------------

However, I've tried the same approach to access /v2/_catalog with token, it could return repositories successfully. 

Does anyone know what caused the insufficient_scope error？ From error message, the scope seems to be correct.  I want to fetch complete manifest of the repository instead of the one exposed by Harbor swagger-api.  Thanks!

**Comment by ywk253100** [comment]
Did you send the valid authentication info with the request to get token? Does the user has read right to yw12345/nginx?
Could you provide the logs of ui under directory /var/log/harbor when you send the request to get token?
An improvement of manifest API which returns the complete information has been merged into branch dev, and will be merged into branch master soon.

**Comment by vickiyan** [comment]
@ywk253100 , I'm wondering how to send the user authentication info with the request to get token? Below is the url I used to get token, it doesn't include the user information. I guess that might be the problem cause.
http://10.45.32.169/service/token?service=token-service&scope=repository:yw12345/nginx:pull

I'll provide you the logs of ui tomorrow when back to office. 
Thanks,
Yan

**Comment by reasonerjt** [comment]
@vickiyan please provide the curl command you used to get the token.

**Comment by vickiyan** [comment]
i've just added "Authorization: Basic xxxx" Header to the curl command to get token and it could works!

Thanks!
