### ISSUE TITLE
cannot GC registry with error "failed to garbage collect: error enumerating blobs: filesystem"

### ISSUE THREAD

**Issue by vickiyan** [vmware/harbor#719]
Hi, 
I tried to GC registry with below command but got error:failed to garbage collect: error enumerating blobs: filesystem: Path not found: /docker/registry/v2/blobs

root@4f275b5aa40e:/storage# registry garbage-collect --dry-run /etc/docker/registry/config.yml               

I found in /etc/docker/registry/config.yml , the registry rootdirectory points to /var/lib/registry, but it should point to /storage directory.   
-------------
version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        blobdescriptor: inmemory
    filesystem:
        rootdirectory: /var/lib/registry
http:
    addr: :5000
    headers:
---------------------------------------

The config file should map with the config/repository/config.yml file when running docker-compose up -d .
Not sure why the rootdirectory changes and how to correct it in order to do GC successfully? 

Thanks!
-Yan

**Comment by ywk253100** [comment]
You can do GC following the [user guide](https://github.com/vmware/harbor/blob/master/docs/user_guide.md#deleting-repositories).

**Comment by vickiyan** [comment]
Yes, it works, thanks a lot!
