### ISSUE TITLE
Add Kubernetes as a hosting platform for Harbor

### ISSUE THREAD

**Issue by xinzhangcmu** [vmware/harbor#72]
Currently Harbor's components (proxy, UI, registry, etc) run in an unmanaged fashion (and probably as single instances). We may leverage Kubernetes as the hosting platform so that we could:

- use replication controller, daemon set, autoscaler, health check, and monitoring to auto-manage Harbor's components, in pursuit of higher availability and scalability

- use rolling-update to manage new releases of Harbor

- use config map to elegantly support different settings

We could start with defining the Pod/RC/Service files for Harbor's components, and later make a Turn-Key solution with 1-click-installation on K8s.

**Comment by ywk253100** [comment]
Thanks for the suggestion. We will support swarm and k8s to host Harbor.

**Comment by bobbyjunzhang** [comment]
@xinzhangcmu We would love to work with you on this! Since you guys are k8s experts, would you like to give it a shot first? We will provide whatever support needed. Thanks.

**Comment by xinzhangcmu** [comment]
We'll give it a shot!

**Comment by xinzhangcmu** [comment]
@perphaszzy and @xj6 are working on this, and found #80, it won't block submitting the K8s yaml files, but it makes the deployment not working end to end

**Comment by reasonerjt** [comment]
We are fixing it.

**Comment by bobbyjunzhang** [comment]
The discussion continues at #97.

**Comment by xinzhangcmu** [comment]
done, closing
