### ISSUE TITLE
Database backup is not working

### ISSUE THREAD

**Issue by biolounge** [vmware/harbor#728]
I was trying to backup the database using the steps mentioned in migration_guide.md.
When I run the below command after creating the directory, I am getting "MySQL Community Server 5.6.32 is not running" message and its not creating any backup.

$docker run -ti --rm -v /data/database:/var/lib/mysql -v /data/database/backup:/harbor-migration/backup migrate-tool backup

Trying to start mysql server...
nohup: redirecting stderr to stdout
MySQL Community Server 5.6.32 is not running.
MySQL Community Server 5.6.32 is not running.
MySQL Community Server 5.6.32 is not running.
MySQL Community Server 5.6.32 is not running.
MySQL Community Server 5.6.32 is not running.
MySQL Community Server 5.6.32 is not running.
MySQL Community Server 5.6.32 is not running.
MySQL Community Server 5.6.32 is not running.
MySQL Community Server 5.6.32 is not running.
MySQL Community Server 5.6.32 is not running.

Could you suggest a way to fix it?

**Comment by reasonerjt** [comment]
it's probably because another mysqld is using that directory, could you check？

**Comment by biolounge** [comment]
Thanks! 
There was an another mysqld process was running. I stopped it and run the command again.
It works! 

$docker run -ti --rm -v /data/database:/var/lib/mysql -v /data/database/backup:/harbor-migration/backup migrate-tool backup
Trying to start mysql server...
nohup: redirecting stderr to stdout
MySQL Community Server 5.6.32 is not running.
MySQL Community Server 5.6.32 is running.
Performing backup...
Backup performed.
