### ISSUE TITLE
hey man,Can do a Centos7 install configuration document?

### ISSUE THREAD

**Issue by ghoul008** [vmware/harbor#73]
i see 0.1.0 is just for ubuntu 14

**Comment by guruprasadbhavsar** [comment]
This might help!

`https://www.vultr.com/docs/how-to-install-harbor-on-centos-7`

**Comment by clouderati** [comment]
In general Harbor _should_ work on all Linux distributions as long as `docker` and `docker-compose` is available. Please feel free to submit a PR to improve the documentation, though. Would be greatly appreciated!
