### ISSUE TITLE
获取用户日志数据失败 Internal error

### ISSUE THREAD

**Issue by wuxian1987** [vmware/harbor#732]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose
2)Config files of harbor, you can get them by packaging "Deploy/config" directory
3)Log files, you can get them by package the /var/log/harbor/ 
when i want to login harbor from web page,then  "获取用户日志数据失败 Internal error" appear...
Why???

**Comment by ywk253100** [comment]
Please provide the logs under directory /var/log/harbor.

**Comment by wuxian1987** [comment]
[root@mesos1 2016-08-30]# more CRON.log 
Aug 30 00:17:01 ce878db18587 CRON[152]: pam_env(cron:session): Unable to open env file: /etc/default/locale: No such file or directo
ry
Aug 30 00:17:01 ce878db18587 CRON[152]: pam_unix(cron:session): session opened for user root by (uid=0)
Aug 30 00:17:01 ce878db18587 CRON[153]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 30 00:17:01 ce878db18587 CRON[152]: pam_unix(cron:session): session closed for user root
Aug 30 01:17:01 ce878db18587 CRON[17]: pam_env(cron:session): Unable to open env file: /etc/default/locale: No such file or director
y
Aug 30 01:17:01 ce878db18587 CRON[17]: pam_unix(cron:session): session opened for user root by (uid=0)
Aug 30 01:17:01 ce878db18587 CRON[18]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 30 01:17:01 ce878db18587 CRON[17]: pam_unix(cron:session): session closed for user root
Aug 30 02:17:01 ce878db18587 CRON[26]: pam_env(cron:session): Unable to open env file: /etc/default/locale: No such file or director
y
Aug 30 02:17:01 ce878db18587 CRON[26]: pam_unix(cron:session): session opened for user root by (uid=0)
Aug 30 02:17:01 ce878db18587 CRON[27]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 30 02:17:02 ce878db18587 CRON[26]: pam_unix(cron:session): session closed for user root



[root@mesos1 2016-08-30]# more docker_jobservice.log 
Aug 30 09:04:59 mesos1 docker/jobservice[11351]: 2016-08-30T01:04:59Z [INFO] Config path: /etc/jobservice/app.conf
Aug 30 09:04:59 mesos1 docker/jobservice[11351]: 2016-08-30T01:04:59Z [DEBUG] [config.go:89]: config: maxJobWorkers: 3
Aug 30 09:04:59 mesos1 docker/jobservice[11351]: 2016-08-30T01:04:59Z [DEBUG] [config.go:90]: config: localUIURL: http://ui
Aug 30 09:04:59 mesos1 docker/jobservice[11351]: 2016-08-30T01:04:59Z [DEBUG] [config.go:91]: config: localRegURL: http://registry:5
000
Aug 30 09:04:59 mesos1 docker/jobservice[11351]: 2016-08-30T01:04:59Z [DEBUG] [config.go:92]: config: verifyRemoteCert: on
Aug 30 09:04:59 mesos1 docker/jobservice[11351]: 2016-08-30T01:04:59Z [DEBUG] [config.go:93]: config: logDir: /var/log/jobs
Aug 30 09:04:59 mesos1 docker/jobservice[11351]: 2016-08-30T01:04:59Z [DEBUG] [config.go:94]: config: uiSecret: ******
Aug 30 09:04:59 mesos1 docker/jobservice[11351]: 2016-08-30T01:04:59Z [INFO] token expiration: 30 minutes
Aug 30 09:04:59 mesos1 docker/jobservice[11351]: 2016-08-30T01:04:59Z [DEBUG] [base.go:54]: db url: mysql:3306, db user: root
Aug 30 09:04:59 mesos1 docker/jobservice[11351]: 2016-08-30T01:04:59Z [DEBUG] [workerpool.go:123]: worker 0 started
Aug 30 09:04:59 mesos1 docker/jobservice[11351]: 2016-08-30T01:04:59Z [DEBUG] [workerpool.go:123]: worker 1 started
Aug 30 09:04:59 mesos1 docker/jobservice[11351]: 2016-08-30T01:04:59Z [DEBUG] [workerpool.go:123]: worker 2 started
Aug 30 09:04:59 mesos1 docker/jobservice[11351]: 2016-08-30T01:04:59Z [DEBUG] [main.go:36]: Trying to resume halted jobs...
Aug 30 09:04:59 mesos1 docker/jobservice[11351]: 2016-08-30T01:04:59Z [WARNING] Failed to reset all running jobs to pending, error: 
Error 1146: Table 'registry.replication_job' doesn't exist
Aug 30 09:04:59 mesos1 docker/jobservice[11351]: 2016-08-30T01:04:59Z [WARNING] Failed to jobs to resume, error: Error 1146: Table '
registry.replication_job' doesn't exist
Aug 30 09:05:01 mesos1 docker/jobservice[11351]: 2016/08/30 01:05:01 #033[1;34m[asm_amd64.s:1998][I] http server Running on :80#033[
0m

**Comment by ywk253100** [comment]
Is there no docker_ui.log?

**Comment by reasonerjt** [comment]
@wuxian1987 seems you need to upgrade DB.

**Comment by reasonerjt** [comment]
@wuxian1987 any update on this issue?

**Comment by hainingzhang** [comment]
No response for a long time. Close it for now. Please reopen if needed.
