### ISSUE TITLE
Proposal: add support to define pattern of tags to be replicated in the replication policy

### ISSUE THREAD

**Issue by quickwind** [vmware/harbor#734]
The use case would be: there is development harbor, which will have more frequent builds of image for testing, but in staging harbor there should be only prerelease version of images, and in production harbor there should be only final release version of images. Admin can setup replication policy for the project so that only prerelease version of images will be replicated to staging harbor and only release version of images will be replicated to production harbor.

**Comment by reasonerjt** [comment]
Thanks for the suggestion, it's on our roadmap in 4Q, but how do you suggest the pattern of tag to be looked like?

Do you prefer regular expression or simple wildcard like "?","*"

**Comment by quickwind** [comment]
@reasonerjt I think simple wildcard pattern should be enough. Thanks.

**Comment by quickwind** [comment]
@reasonerjt I have implemented this using regexp way (more powerful to support more cases), so basically 2 new attributes for a policy "repo_pattern", and "tag_pattern", repo_pattern defines which repo in the project will be replicated, tag_pattern defines which tags will be replicated. If needed, I can create a PR.

**Comment by reasonerjt** [comment]
It's supported right now, closing as fixed.
