### ISSUE TITLE
syslog-tag not supported on docker >=1.12.1

### ISSUE THREAD

**Issue by tronicum** [vmware/harbor#740]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose
docker-engine 1.12.1
docker-compose 1.8.0

docker-compose up fails with

```
Creating harbor_log_1
Creating harbor_registry_1
Creating harbor_mysql_1
Creating harbor_ui_1

ERROR: for ui  Cannot create container for service ui: unknown log opt 'syslog-tag' for syslog log driver

ERROR: for registry  Cannot create container for service registry: unknown log opt 'syslog-tag' for syslog log driver

ERROR: for mysql  Cannot create container for service mysql: unknown log opt 'syslog-tag' for syslog log driver
```

setting syslog-tag to tag in docker-compose.yml fixes this error

**Comment by reasonerjt** [comment]
Which build are you using? It's been changed in docker-compose.yml for a while.. 
"syslog-tag" -> "tag"

**Comment by tronicum** [comment]
> Which build are you using? It's been changed in docker-compose.yml for a while.. 
> "syslog-tag" -> "tag"
> 
I used 0.3.0 because I did not find an tar.gz for the 0.3.5-RC. We wanted to have a look before setting up an build host for it. 

Greetings & thanks, 
    tronicum

**Comment by reasonerjt** [comment]
We pushed the 0.3.5 images to docker hub, and you can get the tarball with script to pull image and bring up Harbor.  You can have a try of that.

**Comment by tronicum** [comment]
upgraded via https://github.com/vmware/harbor/releases/download/0.3.5/harbor-installer.tgz (0.3.5-rc) worked without any errors.
