### ISSUE TITLE
Open project with lots of repositories is slow because it tries to load all the repo's manifests when openning

### ISSUE THREAD

**Issue by quickwind** [vmware/harbor#764]
This could be enhanced to only load the manifest for a repo's tag when details button is clicked.

**Comment by wknet123** [comment]
We'll make it as lazy loading when the button is clicked. Thanks!

**Comment by wknet123** [comment]
Fixed by #769

**Comment by quickwind** [comment]
@wknet123 Thanks, I had one comment though, see in the PR comment....I merged into our repo with my modifications, it works.

**Comment by wknet123** [comment]
This issue has been fixed on 'dev' branch, which will be merged to master on the mid-September.

**Comment by wknet123** [comment]
Some workarounds has been made with #773.
