### ISSUE TITLE
How to login with restful API? or authentication?

### ISSUE THREAD

**Issue by zhangsm** [vmware/harbor#774]

**Comment by ywk253100** [comment]
Basic auth is supported.

**Comment by zhangsm** [comment]
19:15:24 › curl -i -X POST --data '{"username": "admin", "password": "Harbor12345"}' http://domian.x/login
HTTP/1.1 401 Unauthorized
Server: nginx/1.9.15
Date: Wed, 07 Sep 2016 11:15:29 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 0
Connection: keep-alive
Set-Cookie: beegosessionID=4a16baf8ed5a85a3f0c766733a8672b2; Path=/; HttpOnly
Set-Cookie: language=en-US; Path=/

**Comment by zhangsm** [comment]
that's ok
