### ISSUE TITLE
Cannot Delete Registry Repository

### ISSUE THREAD

**Issue by vickiyan** [vmware/harbor#775]
Hi, 
From Harbor's Delete Repository Swagger API, we can only delete Image. How to delete the repository if the repository contains no images (no tags related with the repository)?  Because we don't want to list the repository if there is no images in it.

Thanks,
Yan

**Comment by ywk253100** [comment]
Due to the [bug](https://github.com/docker/distribution/issues/1615) of registry, the API lists repositories which contain no image in it for now. You can filter them by the "repo_count" field which is 0 when no image in the repository. 
An enhancement is in progress and will be available soon.

**Comment by vickiyan** [comment]
Where to set the repo_count field? Can you explain more details? Thanks!

**Comment by ywk253100** [comment]
Update the last comment.
