### ISSUE TITLE
Default NAT network‘s performance is poor

### ISSUE THREAD

**Issue by xiaoping378** [vmware/harbor#780]
I'm just worried about the default bridge network performance, Should we use  **hosts Network Driver** default ?  because the project harbor called "An enterprise-class container registry server".

related docker issue is [here](https://github.com/docker/docker/issues/7857)

**Comment by xiaoping378** [comment]
when i tried to change the bridge mode  to hosts, i met too many errors...

**Comment by reasonerjt** [comment]
what is hosts network driver? I think you mean the host network mode?  By default we'll use bridge as other option such as ipvlan is 1.12 only.  If you switch to host network not sure how dns will work I haven't try, if you want to change you may need to figure out yourself

**Comment by xiaoping378** [comment]
so the default bridge mode is OK? 
i mean the performance is acceptable ?

**Comment by xiaoping378** [comment]
proxy, ui and job_service both need bind the port 80.
i have changed to host mode, and docker-compose up OK
but i don't know what the job_service is, Just change the port of job_service to 8000 , Now i can't docker push images OK ....
Hi @reasonerjt , how should i do ?

**Comment by reasonerjt** [comment]
If you cannot figure out I suggest not use host mode for now.

**Comment by xiaoping378** [comment]
OK, Thanks.
