### ISSUE TITLE
Harbor should not display private repositories in the home page - 2ed

### ISSUE THREAD

**Issue by ecirtap** [vmware/harbor#783]
Hello,

IMHO, [issue 621](https://github.com/vmware/harbor/issues/621) is not fully fixed; private repository names are still displayed in the public home page (tested in 0.3.5).

More generally, the private elements of this list should not be obtained anonymously via the API (curl -v  https://SERVER/api/repositories/top). 

It would be wiser to not display anything about private repositories as their names can contain indications on internal (=private) entreprise activities.

**Comment by ywk253100** [comment]
Fixed by #1301 .
