### ISSUE TITLE
Can create project without being an admin

### ISSUE THREAD

**Issue by bergtwvd** [vmware/harbor#784]
I can create a project without being an admin. This does not seem to be correct.
Harbor v0.3.5.

**Comment by wknet123** [comment]
Please clear browsing cache and try it again.

2016-09-10 4:11 GMT+08:00 bergtwvd <notifications@github.com>:

**Comment by wknet123** [comment]
Everyone signed up can create project as its owner act as project admin role.

**Comment by bergtwvd** [comment]
That is correct, Currently any signed in user can create a project. However, this is not always desirable. For example, in my case, users should only have the rights to push into projects that they are a member of (not ones they create themselves on the fly). So I prefer this to become a site setting.

**Comment by bergtwvd** [comment]
Just one additional comment. This isssue is (from user point of view) also related to the ability to delete a project (see https://github.com/vmware/harbor/issues/112). A site setting: allow project deletion by site admin only, or allow project deletion by the project admin,
P.s. Harbor v0.3.5 does not include #112.

**Comment by wknet123** [comment]
Harbor provides a toggle for self-registration (default is ON), it would only allow admin to add user when the self-registration is turned off. Please refer it on our installation guide.

**Comment by bergtwvd** [comment]
Yes, I know that option, and have already switched it "on".  But this option does not address this isssue.

**Comment by wknet123** [comment]
I mean you should set this option to "off" that only allow admin to add user. The admin user can create a project and allocate 'developer' role for this project to others.

**Comment by bergtwvd** [comment]
Sorry, I was confusing. I have already set self-registration to off.  But once the user has an account (created by the site admin) he can create projects has he likes. This is not desirable for every situation, and needs to be restricted to the site admin in these situations.

**Comment by wknet123** [comment]
So far, by design, we can't prevent signed up user creating its own project.

**Comment by bergtwvd** [comment]
Alothough the issue status got closed, I still wonder if this issue could be considered as a feature request for inclusion in the Harbor roadmap. Any thoughts on this?

**Comment by malkocb** [comment]
Agree with @bergtwvd here: Would be nice to have control over who can create projects (and delete, as discussed in #112, once that is implemented).
