### ISSUE TITLE
Wait long time to find the image in UI after finish pushing it

### ISSUE THREAD

**Issue by supereagle** [vmware/harbor#786]
After finish pushing images, need to wait a least 2 minutes to find them in UI. Any way the decrease the interval?

**Comment by ywk253100** [comment]
Which version of Harbor does you use? Could you provide the logs?

**Comment by supereagle** [comment]
After the image pushed, there is one error about notification from docker registry. Maybe this is the root cause. The Core Services component can not immediately get the notification about the image status. 

In my test env, code is from the master branch, the last commit msg:
commit 11687b2789c510b360729dab70ae9935704b9188
Author: yhua <a@b.com>
Date:   Mon Sep 5 15:40:49 2016 +0800

    add version support in env

**Log from docker_registry.log**
Sep 13 15:02:53 harbor.vclound.com docker/registry[23561]: time="2016-09-13T07:02:53.251374495Z" level=debug msg="filesystem.PutContent(\"/docker/registry/v2/repositories/test/speed/_manifests/tags/0.1/current/link\")" auth.user.name=admin go.version=go1.6.3 http.request.contenttype="application/vnd.docker.distribution.manifest.v2+json" http.request.host=harbor.vclound.com http.request.id=3dfe701f-5585-4476-8d1f-6fd3918b48b5 http.request.method=PUT http.request.remoteaddr=172.18.0.1 http.request.uri="/v2/test/speed/manifests/0.1" http.request.useragent="docker/1.10.3-el7.centos go/go1.4.2 git-commit/0b4a971-unsupported kernel/3.10.0-229.el7.x86_64 os/linux arch/amd64" instance.id=9c4b26be-f776-4e22-af07-8f13044d9f32 service=registry trace.duration=1.007436ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).PutContent" trace.id=9013a01f-a945-43f1-8f57-2015988eaa5c trace.line=95 vars.name="test/speed" vars.reference=0.1 version=v2.5.0 
Sep 13 15:02:53 harbor.vclound.com docker/registry[23561]: time="2016-09-13T07:02:53.251573104Z" level=info msg="response completed" go.version=go1.6.3 http.request.contenttype="application/vnd.docker.distribution.manifest.v2+json" http.request.host=harbor.vclound.com http.request.id=3dfe701f-5585-4476-8d1f-6fd3918b48b5 http.request.method=PUT http.request.remoteaddr=172.18.0.1 http.request.uri="/v2/test/speed/manifests/0.1" http.request.useragent="docker/1.10.3-el7.centos go/go1.4.2 git-commit/0b4a971-unsupported kernel/3.10.0-229.el7.x86_64 os/linux arch/amd64" http.response.duration=13.810735ms http.response.status=201 http.response.written=0 instance.id=9c4b26be-f776-4e22-af07-8f13044d9f32 service=registry version=v2.5.0 
Sep 13 15:02:53 harbor.vclound.com docker/registry[23561]: 172.18.0.7 - - [13/Sep/2016:07:02:53 +0000] "PUT /v2/test/speed/manifests/0.1 HTTP/1.1" 201 0 "" "docker/1.10.3-el7.centos go/go1.4.2 git-commit/0b4a971-unsupported kernel/3.10.0-229.el7.x86_64 os/linux arch/amd64"

**Sep 13 15:02:54 harbor.vclound.com docker/registry[23561]: time="2016-09-13T07:02:54.347895792Z" level=error msg="retryingsink: error writing events: httpSink{http://ui/service/notifications}: error posting: Post http://ui/service/notifications: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retrying" 
Sep 13 15:02:59 harbor.vclound.com docker/registry[23561]: time="2016-09-13T07:02:59.353713248Z" level=error msg="retryingsink: error writing events: httpSink{http://ui/service/notifications}: error posting: Post http://ui/service/notifications: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retrying" 
....
Sep 13 15:03:29 harbor.vclound.com docker/registry[23561]: time="2016-09-13T07:03:29.39480293Z" level=error msg="retryingsink: error writing events: httpSink{http://ui/service/notifications}: error posting: Post http://ui/service/notifications: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retrying"**
Sep 13 15:03:32 harbor.vclound.com docker/registry[23561]: time="2016-09-13T07:03:32.980692039Z" level=debug msg="authorizing request" go.version=go1.6.3 http.request.host="registry:5000" http.request.id=c22f23d4-2682-4264-aeec-7edc49191f59 http.request.method=GET http.request.remoteaddr="172.18.0.4:42996" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=9c4b26be-f776-4e22-af07-8f13044d9f32 service=registry version=v2.5.0 
Sep 13 15:03:32 harbor.vclound.com docker/registry[23561]: time="2016-09-13T07:03:32.980825715Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.6.3 http.request.host="registry:5000" http.request.id=c22f23d4-2682-4264-aeec-7edc49191f59 http.request.method=GET http.request.remoteaddr="172.18.0.4:42996" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=9c4b26be-f776-4e22-af07-8f13044d9f32 service=registry version=v2.5.0 
Sep 13 15:03:32 harbor.vclound.com docker/registry[23561]: 172.18.0.4 - - [13/Sep/2016:07:03:32 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "Go-http-client/1.1"
Sep 13 15:03:33 harbor.vclound.com docker/registry[23561]: time="2016-09-13T07:03:33.015415698Z" level=debug msg="authorizing request" go.version=go1.6.3 http.request.host="registry:5000" http.request.id=a556eb18-38f3-4f9e-8b8d-112749521f6f http.request.method=GET http.request.remoteaddr="172.18.0.4:42997" http.request.uri="/v2/_catalog?n=1000" http.request.useragent="Go-http-client/1.1" instance.id=9c4b26be-f776-4e22-af07-8f13044d9f32 service=registry version=v2.5.0

**Comment by ywk253100** [comment]
Yes, the notification error caused the problem. It seems that the registry can not connect to the notification service hosted in UI container. 
Could you try whether you can ping the UI in registry container by running "ping ui"? If it works well, you can try to set the timeout longer, the configuration file is under directory Deploy/config/registry/config.yml, modify the timeout in notifications part.

**Comment by supereagle** [comment]
I can "ping ui" in regitstry container. After change the timeout of notification from 3000ms to 30000ms, there are no errors in registry any more. But still have to wait long time to find the image and the operation log in UI.

**Comment by reasonerjt** [comment]
@supereagle I noticed the hostname was "harbor.vclound.com" are you deploying harbor on a cloud? or a regular local docker host?

**Comment by supereagle** [comment]
On a local docker host, not cloud.

**Comment by reasonerjt** [comment]
@supereagle are you using Harbor heavily, based on your logs seems the network between containers are not stable, this problem falls out of Harbor's scope, but I'm really curious about the root cause

**Comment by supereagle** [comment]
Just use Harbor for test, not heavily use it. Could you help to explain the mechanism of UI to get the image status? When use the default timeout of notification, there are error from registry. After increase the timeout of notification, there is no error for notification, so the notification should has been sent to UI. 

Any another way for UI to get the image status except notification? I notice that no matter whether the notification is correctly sent to UI, UI can get the image status several minutes later.

**Comment by ywk253100** [comment]
UI gets the status of image from an cache and the cache sync with registry every several minutes. So even the notifications did not work, the UI could get the latest images by synchronization. 

Could you provide the logs of UI and registry?

**Comment by supereagle** [comment]
Both the log of UI and registry have no error.

**Log from docker_registry.log**
Sep 21 18:19:11 jenkins-slave-gkkvm.vclound.com docker/registry[23561]: time="2016-09-21T10:19:11.142349063Z" level=debug msg="filesystem.PutContent(\"/docker/registry/v2/repositories/test/
centos/_manifests/revisions/sha256/286ba285793d1ba00fdd8565a7dea5a79605e0ea83329c5b4be41195df89bf72/link\")" auth.user.name=admin go.version=go1.6.3 http.request.contenttype="application/vn
d.docker.distribution.manifest.v2+json" http.request.host=jenkins-slave-gkkvm.vclound.com http.request.id=65748511-5f2c-4e1c-bd1a-e9001b39688a http.request.method=PUT http.request.remoteadd
r=172.18.0.1 http.request.uri="/v2/test/centos/manifests/7" http.request.useragent="docker/1.10.3-el7.centos go/go1.4.2 git-commit/0b4a971-unsupported kernel/3.10.0-229.el7.x86_64 os/linux
arch/amd64" instance.id=0a76a6cc-0ebb-4283-9b15-af1479df774c service=registry trace.duration=998.109µs trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.
go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).PutContent" trace.id=5bd92454-464d-475c-8b5f-4997fa664564 trace.line=95 vars.name="test/centos" vars.refe
rence=7 version=v2.5.0
Sep 21 18:19:11 jenkins-slave-gkkvm.vclound.com docker/registry[23561]: time="2016-09-21T10:19:11.143751574Z" level=debug msg="filesystem.PutContent(\"/docker/registry/v2/repositories/test/
centos/_manifests/tags/7/index/sha256/286ba285793d1ba00fdd8565a7dea5a79605e0ea83329c5b4be41195df89bf72/link\")" auth.user.name=admin go.version=go1.6.3 http.request.contenttype="application
/vnd.docker.distribution.manifest.v2+json" http.request.host=jenkins-slave-gkkvm.vclound.com http.request.id=65748511-5f2c-4e1c-bd1a-e9001b39688a http.request.method=PUT http.request.remote
addr=172.18.0.1 http.request.uri="/v2/test/centos/manifests/7" http.request.useragent="docker/1.10.3-el7.centos go/go1.4.2 git-commit/0b4a971-unsupported kernel/3.10.0-229.el7.x86_64 os/lin
ux arch/amd64" instance.id=0a76a6cc-0ebb-4283-9b15-af1479df774c service=registry trace.duration=1.08103ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/bas
e.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).PutContent" trace.id=df584efc-bd95-45b4-b21e-e3b4a093af93 trace.line=95 vars.name="test/centos" vars.re
ference=7 version=v2.5.0
Sep 21 18:19:11 jenkins-slave-gkkvm.vclound.com docker/registry[23561]: time="2016-09-21T10:19:11.144793679Z" level=debug msg="filesystem.PutContent(\"/docker/registry/v2/repositories/test/
centos/_manifests/tags/7/current/link\")" auth.user.name=admin go.version=go1.6.3 http.request.contenttype="application/vnd.docker.distribution.manifest.v2+json" http.request.host=jenkins-s
lave-gkkvm.vclound.com http.request.id=65748511-5f2c-4e1c-bd1a-e9001b39688a http.request.method=PUT http.request.remoteaddr=172.18.0.1 http.request.uri="/v2/test/centos/manifests/7" http.re
quest.useragent="docker/1.10.3-el7.centos go/go1.4.2 git-commit/0b4a971-unsupported kernel/3.10.0-229.el7.x86_64 os/linux arch/amd64" instance.id=0a76a6cc-0ebb-4283-9b15-af1479df774c servic
e=registry trace.duration=955.265µs trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/dri
ver/base.(*Base).PutContent" trace.id=4e8c9405-e4d0-42b2-bd3a-206f5f06d829 trace.line=95 vars.name="test/centos" vars.reference=7 version=v2.5.0
Sep 21 18:19:11 jenkins-slave-gkkvm.vclound.com docker/registry[23561]: time="2016-09-21T10:19:11.144921298Z" level=info msg="response completed" go.version=go1.6.3 http.request.contenttype
="application/vnd.docker.distribution.manifest.v2+json" http.request.host=jenkins-slave-gkkvm.vclound.com http.request.id=65748511-5f2c-4e1c-bd1a-e9001b39688a http.request.method=PUT http.r
equest.remoteaddr=172.18.0.1 http.request.uri="/v2/test/centos/manifests/7" http.request.useragent="docker/1.10.3-el7.centos go/go1.4.2 git-commit/0b4a971-unsupported kernel/3.10.0-229.el7.
x86_64 os/linux arch/amd64" http.response.duration=13.866499ms http.response.status=201 http.response.written=0 instance.id=0a76a6cc-0ebb-4283-9b15-af1479df774c service=registry version=v2.
5.0
Sep 21 18:19:11 jenkins-slave-gkkvm.vclound.com docker/registry[23561]: 172.18.0.7 - - [21/Sep/2016:10:19:11 +0000] "PUT /v2/test/centos/manifests/7 HTTP/1.1" 201 0 "" "docker/1.10.3-el7.ce
ntos go/go1.4.2 git-commit/0b4a971-unsupported kernel/3.10.0-229.el7.x86_64 os/linux arch/amd64"
Sep 21 18:19:37 jenkins-slave-gkkvm.vclound.com docker/registry[23561]: time="2016-09-21T10:19:37.80906515Z" level=debug msg="authorizing request" go.version=go1.6.3 http.request.host="regi
stry:5000" http.request.id=65161fca-5c46-45ca-8961-e4646cc711a1 http.request.method=GET http.request.remoteaddr="172.18.0.5:59491" http.request.uri="/v2/" http.request.useragent="Go-http-cl
ient/1.1" instance.id=0a76a6cc-0ebb-4283-9b15-af1479df774c service=registry version=v2.5.0

**Log from docker_ui.log**
Sep 21 18:19:16 harbor.vclound.com docker/ui[23561]: 2016-09-21T10:19:16Z [DEBUG] [notification.go:98]: receive an event: ID-0bd4f9b4-1cf3-4f0e-8ed9-22a47aee5608, target-test/centos:, digest-sha256:ca5dfc813bf0bd816e05c30827d4ed588d461b15b500404b6999b13e5866cfda, action-push
Sep 21 18:19:16 harbor.vclound.com docker/ui[23561]: 2016/09/21 10:19:16 #033[1;34m[router.go:829][D] | POST       | /service/notifications                   | 382.104µs        | match      | /service/notifications                   | #033[0m
Sep 21 18:19:21 harbor.vclound.com docker/ui[23561]: 2016-09-21T10:19:21Z [DEBUG] [notification.go:98]: receive an event: ID-1fcf01e9-2bbd-479d-a32a-959c105857fa, target-test/centos:, digest-sha256:ca5dfc813bf0bd816e05c30827d4ed588d461b15b500404b6999b13e5866cfda, action-pull
Sep 21 18:19:21 harbor.vclound.com docker/ui[23561]: 2016/09/21 10:19:21 #033[1;34m[router.go:829][D] | POST       | /service/notifications                   | 337.284µs        | match      | /service/notifications                   | #033[0m
Sep 21 18:19:22 harbor.vclound.com docker/ui[23561]: 2016-09-21T10:19:22Z [DEBUG] [base.go:132]: Loaded HeaderScriptInclude file: sections/script-min-include.htm
Sep 21 18:19:22 harbor.vclound.com docker/ui[23561]: 2016/09/21 10:19:22 #033[1;34m[router.go:829][D] | GET        | /repository                              | 2.100701ms       | match      | /repository

**Comment by ywk253100** [comment]
Sorry for the late replay, could you try the new version of Harbor?
