### ISSUE TITLE
Deploying Harbor on a host which does not have Internet access, Can't find save_image.sh file 

### ISSUE THREAD

**Issue by xiaoping378** [vmware/harbor#793]
[follow the docs in here](https://github.com/vmware/harbor/blob/master/docs/installation_guide.md#deploying-harbor-on-a-host-which-does-not-have-internet-access)

the project lost files:  **save_image.sh and ./load_image.sh**

**Comment by reasonerjt** [comment]
save_image.sh is in the package on release tab.

**Comment by xiaoping378** [comment]
This package?  ---  NO
https://github.com/vmware/harbor/archive/0.3.5.tar.gz

**Comment by reasonerjt** [comment]
Sorry, look at previous packages, the script was built by our build server and uploaded to github, we'll refactor this part and probably will not need such scripts.

Thanks for reporting but your PR may not be accepted.

**Comment by xiaoping378** [comment]
OK, Got it/

**Comment by reasonerjt** [comment]
in 0.4.0 we released offline installer. closing this issue.
