### ISSUE TITLE
[issue]Click " My Projects | Public Projects" No Respond When on Project Detail Page

### ISSUE THREAD

**Issue by yhua123** [vmware/harbor#794]
![untitled](https://cloud.githubusercontent.com/assets/19166125/18459733/a0613d20-799e-11e6-8ba3-995957e1837d.png)

**Comment by supereagle** [comment]
Is it because you just has only one project "project0001", which is also public? In this case, the project detail page will the same for My Projects and Public Projects.

**Comment by yhua123** [comment]
Yes, you are right. 
But for better experience, on this page, user can use these 2 link jump to project list page.
![untitled](https://cloud.githubusercontent.com/assets/19166125/18463859/b0a847ac-79bf-11e6-85e0-11df25fa643c.png)
Stay on this page, if you click my "Public Projects" will jump to public project, and can't jump back when you click "My Project" again.
Maybe I need update the issue title :)
