### ISSUE TITLE
Failed to push image 

### ISSUE THREAD

**Issue by perhapszzy** [vmware/harbor#80]
I changed the hostname to localhost in harbor.cfg. I was able to see the UI on localhost and login using admin, but I was not able to push any images to the registry:

```
zeyu@perhaps:~/gocode/src/github.com/caicloud/paging$ docker login localhost
Username (admin): admin
Password: 
WARNING: login credentials saved in /home/zeyu/.docker/config.json
Login Succeeded
zeyu@perhaps:~/gocode/src/github.com/caicloud/paging$ docker push localhost/admin/ubuntu:14.04
The push refers to a repository [localhost/admin/ubuntu]
5f70bf18a086: Image push failed 
1b82ce694c3b: Preparing 
db6b2d84f3c6: Preparing 
05b940eef08d: Preparing 
unauthorized: authentication required
```

What's the problem?

**Comment by perhapszzy** [comment]
dup of #61  closing.

**Comment by x6j** [comment]
怀疑你改了hostname,是不是在auth server config里也要改。
https://github.com/caicloud/caicloud-docker-registry/blob/master/scripts/registry/aliyun/templates/config-auth.yml.in#L7

**Comment by x6j** [comment]
在harbor里可能是在这里设置
https://github.com/vmware/harbor/blob/4a2a8b6ad3721b03b23aecb346e7e10ca8102a46/service/utils/authutils.go#L35

**Comment by x6j** [comment]
可能不相关。habor的issuer应该不受habor.cfg影响。
https://github.com/vmware/harbor/blob/864b8146f5463ea3c726044425b42ceaf7d7f829/Deploy/templates/registry/config.yml#L21

**Comment by x6j** [comment]
https://github.com/vmware/harbor/blob/4a2a8b6ad3721b03b23aecb346e7e10ca8102a46/service/token.go#L45

似乎harbor也有这个问题
https://github.com/cesanta/docker_auth/issues/67

**Comment by x6j** [comment]
看docker auth 的fix,似乎应该有下面的逻辑。
https://github.com/cesanta/docker_auth/pull/68/files

```
for _, scopeStr := range req.Form["scope"] {
  ...
   ar.Scopes = append(ar.Scopes, scope)
}		  
return ar, nil
```

**Comment by reasonerjt** [comment]
@x6j Thanks for investigation, this is not a dup to #61.

I

**Comment by xwisen** [comment]
The admin repository is really exist?In default it provide a admin repository named library.So,maybe you can try <docker push localhost/admin/ubuntu:14.04>

**Comment by perhapszzy** [comment]
I tried to create a user named "test" and tried to push images to test but also failed with the same error (I can run docker login, but not docker push)

**Comment by xiahaoshawn** [comment]
@reasonerjt Does Harbor support the domain name "localhost" ?

**Comment by perhapszzy** [comment]
I rebuild the harbor image, but I still can't push images:
operations:
```
zeyu@perhaps:~$ docker login localhost
Username (test): test
Password: 
WARNING: login credentials saved in /home/zeyu/.docker/config.json
Login Succeeded
zeyu@perhaps:~$ docker push localhost/test/ubuntu:14.0
The push refers to a repository [localhost/test/ubuntu]
tag does not exist: localhost/test/ubuntu:14.0
zeyu@perhaps:~$ docker push localhost/test/ubuntu:14.04
The push refers to a repository [localhost/test/ubuntu]
5f70bf18a086: Image push failed 
1b82ce694c3b: Preparing 
db6b2d84f3c6: Preparing 
05b940eef08d: Preparing 
unauthorized: authentication required
```

logs:
```
registry_1  | 172.18.0.6 - - [06/Apr/2016:16:22:14 +0000] "POST /v2/test/ubuntu/blobs/uploads/ HTTP/1.1" 401 202 "" "docker/1.10.3 go/go1.5.3 git-commit/20f81dd kernel/3.16.0-69-generic os/linux arch/amd64"
proxy_1     | 172.18.0.1 - - [06/Apr/2016:16:22:14 +0000] "POST /v2/test/ubuntu/blobs/uploads/ HTTP/1.1" 401 202 "-" "docker/1.10.3 go/go1.5.3 git-commit/20f81dd kernel/3.16.0-69-generic os/linux arch/amd64"
```

**Comment by perhapszzy** [comment]
btw, I did see the newly updated logs that outputs the scopes
```
2016-04-06T16:22:14Z [DEBUG] [token.go:46]: scopes: [repository:test/ubuntu:push,pull]
```

**Comment by reasonerjt** [comment]
I don't think it's the same issue, the this message:

> ui_1        | 2016-04-06T16:22:14Z [INFO] current access, type: repository, name:test/ubuntu, actions:[] 
means the current user don't have access to the project test.

**Comment by perhapszzy** [comment]
I have already logged as user "test" shouldn't I be able to push image to that path?

**Comment by reasonerjt** [comment]
if this is the case, you'll have to create a project called "test".
Currently harbor does not have a personal namespace. Every namespace has to be a project.

**Comment by perhapszzy** [comment]
I c. It works now! Thank you!
