### ISSUE TITLE
Any account can pull images of public project.

### ISSUE THREAD

**Issue by zhangchengshan** [vmware/harbor#805]
For now, any account whether it has role in this public project can pull the image. Whether harbor can add a kind of account only see the public project in web and can't pull image ,can't create private project.

**Comment by hainingzhang** [comment]
Could you explain what this feature is for?

**Comment by zhangchengshan** [comment]
@hainingzhang This role is a pure visitor for the harbor, it can't pull or push any image whether the project is public or private. I think image should be pull or push by CI and CD, or publish system, not a single person.

**Comment by hainingzhang** [comment]
Currently, Harbor does not have a role which allows viewing on web but not pulling from docker client.
In your case, so why not just set the project as private, and only CI/CD accounts can push/pull to/from the project?

**Comment by zhangchengshan** [comment]
Because the harbor can't forbid some account to create private project. So ldap users can login harbor online and create the private project, and push images into their project. This situation is bad for the OP.
At the moment, we allow some specific accounts to pull and push images by nginx.

**Comment by reasonerjt** [comment]
@zhangchengshan , so essentially you are ask for restriction on creating projects?

You don't want every user can create private project, is that correct?

**Comment by zhangchengshan** [comment]
@reasonerjt yes, everyone can push images by their project, which caused the disk space out of control.

**Comment by reasonerjt** [comment]
@zhangchengshan what about add a setting such that only admin can create project?

**Comment by zhangchengshan** [comment]
@reasonerjt That's OK. Thanks for your advise.

**Comment by zhangchengshan** [comment]
Close this issue
