### ISSUE TITLE
push failed  unauthorized: access to the requested resource is not authorized

### ISSUE THREAD

**Issue by 9923** [vmware/harbor#81]
I install harbor by harbor_0.1.0.tgz, and is run successed,also can open the web .  but push image fail.
prompt:5f70bf18a086: Preparing 
1834950e52ce: Preparing 
unauthorized: access to the requested resource is not authorized

**Comment by wknet123** [comment]
Hi @9923 , you must sign up a user, log into UI, and create a project which is a namespace of the repository, and then use "docker login" at Docker client by using the username and password you signed up, execute "docker push [project_name]/[repository_name]:[tag]" command to push new images to the registry.

**Comment by 9923** [comment]
HI @wknet123 !  Yes , I created a public project like busybox,and In another machine with admin login successful,like :WARNING: login credentials saved in /home/zhouzx/.docker/config.json Login Succeeded. then push but failed,the tips:
5f70bf18a086: Preparing 
1834950e52ce: Preparing 
unauthorized: access to the requested resource is not authorized

I also signed up a user with 9923 name ,and use 9923 logined successful . then push failed with the same tips.

**Comment by wknet123** [comment]
Hi, I want to confirm if you are a project admin role to the project you pushed onto?

**Comment by 9923** [comment]
@wknet123 ,Thank you, I resolved !
