### ISSUE TITLE
'docker login host-IP' cannot success?

### ISSUE THREAD

**Issue by wangfeiping** [vmware/harbor#811]
Linux docker-container-B 3.10.0-327.28.3.el7.x86_64 #1 SMP Thu Aug 18 19:05:49 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Docker version 1.11.2, build b9f10c9
docker-compose version 1.8.0, build f3628c7
no error logs.

I installed the harbor-0.3.5, and then I login the web.

I cannot login docker when I use the host IP

`
docker login 172.28.32.23
Username: admin
Password: 
Error response from daemon: Get https://172.28.32.23/v1/users/: dial tcp 172.28.32.23:443: getsockopt: connection refused
`

I can login docker when I used 127.0.0.1, but I cannot push docker image successfully.

`
docker login 127.0.0.1
Username (admin): admin
Password: 
Login Succeeded
`

`
docker push 172.28.32.23/public/harbor-log:0.3.5
The push refers to a repository [172.28.32.23/public/harbor-log]
Get https://172.28.32.23/v1/_ping: dial tcp 172.28.32.23:443: getsockopt: connection refused
`

I don't know why?

**Comment by tuxknight** [comment]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose
2)Config files of harbor, you can get them by packaging "Deploy/config" directory
3)Log files, you can get them by package the /var/log/harbor/

**Comment by wangfeiping** [comment]
Oh! Sorry, I uploaded files yesterday, but now I can not find them too?

1)Version of docker engine and docker-compose
Linux docker-container-B 3.10.0-327.28.3.el7.x86_64 #1 SMP Thu Aug 18 19:05:49 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Docker version 1.11.2, build b9f10c9
docker-compose version 1.8.0, build f3628c7

2)Config files of harbor, you can get them by packaging "Deploy/config" directory

[config.zip](https://github.com/vmware/harbor/files/479163/config.zip)

3)Log files, you can get them by package the /var/log/harbor/ 

[harbor-0.3.5.zip](https://github.com/vmware/harbor/files/479164/harbor-0.3.5.zip)

**Comment by wangfeiping** [comment]
@tuxknight 

I cannot login docker when I use the host IP

docker login 172.28.32.23
Username: admin
Password:
Error response from daemon: Get https://172.28.32.23/v1/users/: dial tcp 172.28.32.23:443: getsockopt: connection refused

I can login docker when I used 127.0.0.1, but I cannot push docker image successfully.

docker login 127.0.0.1
Username (admin): admin
Password: Login Succeeded

docker push 172.28.32.23/public/harbor-log:0.3.5
The push refers to a repository [172.28.32.23/public/harbor-log] Get https://172.28.32.23/v1/_ping: dial tcp 172.28.32.23:443: getsockopt: connection refused

**Comment by wangfeiping** [comment]
I used wrong password to login and found that:
Why 127.0.0.1 used http, but 172.28.32.23 used https?
I`m not change any config but "hostname = 172.28.32.23".

docker login 127.0.0.1
Username (admin): admin
Password: 
Error response from daemon: Get http://127.0.0.1/v2/: unauthorized: authentication required

docker login 172.28.32.23
Username: admin
Password: 
Error response from daemon: Get https://172.28.32.23/v1/users/: dial tcp 172.28.32.23:443: getsockopt: connection refused

**Comment by tuxknight** [comment]
@wangfeiping You should check arguments of docker daemon.  Insecure registry communication over http only enabled with option ``--insecure-registry``

**Comment by wangfeiping** [comment]
@tuxknight Thank you!

I don't know why, but I found that:

ps -ef | grep dockerd

root       6250      1  1 18:42 ?        00:00:01 dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver devicemapper --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=generic

dockerd is not execute according to the config (/usr/lib/systemd/system/docker.service):
ExecStart=/usr/bin/dockerd --insecure-registry 172.28.32.23

Fortunately, I run docker with "/usr/bin/dockerd --insecure-registry 172.28.32.23", and all is ok!

I still don't know why, may be my mistake or just a docker's issue.

**Comment by wangfeiping** [comment]
https://wiki.archlinux.org/index.php/Systemd_

systemd

The available unit files can be seen in /usr/lib/systemd/system/ and /etc/systemd/system/ (the latter takes precedence).

**Comment by winterZhao** [comment]
I find if you only use docker-registry,you can use  "--insecure-registry 172.28.32.23'' to solve this question,and you can pull or push images;but if you use harbor, using "--insecure-registry 172.28.32.23' can't sovle this question ,and have a "connection refused" error

**Comment by zzg16** [comment]
解决方法见: https://docs.docker.com/registry/insecure/#deploy-a-plain-http-registry

> Edit the daemon.json file, whose default location is /etc/docker/daemon.json on Linux or C:\ProgramData\docker\config\daemon.json on Windows Server. If you use Docker for Mac or Docker for Windows, click the Docker icon, choose Preferences, and choose +Daemon.
> If the daemon.json file does not exist, create it. Assuming there are no other settings in the file, it should have the following contents:

```
{
  "insecure-registries":["0.0.0.0/0"]
}
```

**Comment by winterZhao** [comment]
I try it but it can't  solve this problem ,I run my docker with daemon,so I add 'insecure-registries' with my docker.srvice like this;
 vim /etc/systemd/system/docker.service

    [Unit]
    Description=Docker Application Container Engine
    Documentation=http://docs.docker.io
    
    [Service]
    Environment="PATH=/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin"
    ExecStart=/usr/bin/dockerd --log-level=error \
    --graph=/app/docker/data \
    --registry-mirror=https://docker.mirrors.ustc.edu.cn \
    --insecure-registry=0.0.0.0:5000 \
    --insecure-registry=https://docker.mirrors.ustc.edu.cn
    ExecReload=/bin/kill -s HUP $MAINPID
    Restart=on-failure
    RestartSec=5
    LimitNOFILE=infinity
    LimitNPROC=infinity
    LimitCORE=infinity
    Delegate=yes
    KillMode=process
    
    [Install]
    WantedBy=multi-user.target

and then execute it with commend below 

    systemctl daemon-reload
    systemctl restart docker


I think I have rum command like  'insecure-registries',It runs well with docker-registry,but wrong with harbor
