### ISSUE TITLE
Vulnerability scanning tool

### ISSUE THREAD

**Issue by biolounge** [vmware/harbor#817]
Any plans to add or integrate Vmware Harbor with any vulnerability scanning technologies?

**Comment by reasonerjt** [comment]
there is some discussion, but may not in very near future.

**Comment by hainingzhang** [comment]
It is in the roadmap. We will plan for it.

**Comment by reasonerjt** [comment]
The integration with Clair is WIP and will be included in next release, the work will be tracked by #2042
