### ISSUE TITLE
Image replication should emphasize between the same version of Harbor releases in Docs.

### ISSUE THREAD

**Issue by wknet123** [vmware/harbor#826]
Different version may cause error while synchronizing images.

**Comment by reasonerjt** [comment]
good point, this is due to api incompatibility, we don't have a good solution now and will highlight this in doc.

**Comment by reasonerjt** [comment]
Maybe we can add "/api/version" and check it during “ping"? and also check this during replication by adding a state in statemachine? @ywk253100 what do you think?

**Comment by ywk253100** [comment]
Agree.

**Comment by ywk253100** [comment]
Incompatibility explanation has been added in docs by #957 .
