### ISSUE TITLE
Failed to Build and save images for offline installation

### ISSUE THREAD

**Issue by CodeJuan** [vmware/harbor#83]
#  scenario
1. I followed the the guidance [build-and-save-images-for-offline-installation](https://github.com/vmware/harbor/blob/master/docs/installation_guide.md#build-and-save-images-for-offline-installation)
2. downloaded [harbor_0.1.0.tgz](https://github.com/vmware/harbor/releases/download/0.1.0/harbor_0.1.0.tgz),
3. unziped 
4. `cd  harbor`
5. `./prepare`
6. `docker-compose build`, but  the result is `proxy uses an image, skipping`

# my solution
1. mkdir proxy 
2. create `proxy/Dockerfile`, the content of `proxy/Dockerfile` is `FROM nginx:1.9`
3. modified `docker-compose.yml`, replace `image: nginx:1.9` to `build: ./proxy`
3. After that, `docker-compose build` works

I'm not sure my solution is right.  Could you please give me a hand, Thank you very much.

**Comment by xiahaoshawn** [comment]
Yes, your solution is right. "docker-compose build, but the result is proxy uses an image, skipping" when you use docker-compose up you will find "Pulling proxy (nginx:1.9)...".  
Build image from Dockerfile follow the instruction`FROM nginx:1.9` will also pull the image from docker hub.

**Comment by CodeJuan** [comment]
Thank you for your reply.
May I send a PR to fix it?

**Comment by xiahaoshawn** [comment]
Actually both docker-compose up(after docker-compose build) and build image from Dockerfile follow the instruction 'FROM nginx:1.9 ' are pull the image from Docker Hub, these are the same way to get the image. That is not an issue.

**Comment by CodeJuan** [comment]
You mean that the image `nginx:1.9` would pull when I execute `docker-compose up`.
Yep, I got it, it's my fault.
Thanks for your kindly help :+1:
