### ISSUE TITLE
UI does not refresh after deleting a repo tag 

### ISSUE THREAD

**Issue by wemeya** [vmware/harbor#838]
In nginx, it has two repos, after I deleted a tag, UI doesn't refresh automatically. I must press F5 to see the change. See below:

![image](https://cloud.githubusercontent.com/assets/12540577/18828497/c48d8ae8-840a-11e6-9644-08c499d837f0.png)

After I deleted:

![image](https://cloud.githubusercontent.com/assets/12540577/18828678/6d985352-840b-11e6-80c9-eba6783c6735.png)

**Comment by wknet123** [comment]
Fixed with #943
