### ISSUE TITLE
UI repo search doesn't work well

### ISSUE THREAD

**Issue by wemeya** [vmware/harbor#839]
I pushed a new image, then refresh the UI and search, but it can't find. Also, it can't find the older images. After I refreshed a few more times, it works well.

![image](https://cloud.githubusercontent.com/assets/12540577/18828872/62ce4f98-840c-11e6-8667-d33b3c33253c.png)

![image](https://cloud.githubusercontent.com/assets/12540577/18828890/7331d27e-840c-11e6-8e8e-860449f795f7.png)

**Comment by reasonerjt** [comment]
Seems it's because adding data and refresh cache are in two go routines so sometimes refresh cache doesnt' get the latest data, thanks for the finding, I'll fix it.

**Comment by reasonerjt** [comment]
Fixed in #844
