### ISSUE TITLE
ldap_basedn = UID=%S not working

### ISSUE THREAD

**Issue by nils-smits** [vmware/harbor#843]
Info user.
Username: John Smith
UserId: john.smith

The problem is if i config the harbor.conf with ldap_basedn CN=%s,OU=users,DC=example,DC=local, I can login in with John Smith. I can login in.

[DEBUG]  [authenticator.go:52]: Current AUTH_MODE is ldap_auth
[DEBUG]  [ldap.go:47]: ldapURL:ldap://ldap_server.example.local
[DEBUG]  [ldap.go:69]: baseDn:CN=John Smith,OU=users,DC=example,DC=local
[DEBUG]  [ldap.go:97]: username:John Smith,email:john.smith@example.local

But when i set the harbor.conf file with UID=%s,OU=users,DC=example,DC=local, I can't login with john.smith .
And all are user use the UID credentials.

[DEBUG] [authenticator.go:52]: Current AUTH_MODE is ldap_auth
[DEBUG] [ldap.go:47]: ldapURL:ldap://ldap_server.example.local
[DEBUG] [ldap.go:69]: baseDn:UID=john.smith,OU=users,DC=example,DC=local
[ERROR] [base.go:162]: Error occurred in UserLogin: LDAP::Bind() error (49) : Invalid credentials
[DEBUG] [base.go:132]: Loaded HeaderScriptInclude file: sections/script-min-include.htm

Can any help with this problem.

**Comment by reasonerjt** [comment]
We have changed the way to configure ldap server, so %s is no longer needed. 

You need to set the *ldap_basedn* which is the root of the subtree and the *ldap_uid* attribute which is the name of the attribute.

More details please refer to [installation_guide.md](https://github.com/vmware/harbor/blob/master/docs/installation_guide.md)

**Comment by nils-smits** [comment]
i install the new version op Harbor, but when i search for a user in a security group it does not find the user. What do in need to set in the harbor.conf ?

**Comment by reasonerjt** [comment]
@nils-smits 
So did you successfully verify the user's credentials using tools like ldapsearch?  Please let us know your command for the successful binding.

**Comment by nils-smits** [comment]
Yes that was not the probleem, we have to add a extra line on de ldap_filter line in de harbor.conf so i wil search in de group if a user has permissions.

ldap_filter = (objectClass=user)(memberOf=CN=Harbor Users,OU=users,DC=example,DC=local)
