### ISSUE TITLE
can't pull the image `vmware/harbor-ui:0.4.0`

### ISSUE THREAD

**Issue by SydOps** [vmware/harbor#848]
can't pull the image `vmware/harbor-ui:0.4.0` with both `0.4.0` and `latest` tag:
```
$ docker pull vmware/harbor-ui:0.4.0
Pulling repository docker.io/vmware/harbor-ui
Tag 0.4.0 not found in repository docker.io/vmware/harbor-ui

$ docker pull vmware/harbor-ui
Using default tag: latest
Pulling repository docker.io/vmware/harbor-ui
Tag latest not found in repository docker.io/vmware/harbor-ui
```

**Comment by yhua123** [comment]
I just try this cmd:
# docker pull vmware/harbor-ui:0.4.0
0.4.0: Pulling from vmware/harbor-ui

3d8fd83d62fc: Pull complete 
41cd2e7b78a9: Pull complete 
5dd79dfedec8: Pull complete 
b67df568cce6: Pull complete 
82b72c257ae5: Pull complete 
955390f4ea06: Pull complete 
09c52f732891: Pull complete 
63166e097589: Pull complete 
Digest: sha256:7fbd44371b05244ad9c4ca23fba3929af8f124107a1d3c4728dba5196654e460
Status: Downloaded newer image for vmware/harbor-ui:0.4.0

**Comment by SydOps** [comment]
Thanks, @yhua123. 

It's my local setting problem. I can pull now.
