### ISSUE TITLE
The uploaded images can't be displayed in repositories on the web UI

### ISSUE THREAD

**Issue by Huangwilliam** [vmware/harbor#85]
I created a demo project through web UI, and push an image to demo project. The image is uploaded to demo project successfully, but no image is displayed repositories on the web UI.

![image](https://cloud.githubusercontent.com/assets/18300711/14306962/4522a0f2-fbfe-11e5-9467-6512ebe98e2a.png)

**Comment by reasonerjt** [comment]
This is likely a configuration issue and it should have been fixed in latest code,

**Comment by reasonerjt** [comment]
Could you show me the config.yml of registry?  
Deploy/config/registry/config.yml

**Comment by Huangwilliam** [comment]
Could you please tell me what's probably wrong for the configuration? Thanks.

The config.yml is as bellowing:

version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: /storage
    maintenance:
        uploadpurging:
            enabled: false
http:
    addr: :5000
    secret: placeholder
    debug:
        addr: localhost:5001
auth:
  token:
    issuer: registry-token-issuer
    realm: http://10.37.0.40/service/token
    rootcertbundle: /etc/registry/root.crt
    service: token-service

notifications:
  endpoints:
      - name: harbor
        disabled: false
        url: http://ui/service/notifications
        timeout: 500
        threshold: 5
        backoff: 1000

**Comment by reasonerjt** [comment]
issue is in the config.yml in repo, will fix it.

**Comment by reasonerjt** [comment]
Sorry I added wrong comment.  What's the version of your docker daemon? could you upload the logs?  tar the directory: **/var/log/harbor/${today's date}**

**Comment by Huangwilliam** [comment]
Docker version:
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

[harbor-log.tar.gz](https://github.com/vmware/harbor/files/205867/harbor-log.tar.gz)
Log is attached.
Thanks.

**Comment by reasonerjt** [comment]
I don't see obvious errors in logs. however, in your screenshot, you created a project called "Demo" but pushed to "demo/hello-world"

**Comment by Huangwilliam** [comment]
I used "docker push 10.37.0.40/demo/hello-world:latest" for pushing image.

**Comment by reasonerjt** [comment]
So are you viewing the project "Demo" or "demo"?

**Comment by Huangwilliam** [comment]
I understood it. I though "Demo" and "demo" the same, but it is not the fact.
Thank you.

**Comment by ganting** [comment]
i got this problem also, but it's not the upcase reson
my config.yml 
```
version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: /storage
    maintenance:
        uploadpurging:
            enabled: false
http:
    addr: :5000
    secret: placeholder
    debug:
        addr: localhost:5001
auth:
  token:
    issuer: registry-token-issuer
    realm: https://10.33.40.144/service/token
    rootcertbundle: /etc/registry/root.crt
    service: token-service

notifications:
  endpoints:
      - name: harbor
        disabled: false
        url: http://ui/service/notifications
        timeout: 500
        threshold: 5
        backoff: 1000
```

log: 
[log.tar.gz](https://github.com/vmware/harbor/files/218599/log.tar.gz)

**Comment by xiahaoshawn** [comment]
Did you set "ui_url_protocol = https" in the harbor.cfg?
