### ISSUE TITLE
2016-09-29T08:55:51Z [ERROR] [repository.go:420]: failed to get top repos: Error 1146: Table 'registry.repository' doesn't exist

### ISSUE THREAD

**Issue by mygoda** [vmware/harbor#851]
when i use latest habor to get hub, and when i login ui i can see this error  `2016-09-29T08:55:51Z [ERROR] [repository.go:420]: failed to get top repos: Error 1146: Table 'registry.repository' doesn't exist`

why?

**Comment by reasonerjt** [comment]
Please upgrade your DB.
