### ISSUE TITLE
Cannot rename project

### ISSUE THREAD

**Issue by bergtwvd** [vmware/harbor#858]
Renaming a project is currently not possible.

**Comment by hainingzhang** [comment]
Renaming the project will cause changes in file system on storage, the docker distribution does not provide such API, it is a limitation for now. 

Maybe you can move the images from one project to the other (provided you have all your images downloaded on your local client):

1. create a new project,

2. on your docker client, tag the images of your old project to new project, i.e.

  docker tag oldproject/image:tag  harbor_ipaddress/newproject/image:tag

3. push the images to the new project ( it does not physically transfer the images, just register the image under new project)
docker push harbor_ipaddress/newproject/image:tag

4. Now that all images are shared between the new and old project, you can delete images in old project and the project itself.

5. Now all your images are moved to new project, be sure to add back user/roles afterwards.

**Comment by bergtwvd** [comment]
Thanks for the answer; this is indeed how I do this now.

**Comment by hainingzhang** [comment]
Not an issue. Close it for now. Please reopen if needed.
