### ISSUE TITLE
Can't add members through web UI

### ISSUE THREAD

**Issue by Huangwilliam** [vmware/harbor#86]
I signed up an new account "demouser1" by going through the self-registration process and then created a "demo" project.

I'd like to add a new member named "test" to "demo" project, but it is failed.
It is said "User does not exist".

![image](https://cloud.githubusercontent.com/assets/18300711/14308042/0198d5f6-fc06-11e5-8606-39f1a37b03e1.png)

**Comment by reasonerjt** [comment]
In Harbor, project is collection of users and images.  So when you add a member to a project, the member need to be added to harbor.

So please confirm the test user exists.

**Comment by Huangwilliam** [comment]
OK, I see, thank you.
