### ISSUE TITLE
replication raise error

### ISSUE THREAD

**Issue by zhaoshouzhong** [vmware/harbor#861]
1)Version of docker engine :1.12.1 , version of docker-compose:1.8.0
2)I install harbor in A,B ,and create a replication policy(rep images from A to B), connection of test is ok.
![policy](https://cloud.githubusercontent.com/assets/22735215/19225484/0f2ae256-8ed0-11e6-8ed2-788fb8916827.PNG)

3)from A, when it excutes,it raise error:
2016-10-10T03:55:19Z [INFO] initializing: repository: library/activemq, tags: [], source URL: http://registry:5000, destination URL: http://192.168.10.44, insecure: false, destination user: admin
2016-10-10T03:55:19Z [INFO] initialization completed: project: library, repository: library/activemq, tags: [v5.4], source URL: http://registry:5000, destination URL: http://192.168.10.44, insecure: false, destination user: admin
2016-10-10T03:55:19Z [ERROR] [transfer.go:209]: an error occurred while creating project library on http://192.168.10.44 with user admin : failed to create project library on http://192.168.10.44 with user admin: 400 Invalid json request

4)from B,ui.log:
Oct 10 11:56:14 172.18.0.1 ui[1081]: 2016-10-10T03:56:14Z [DEBUG] [authenticator.go:52]: Current AUTH_MODE is db_auth
Oct 10 11:56:14 172.18.0.1 ui[1081]: 2016-10-10T03:56:14Z [ERROR] [base.go:58]: Error while decoding the json request, error: json: cannot unmarshal bool into Go value of type int
Oct 10 11:56:14 172.18.0.1 ui[1081]: 2016-10-10T03:56:14Z [INFO] Requst with Basic Authentication header, username: admin
Oct 10 11:56:14 172.18.0.1 ui[1081]: 2016-10-10T03:56:14Z [DEBUG] [authenticator.go:52]: Current AUTH_MODE is db_auth
Oct 10 11:56:14 172.18.0.1 ui[1081]: 2016-10-10T03:56:14Z [ERROR] [base.go:58]: Error while decoding the json request, error: json: cannot unmarshal bool into Go value of type int
Oct 10 11:56:14 172.18.0.1 ui[1081]: 2016-10-10T03:56:14Z [INFO] Requst with Basic Authentication header, username: admin
Oct 10 11:56:14 172.18.0.1 ui[1081]: 2016-10-10T03:56:14Z [DEBUG] [authenticator.go:52]: Current AUTH_MODE is db_auth
Oct 10 11:56:14 172.18.0.1 ui[1081]: 2016-10-10T03:56:14Z [ERROR] [base.go:58]: Error while decoding the json request, error: json: cannot unmarshal bool into Go value of type int
Oct 10 11:56:14 172.18.0.1 ui[1081]: 2016-10-10T03:56:14Z [INFO] Requst with Basic Authentication header, username: admin
Oct 10 11:56:14 172.18.0.1 ui[1081]: 2016-10-10T03:56:14Z [DEBUG] [authenticator.go:52]: Current AUTH_MODE is db_auth
Oct 10 11:56:14 172.18.0.1 ui[1081]: 2016-10-10T03:56:14Z [ERROR] [base.go:58]: Error while decoding the json request, error: json: cannot unmarshal bool into Go value of type int

thanks.

**Comment by reasonerjt** [comment]
Are the env A and B has same version of code?  This is may due to some API change between versions.

**Comment by zhaoshouzhong** [comment]
By installing the same code ,The problem has been resolved.
