### ISSUE TITLE
Cannot change settings when there are more than 10 projects

### ISSUE THREAD

**Issue by bergtwvd** [vmware/harbor#865]
Harbor v0.4.0.

When there are more than 10 PUBLIC projects, the project settings for project 11 and beyond are not visible in the GUI. With project settings I mean the options "Repositories | Replications | Users | Logs".

If I make one project in the range 1..10 private than the project settings of project 11 becomes visible,  This is the only work around to get to the settings.

**Comment by reasonerjt** [comment]
I think this is fixed in 0.4.1, could you check?

**Comment by bergtwvd** [comment]
Checked. Fixed in 0.4.1.
