### ISSUE TITLE
anonymous account

### ISSUE THREAD

**Issue by gumby8813** [vmware/harbor#866]
Is there a way to disable anonymous access. In other words public projects are available to those who are registered in Harbor only.

**Comment by gumby8813** [comment]
I believe the issue may be in: service/token/authutils.go
Lines 142-144: 
if strings.Contains(permission, "R") || dao.IsProjectPublic(projectName) {
				a.Actions = append(a.Actions, "pull")
			}

Can anyone confirm whether removing " || dao.isProjectPublic(projectName) " will remove anonymous access. 
Also, will this mean that we have to add all registered users with read access to all public projects?

**Comment by reasonerjt** [comment]
yes, you can try that.

**Comment by reasonerjt** [comment]
@gumby8813 any update? Do you still need this issue open?

**Comment by gumby8813** [comment]
I think you can close it. Thank you.
