### ISSUE TITLE
harbor+ldap configuration,  login error.

### ISSUE THREAD

**Issue by gdonzy** [vmware/harbor#869]
1)Version of docker engine and docker-compose
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

docker-compose version 1.8.1, build 878cff1

2)Config files of harbor, you can get them by packaging "Deploy/config" directory
harbor.cfg file：
## Configuration file of Harbor

#The IP address or hostname to access admin UI and registry service.
#DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
hostname = docker.donzy.me

#The protocol for accessing the UI and token/notification service, by default it is http.
#It can be set to https if ssl is enabled on nginx.
ui_url_protocol = https

#Email account settings for sending out password resetting emails.
email_server = smtp.mydomain.com
email_server_port = 25
email_username = sample_admin@mydomain.com
email_password = abc
email_from = admin <sample_admin@mydomain.com>
email_ssl = false

##The initial password of Harbor admin, only works for the first time when Harbor starts. 
#It has no effect after the first launch of Harbor.
#Change the admin password from UI after launching Harbor.
harbor_admin_password = Harbor12345

##By default the auth mode is db_auth, i.e. the credentials are stored in a local database.
#Set it to ldap_auth if you want to verify a user's credentials against an LDAP server.
auth_mode = ldap_auth

#The url for an ldap endpoint.
ldap_url = ldap://192.168.2.146

#A user's DN who has the permission to search the LDAP/AD server. 
#If your LDAP/AD server does not support anonymous search, you should configure this DN and ldap_search_pwd.
ldap_searchdn = cn=Manager,dc=example,dc=com

#the password of the ldap_searchdn
ldap_search_pwd = donzy

#The base DN from which to look up a user in LDAP/AD
ldap_basedn = ou=People,dc=exapmle,dc=com

#Search filter for LDAP/AD, make sure the syntax of the filter is correct.
#ldap_filter = (objectClass=*)

# The attribute used in a search to match a user, it could be uid, cn, email, sAMAccountName or other attributes depending on your LDAP/AD  
ldap_uid = uid 

#the scope to search for users, 1-LDAP_SCOPE_BASE, 2-LDAP_SCOPE_ONELEVEL, 3-LDAP_SCOPE_SUBTREE
ldap_scope = 3 

#The password for the root user of mysql db, change this before any production use.
db_password = root123

#Turn on or off the self-registration feature
self_registration = on

#Determine whether the UI should use compressed js files. 
#For production, set it to on. For development, set it to off.
use_compressed_js = on

#Maximum number of job workers in job service  
max_job_workers = 3 

#Secret key for encryption/decryption of password of remote registry, its length has to be 16 chars
#**NOTE** if this changes, previously encrypted password will not be decrypted!
#Change this key before any production use.
secret_key = secretkey1234567

#The expiration time (in minute) of token created by token service, default is 30 minutes
token_expiration = 30

#Determine whether the job service should verify the ssl cert when it connects to a remote registry.
#Set this flag to off when the remote registry uses a self-signed or untrusted certificate.
verify_remote_cert = on

#Determine whether or not to generate certificate for the registry's token.
#If the value is on, the prepare script creates new root cert and private key 
#for generating token to access the registry. If the value is off, a key/certificate must 
#be supplied for token generation.
customize_crt = on

#Information of your organization for certificate
crt_country = CN
crt_state = State
crt_location = CN
crt_organization = organization
crt_organizationalunit = organizational unit
crt_commonname = example.com
crt_email = example@example.com
#####

3)Log files, you can get them by package the /var/log/harbor/ 

[log.zip](https://github.com/vmware/harbor/files/523827/log.zip)

**Comment by reasonerjt** [comment]
please also attach the ldapsearch command and result.

**Comment by gdonzy** [comment]
dapsearch -x -D "cn=Manager,dc=example,dc=com" -w donzy -b "ou=People,dc=example,dc=com" -H ldap://192.168.2.146

# extended LDIF
#
# LDAPv3
# base <ou=People,dc=example,dc=com> with scope subtree
# filter: (objectclass=*)
# requesting: ALL
#

# People, example.com
dn: ou=People,dc=example,dc=com
ou: People
objectClass: top
objectClass: organizationalUnit

# ldapuser01, People, example.com
dn: uid=ldapuser01,ou=People,dc=example,dc=com
uid: ldapuser01
cn: ldapuser01
objectClass: account
objectClass: posixAccount
objectClass: top
objectClass: shadowAccount
userPassword:: e2NyeXB0fSQ2JGJqUlZ1QW00JHRVbk11L1BtYUJRYjZIVTNSeTYyRnVVdldCVXZ
 0ekh6WW9yUk1QOUo5eWNMaXdPNTBMS3VJUmt2WTJFc3QzczZPZWIuVC5HSGczenlxbWxIUjFTdG4v
shadowLastChange: 17084
shadowMin: 0
shadowMax: 99999
shadowWarning: 7
loginShell: /bin/bash
uidNumber: 1000
gidNumber: 1000
homeDirectory: /home/guests/ldapuser01

# ldapuser02, People, example.com
dn: uid=ldapuser02,ou=People,dc=example,dc=com
uid: ldapuser02
cn: ldapuser02
objectClass: account
objectClass: posixAccount

the ldapsearch command and part result

**Comment by gdonzy** [comment]
sorry, this is not a bug. harbor.cfg  basedn is wrong. the string "exapmle" is error.

**Comment by reasonerjt** [comment]
ok thanks for the update ,closing.
