### ISSUE TITLE
deploy_ui运行一段时间后establish连接数将会把端口占完,导入habor无响应

### ISSUE THREAD

**Issue by tunnyblock** [vmware/harbor#873]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose
2)Config files of harbor, you can get them by packaging "Deploy/config" directory
3)Log files, you can get them by package the /var/log/harbor/ 

UI容器在获取repository信息的时候会报大量的类似错误
**[repository.go:222]: error occurred while initializing repository client for 064809672/zabbix: Get http://registry:5000/v2/: dial tcp 172.18.0.5:5000: connect: cannot assign requested address**

目前分析大致原因
次获取repository信息，都会创建Response实例，包含一个httpclient，ui界面上的rest请求有数十个，刷新后不会利用已有的连接，没有复用，2连接建立后，并没有手动关闭连接，而是等待golang的垃圾回收机制去回收这个httpclient

docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
root@kvm-003988:/var/log/harbor/2016-10-12#

 docker-compose version
docker-compose version 1.8.0, build f3628c7
docker-py version: 1.9.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
root@kvm-003988:/var/log/harbor/2016-10-12#

**Comment by reasonerjt** [comment]
Hi, are you seeing the issue in latest code?

**Comment by reasonerjt** [comment]
@tunnyblock could you try to reproduce this in latest release?

**Comment by reasonerjt** [comment]
Any update @tunnyblock ?

**Comment by reasonerjt** [comment]
Closing, if you are seeing this again please reopen
