### ISSUE TITLE
[Issue] Log Link Error on Dashboard with One Deleted Project

### ISSUE THREAD

**Issue by yhua123** [vmware/harbor#882]
Step 1: create project: project0001
Step 2: delete the project0001
Step 3: click the log link for project0001 on dashboard
show error like attached pic
![untitled](https://cloud.githubusercontent.com/assets/19166125/19345064/662f03ba-916f-11e6-9215-ddbe2d343175.png)

**Comment by wknet123** [comment]
Fixed by #949
