### ISSUE TITLE
unauthorized: authentication required

### ISSUE THREAD

**Issue by chowyu08** [vmware/harbor#887]
harbor.cfg
![image](https://cloud.githubusercontent.com/assets/16483518/19408723/e0c99d8c-92f6-11e6-907e-7afd0bc15943.png)

harbor deploy success, I can login and access the harbor ui, I create a project "test", but cannot push image to harbor, it seems change to push in docker.io
problem:
![image](https://cloud.githubusercontent.com/assets/16483518/19408720/ca7749c6-92f6-11e6-99f5-30e970fcf9ae.png)

**Comment by guntherboeckmann** [comment]
You must configure nginx and UI properly: 
https://github.com/vmware/harbor/blob/master/docs/configure_https.md
also the Token service:
https://github.com/vmware/harbor/blob/master/docs/customize_token_service.md

**Comment by hainingzhang** [comment]
Not an issue. Please refer to docker and Harbor document for this. Close it for now. Please reopen if needed.
