### ISSUE TITLE
How to use the 'Anonymous' user model with the swagger rest client

### ISSUE THREAD

**Issue by huzhengchuan** [vmware/harbor#888]
I use the harbor in 0.4 version. In the guide, it say 'An anonymous user has no access to private projects and has read-only access to public projects.'. When I visit the api/projects with the python client , which generated by swagger-tools. I not setting the auth_setting in https headers. it response 401 authorize error. I didnot know how to visit harbor in an anonymous user with the swagger-rest-client.

**Comment by hainingzhang** [comment]
even as a anonymous user, you still need to log in as a user of Harbor in order to perform anonymous access. The swagger guide with user login can be found in this link: 
https://github.com/vmware/harbor/blob/master/docs/configure_swagger.md

**Comment by huzhengchuan** [comment]
I Know, Thanks for your help.
