### ISSUE TITLE
Get warning when importing the Harbor OVA with the C# Client

### ISSUE THREAD

**Issue by ywk253100** [vmware/harbor#892]
When you import the Harbor OVA with the C# Client you get the following warning. Not a real issue…
With the vSphere Web Client everything is fine.

![image001](https://cloud.githubusercontent.com/assets/5835782/19434285/195da732-9497-11e6-9acd-ec72bfaadb65.png)

**Comment by ywk253100** [comment]
The OS type is Photon OS, I am not sure if the old C# client can recognize this new OS type. We will check with the corresponding team.

**Comment by reasonerjt** [comment]
Given C# client is deprecated if you can verify the warning is gone on web client, I think we can close this issue.

**Comment by reasonerjt** [comment]
Need to clarify the issue before 0.5.0

**Comment by ywk253100** [comment]
Everything is fine with vSphere web client.

**Comment by ywk253100** [comment]
Fixed.
