### ISSUE TITLE
After delete user from project, you can query the user of project by api "http://xxx/api/projects/{project_id}/members/{user_id}"

### ISSUE THREAD

**Issue by gdonzy** [vmware/harbor#895]
1)Version of docker engine and docker-compose
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

docker-compose version 1.8.1, build 878cff1

2)Config files of harbor, you can get them by packaging "Deploy/config" directory

[harbor.cfg.zip](https://github.com/vmware/harbor/files/535217/harbor.cfg.zip)

3)Log files, you can get them by package the /var/log/harbor/ 

[harbor_log.zip](https://github.com/vmware/harbor/files/535221/harbor_log.zip)

![webwxgetmsgimg](https://cloud.githubusercontent.com/assets/4796689/19463496/20d39266-9527-11e6-8c94-79a6c9942b8e.jpg)

**Comment by reasonerjt** [comment]
We need a testcase for this.

**Comment by gdonzy** [comment]
1. clear environment
2. add a user to  ldap
3. login the user in Harbor web
4. create a project named by "test_project01" in Harbor
5. add a user to "test_project01" project in Harbor
6. delete the user from the project , not delete the user
7. the project_id of the project is {project_id}, and the user_id of the user is {user_id},  when i use the api "https://xxx/api/projects/{project_id}/members/{user_id}",  the status_code returned from the api  is 200.

**Comment by gdonzy** [comment]
src/harbor/api/member.go
100                 //return empty role list to indicate if a user is not a member                                                              
101                 result := make(map[string]interface{})                                                                                      
102                 user, err := dao.GetUser(models.User{UserID: pma.memberID})     

I think this may be the reason of the problem.

**Comment by reasonerjt** [comment]
you hope it return 404?

**Comment by gdonzy** [comment]
I think the user is not member of the project. The 200 isn't bright.

**Comment by reasonerjt** [comment]
but if returns 404 it's ambiguous regarding if the project does not exist or the member is not part of the project?

**Comment by gdonzy** [comment]
this situation is relatively rare, but i find one in harbor docs.
![404](https://cloud.githubusercontent.com/assets/4796689/19468587/c576e436-9549-11e6-932b-718831403608.png)

**Comment by ywk253100** [comment]
Fixed by #955 .
