### ISSUE TITLE
How Can I docker pull the images directly without run docker login command

### ISSUE THREAD

**Issue by chjhaijiang** [vmware/harbor#908]
I had created the harbor successfully.
However, the problem I met is: How Can I docker pull the images directly without run docker login command?
I assume the anonymous user is designed for this, but I didn't know how to make it works?

**Comment by reasonerjt** [comment]
create a public project, and anonymous user can pull image under any public projects.

**Comment by chjhaijiang** [comment]
I am already create the public project., but it still did not work for me until docker login is runed.
![project](https://cloud.githubusercontent.com/assets/3355018/19556393/8195fdd2-96f3-11e6-8e8f-a1adf47357e7.png)

**Comment by reasonerjt** [comment]
Please confirm this is public?

**Comment by chjhaijiang** [comment]
Thanks, the project is public. The cause is the harbor I built didn't use https protocol instead of http. I had to add --insecure-registry <IP address> in my docker config.

**Comment by reasonerjt** [comment]
Thanks, I'm closing the issue.
