### ISSUE TITLE
Proposal: Integrate Clair for analyzing image vulnerability

### ISSUE THREAD

**Issue by supereagle** [vmware/harbor#914]
[Clair](https://github.com/coreos/clair) is a tool to analyze the vulnerabilities of docker images. It gets the vulnerabilities of the image by analyzing the features and their vulnerabilities added by each layer. In Harbor, each layer of the images can be sent to Clair server to analyze when they are pushed, and show their vulnerabilities in the UI.

There are two ways to integrate Clair:
- Configurable Clair server url
  If the Clair server url is configured, each layer will be analyzed when the image is pushed, otherwise will has no vulnerability analysis. 
- Clair as component of Harbor
  Integrate Clair as component of Harbor, and start it with Harbor by docker-compose. As the Clair server need to track an upstream vulnerability database and imports them into Clair, so the deployment machine should be able to connect to the Internet.

WorkItems:
- [x] Read Clair server url from config
- [x] Analyse image when receive notification of pushing images
- [x] Get vulnerabilities when view image details
- [ ] Show vulnerabilities in UI (Not familiar with AngularJS, need help)
- [ ] Test and add test cases

**Comment by reasonerjt** [comment]
we have plan to enable vulnerability scan, but need to focus on other work in recent weeks/months, thanks for the advice.

**Comment by supereagle** [comment]
I have spent some time to investigate Clair and done some practices to integrate it in past weeks. If your are ok, I think I have time and am glad to contribute to this function.

**Comment by reasonerjt** [comment]
Sure, but could you let me see how it works on your forked repo?  Currently we are not ready for a huge PR.

**Comment by supereagle** [comment]
Ok, I will do this work in my forked repo. After it is ready, I will ping you.

**Comment by sboulkour** [comment]
Hey @supereagle 
Did you progress as expected in the integration of clair with harbor ?

**Comment by supereagle** [comment]
@sboulkour  The work is on going, but the progress is a little slow as I'm busy recently.

**Comment by supereagle** [comment]
@reasonerjt   I have finished most work of the integration Harbor with Clair in [my forked repo](https://github.com/supereagle/harbor/tree/clair). PTAL.

**Comment by jryberg** [comment]
@supereagle, do you have any update? This is *VERY* useful and it would be great to have this feature implemented. 

Regards Johan

**Comment by supereagle** [comment]
Sorry. My PR #1260 has been closed, now I am not sure how this feature will be implemented. Maybe you can subscribe issue #2042 for updates.

**Comment by reasonerjt** [comment]
Closing this issue and the progress will be tracked by #2042
