### ISSUE TITLE
Cannot assign bridge IP address after Harbor start

### ISSUE THREAD

**Issue by rootsongjc** [vmware/harbor#92]
After I start harbor, docker will create a bridge with IP 172.17.0.1 automatically. How can I assign the IP by myself?
I have a host will IP 172.17.1.42  can't access the harbor.

**Comment by ywk253100** [comment]
You can modify harbor/Deploy/docker-compose.yml to configure the default network used by Harbor before starting it.

1) Add the following code to the end of docker-compose.yml (replace the 172.28.0.0/16 with your own subnet )

``` networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
```
2) Delete the old network and containers created previously
```
docker network rm deploy_network  
docker-compose rm
```
3) Start Harbor
```
docker-compose up -d
```

References:
https://docs.docker.com/compose/networking/#configuring-the-default-network
https://docs.docker.com/compose/compose-file/#ipam

**Comment by rootsongjc** [comment]
@ywk253100 Thanks, it works! This is my config.
networks:
  default:
    ipam:
      driver: default
      config:
      - subnet: 172.28.0.0/16
