### ISSUE TITLE
There is some errors when migrate my harbor.

### ISSUE THREAD

**Issue by yujianglei** [vmware/harbor#936]
I use HTTP protocol to access my harbor  before migration.  And now I replace the harbor.cfg.  but appear errors.

Harbor.cfg:
ui_url_protocol = http

when I execute ./prepare script on Deploy directory, Follow logs:
Traceback (most recent call last):
  File "./prepare", line 37, in <module>
    validate(rcp)
  File "./prepare", line 22, in validate
    if len(conf.get("configuration", "secret_key")) != 16:
  File "/usr/lib64/python2.7/ConfigParser.py", line 340, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option u'secret_key' in section: u'configuration'

**Comment by reasonerjt** [comment]
How did you replace harbor.cfg?  with "git pull" ??
In the latest code of prepare and harbor.cfg on dev branch we removed secret_key

**Comment by yujianglei** [comment]
Manual backup  harbor.cfg  thar  old version .  and  I migrate harbor by refered to  the url (https://github.com/vmware/harbor/blob/master/docs/migration_guide.md)

**Comment by reasonerjt** [comment]
If you are on "master" branch, the harbor.cfg should have "secret_key" parm, could you confirm with the previous version?

**Comment by yujianglei** [comment]
It's OK.   THANKS. @reasonerjt
