### ISSUE TITLE
Appear errors when create new project

### ISSUE THREAD

**Issue by yujianglei** [vmware/harbor#941]
## Follow logs:

> Oct 25 16:31:04 172.18.0.1 ui[24188]: 2016-10-25T08:31:04Z [ERROR] [base.go:58]: Error while decoding the json request, error: json: cannot unmarshal bool into Go value of type int
> Oct 25 16:31:05 172.18.0.1 ui[24188]: 2016-10-25T08:31:05Z [ERROR] [base.go:58]: Error while decoding the json request, error: json: cannot unmarshal bool into Go value of type int
> Oct 25 16:31:06 172.18.0.1 ui[24188]: 2016-10-25T08:31:06Z [ERROR] [base.go:58]: Error while decoding the json request, error: json: cannot unmarshal bool into Go value of type int

**Comment by reasonerjt** [comment]
This is a fixed bug, please use the latest release 0.4.1

**Comment by yujianglei** [comment]
ok

**Comment by hainingzhang** [comment]
Close it for now. Please reopen if needed.

**Comment by xiaoping378** [comment]
release 0.4.5 also have this issue.
