### ISSUE TITLE
Docs are not updated

### ISSUE THREAD

**Issue by supereagle** [vmware/harbor#944]
Can not find `docker-compose.yml.daocloud` according to the doc [image_pulling_chinese_user.md](https://github.com/vmware/harbor/blob/master/docs/image_pulling_chinese_user.md)

**Comment by supereagle** [comment]
@reasonerjt Is this doc used anymore? If not, maybe we can remove it.

**Comment by reasonerjt** [comment]
Thanks for pointing out, will remove it.  For now if you don't want to pull images from docker hub you can use the offline installer.
