### ISSUE TITLE
"Failed to list user data" if user is unset administrator 

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#959]
1. add user "daniel" and promote it to "system admin"
2. login daniel in another computer, and swtich to "admin option"
3. turn off the admin in the browser in step 1.
   4.refresh browser in step 2.

see error: "Failed to list user data"

**Comment by reasonerjt** [comment]
likely a dup of #906

**Comment by wknet123** [comment]
Fixed with #974
