### ISSUE TITLE
Couldn't  register with a username used by a deleted user in harbor.

### ISSUE THREAD

**Issue by tuxknight** [vmware/harbor#96]
Couldn't  register with a username once was used by a deleted user in harbor.

What I saw in database was 

```
mysql> select user_id,username,deleted,reset_uuid from user;
+---------+-----------+---------+------------+
| user_id | username  | deleted | reset_uuid |
+---------+-----------+---------+------------+
|       1 | admin     |       0 | NULL       |
|       2 | anonymous |       1 | NULL       |
.................
|       4 | jenkins79 |       1 | NULL       |
+---------+-----------+---------+------------+
```

**Comment by reasonerjt** [comment]
This is currently a limitation that due to audit purpose we use a flag to mark deleted users. such that the audit log is trackable via user's id.

**Comment by bobbyjunzhang** [comment]
We can see if we can remove the limitation by having user_id as the key, instead of username.

**Comment by reasonerjt** [comment]
user_id **is** the key but then you'll see "**John Doe**" to represent different users on UI and in audit logs.

**Comment by hainingzhang** [comment]
Because we have to audit each user's operations, Harbor does not allow recreate a user with the same user id.
