### ISSUE TITLE
Error in make install

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#973]
/usr/local/bin/docker-compose -f /root/gows/src/github.com/vmware/harbor/make/docker-compose.dev.yml up -d  
ERROR: .IOError: [Errno 2] No such file or directory: '/root/gows/src/github.com/vmware/harbor/make/docker-compose.dev.yml'

Seems it generated docker-compose.yml not docker-compose.dev.yml

**Comment by yhua123** [comment]
need merge #958
