### ISSUE TITLE
Support for SSH enable - OVA/OVF option/log bundle/config files collection from Harbor UI

### ISSUE THREAD

**Issue by mobla** [vmware/harbor#990]
If you are reporting a problem, please make sure the following information are provided:
1) VIC - Build#6402 (client machine Photon, Docker v1.11.2 and compose v1.8.0
2) Harbor build 0.4.5 beta

It would be nice to have 
a. enable-SSH option during Harbor deploy OVA or from Admin UI for trouble shooting.
b. collect log bundles, configuration files from Harbor Admin UI would also be nice (as we have in VIC admin portal).

Please close it as dup if we have already have this filed!

Thanks,
Murali

**Comment by reasonerjt** [comment]
Let's provide a script to collect logs and configuration files.

**Comment by reasonerjt** [comment]
@ywk253100 please provide some re-usable function because during upgrade we need to backup the configuration files also. (not logs)

**Comment by reasonerjt** [comment]
as for a), we think there's security risk. @hainingzhang please chime in.

**Comment by ywk253100** [comment]
Fixed by #1030 .
