### ISSUE TITLE
Harbor appliance is always setting/preferring "IP address" as hostname in harbor.cfg

### ISSUE THREAD

**Issue by mobla** [vmware/harbor#995]
Harbor Build: 0.4.5
Steps:
1. Follow https://github.com/vmware/harbor/blob/master/docs/installation_guide_ova.md  - with DHCP
2. Boot the Harbor appliance
3. Identifier of the machine "hostname" in harbor.cfg is always set to IP address. Harbor must prefer Hostname as primary network identifier

[logs.tar.gz](https://github.com/vmware/harbor/files/565743/logs.tar.gz)
[config.tar.gz](https://github.com/vmware/harbor/files/565742/config.tar.gz)
Otherwise the https certs will have to be generated using IP address as SAN. Ideally Harbor should trust both FQDN and IP address (IP can be specified as SAN) along with FQDN in subject CN 

https://github.com/vmware/harbor/blob/master/docs/installation_guide_ova.md to use SSL Cert: & SSL Cert: Key

**Comment by ywk253100** [comment]
Fixed by #1058 .
